### ISSUE TITLE
Install Cost Management Operators in GOLD

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1000]
**Describe the issue**
Platform Services Team would like to have crost management operators installed in Silver cluster

https://www.redhat.com/en/blog/introducing-openshift-cost-management-human-readable-view-cloud-native-application-costs

**Additional context**
Cost Management service for Openshift will allow us to get more insight into application cost.

**Definition of done**
Install and enable the cost management parts on the GOLD cluster a per instruction here 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/getting_started_with_cost_management/assembly_adding_sources_cost#installing_cost_mgmt-operator

**Comment by StevenBarre** [comment]
Already handled by CCM.

![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/6e566fa3-cdd1-46ee-b639-b99783251bc5)
