### ISSUE TITLE
2021Q2 Upgrade SILVER

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1007]
Upgrade to 4.6

**Comment by StevenBarre** [comment]
Apr 25th - CHG0025039 - MCS SILVER - 2021 Q2 Patching - Registry Hard Prune
Apr 26-30 CHG0025038 - MCS SILVER - 2021 Q2 Patching - Upgrade to OCP 4.6.21

**Comment by wmhutchison** [comment]
Closing this off. LLDPAD is malfunctioning but is not an integral part of OCP 4.6 upgrade.  May end up removing it for the time being.
