### ISSUE TITLE
2021Q2 Upgrade GOLD

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1008]
Upgrade to 4.6

**Comment by StevenBarre** [comment]
May 9th - CHG0025136 - MCS GOLD - 2021 Q2 Patching - Registry Hard Prune
May 10-14 CHG0025140 - MCS GOLD - 2021 Q2 Patching - Upgrade to OCP 4.6.21

**Comment by wmhutchison** [comment]
RFC executed this week to upgrade GOLD to 4.6.25. Will close off at the end of the week if no issues are seen.
