### ISSUE TITLE
2021 Q2 OCP4 Patching

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1009]
**Describe the issue**
Upgrade all the clusters in Q2.

**Additional context**
Likely moving to 4.6.latest

**Definition of done**
All clusters upgraded to pick up security fixes.

**Comment by wmhutchison** [comment]
Creating a new issue that will be associated with this Epic. 2021Q2 Upgrade 3.11 clusters.

While the general intent is to avoid OS patching for 3.11 LAB and PROD, those servers were built with Advanced Soluitions gold image build, which means it falls under the auspices of how we manage servers within the Hosting Contract, and thus we are required to patch them quarterly unless decommissioned.

Setting the go/no-go date of the next MCS Governance Prep meeting (June 11th) for us to make the call if we need to trigger OS patching RFCs for 3.11 LAB and PROD. Other maintenance work will also come up as well (3PAR Storage migration).

**Comment by wmhutchison** [comment]
With 3.11 OS patching exempted for Q2, we can officially close this Epic as done.
