### ISSUE TITLE
Sysdig - Investigate PVC consumption metric scraping

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#1015]
**Describe the issue**
Sysdig PVC consumption metrics (%used, etc) are not tracked consistently, investigate sysdig options to improve filesystem metric gathering.

**Additional context**
Ideas to investigate:
- k8s_extra_resources config? - https://docs.sysdig.com/en/enable-kube-state-metrics.html
- Remote FS metrics? - https://docs.sysdig.com/en/collect-metrics-from-remote-file-systems.html

**Definition of done**
- [ ] consistent collection of PVC usage metrics
- [ ] documentation for sysdig teams on where to find PVC usage metrics
- [ ] updates to sysdig-teams default dashboards (if possible/required)

**Comment by ShellyXueHan** [comment]
### Updates:

After some investigation we found out the following:
- PVC metrics (including utilization) is part of kubelet service metrics
- kubelet metrics come from prometheus
- the current process filter for kubelet does not match, which result in no metrics scraped by sysdig

So far we've tested the update in klab and clab, PVC dashboard is able to return template metrics. Will keep ticket open until changes are pushed to production clusters.

**Comment by ShellyXueHan** [comment]
Verified in Silver cluster that PVC metrics are showing up no problem. App teams also able to verify the default storage template working under their team scope. Closing
