### ISSUE TITLE
sysdig agent - disconnect events

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1019]
**Describe the issue**
We are getting lots of Issue Events `Infra Connectivity` from silver nodes. However there is only node connection issue event but no reconnect events. Need to investigate.

**Additional Context**
Ideally an application dashboard can be configured to track and alert on sysdig_agent issues - in this case, an alert for when a specific cluster has less than the expected # of connected agents (for X duration).

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done
- [ ] investigate into the issue
- [ ] resolve problem

**Comment by mitovskaol** [comment]
@ShellyXueHan Are the issues still happening?

**Comment by ShellyXueHan** [comment]
yes it's still happening. will investigate.

**Comment by ShellyXueHan** [comment]
### Update:

We've confirmed that this is caused by Sysdig agent pods running out of resource. They are given 2 cores request and 4 cores limit for CPU resource, which is recommended by Sysdig support. Increasing the resource last time worked, but many pods are hitting the request level now. This again cause the event issue.

A new ticket has been created to get some help looking into sysdig agent pod utilization. Reason for this is that we cannot simply increase the CPU resource as needed, considering there are more than 50 nodes in silver.

Will update once hear back!

**Comment by ShellyXueHan** [comment]
### Update:

Found doc on resource adjustment and updated accordingly. Events are returned now. closing
