### ISSUE TITLE
sysdig agent - disconnect events

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1020]
**Describe the issue**
We are getting lots of Issue Events `Infra Connectivity` from silver nodes. However there is only node connection issue event but no reconnect events. Need to investigate.

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done
- [ ] investigate into the issue
- [ ] resolve problem

**Comment by jefkel** [comment]
Duplicate of #1019
