### ISSUE TITLE
As platform service team, I'd like to make openshift namespace metadata available automatically

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#103]
There are project related metadata on each namespace. We currently have scripts to generate a csv file that sort and include the metadata. However, we'd like to have it automatically updated and available to the team for reporting purpose.

**Comment by ShellyXueHan** [comment]
Update:
- Ansible playbook: https://github.com/BCDevOps/platform-services/tree/master/tools/audit/repo-mapper/ansible
- service account: https://github.com/bcgov-c/devops-platform-operations-docs/blob/405249976cab5f9e3cb4f53bfeb25effbaad749a/rbac/clusterrolebinding-project-meta-viewers.yaml


Consider a cronjob to run the playbook and make the generated csv file available, in one of the ways:
- minio
- email
- api request

**Comment by mitovskaol** [comment]
@ShellyXueHan No specific way , maybe email it to me on  a weekly basis ? Or generate it somewhere where I can download it. Also , it can be on demand script that generates it , it doesn’t have to be a scheduled cron job unless it is needed for something else.

**Comment by jefkel** [comment]
I would suggest storing in pod (ephemeral) and having a specific link to download it.  (perhaps auth'd via openshift creds for the namespace.)

Can cron to re-generate daily, and have it generate on startup.. then you can get away with a single replica deployment.

Could get even fancier, but with an expected timeout for the first minute or so when you hit your URL:
deployment of a pod:
 - pod generates CSV for auth'd download via a URL
 - waits "x" hours and then uses oc idle to idle itself.

**Comment by ShellyXueHan** [comment]
I like oc idle rather than a cronjob which might consume more resource. @mitovskaol  So how about a quick mvp with what Jeff suggested. Then the second phase for sending to email and on demand request?

**Comment by mitovskaol** [comment]
@ShellyXueHan I like Jeff's suggestion, I would prefer on-demand download - this way I can always download the list when I need it and it won't clutter my email.

**Comment by ShellyXueHan** [comment]
@mitovskaol sure, i'll look into using ansible webhook so that you could trigger it on demand.

We could then need something to guard it once we open up the endpoint, like auth code or integrate authentication flow. @jefkel I'd like to go through some thoughts with you, can we have a quick discussion on this?

**Comment by jefkel** [comment]
If you are able to implement the `oc idle <servicename>` approach, then you don't need a webhook.  Quick and dirty pod flow logic I'm thinking of:
![OnDemand1](https://user-images.githubusercontent.com/22400069/78807551-16dff080-7979-11ea-854b-1cacc64afc4d.png)

For Authentication, you can use the config in the Jenkins pod to leverage openshift's built in auth (and can control access via view permission in the namespace)

**Comment by ShellyXueHan** [comment]
app available here: https://repo-mapper-static-devhub-tools.pathfinder.gov.bc.ca
