### ISSUE TITLE
Adapt Rocket Chat to use GitOps

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1031]
Rocket chat should be updated to be GitOps focused so that updates and deployments are made via changes to the GitHub repository and not by manually doing build and running OCP templates. As part of this ticket, R.C needs to be built and deployed automatically so that all hot-fixes are automatically picked up.

**Comment by jleach** [comment]
I think ArgoCD isn't quite ready for this so I'm going to move it back to the backlog until ArgoCD is ready for me to proceed.

**Comment by jleach** [comment]
Converted R.C to use Kusomize. ArgoCD is a little over loaded so the final step of using ArgoCD to deploy RC et al is paused until performance issues are resolved.

**Comment by IanKWatts** [comment]
This is done.  RocketChat has been adapted for use with Argo CD and is under Argo CD control in all three namespaces.  Pipelines have been updated with automation for builds, tests, deployments, and promotions.
CC: @lukegonis
