### ISSUE TITLE
Object Store Integration with Artifactory FileStore Info Gathering

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#104]
Once an Object store bucket is available for production use, we need to evaluate the following:

Can we separate which repositories use object storage and which do not?
- Which Repositories should have object store storage? (potentially no caching repos?)

How much local (staging/caching) storage is needed?

What is the staging -> Object storage maintenance schedule?

**Comment by caggles** [comment]
I'm removing the step to figure out the migration path from our current file storage system to integrating with object store - this is being moved to a different ticket.

**Comment by caggles** [comment]
This ticket is a duplicate.
