### ISSUE TITLE
Mobile Singing Service - issue with downloading signed package

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1044]
**Describe the issue**
Request timeout when downloading package from signing agent.

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by jleach** [comment]
Work completed. Issue appears to be slow VPN access to the BCNGN. Shelly did some tests and it took 20min on VPN or ~2min when not on BCNGN.
