### ISSUE TITLE
Sysdig configuration tuning for infra nodes

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#1045]
**Describe the issue**
Sysdig agents running on the infrastructure nodes in the clusters are generating a lot of error messages regarding elastisearch metric gathering.  The sysdig agent can collect elastisearch metrics directly via the *app_check* configuration section with some adjustments to ensure it can connect appropriately.  Alternatively, the elastisearch *app_check* metric gathering can be disabled on the infra nodes (if gathering is not required).  This will reduce the ongoing log message generation.

**Additional context**
Specific link to elastisearch app_check configuration documentation: https://docs.sysdig.com/en/elasticsearch.html

**Definition of done**
- [ ] Elastisearch error messages in logs are resolved via updated configuration for elastisearch app_check
- [ ] Configuration changes rolled through all sysdig deployments. (CLAB, KLAB, SILVER, GOLD)

**Comment by mitovskaol** [comment]
@ShellyXueHan  Is this still relevant?

**Comment by ShellyXueHan** [comment]
yes! still need to look into this when time allows.

**Comment by ShellyXueHan** [comment]
capture in an open ticket with sysdig, will work on once it when we upgrade to latest version.

**Comment by ShellyXueHan** [comment]
configuration changes pushed already. closing
