### ISSUE TITLE
Use MTC to migrate CRD bike count application from OCP3 to OCP4 (silver).

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1046]
Use the MTC to migrate the CRD Bike Count Application from OCP3 to OCP4. This project does have a vanity URL so DNS updates are required. When migrated advise the PO of what the new generic URL is for prod.

- [x] Create project setup on OCP4 with the same licence plate based name as OCP3;
- [x] Run the MTC playbook to build the plan and trigger the migration;
- [x] Add existing users with same roles to access the namespace;
- [x] Advise PO the migration is done and the DNS can be updated;
- [ ] Submit request to have old namespace set decommissioned;
- [ ] Update PO and/or TC as needed in the registry.

**Comment by jleach** [comment]
@wmhutchison 

Please run the "migrate.yaml" playbook located [here](https://github.com/bcgov/mtc-scripts) to create a Migration Toolkit for Containers (MTC) migration of the CRD Bike Count project. It will need the following arguments:

`ansible-playbook migrate.yaml -e "name=bikecount key=gvzrts"`

**NOTE** the playbook switches between clusters, first going to the source cluster to lookup PVCs then to the destination cluster to create the actual migration in `openshift-migrations`. You will need to have two contexts named after the source and destination cluster.

Cc: @StevenBarre

**Comment by StevenBarre** [comment]
Looks like the playbook doesn't handle when the source projects have no volumes. 

```
TASK [plan : Build and apply manifest to the cluster] *********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to create object: \"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"MigPlan.migration.openshift.io \\\"bikecount-plan\\\" is invalid: spec.persistentVolumes: Invalid value: \\\"null\\\": spec.persistentVolumes in body must be of type array: \\\"null\\\"\",\"reason\":\"Invalid\",\"details\":{\"name\":\"bikecount-plan\",\"group\":\"migration.openshift.io\",\"kind\":\"MigPlan\",\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: \\\"null\\\": spec.persistentVolumes in body must be of type array: \\\"null\\\"\",\"field\":\"spec.persistentVolumes\"}]},\"code\":422}\n", "reason": "Unprocessable Entity", "status": 422}
```

**Comment by StevenBarre** [comment]
Playbook fixed and ran. Migration Plan completed.

**Comment by jleach** [comment]
Waiting on DNS changes to go through.
