### ISSUE TITLE
Explore Vertical Pod Autoscaler usage in Klab

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1049]
**Describe the issue**

VPA has been enabled on KLAB, we need to try it out based on RedHat's recommendation and see how it fits into our use case.

Ref:
- https://github.com/BCDevOps/developer-experience/issues/992
- https://docs.openshift.com/container-platform/4.5/nodes/pods/nodes-pods-vertical-autoscaler.html

**Definition of done**

- [x] Install Operator in KLAB
- [x] Configure Operator if needed
- [x] Perform tests with stakeholders

**Comment by wmhutchison** [comment]
Will need to spend some time reviewing this so as to get familiar with the technology involved.

**Comment by wmhutchison** [comment]
Moving to Sprint Backlog for now. Some business interest expressed here for this coming Sprint, so will need to find time for this.

**Comment by StevenBarre** [comment]
Operator was installed in labs back in March via https://github.com/bcgov-c/platform-gitops-gen/pull/105

It is still in Tech Preview however. I've ensured its updated in the labs for further testing.
