### ISSUE TITLE
Document requirements for the custom AG RBAC in Openshift 4

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1050]
When a new project is provisioned in Openshift 4, the PO and Tech Lead listed on the provisioning request are granted  the Openshift `admin` role with full control over the namespace and the ability to grant access to other users. 
As defined [here](https://docs.openshift.com/container-platform/4.5/authentication/using-rbac.html#viewing-local-roles_using-rbac) - `If used in a local binding, an admin has rights to view any resource in the project and modify any resource in the project except for quota.`

AG needs to separate user access provisioning within a namespace from development work within the namespace. This requirement can be satisfied by creating 2 custom role bindings that will be used in all AG projects.

Custom role binding #1:
- `user access provisioning admin` is a reduced RBAC from the standard local `admin` role that only inlcudes the ability to add/remove users in namespaces.

Custom role binding #2:
- 'developer' role is a reduced RBAC from the standard `edit` role that excludet the ability to manage secrets (viewing secrets is Ok but no ability to add/remove/modify).

The namespaces would still have a full `admin` role assigned to them at the time of the provisioning and this role will be responsible for setting up secrets where this cannot be automated through the Registry.

**Comment by rloisell** [comment]
I think there would be 3 custom role bindings - you are missing one that is between Edit and Admin. 

Also, this is more than an AG requirement, in theory all ministries need to adhere to the same policy in regards to user provisioning, we (AG/PSSG) just strive to meet this audit requirement.

**Comment by mitovskaol** [comment]
@rloisell  Can you please describe in more detail the type of access this 3d role would need to have?

**Comment by rloisell** [comment]
The three roles:

1) User Admin - is a reduced RBAC from the standard local admin role that only includes the ability to add/remove users in namespaces.
2) Developer Admin - can set secrets, provision service accounts, setup environments aside from User provisioning. (Lead Dev on project)
3) Developer Edit - role is a reduced RBAC from the standard edit role that excludes the ability to manage secrets (viewing secrets is Ok but no ability to add/remove/modify). (Most Dev on project). 

Does that make sense?

**Comment by mrobson** [comment]
@rloisell @mitovskaol can you point me towards some details as to what devs need to do w/ service accounts within your use cases?

They need to create them?
They need to be able to assign roles to the SAs they create?

**Comment by WadeBarnes** [comment]
@mrobson, Here is a script that performs the "standard" initialization for a project set.  This would be run by the `Developer Admin` role (as @rloisell calls it); [initOSProjects.sh](https://github.com/BCDevOps/openshift-developer-tools/blob/master/bin/initOSProjects.sh)

Summary of the general operations that need to be performed:
- Grant services accounts permissions to pull (deploy) images from the `tools` namespace.
- Grant the CI/CD (i.e. Jenkins, etc) permissions to manage rollouts, etc.
- Provision pull secrets for Artifactory and/or other repositories, and grant the appropriate service accounts permission to use them.

**Comment by mrobson** [comment]
Thanks - so you don't really need to create new SAs, which edit can do, you primarily need to modify rolebindings and create/link secrets.

Based on what your script does, it appears that you only need to modify rolebindings on the tools namespace - so you only need an "admin" level user in tools and "edit" for dev / test / prod. I am not sure what else you may be doing that could change this view.

grantDeploymentPrivileges:
oc policy add-role-to-user for system:image-puller ....... for all 3 namesapces to tools

assignRole:
oc policy add-role-to-user for edit ....... for jenkins to tools

buildPullSecret:
oc create secret docker-registry
oc secrets link default / builder to the new secret in the namespace

So you could have:

1) user admin role that can manage rolebindings in all 4 namespaces and nothing else
2) developer user admin role that can a manage rolebindings in tools + what ever else you want
3) developer admin that can manage secrets in all 4 namespaces + what ever else you want
4) developer role with the reduced edit that can not manage secrets

This gives you good separation of roles and, in addition, makes it easier to trace audit logs for what these users have been doing.

**Comment by NickCorcoran** [comment]
Email sent to @rloisell to continue conversation and determine next steps.  To document here once discussed.

**Comment by mitovskaol** [comment]
@rloisell @NickCorcoran Can we please post the final result of your discussion in this ticket for further planning and implementation. Thanks!

**Comment by michaelshire** [comment]
Other than the OpenShift CLI and the OpenShift Console GUI, are you using any other tools that report or modify a project/namespace rolebindings?

**Comment by michaelshire** [comment]
@rloisell @NickCorcoran 
```
1) User Admin - is a reduced RBAC from the standard local admin role that only includes the ability to add/remove users in namespaces.
2) Developer Admin - can set secrets, provision service accounts, setup environments aside from User provisioning. (Lead Dev on project)
3) Developer Edit - role is a reduced RBAC from the standard edit role that excludes the ability to manage secrets (viewing secrets is Ok but no ability to add/remove/modify). (Most Dev on project).
```
For 2) does the standard "edit" role have the appropriate permissions?
- serviceaccounts [create, delete, deletecollection, get, list, patch, update, watch]
- secrets [create, delete, deletecollection, get, list, patch, update, watch]
- rolebindings [ <none> ]

**Comment by mitovskaol** [comment]
@michaelshire We built our own custom provisioner with ArgoCD that create admin role bindings for the namespaces in Openshift at the time of provisioning and assigns them to the Techical Leads and Product Owner listed on the provisioning request in the Project Registry (linked to their GitHub ID). The sync that the provisioner runs allows to update admin users in the project namespaces if the Tech Lead/PO changes in the Project Registry. When this happens, the old user(s) are removed from the namespaces and the new user(s) added as admins. This only applies to the special role bindings that are created by the ArgoCD provisioner and does not apply to the role bindings created by an admin user manually.  Please feel free to reach out to @j-pye for more details.

**Comment by michaelshire** [comment]
@rloisell @NickCorcoran

For 1) I've tested this in my own lab environment.  The role requires the ability to create and list role bindings.  If this is acceptable, there is a functional solution, will work with @j-pye on implementing into the provisioning process.

`
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # name of the cluster role to be used in the rolebinding
  name: user-admin
rules:
  # permit list and create on the rolebinding API
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create", "list"]
  #permit bind on the clusterrole API
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["bind"]
  # limit rolebindings to the following resourceNames (or omit to allow binding any ClusterRole)
  resourceNames: ["admin","edit","view"]
`

**Comment by michaelshire** [comment]
[https://app.zenhub.com/files/220104031/0d5bd9ba-82e1-419d-ae8f-399335bc6b54/download](https://app.zenhub.com/files/220104031/0d5bd9ba-82e1-419d-ae8f-399335bc6b54/download)

Attached is the "devedit" clusterrole to satisfy 3).  It is a copy of the edit role, with the permissions to modify (create, delete, deletecollection, patch, update) removed for the secrets API.

*Lightly* tested in my environment.

**Comment by NickCorcoran** [comment]
@michaelshire @j-pye no objections in suggested naming for new roles.  Propose we create roles on CLAB and test out there.
Once tested, I can schedule a meeting w/ AG architects and select devs to demo.

**Comment by j-pye** [comment]
@NickCorcoran Would you like that done as apart of this ticket or should i create an implementation ticket? 

I'm thinking I'll just add it to CCM and limit it to the labs for now if that work for you.

**Comment by NickCorcoran** [comment]
@j-pye Yes, lets create a new ticket for implementation and close this one.

Thanks!
