### ISSUE TITLE
Use MTC to migrate the Capstone application from OCP3 to OCP4 (silver)

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1052]
Use the MTC to pilot migrating a project from OCP3 to OCP4. This project does not have a vanity URL so no DNS updates are required. When migrated advise the PO of what the new generic URL is for prod.

- [x] Create project setup on OCP4 with the same licence plate based name as OCP3;
- [x] Run the MTC playbook to build the plan and trigger the migration;
- [ ] Add existing users with same roles to access the namespace;
- [ ] Advise PO the migration is done and what the new URL is;
- [ ] Submit request to have old namespace set decommissioned;
- [ ] Update PO and/or TC as needed in the registry.

**Comment by jleach** [comment]
Use the MTC to pilot migrating a project from OCP3 to OCP4.

**Comment by jleach** [comment]
Please review and run the "migrate.yaml" playbook located (here)[] to create a Migration Toolkit for Containers (MTC) migration of the Capstone project. It will need the following arguments:


`ansible-playbook migrate-yaml -e "name=capstone key=xordpe"`

**Comment by StevenBarre** [comment]
Migrated to Silver with

>Final Restore openshift-migration/capstone-migration-xvkbx: partially failed on destination cluster

which was the same as seen in KLAB.

Made some minor tweaks to the playbooks.

**Comment by jleach** [comment]
@StevenBarre Appreciated. Ty.
