### ISSUE TITLE
Migrate round 4 nodes from PROD 3.11 to SILVER

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#1057]
**Describe the issue**
Nodes 187, 188, 189, & 190 need to be drained and decommissioned. Then have their network switch ports changed.

**Definition of done**
- [x] CHG to drain the nodes of workload
- [x]  CHG to remove the nodes from the cluster and decommission them
- [x] Work with network team to ensure new network switchports are configured and ready
- [x] Validate nodes
- [x] Remove cordon and quarantine from nodes and add to the worker pool
- [x] CHG to officially hand over nodes

**Comment by tbaker1313** [comment]
Node have been drained and decommissioned. Networks is configuring the switchports soon.

**Comment by tmorik** [comment]
All 4 new nodes below have been added to the silver cluster and set up. They are handed over to the customer by the standard change **CHG0024682**

- MCS-SILVER-APP-22.dmz - RITM0086351

- MCS-SILVER-APP-23.dmz - RITM0086352

- MCS-SILVER-APP-24.dmz - RITM0086353

- MCS-SILVER-APP-25.dmz - RITM0086354
