### ISSUE TITLE
Artifactory Operator repo permissions

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#106]
## Problem:
Repository Permissions and Groups not working as we would like with the automation.

(Placeholder for more detail)

**Comment by jefkel** [comment]
Quick links:
Update permission object: 
*key is that "manage" permission holders can only modify the "actions" section*
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API+V2#ArtifactoryRESTAPIV2-GetPermissionTargetDetails

Sample permission object: 
https://www.jfrog.com/confluence/display/RTF/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json

**Comment by caggles** [comment]
Permissions management API has had a major upgrade with v7.

**Comment by jefkel** [comment]
> Permissions management API has had a major upgrade with v7.
are doc links available?

**Comment by caggles** [comment]
Closing as no longer relevant, given the new operator.
