### ISSUE TITLE
Load Testing Follow-up: Additional Error Testing

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#1069]
**Describe the issue**
During the initial load test on Artifactory to check on the path method for docker URLs, a few errors showed up. There weren't very many (around a rate of 0.25%), but we should look into the reasons why these rare errors occurred to see if there's anything we can do about them.

**Additional context**
https://github.com/BCDevOps/developer-experience/pull/1014

**Definition of done**
- [ ] A new load test performed using the same script as before
- [ ] Records of what these errors actually are
- [ ] Possible fixes for these errors, where possible.

**Comment by lukegonis** [comment]
this was completed in sprint 28
