### ISSUE TITLE
Set up database backups for Mautic (Platform Comms Subscription Service)

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1076]
DoD:
- set up a backup process that backs up all the data in the Mautic database on a regular basis.

**Comment by mitovskaol** [comment]
@AndrewJun97 Can you please add a bit more detail to this ticket about how the backups were implemented, where to find the code, the frequency of the backups, etc.

**Comment by AndrewJun97** [comment]
Backups have been implemented using [backup-container](https://github.com/BCDevOps/backup-container).
Backups will be performed at 1am every day.
There will be 6 daily backups, 4 weekly backups, and 1 monthly backup stored.

Backup configuration/deployment files to be found [here](https://github.com/bcgov/Mautic-Openshift/pull/18)
