### ISSUE TITLE
INC0051180 - MCS-SILVER-APP-18.DMZ appears to have rebooted itself | SPIKE

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1079]
**Describe the issue**
Received alerts for the host and upon investigation found it had unexpectedly rebooted.

**Additional context**
HPE case 5354708116  opened

**Definition of done**
- Determine root cause of reboot
- Return node to service

**Comment by StevenBarre** [comment]
Moved to blocked waiting on response from HPE

**Comment by wmhutchison** [comment]
HPE responded with the normal request of specific data dumps from ILOM. Have provided this. 

This ticket will spill into Sprint 26.

**Comment by wmhutchison** [comment]
Nothing amiss found in the ILOM data provided to suggest hardware problems. Vendor suggestion is to change the Workload Profile in BIOS to High and monitor server in production use to see if that results in additional issues or not.

**Comment by wmhutchison** [comment]
If all goes to plan, this will be resolved by end of business day April 8th.

**Comment by wmhutchison** [comment]
Issue addressed by applying different Workload Profile setting (High Capacity) in BIOS. Node in question successfully returned to service, no new issues to report.
