### ISSUE TITLE
PenTest remediation - Secure Cookie - Artifactory

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1087]
**Describe the issue**
It was found that our Artifactory installation was not using secure cookies in at least one instance during our pentest.

Ensure secure cookies are enabled where applicable.

**Definition of done**
- [ ] Secure cookies enabled
- [ ] Tested

**Comment by lukegonis** [comment]
Still Relevant

**Comment by NickCorcoran** [comment]
Artifactory product issue, not a setting we can change.  closing.
