### ISSUE TITLE
SIEM integration - Audit logs - OCP 4.6

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1096]
**Describe the issue**
Connect pipes to allow audit logs to be forwarded to the BCDevOps tenancy on the SIEM
- other log types to be investigated in separate tickets

**Definition of done**
- [x] Identify configurations that need to be made
- [x] Ensure connection can be made to SIEM as was done previously - https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/208
- [x] Ensure access to SIEM console for DXC and PS staff

**Comment by StevenBarre** [comment]
Related https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/450

**Comment by NickCorcoran** [comment]
Submitted request to SecOps with list of platform services staff (gov and contractors) and DXC staff that will require access to the SIEM.

**Comment by StevenBarre** [comment]
Logging enabled by CHG0025038 - MCS SILVER - 2021 Q2 Patching - Upgrade to OCP 4.6.21

Moving back to in progress.
