### ISSUE TITLE
Monitor for Build Entitlement changes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1103]
**Describe the issue**
Per [RH](https://access.redhat.com/support/cases/#/case/02913386) the build entitlements we provide to the community and use ourselves are liable to change at any time. We want to monitor for their change and update the cluster wide entitlements shortly after.

Currently the KLAB Util server is the one subscribed and it keeps the files in `/etc/pki/entitlement/`.

Build a cronjob to run on that server and email the MCS team should the contents of that dir change. We probably want it to run at 8am each day so we get the notice when we first log in for the day.

**Additional context**
- https://github.com/bcgov-c/platform-tools/blob/ocp4-base/ocp4/entitlement.yaml
- https://github.com/bcgov-c/devops-fulfillment-pipeline/blob/master/roles/tenant/templates/build-entitlements-secret.yaml.j2

**Definition of done**
- [x] Cron job on the util server to monitor for changes
- [x] Store the cronjob in git, perhaps in https://github.com/bcgov-c/platform-ops/tree/ocp4-base/ocp4
- [x] Documentation in advsol-docs documenting the cron, and what needs updating when it fires.

**Comment by tmorik** [comment]
The testing script has been uploaded to GitHUB as a Draft PR.  https://github.com/bcgov-c/platform-ops/pull/366

Currently it's been testing using KLAB.

**Comment by tmorik** [comment]
Test done, sent a PR. https://github.com/bcgov-c/platform-ops/pull/366

**Comment by tmorik** [comment]
Document PR: https://github.com/bcgov-c/advsol-docs/pull/148

**Comment by tmorik** [comment]
PR Merged.
