### ISSUE TITLE
Document Gold/Gold DR design and app failover strategy

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1108]
**Gold Kamloops and Gold Calgary clusters will be built, configured and maintained by the Platform Ops team the same way as Silver** 

- All Shared Services will be available in both Gold clusters 

** New ingress route is required to be built between Gold Kamloops and Gold Calgary clusters for non-HTTP traffic (e.g. for data replication)** 

Gold and Gold DR clusters are going to be built, configured and monitored in the same way as the Silver cluster in the OCP 4 Platform. All Openshift services will be up, monitoring will be on and both clusters will be fully supported by the Platform Ops and Platform Services team. 

Enterprise Hosting runs an HA GSLB service  - one instance is running in KDC and another in CDC. 

 

**Gold Service Capabilities** 

Delayed upgrade cycle benefit is available by default to Gold customers. Openshift and Shared Services upgrades will start in the KLAB and CLAB clusters, then will be applied to Silver and then to Gold Kamloops and lastly to Gold Calgary. 

Ability to set up a failover from Gold Kamloops to Gold Calgary will be optional and available to the customers who want to take advantage of it. 

 

**Gold Service Cost Model** 

Hosting in the Gold Kamloops cluster will come with a fee. Access to the Gold Calgary cluster with the purpose of setting up a failover for an app will  available for an additional fee. 

Gold service will be available to teams who wish benefit from the delayed patch cycle and have an option to set up a geographic failover for their service. 

 

**No production workloads in Calgary allowed on a regular basis** 

The current hosting agreement for the Calgary Data Center (CDC) does not allow running active production workloads there on a regular basis if the Kamloops Data Center (KDC) is operational. Running production workloads is only allowed during short windows of application maintenance when the app instance in KDC is not available or in the case of the KDC outage. This means that pods can be running in the app's instance in Gold Calgary but they cannot receive traffic under normal circumstances. 

 

**Product team are responsible for configuring and testing the failover for apps**  

Gold customers will have an option to run a copy of their app in Gold Calgary in addition to the main instance in Gold Kamloops and will be able to set up active-active data replication between the two instances. 

Settting set a failover up for an app, will require adding an entry in the gov's Global Load Balancing Service to monitor the availability of the app in Gold Kamloops and redirect traffic to the app's instance in Gold Calgary if the Kamloops instance is not available. 3 DNS entries for an app will have to be added to the GSLB entry, for example: 

                  - myapp.gov.bc.ca (main entry point) 

                  - myapp.kamloops.gov.bc.ca (default redirect set up in GLBS) 

                  - myapp.calgary.gov.bc.ca (redirrect to this DNS is triggered in the kamloops DNS is not responding) 

 

There are 2 app failover options available to a team: 

- Automated failover – GSLB will monitor the application and if its API is down, starts sending traffic to its Calgary DNS  

- Manual failover – modify the DNS entry in DNS management system to point to their Calgary instance (not recommended) or drain their pods in Kamloops (preferred). DNS management system does not have DR and won’t be available in KDC is down. Automated failover with GSLB must be configured for a reliable failover. The manual failover is expected to be used to reduce service disruption during the app maintenance when the Kamloops-hosted service instance may not be available. 

 

**Other considerations:** 

 

- Setting up a PostgreSQL data replication between KDC and CDC. A product team can set a HA 3 node PostgreSQL cluster in Kamloops and a HA 3 node cluster in Calgary and active-active data replication between them. Master in Calgary can be setup as a member for the HA cluster in Kamloops to get their copy of the data. 

 

- S3 Object storage service access is available to Calgary apps. Product teams should connect to it through its front-end interface and should NOT use center specific DNS for accessing the service. 

 

Next steps: 

- Build the new ingress route to Gold Calgary for non-HTTP traffic ( @StevenBarre  )

- Migrate Platform Services' essential apps to Gold Kamloops and setup their instance in Calgary with active-active data replication  @jleach 

- Configure GSLB entry for the apps 

- Test the manual failover 

- Open access to Gold Kamloops to Ministry product teams

**Comment by gnunn1** [comment]
test comment

**Comment by dudemiester** [comment]
commenting test

**Comment by StevenBarre** [comment]
https://docs.developer.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/c46p83i1tev0e75glpkg/multi-cluster-applications
