### ISSUE TITLE
RocketChat DB backup pod file system 60% full

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1110]
**Describe the issue**
Rocketchat DB backup pod file system 60% full. try clearing cache or extend resources.

**Definition of done**
- [x] find out what's taking the space
- [x] update config

**Comment by jleach** [comment]
Each RC backup takes about 500Mb so was filling up storage quicker than expected. I've grown the PVC to 14G that should be enough for some time given current growth and rotation schedule.
