### ISSUE TITLE
Use MTC to migrate the FPO application from OCP3 to OCP4 (silver)

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1124]
Use the MTC to pilot migrating a project from OCP3 to OCP4. This project does not have state and the client manages the DNS record so they will do the last mile in the migration.

 - [x] Create project setup on OCP4 with the same licence plate based name as OCP3; - N/A
 - [x] Run the MTC playbook to build the plan and trigger the migration;
 - [x] Add existing users with same roles to access the namespace;
 - [ ] Advise PO the migration is done and what the new URL is;
 - [ ] Submit request to have old namespace set decommissioned;
 - [ ] Update PO and/or TC as needed in the registry.

**Comment by jleach** [comment]
@StevenBarre @wmhutchison 

Please review and run the "migrate.yaml" playbook located here to create a Migration Toolkit for Containers (MTC) migration of the Family Protection Order project. It will need the following arguments:

ansible-playbook migrate.yaml -e "name=fpo key=jag-csb-jes-family-protection-order"

**NOTE** 

1) This is a trial to see what happens to a project with a non-compliant namespace name. Its one of Wade's so we trust he can do an internal migration to a standard namespace.

2) the playbook switches between clusters, first going to the source cluster to lookup PVCs then to the destination cluster to create the actual migration in openshift-migrations. You will need to have two contexts named after the source and destination cluster. Also, I can't list namespaces on "pathfinder" so I can't 100% test the script.

**Comment by jleach** [comment]
@StevenBarre @wmhutchison Please add wade as an admin to the project set once completed so he can evaluate the success of the migration.

**Comment by StevenBarre** [comment]
Dibs @wmhutchison

**Comment by StevenBarre** [comment]
Created namespaces and granted Wade access
```
$ ansible-playbook -i inventory mkname.yaml -e license_plate=jag-csb-jes-family-protection-order
# for E in tools dev test prod; do oc -n "jag-csb-jes-family-protection-order-$E" adm policy add-role-to-user admin wadebarnes@github; done
```

Waiting on go-ahead from @jleach to run the migration.

**Comment by StevenBarre** [comment]
Playbook run, and migration completed
