### ISSUE TITLE
Devhub Issue: Using Artifactory (no description frontmatter)

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#113]
> path: (do not delete) https://github.com/BCDevOps/developer-experience/blob/master/apps/artifactory/DEVHUB-README.md
 > (do not delete) devhub page: /Using-Artifactory

## Devhub Content Issue

Just leaving a note that this file requires a description in the frontmatter so that it renders nicely  as a card. Try to keep the description to 140  characters or less :) 

<img width="402" alt="Screen Shot 2020-01-16 at 12 44 10 PM" src="https://user-images.githubusercontent.com/21046727/72561377-edbe3100-385d-11ea-9b15-2e6d45ab90fc.png">

**Comment by caggles** [comment]
Hey Patrick! I know this is a bit of an old issue, but related: I recently have found that searching for artifactory does not result in anything coming up in devhub. The documentation is there - linking directly to it works fine. But nothing shows up on search.
