### ISSUE TITLE
Use MTC to migrate the MDS DSR application from OCP3 to OCP4 (silver)

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1134]
Use the MTC to pilot migrating a project from OCP3 to OCP4. This project does not have state and the client manages the DNS record so they will do the last mile in the migration.

 - [x] Create project setup on OCP4 with the same licence plate based name as OCP3; - N/A
 - [x] Run the MTC playbook to build the plan and trigger the migration;
 - [x] Add existing users with same roles to access the namespace;
 - [x] Advise PO the migration is done and what the new URL is;
 - [ ] Submit request to have old namespace set decommissioned;
 - [x] Update PO and/or TC as needed in the registry.

**Comment by jleach** [comment]
@StevenBarre @wmhutchison

Before starting, please join us in the Rocket.Chat channel #mds-dsrp-mig-temp so we can coordinate with the DevOps team as needed. When ready....


Please review and run the "migrate.yaml" playbook located here to create a Migration Toolkit for Containers (MTC) migration of the Family Protection Order project. It will need the following arguments:

ansible-playbook migrate.yaml -e "name=mdsdsrp key=eazios"

**NOTE**

The playbook switches between clusters, first going to the source cluster to lookup PVCs then to the destination cluster to create the actual migration in openshift-migrations. You will need to have two contexts named after the source and destination cluster. Also, I can't list namespaces on "pathfinder" so I can't 100% test the script.

**Comment by StevenBarre** [comment]
Dibs

**Comment by jleach** [comment]
Sent follow up to owners asking for decommissioned status on prod.
