### ISSUE TITLE
Remove default Artifactory SVC CR from Project Provisioner

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#1138]
**Describe the issue**
Once cluster default access to Artifactory is configured successfully, provisioner created CR's for artifactory service accounts should be removed.  This becomes a duplicate setup that has already proven challenging for teams to adopt as a default approach, keeping it around will continue to confuse teams, and require operational management.

Teams that have additional need for artifactory access (for external build pipelines, etc) can provision their own access and manage as the do any other optional resource.

**Additional context**
Requires successful completion of #1126 (part 2)

**Definition of done**
- [ ] Notice of removal of feature: all teams to create their own Artifactory Service Account CR if they don't want to use the default cluster access
- [ ] Remove artifactoryServiceAccount CR creation from project provisioner
- [ ] Confirm gitops sync has removed all CRs and Archeobot successfully removes all legacy service accounts.

**Comment by StevenBarre** [comment]
Confirmed that all clusters have a Artifactory docker pull secret in the global pull secret file.

**Comment by lukegonis** [comment]
Still relevant

**Comment by IanKWatts** [comment]
I talked to Cailey about this and will update the Provisioner and maybe ArgoCD to allow for existing ArtifactoryServiceAccounts to remain, while not creating them for new projects.

**Comment by IanKWatts** [comment]
The Provisioner has been updated and new ArtifactoryServiceAccounts will not be created.  Existing ArtifactoryServiceAccounts will not be deleted.  app-provisioner v4.2.18
