### ISSUE TITLE
Use MTC to migrate the CAPS application from OCP3 to OCP4 (silver)

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1139]
Use the MTC to pilot migrating a project from OCP3 to OCP4.

 - [x] Create project setup on OCP4 with the same licence plate based name as OCP3; - N/A
 - [x] Run the MTC playbook to build the plan and trigger the migration;
 - [x] Add existing users with same roles to access the namespace;
 - [x] Advise PO the migration is done and what the new URL is;
 - [ ] Submit request to have old namespace set decommissioned;
 - [x] Update PO and/or TC as needed in the registry.

**Comment by jleach** [comment]
Coordinate w/ Jason.

Please review and run the "migrate.yaml" playbook located here to create a Migration Toolkit for Containers (MTC) migration of the CAPS project. It will need the following arguments:

ansible-playbook migrate.yaml -I inventory -e "plan=caps key=8gsiqa"

NOTE

The playbook switches between clusters, first going to the source cluster to lookup PVCs then to the destination cluster to create the actual migration in openshift-migrations. You will need to have two contexts named after the source and destination cluster. Also, I can't list namespaces on "pathfinder" so I can't 100% test the script.

**Comment by wmhutchison** [comment]
@jleach I'm taking this, will touch base after catching up on comms/etc.

**Comment by jleach** [comment]
Namespaces were reported "empty" today by the owner. Not sure why - digging. It looks like it's also named "Duplicate" in the registry.

**Comment by jleach** [comment]
@StevenBarre @wmhutchison

Are one of you able to re-run this migration. Same command as above. Thanks.

**Comment by wmhutchison** [comment]
On it.

**Comment by jleach** [comment]
Send email to owners to see if we can close this. We need a decommissioned request from them.

**Comment by jleach** [comment]
Closing DevOps request 1108 completes this work.
