### ISSUE TITLE
OCP4.6 - Update OAuth Token timouts

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1155]
**Describe the issue**
Adjust OATH and Default inactivity timeouts to improve developer experience.
Shift from 1+day to 15 mins appears to have been too drastic a change for developers, resulting in numerous logins required throughout the days, even if they do not leave their machines.  
Suggest to try 60 min timeout and re-assess developer experience.

**Additional context**
#438

**Definition of done**
- [x] Set default inactivity timeout Default: 4 hrs
- [x] Set values for individual OAuth Client inactivity timeouts: 4 hrs
- [x]  If changes are needed, create playbooks to implement
- [x] Test changes in LAB
- [x] Promote changes to SILVER

**Comment by NickCorcoran** [comment]
Feedback from Cloud Pathfinder exploration into similar timeouts for AWS DevOps:
6 hours sounds reasonable to me. We had a quick look at policy and nothing jumped out at us so let’s do it and I have a request with our security to figure out what policy says (or if it doesn’t say anything). There is guidance around user timeouts 15 min for apps, but nothing yet apparent about secure dev token timeouts. That makes sense if we think that majority of dev in BC Gov is more like the scenario of using Toad to connect to an Oracle DB in the data centre, with no timeouts happening there.

As such, adjusting to 6 hrs and will revisit as needed in line with Cloud Pathfinder.

**Comment by rloisell** [comment]
So there is some OCIO policies in regards to this, or at least in regards to AD FS (and IDIR). Perhaps being consistent with token lifetime in that space would be warranted?

**Comment by NickCorcoran** [comment]
Thanks @rloisell.  I had put the question to the OCIO ISB and the advice I was given was to follow the standard app timeout policy, but that was 
 while ago.  I can see that was wrong in this case.  The Cloud Pathfinder team has set the 6 hour threshold and have been working with the OCIO through this as well.  I agree there needs to be more consistency here.  I'll see what I can do to help that along.

**Comment by rloisell** [comment]
I know when it came to AD FS it was Chris Flight who was mentioning the standard, and I think OCIO SecOps raised issues within anything longer as well.

**Comment by NickCorcoran** [comment]
Recommended timeout as part of ECM PaaS was 4 hours, so will reflect that.  I will touch base with all groups so that we have a better collective understanding and consistent timeout implmented.

**Comment by StevenBarre** [comment]
OAuth client values override the defaults from the server, so I'm going to just not set those anymore and just set 4h in the oauth server.

https://github.com/bcgov-c/platform-gitops-gen/pull/145
