### ISSUE TITLE
Aqua deep dive and prep for demo to stakeholders

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1159]
- [x] Investigate capabilities (for MVP and what could be used as we move forward)
      - start in Lab, but especially in Silver against live targets
- [x] Scan specific apps
- [x] Prepare presentation and plan for walk-through demo
- [ ] schedule walk-through w/ OCIO ISB and perhaps others

**Comment by jleach** [comment]
Going to move this back to the backlog. Its a little too early in the rollout of Aqua to build out community consumable materials.

**Comment by NickCorcoran** [comment]
This has been done in the Lab.  TO do some scans in Silver before performing demo w/ OCIO ISB.

@jleach I'd suggest we create a new ticket for creating a video walkthrough a bit later.

**Comment by jleach** [comment]
Upgraded to 3.14.
