### ISSUE TITLE
Determine why Xcode on the Mobile Signing Service cannot access account credentials.

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1169]
## Description

The signing agent on the Mac mini's is run as a daemon so that it starts reliably when the machines reboot. When run this way, Xcode is unable to access the correct account credentials to fetch updated provisioning profiles. We need to figure out how to make said credentials accessible to Xcode from the agent's process.

## Done When

The MSS can start as a daemon (background process when the machine reboots) and access all credentials needed to sign mobile applications.

**Comment by ShellyXueHan** [comment]
### Update:

Since we are migrating everyone to self-signing from MSS, let's not spend time fix this. Closing now!
