### ISSUE TITLE
Create a viable Power Point template for DXC to create biweekly Governance SILVER router traffic reports

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1175]
**Describe the issue**
After week 1 of launching portions of the COVID vaccine registration service on the SILVER cluster, a desire to know the impact of this new workload on the cluster was presented, and thus an adhoc unique report was created in Power Point. A desire for this report to continue to be created/presented was mentioned, thus now a need to create a suitable template file that any DXC MCS stakeholder can take and follow to create a suitable report for Governance. 

Once created at least one additional DXC MCS team member will be cross-trained on the template's use as part of this issue ticket before closing it off.

**Additional context**
DXCAS Ticket reference: RITM0092942

**Definition of done**
- [x] Derive suitable template for generating Prometheus URLs for any specific day.
- [x] Create Power Point presentation template file which will include internal documentation on its use.
- [x] Cross-train at least one MCS team member on the use of the template while working on the next report.

**Comment by wmhutchison** [comment]
Prometheus URL will be like this, which for a given date generates both the router pod loads by actual pod and also the summation of all pod traffic.

```
https://prometheus-k8s-openshift-monitoring.apps.silver.devops.gov.bc.ca/graph?g0.range_input=12h&g0.end_input=2021-05-07%2002%3A00&g0.expr=sum(max_over_time(haproxy_frontend_current_sessions%5B5m%5D))%20by%20(pod)&g0.tab=0&g1.range_input=12h&g1.end_input=2021-05-07%2002%3A00&g1.expr=sum(max_over_time(haproxy_frontend_current_sessions%5B5m%5D))&g1.tab=0
```

The above example has the `end_input` variable set to 2021-05-07 which actually will correspond to the traffic for 2021-05-06 since it specifies the ending time (GMT) and then works back 12 hours.

**Comment by wmhutchison** [comment]
Not close to completing this yet due to other concerns taking priority. Assigning to Sprint 28.

**Comment by wmhutchison** [comment]
Having problems getting enough available time to deal with this for now. Moving to Backlog for now.

**Comment by tmorik** [comment]
https://github.com/bcgov-c/advsol-docs/pull/152/files
