### ISSUE TITLE
Build integration between RocketChat and Uptime Robot Reliability Dashboard

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1181]
As a Platform Community member who is not a developer I would like to have an easy access to the Platform updates and alerts outside of RocketChat. 

DoD:
- Build an integration between the #devops-alerts channel in RC and the "Status Updates" section in the [Platform Service Reliability dashboard](https://stats.uptimerobot.com/w28pPSLlZE) so that the content in "what is happening?" section of the alert is displayed in the Status Update section as a link, clicking the link shows the full alert message (e.g. "What is the impact?" and "what should I do?" sections, etc)

**Comment by jleach** [comment]
This may not be doable. UptimeRobot does not appear to have API for adding announcements. As per [the docs](https://uptimerobot.com/api/) there is no method for creating status updates.

![Screen Shot 2021-07-22 at 10.18.10 AM.png](https://images.zenhubusercontent.com/5c2fa1b7ce4f66381cd8d02d/2bdf365a-0152-4b74-a5a7-5e73adb72c6c)

**Comment by jleach** [comment]
Not doable given the UptimeRobot API. Closing.
