### ISSUE TITLE
Fix user attribute mapping - KeyCloak

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1193]
It was discovered when another user was setting up a KeyCloak <> Azure connection that user mapped attributes were not being pulled properly from the Azure authentication token.
Marco helping Nick, w/ IDIM input (as they are the ones with Azure-side configuration visibility), to fix this.

Testing taking place using test realm 4368t2n5.

**Definition of done**
- [x] Attributes available in token known
- [x] Attributes properly mapped with correct names
- [x] Attributes verified on the User Attributes page within KeyCloak

**Comment by NickCorcoran** [comment]
May 17
Nick and Marco met to look at problem
Information requested from IDIM
Requested for Marco's IDIR be added to the Azure context for testing purposes

May 18
Some details returned from IDIM, more investigation required
Nick and Marco met to look at problem
Marco tried hooking up test harness, but unsuccessful due to defined redirect URI on Azure side

**Comment by arcshiftsolutions** [comment]
@NickCorcoran - Good morning; I was successful in getting the broker token. We should be able to proceed with our mapping exercise. I'll reach out today.

**Comment by arcshiftsolutions** [comment]
We have mapped the attributes available to us in the token. We've reached out to Chris at IDIM around the additional attributes which are not yet available in the token.

**Comment by NickCorcoran** [comment]
Waiting on response on queries to IDIM and MS on getting proper attributes (IDIR ID and GUID) mapped into the token.  Note sent to MS on 4 June.
