### ISSUE TITLE
Prepare and present at DevSecOps event with Public Sector Network

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1198]
The deck has been prepared and can be found [here](https://bcgov-my.sharepoint.com/:p:/g/personal/nick_corcoran_gov_bc_ca/EftUEjxYxzZIjCtm4a2Tb7cBTNt1XbFvxzajiOvi17FTGA?e=zUW5X8)

The presentation took place on May 18, 2021.

**Comment by NickCorcoran** [comment]
https://publicsectornetwork.co/wp-content/uploads/2020/07/PSN-Virtual-2021-DevSecOps-Canada.pdf

- [x] Prepare presentation
- [x] Prepare notes
- [x] Test connections and plan execution
- [x] Attend conference
- [x] Present
