### ISSUE TITLE
Alert when Postgres Has no synchronous standby

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#12]
Patroni HA DB has occasionally lost it's synchronous standby and did not automatically re-initializing one.  A restart of a replication member will reset the Sync Standby flag for a member.

- [x] Alerting for this situation to be added
- [x] Possible monitoring and auto-heal?

**Comment by mitovskaol** [comment]
@caggles  Does this issue still happen with Patroni?

**Comment by lukegonis** [comment]
Still valid
