### ISSUE TITLE
Prep for Sr. Security Analyst position(s) competition

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1201]
Prep for interview process

- [x] Written exercise?
- [x] Interview questions development
- [x] Scoring criteria

**Comment by NickCorcoran** [comment]
Scheduled mtg w/ Julian on 1 June to discuss.

**Comment by NickCorcoran** [comment]
Met yesterday and discussed...
Exercise:
- https://github.com/BCDevExchange-CodeChallenge
- https://github.com/BCDevExchange-CodeChallenge/CodeChallenge10-Master
Julian has an idea for a simple security focused exercise applicable to the job.

Competency based questions:
- Nick to create some questions with scoring based on BCGov competencies and share for review

**Comment by juhewitt** [comment]
wonderful.  I'm still waiting on the PSA so we can post; Nick's in the loop and will keep you updated Julian when it goes lives.

**Comment by NickCorcoran** [comment]
Nick - drafted questions and potential scoring and ideal answers.  Shared w/ Justin/Julian for feedback.

**Comment by NickCorcoran** [comment]
Nick to do some work on written exercise and share w/ Justin/Julian by end of week - July 2nd.
