### ISSUE TITLE
Migrate Rocket Chat mongo database from Redhat image

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1211]
## Description

The mongo image `registry.redhat.io/rhscl/mongodb-36-rhel7:1` is deprecated and we need to find an alternative image that is currently maintained.

## Done When

- [x] dev migrated to `mongodb-63-ha:1` image;
- [x] test migrated to `mongodb-63-ha:1` image;
- [x] prod migrated to `mongodb-63-ha:1` image;

**Comment by jleach** [comment]
No suitable mongo image existed so I rebuilt one as part of #1388. This was based on the RHEL8 image and official mongoDB RPMs. I's mostly a drop-in replacement for the image produced by Redhat. Currently being tested in Rocket.Chat dev/test.

**Comment by IanKWatts** [comment]
The Prod move to the non-redhat image was done prior to the migration to Argo CD, which was completed in late 2021.
