### ISSUE TITLE
Use MTC to migrate Justin Disputes project to Silver

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1213]
Use the MTC to migrate Justin Disputes Project from OCP3 to OCP4. This project does not have state and the client manages the DNS record so they will do the last mile in the migration.

 - [x] Create project setup on OCP4 with the same licence plate based name as OCP3; 
 - [x] Run the MTC playbook to build the plan and trigger the migration;
 - [x] Add existing users with same roles to access the namespace;
 - [x] Advise PO the migration is done and what the new URL is;
 - [ ] Submit request to have old namespace set decommissioned;
 - [x] Update PO and/or TC as needed in the registry.

bash-4.2# oc get projects|grep wuboml
wuboml-dev                             AG-PSSG - JUSTIN (dev)                                                Active
wuboml-prod                            AG-PSSG - JUSTIN (prod)                                               Active
wuboml-test                            AG-PSSG - JUSTIN (test)                                               Active
wuboml-tools                           AG-PSSG - JUSTIN (tools)                                              Active
bash-4.2#

Note: They have provisioned OCP4 namespace already.
OC4 (Destination) - License Plate: c8ddb1

**Comment by jleach** [comment]
## Description

We would like to migrate any of our assets on ARO to the Silver cluster so that ARO can be decommissioned.

## Done When

The MTC is used to migrate any assets its capable of migrating from ARO to Silver.

**Comment by jleach** [comment]
@wmhutchison @tbaker1313 

Please review and run the "migrate.yaml" playbook located here to create a Migration Toolkit for Containers (MTC) migration of the JUSTIN project. It will need the following arguments:

ansible-playbook migrate.yaml -I inventory -e "plan=justin key=wuboml"

NOTE

The playbook switches between clusters, first going to the source cluster to lookup PVCs then to the destination cluster to create the actual migration in openshift-migrations. You will need to have two contexts named after the source and destination cluster.

**Comment by tbaker1313** [comment]
Will complete in CHG0026432 - May 27th @ 0700

**Comment by jleach** [comment]
@tbaker1313 Before you start can you check the namespaces exist on Silver:

```yaml
Namespaces: 
  - Name: wuboml-tools  
    Clusters:
      - silver  
  - Name: wuboml-test  
    Clusters:
      - silver  
  - Name: wuboml-prod  
    Clusters:
      - silver  
  - Name: wuboml-dev  
    Clusters:
      - silver 
```

**Comment by jleach** [comment]
Playbook completed this morning. Work done from our perspective. Will keep ticket open for the time being; it will be some time before they actually complete the migration (DNS, etc).
