### ISSUE TITLE
OCP GOLD DR - Build UTIL Server for GOLD DR Cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1222]
**Describe the issue**
The UTIL server is integral for both the building and operations/maintenance of an OCP4 cluster.

**Additional context**

**Definition of done**
- [x] place iStore order
- [x] Build MCS-GOLDDR-UTIL.DMZ as a standard DXC Linux server build.
- [x] Create initial inventory files for GOLD DR cluster.
- [x]  Run playbook to configure UTIL server.

**Comment by wmhutchison** [comment]
Note for Tim/Tats when building out the `rhcos-ignition-builder/inventory` content for GOLDDR. It would be best to use existing CLAB files as the starting point, since Calgary has things that are more obvious (different DNS than Kamloops) but also things not so much because of early-stages design decisions (Calgary uses 10.95.0.0/16, 10.96.0.0/16 while Kamloops uses 10.97.0.0/16, 10.98.0.0/16).

No need to update/modify the vault.yaml file you'll need, just copy one as-is from one of the other directories since it's only storing the common pull secret used by Openshift for obtaining all the Red Hat content during cluster build.

**Comment by tbaker1313** [comment]
Inventory files created for hosts. Still awaiting a little more information to complete.

**Comment by tbaker1313** [comment]
Bootstrap server added and inventory updated. Nearing completion.
