### ISSUE TITLE
OCP GOLD DR - Assign IP addresses and create DNS entries

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1227]
**Describe the issue**
We pre-assign all required IP addresses so that automation for building out the cluster can properly make use of inventory files we'll be creating as well which will define specific IPs for each node. DNS should be also setup ahead of time.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Use VRA to allocate all required PROD/MGMT/STOR IPs.
- [x] Confirm IP allocation via Infoblox.
- [x] Use NNR to assign PROD DNS entries.
- [x] QA that all IPs with DNS entries properly resolve.

**Comment by tbaker1313** [comment]
Network addresses assigned and confirmed.
