### ISSUE TITLE
OCP GOLD DR - Order F5 VIPs for GOLD DR cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1232]
**Describe the issue**
Work needs to take place so that the virtual F5 instance for GOLD DR cluster can be configured correctly for the two API VIPs and the single APP VIP. Requests done internally via TheHUB tickets and filling in the order form for Load Balancer configs.

Do note that because of the order involved, we cannot test the results of this work until we get into a position to actually bootstrap the GOLD DR cluster.

**Additional context**
Link to docs detailing what is involved for ordering the Load Balancer configs. <https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Install.md#order-load-balancers>

RITM0095110 = Internal ticket for ordering APPS VIP
RITM0095111 - Internal ticket for ordering API VIP
RITM0095112 - Internal ticket for ordering API-INT VIP

**Definition of done**
- [x] use VRA to reserve all involved IP addresses.
- [x] use NNR to assign DNS entries to VIPs.
- [x] Fill in required forms for ordering F5 VIP configurations and submit TheHUB tickets
- [x] track RITM tickets assigned to Network team and confirm their completion

**Comment by wmhutchison** [comment]
DNS needs to be created as follows in NNR.

apps.golddr.devops.gov.bc.ca and *.apps.golddr.devops.gov.bc.ca -> 142.34.64.4
api.golddr.devops.gov.bc.ca -> 142.34.64.5
api-int.golddr.devops.gov.bc.ca -> 142.34.113.147

**Comment by wmhutchison** [comment]
Once NNR task is done, this can be moved to Blocked since we'll be waiting on Network to finish their work.

**Comment by wmhutchison** [comment]
For Sprint Review: Not going to be finished within Sprint 28. Quite likely be finished within Sprint 29.

**Comment by tbaker1313** [comment]
Added required  DNS entries. Moving to blocked for now.

**Comment by wmhutchison** [comment]
Work is now completed and the VIPs have been successfully tested.
