### ISSUE TITLE
Redhat SSO installation for platform services tooling

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#1235]
## Background

There have been a few occasions where SSO Service degradation has a direct impact to the OCP availability (as well as other devops tools such as sysdig/aqua/argo etc). 

The May 30th 2021 incident is of note in particular. This incident made the cluster inaccesible by everyone except those who have direct non sso keys to the cluster. 

Most incidents have been strongly related to SSO clients then it has infrastructure changes, human error, or application error. This makes incidents hard to predict and change management to solve these incidents in a timely manner difficult (especially if you cannot access the cluster to troubleshoot). 

There is a usecase for the platform services toolset to utilize its on SSO instance as it isn't __just another client__. It is a very special client.

Seperating concerns between the typical SSO Client (government applications) and Platform Services tools (applications that support the teams and infrastructure that support the government applications) is paramount.

**Comment by mitovskaol** [comment]
Emergency access to Openshift Console in all production clusters has been set up with GitHub Teams. Closing this ticket.
