### ISSUE TITLE
OCP GOLD DR - Setup NetApp Filer

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1238]
**Describe the issue**
This ticket will track all prep work involved with setting up and configuring the NetApp appliance which will provide storage services to the Calgary GOLD cluster. The work will focus mainly between the DXCAS Storage and MCS teams.

**Additional context**

**Definition of done**
- [x] Confirm with Storage that configuration of the NetApp appliance is complete.
- [x] Confirm connectivity to the assigned IPs of the NetAPP appliance on the STOR network rail.
- [x] Confirm the standard username/password can SSH to the NetAPP appliance via STOR network.

**Comment by wmhutchison** [comment]
Yanking this out of Sprint 28 for now, since it's doubtful it will be completed prior to the end of Sprint 28.

**Comment by wmhutchison** [comment]
The remaining bullet points for this ticket involve confirming what Jody has previously claimed, in that he's stated that the NetApp is ready for us. We'll need to confirm both network connectivity via STOR VLAN and we need to do this from the UTIL server since phase 2 of the configuration will have our playbooks login directly to the appliance to configure it.

**Comment by wmhutchison** [comment]
Per an email from Jody Tomlinson on June 4th 2021.

Hey Dan and MCS Team,

The GOLDDR NetApp is now up and ready for connection and testing.  Here are the IP’s to use gang.  Let me know if you run into any problems.  Accounts and passwords should be the same as the other environments.

192.168.104.124 - mcs-golddr-nfs-netapp-nfs.hs.advsol.tech
192.168.104.125 - mcs-golddr-netapp-iscsi1.hs.advsol.tech
192.168.104.126 - mcs-golddr-netapp-iscsi2.hs.advsol.tech

Enjoy and come again,

Jody Tomlinson
Senior Storage Administrator
Advanced Solutions Inc.

**Comment by tbaker1313** [comment]
Confirmed login with expected username/password is working. Closing.
