### ISSUE TITLE
Platform Registry - Validate GitHub ID for PO and Tech Contact on project set creation

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1255]
**Describe the issue**
Currently, placeholders (i.e. tbd, unknown@github.com) can be added as GitHub ID/email on project set creation through the platform registry.  This creates role bindings in OpenShift which are not real, or not to intended users.  While the user would need to be a member of the BCDevOps org to actually access anything, these 'false' role-bindings can contribute to confusion among team members.

**Definition of done**
GitHub ID/email should be validated as part of the submission to avoid placeholders being added.  An entered GitHub ID/email that is not a member of the BCDevOps org should result in an error and return the submitter to the form to enter a valid ID/email from that org.

**Comment by sbathgate** [comment]
React Final Form, which we use in the Registry, has a piece of functionality that could dramatically assist with this ticket. An example can be found [here](https://codesandbox.io/s/5m4w2909k?file=/GithubUserTypeahead.jsx). The feature will provide an autoprompt of potential GH id's, with some tweaking I believe this could be used to achieve the above with the added benefit of prompting users as they input the GitHub ID's

**Comment by lukegonis** [comment]
change has been promoted to prod Sept 21
