### ISSUE TITLE
Sysdig - Docker and k8s events are unavailable

### ISSUE THREAD

**Issue by matthieu-foucault** [BCDevOps/developer-experience#1266]
**Describe the issue**
Since the move to the Silver cluster, Docker and Kubernetes event are not visible in Sysdig. Alert event are working as expected.

**Additional context**

https://docs.sysdig.com/en/event-types.html lists the events that should be enabled by default.

I vividly remember those event being available on the Pathfinder cluster last year. We don't have namespaces on that cluster so I can't confirm whether they are still visible there or not.

**Definition of done**

Events that are enabled by default according to the sysdig docs are visible by teams.

**Comment by ShellyXueHan** [comment]
### Updates:
- Verified that events are missing from Silver cluster only
- Support ticket created, expect further investigation

**Comment by ShellyXueHan** [comment]
### Updates:
- we've verified that the connection between kubelet and API server is all good, issue should be on sysdig agent pods
- sysdig support is escalating to engineer to look into the logs and get back to us with more info to troubleshoot

**Comment by ShellyXueHan** [comment]
### Update:

Sysdig support suggested increasing agent pod resources. Tested in silver, events are showing up now. Will keep looking for a weeks period to verify fix.

**Comment by matthieu-foucault** [comment]
Is this available to everyone? I'm still only seeing "alert" events in the Events view

**Comment by ShellyXueHan** [comment]
hmmm looks like it's still not working for teams, probably events are in a different scope. @matthieu-foucault let me double check and get back to you!

**Comment by ShellyXueHan** [comment]
### Updates:
By default, `Infrastructure Events` in a sysdig team setting is disabled. However, there is no API/CLI resource to manage this setting (so far it looks like this is only available by manually clicking). Still connecting with sysdig support to figure out if there is a way to bulk update this for all teams based on templates.

On the other side, app teams can not be given access to modify team settings directly as this will also include the power to access all other team's metrics. Anyway there is no point of manually updating it as any CR update will revert this setting by default (shrug).

Will update again later on!

**Comment by ShellyXueHan** [comment]
### Update:
Confirmed with Sysdig, unfortunately there's no way to automate bulk team settings yet. API might be open up for this later on but no timeline either. Will update the sysdig doc to capture this as a request.

**Comment by ShellyXueHan** [comment]
okay so I have a way to bulk update team setting now. But unfortunately another issue pop up with events: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1614 will update when ready.

**Comment by ShellyXueHan** [comment]
### Updates:

Event related issues have been fixed all good now. Events are enabled for your `<project_set>-team` sysdig team.
