### ISSUE TITLE
Add Ministry Sectors to the Platform Registry

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1271]
**Describe the issue**
The Platform Registry currently tracks the Ministry and Ministry short name for each Ministry, it would be beneficial to also map the Sector the Ministry is apart of in the Registry Database and API. 

This data can then be used in authorization policies for applications such as vault and aqua. There might also be some additional benefit when generating future security reports.

**Additional Notes**
Thinking Out Loud: It might be beneficial to define the Ministries and Sector Mappings in a Config Map that way they can be dynamically loaded when organization changes happen. This also might reduce the need for a migration to add, remove, or edit any of the mappings.

**Definition of done**
- [x] Database and API updated to support the insertion and retrieval of this information via the web UI
- [ ] Sector Long Name and Short Name stored or mapped
- [ ] Mapping should be done by the API. ( Each Ministry belongs to a specific sector and should not need to input their sector if they're already entering their ministry when requesting a project set)

**Comment by NickCorcoran** [comment]
I think my main goal here was to get access for Ministry security/privacy teams into the registry on their own.  If a user can be given a role that allows visibility to multiple ministries projects this could also work.

**Comment by Iryna-Kaplun** [comment]
This ticket has been moved to the registry repo #1056 and it will be tracked there.
