### ISSUE TITLE
Test out app failover in LABs

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1282]
The Platform Services Team needs to explore the options for setting up data replication between 2 app instances and setting up a GSLB service to fail over between the instances in the case when the main app instance becomes unavailable. 
This set up will be tested in CLAB and KLAB clusters before being implemented in Gold/Gold DR.

DoD (feel free to modify as needed):
 - Set up 2 test app instance in KLAB with a Mongo cluster and enable data replication between the dbs
- Move one instance to CLAB and enable the data replication cross cluster
- Enable GBLS between the app instances in CLAB and KLAB
- Document the findings in this ticket

**Comment by jleach** [comment]
This is done. Working as expected.

**Comment by mitovskaol** [comment]
HOORAY!! This is awesome news @jleach  Were you able to fail back successfully too?

**Comment by jleach** [comment]
Opp. Sorry, I mistook this for database work only. I didn't setup an application component but since @j-pye  has setup Vault I to work with the GSLB I have no reason to believe the technology won't work. I think this work + @j-pye Vault work verifies this ticket.

**Comment by jleach** [comment]
PS. The missing next step, if any, is to test EnterpriseDB and CrunchyDB and determine what one we want to recommend based on ease of use, licensing const if required, operator support (maturity). Patroni will not work x-cluster.

**Comment by mitovskaol** [comment]
GLSB driven failover has been tested for Vault . Closing the ticket.
