### ISSUE TITLE
Create monitor for OCP4 purchased certificates

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1309]
**Describe the issue**
Unlike OCP3, OCP4 does not have a vendor-provided playbook to check certificate expiries. The expectation is that in OCP4 self-signed certs created and managed by the cluster will continue to do so without intervention by us.

The purchased certs however may be a different story. Need to look into whether or not AlertManager tracks any of this, and if not, work out an appropriate solution so that we are kept up to date well in advance since certificate ordering takes time.

**Additional context**
All live certs in OCP4 clusters currently have an expiry date of late August 2021.

```
# for ENV in klab clab silver gold ; do echo "APP Certificate for $ENV environment"; curl -vk https://blat.apps.$ENV.devops.gov.bc.ca/ |& grep date ; echo "API Certificate for $ENV environment"; curl -vk https://api.$ENV.devops.gov.bc.ca:6443/ |& grep date; done
APP Certificate for klab environment
*       start date: Aug 24 21:18:38 2020 GMT
*       expire date: Aug 25 21:18:37 2021 GMT
API Certificate for klab environment
*       start date: Aug 24 21:35:15 2020 GMT
*       expire date: Aug 24 21:35:15 2021 GMT
APP Certificate for clab environment
*       start date: Aug 28 17:24:53 2020 GMT
*       expire date: Aug 28 17:24:52 2021 GMT
API Certificate for clab environment
*       start date: Aug 24 21:42:34 2020 GMT
*       expire date: Aug 24 21:42:33 2021 GMT
APP Certificate for silver environment
*       start date: Aug 24 21:31:03 2020 GMT
*       expire date: Aug 25 21:31:02 2021 GMT
API Certificate for silver environment
*       start date: Aug 24 21:58:01 2020 GMT
*       expire date: Aug 25 21:58:01 2021 GMT
APP Certificate for gold environment
*       start date: Aug 24 21:49:39 2020 GMT
*       expire date: Aug 25 21:49:39 2021 GMT
API Certificate for gold environment
*       start date: Aug 24 21:49:10 2020 GMT
*       expire date: Aug 24 21:49:09 2021 GMT
```

**Definition of done**
- [ ] Check if AlertManager track this and if so, when it will start alerting.
- [x] If AlertManager is not an option, create custom monitoring for this.
- [x] Test and confirm custom monitoring works if AlertManager is not used.

**Comment by wmhutchison** [comment]
Confirmed that AlertManager tracks no certificates except for the client Kubelet certs (which are admittedly already renewed via operator automation).

Moving this to Backlog for now, since we've got this current round of cert expiries visible to us for now.

**Comment by StevenBarre** [comment]
If we can get `check_http` working with Nagios, it can do this for us. https://nagios-plugins.org/doc/man/check_http.html

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-tools/pull/48 now includes TLS cert checks for API and APPS. Will WARN at 90 days, and CRITICAL at 7 days.

Moving to in progress.

**Comment by StevenBarre** [comment]
Nagios is now monitoring cert expiry for all clusters.
