### ISSUE TITLE
Decommissioning Openshift 3.11 clusters

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1314]
**Describe the issue**
Track all work involved with performing this task, which presumes all is clear to do so.

Two iStore Order for decomissioning OpenShift 3.11 LAB and PROD clusters
Date Submitted: June 8, 2021
iStore Numbers: TBD
Lead time (business days after EA Approves):

**Additional context**

**Definition of done**
- [x] Send Luke email detailing all nodes to request decomms for.
- [x] Luke creates iStore orders for the decomms.
- [x] DXC receives internal tickets based off the iStore requests and puts them on hold.
- [x] DXC communicates internally that these are not normal decomms, the hardware is earmarked for future use and not to be recycled in the general pool of hardware.
- [x] DXC when able to proceed schedules and executes suitable RFCs for shutting down both LAB and PROD clusters.
- [x] Close off this ticket once we've received and processed the decomm paperwork for the three master VMs

**Comment by lukegonis** [comment]
@wmhutchison the order has been submitted, I split it into two orders, one for LAB and one for PROD, I will post a comment here once I receive the iStore numbers.

**Comment by wmhutchison** [comment]
Tickets have dropped starting today, Tim Baker is wading through them all and will place them on Hold.

**Comment by wmhutchison** [comment]
Most certainly will continue and hopefully conclude in Sprint 30.

**Comment by wmhutchison** [comment]
By request from Dan Deane to free up ESXi resources, a separate RFC was created by Tim Baker and executed to decomm the remaining six APP VMs in 3.11 PROD. Those will be gone by EOD July 6th.

**Comment by tbaker1313** [comment]
LAB Decom scheduled for July 8th starting at 1000
PROD Decom scheduled for July 8th starting at 1300

**Comment by wmhutchison** [comment]
Saving current ILOM IPs here in case we need them.

172.30.64.27 - ociopf-p-163-sc.hs.advsol.tech
172.30.64.49 - ociopf-p-195-sc.hs.advsol.tech
172.30.64.52 - ociopf-p-198-sc.hs.advsol.tech
172.30.64.228 - ociopf-p-160-sc.hs.advsol.tech
172.30.64.229 - ociopf-p-161-sc.hs.advsol.tech
172.30.64.230 - ociopf-p-162-sc.hs.advsol.tech
172.30.64.231 - ociopf-p-170-sc.hs.advsol.tech
172.30.64.232 - ociopf-p-171-sc.hs.advsol.tech
172.30.64.233 - ociopf-p-180-sc.hs.advsol.tech
172.30.64.234 - ociopf-p-181-sc.hs.advsol.tech
172.30.64.235 - ociopf-p-182-sc.hs.advsol.tech
172.30.64.238 - ociopf-p-185-sc.hs.advsol.tech
172.30.64.239 - ociopf-p-186-sc.hs.advsol.tech

**Comment by wmhutchison** [comment]
Adding Tim Baker to this ticket since he's in the loop on final items, since tickets for VM PROD masters hasn't officially dropped yet.

**Comment by wmhutchison** [comment]
Master VM decomm tickets dropped, closing ticket.
