### ISSUE TITLE
Sysdig agent metric limit issue

### ISSUE THREAD

**Issue by wadeking98** [BCDevOps/developer-experience#1315]
**Describe the issue**
The Sysdig agents running on each Openshift node have a limit to the number of metrics they monitor at a given time. Once that limit is reached, the Sysdig agent will start to ignore certain metrics. The metric limit of the Sysdig agents is too small and causes data outages in some of our dashboards.

**Additional context**
![Screenshot from 2021-06-16 14-54-35](https://user-images.githubusercontent.com/36937407/122299562-01d2eb80-ceb3-11eb-9630-543d78047e52.png)

**Definition of done**
The Sysdig agent metric limit to be increased and to consistently receive data on all dashboards

**Comment by ShellyXueHan** [comment]
@wadeking98 are you still see metrics discontinued?

**Comment by wadeking98** [comment]
Hi @ShellyXueHan. Yes the metrics are still discontinued in the backup environment https://app.sysdigcloud.com/#/shared/dashboard/6d681a7b7b4b43a196ed7e44644f4437. 
![image](https://user-images.githubusercontent.com/36937407/150878736-78671199-121a-49d9-8e68-35c3dd80c555.png)

**Comment by ShellyXueHan** [comment]
@wadeking98 is this issue still around? we have extended our metrics limit so should be seeing improvements now.

**Comment by wadeking98** [comment]
Yes, this is still an issue. For the 1 hour - 1 day window we see missing metrics sometimes. For lager windows like 2 weeks most of the data is there

**Comment by ShellyXueHan** [comment]
### Update:
The limits that we are hitting now:
- Gold and Golddr - prometheus metrics ~18K
- Silver custom metrics

Tuning to be continued!

**Comment by ShellyXueHan** [comment]
### Update:
- we've disable several unused operational metrics
- still hitting limits: JMX for silver and prometheus in Gold and Golddr
- need to find more unused metrics, or retire some of them in favour of custom app integration metrics

**Comment by ShellyXueHan** [comment]
### Update:

We couldn't find more metrics types that can be disabled safely at the moment. Long term plans are set instead! Billy will start to work with Sysdig to develop better training material to focus on application specific metrics in stead of general ones. This will gradually release the general metrics from teams, and then we can disable them for space.
