### ISSUE TITLE
Implement project creation Unit testing on registry web app

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1318]
After the initial pipeline work has been completed, new Unit testing should be added to the registry WEB application. 
Initial E2E testing should evaluate the project creation flow which will include:

- [ ] Project Creation flow
  - [ ] All fields validate and no errors on submit
  - [ ] New Project shows in Dashboard approvals (Admin login)
  - [ ] No Dashboard Approvals show (Non Admin user)
  - [ ] New project is marked as pending and cannot be edited
  - [ ] Project can be approved from Dashboard (Admin)
  - [ ] Project shows as provisioned and editing capability is enabled.

Additional tests will be required to validate editing capability.

**Comment by lukegonis** [comment]
@okanji can you please review the scope of this issue and adjust it as you see fit/confirm it still applies

**Comment by okanji** [comment]
@lukegonis, there is no point in still doing this as we are crating the new registry API that will have its own unit testing. I think we can close this

**Comment by ShovelHand** [comment]
As per Oamar's comments from May, I am closing this issue.
