### ISSUE TITLE
Update backup container

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#132]
- [ ] Split out the block vs file performance stuff into its own documentation.
- [ ] Add some more details about how to actually set up the backup container.
- [ ] Add an option for building your own templates instead of using the shell script.

**Comment by jleach** [comment]
@caggles Looks like Wade just released an updated backup container today.

**Comment by lukegonis** [comment]
Next step is to determine if Wade's updated backup container covers this.
