### ISSUE TITLE
Prepare Pipeline for Artifactory Operator (archeobot)

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#1325]
**Describe the issue**
Create a pipeline for the automated deployment of the Artifactory operator, archeobot.

**Additional context**
Details to come

**Definition of done**

- [ ] Identify requirements for automated operator deployment
- [ ] additional completion requirements to come

**Comment by caggles** [comment]
We will be using CCM for Archeobot, not a traditional pipeline, so this ticket is no longer appropriate.
