### ISSUE TITLE
Deploy RocketChat in Gold/Gold DR

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1326]
As a primary communications tool for Platform Community, RocketChat can be considered an essential service. As such, it should be deployed to extra HA Gold tier and configured with a geographic failover to Gold Calgary to increase its realiability. 

DoD:
- [x] RocketChat app deployed to Gold Kamloops and Gold Kalgary, data replication and geographic failover is enabled

**Comment by jleach** [comment]
Note: We're considering moving RC to ARO or AWS. Few meetings over the next few days with the cloud pathfinder team to discuss.

**Comment by mitovskaol** [comment]
Note: RC will be moving to Gold/Gold DR as was originally planned. We will pick another app to move to AWS ECS.
