### ISSUE TITLE
Roll Out GitHub Direct Access for PS and KeyCloak Teams in Silver

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1327]
User authentication for access to the Openshift 4 Console in the Silver cluster is currently only available via the KeyCloak SSO. The KeyCloak SSO service runs as an app on the same cluster. If the service is experiencing an outage, access to the Console and to the app namespaces is not available and the KeyCloak SSO team is unable to troubleshoot the app to restore the service. Therefore, we will be building an alternative access **for admin users** to the Openshift 4 Console that bypasses the KeyCloak SSO.

DoD:
- Build an integration between the Silver Openshift 4 Console and GitHub's private `bcgov-platform-services` org  that allow users that are part of the org and have 2FA enabled, access the Console.
- Create a new login page with 2 login options: `Developer Access with BC Gov SSO Service` and `Platform Services Access Only`. Option 1 will redirect to the KeyCloak login page , option 2 to GitHub for user authentication.
- Update RBAC scripts to copy the permissions that Platform Services and Ops team members have for their SSO-authenticated account (i.e. XXX@github) to the direct GitHub access account so that no mattere what authentication option they chose, they would get the same level of access
- Traing the KeyCloak Support team on using the option 2 for authentication and how to replicate their current namespace level access for SSO authentication to their direct GitHub access accounts.

**Comment by j-pye** [comment]
Draft PR with base templates that still need to be modified
https://github.com/bcgov-c/platform-gitops-gen/pull/226
