### ISSUE TITLE
Developer access to SIEM for app container logs

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1331]
**Describe the issue**
OpenShift logs now shipped to OCIO SIEM.  Need to ensure teams can access their own container logs on that platform if they desire/require longer term container log retention.  

**Additional Context**
- VPN required to access SIEM UI
- Container logs currently retained for 2 months on SIEM

**Definition of done**
- [x] Work with SecOps to ensure they can support access model they have defined

**Comment by NickCorcoran** [comment]
Apparently, OCP 4.8 has JSON log format available, and parsing down to the pod level.  This could make it much easier.  It is detailed as Logging 5.1, so reaching out to RH to see if that could work w/ OCP 4.6, or if we have to wait til 4.8.

https://youtu.be/fhL36ql_sqQ?t=5915

**Comment by mitovskaol** [comment]
@NickCorcoran Can you please set up a meeting with the SIEM team to discuss adding KeyCloak integration into the product in order to enable developer access to it.

**Comment by NickCorcoran** [comment]
Have discussed with SecOps and KeyCloak team.
Have provided content for DevOps Request to SecOps for submission tracking for KeyCloak client creation.  Access to be IDIR only.
|
Once connectivity confirmed, to work with SecOps on creating an access request form/process that is sustainable.
|
Data parsing still has to happen to break out by project space, but we do have at least one team that has done this already, so pattern should be easily leveraged.  SecOps to work on this soon.

**Comment by NickCorcoran** [comment]
Added Conrad so KeyCloak team is aware of tracking on our side.

**Comment by ConradBoydElliottGustafson** [comment]
@NickCorcoran Thanks Nick. On our side it's all good -- just waiting for a request.
