### ISSUE TITLE
Prepare and run a Developer Workshop for Building Dashboards with Sysdig

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1332]
In order to expand adoption of the Sysdig Monitoring Service on the Openshift 4 Platform, we need to prepare the materials and run a hands-on developer workshop for how to build  app monitoring dashboards with Sysdig.

DoD:
- update the [self-help docs](https://developer.gov.bc.ca/OpenShift-User-Guide-to-Creating-and-Using-a-Sysdig-Team-for-Monitoring) to include more examples if needed
- prepare a deck and lab materials
- run the developer workshop

**Comment by ShellyXueHan** [comment]
### Update:
- will get start with preping demo
- currently discussing with sysdig support to see if there are ways to improve sysdig team setting, would be great to do a formal demo when that's determined

**Comment by mitovskaol** [comment]
@ShellyXueHan I believe this workshop already happened and this ticket can be closed. LMK

**Comment by ShellyXueHan** [comment]
yes we've had community demos as well as videos and documentation in place. Good to close now!
