### ISSUE TITLE
Need a proactive test for OCP application performance issues

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1343]
**Describe the issue**
We currently are able to replicate performance issues during the time when F5 was affecting SILVER by using a test URL originally provided by Karim. We need to create our own unique test URLs that no longer use Karim's app and can be used going forward and monitored for response times to at least determine if there some sort of "issue" happening, regardless of root cause.

**Additional context**
Nagios may be one option to remotely monitor response times, provided there's a module that can work on alerting on response times if over a certain threshold. May or may not pursue a native Openshift solution as well, but may not be for the best. Perhaps UptimeRobot as another option?

**Definition of done**
- [x] Work out a suitable replacement for Karim's test application tests including persistent storage
- [x] Determine which tools can be used to properly monitor response times for the test replacement
- [x] Implement and test the solutions involved

**Comment by wmhutchison** [comment]
Current test is as follows.

```
$ wget --output-document=/dev/null https://nginx-container-wmhutchison-test.apps.silver.devops.gov.bc.ca/test-payload.js
--2021-07-21 15:28:02--  https://nginx-container-wmhutchison-test.apps.silver.devops.gov.bc.ca/test-payload.js
Resolving nginx-container-wmhutchison-test.apps.silver.devops.gov.bc.ca (nginx-container-wmhutchison-test.apps.silver.devops.gov.bc.ca)... 142.34.194.118
Connecting to nginx-container-wmhutchison-test.apps.silver.devops.gov.bc.ca (nginx-container-wmhutchison-test.apps.silver.devops.gov.bc.ca)|142.34.194.118|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5561603 (5.3M) [application/javascript]
Saving to: ‘/dev/null’

100%[====================================================================================================================================================================================>] 5,561,603   --.-K/s   in 0.03s   

2021-07-21 15:28:02 (200 MB/s) - ‘/dev/null’ saved [5561603/5561603]
```

**Comment by wmhutchison** [comment]
This test needs to be reconfigured to belong to its own unique namespace, perhaps `openshift-bcgov-canary` and then injected into CCM so that all clusters can benefit from this sort of test.

Setting this up in Nagios (I believe it supports HTTP latency response monitoring) is an obvious item. Will also explore local app monitoring inside Openshift itself (in case Nagios is acting up).

Will likely require tweaking over time, but once done, should offer a proper proactive metric regarding cluster web response time that's been consistent in the past when reporting F5 slowdown issues similar to what was experienced in May 2021.

**Comment by StevenBarre** [comment]
I'll be taking this on.

**Comment by StevenBarre** [comment]
Progress in https://github.com/bcgov-c/platform-tools/pull/48

Currently the traffic path is going through our corp proxy and then back in via SiS. This seems to be slow and unreliable (most likely the proxy). Waiting on some networking changes to allow going direct from Nagios to the F5 and bypass the proxy.

**Comment by StevenBarre** [comment]
Network changes completed for KLAB and tested. SNAT changes for the rest of the clusters scheduled for Tue the 24th.

![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/b8d29302-7710-4502-aa46-32f8234385bd)

**Comment by StevenBarre** [comment]
All clusters are not monitoring the speed of downloading a 5MB file.
