### ISSUE TITLE
SysDig Access not complete for all Platform Operations

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1345]
**Describe the issue**
Since discovery work had Tatsuya ask internally if he has access to Sysdig. It turns out he does not, and neither does Tim.

**Additional context**

**Definition of done**
- [x] Confirm if other Platform Operations staff have the ability to add new users (William)
- [x] Self-serve add new accounts for both Tatsuya and Tim.

**Comment by tmorik** [comment]
confirm Tats and Tim can now login and see the graphs.
