### ISSUE TITLE
GOLDDR CCM prep - create new Github repositories

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1346]
**Describe the issue**
CCM install docs need new Github repositories. While this ticket is mainly for GOLDDR, combining the need for a KLAB2 repo as well.

**Additional context**
Github user `wmhutchison` should be owner and/or admin on these repos so that user can make core changes to the repos as necessary to complete CCM setup.

**Definition of done**
- [x] Assign ticket to whoever can or will do the work.
- [x] Confirm existence and accessibility for repo `platform-gitops-calgary-golddr`
- [x] Confirm existence and accessibility for repo `platform-gitops-kamloops-klab2`

**Comment by j-pye** [comment]
Both repositories have been created and the access has been granted to the advsol team on github. GoldDR repository has already been integrated with CCM.
