### ISSUE TITLE
NetAPP Storage Question - How does the netapp-file-backup storageclass work

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1348]
**Describe the issue**
Per Justin Pye's question.
```
Does netapp-file-backup backup somewhere off site? Just wondering, in the event of a namespace deletion or PVC deletion, is there a way for teams to still recover their data if that storage class was used?
```

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Ask DXC Storage team via internal question ticket
- [x] Pass answer back when found.

**Comment by StevenBarre** [comment]
@j-pye https://developer.gov.bc.ca/OCP4-Backup-and-Restore should answer most of your question.

**Comment by wmhutchison** [comment]
Link above points you to https://ssbc-client.gov.bc.ca/services/AppHosting/base.htm#databackup which is an OCIO link. Backups are stored offsite, and aged out as appropriate.

Restore requests are brought in via Service request which gets handled by DXC stakeholders.
