### ISSUE TITLE
RocketChat takes a very long time to load.

### ISSUE THREAD

**Issue by davidedwardclark** [BCDevOps/developer-experience#135]
It takes so long in fact that it is essentially down. I get a loading animation that won't go away. This has happened on several occasions in the last half year.

Doing a hard refresh or opening RC in a new tab does not fix the problem.

I have noticed the issue in Chrome on both PC, and Mac.

**Comment by mitovskaol** [comment]
This should have been fixed by the recent upgrade and the RC migration to OCP 4
