### ISSUE TITLE
Artifactory Proxy/Remote Repository to k8s.gcr.io

### ISSUE THREAD

**Issue by cvarjao** [BCDevOps/developer-experience#1361]
**Describe the issue**
Add a remote proxy repository to `k8s.gcr.io`

**Additional context**
For pulling public images available from `k8s.gcr.io`
- related to : https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2052

**Definition of done**
- An Artifactory repository is created (e.g.: `k8s-gcr-io`)
- Repository is available for pulling images (e.g.:  `https://artifacts.developer.gov.bc.ca/k8s-gcr-io`)

note: Names above are provided as example, I have no expectation that it will be the final name.

**Comment by caggles** [comment]
done! the name of the new repo is google-docker-remote. I will be making a post about this in devops-artifactory after I've added/tested a few other repos.
