### ISSUE TITLE
New Red Hat Entitlement Certs need to be pushed out to Tools namespaces

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1365]
**Describe the issue**
Custom monitoring on KLAB detected new Red Hat entitlement certs. A PR has been created to update the repo 

**Additional context**
PR: <https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/35>

**Definition of done**
- [x] Confirm PR is approved/merged.
- [x] Resync Project Registry with new certificate content

**Comment by j-pye** [comment]
Registry Sync Completed July 6th @ 11:55AM
