### ISSUE TITLE
Generate CSRs for CLAB cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1375]
**Describe the issue**
Tracking effort spent towards creating new CSRs and private keys for the API and APPS wildcard certs for the CLAB cluster.

**Additional context**
Source URL for how to generate new CSR's: <https://github.com/bcgov-c/platform-ops/blob/ocp4-base/ocp4/roles/config-api/README.md#tls-certs>
Post full directory path to where CSR and private certs on CLAB-util host reside: 
CSR created on CLAB-UTIL server at
/root/csr-api-clab-2021-07-07

**Definition of done**
- [x] Generate new directory and CSR's.
- [x] Update ticket with full path of new content.

**Comment by tbaker1313** [comment]
CSR created on CLAB-UTIL server at 
/root/csr-api-clab-2021-07-07
