### ISSUE TITLE
Generate CSRs for SILVER cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1376]
**Describe the issue**
Tracking effort spent towards creating new CSRs and private keys for the API and APPS wildcard certs for the SILVER cluster.

**Additional context**
Source URL for how to generate new CSR's: <https://github.com/bcgov-c/platform-ops/blob/ocp4-base/ocp4/roles/config-api/README.md#tls-certs>
Post full directory path to where CSR and private certs on BASTION host reside: 
- The Path for CSR is /root/csr-api-silver-2021-07-07 on SILVER-UTIL server.

**Definition of done**
- [x] Generate new directory and CSR's.
- [x] Update ticket with full path of new content.

**Comment by tmorik** [comment]
The Path for CSR is `/root/csr-api-silver-2021-07-07` on `SILVER-UTIL` server.
