### ISSUE TITLE
R&D: ArgoCD for Dev Teams MVP

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1378]
**Describe the issue**
As the platform services team, we'd like to provide access to ArgoCD to development teams on the platform. 

**Additional context**
- ArgoCD for Dev teams should be deployed as a standalone instance through CCM 
- ArgoCD Access should be done using keycloak - This will likely require a custom operator so that teams can self-serve who has access to their projects. (This is a crawl step, not a run step even though it's a big chunk of work)
- Teams should be broken down into AppProjects or ApplicationSets - SPIKE/R&D needed
- GitOps repositories should be created for each team in bcgov-c whether through devops-requests or a Project Registry Microservice
- ArgoCD Project Applications should be limited to the same access as the Namespace Admin Role in OpenShift
- ArgoCD API access for teams is outside the scope of the MVP
- The CCM Instance and Teams instance will need to be thoroughly tested together in KLAB or CLAB to ensure there is no overlaps or excessive reconciling

A full MVP Proposal / Requirements will be linked here in the future.

**Comment by mitovskaol** [comment]
@j-pye @IanKWatts  Can this EPIC now be closed? it looks like the R&D work for the shared instance of ArgoCD has been complete.

**Comment by IanKWatts** [comment]
@mitovskaol I think so.  The Warden Operator hasn't been rolled out for testing yet, but its purpose has been defined.
