### ISSUE TITLE
Create DNS record + SSL Cert for new KC SSO

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#138]
Brife content:
1. create DNS record for `oidc.gov.bc.ca` and `*.oidc.gov.bc.ca`
2. get GCPE approval

**Comment by lukegonis** [comment]
**oidc.gov.bc.ca**

- domain name registration form (GCPE PDF Doc) and DNS form (iStore form) submitted to both GCPE IS Joint Delivery Working Group and CITZIMBSD, now awaiting GCPE IS Joint Delivery Working Group approval
-Once GCPE IS Joint Delivery Working Group approves, I will forward their email approval to CITZ DNS Request, SPAN/BC CITZ:EX
- SSL Cert form (iStore form) submitted to CITZIMBSD

***.oidc.gov.bc.ca**

- domain name registration form (GCPE PDF Doc) and DNS form (iStore form) submitted to both GCPE IS Joint Delivery Working Group and CITZIMBSD, now awaiting GCPE IS Joint Delivery Working Group approval
-Once GCPE IS Joint Delivery Working Group approves, I will forward their email approval to CITZ DNS Request, SPAN/BC CITZ:EX
- Wildcard cert form (obscure word doc) submitted to our ministry service manager (Ashley Armstrong) for her approval
- Once wildcard cert form (obscure word doc) is approved by ministry service manager, SSL Cert form (iStore form) can be submitted to CITZIMBSD

lol

**Comment by lukegonis** [comment]
[https://app.zenhub.com/files/220104031/b6994f51-15fa-47b8-b307-c07d113c21bd/download](https://app.zenhub.com/files/220104031/b6994f51-15fa-47b8-b307-c07d113c21bd/download)

**Comment by lukegonis** [comment]
[https://app.zenhub.com/files/220104031/788445e6-de0a-4131-b1fd-566f3b7a401e/download](https://app.zenhub.com/files/220104031/788445e6-de0a-4131-b1fd-566f3b7a401e/download)

**Comment by ShellyXueHan** [comment]
@lukegonis that's amazing thanks bro!

**Comment by ShellyXueHan** [comment]
Update:
*.oidc is rejected, now that looks like we need to submit the three SSL cert iStore orders:
- oidc.gov.bc.ca
- test.oidc.gov.bc.ca
- dev.oidc.gov.bc.ca
- *.sbox.oidc.gov.bc.ca (TBD for sandbox keycloak instances)

**Comment by ShellyXueHan** [comment]
iStore ticket created: http://imbsd.gov.bc.ca/Ticket/52244

**Comment by ShellyXueHan** [comment]
Updates:
- ssl certs have been created
- waiting on Domain Name Registration. still getting `server IP address could not be found.`

**Comment by ShellyXueHan** [comment]
Update:
- DNS records created
- re-started the SL Cert request for wildcard

**Comment by ShellyXueHan** [comment]
Update:
wildcard cert is rejected. Getting Nick's help for an exemption applied.

**Comment by ShellyXueHan** [comment]
Update:
@NickCorcoran got progress on this and looks like we do not need an exemption, but need to attach a new signed form. So a new request has been initiated. Waiting on that now.

**Comment by NickCorcoran** [comment]
@ShellyXueHan, that was the form I provided w/ Justin's signature, correct?

**Comment by ShellyXueHan** [comment]
Yea yea I'm just putting the updates here to keep track. (And I don't remember the form name....) Pls correct me if I'm wrong about what's happening.

**Comment by NickCorcoran** [comment]
All good - Wildcard certificate application form
https://ssbc-client.gov.bc.ca/services/SSLCert/documents.htm

**Comment by ShellyXueHan** [comment]
got the wildcard cert completed! Closing ticket.
