### ISSUE TITLE
Renew Wildcard Cert for *.developer.gov.bc.ca 

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1390]
**Describe the issue**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] submit istore order
- [x] ims@gov.bc.ca emails technical contact 
- [x] Shelly Generates CSR and replies to ims@gov.bc.ca
- [x] shelly install the new cert to all apps using it

### Apps using this cert:
- [x] registry.developer.gov.bc.ca
- [x] reggie.developer.gov.bc.ca
- [x] mss.developer.gov.bc.ca

**Comment by ShellyXueHan** [comment]
@lukegonis not done yet, we still got 2 more apps that need the route update.
