### ISSUE TITLE
Statuspage knowledge transfer

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#14]
**Is your feature request related to a problem? Please describe.**
@stewartshea built the statuspage (https://github.com/BCDevOps/platform-services/tree/master/apps/statuspage). It's temporary down. The platform service team need documentation and a knowledge transfer from Shea.

**Definition of Done**
- Bring up the app
- the team has the knowledge about it
- documentation

**Comment by lukegonis** [comment]
No longer relevant
