### ISSUE TITLE
Develop Xray templates

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#1403]
**Describe the issue**
Xray typically gets installed via helm, which won't work on Openshift - the existing helm template doesn't work properly. We should develop some templates instead.

**Definition of done**
- [x] set of templates that attempts installation in lab
- [x] helm vars that produce the template
- [x] documentation on changes between helm-produced template and actual template

**Comment by mitovskaol** [comment]
@caggles Just an idea - can we maybe reach out to JFrog for help with customizing the helm charts to work in our Openshift environment?
