### ISSUE TITLE
Replace pathfinder email with new PlatformServicesTeam in all our docs and accounts

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1406]
As we not have a new generic team mailbox `PlatformServicesTeam@gov.bc.ca` , we need to do search and replace all reference to the old pathfinder email in all our resources (docs, issue templates, etc) and in accounts (corporate Google account, next gen security tool accounts, etc) with the new mailbox.

**Comment by ShellyXueHan** [comment]
duplicate of https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1320
