### ISSUE TITLE
Deploy ArgoCD Notification with CCM

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1432]
Definition of Done:
- [x] ArgoCD role updated to support notifications
- [x] Role Tested in KLAB
- [x] PR added to issue comments
- [x] PR merged for CCM integration

**Comment by IanKWatts** [comment]
PR for notifications support via CCM: https://github.com/bcgov-c/platform-gitops-gen/pull/324

**Comment by IanKWatts** [comment]
Argo CD Notifications have been enabled in all clusters via CCM as of December 16, 2021.
