### ISSUE TITLE
Access to bcgov-c github org

### ISSUE THREAD

**Issue by poornima-sivanand** [BCDevOps/developer-experience#1438]
**Describe the issue**
Require access to graphana boards on Klab cluster for the openshift quota analysis work with Justin. Need to be added to the file : https://github.com/bcgov-c/platform-gitops-gen/blob/master/inventory/group_vars/all/rbac.yaml#L8

**Definition of done**
 - Access to bcgov-c to be able to create a pull request to : https://github.com/bcgov-c/platform-gitops-gen/blob/master/inventory/group_vars/all/rbac.yaml#L8
 - Access to graphana boards on the Klab cluster

**Comment by ShellyXueHan** [comment]
both access added
