### ISSUE TITLE
Keycloak SSO Instance Migration to OCP 4

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#144]
This is to migrating our KeyCloak instances to a new DNS name, aiming to facilitate the change from a pathfinder service to a BCGov service. Application teams using SSO service will be impacted as well.

### Community involvement
- channel notification
- relevant documents for the migration
- setup pull request to serve as samples for application SSO updates

### Tasks for the platform service team:
- request for new DNS record
- test out the impact on keycloak in a multi-domain setup
- setup migration plan to the new DNS
- setup migration plan to OCP4 cluster
- migrate keycloak

**Comment by mitovskaol** [comment]
@ShellyXueHan Can this be closed now since the KeyCloak app has migrated to Silver?
