### ISSUE TITLE
Copy vault init container image locally so that image pulls don't fail

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1449]
## Description

The vault init container is pulled from docker hub where we run into image pull quota issues:

```
Failed to pull image "docker.io/hashicorp/vault:1.7.3": rpc error: code = Unknown desc = Error reading manifest 1.7.3 in docker.io/hashicorp/vault: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

## Done When

- [x] Either the image pull SA is using a secret with proper cluster credentials or the image is routed locally (or artifactory) so that we do not run into quota issues.

**Comment by jleach** [comment]
@sbathgate This exists.

**Comment by jleach** [comment]
@sbathgate And this.

**Comment by j-pye** [comment]
We have the new global pull secret and I've also created a shared image stream that will be applied when we do the next production deployment. Closing.
