### ISSUE TITLE
Uptime Robot - list of monitors to include in status page

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1451]
**Describe the issue**
Decide on the list of cluster and services monitors to display on the status page.

### Ref:
Status page: https://status.developer.gov.bc.ca/
Our supported services: https://drive.google.com/file/d/1pvaxCdYts1MeRv7bHP10a1yt_MGk6KpK/view 

### List of services to include on status page:
- Silver Cluster Openshift Service
- Gold Kamloops Cluster Openshift Service
- Gold Calgary Cluster Openshift Service
- Artifactory Service
- Aqua Service
- Vault (endpoint TBD)
- KeyCloak SSO (prod only as other ones don't affect apps) Service
- RocketChat Service
- Registry
- EnterpriseDB Operator (TBD??? marked as essential)

**Definition of done**
- [x] decide on the list
- [x] decide on the order and naming that appears on status page
- [x] create monitor and see if endpoint is good measure
- [x] add monitor to status page

**Comment by juhewitt** [comment]
@ShellyXueHan  @mitovskaol reminder that this is our service catalogue: https://drive.google.com/file/d/1pvaxCdYts1MeRv7bHP10a1yt_MGk6KpK/view?usp=sharing

So keep that in mind as you flush out what we and our partners want to see for our products availability in our ecosystem.  

@marthaedwards

**Comment by juhewitt** [comment]
secondly, like you already did @mitovskaol from you user research on the experience, check in with @marthaedwards on 'building' it out, and then just testing it with our user base too as part of our service journey...
