### ISSUE TITLE
2021 OCP4 Cert Renewal - Replace certs on CLAB

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1464]
**Describe the issue**
Replace older certs about to expire on the named cluster with their signed replacements. 

**Additional context**
Testing on KLAB both confirmed that no node drain/restarts will happen due to the cert replacement.

**Definition of done**
- [x] Create new branch/PR for replacement certs
- [x] Merge PR for replacement certs if not already done.
- [x] Run playbook to replace API cert
- [x] Run playbook to replace APPS cert

**Comment by tmorik** [comment]
PR: https://github.com/bcgov-c/platform-ops/pull/387

**Comment by tmorik** [comment]
Merged PR and run the playbooks for API and APP certs refresh. Both playbooks successfully done and certs have been updated for another one year:

```
[root@mcs-clab-util ]# curl -vk https://api.clab.devops.gov.bc.ca:6443/ |& grep date
*       start date: Jul 26 18:55:56 2021 GMT
*       expire date: Aug 24 18:55:55 2022 GMT
[root@mcs-clab-util ]# curl -vk https://blat.apps.clab.devops.gov.bc.ca/ |& grep date
*       start date: Jul 29 20:52:42 2021 GMT
*       expire date: Aug 28 20:52:42 2022 GMT
```
