### ISSUE TITLE
2021 OCP4 Cert Renewal - Replace certs on SILVER

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1465]
**Describe the issue**
Replace older certs about to expire on the named cluster with their signed replacements. 

**Additional context**
Testing on KLAB both confirmed that no node drain/restarts will happen due to the cert replacement.

**Definition of done**
- [x] Create new branch/PR for replacement certs
- [x] Schedule suitable RFC for execution and receive approval.
- [x] Merge PR for replacement certs if not already done.
- [x] Run playbook to replace API cert (under scheduled RFC)
- [x] Run playbook to replace APPS cert (under scheduled RFC)

**Comment by wmhutchison** [comment]
Sprint Backlog for now until we get an RFC scheduled and approved for this.

**Comment by tmorik** [comment]
PR: https://github.com/bcgov-c/platform-ops/pull/389

**Comment by wmhutchison** [comment]
Moving to In Progress since we have this scheduled for implemention before end of Sprint.

**Comment by wmhutchison** [comment]
CHG0028459 was successfully applied during its change window (after 6pm on August 8th 2021). Closing ticket.
