### ISSUE TITLE
2021 OCP4 Cert Renewal - Replace certs on GOLD

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1466]
**Describe the issue**
Replace older certs about to expire on the named cluster with their signed replacements. 

**Additional context**
Testing on KLAB both confirmed that no node drain/restarts will happen due to the cert replacement.

**Definition of done**
- [x] Create new branch/PR for replacement certs
- [x] Schedule suitable RFC for execution and receive approval.
- [x] Merge PR for replacement certs if not already done.
- [x] Run playbook to replace API cert (under scheduled RFC)
- [x] Run playbook to replace APPS cert (under scheduled RFC)

**Comment by wmhutchison** [comment]
Sprint Backlog for now, need to get an RFC date/time worked out and approved first.

**Comment by tmorik** [comment]
PR created: https://github.com/bcgov-c/platform-ops/pull/391

**Comment by wmhutchison** [comment]
PR passed QA and is approved for merge during RFC.

RFC also now scheduled, CHG0028501 for execution next Monday (August 9th 2021) during business hours. Olena has already approved the RFC. Moving this into In Progress, and the timing is such that this will be completed at the very end of the Sprint.

**Comment by wmhutchison** [comment]
CHG0028501 successfully executed for installing new certs in GOLD. Can close this ticket.
