### ISSUE TITLE
2021 OCP4 Cert Renewal - Decision Point for Scheduling PROD RFCs for SILVER and GOLD

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1469]
**Describe the issue**
Now that both CLAB and KLAB have had their renewed certificates applied without issue, we need to start thinking about suitable RFC dates/times for doing the same for SILVER and GOLD. SILVER being the cluster under full production load, the following considerations need to be thought about.

- granting enough lead time for proper notifications via #devops-alerts channel. Would not recommend trying to squeeze SILVER RFC into this week.
- decide if after-hours weekday or weekend (Sunday evening) is best
- decide if regular after-hours (ie: 6pm) is enough, or if you want to go with recommended after-hours for Wildfire which is after sunset (11pm is often chosen for that scenario).
- an RFC would be created with a 2 hour change window, but actual implementation time would be 15 minutes or less.

**Additional context**
We have successfully applied the renewed certificates in both the KLAB and CLAB clusters without issues involving nodes having a drain/reboot sequence being triggered. The same playbooks are used for SILVER/GOLD, thus should not trigger this event there either.

**Definition of done**
- [x] Review and make considerations of appropriate change dates/times for SILVER RFC, GOLD RFC will follow similar change activity 
- [x] Update relevant tickets in EPIC for SILVER and GOLD with proposed RFC date/times

**Comment by wmhutchison** [comment]
Some suggestions for suitable RFC dates/times.

- For a weekend RFC window for SILVER, perhaps this Sunday (August 8th) at 6:00pm. 
- For a weekday after-hours window for SILVER, perhaps next Tuesday (August 10th) at 6:00pm.
- GOLD RFC could readily be still scheduled during business hours due to its state of not quite being fully in use by regular users. Would pick an RFC date of 1-2 business days after SILVER.
- proposed SILVER times could be also adjusted for Wildfire if desired (ie: 10pm instead of 6pm).

**Comment by mitovskaol** [comment]
@wmhutchison  @juhewitt's and mine recommendation is to run this maintenance as soon as possible (and as soon as you feel ready). From the suggestions above, it looks like the earliest opportunity would be Sunday Aug 8 at 6pm. If, however, you'd prefer to apply this change sooner, we are ok with going ahead with it on **any weekday this week after 5:30pm**.  Please post the announcement in the #devops-alerts channel as soon as you pick the date and directly ping the 2 wildfire teams as a courtesy to let them know that it is coming up. Thanks!

**Comment by wmhutchison** [comment]
RFC for SILVER now scheduled for Sunday August 15th at 6pm. RFC is approved, and communications have gone out.

Will get RFC for GOLD created/apprroved by Friday, aiming for next Monday.

**Comment by wmhutchison** [comment]
All RFCs scheduled and have been approved by Olena. Can close this ticket since decision points as requested were made.
