### ISSUE TITLE
Rocketchat mongodb performance issue

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#148]
Plan on the follow up issue fixing:
1. update current mongodb settings:
   - pvc storage type to netapp-block-standard
   - increase CPU and memory (have a more stable instances first)
   - make a backup first before starting all these
   - please also see reference here: https://github.com/BCDevOps/platform-services/pull/603
2. fix corrupted data in another maintenance outage so that it's easier to identify issues

Track the actions taken so far:
- get in mongo terminal: `mongo admin -u admin -p $MONGODB_ADMIN_PASSWORD`
- inside mongo terminal: check the rs syncing status `rs.printSlaveReplicationInfo()`
- reconfiging replicaset:
```
rs.reconfig({_id: "rs0", version: 2, members: [
       { _id: 0, host : "mongodb-0.mongodb-internal.e5imao-prod.svc.cluster.local:27017", priority : 0.5 },
       { _id: 1, host : "mongodb-1.mongodb-internal.e5imao-prod.svc.cluster.local:27017", priority : 0.5 },
       { _id: 2, host : "mongodb-2.mongodb-internal.e5imao-prod.svc.cluster.local:27017", priority : 0.5 },
       { _id: 3, host : "mongodb-3.mongodb-internal.e5imao-prod.svc.cluster.local:27017", priority : 1 }
 ]}, {force:true});
```

**Comment by ShellyXueHan** [comment]
link to retro-meeting results:
- https://github.com/BCDevOps/developer-experience/blob/jk-rc-outage-review/docs/rocket.chat-outage.md

**Comment by ShellyXueHan** [comment]
Plan for the fix: @caggles @filiy please review and comment

- scale down RC app
- bring up RC route to serve the error message page
- get a dump of the current db
- delete the current statefulset, remove the gluster-file pvc (do not delete the secret!)
- once all clear, use new template to bring up a whole new statefulset (https://github.com/BCDevOps/platform-services/pull/603)
- restore db according to readme
- wait for the replica set to get back
- start reindexing process according to the doc (https://github.com/BCDevOps/platform-services/pull/603/commits/8714f29f052570514f70bdd95321226239c3b272)
- bring up app with new template (updated health probe delay and hpa)
- recreate the app route
- test

**Comment by caggles** [comment]
Further investigation yesterday has turned up a probable solution to the issue. We found that reindexing each mongodb node resulted in the index shrinking slightly and, more importantly, the CPU usage for high-volume queries dropped significantly. Moving to netapp-block instead of gluster-file also improves stability very noticeably. Today, we plan to perform both of these changes in prod.

**Comment by ShellyXueHan** [comment]
Update:

reindexing and storage class update are done. Documented here: https://github.com/BCDevOps/platform-services/pull/603
