### ISSUE TITLE
Custom RBAC mtg w/ AG to review new roles and their fit

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1488]
- [x] Describe new roles added to OCP
- [x] Review with Ryan and team and identify if they meet their needs (Ryan, I can fit into your schedule if you can setup).
- [ ] Adjust as needed

https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1050

**Comment by rloisell** [comment]
@NickCorcoran  - I am away the rest of this week, will work towards scheduling this when I get back.

**Comment by NickCorcoran** [comment]
Meeting setup for 31 Aug 2021.

**Comment by NickCorcoran** [comment]
Meeting delayed to Sept 20th due to availability.  @rloisell suggest you test out the new roles in Silver and we can adjust if needed before this meeting.

**Comment by NickCorcoran** [comment]
Meeting completed.  More work to be done as separate ticket(s) in line w/ Community and Platform Priority #9
