### ISSUE TITLE
Migrate Documize app to AWS ECS

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1491]
We would like to investigate and document the experience of moving a typical app with a database component from the on-prem Openshift Silver cluster to the government tenancy in AWS ECS. The Documize app has been picked for this exercise because it is a non-critical app that does not depend on the DevSecOps tools running on-prem so it should be relatively easy to move it to a new hosting environment. In addition, the Documize app has a database component (PostgreSQL, HA-enabled using Patroni) which will allow us to evaluate the migration from a local database to the DBaaS (DocumentDB) that us available in AWS.

DoD: 
- all 4 environments for the Documize app (dev/test/tools and prod) have been migrated in AWS ECA 
- the migration process is documented in `openshift-wiki` repo including the lessons learned, pro tips and challenges encountered during the migration

**Comment by jleach** [comment]
Met with on-boarding team and have environments provisioned. Using my own RDS and ECS for R&D. Will move work to our environments next.

**Comment by jleach** [comment]
Additional on-boarding meeting today. Walked through sample project setup. Tomorrow is the 3rd and final meeting with Max where we deploy the sample application to our environments.

**Comment by ShellyXueHan** [comment]
updates:
- need to decide on who have capacity to work on this
- I can provide some KT on both documize itself and aws onboarding
