### ISSUE TITLE
Create App Architecture diagram for Resource App

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1498]
**Describe the issue**
Create an app architecture diagram to understand the different components and integrations for Resource Tuning Advisor Application

** Additional information**
Any supporting information

**Definition of done**
When a diagram is complete and available as an asset within the Resource App repo

**Comment by poornima-sivanand** [comment]
Completed First Draft of architecture diagram -> available at https://github.com/BCDevOps/openshift-quota-rec/blob/main/images/Architecture.png. 
Also attaching a copy to this ticket.![Architecture.jpg](https://images.zenhubusercontent.com/5f91c4c3ca944520a1ee33ae/020fd4c0-5bc2-46a7-9c64-7e04ffa5bc66)

**Comment by juhewitt** [comment]
@NickCorcoran Poornima will have to create some additional tickets for STRA, PIA etc.  I wanted you to see holistically what this app is doing at a high level.  Code and documentation is in private repo.  

@patricksimonian I wanted you to get some insight into what this looks like, as your existing report plus new report with hiring will be working on this in some capacity.

**Comment by poornima-sivanand** [comment]
The new version can be found [here.](https://github.com/BCDevOps/openshift-quota-rec/blob/main/images/architectureV1.1.jpg![architectureV1.1.jpg](https://images.zenhubusercontent.com/5f91c4c3ca944520a1ee33ae/3c59f181-fde5-4282-aa94-84dca637e066))

**Comment by lukegonis** [comment]
This is now complete
