### ISSUE TITLE
Update postgresql connections

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#150]
Looking at the Artifactory logs shows multiple connection errors:
org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections

Looks like artifactory default connection pool is 50, and the postgres DB is configured for 100 max connections.  We should look at growing this to manage 3 artifactory front ends + a few spare for operational connections.  Suggest postgres max connections = 200.

**Comment by caggles** [comment]
The number of connections is being increased as part of the upgrade to v7.
