### ISSUE TITLE
Openshift 3.11 Cleanup - Request Decommission of un-needed Rocket Chat channels

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1511]
**Describe the issue**
A total of four Rocket Chat channels were originally set up for use by Openshift 3.11 clusters. 

* `platform-lab-weather`: legacy weather report from the LAB cluster which no longer exists. Definitely can be removed.
* `platform-prod-weather`: legacy weather report from the PROD cluster which no longer exists. Definitely can be removed.
* `platform-lab-alerts`: AlertManager for LAB cluster. Have seen recent activity so might be getting some new use.
* `platform-prod-alerts`: AlertManager for PROD cluster. Have seen recent activity so might be getting some new use.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Investigate channels showing new activity post 3.11 decomm and find out if there's interest in keeping them active.
- [x] Request removal of all Rocket Chat channels that are now confirmed to be no longer required.

**Comment by tbaker1313** [comment]
Determined the recent activity was from a sysdig test alert. No reason a new channel can't be used for these if needed later. Steven is removing these channels now.
