### ISSUE TITLE
Xray Tech Debt

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1515]
The basic installation of Xray is in place in KLAB, but there are some tasks to improve the stability of the installation that should be included in the installation scripts.

- [x] Move from single-instance postgres to HA patroni.
- [x] Investigate the use of S3 buckets for storage instead of such large PVs.
- [x] Add backup container.
- [x] Confirm with JFrog that backup container and S3 are sufficient backups.
- [x] What happens if Xray goes down and Artifactory stays up?

**Comment by caggles** [comment]
s3 buckets aren't feasible for Xray because much of it lives in the DB.
