### ISSUE TITLE
Resiliency/HA and Resource optimization assessment for BC Wildfire application

### ISSUE THREAD

**Issue by michaelshire** [BCDevOps/developer-experience#1518]
Resiliency/HA and Resource optimization assessment for BC Wildfire application
https://developer.gov.bc.ca/Resiliency-Guidelines
https://developer.gov.bc.ca/Resource-Tuning-Recommendations

**Comment by michaelshire** [comment]
Completed assessment (rev4)
[https://app.zenhub.com/files/220104031/ccc4982f-3616-42fe-b358-7dea02dc90ca/download]

**Comment by sbathgate** [comment]
The report has been delivered to the Wildfire team.
