### ISSUE TITLE
Resiliency/HA and Resource optimization for EBMC application

### ISSUE THREAD

**Issue by michaelshire** [BCDevOps/developer-experience#1519]
BC Gov has requested another app healthcheck for the EMBC app (emergency management BC) - its been in the news quite a lot, with some residents complaining that its not actually providing them with alerts for the wildfires! Olena and Justin are going to reach out to the app team, but they have identified some design flaws they are working through, and would like recommendations for structural improvements and for resolving performance issues.  EMBC Evacuation Service https://ess.gov.bc.ca/ , the prod namespace in Openshift is 9edb33-prod

**Comment by mitovskaol** [comment]
The review has been completed and the final report shared with the EMBC team.
