### ISSUE TITLE
Critical Systems Standard - OCP - Major Incident Management

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1531]
The Response and Recovery Director defines and maintains a separate process (above and beyond for that used for a non-critical system) to respond to a major incident that is impacting business service performance or availability. 

This process should at minimum: 

- [x] Define the recovery team member roles and construct the responsibilities matrix 
- [x] Assign primary and alternate names to the roles 
- [x] Define the procedure to escalate a major incident through the help or service desk to the Recovery and Response Director 
- [x] Establish authority to convene immediately the appropriate Response and Recovery Team members 
- [x] Include a communications plan (channels, medium, timing, etc.) for all stakeholders who need to know the status of the response or recovery 
- [ ] Document procedures for handling vital documents generated during the response and recovery effort 
- [x] Document procedures to ensure the names in the Recovery Team file is up to date

**Comment by sbathgate** [comment]
- Platform Services Team's Support Services documentation [link](https://docs.google.com/spreadsheets/d/1pvaxCdYts1MeRv7bHP10a1yt_MGk6KpK/edit?usp=sharing&ouid=117522969697637793376&rtpof=true&sd=true)
- Platform Services DevSecOps Escalation Script [link](https://docs.google.com/document/d/1eItxLnLQtehVxnf0ykDlkZ8KoHmOC6YlMJJCFXo5-Wc/edit?usp=sharing)
- Platform Services DevSecOps Escalation Flowchart [link](https://app.mural.co/t/platformservices5977/m/platformservices5977/1630361745516/95ef7c6ef41a6329dd54913d14d1280fd567e2c4?sender=u1b7f725325763913e60b4808)
