### ISSUE TITLE
Deploy Rocket.Chat to Gold/DR clusters

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1537]
## Description
Set up RocketChat in Gold, cut over to the Gold instance, and remove the old project set in Silver.

## Done When
- [ ] GSLB request has been completed
- [ ] All resources are created/configured in Gold and Gold DR
- [ ] Create TransportServerClaim CRDs to allow cross-cluster communication
- [ ] Configure data replication for mongodb
- [ ] Configure data replication for the 'rocketchat-uploads' PVC
- [ ] Configure data replication for redis (hubot)
- [ ] Create an an ingress NetworkPolicy in each cluster to allow the F5 to reach Services
- [ ] Update GitHub Actions and related Secrets
- [ ] Cut over to Gold via DNS update
- [ ] Remove old project set in Silver

**Comment by IanKWatts** [comment]
Taking over this task and looking into the migration process.
RocketChat has been migrated to Argo CD in Silver and will be managed by Argo CD in Gold / Gold DR.

**Comment by IanKWatts** [comment]
This issue has been replaced by three issues that break down the tasks into groups.  Those tickets are: 1971, 1972, 1973
