### ISSUE TITLE
OCP4.7 Test Volume Snapshots in CLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1555]
**Describe the issue**
In OCP 4.7 / Trident v21.07.1 volume snapshots will be available for general use and it'd be worth checking what it'd take to get it enabled in our platform clusters.

Note `ontap-nas-economy` driver doesn't support snapshots. That maps to the StorageClass `netapp-file-standard`.

**Additional context**
https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/operations/tasks/volumes/snapshots.html

**Definition of done**
- [ ] Find out what would be needed to get volume snapshots enabled
- [ ] Find out limitations
- [ ] Test if snapshots take up free space in a volume

**Comment by StevenBarre** [comment]
All we need to enable this for `netapp-block-standard` is a clss.

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: netapp
driver: csi.trident.netapp.io
deletionPolicy: Delete
```

Then users can create VolumeSnapshots from PVCs, and new PVCs from VolumeSnapshots.

However, it appears you cannot quota the size of VolumeSnapshots, so someone could just make a large number of snapshots of their PVC and potentially consume a lot of NetApp storage. I've opened a case with Red Hat to see if I'm just missing something. You can quota the number of snapshots though!

**Comment by StevenBarre** [comment]
@juhewitt @mitovskaol @sbathgate I've confirmed with Red Hat that we can ONLY quota the number of snapshots, not the total size of snapshots. Do you want to have this feature enabled in PROD clusters when we upgrade? What would you like the quotas to be?

**Comment by sbathgate** [comment]
Do we have a normalized idea of what would be a typical Snapshot size? Obviously will vary fairly dramatically on a per app basis, but might give an idea of how many to allow.

**Comment by StevenBarre** [comment]
>Do we have a normalized idea of what would be a typical Snapshot size?

Not really. Nominally it could be the size of their largest PVC. Current quotas are 50Gi/100Gi/200Gi so any individual snapshot could be that big. The actual space used on the NetApp could be that full size, or very minimal, depending on how much change to data there is.

**Comment by StevenBarre** [comment]
Hive mind has decided on a cap of 5 snapshots per namespace and adjusting later if needed.

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: snapshot-quota
spec:
  hard:
    count/volumesnapshots.snapshot.storage.k8s.io: "5"
```

**Comment by StevenBarre** [comment]
PR for Registry Pipeline to add quota https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/52

PR to add VolumeSnapshotClass https://github.com/bcgov-c/platform-ops/pull/392/commits/adef78bf46b4a00ef4d15f8d1ed501898b650ee7

TODO: Need registry app/db support for quota

**Comment by StevenBarre** [comment]
Registry App work will be done in https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1639

**Comment by mitovskaol** [comment]
@StevenBarre I've included you with the announcement of this new service in the agenda for Platform Meetup on Oct 12. Silver should have been upgraded to 4.7 at this time ( or almost upgraded) so it will be a good timing to announce this new feature to the teams.
