### ISSUE TITLE
OCP4.7 Verify new Samples images and Templates

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1559]
**Describe the issue**
The Samples Operator manages the imagestreams and templates in the `openshift` namespace. With each new version of OCP some samples are added and removed. There is a playbook that sets exclusions to trim down which samples are available on the cluster. Determine which images/templates are new and work with Platform Services to understand which to keep or exclude. Update the playbook to exclude any new images and remove any exclusions that are no longer needed.

**Additional context**
https://docs.openshift.com/container-platform/4.7/release_notes/ocp-4-7-release-notes.html#ocp-4-7-images-removed-from-samples-imagestreams

**Definition of done**
- [x] PR to update the samples playbook

**Comment by StevenBarre** [comment]
Find new samples

```
oc -n openshift get is,template -o=custom-columns=KIND:.kind,NAME:.metadata.name,AGE:.metadata.creationTimestamp | grep 2021-08-30
```

**Comment by jleach** [comment]
@StevenBarre Afirmative. Tempted to keep `hello-openshift` but lets pass on that also.

**Comment by jleach** [comment]
@StevenBarre I think we can get rid of these also:
```console
fuse75-console                 The Red Hat Fuse Console eases the discovery and management of Fuse applicati...   8 (1 blank)       5
fuse76-console                 The Red Hat Fuse Console eases the discovery and management of Fuse applicati...   8 (1 blank)       5
cache-service                  Red Hat Data Grid is an in-memory, distributed key/value store.                    8 (1 blank)       4
datagrid-service               Red Hat Data Grid is an in-memory, distributed key/value store.                    7 (1 blank)       4
```

**Comment by jleach** [comment]
@IanKWatts Tag. It'll be more clear why later.

**Comment by StevenBarre** [comment]
Samples exclusion list updated https://github.com/bcgov-c/platform-ops/commit/83fffe9d4ef78823b6f03d4288f42929a43f0d45

Upgrade docs step added https://github.com/bcgov-c/advsol-docs/pull/161/commits/ea504ab46d693fdfe08693f0e675b455cd2149a6
