### ISSUE TITLE
OCP4.7 Test F5 CIS upgrade in CLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1568]
**Describe the issue**
F5 CIS v2.5.0 is required before upgrading to OCP4.7

**Additional context**
https://clouddocs.f5.com/containers/latest/reference/release-notes.html#release-notes-2-5-0

**Definition of done**
- [x] Playbook that installs/upgrades CIS is updated to deploy v2.5.0 or newer
- [x] Test that Porter Operator still works with new version
- [x] Document any upgrade steps required for other clusters

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-ops/commit/659189a633be41dd8bab11c2fe2e86aaf8b4703b

**Comment by StevenBarre** [comment]
Initial checks look good. Getting @j-pye to "Test that Porter Operator still works with new version" before closing.

**Comment by j-pye** [comment]
Confirmed the porter operator is still working as expected using existing TransportServerClaims as well as new.
