### ISSUE TITLE
OCP4.7 Upgrade NetApp Trident in KLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1569]
**Describe the issue**
Upgrade Trident based on testing in KLAB.

**Additional context**
https://github.com/NetApp/trident/releases

**Definition of done**
- [x] Trident upgraded

**Comment by tmorik** [comment]
NetApp Trident in KLAB has been upgraded. 

```
    # oc -n openshift-bcgov-trident describe tprov trident | grep Message: -A 3
	  Message:                Trident installed
	  Status:                 Installed
	  Version:                v20.10.1
```
