### ISSUE TITLE
OCP4.7 Upgrade in KLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1570]
**Describe the issue**
Run the OCP 4.7 upgrade in KLAB. Document if/where it gets stuck and any steps to work around it. Try and determine how disruptive the changes are to the API, Router, and hosted apps.

**Additional context**

**Definition of done**
- [x] Upgrade `oc` CLI on util server
- [x] KLAB upgraded to OCP 4.7
- [x] MachineConfig changes applied
- [x] CCM applied
- [x] EnCase updated
- [x] ETCD Backup updated
- [x] Nagios updated
- [x] Pruner updated
- [x] vROps updated
- [x] Logging updated
- [x] Sample Operator updated

**Comment by tmorik** [comment]
KLAB has been upgraded to 4.7, exception with the task of `CCM applied`.

**Comment by StevenBarre** [comment]
CCM v3.0.0 created and applied to KLAB. Ready for PROD rollout.
