### ISSUE TITLE
OCP4.7 Perform Hard Prune in KLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1571]
**Describe the issue**
The image registry should have a hard prune run on it from time to time. So we plan a Sunday morning change window operation to run the prune each quarter before patching kicks off. KLAB can be run during daylight hours.

**Additional context**
https://docs.openshift.com/container-platform/4.6/applications/pruning-objects.html#pruning-hard-pruning-registry_pruning-objects

**Definition of done**
- [x] KLAB image registry pruned

**Comment by tmorik** [comment]
KLAB image registry pruned
