### ISSUE TITLE
OCP4.7 F5 CIS upgrade in KLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1572]
**Describe the issue**
F5 CIS v2.5.0 is required before upgrading to OCP4.7

**Additional context**
https://clouddocs.f5.com/containers/latest/reference/release-notes.html#release-notes-2-5-0

**Definition of done**
- [x] Upgrade F5 CIS in KLAB

**Comment by tmorik** [comment]
F5 CIS in KLAB has been upgraded.
