### ISSUE TITLE
OCP4.7 Upgrade NetApp Trident in GOLDDR

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1581]
**Describe the issue**
Upgrade Trident.

**Additional context**
https://github.com/NetApp/trident/releases

**Definition of done**
- [x] Trident upgraded

**Comment by StevenBarre** [comment]
CHG0029881 MCS GOLD DR - 2021 Q4 Patching - Upgrade to OCP 4.7

**Comment by tbaker1313** [comment]
Trident has been updated.
