### ISSUE TITLE
OCP4.7 Upgrade in GOLDDR

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1582]
**Describe the issue**
Run the OCP 4.7 upgrade in GOLDDR.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] Schedule a week long CHG
- [x] Update HPE and Dell firmware
- [x] Upgrade `oc` CLI on util server
- [x] GOLDDR upgraded to OCP 4.7
- [x] MachineConfig changes applied
- [x] CCM applied
- [x] EnCase updated
- [x] ETCD Backup updated
- [x] Nagios updated
- [x] Pruner updated
- [x] vROps updated
- [x] Logging updated
- [x] Sample Operator updated

**Comment by StevenBarre** [comment]
CHG0029881 MCS GOLD DR - 2021 Q4 Patching - Upgrade to OCP 4.7

**Comment by tbaker1313** [comment]
Updated to OCP 4.7 - awaiting firmware on Nov 9th.

**Comment by tbaker1313** [comment]
Updated two servers with firmware and determined there is no difference from old and new versions except for 'intelligent provisioning' which is only needed at server setup time. Not required for the other servers in GOLDDR.

**Comment by tbaker1313** [comment]
CCM for GOLDDR will be done on Nov 10th

**Comment by tbaker1313** [comment]
This has been completed.
