### ISSUE TITLE
OCP4.7 F5 CIS upgrade in GOLDDR

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1584]
**Describe the issue**
F5 CIS v2.5.0 is required before upgrading to OCP4.7.

Change should be safe to perform during the day as long as users are warned to not make any TransportServerClaim changes during the work.

**Additional context**
https://clouddocs.f5.com/containers/latest/reference/release-notes.html#release-notes-2-5-0

**Definition of done**
- [x] CHG created
- [x] Upgrade F5 CIS in GOLDDR

**Comment by StevenBarre** [comment]
CHG0029880 MCS GOLD DR - 2021 Q4 Patching - Registry Hard Prune

**Comment by tbaker1313** [comment]
Completed.
