### ISSUE TITLE
Create playbook to set up home folders on util servers

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1587]
**Describe the issue**
Add a playbook in https://github.com/bcgov-c/rhcos-ignition-builder to set up the home folders for all the MCS team members with a certificate based authentication and any other useful things from the old Bastion host.

**Additional context**
https://access.redhat.com/support/cases/#/case/02868830
https://github.dxc.com/AdvSol/mcs-ops/blob/master/playbooks/home-dir-setup.yaml

Steve misses the nice PS1 prompt that bastion had.

**Definition of done**
- [ ] Playbook to create home dirs and pre-populate kubeconfig for each MCS team member

**Comment by tbaker1313** [comment]
Moving to in progress and assessing what is required to make this happen.

**Comment by tbaker1313** [comment]
First testing completed, created new branch to refine - homedir-playbook

**Comment by tbaker1313** [comment]
Testing so far successful. Doing a little more optimization.

**Comment by tbaker1313** [comment]
Tested and merged.
