### ISSUE TITLE
iStore Order - F5 GSLB DNS Request Rocket.Chat

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1588]
**Describe the issue**
iStore Order for: F5 GSLB DNS Request Rocket.Chat
Date Submitted: August 30, 2021
iStore Number:
Lead time (business days after EA Approves): 

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [x] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by juhewitt** [comment]
At our sprint planning can we revisit this one?  @mitovskaol this was 2 months old and now that Gold is there, and Vault is live... I'm wondering what else is needed to move forwards

**Comment by juhewitt** [comment]
this was escalated @lukegonis and I believe was actually completed already.  check in with team.
