### ISSUE TITLE
Image Management - second step

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1589]
**Describe the issue**
For the builds that are managed by the Platform Services Team:
- add monitoring for jobs
- ensure access to images from all clusters

**Definition of done**
- [x] Build job failures generate a RocketChat notification
- [x] All images built in the Silver `bcgov` namespace are available to all clusters by way of the Artifactory repo `plat-common-images`

**Comment by ShellyXueHan** [comment]
@mitovskaol above ticket created to track things mentioned for image management all together. Once we know who's working on it, this should be break down into individual tasks.

**Comment by mitovskaol** [comment]
@IanKWatts Can you please check with @ShellyXueHan what the scope is for this ticket and either close it if irrelevant or add more content to it so that we can prioritize it in one of the next Sprints

**Comment by IanKWatts** [comment]
@mitovskaol This ticket is still partly relevant.  I have assigned it to myself and updated the description.

**Comment by IanKWatts** [comment]
CronJobs have been added for all builds and build failures will result in a message being posted in the "#image-mgmt" channel in RocketChat.
