### ISSUE TITLE
Determine direction on Docker Desktop usage and issue guidance

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1594]
## Description

Docker Desktop GUI is no longer "free" to use but rather requires a subscription; the CLI and Damon are still free. There is a grace period until Jan. 31, 2022.

https://docs.docker.com/subscription/#docker-desktop-license-agreement
https://www.docker.com/blog/updating-product-subscriptions/

We need to determine the impact on the BCGov so we are in compliance with licensing requirements and, if needed, purchase licences or advise employees to uninstall the GUI component and rely on the CLI.

This may not impact contractors as they are required to bring their own resources and most will not be large enough organizations to require licensing.

## Done When

- [ ] The licensing changes are understood;
- [ ] Either purchase licences or issue temporary guidance to un-install the GUI;
- [ ] Trigger procurement and/or issue long-term guidance.

**Comment by jleach** [comment]
@sbathgate FYI. To track the issue.

**Comment by jleach** [comment]
It says on [this page](https://docs.docker.com/subscription/#docker-desktop-license-agreement) that its free for non-commercial open-source usage. We should check if that includes Government since we're not really commercial. My 2c worth is get a pro (lawyer) to advise on licensing.

**Comment by mitovskaol** [comment]
@juhewitt @jleach Can you please validate but this is what the [Docker website](https://www.docker.com/products/docker-desktop) says:
```
The Docker Pro, Docker Team, and Docker Business subscriptions now include commercial use of Docker Desktop.
```

**Comment by jleach** [comment]
@mitovskaol 

I think we need to figure out how to advise development teams and help the with a clear path forward like: Step 1 click this, Step 2 type this. Docker is quite fundamental to teams that orbit the platform and we should help.

That said, I think you are correct but I cannot tel if we're compliant. We get get 5 seats for $7/mo which is not enough to cover all full time employees; contractors are IMHO not subject to the licence because we are less than 250 employees and $4mil in revenue. Usually we're just 1-person operations.

**Comment by mitovskaol** [comment]
The following email communicating the BC Gov's recommendation for future use of Docker Desktop has been sent to our Platform distribution list on Jan 17, 2021:
________________________________________________________________________
What is happening? 

Docker Inc will implement a new tier pricing subscription model for their product, Docker Desktop at the end of January 2022.  Docker is a popular containerization software used by most teams building applications on the Private Cloud Openshift Platform.

Docker provides a set of products to create and manage containers for cloud native apps which include Docker Engine and Docker Desktop.
 
Docker Engine is available to use free of charge, subject to the terms of the Apache License, Version 2.0.
 
However Docker Desktop, a tool that some of you use to conveniently interact with the Docker Engine, will no longer be free to use.  The cost of continuing to use Docker Desktop will start at $5USD/month per user, depending on the subscription type: Pro, Team or Business.
 
As always, any use of third party software (i.e. non-province owned) including open-source licensed, involves a license which is a form of contract. Please ensure contract terms are appropriately reviewed as required by province policy before you accept them, including via clickthrough acceptance.
 

When is it happening?
 
The new subscription model by Docker Inc for Docker Desktop is activated on Jan 31, 2022.
 

Will there be a centralized license management for Docker Desktop on the Private Cloud Platform?
 
No, at this moment we cannot offer any support to the teams that want to purchase a license for Docker Desktop. Each team will have to decide if they want to continue using Docker Desktop or switch to other tools that work with Docker Engine.  The Province is not responsible for compensating the cost of Docker Desktop for our contracted partners that choose to use it, as it is not a required tool to use Docker.  
 
Can we use the free version of Docker Desktop, as we are part of a government organization and working with open source technology?
 
Unfortunately the Province is not exempt from having to buy the paid subscription under the new subscription model for Docker Desktop.
 
Can I continue using Docker Engine without Docker Desktop?
 
Yes! For example, here are two articles that  describe different approaches for using Docker Engine without Docker Desktop.  [Docker CLI on Mac OS without Docker Desktop](https://itnext.io/utilizing-docker-cli-without-docker-desktop-4933f3473d5e) and for [running Window and Linux Containers without Docker Desktop on Mac OS and Windows](https://lippertmarkus.com/2021/09/04/containers-without-docker-desktop/). As above, please ensure that any applicable license terms are appropriately reviewed before you accept them.
 
Love, Platform Services Team, xo
