### ISSUE TITLE
Regular Audit of containers running as root/privileged

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1595]
Pods by default run in unprivileged mode, but we should monitor when that is not the case

The CCM role 'cluster_checks' has been updated to support this.  A cron job will run monthly in each cluster to collect information on containers not running with high-level user IDs.  A report will be sent to the Platform Services team mailbox.

**Definition of done**
Determine how to regularly query the cluster for containers running as root
Alert on those not expected
Ensure there is an escalation process to address those that are not appropriately running

**Comment by garywong-bc** [comment]
Is this even possible?  Whenever I attempt to run such an image from DockerHub on OCP, it just fails. /cc @NickCorcoran

**Comment by lukegonis** [comment]
Still relevant

**Comment by NickCorcoran** [comment]
@IanKWatts - I know you did some work on this, but unsure how much.  Can probably be closed once CCM update complete.  Reports planned to be sent to platform services mailbox on a monthly basis for review.

**Comment by IanKWatts** [comment]
This is pretty much ready, but can't yet send email to BC gov email addresses.  Will have to use CHES, I think, so need to get access to that first.

**Comment by IanKWatts** [comment]
@NickCorcoran Do you just want running containers or also those that are completed?  Getting both means a longer list, but would capture cronjobs and what not.

**Comment by NickCorcoran** [comment]
@IanKWatts if we can get completed too, that would be great.  But I'd like for it to be easily distinguishable (running vs completed) so we don't go searching for something that's done.

**Comment by IanKWatts** [comment]
CHES email setup and testing is complete and PR has been merged for CCM.  Will be rolled out next week.
