### ISSUE TITLE
Connect Rocket.Chat backup container to a channel for notifications

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1597]
## Description

On our hand-over call we talked about setting up the backup container for Rocket.Chat so that it reports status to a channel.

## Done When

- [x] Rocket.Chat's backup container us using a web hook to report on backup status.

**Comment by ShellyXueHan** [comment]
### Updates:
- currently backup notification is enabled to channel rocketchat-ops
- unfirtunately Vault isn't working in silver now, will have to convert the template back to using vault afterwards
