### ISSUE TITLE
Deploy Python Dash App on OpenShift

### ISSUE THREAD

**Issue by poornima-sivanand** [BCDevOps/developer-experience#1600]
Describe the issue
Deploy the Python Dash App on OpenShift (this is temporary to do UX research)

Definition of done

- Sample dashboards displayed on OpenShift to perform UX research

**Comment by poornima-sivanand** [comment]
Route available at https://resource-tuning-app-demo-ee74e4-dev.apps.klab.devops.gov.bc.ca/
(note: this route will not be used , instead an api will be used to populate platform registry with the same information)

**Comment by lukegonis** [comment]
the first iteration has been deployed. @poornima-sivanand  and team are going to use that for talking to people and getting their feedback on future improvements
