### ISSUE TITLE
Project Deletion feature business requirements investigation

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1602]
**Describe the issue**
It's not clear how the deletion feature will work

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- clarity around how the feature works 
- architecture/workflow diagram
- outstanding questions answered/approved by PO

**Comment by w8896699** [comment]
When we send the request to Database, do we want to completely delete Profile row from database? or just mark it as archived, what about other info, like contact(remove or mark as archived). *I suggest marking the profile and all other info in the db as archived, all information about the project will still be stored in the database but not showing anywhere in the UI *
Where should we show for Administrator on review pop up? Just saying Are you approve for deleting this project? The project deletion should follow the same approval process as project provisioning and quota increase now.
Do we want to let the Administrator delete the project without a request? Yes. Administrator can submit a deletion request on behalf of the PO and it will flow through the same approval process as if PO himself submitted it.
After Administrator approved the request, are we just delete the project right away or we will hold for a week. It would be me or Justin H approving these requests. When the approval is received, you can delete the project right away. Justin and I will reach out to the team manually to confirm the project deletion before we hit the Approve button,
How do we want to handle data if there’s a database. **There will be a checkbox added to the page above the Delete button that says “By checking the checkbox I confirm that I scaled down all pods in the project namespaces and deleted all PVCs”. When the Delete button is clicked in the UI, a pop up will appear asking “Are you sure you want to delete…. it cannot be reversed …etc” and “All project pods must be scaled down to zero and PVCs must be removed prior to submitting the request”. Once they confirm the above, the request will be sent for approval.
Please let me know if everything above makes sense or if more information is needed
