### ISSUE TITLE
Ensure setup and test Azure AD as part of KeyCloak realm that allows openshift access

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1609]
Now that Azure AD is supplying the appropriate attributes to KeyClaok, we need to set it up in a prod realm and test against OpenShift.  

- [x] Setup Prod Realm
- [x] Ensure connection to Azure AD
- [x] Ensure attributes in token
- [x] Ensure Azure AD includes all IDIR
- [x] Ensure Azure AD policy is for periodic MFA check

- [x] Test against OpenShift lab (KLAB or CLAB)

**Comment by arcshiftsolutions** [comment]
@zsamji - FYI.

**Comment by arcshiftsolutions** [comment]
@NickCorcoran - Have we requested the Azure AD setup for PROD on the IDIM side?

**Comment by NickCorcoran** [comment]
Met with Marco and Chris and discussed setup.  New profile to be setup on Azure side w/ requested configurations.  Marco to work with Chris next week to complete setup so it can be tested on our Lab clusters first before roll-out to Silver/Gold.

**Comment by NickCorcoran** [comment]
Chris and Marco to work on this on 21 Sept (hopefully)

**Comment by NickCorcoran** [comment]
Azure AD side configured and connection made, but missing additional attributes required.  To investigate tomorrow.

**Comment by NickCorcoran** [comment]
Environments setup.  
Tested against KLAB.  Logged in successfully.
Attributes successfully passed - preferred username (email), name, IDIR GUID, IDIR ID

**Comment by NickCorcoran** [comment]
IDIR ID and GitHub ID are **NOT** linked in realm used.

Separate issue to be created for Authorization investigation and potential GitHub > IDIR migration (in some cases).
