### ISSUE TITLE
Support BC Health Pass Rollout

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1615]
**Describe the issue**
Most of the details are under NDA. Discussions are in https://chat.developer.gov.bc.ca/group/internal-bc-health-pass

**Additional context**
Support testing and rollout

**Definition of done**
This is a spike without a clear DoD other than successful launch of the BC Health Pass

**Comment by wmhutchison** [comment]
Have accepted a meeting invite for September 3rd 7pm-10pm on behalf of Platform Ops as the current MCS on-call person for that time. Will update if that changes (moved to different time or cancelled).

**Comment by wmhutchison** [comment]
Friday evening testing was partly successful, but bottlenecked significantly due to Akamai bot protection preventing real testing from proceeding. Remaining tests were promising, but full testing including Akamai will be rescheduled once those issues can be worked out. Preliminary estimate for next run is Sunday evening. DXC Situation Management is the SPOC for the Platform Ops team regarding communication for this.

**Comment by wmhutchison** [comment]
Next run was scheduled for Monday morning (9:30am) instead of Sunday evening. Testing went from 9:30am to 10:00am, with both 200 VU's (Virtual Users) and then opened things up to 400 VU's. Some glitches/issues came up, but none were attributed to the Openshift Platform.

**Comment by wmhutchison** [comment]
Proactive monitoring by all stakeholders started at 6:30am on Tuesday, and will go all day at the very least (will see if this extends into the evening as well). No Openshift issues to report thus far.

**Comment by wmhutchison** [comment]
After-hours support of this project ended at approximately 7:00pm on Tuesday September 7th, by virtue of involved stakeholders cutting loose all AdvSol assets (MCS/Platform Ops team, Situation Management, F5/Network team).

**Comment by wmhutchison** [comment]
the latest identified bottleneck noted to date was PROD SSO services. Testing with upgrading the Akami outbound queue to 800 was as far as things got before Marco from the SSO team noted that all SSO pods minus two fell over. The stakeholders rolled back to 750 which appeared to make PROD SSO happy again.

A take-away for the developers was to look at caching the SSO token required for the Openshift apps to interface with PHSA, and according to an update Wednesday morning, was successfully implemented.

An incident however with PROD SSO took place starting at around 12:03am PDT September 8th that lasted until around 7:00am after Platform Ops team edited the PVCs for the DB storage, doubling their capacity from 5GB to 10GB.

**Comment by wmhutchison** [comment]
We are currently sitting at an Akamai outbound queue of 1000 users and appear to be stable. Keep in mind that some functionality originally placed into the app (supporting PDFs) was disabled and likely will remain disabled for a while. A follow-up meeting to take place after 3pm to discuss what's happening next, and likely need for AdvSol support (or not).

**Comment by StevenBarre** [comment]
Things have been stable this week and no more support is expected. Closing.
