### ISSUE TITLE
Ability to access Services on Silver from Gold

### ISSUE THREAD

**Issue by ikethecoder** [BCDevOps/developer-experience#1622]
**Describe the issue**
Is there a possibility to use the Porter Operator to create links between Gold/GoldDR and Silver? Our API Gateway on Silver has a bunch of upstream services where we leveraged the Kubernetes Services / Network Policies to route traffic from the API Gateway to the Upstream Service. With the API Gateway moving to Gold, there will be services remaining on Silver.. if we can get to it through a TransportServer, then it provides a route for us.

**Additional context**
We want to use this in combination with Service Serving Certificates to create a secure and efficient link between the API Gateway on Gold/DR and the Upstream Services on Silver.

**Definition of done**
On Gold and Gold DR, be able to access a Service running on Silver.

**Comment by mitovskaol** [comment]
@StevenBarre @j-pye Can you please comment if this is possible to achieve today or if network changes are required?

**Comment by mitovskaol** [comment]
Closing this ticket as the implementation of Porter Operator to enable this connectivity will be tracked in [this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2232)
