### ISSUE TITLE
New SILVER INFRA Nodes - Create New PR for Inventory Files

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1626]
**Describe the issue**
Create a new branch/PR under the rhcos-ignition-builder repo for the new inventory files needed. Can create initial files without MAC addresses, and add those in before approving/merging once the VMs are created.

**Additional context**
Since these are new inventory files, there is no need to hold off on merging the PR once approved.

**Definition of done**
- [x] Create new branch/PR for inventory files using whatever data is available.
- [x] Complete filling in data for branch once MAC addresses are available.
- [x] Approval/merge the PR.

**Comment by tbaker1313** [comment]
Updated files and added IP addresses. Will add the MAC addresses when possible.

**Comment by tbaker1313** [comment]
Completed.
