### ISSUE TITLE
New SILVER INFRA Nodes - Request Creation of new VMs

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1627]
**Describe the issue**
Since the VMs/nodes are being pushed out before formal build bundles, we'll need to request directly from VMWare team the new VMs (or Dan Deane).

**Additional context**
Specs to avoid looking at an SDSF form.
- 16 vCPU
- 128GB RAM
- single OS drive, 800GB
- if using VRA to create VMs, create in Kamloops using VLAN 158. VLAN 208 (BUR) is then removed and replaced with VLAN 3031.
- make sure new VMs are placed in same folder as MCS-SILVER-INFRA-04 through 06.

**Definition of done**
- [x] Ask Dan Deane if he wants a tracking RITM for this or not.
- [x] If RITM is requested, submit one via TheHUB Portal.
- [x] Confirm VMs are created.

**Comment by tbaker1313** [comment]
Completed. Tickets are still pending.
