### ISSUE TITLE
New SILVER INFRA Nodes - Build and test new VMs

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1628]
**Describe the issue**
Actual build-out of the new nodes. INFRA nodes do start out as worker nodes, so similar methodology can be used for building/testing these before leaving them in a quarantined/cordoned state.

**Additional context**
<https://github.com/bcgov-c/rhcos-ignition-builder#add-more-nodes-later>

**Definition of done**
- [x] Build out new VMs similar to how APP nodes are built. Leave quarantined.
- [x] If desired, cordon off nodes as well and switch from type worker to type infra.

**Comment by tbaker1313** [comment]
New nodes are built as APP nodes, and are currently cordoned.

**Comment by tbaker1313** [comment]
All 3 nodes have be relabeled to INFRA nodes and will remain cordoned until they a decision has been made about putting them in service. Outstanding items are adding to nagios monitoring and updating the asset records with detailed networking information.

**Comment by tbaker1313** [comment]
Closing, officially handed over - still cordoned.
