### ISSUE TITLE
Infra VMs MCS-SILVER-INFRA-7, 8, 9

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1630]
**Describe the issue**
iStore Order for: 
Date Submitted: September 3, 2021
iStore Number: 1078603
Lead time (business days after EA Approves): 

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [ ] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by mitovskaol** [comment]
@lukegonis  Can you please submit a new iStore order to decommission these 3 VMs. We do not need them anymore and unfortnunately the only way to get rid of them is through a decomissioning request. Thanks.

**Comment by lukegonis** [comment]
Closing this issue as the Order has been fulfilled
