### ISSUE TITLE
Migrate from community Argo to OpenShift GitOps Operator

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1634]
**Describe the issue**
Migrate from using the community version of ArgoCD for CCM to using the official operator version of ArgoCD provided by Red Hat. This will get us support via our existing Red Hat licenses and support portal and TAM.

**Additional context**
https://docs.openshift.com/container-platform/4.7/cicd/gitops/gitops-release-notes.html

**What is the plan? How will this get completed?**
Execute the migration plan (2961) for each cluster.

**Identify any dependencies**
This requires cluster admin access.

**Definition of done**
- [x] CCM managed by the official GitOps operator
- [x] Old Argo CD instances are decommissioned

**Comment by IanKWatts** [comment]
All clusters migrated.  Just need to finish automation updates.

**Comment by IanKWatts** [comment]
All CCM instances of Argo CD have been migrated to the GitOps Operator.  I will create a new epic for the migration of the shared instances.
