### ISSUE TITLE
Create and apply PROD CCM Version 2.4.8

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1641]
**Describe the issue**
When there are enough merged commits in the platform-gitops-gen repository to push to the production OCP4 clusters and a matching business need for the same commits to be pushed, work then starts towards creating a suitable new Release tag that will include all of the merged commits and then create corresponding RFCs to update SILVER, GOLD and GOLDDR clusters with the specific new version. Last version was 2.4.6.

**Additional context**
*List of commits to review.* <https://github.com/bcgov-c/platform-gitops-gen/commits/master>

**Definition of done**
- [x] Preliminary communication on #devops-ccm channel detailing intent to apply new release and identify deadlines for final submissions (September 17th)
- [x] Create new release in Github and corresponding RFCs
- [x] Execute SILVER RFC (proposed implementation date is September 20th)
- [x] Execute GOLD RFC (proposed implementation date is September 21st)
- [x] Execute GOLDDR RFC (proposed implementation date is September 21st)

**Comment by wmhutchison** [comment]
For a starting point here are all merged commits in the repo since 2.4.6.

https://github.com/bcgov-c/platform-gitops-gen/commit/065ad2aa5c1f4523071348db6c93ff6da4f44d32 #238 (Add dev container support)
https://github.com/bcgov-c/platform-gitops-gen/commit/e7442e0f0bf24087ec53a4b49eeeac6d6e27fa3e #243 (Add builder SA patch with pull secret)
https://github.com/bcgov-c/platform-gitops-gen/commit/cf1d2b230a995104b2897804d850a7de95507895 #242 (GitOps and OpenShift Operators Best Practices)
https://github.com/bcgov-c/platform-gitops-gen/commit/cda2a456951dd96ba069564807867f4b3ac59948 #247 (Add contractor admins to ns)
https://github.com/bcgov-c/platform-gitops-gen/commit/1e504b51a950550489f35e5497543e1d5477fd65 #239 (Aqua active-active mode)
https://github.com/bcgov-c/platform-gitops-gen/commit/c8ca16b943d798d40d02493faf9365a0cc6c9036 #245 (Add Makefile Support and GitOps Container Upgrade)
https://github.com/bcgov-c/platform-gitops-gen/commit/f133dc229661aee6e8dee4baedbb849c402cf908 #240 (Configure argocd-shared for Silver)
https://github.com/bcgov-c/platform-gitops-gen/commit/02b7f8cdffb755eca578e0dd98d38905cf5b915a #248 (Update image management with aqua scanner image)
https://github.com/bcgov-c/platform-gitops-gen/commit/bd4c2ea25604384ac604d16da3780d764bc760d9 #251 (Grant Shaun Bathgate cluster reader access)
https://github.com/bcgov-c/platform-gitops-gen/commit/a1f4ffa9b089df43b1e7a5bbf5bb2101a2503fb5 #246 (Docs for running with podman)
https://github.com/bcgov-c/platform-gitops-gen/commit/d2b0edb3bfa53329d5cec519617e00c3cabd5fc8 #252 (bcdevops helper improvements)
https://github.com/bcgov-c/platform-gitops-gen/commit/c0404e2ad0b9a4f576666b6343640dbdce7388f5 #253 (Sysdig operator - cluster role binding to manage sysdig team custom resources)
https://github.com/bcgov-c/platform-gitops-gen/commit/5281f4c9acf8fd032c37ac27fdb6c5262e94f01a #254 (Sysdig operator - part 2)
https://github.com/bcgov-c/platform-gitops-gen/commit/2ed792ad9edce31b044faeb18ecca1dc32f5991f #255 (Sysdig operator - fix cluster role binding service account's API group)
https://github.com/bcgov-c/platform-gitops-gen/commit/4c5f2b640c761912a1f1aa7ae361254730edfdae #257 (Aqua Operator CR updated RBAC auth labels)

**Comment by wmhutchison** [comment]
The above list seems rather large, but not all of these will be advertised in the release notes and RFC details, since some of these are updates to the devcontainer efforts which is not consumed by ArgoCD, and thus out of scope for consideration. Those merges will still technically be part of the new release, but not have any impact or effect in a CCM push.

**Comment by tbaker1313** [comment]
Created release 2.4.7 and PR for the updates to the versioning. RFC created and will request approval shortly.

**Comment by tbaker1313** [comment]
Completed in SILVER, GOLD and GOLDDR clusters.
