### ISSUE TITLE
Update provisioner to support separation of CPU/RAM quotas

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#1647]
**Describe the issue**
Instead of using a single quota size for project set resources, separate quota sizes will be used for storage, CPU, and RAM.

**Additional context**
In the registry app, the single T-shirt size dropdown for project set quotas will be replaced by three dropdown so that separate quota sizes can be configured for each of storage, CPU, and RAM.  Update the provisioner to accommodate this.

**Definition of done**
- [ ] The provisioner templates and automation tasks have been updated to support the separate values for each resource set
- [ ] Pull requests have been merged to enable this functionality in each cluster.

**Comment by w8896699** [comment]
Justin Pye helped me finished this one pr: https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/64/files
