### ISSUE TITLE
Artifactory HA - resource monitoring

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1654]
**Describe the issue**
Artifactory HA pods are running at memory limit for at least 2 weeks. No service issue but we bumped it with 2Gi for both limit and request. Looking good now. Will keep an eye on the usage for few more days.

Some investigation needed later on.

**Definition of done**
- [x] Shelly has already put together a Sysdig dashboard - I should update it!

**Comment by lukegonis** [comment]
Still relevant, blocked by Sysdig

**Comment by ShellyXueHan** [comment]
Here's the resource dashboard for artifactory: https://app.sysdigcloud.com/#/dashboards/256940?last=3600&scope=kubernetes.namespace.name%20%3D%20%22devops-artifactory%22%20and%20kubernetes.cluster.name%20%3D%20%22silver%22
