### ISSUE TITLE
Install VPA in Prod Clusters

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1687]
**Describe the issue**
VPA is currently Tech Preview. Once it goes GA in 4.8 test the upgrade in the labs and then install into the Prod clusters.

**Additional context**
https://docs.openshift.com/container-platform/4.8/nodes/pods/nodes-pods-vertical-autoscaler.html

**Definition of done**
- [x] VPA Installed via CCM on SILVER
- [x] VPA Installed via CCM on GOLD
- [x] VPA Installed via CCM on GOLDDR

**Comment by wmhutchison** [comment]
This will get linked into the upcoming OCP 4.8 ZenHub EPICs once created to solidify the dependency.

**Comment by wmhutchison** [comment]
This is in line to go in with the next CCM push, which will be the one that's applied after each PROD cluster is upgraded.

**Comment by wmhutchison** [comment]
Moving this back to Backlog for now. Will bump it back when overall OCP upgrades for SILVER/GOLD/GOLDDR are first figured out.

**Comment by wmhutchison** [comment]
VPA confirmed in all PROD clusters as installed via CCM. Closing ticket.
