### ISSUE TITLE
Familiarize with Resource Tuning Advisor App

### ISSUE THREAD

**Issue by poornima-sivanand** [BCDevOps/developer-experience#1689]
Help Alex familiarize with the Resource Tuning Advisor App

Definition of Done:

Once this issue is completed:

- [ ]  Provide overview of the app architecture and design to the new developer Alex 
- [ ] Provide an overview of the status of the current work and review the roadmap for the future features for the app

**Comment by ShovelHand** [comment]
I think this issue can be closed. I did have a call with Poornima shortly after beginning with the BCDevExchange, but I'll leave it for a future sprint review to discuss before closing.
