### ISSUE TITLE
Sysdig reoccurring issue - event missing from Silver cluster

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1699]
**Describe the issue**
issue https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1266 happening again in silver cluster. Might be a different cause, currently debugging with Sysdig support.

**Definition of done**
- [x] identify issue
- [x] prevent this happen again
- [x] push changes to production cluster

**Comment by ShellyXueHan** [comment]
### Updates:
- I've had 2 troubleshooting sessions with sysdig support
- sysdig engineer team has what they need now, waiting for feedback from them!

**Comment by ShellyXueHan** [comment]
### Update:

grabbed trace level logs and sent to sysdig engineer team, waiting for updates!

**Comment by ShellyXueHan** [comment]
Scheduling event with sysdig engineers for torubleshooting session.

**Comment by matthieu-foucault** [comment]
Any ETA on a lasting fix for this? Not having events since migrating to the Silver cluster a year ago has reduced our ability to debug issues with Sysdig

**Comment by ShellyXueHan** [comment]
Hey Matthieu @matthieu-foucault ! We are still working with Sysdig engineer team to continue dig into this, there is no clear indication on what's causing this issue. All the previous fixes and upgrades only temporary brought back events and they would be gone again soon, this has been happening for the past months till a year. There's no estimation on the issue unfortunately until we know what's causing it. But I'll update this ticket once we hear back!

**Comment by ShellyXueHan** [comment]
# Update:
Had another debugging session, sysdig support's finding show that Protobuf did not indicate any problems from server. Hence the issue happens to be with the events watcher. The engineering team is working on addressing the issue. The issue will likely be fixed in the next release of agent 12.3.0.

**Comment by ShellyXueHan** [comment]
agent 12.3 (containing the fix) is expected to be release in 2-3 weeks approximately
