### ISSUE TITLE
Investigate Aqua audit/enforce on OpenShift Resource Allocations

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1702]
- [ ] Investigate available features
- [ ] Set test policies in CLAB
- [ ] Obtain results
- [ ] Share w/ Justin

**Comment by Nicole-Huard** [comment]
@NickCorcoran I see this was assigned to Mike Shire - do you still need help with this? Is this an active item? If so, I can see who's available on our end to support this work.

**Comment by NickCorcoran** [comment]
@Nicole-Huard Michael had indicated it was something he could help me with, but we hadn't gotten to it yet.  If there is someone with similar insights that would be helpful.  This is not a high priority though.

**Comment by Nicole-Huard** [comment]
When you're ready to go forward, we can find a resource to provide insights @NickCorcoran

**Comment by NickCorcoran** [comment]
Nick to investigate w/ Gerald on knowledge, and touch base w/ Justin H re: need for investigation due to resource restrictions dictated by Argo and monitoring using the custom app developed for resource consumption.

**Comment by NickCorcoran** [comment]
We are going to keep this in the backlog as a requirement to restrict misconfigurations of resource utilization; can tools like Aqua enforcers do this? etc..
For now I will un-assign Arctiq resources and we can revisit if this becomes a priority.

**Comment by NickCorcoran** [comment]
New issue to be created for ACS.
