### ISSUE TITLE
Investigate Tremolo Security for User Access Management

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1704]
Discussions  with Red Hat indicated that many of their customers use this solution for Openshfit access management,
https://www.tremolosecurity.com/

"Tremolo Security's open source identity management system provides a Red Hat certified solution for managing access to your Red Hat Linux servers, OpenShift & Ope*nStack deployments, and your applications augmenting KeyCloak". 

**Related ticket:**
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1666

**Actions**
- [x] Read documentation
- [x] Schedule demo

**Future**
- Install in lab
- Trial capabilities

**Tagging SSO team for information purposes.

**Comment by AvneetKahlon** [comment]
Had first meeting to discuss the requirements.

**Comment by AvneetKahlon** [comment]
Got demo from Tremolo
