### ISSUE TITLE
Install the Serverless Operator

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1721]
**Describe the issue**
After a demo of Serverless, several teams showed an interest. Install in the clusters via CCM

**Additional context**
https://docs.openshift.com/container-platform/4.7/serverless/admin_guide/install-serverless-operator.html

**Definition of done**
- Read the docs and determine steps to install and any config required
- Test install in LAB
- Create PR in CCM to install in all clusters

**Comment by mitovskaol** [comment]
@NickCorcoran Service Mesh will be available in OCP 4.8

**Comment by StevenBarre** [comment]
Had a chat with Matt today. Service Mesh can be installed in v4.7. His previous comment about it being "a whole thing" was more around user training, than installation. I think I'll give it a go in a lab next sprint and see what all is involved.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/303
https://github.com/bcgov-c/platform-gitops-gen/pull/304

**Comment by StevenBarre** [comment]
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.7/html/service_mesh/service-mesh-2-x

**Comment by StevenBarre** [comment]
Components are installed in CLAB. Now waiting on the dev team to test and see if any changes need to be made. Closing this ticket and will open a new one should any new changes be needed, and when its ready to be rolled out to PROD.

**Comment by StevenBarre** [comment]
https://docs.openshift.com/container-platform/4.12/serverless/install/preparing-serverless-install.html
> OpenShift Serverless currently cannot be used in a multi-tenant configuration on a single cluster.
