### ISSUE TITLE
Uptime monitor - gather requirements and explore alternatives

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1726]
**Describe the issue**
we have encounter some false alarm with Uptime Robot and not able to get enough support from them. Thus starting to see what are the alternatives available and decide on the next step.

(this is for platform and shared services uptime monitoring)

**Definition of done**
- [x] gather requirements for uptime monitoring
- [x] explore some tools

**Alternatives**
Some things to explore once we settle on the requirement list:
- look into what UK gov uses
- Grafana dashboard on a VM
- https://www.g2.com/products/uptimerobot/competitors/alternatives
- https://uptime.com/

**Comment by ShellyXueHan** [comment]
### Update:
We had a chat with uptime.com and this service is looking quite promising!  So far looks like it would meet our requirements. Next step is to explore more feature on it to see if things work as what we expect.

**Comment by ShellyXueHan** [comment]
### Updates:
@jhpye @mitovskaol @marthaedwards Here's what I found out so far, also added some sample status pages in the doc:
https://github.com/BCDevOps/platform-services/blob/uptime-status-alternatives/monitoring/uptime-robot/exploration.md

So far my vote goes to `uptime.com`.  Lmk what you think :)

**Comment by ShellyXueHan** [comment]
ops tagged Justin P here instead :P @juhewitt ^^^

**Comment by juhewitt** [comment]
Uptime it is!  Looks great Shelly.  Please reach out to see if there's any support they can help us with to get us migrated over in the next sprint asap.

**Comment by mitovskaol** [comment]
+ for Uptime.com!

**Comment by sbathgate** [comment]
Uptime.com looks like a solid option. Their dashboard is super friendly and I like some of the grouping capabilities.
