### ISSUE TITLE
Enterprise DB R&D

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#174]
Timeboxed research on moving Keycloak from Patroni to EDB.

- [x] what are the differences between EDB and Patroni?
- [x] how exactly does our Keycloak Patroni instance work?
- [x] what might be some gotchas about moving from one to the other?
- [x] create a list of highly specific questions for EDB support

**Comment by tosazuwa** [comment]
Blocked due to licenses procurement delays
