### ISSUE TITLE
SIEM Ingress Parsing

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1741]
- [ ] Interrogate logs for useful fields
       - [ ] container - namespaceID, podID, actionType, etc
       - [ ] audit - user, action, time
       - [ ] system - tbd

- [ ] Investigate parsing rules application
- [ ] Map appropriate fields for parsing

**Comment by bruce-wh-li** [comment]
We can parse the original message using field extraction.   But it is arduous effort and might not be the right place to process.

**Comment by bruce-wh-li** [comment]
Steven Barre has difficulty to  connect the siem endpoint as DXC does not have VPN2.
