### ISSUE TITLE
Unable to configure integration for RabbitMQ workload in sysdig

### ISSUE THREAD

**Issue by ssuganth** [BCDevOps/developer-experience#1742]
We are trying to configure the integrations as described here in link https://docs.sysdig.com/en/docs/sysdig-monitor/integrations-for-sysdig-monitor/configure-monitoring-integrations/  However, even though we have role ROLE_TEAM_MANAGER in sysdig for our Openshift namespace (0198bb-dev), clicking on “Configure Integration” does not do anything. Is it a permission issue? 

![image](https://user-images.githubusercontent.com/89552320/137349219-c31b014d-99e9-43f7-aee3-cb25b5479b75.png)

**Comment by ssuganth** [comment]
We could now install/configure the RabbitMQ integration in sysdig but even after doing it the metrics were not fetched.
We followed the documentations provided in sysdig and included below required pod level annotations in openshift & also enabled the "rabbitmq_prometheus" plugin in the pods.

"**rabbitmq_prometheus**" plugin is already enabled and active in pods.
Pod level annotations:
**prometheus.io/path: /metrics**   -> Default path of metrics exported by "rabbitmq_prometheus" plugin.
**prometheus.io/port: '15692'** -> Default port where "rabbitmq_prometheus" plugin exposes the metrics
**prometheus.io/scrape: 'true'**

Please refer the screenshot where the metrics are not being fetched by sysdig. Please verify if any configuration/set-up missing at the sysdig/sysdig agent level.

![image](https://user-images.githubusercontent.com/89552320/138377312-6dfc5a3a-8abc-4ac3-87f3-534bf4d022f0.png)

**Comment by pbolduc** [comment]
Related: https://github.com/BCDevOps/developer-experience/issues/1471

**Comment by ShellyXueHan** [comment]
@ssuganth after enabling the metrics endpoint to sysdig, you should be able to find the application metrics from `Explore` and in dashboards directly now. Would you check it out? If you this is still an issue, please continue discuss on Rocketchat for quicker response: https://chat.developer.gov.bc.ca/channel/devops-sysdig Thank you!

**Comment by pbolduc** [comment]
I can see the metrics and dashboards for RabbitMQ and Redis perfectly now.

![image](https://user-images.githubusercontent.com/1844480/202305715-bba2ce11-a32f-4f0e-bcc6-b88c1c750bbf.png)

**Comment by ssuganth** [comment]
I can see too, thanks @ShellyXueHan
