### ISSUE TITLE
CCM - Migrate to OpenShift GitOps Operator

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1748]
**Definition of done**
- [x] Role created to install OpenShift GitOps Operator
- [x] platform-gitops-gen modified to support gitops operator
- [x] Tested in CLAB
- [x] Any manual steps documented in Advsol-Docs repository
- [x] Include the feature in CCM to roll out in all production clusters

**Comment by j-pye** [comment]
Work started on this early in the sprint but time was redirected to focus on the Warden Operator.

**Comment by lukegonis** [comment]
Still relevant

**Comment by IanKWatts** [comment]
New CCM role is 'gitops'.
Migration plan is published in platform-gitops-gen/doc/
