### ISSUE TITLE
CCM - Optimize Shared Templates

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1749]
**Describe the issue**
There are several duplicate templates between multiple Ansible Roles in CCM and Implementing a new feature, app, or service into CCM requires copying these or updating group_vars for all clusters. This needs to be simplified

**Definition of done**
- [x] Cluster Apps role consolidated with a single config file
- [x] group_vars simplified where possible
- [x] Changes tested in KLAB or CLAB
- [x] Changes documented in Advsol-Docs repository

**Comment by j-pye** [comment]
Work started on this early in the sprint but time was redirected to focus on the Warden Operator.

**Comment by IanKWatts** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/641
