### ISSUE TITLE
Platform Operations Quarterly Maintenance - 2021 Q4

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1757]
**Describe the issue**
This Epic will serve as an umbrella for all planned maintenance activities for 2021 Q4 for both Openshift clusters and OS patching for UTIL servers.

**Additional context**
KLAB/CLAB OCP upgrades to 4.7 were technically covered off in Q3 and will not be revisited in Q4 unless a new security upgrade is mandated. Current plan is to tackle UTIL OS patching after so that no cluster is getting its UTIL server OS-patched before its OCP4 upgrade.

**Definition of done**
- [x] Flesh out all required tasks to encompass all planned maintenance activities in Q4.
- [x] Implement all of the work via suitable RFCs. Update patching spreadsheet when done.

**Comment by tbaker1313** [comment]
This has been completed.
