### ISSUE TITLE
Enable HTTP/2 on routers

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1766]
**Describe the issue**
A developer is looking to use http/2 and gRPC connections in Silver. https://cloud.redhat.com/blog/grpc-or-http/2-ingress-connectivity-in-openshift

**Additional context**
https://docs.openshift.com/container-platform/4.7/networking/ingress-operator.html#nw-http2-haproxy_configuring-ingress

```
oc annotate ingresses.config/cluster ingress.operator.openshift.io/default-enable-http2=true
```

- RC user: ytqsl
- namespace: b5e079-dev

**Definition of done**
- Discuss with RH if this is safe to enable or has any side effects since its not enabled by default
- If safe, enable in LAB and test
- Enable in PROD

**Comment by StevenBarre** [comment]
Case opened with RH to get some more info https://access.redhat.com/support/cases/#/case/03060108

**Comment by StevenBarre** [comment]
>if you have an application that is intended to accept WebSocket connections, it must not allow negotiating the HTTP/2 protocol or else clients will fail to upgrade to the WebSocket protocol.

We need to survey the app owners to see if this would be a problem.

**Comment by StevenBarre** [comment]
@ytqsl has been provisioned `e07c51-*` in CLAB to test out and report back. Moving to Blocked until they have time for that.

They also report that gRPC does work in SILVER with a passthrough route already, so this may not be needed?

**Comment by StevenBarre** [comment]
@ytqsl says
>thanks for the follow up but we had no progress made over the holidays, I hope we can pick this up soon. I’ll let you know once we have some results

**Comment by StevenBarre** [comment]
Still waiting for user testing

**Comment by StevenBarre** [comment]
Closing as the interested user doesn't have time to test. Annotation removed in CLAB.

**Comment by ll911** [comment]
can we reopen this? i can help to test this.

**Comment by ll911** [comment]
H2 + PROXY 
https://docs.openshift.com/container-platform/4.9/networking/ingress-operator.html#nw-ingress-controller-configuration-proxy-protocol_configuring-ingress

**Comment by StevenBarre** [comment]
@ll911 HTTP 2 enabled in CLAB. I tried PROXY mode as well, but it just broke all the routes. Will do some more reading on what's needed.

**Comment by StevenBarre** [comment]
@ll911 after some further testing and research, the options to enable PROXY protocol is only on the upstream side of the router. So from the F5 load balancer to the ingress router. It does not impact connections from the router to pods.

https://github.com/openshift/enhancements/blob/master/enhancements/ingress/proxy-protocol.md#user-stories

Since our Load Balancer is using Source NAT, haproxy is already getting the correct client IPs and adding X-Forwarded-For headers to requests to backends. It also appears that the F5 does not have native support for PROXY protocol anyways, so enabling this feature just breaks things. https://support.f5.com/csp/article/K40512493

Let me know how the HTTP/2 testing is going!

**Comment by StevenBarre** [comment]
@ll911 happy new year. How is the testing going?

**Comment by ll911** [comment]
That's what my workaround so far 
HTTP1.1 (F5) -> RE ENCRYPT HA router -> H2 pods. This creates additional maintenance as caCerts required by both route and pod. I would like be able to use pass through route with H2, so secrets are managed in one place like vault.  Currently if I use HA passthrough with h2, then clientIP is missing from header. https://cloud.redhat.com/blog/grpc-or-http/2-ingress-connectivity-in-openshift.

**Comment by ll911** [comment]
> 

It sounds like negotiation is off, will need negotiation on, so client can request h1.1 if cannot establish on h2.

**Comment by StevenBarre** [comment]
Negotiation is enabled in the router, so it supports both h1 and h2.

But as you've discovered, either you need to use re-encrypt and get a forwarded-for header with the client IP, OR you can use passthrough. There's no way to get both passthrough and client IPs working.

The PROXY feature is only for the frontside, and so the passthrough connection from the haproxy router to your app would still hide the clients ip. Though our F5 doesn't support PROXY protocol anyways, so we can't enable it.

**Comment by StevenBarre** [comment]
@ll911 `f225b6` created in CLAB for you to test in

**Comment by ll911** [comment]
so you cannot have h2(public browser) => f5 (passthrough) => h2 pods? it only works for h1.1 (public, e.g. browser) => f5 (Edge or Reencrypt) => h2 pods? this wont work for h2 websockets traffic

**Comment by ll911** [comment]
h2 test success
h2(reencrypt) => h2 pod (clientIP in XFF header)
h2(passthrough) => h2 pod (clientIP will be missing)
