### ISSUE TITLE
Developer Tekton Pipeline Security Template 

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1771]
DoD:
- create pipeline templates in the [pipeline template repo](https://github.com/bcgov/Security-pipeline-templates/tree/main/Tekton) that follow the same pattern as was developed for GitHub Actions.

**Comment by Nicole-Huard** [comment]
Story points for each issue within this Epic revised from 3 to 8 due to the manual nature of putting these pipelines together, compared to GitHub Actions pipeline templates.

**Comment by Nicole-Huard** [comment]
@NickCorcoran @j-pye did either of you have a chance to review the Tekton Security Pipeline Templates? Wondering if you have feedback.

**Comment by Nicole-Huard** [comment]
@gregnrobinson once Nick/Justin/BC Gov team review, we can finalize the template, then circle back with Olena to create recordings for the community to help them get started & use the templates.

**Comment by Nicole-Huard** [comment]
Reviews complete; presented at Meetup Jan 4th; Olena confirmed we can move on to the recordings
