### ISSUE TITLE
SIEM - SAML Assertions

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1776]
Users will need to be assigned roles upon logging in to the SIEM UI.  These will be limited based on SAML Assertions.

- [x] Investigate where saml assertions are to be declared
- [x] Investigate mapping assertions to roles
- [x] Implement mapping

**Comment by bruce-wh-li** [comment]
The mapping from SAML group to Splunk role was done.   However, we don't have access to the manual created role due to lack of capabilities granted to our account openshift_admin.    But, the mapping is proven working.
