### ISSUE TITLE
Add Keycloak IDP Hints to cluster developer login landing page

### ISSUE THREAD

**Issue by jujaga** [BCDevOps/developer-experience#1779]
**Describe the issue**

The new Silver cluster login page could benefit from leveraging Keycloak IDP Hints for the login buttons. This would reduce the number of clicks a user would have to do in order to authenticate.

**Additional context**

Inserting a query param of `kc_idp_hint=github` would make it so that Keycloak would automatically forward you to the github authentication flow.

- Keycloak Reference: <https://www.keycloak.org/docs/4.8/server_admin/#_client_suggested_idp>
- Rocket Chat conversation: <https://chat.developer.gov.bc.ca/channel/devops-operations?msg=DjceRaLMjq7JFhDuJ>

**Definition of done**

There exists two or more buttons for specific, targeted developer logins. They could be named like the following:

- Github Developer Login
- IDIR Developer Login
- Azure Developer Login

Each of these buttons would leverage their appropriate `kc_idp_hint` in their query parameter to allow Keycloak to automatically forward the user to the appropriate 3rd party authentication flow.

**Comment by mitovskaol** [comment]
Closing as this work is now tracked in [this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1794)
