### ISSUE TITLE
Sysdig Monitoring (Golden Signals) Demo for Team Meetup January 4

### ISSUE THREAD

**Issue by Nicole-Huard** [BCDevOps/developer-experience#1782]
**Describe the issue**
Presentation to BC Gov stakeholders on how to monitor using Sysdig, to encourage usage of Sysdig

- 50 teams using Sysdig out of ~200 on platform; only 25 had alerting activited -- indicates low usage; hypothesis is this is due to knowledge gap
- demo to bridge the knowledge gap
- demo outline:

1. Intro: What is sysdig, why should you care?
2. Onboarding -- Shelly
3. Default dashboard - why they’re set up the way they are, why they’re relevant
4. If there’s time: Customization or alerting (What metrics should you care about?)

**Definition of done**
- [x] delivery of 30 minute demo on January 6th
- [x] delivery of 1 hour presentation on January 18th, 1-2pm PST

**Comment by Nicole-Huard** [comment]
tackle 2 use cases for sysdig:
1. Resource allocation
2. monitoring an app to ensure its healthy

**Comment by Nicole-Huard** [comment]
Sysdig monitoring dashboard shown at Sprint Review today - feedback was good.
James to start working on 1 hour presentation deck
@mitovskaol to circle back on whether this will be extended to hands on workshop action

**Comment by Nicole-Huard** [comment]
30 minute demo completed at Jan 4th Meetup

**Comment by Nicole-Huard** [comment]
How to session rescheduled for January 18th 1-2pm PST

**Comment by Nicole-Huard** [comment]
@ShellyXueHan no - that's the date we landed on, wasn't it? I was just trying to keep this ticket up to date.

**Comment by ShellyXueHan** [comment]
oh I see. All good then, emails and notifications have sent out to the community already. You and James have the meeting invite as well, so we are pretty much ready! I'm leaving the ticket open because the DOD includes the actual presentation delivery.
