### ISSUE TITLE
Install Red Hat Integration components Suite in CLAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1787]
AG ISB Integration Team (@agahchen and @jennifer-dowd ) would like to evaluate the following components of the  Red Hat Integration suite in our LAB environment.

DoD: 
 - [x] @agahchen provides Platform Ops team with evaluation licenses from RedHat for the following components:
 OpenShift Serverless (Serving and Eventing Required)
Red Hat Camel-K
Red Hat AMQ Streams (Kafka)
Red Hat Jaegar
Red Hat Fuse Console
Red Hat Service Registry
Red Hat 3scale API Manager
Red Hat 3scale API Gateway

 - [x] Install these components in CLAB
 - [x] 1 test project sets created in CLAB via the Registry (Jennifer Dowd as PO and David as TL)
 - [x] access to these components is enabled for this project set

Feel free to make this ticket into an Epic if this is more work than can be accomplished in a single sprint.

**Comment by StevenBarre** [comment]
RH Integration operators installed manually. Started working on CCM code to match.

Will do the Serverless/Service Mesh next week.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/298

**Comment by StevenBarre** [comment]
Components are installed in CLAB. Now waiting on the dev team to test and see if any changes need to be made. Closing this ticket and will open a new one should any new changes be needed, and when its ready to be rolled out to PROD.
