### ISSUE TITLE
Create Image Management page in DevHub

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1789]
Create a markdown file in the BCDevOps/openshift-wiki repo that includes product team oriented version of our Image Management approach that is outlined in [this Epic](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/362).

DoD:
- a markdown file is created and reviewed by another Platform Admin and is included in the search index in DevHub

**Comment by IanKWatts** [comment]
@ShellyXueHan @caggles I have updated this doc with manged build info:
https://github.com/BCDevOps/openshift-wiki/blob/master/docs/Artifactory/common_images.md

Do you want to add more info there?
What is the process for tying this in to DevHub?

**Comment by ShellyXueHan** [comment]
@IanKWatts LGTM!

To add it to devhub, you gotta PR in the entry in one of the topics here: https://github.com/bcgov/devhub-app-web/tree/master/web/topicRegistry

See here for more details: https://github.com/bcgov/devhub-app-web/blob/master/docs/registry.md#adding-your-source-into-a-topic-from-github

**Comment by mitovskaol** [comment]
@IanKWatts DevHub will be retiring very soon, so I would not bother pushing the image there. Send the page over to @jonathanB7 , our technical writer, and he will add it to the new mono-repo that he is building and that will contain ALL our technical docs.
