### ISSUE TITLE
Research Azure AD username validation during registration

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1793]
As part of the registry service, usernames should be validated as existing prior to granting role bindings within OpenShift.

With the introduction of Azure AD as an IDP, we must validate entered IDIR users against Azure AD prior to adding permissions to a specified account.  This will require an API call to Azure AD, using a service account with the correct permissions, at the time of registration or username update within the registry service.

- [ ] Create Azure AD service account for this purpose
- [ ] Research API call details required to validate user

For another ticket to complete (once research done):
- [ ] Update registry to include an option to use IDIR (vs GitHub) account
- [ ] Update registry to perform this action

**Comment by lukegonis** [comment]
@NickCorcoran can you please confirm if this has been completed? Thanks
