### ISSUE TITLE
Develop Common Pipeline Component Strategy (Pipeline Governance)

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1797]
As a product team - either new or existing - looking to work on the Platform I would appreciate having access to reusable and extensible pipeline components that my team can use as a starting point for CI/CD on the project and extend as needed. I might also be interested in becoming a Technical Steward of a common pipeline tool and support their pipeline code and other products teams looking to use it.

As a member of Platform Services team I would like to reduce the amount of Platform resources used by multiple instances of Jenkins (one per project) therefore having a centralized CI/CD tool as a service allow for more efficient use of Platform resources as well as an opportunity to enforce security best practices through the use of pipeline templates (i.e. only allow images from Artifactory for production deployment and make container scanning by Aqua mandatory for production deployments as well)

Platform Services team needs to come up with a strategy for establishing pipeline common components and support for them on the new OCP 4 Platform in order to reduce the additional load that multiple instances of CI/CD tools bring to the Platform (there are 100+ instances of Jenkins running on the OCP 3.11 cluster). 

 Potential next steps include:
- [ ]  For each pipeline tool that we will support - GitHub Actions, ArgoCD, Tekton, and Jenkins, develop pipeline templates and store in a repo with public access
- [ ] Consult with @NickCorcoran what security controls i.e. AQUA cli integration should be implemented in the pipeline template  
- [ ] Pilot the use of the templates with several early adopter teams
- [ ] Develop self-help documentation

**Comment by Nicole-Huard** [comment]
GitHub Actions Build & Deploy Templates are ready for BC Gov team to review
Tekton Security Templates are ready for BC Gov team to review

Greg will put the finishing touches on the Tekton Build & Deploy Template, then will work to create short recordings on how to use the templates to help guide the community.

**Comment by Nicole-Huard** [comment]
@mitovskaol since the pipeline templates are now complete and approved, can this ticket be closed or is there more work to be done?
