### ISSUE TITLE
OCP4.6 - Separate /var/lib/containers and /var/lib/etcd to its own disk

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1798]
**Describe the issue**
OCP 4.6 now supports moving [/var to its own partition](https://docs.openshift.com/container-platform/4.6/release_notes/ocp-4-6-release-notes.html#ocp-4-6-4k-var-partition-support). We had previously tried to move `/var/lib/ectd` and `/var/lib/containers` to a separate disk but ran into issues.

On the HPE servers, the primary disk is a 300G hard drive, with a secondary 800G SSD. Currently the Silver cluster is running with just the 800G SSD holding all the data. We'd like to make the root the HDD, and move the two `/var` folders onto the SSD.

`/var/lib/etcd` is only on the Master servers. 

**Which Sprint Goal is this issue related to?**

**Additional context**
The DELL servers use SSDs for both the OS drive and DATA drive, but we'd still like to separate the data on them as well.

**Definition of done Checklist (where applicable)**
- [ ] How can we migrate existing nodes? Test in LAB changing an existing cluster.
- [ ] Change the [install playbooks](https://github.com/bcgov-c/rhcos-ignition-builder) to properly support and test in a LAB
- [ ] Plan and complete the migration in SILVER

**Comment by wmhutchison** [comment]
Closing off this issue. This no longer makes sense now that we're 100% SSD's, made more sense when we had spinning disks to siphon off IOPS. Also better and more consistent from a billing perspective.
