### ISSUE TITLE
Sort out how Aqua will scan *-prod namespaces

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1799]
Due to resource constraints we don't want to scan all images in the cluster at any scheduled interval. Rather, we want to periodically scan `*-prod` namespaces and let teams scan images are they are build (part of CICD pipeline) or when new images are added to the cluster.

DoD:
- [  ]  The decison about the approach to scanning `prod` namespace is documented in this ticket and (in the AQUA Service Definition ?).

**Comment by NickCorcoran** [comment]
I think the best option for this is the setting to 'Automatically register running containers'.  This will catch all Dev/Test/Prod containers running and their associated images.  that way we're not scanning images that aren't actually used.
