### ISSUE TITLE
Need easier way to notify OpenShift project admin when over-requesting

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#18]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when we need to notify the admin users of a project when Steven told us they are over requesting resources.

**Definition of Done**
Describe the end state of this feature as if it would be ready for release.

scripts that connect admin user to rocketchat user

**Additional context**
Add any other context, labels, assignees, epics or screenshots about the feature request when possible.

**Comment by caggles** [comment]
do we need to notify them via rocket-chat?
what if we just have a bot that sends an email listed under the product-owner label?

**Comment by ShellyXueHan** [comment]
Updates:

We are currently working on completing product owner/tech lead contact email on to the namespaces, so email bot could be a better choice at the moment.

**Comment by ShellyXueHan** [comment]
@caggles since we have most of the namespace setup with contact email, I'll go ahead to create the endpoint. Let's have a discussion on the feature.

**Comment by lukegonis** [comment]
Work has been completed to add application resource usage to project registry extract report.
