### ISSUE TITLE
Create monitoring for Artifactory service on Silver cluster

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1804]
As a Platform Services team member responsible for supporting the Artifactory service, I need :
1. Decide on an SLA (uptime, responsiveness, service availability from external client perspective), SLO (internal metrics for the SLA commitments) and SLI (actual measurements for the SLOs) for Artifactory service. Should not be higher than SLA/SLO/SLI for the Openshift Platform itself (SLA = 99.5% for Silver cluster).
2. Determine how the Artifactory service will be monitored (is there an API endpoint that applications use to access the Artifactory service?)
3. Set up monitoring script and send notifications (to who?) if the service is down.
4. Determine if there are any possibility to automate service restore in the case of a service outage.

**Comment by mitovskaol** [comment]
@caggles Can you please have a look and see if you want to track the monitoring work in this ticket or if not, close it and create new one.

**Comment by caggles** [comment]
Closing as duplicate.
