### ISSUE TITLE
Explore automation options for managing capacity of the Docker image registry

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1805]
Develop a script to check the size of images uses by each namespace and alert the team assigned to that namespace if some threadhold (100Gi?) is crossed. 

Refer to this platform experience issue for more info:
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/499

**Comment by StevenBarre** [comment]
Script users can run on their own namespaces https://github.com/bcgov/how-to-workshops/pull/4/files

**Comment by StevenBarre** [comment]
Draft PR https://github.com/bcgov-c/platform-tools/pull/103

Still lots of debug code in there, and polish needed, but it does the basics of adding the namespaces to a queue, firing up parallel jobs to process the queue, counting up the size of the image registry for each NS and sending an email if over a size.

**Comment by StevenBarre** [comment]
PR completed and approved. Code launched on prod clusters to send weekly emails.
