### ISSUE TITLE
Develop image management guidelines for PS team members

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#1807]
We would like a document xor video that helps teams understand how to manage images and what are the surrounding best practices.

**Comment by mitovskaol** [comment]
Linking to [the ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1805) for developing a script for teams to tell them how much space they use in the image registry. This script should be mentioned in the documentation.
