### ISSUE TITLE
Automate SSO setup for OCP4 cluster auth

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1809]
**Describe the issue**
So far we only have doc on how to setup KeyCloak client and authentication flow for OCP4 cluster login, we will need some automation on this process.

Details:
- Description of manual steps required can be found in [Issue BCDevOps/OpenShift4-RollOut#404](https://github.com/BCDevOps/OpenShift4-RollOut/issues/404)
- Ansible Playbook is used for running the automation
- basically calling SSO APIs for setup steps, reusing some SSO resource management playbook for this task
- a service account from SSO master realm is required for this action

**Definition of done Checklist (where applicable)**
1. Create ansible playbook to automate the setup:
2. create docs
3. deploy somewhere vs. run locally

**Status**
- Blocked: Currently we are waiting until we settle down on deciding which SSO service (oidc/cloud/simple auth option/etc) to use for cluster login.
- Automation is half way through for SSO setup: https://github.com/BCDevOps/keycloak-admin/tree/master/keycloak_realm_builder/scripts/custom_usage#3-setup-ocp4-cluster-login-keycloak-flow)

**Comment by lukegonis** [comment]
Still relevant

**Comment by ShellyXueHan** [comment]
not relevant anymore as SSO team provide realm backup now.
