### ISSUE TITLE
iStore Order: Decom Platform Services’ INFRA VMs MCS SILVER INFRA 07 08 and 09

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1813]
**Describe the issue**
iStore Order for: Decom Platform Services’ INFRA VMs MCS SILVER INFRA 07 08 and 09
Date Submitted: October 27, 2021
iStore Number: 1083768
Lead time (business days after EA Approves):

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [x] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by juhewitt** [comment]
@lukegonis this hasn't come through to me yet as EA.
