### ISSUE TITLE
Add NetPol to edb-operator namespace

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1814]
**Describe the issue**
The Compliance Operator has identified that some namespaces don't have any NetworkPolicies and is encouraging us to add them.

**Additional context**
https://github.com/bcgov/how-to-workshops/tree/master/labs/netpol-quickstart

**Definition of done**
Add KNP to edb-operator namespace

**Comment by caggles** [comment]
Added a network policy to the edb-operator namespace in Silver and KLAB.
