### ISSUE TITLE
Add NetPol to Pye namespaces

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1816]
**Describe the issue**
The Compliance Operator has identified that some namespaces don't have any NetworkPolicies and is encouraging us to add them.

**Additional context**
https://github.com/bcgov/how-to-workshops/tree/master/labs/netpol-quickstart

**Definition of done**
Add KNP to these namespaces:
- [x] gitops-tools
- [x] platform-provisioner-dev
- [x] platform-provisioner-prod
- [x] platform-provisioner-test
- [x] platform-provisioner-tools
- [x] platform-registry-test
- [x] platform-utils-operator
- [x] pye-sandbox
- [x] sealed-secrets
- [x] vault-dev
- [x] vault-prod
- [x] vault-test
- [x] vault-tools

**Comment by IanKWatts** [comment]
@StevenBarre A pull request has been created for the namespaces managed by CCM.
- gitops-tools
- platform-utils-operator
- sealed-secrets
https://github.com/bcgov-c/platform-gitops-gen/pull/357

These namespaces will be updated via argocd manifest repo or manually:
- `platform-provisioner-*`
- `platform-registry-*`
- pye-sandbox

The `vault-*` namespaces are empty and Vault itself is in openshift-bcgov-vault, so maybe those need to be removed.  I'll ask around.

**Comment by IanKWatts** [comment]
@StevenBarre Default network policies have been added to all of these namespaces in each cluster where they exist [1].  Regarding my comment above, we are keeping the vault namespaces; they are meant to be used for testing.  As noted, some were updated via CCM and some manually.

[1] pye-sandbox in golddr still needs this update, but I don't have perms there.  Asking Justin to make that update.
