### ISSUE TITLE
Aqua - DB corruption hot fix

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#1819]
**Describe the issue**
Aqua databases (server/pubsub/audit) started to get into recovery mode from yesterday Oct 28 (as db backup failed that day already), but having issue getting back to working status.

Here are the actions that I've tried:
- first shutdown aqua services
- restarting DB pods, giving same issue (forgot to capture some log....)
- restoring DB backup from backup container. Failed with following error (might be that the backup copy was corrupted already, but not captured by verification step)
  ```
  psql: error: could not connect to server: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
  ```
- then we decided to go with a clean start and deleted the PVCs. Restart DBs and services, run the post deploy job, bring back up scanner. 

We are still see the DB pods showing logs:
```
2021-10-29 17:13:50.749 UTC [315] LOG:  incomplete startup packet
```

but the database service and Aqua are running fine now. Should look into this soon!

**Follow up:**
- [x] get admin users access to the namespaces: https://github.com/bcgov-c/platform-gitops-gen/pull/293
- [x] look into db `incomplete startup packet` log
- [ ] then look into backup container issue

**Comment by patricksimonian** [comment]
incomplete startup packet log is due to sysdig I do believe. https://stackoverflow.com/questions/59196280/getting-incomplete-startup-packet-in-postgresql-logs

**Comment by patricksimonian** [comment]
I'll look into why backup container verifications aren't working

**Comment by patricksimonian** [comment]
database verifications have been failing due to server timeout. https://chat.developer.gov.bc.ca/channel/devops-how-to?msg=2YKcerFwXC4XqCbmT

Need to set `DATABASE_SERVER_TIMEOUT` env var to something high like 300 seconds
