### ISSUE TITLE
Add XRAY role and rolebinding to CCM

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1820]
**Describe the issue**
Steve added the role live in Silver, but this should be codified in CCM to ensure consistency.

**Additional context**
https://github.com/bcgov/platform-services-xray/blob/main/templates/rabbitmq-role.yaml

**Definition of done**
- PR to CCM to create the Role and Binding

**Comment by caggles** [comment]
PR: https://github.com/bcgov-c/platform-gitops-gen/pull/317
