### ISSUE TITLE
Developer Jenkins Pipeline Tempate

### ISSUE THREAD

**Issue by Nicole-Huard** [BCDevOps/developer-experience#1825]
DoD:

- [ ] create pipeline templates in the pipeline template repo that follow the same pattern as was developed for GitHub Actions.

**Comment by Nicole-Huard** [comment]
@mitovskaol based on yesterday's conversation, will you prefer to keep this in backlog or close the issue?

**Comment by mitovskaol** [comment]
Closing the issue as we will be enoucaraging teams to migrate from Jenkins to other automation tech.
