### ISSUE TITLE
Create UI for the Assessment App

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1826]
The Config Assessment app built to evaluate the correctness of Openshift configuration of Ministry apps on the Platform, needs a new UI that includes the BC Gov look-n-feel.

DoD:
-  [x]  the screenshot mockups (non-functional) of the new UI  are created and reviwed/approved by the Platform team
-  [x] the UI components based on the [BC Gov's bootstrap theme](https://github.com/bcgov/bootstrap-theme) are added to [the app repo](https://github.com/bcgov/AppAssessment) 
-  [x] the running app in KLAB is updated with the new UI and signed off by Olena

**Comment by mitovskaol** [comment]
@ShovelHand  Can you please work on the UI mockups with @marthaedwards  and attach them to this ticket for the team to review

**Comment by ShovelHand** [comment]
[https://app.zenhub.com/files/220104031/83bc9138-ff14-4f8d-af90-7bcbf69a17ea/download](https://app.zenhub.com/files/220104031/83bc9138-ff14-4f8d-af90-7bcbf69a17ea/download)
I have attached a PDF of the input with some stylings I've applied to the output.

**Comment by ShovelHand** [comment]
@mitovskaol Pardon me, Olena, I should have directed your attention to this to check off that last DoD box. Can you see the report by visiting https://console.apps.klab.devops.gov.bc.ca/topology/ns/7f8e79-tools?view=graph and clicking on the link, or by going directly to https://web-frontend-7f8e79-tools.apps.klab.devops.gov.bc.ca/?

**Comment by mitovskaol** [comment]
Looks good to me Alex. The ticket can be closed.
