### ISSUE TITLE
Add oAuth to the Assessment app

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1827]
The [Assessment app](https://github.com/bcgov/AppAssessment) needs to be wrapped with OAuth so that its users can only produce/see assessment reports for the namespaces in Openshift that they have access to.

DoD:
-  [x]  the Assessment app needs to be integrated into the KeyCloak SSO realm that is used for authentication on the cluster it runs on (KLAB or Silver)

**Comment by ShovelHand** [comment]
OAuth is now implemented in AppAssessment, but it must be noted that we ended up not using KeyCloak SSO, and instead used an OAuth-Proxy sidecar as described in this Git repository: https://github.com/openshift/oauth-proxy.
