### ISSUE TITLE
Deploy the Assessment app to Silver 

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1828]
The Assessment app should be installed in the Silver cluster and made available to the product teams to install it and run in their namespaces.

DoD:
-  [x] the Assessment app has been successfully tested in KLAB (including oAuth)
-  [ ] the Assessment app is available as an item in the Catalogue in the Silver cluster

**Comment by ShovelHand** [comment]
Closing this issue with the note that after discussing amongst the team, we reached consensus that making this available through the catalog is not the way to go. The first test users, specifically Michael Wells, had installed this through the command line. Details for doing this are available in the Git ReadMe for the project.
