### ISSUE TITLE
Document ArgoCD Shared Architecture

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1830]
DoD:

- a link to the document describing the shared AroCD architecture included in this ticket.

This doc has been added to the platform-services-docs repo.
https://github.com/bcgov-c/platform-services-docs/tree/main/argo

**Comment by mitovskaol** [comment]
@IanKWatts Can you please include the link to the doc in the ticket when it exists

**Comment by IanKWatts** [comment]
Sure, I can create this after I have had a KT session for the operator with Justin Pye.
Existing docs in the team document space include:
- ArgoCD Shared Instance Overview
- ArgoCD Shared Instance RBAC Model
- ArgoCD Shared Instance Test Plan
