### ISSUE TITLE
Schedule Rocketchat upgrade

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#184]
- test on moving to cloud cluster
- version 3 is available with several fix: https://github.com/RocketChat/Rocket.Chat/issues/16296#issuecomment-599914331

**Comment by ShellyXueHan** [comment]
blocked: waiting for suitable cluster

**Comment by lukegonis** [comment]
Closing this issue as it is a duplicate of issue 209
