### ISSUE TITLE
SIEM - SAML Assertions

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1850]
Ensure Users associated w/ Namespaces are able to be assigned assertions to see that data in the SIEM interface

**Comment by bruce-wh-li** [comment]
We already able to support SAML to authenticate SIEM using Keycloak SSO service.  It's two phase.  The first phase the role is hardcoded.   The second phase, we are able to configure the role based on its SAML group.  But, it is all manual process for now.
