### ISSUE TITLE
Decide on Resouce Quota Naming Convention

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1853]
We want to change the resource quotas for projects in the OCP 4 Platform by introducing additional sizes as per the screenshot below. We want to come with a way to refer to different quota sizes that is different from T-shirt sizes. 

One option is to have a quota name reflect the resource type (`C` for CPU, `R` for RAM and `S` for Storage) and the **Limit** amounts e.g. `C1.5` for 1.5 core of CPU or `S32` for 32Gb of Storage or `R64` for 64Gb of RAM.

Teams will be able to request a resource increase for their projects by selecting the appropriate resource quota size in the dropdown on the project edit page in the Resource Registry e.g. `C4`and `S1` for `-dev` namespace and  `C4` and `S64` for `-prod` namespace

Please add your opinion in the comments.

DoD:
- [x]  the Platform Services Team agrees on the quota naming convention 

 ![CPU-RAM T-shirt Quotas.png](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/e409edfb-cd3c-4fdd-930e-d2b36f9112bb)

![Storage T-shirt Quotas.png](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/f69c325d-0205-465d-b678-7cff53a1e408)

**Comment by StevenBarre** [comment]
Suggest `M` for Memory instead of RAM. `V` for Volumes / PVC Claims (separate from storage size).

**Comment by mitovskaol** [comment]
Proposing the following quota names that will be show in the quota management dropdown on the project edit page in the Project Registry:
CPU: `C0.5`, `C1`, `C2`, `C4`, `C8`, `C16`, `C32`
RAM:  `M1.5`,`M2`,`M4`,`M8`,`M16`,`M32`,`M64`
Storage: `S1`,`S2`,`S4`,`S16`,`S32`,`S64`,`S128`,`S256`, `S512`,
PVC: `V10`, `V20`, `V60`

**Comment by sbathgate** [comment]
Is there a reason that XXS is C0.5/C1.5 instead of doubled like all other apps? Just to account for potential overages where it is smaller?

I am also personally partial to decoupling the numeric value from the actual resource value. 
so:
C1,C2,...,C7,Cn
M1,M2,...Mn

I figure this may enable us to more easily adjust in the future as otherwise are we choosing the Request or Limit in the values above and could there be occasion that the Request / Limit ratios may vary. In the event we did change the values, we would also only need to update this in the Quota table vs updating every single project in the Registry to reflect the new sizes.

**Comment by mitovskaol** [comment]
The quota sizes have been calculated based on the machine learning analysis that Justin and Poornima did and the data shows that almost 30% of all app would do well with 0.5core so I think we should only give them what they need and not round it up.

Re: decoupling the quota names from actual resources, it will be very difficult to remember/understand when a team mentions in a conversation that they are on C5 and want to go to C7 how much resources they actually have and how many they want to upgrade to vs if they say we are on C2 and want to go to C4, it will be immediately clear that they need to ugprade from 2 core to 4 cores.

**Comment by StevenBarre** [comment]
Agree about having the number match the quantity of resource. Future adjustments would be to make new quotas and slowly migrate people. We can't easily do mass changes to quotas without causing a lot of issues with teams.

**Comment by sbathgate** [comment]
RE: the 0.5 discussion, it was more an observation that most request / limit values are Request 1 / Limit 2, (where limits are double the Request Value) in comparison to the first value which it is tripled. Just seems like a unique break of the pattern. 

And for sure there is a clarity in the initial proposed scheme, I was mostly concerned with the fact, C2 is (as I understand it) the Request value, so a: has no relevance to the limit unless we always intend to have it as double, which I don't imagine we can definitively state, so what would the plan be in the event that the doubling pattern varies (as seen in the 0.5 CPU for example)... which also, is it a concern? Or do we only care about Request value in this context?  and b: could make this a bit more troublesome in the future to maintain. Aspects could be seen as an argument of UX vs Maintainability sort of thing.

**Comment by mitovskaol** [comment]
It is only "Request" that is included in the "reserved but not used" resources that are taken from the shared resource pool and so the quota names are based on the **maximum** value of the "Request" setting. The expectation that for the Limit value the teams will use 1:2 or 1:3 ratio for the Request : Limit.

**Comment by IanKWatts** [comment]
@lukegonis I see that this issue is closed, but there is no comment on what the final decision was regarding the names of the sizes.  Can we add that here?

**Comment by j-pye** [comment]
@IanKWatts I'll post the list shortly

**Comment by j-pye** [comment]
@mitovskaol @lukegonis @juhewitt @IanKWatts 


**CPU Quotas:**

All CPU Requests and Limits are represented in cores (not millicores)

```
cpu-request-0.5-limit-1.5
cpu-request-1-limit-2
cpu-request-2-limit-4
cpu-request-4-limit-8
cpu-request-8-limit-16
cpu-request-16-limit-32
cpu-request-32-limit-64
```

**Memory Quotas:**

All Memory Requests and Limits are represented in GIB

```
mem-request-2-limit-4
mem-request-4-limit-8
mem-request-8-limit-16
mem-request-16-limit-32
mem-request-32-limit-64
mem-request-64-limit-128
```

**Storage Quotas:**

All Storage sizes are in GiB, and backup quotas default to half the storage size but are not shown above so won't be made apart of the quota label.

```
storage-1
storage-2
storage-4
storage-16
storage-32
storage-64
storage-128
storage-256
storage-512
```

-- The registry db should be structured in a way that additional quota sizes can be added for VolumeSnapshots or PVCs incase there is ever a need to extend our current line of thinking.
