### ISSUE TITLE
Vault Troubleshooting Guide

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1857]
**Describe the issue**
Develop a troubleshooting guide for Vault. This will be used in the after hours support process as this continues to evolve.
This will require:
- [x] Vault Service Definition
  - [x] Summary
  - [x] Service Leads
  - [x] Application Details
- [x] Triage Process
- [x] Diagnostic Steps
- [x] Support Services
  - [x] Support Contacts
  - [x] Hours of Availability
  - [x] Response Times
  - [x] Technical Contacts
  - [x] Severity Definitions
- [x] Resources

**Definition of done**
When the Vault troubleshooting guide is formatted and complete for reference.

**Comment by j-pye** [comment]
Much of the troubleshooting documentation has been added to https://github.com/BCDevOps/openshift-wiki/tree/master/docs/Vault
