### ISSUE TITLE
ArgoCD Troubleshooting Guide

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1858]
**Describe the issue**
Develop a troubleshooting guide for ArgoCD. This will be used in the after hours support process as this continues to evolve.
This will require:
- [x] ArgoCD Service Definition
  - [x] Summary
  - [x] Service Leads
  - [x] Application Details
- [x] Triage Process
- [x] Diagnostic Steps
- [x] Support Services
  - [x] Support Contacts
  - [x] Hours of Availability
  - [x] Response Times
  - [x] Technical Contacts
  - [x] Severity Definitions
- [x] Resources

**Definition of done**
When the ArgoCD troubleshooting guide is formatted and complete for reference.

Here is the document:
https://docs.google.com/document/d/1HDbQXerK2i7R8sNpph0xbvy4Eqb5Wd_vpcqLBBL3yiE/edit?skip_itp2_check=true# 

And migrated to the DXC docs repo in Markdown format:
https://github.com/bcgov-c/advsol-docs/blob/master/argocd_troubleshooting_guide.md

**Comment by IanKWatts** [comment]
@mitovskaol  Regarding the points in the description of this task that are already marked as done, do you know where I could find that info?  I guess I'm looking for a document that describes the after-hours support of DXC and to which I could add the requested Argo CD troubleshooting information.

**Comment by mitovskaol** [comment]
@IanKWatts  I sent you the link to the ArgoCD troubleshooting guide in RC
