### ISSUE TITLE
Create AG-GitOps space for AG/PSSG

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1860]
In order to manage RBAC via YAML for all OCP namespaces, as well and implement KNPs for all AG/PSSG project sets, there is a desire to manage centrally through a single Argo-CD space linked to a private GitHub Repo.

- [x] Setup Argo-cd space for AG-GitOps
- [x] Add @rloisell to manage

**Comment by j-pye** [comment]
GitOps Repository created and AppProj Generated and Applied in Silver. 
Gold/GoldDR shared instance won't be deployed until ArgoCD Shared goes GA.
Lab configuration will happen later today.

**Comment by j-pye** [comment]
I'm considering this complete as setup has been complete in the labs, minor changes still required in silver but that'll happen after we go GA with ArgoCD Shared and the warden operator.

Feel free to reopen if needed.
