### ISSUE TITLE
Preparation of presentation on Sysdig Monitoring (Golden Signals)

### ISSUE THREAD

**Issue by Nicole-Huard** [BCDevOps/developer-experience#1867]
**Describe the issue**
Create a 1-hour "how-to" presentation to show how Sysdig can be effectively used to monitor applications, based on the demo provided during the January 4th meetup

**Additional context**

**Definition of done**
Presentation reviewed by BC Gov and ready for delivery

**Comment by Nicole-Huard** [comment]
@ShellyXueHan I've assigned you to this ticket, along with Frank, as we discussed that you would add content about onboarding to Sysdig.  We can look at regrouping on this once James has the demo ready! Sound good?

**Comment by ShellyXueHan** [comment]
sounds great! I don't think I'll have slides to add, just gonna screenshare and walk through the onboarding process directly.

**Comment by ShellyXueHan** [comment]
@mitovskaol we are looking to create a 1-hour "how-to" sysdig presentation after the January 4th meetup. It'll be pretty technical and focus on how to use sysdig to achieve monitoring goals. Would you suggest some times or event for this?

**Comment by mitovskaol** [comment]
@ShellyXueHan I suggest we run the "how-to" event as a developer workshop and scheduled it as a standalone event.

**Comment by Nicole-Huard** [comment]
@ShellyXueHan any update on the date for this?

**Comment by Nicole-Huard** [comment]
@mitovskaol or @ShellyXueHan  is there a scheduled date for the Sysdig Monitoring "how-to" developer workshop?

**Comment by mitovskaol** [comment]
@Nicole-Huard It is on Jan 4.

**Comment by ShellyXueHan** [comment]
I think Nicole is asking for the 1hour session, not the shorter one on community meetup. We don't have any reoccurring event to fit an hour long demo yet. Shall we just make a time directly and send out an invite to the community?

**Comment by mitovskaol** [comment]
@ShellyXueHan Yes, lets run in the week following the demo at the Meetup, the week of Jan 10. Feel free to pick a day and a time in the afternoon (2:30-3:30?) and send an invite out to the attendee list for the Meetup

**Comment by Nicole-Huard** [comment]
Thanks @mitovskaol 
@ShellyXueHan I'm just checking in with James on his availability that week, as he's based in Ontario.  Looking at his schedule for the week, I've suggested Wed 12, 2:30-3:30 so will let you know his response. Is 2:30 the best time for the community or might we be able to bump it up to 1:30 or 2?

**Comment by ShellyXueHan** [comment]
@Nicole-Huard 1:30 or 2 definitely works! Feel free to just a pick a time then. We can also advertise that during the meeting up a week ahead!

**Comment by Nicole-Huard** [comment]
@ShellyXueHan @mitovskaol lets go with Wednesday January 12th at 1:30 PT for the 1 hour "how to" session please!

**Comment by ShellyXueHan** [comment]
### Updates:
- [x] mautic email with presentation overview
- [ ] email with calendar item - will send in the new year!
- [ ] Rocketchat messages as second reminder

**Comment by ShellyXueHan** [comment]
okay presentation moved to 18th 1-2pm due to conflicts with ocp101. invites sent as well!
