### ISSUE TITLE
Developer Tekton Build & Deploy Pipeline Template

### ISSUE THREAD

**Issue by Nicole-Huard** [BCDevOps/developer-experience#1869]

**Comment by Nicole-Huard** [comment]
@j-pye @IanKWatts @mitovskaol when you have a chance, can you please review the Tekton Build & Deploy template? https://github.com/bcgov/pipeline-templates/tree/main/tekton#installation

**Comment by IanKWatts** [comment]
@Nicole-Huard I'm reviewing the pipelines.  I'll need a little time to test them and provide feedback.

**Comment by Nicole-Huard** [comment]
Thanks @IanKWatts!  Do you have a timeline in mind for when we might receive your feedback?

**Comment by gregnrobinson** [comment]
I’m also doing a build and deploy using s2i which will be finished today
because I know a lot of folks use s2i for deploying applications.  It right
now the build-deploy-helm is the one to test for the deployment side.

**Comment by IanKWatts** [comment]
@Nicole-Huard I'm working on it when I can.  Hopefully we can sign off on it by the end of the week.

**Comment by Nicole-Huard** [comment]
Reviews complete; presented at Meetup Jan 4th; Olena confirmed we can move on to the recordings
