### ISSUE TITLE
Evaluate Cert-Manager in KLAB - Setup Operator

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1876]
https://cert-manager.io/docs/

This task is primarily to evaluate cert manager for automating self-signed certs, however, this tool also works for Let's Encrypt and several other certificate providers. 

This ticket will focus on operator setup only.

- [ ] Setup operator in KLAB

**Comment by NickCorcoran** [comment]
Cert manager is now an operator in OCP.  Looking to deploy that in KLAB to test.  Wade has agreed to help with testing against Entrust once setup.

**Comment by NickCorcoran** [comment]
This ticket has been replaced with this one: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4891
