### ISSUE TITLE
Resource Tuning Advisor App Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1879]
**Describe the issue**
To ensure proper support and response of our support applications, essential monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [ ] CPU Utilization
- [ ] Memory Utilization
- [ ] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Montoring/Alerting Configurations setup.
- [ ] AI OPS/Resource Tuning Advisor App

**Comment by mitovskaol** [comment]
We are not going to build this app at this moment
