### ISSUE TITLE
ArgoCD (Shared) App Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1881]
**Describe the issue**
To ensure proper support and response to Platform Services applications issues, baseline monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [x] CPU Utilization
- [x] Memory Utilization
- [x] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Monitoring/Alerting Configurations setup.
- [ ] ArgoCD (Shared)

**Comment by w8896699** [comment]
dashboard is monitoring :
Pod availablility
Patroni db fullness
Statutory of resources
Error rate

Alert has set for:
any pods go down
RAM used more than 95% of limited
CPU used more than 95% of limited
higher than 0.05% of http error

Todo, will need to add uptime.com check on this

**Comment by w8896699** [comment]
Added argocd silver into status page
