### ISSUE TITLE
Enterprise DB Operator Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1886]
**Describe the issue**
To ensure proper support and response to Platform Services applications issues, baseline monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [ ] CPU Utilization
- [ ] Memory Utilization
- [ ] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Monitoring/Alerting Configurations setup.
- [ ] EnterpriseDB Operator

**Comment by caggles** [comment]
This actually isn't relevant - there's nothing to monitor for the Platform Team operator, since each team uses their own namespaced operator.
