### ISSUE TITLE
Just Ask App Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1887]
**Describe the issue**
To ensure proper support and response to Platform Services applications issues, baseline monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [x] CPU Utilization
- [x] Memory Utilization
- [x] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Monitoring/Alerting Configurations setup.
- [x] Just Ask!

**Comment by ShellyXueHan** [comment]
dashboard:
- silver production: https://app.sysdigcloud.com/#/dashboards/270261?last=3600&scope=kubernetes.namespace.name%20as%20%22Namespace%22%20in%20%3F%28%22bdec76-prod%22%29%20and%20kubernetes.cluster.name%20as%20%22Cluster%22%20in%20%3F%28%22silver%22%29

**Comment by w8896699** [comment]
Alert on:
Pod down
Run out of CPU 75%
Run out of RAM 85%
Network latency 4s
Namespace run out of quota 90%

For golden signals dashboard can be found [here](https://app.sysdigcloud.com/#/dashboards/347607?last=1209600&scope=kubernetes.cluster.name%20as%20%22cluster%22%20in%20%3F%28%22silver%22%29%20and%20kubernetes.namespace.name%20as%20%22namespace%22%20in%20%3F%20and%20kubernetes.workload.type%20as%20%22type%22%20in%20%3F%20and%20kubernetes.workload.name%20as%20%22workload%22%20in%20%3F%28%22just-ask-api%22%2C%20%22just-ask-db%22%2C%20%22just-ask-web%22%2C%20%22just-ask-backup-4%22%29%20and%20container.label.io.kubernetes.pod.name%20as%20%22pod%22%20in%20%3F)

Container Resources Usage and be found [here](https://app.sysdigcloud.com/#/dashboards/347607?last=1209600&scope=kubernetes.cluster.name%20as%20%22cluster%22%20in%20%3F%28%22silver%22%29%20and%20kubernetes.namespace.name%20as%20%22namespace%22%20in%20%3F%20and%20kubernetes.workload.type%20as%20%22type%22%20in%20%3F%20and%20kubernetes.workload.name%20as%20%22workload%22%20in%20%3F%28%22just-ask-api%22%2C%20%22just-ask-db%22%2C%20%22just-ask-web%22%2C%20%22just-ask-backup-4%22%29%20and%20container.label.io.kubernetes.pod.name%20as%20%22pod%22%20in%20%3F)
