### ISSUE TITLE
Platform Services Comms Subscription Service App Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1890]
**Describe the issue**
To ensure proper support and response to Platform Services applications issues, baseline monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [ ] CPU Utilization
- [ ] Memory Utilization
- [ ] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Monitoring/Alerting Configurations setup.
- [ ] Platform Services Comms Subscription Service (Mautic)

**Comment by w8896699** [comment]
Alert: 
Mautic pod down. 
Mautic pvc full. alert if is almost full(reach 95%)
If mysql db is down
Mautic resources quota >90% (used/limited)

Four golden signals dashboard can be found in [here](https://app.sysdigcloud.com/#/dashboards/347606?last=1209600&scope=kubernetes.cluster.name%20as%20%22cluster%22%20in%20%3F%28%22silver%22%29%20and%20kubernetes.namespace.name%20as%20%22namespace%22%20in%20%3F%20and%20kubernetes.workload.type%20as%20%22type%22%20in%20%3F%20and%20kubernetes.workload.name%20as%20%22workload%22%20in%20%3F%20and%20container.label.io.kubernetes.pod.name%20as%20%22pod%22%20in%20%3F%20and%20kube_pod_label_app%20in%20%3F%28%22mautic%22%29):
