### ISSUE TITLE
RocketChat App Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1891]
**Describe the issue**
To ensure proper support and response to Platform Services applications issues, baseline monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [x] CPU Utilization
- [x] Memory Utilization
- [x] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Monitoring/Alerting Configurations setup.
- [ ] RocketChat / Reggie / Hubot

**Comment by ShellyXueHan** [comment]
Dashboards:
- gold: https://app.sysdigcloud.com/#/dashboards/262391?last=3600&scope=kubernetes.namespace.name%20as%20%22Namespace%22%20in%20%3F%28%2287d478-prod%22%29%20and%20kubernetes.cluster.name%20as%20%22Cluster%22%20in%20%3F%28%22gold%22%29
- golddr: https://app.sysdigcloud.com/#/dashboards/262392?last=3600&scope=kubernetes.namespace.name%20as%20%22Namespace%22%20in%20%3F%28%2287d478-prod%22%29%20and%20kubernetes.cluster.name%20as%20%22Cluster%22%20in%20%3F%28%22golddr%22%29

Alerts:
- CPU spike for RC and DB pods
- file system usage for RC and DB pods

**Comment by w8896699** [comment]
Dashboard: https://app.sysdigcloud.com/#/dashboards/379268?last=3600&scope=kubernetes.cluster.name%20as%20%22cluster%22%20in%20%28%22gold%22%2C%20%22golddr%22%29%20and%20kubernetes.namespace.name%20as%20%22namespace%22%20in%20%28%2287d478-prod%22%29%20and%20kubernetes.workload.type%20as%20%22type%22%20in%20%3F%20and%20kubernetes.workload.name%20as%20%22workload%22%20in%20%3F%20and%20container.label.io.kubernetes.pod.name%20as%20%22pod%22%20in%20%3F

Alert:
![Screen Shot 2023-02-27 at 5.39.41 PM.png](https://images.zenhubusercontent.com/5d6ffb905ec50a5aa4201bcb/de68f097-2f62-4ccc-87e0-06c4b0604cf5)
