### ISSUE TITLE
Vault App Baseline Monitoring / Alerts

### ISSUE THREAD

**Issue by sbathgate** [BCDevOps/developer-experience#1892]
**Describe the issue**
To ensure proper support and response to Platform Services applications issues, baseline monitoring and alerting is necessary within Sysdig. This includes the following:

Saturation Monitoring (alerts > 80%):
- [x] CPU Utilization
- [x] Memory Utilization
- [x] Storage Utilization

**Definition of done**
When the Platform Services application below have at least the Baseline Monitoring/Alerting Configurations setup.
- [x] Vault

**Comment by ShellyXueHan** [comment]
https://app.sysdigcloud.com/#/dashboards/258484?last=300&scope=kubernetes.namespace.name%20%3D%20%22openshift-bcgov-vault%22%20and%20kubernetes.cluster.name%20%3D%20%22gold%22

**Comment by ShellyXueHan** [comment]
### Updates:
- vault in silver: https://app.sysdigcloud.com/#/dashboards/258483?last=3600&scope=kubernetes.namespace.name%20%3D%20%22openshift-bcgov-vault%22%20and%20kubernetes.cluster.name%20%3D%20%22silver%22
-vault in gold: https://app.sysdigcloud.com/#/dashboards/258534?last=3600&scope=kubernetes.namespace.name%20%3D%20%22openshift-bcgov-vault%22%20and%20kubernetes.cluster.name%20%3D%20%22gold%22
