### ISSUE TITLE
Automatically Merge Platform Registry GitOps PRs

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#1900]
**Issue**
As a Registry Requester Approver, I'd like requests approved through the registry UI to be automatically merged.

**DoD:**

`.policy.yml` changes in each repository
- [x] `auto-merge` Label triggers automatic merge in Registry GitOps Repositories
- [x] `requires-approval` Label triggers automatic merge after Sync PR is approved

Provisioner Changes
- [x] Add appropriate labels for `create`, `edit`, `delete`, and `sync` actions

**Comment by IanKWatts** [comment]
Registry app updates are in the works
Pull requests have been created for each "namespace" repo for changes to the policybot and bulldozer files
