### ISSUE TITLE
iStore order - 21 GitHub Enterprise User Licenses

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1902]
**Describe the issue**
iStore Order for: iStore order request for 21 GitHub Enterprise User Licenses
Date Submitted: Nov 3, 2021
iStore Number: 1084496
Lead time (business days after EA Approves):

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to OCIO Enterprise Solutions
- [x] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by mitovskaol** [comment]
iStore order #1084496 for the 21 GitHub Ent licences has been processed and Shipped for billing.
