### ISSUE TITLE
Aqua - Data Migration to Patroni StatefulSet and DB changeover

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#1914]
## Summary

Patroni has been deployed in the clusters and now requires a one time job to migrate state over from aqua scalock db (aqua-db)

## To Do

- migrate state from aqua-db to patroni
- verify data
- change over service host from aqua-db to aqua-patroni-db in aqua server config map
- verify!

**Comment by patricksimonian** [comment]
The work is in progress but shelly and I decided to halt any changes to Aqua. It's also a good moment to pause and really consider switching aqua to CrunchyDb with a licence!

**Comment by ShellyXueHan** [comment]
### Update:
We've decided to use crunchy DB later on. Work will be captured in another ticket later on when it's available. closing now.
