### ISSUE TITLE
Nagios Monitoring - Change alerting period for Node Label checks

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1920]
**Describe the issue**
As part of ongoing curation of custom monitors written for Nagios, we are looking at monitors that do not need to run 24x7 but instead only need to notify us during waking/business hours, so that on-call staff are not potentially woken up for non-issues. 

One such monitor is our checking to ensure all nodes in a cluster have all required labels to be assigned so that daemonsets and similar items start up required pods on all nodes. This was a more critical item to do when we were running Aporeto, and we still want to have this check during business hours so that any new nodes we build do get a reminder monitor alert if we've forgotten one of the key node labels, such as ensuring Sysdig starts up.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Create change and test in a LAB environment.
- [ ] Create RFCs to promote changes in PROD. Will use existing RFCs created for other pushes.

**Comment by wmhutchison** [comment]
This item will be promoted for execution into Sprint 37. Will move once suitable Sprint SG is created.

**Comment by wmhutchison** [comment]
This can be moved to Sprint Backlog since I have full intent on taking on and completing this in next Sprint.

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/platform-tools/pull/94 created and tested successfully in CLAB.

**Comment by StevenBarre** [comment]
Changes completed
