### ISSUE TITLE
TLS certs for Aqua

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1923]
Patrick:
- [x] Generate .CSR for aqua.developer.gov.bc.ca to cover silver/gold/gold-dr
- [x] Generate .CSR for aqua.clab.developer.gov.bc.ca and aqua.klab.developer.gov.bc.ca
- [x] Provide files to Nick

Nick:
- [x] Prepare TLS cert iStore request form and provide to Luke for submission

**Comment by patricksimonian** [comment]
CSRs generated
