### ISSUE TITLE
Kickoff and document review

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1924]
**Describe the issue**
Review all the documentation we've been given to date.

**Additional context**
We were given these resources: 

Stakeholder stuff:
[Roadmap](https://app.mural.co/t/platformservices5977/m/cloudpathfinder2329/1623864264564/0527296c93e73799c641f7d9fae03f0139002aee?sender=udb0eaba57bd3b9a2fa8e3916)
[Cloud IA](https://app.mural.co/t/platformservices5977/m/platformservices5977/1626806093438/ca4fb81b38837ee25cb5d502afde73e0607fbb0f?sender=udb0eaba57bd3b9a2fa8e3916)
[Service Overview](https://docs.google.com/presentation/d/1ItipubvqCR1rI_VVVbx_swX659HPgN_tiwiKJp1eL94/edit#slide=id.gbdc1011b6a_0_517)
[Executive Sprint Overview](https://docs.google.com/presentation/d/1Az-vZ9wJocqPpNTWpfsfcB4ipqKgvTXDfAxqiDaSIyM/edit#slide=id.gddc6dce5bd_0_0)
[Evidence Based decision making in driving devops transformation](https://docs.google.com/presentation/d/1u8EuIhcUU3OW0sdbxGaRoMAxkhj-tbHQkBtz_cUupn4/edit#slide=id.gddc6dce5bd_0_0)

User stuff: 
These are the resources we have to date:
[Onboarding research analysis](https://app.mural.co/t/platformservices5977/m/platformservices5977/1632431504450/b95cf2daec2d23d395846f61fe056991bb9491e5?sender=udb0eaba57bd3b9a2fa8e3916)
[Service overview](https://docs.google.com/presentation/d/1ItipubvqCR1rI_VVVbx_swX659HPgN_tiwiKJp1eL94/edit#slide=id.gbdc1011b6a_0_517)
[Platform challenges](https://docs.google.com/presentation/d/1_V2hQv-wW4FiClZ3T9IPXTs8CbS3KlQUdCTPYOjod00/edit#slide=id.p1)
[BMC workshop preso](https://docs.google.com/presentation/d/1wccNb90inALBbeySerbZLMqkbVjhQmJQsxZ0xpyAC4c/edit#slide=id.p1)
[Developer experience challenges poll](https://docs.google.com/spreadsheets/d/1uVKwFSmfpEdAPvo17DLJ_VkLLKi2yOCod1E7hkiX4FU/edit#gid=0)
[Raw data from BMC workshop](https://docs.google.com/spreadsheets/d/1WZeA8Ffk-0WyLOqp5ht5WvGH_XENFJV3nFsZo7MclSo/edit#gid=1189636354)
[Private cloud BMC](https://app.mural.co/t/platformservices5977/m/cloudpathfinder2329/1616704079748/fe26c5ca20ed0cdbc651f60b2370db708d34a9f0?sender=udb0eaba57bd3b9a2fa8e3916)
[Service blueprint](https://app.mural.co/t/platformservices5977/m/cloudpathfinder2329/1612805170526/e783ab82c0e658a661f97431218df00858efffe9?sender=udb0eaba57bd3b9a2fa8e3916!)
[Bjorns Experience DevOps Journey Map-smallResolution (1).png](https://images.zenhubusercontent.com/619e7c0917f0b96bbcf6d42f/0519eb43-06ed-4e6a-8c4e-c2446ec6a2d8)
[Roadmapping prioritization community engagement](https://app.zenhub.com/files/220104031/9f7c208d-15c1-48ee-970f-30721be6e2c7/download)
[DevOps platform workshop voting](https://app.zenhub.com/files/220104031/e15bd0b0-8463-42d8-89c0-fa85056022d1/download)
[Product Owner platform workshop voting](https://app.zenhub.com/files/220104031/179f11e3-6626-4f8d-91eb-9b8b275132e8/download)

**Definition of done**
These resources are slotted into the "user research - review documentation" or "stakeholder research - review documentation" issues.

**Comment by theresawuzhere** [comment]
The User research has been put into "User research and engagement - Review research to date #1927"
Stakeholder research has been put into "Stakeholder research and engagement - Review research to date #1926"
These files have been reviewed and put into these issues so they can be evaluated.
