### ISSUE TITLE
Content Audit - Quality

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1925]
**Describe the issue**
We want to look at the content from an editorial perspective including: 

- The on-page content is well organized (flows well, easy to scan, flows from most to least important, uses media appropriately
- Is grammatically correct and readable, uses the active voice, avoids cliches, long sentences, redundant detail.
- Is written for a specific audience, includes the right amount of context
- Focuses on one topic per page, is succinct and easy to understand
- Meets the organization's brand guidelines

**Additional context**
This document explains a lot about content audits and is from Emma's company. See the section on Quality Audits.
[https://app.zenhub.com/files/220104031/ddced749-b620-477a-9b87-875e0cc8179e/download](https://app.zenhub.com/files/220104031/ddced749-b620-477a-9b87-875e0cc8179e/download)

**Definition of done**
- [x] Quality content audit spreadsheet filled in

**Comment by theresawuzhere** [comment]
@lukegonis I have updated the issue
@emma-csi after you are done, please put it in review and assign it to me.

**Comment by theresawuzhere** [comment]
The quality audit is combined into the [content audit slidedeck](https://docs.google.com/presentation/d/11hux0jB-DP16JdAbPvh5hlK-oOJ8HcpRDwrC04UN7HU/edit?usp=sharing)
