### ISSUE TITLE
Turn on specific Aqua runtime policies

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1938]
Enable the following policies that are currently in Audit mode only:

![image.png](https://images.zenhubusercontent.com/5d8aa0380d75970001f889be/00fa2b5d-1dc7-4ed0-8811-ace38dbc6449)
![image.png](https://images.zenhubusercontent.com/5d8aa0380d75970001f889be/f7a24926-c610-42c9-8431-87546a562fec)

- [x] Enable
- [x] Monitor
- [x] Announced at community meetup
- [x] Drafted communication
- [ ] Collect any feedback (if any)

**Comment by StevenBarre** [comment]
Will an email be sent out to all platform users telling them this is being turned on and what it might look like if something is blocked?

**Comment by NickCorcoran** [comment]
I discussed this at the last community meetup, but a communication is likely a good thing.  Thanks @StevenBarre.  I am prepping something and will get @mitovskaol to share.
