### ISSUE TITLE
User Research and Engagement - Make recruitment plan

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1945]
**Describe the issue**
We will create a research plan that addresses the recruitment needs for the design portion of our work - we'll focus on case study interviews, card sorting, task testing, and content testing

**Additional context**
None

**Definition of done**
- [x] Research plan started that has recruitment needs.

**Comment by theresawuzhere** [comment]
I evaluated this for the discovery phase, to see if we needed to do any exploratory user research. The answer is that we do not need to do this exploratory research. We will need to do evaluative user research on the site structure, but this will be in the design stage. I've moved this back into the backlog, hopefully that's ok @lukegonis

**Comment by theresawuzhere** [comment]
Here is the research plan
https://docs.google.com/document/d/1WFSgAHKgfzWhEgPsBRYM7LSqIgQ8JXhgocqbjLku574/edit?usp=sharing

**Comment by mitovskaol** [comment]
@theresawuzhere The research plan looks great!
