### ISSUE TITLE
Create recordings showing how to use the GitHub Actions Security Pipeline Templates

### ISSUE THREAD

**Issue by Nicole-Huard** [BCDevOps/developer-experience#1949]
**Describe the issue**
Short recordings to help the BC Gov community use the GitHub Actions Security Pipeline Templates created

**Additional context**
standard 5 min "how-to" video that will help a developer to get started with the templates

**Definition of done**

- [ ] Recordings created by Arctiq Team
- [ ] Recordings reviewed by BC Gov team
- [ ] Recordings available to BC Gov community

**Comment by Nicole-Huard** [comment]
@mitovskaol any additional requirements or context for the recordings? e.g. expected length?

**Comment by mitovskaol** [comment]
@Nicole-Huard  No additional requirements, a standard how-to video that will help a developer to get started with the templates. In terms of length, it should be under 5 min if possible.
