### ISSUE TITLE
Collect list of applications supported by platform service 

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#195]
During platform outage, we need to verify the status of the services that PS is supporting, so that the team can monitor and update the community.

Info to provide:
- application
- namespaces
- routes

**Comment by ShellyXueHan** [comment]
Rocketchat:
- e5imao-prod
- chat.pathfinder.gov.bc.ca

KeyCloak:
- devops-sso-*
- sso.pathfinder.gov.bc.ca
- sso-dev.pathfinder.gov.bc.ca
- sso-test.pathfinder.gov.bc.ca

Signing service:
- devhub-*
- https://signing-web-devhub-prod.pathfinder.gov.bc.ca 

Realm-o-matic:
- devhub-*
- https://realm-o-matic.pathfinder.gov.bc.ca/

Reggie:
- devhub-*
- https://reggie.pathfinder.gov.bc.ca/

**Comment by caggles** [comment]
We should also check on Jenkins instances in all of the above namespaces (though doing so should be secondary to checking on the apps themselves)

**Comment by ShellyXueHan** [comment]
sounds good. I've added this info to the admin documize page.
