### ISSUE TITLE
Cert Renewal for chat.developer.gov.bc.ca

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1953]
**Describe the issue**
iStore Order for: Cert Renewal for chat.developer.gov.bc.ca
Date Submitted: November 25, 2021
iStore Number: 1086961
Lead time (business days after EA Approves):

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [ ] EA Approves 
- [ ] Order is sent to DXC for fulfillment 
- [ ] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by ShellyXueHan** [comment]
### Updates:
- New CSR generated
- got the new certs back fro, Kristine already
- installed in all rocketchat instances as well - expiry date is 2022-12-24 now :)
