### ISSUE TITLE
Document the approach for project deletion feature in Project Registry

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#1954]
This ticket will capture the design decisions for the project deletion feature in the Registry.

DoD:
 - [ ] the project deletion specification is documented in this ticket and signed off by the PS team.

Suggested basic functional requirements:
- a PO or TLs  or Project Registry Admins should be able to request a project deletion from the project edit page e.g. press a "Delete" button 
Assumption: project deletion will remove ALL 4 namespaces for the project set )`dev`, `test`, 'prod`,  and `tools`. We will not allow the removal of individual namespaces in a project set at the moment.
- a pop up should appear asking the requestor to confirm their decision and reminding them that the removal is final and the project cannot be restored once deleted
- the following internal checks would have to pass before the request can be process:
  - all pods in the project namespaces should be scaled down to 0 by the product team
  - all PVS in the project namespaces should be removed by the product team

If any of the checks above is not passed, notify the requestor that these actions must be taken by the product team before the request can be processed.

Once all checks are passed, the following changes will happen:
- the project record in the Registry database is marked as "Archived" and will not appear on the dashboard in the UI anymore. 
- the 4 namespaces in the Openshift are deleted by the provisioner + whatever provisioner changes are required
- an email is sent to the PO/TLs of the deleted project confirming that the project was deleted

**Comment by w8896699** [comment]
Delete feature will have 4 steps before sending the request after the user click the Delete button:
1: Let user confirm the Project they want to delete is correct
2: Let user confirm that all pods are scale down, data has been backuped
3: User will need to wait provisioner go check if namespaces are all there and pods are down
if yes, process step 4, if no, let user know and terminate the deletion process
4: Let user confirm again 
Send request.
