### ISSUE TITLE
OCP4.8 - Research and Prep work for Openshift upgrade and associated components

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#1956]
**Describe the issue**
This issue will track the effort spent towards researching and documenting both the technical requirements for upgrading to Openshift 4.8, as well as fleshing out all of the ZenHub EPICs/tickets in similar fashion to what was done with Openshift 4.7. The intent is to ensure that the R & D is done in advance so that in January 2022 we can hit the ground running in terms of final LAB testing and PROD cluster implementation.

William Hutchison will be running with this work primarily, and Steven Barre will support and QA the results before we move towards implementation. Steven may provide additional feedback of components needing inclusion that might not be ready now but could be when we get closer to implementation date.

**Additional context**

**Definition of done**
- [x] Document summary of technical changes involved with the upgrade
- [x] QA technical summary before we start creating tons of ZenHub tickets
- [x] Flesh out ZenHub EPICs and issues
- [ ] Final QA of all the above before any LAB cluster upgrades are targeted

**Comment by wmhutchison** [comment]
To make creation of these ZenHub tickets more documentation-friendly going forward, will be laying out the dependencies in terms of "waves" similar to how ArgoCD defines implementation order. Once that's been done, then will go to town on creating CLAB's OCP 4.8 tickets for review and polishing up since it'll be the official guinea pig for OCP 4.8.

**Comment by wmhutchison** [comment]
An initial stab at the guinea pig cluster which will be CLAB. Listing in order of "waves" instead of blockers, with blocking items being in previous waves. 

Wave 1
------
   -> OCP4.8 Test oc CLI upgrade in CLAB (standard operation for each upgrade)
      -> Estimate 0.5
   -> OCP4.8 Test F5 CIS upgrade in CLAB  (standard operation for each upgrade if available)
      -> Estimate 0.5
   -> OCP4.8 Test Hard Prune steps in CLAB (standard operation for each upgrade)
      -> Estimate 0.5


Wave 2
------
   -> OCP4.8 Test Upgrade in CLAB (standard operation for each upgrade)
      -> Estimate 2
   -> OCP4.8 Test MachineConfig changes in CLAB (only if required regarding new values)
      -> Estimate 1
   -> OCP4.8 Test OpenShift Logging Operator upgrades to 5.2 (standard operation for each upgrade, assuming new version is available)
      -> Estimate 1

Wave 3
------
   -> OCP4.8 Test CCM branch in CLAB (standard operation for each upgrade, confirm VPA still works)
      -> Estimate 1


Wave 4
------
   -> OCP4.8 Test NetApp Trident upgrade and volume snapshots in CLAB (standard operation for each upgrade, assuming new version is available)
      -> Estimate 1
   -> OCP4.8 Test Nagios CronJobs (standard operation for each upgrade)
      -> Estimate 0.5
   -> OCP4.8 Test vROps DaemonSet (standard operation for each upgrade)
      -> Estimate 1
   -> OCP4.8 Test Pruner CronJobs (standard operation for each upgrade)
      -> Estimate 0.5
   -> OCP4.8 Test ETCD Backup CronJob (standard operation for each upgrade)
      -> Estimate 0.5
   -> OCP4.8 Test Encase Daemonset (standard operation for each upgrade)
      -> Estimate 1
   -> OCP4.8 Verify new Samples images and Templates (standard operation for each upgrade)
      -> Estimate 0.5
   -> OCP4.8 Test ignition/playbooks (standard operation for each upgrade)
      -> Estimate 0.5

Wave 5
------
   -> OCP4.8 Invite testing re: HaProxy 2.2 and HTTP header changes (https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-preparation-haproxy-2.2)
      -> Estimate 1, include for KLAB as well.

   -> OCP4.8 Update upgrade docs and create CHG for other clusters (standard operation for each upgrade) 
      -> Estimate 1

**Comment by wmhutchison** [comment]
https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-monitoring-removed-API-alerts will start prepping us for API calls that need to be fixed before we upgrade to OCP 4.9. May be spammy for Platform Ops folks, but otherwise not impactful.

https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-preparation-haproxy-2.2 may require user testing in LAB clusters before proceeding to PROD upgrade.

The use of VPA was technically tested in previous iterations, OCP 4.8 will just formalize its inclusion into remaining LAB clusters and PROD.

**Comment by wmhutchison** [comment]
The goal before shelving this ticket for the year (going on vacation in a day until Jan 2022) is to get all of the CLAB Zenhub tickets/dependencies/blockers created. It's where all the magic resides, the tickets for the remaining clusters will be  a lot less complex.

**Comment by StevenBarre** [comment]
>OCP4.8 Test F5 CIS upgrade in CLAB

To expand further, CIS is strongly tied to the Kube version, so we need to make sure the version running on the cluster is compatible with the version we are upgrading to. If it's not, we need to upgrade CIS before the OCP upgrade.

>Wave 3

Can we add a step to the CCM stuff to also update https://github.com/bcgov-platform-services/platform-gitops-container/blob/main/Dockerfile#L25 with the new CLI version?

>OCP4.8 Test NetApp Trident upgrade and volume snapshots in CLAB

Volume snapshots were a new feature in OCP 4.7 and the matching Trident upgrade, its not a thing we'll deal with each upgrade cycle.

>OCP4.8 Verify new Samples images and Templates

To expand a bit, we have an exclude list to keep the samples fairly minimal. Each new OCP release includes new Samples so we want to work with someone from the platform services team (Ian currently?) to identify the new images/templates from the new OCP version and determine which should be kept and which need to be added to the exclude list.

I think it's best to create a main epic in ZH, then a sub-epic for each cluster, then all the tickets in each epic for that cluster. The first lab will have many more tickets and the PROD clusters can have just one or two for the upgrade as everything will be covered by the CHG and docs. Don't need a ticket for each sub-step of the full upgrade.

**Comment by wmhutchison** [comment]
Moving to Backlog while I am on vacation. Should be able to jump into ZenHub ticket creation when I'm back in January 2022.

**Comment by wmhutchison** [comment]
Back from Vacation, this ticket can now proceed during the upcoming Sprint.

**Comment by wmhutchison** [comment]
work is ongoing, was originally going to keep this ticket open to keep track of CLAB items of interest, but will instead do so for the documentation ticket earkmarked for this instead.
