### ISSUE TITLE
iStore order for Platform Services OpenShift Servers (True Up Order)

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#1976]
**Describe the issue**
iStore Order for: True up order for changes to 59 servers
Date Submitted: November 12, 2021
iStore Number: listed below

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [x] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![image.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/44665815-71ca-493a-8ebb-78dc41e04784)

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by wmhutchison** [comment]
To derive accurate dating for the Backups, went back through the project to determine the RFC references/tickets and their marked decommission date. Results as follows.

GOLDDR-*, CHG0027720, July 9th 2021
SILVER-APP-22, CHG0024072, decommmission date was March 17th 2021
SILVER-APP-23, CHG0024072, decommmission date was March 17th 2021
SILVER-APP-24, CHG0024072, decommmission date was March 17th 2021
SILVER-APP-25, CHG0024072, decommmission date was March 17th 2021
SILVER-APP-26, CHG0024716, decommmission date was April 9th 2021
SILVER-APP-27, CHG0024716, decommmission date was April 9th 2021
SILVER-APP-28, CHG0024716, decommmission date was April 9th 2021
SILVER-APP-29, CHG0024716, decommmission date was April 9th 2021
SILVER-APP-30, CHG0025478, decommmission date was April 30th 2021
SILVER-APP-31, CHG0026416, decommmission date was May 28th 2021
SILVER-APP-32, CHG0026416, decommmission date was May 28th 2021
SILVER-APP-33, CHG0025478, decommmission date was April 30th 2021
SILVER-APP-34, CHG0025478, decommmission date was April 30th 2021
SILVER-APP-35, CHG0025478, decommmission date was April 30th 2021

**Comment by juhewitt** [comment]
Approved all new storage costs

**Comment by mitovskaol** [comment]
@lukegonis  Can you please check if this ticket can be closed. Thanks!

**Comment by lukegonis** [comment]
Moving to closed as Tyron has confirmed this order is now completed
