### ISSUE TITLE
Investigate F5 NAT pool usage

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#1982]
**Describe the issue**
Back in July a misbehaving app caused a NAT pool port exhaustion. As there is currently only one NAT IP, we're limited to 64k connections outgoing.

**Additional context**
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/a39d2b4e-73a7-448e-9a97-dd23633ebd30)

**Definition of done**
- [x] Discuss with networking team if we can get better stats on NAT usage
- [x] Decide if we should expand the NAT pool to have more IPs
- [x] Create tickets to implement if needed

**Comment by StevenBarre** [comment]
Statistics -> Module Statistics -> Local Traffic

Statistics Type -> SNATs

![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/a5f45a11-2222-472e-8bf6-e149c994d9ab)

Maximum is "since last reboot" of the F5 device.

So currently the Silver F5 has hit a max of about half the total connections allowed.

**Comment by StevenBarre** [comment]
Decided with rest of MCS team that we will proceed and implement. We will expand to 4 IPs per prod cluster and 2 IPs per lab.

Steps will be

-	Find all uses of the NAT IPs in firewall rules and ensure they are using the network object. Make tickets to update any that aren’t
-	Update the network object in the firewalls with the new set of IPs
-	Update LAB F5s to use multiple IPs in NAT pool and test
-	Scheduled prod changes to add NAT IPs
-	Send blast email to community announcing the change and dates
-	Update Silver, then gold, then goldr to have multiple IPs in NAT pool during Sunday morning changes. (or should we do weekday 6am?)

**Comment by juhewitt** [comment]
I would say we need a TL;DR in the communications for Product Owners -> basically we're building outgoing network traffic capacity as more teams come into the platform; we're already at half capacity and will be increasing by xyz... 

I would do the change at the least impact to the service

also, if you think there's any possibility of folks hard coding anything with these IPs... they might not be... but you would know more than me...

**Comment by mitovskaol** [comment]
I would suggest to maybe make the change in the evening at around 7pm on a weeknight, so if something goes wrong we have more time to fix it before teams start coming in in the morning

**Comment by StevenBarre** [comment]
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2034 to track the work goring forward.

I've started reviewing the Firewall rules that exist that will need updates.
