### ISSUE TITLE
ACS - Scale down and uninstall operator in KLAB

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#1988]
Capabilities review of ACS complete in KLAB.  As we get ready for trial connection to CloudGuard, we should remove this component to reduce chance of conflicting services.

- [x] scale down pods
- [x] uninstall operator
- [x] any other clean-up tasks

**Comment by StevenBarre** [comment]
https://docs.openshift.com/acs/3.67/installing/uninstall-acs.html

**Comment by StevenBarre** [comment]
ACS has been uninstalled
