### ISSUE TITLE
Document PS Team's use of GitHub orgs and repos

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2030]
The Platform Services Team has agreed on the following use of the BC Gov's own orgs and repos in GitHub:

`bcgov` public org:
1) Contains **public code repositories that hold open source code and/or public docs**  for all BC Gov teams working on the Platform including the Platform Services Team.

`bcgov-c` private org
2) This org is used as a **temporary (up to 12 months)** location for the BC Gov's team's private repos with closed source code and private docs. All repos are expected to be moved to the `bcgov` public org at the end of the period. The **only** permanent private repos allowed in this org are product team's GitOps repos with ArgoCD manifests.

`bcgov-platform-services` private org
3) This org is used by  **Platform Services Team only**  and contains Platform configuration scripts such CCM GitOps manifests (this org allows for the guaranteed amount of GitHub Actions) as well as for managing the `Maintainer` (aka admin) access to the Openshift Platform clusters. All our public repos are contained in `bcgov` org.

 Ministry-specific private orgs
4) These orgs **must** be linked to the BC Gov's GitHub Enterprise account (user licenses are required for the members of these orgs) and are used as a **permanent location** for teams' private repos with closed-sourced code that cannot be transitioned to a public repo within 12 months. Read the instructions for how to create a private org linked to the corporate GitHub Enterprise account [here](https://developer.gov.bc.ca/Use-of-GitHub-Enterprise-User-Licenses-in-BC-Gov)  

Security Insight feature is available for all orgs linked to the corporate GitHub Enterprise account as well branch protection and code owners for private repos.  Branch protection only allows specific people to push to the protected branch. Code owners feature allows enabling automated reviews, e.g. if a specific user is a code owner of the certain files they are automatically added as PR reviewers and their approval is required before the code can be merged. 

Other uses of GitHub:
1) GitHub app integration e.g. SonarCloud testing, a third-party app needs be enabled for each repo individally. The Platform Service Team's approval is required for all third party app integration in all BC Gov's orgs.

DoD:
- [ ] the Team approved the content above and it is published in DevHub.

**Comment by StevenBarre** [comment]
:shipit:

**Comment by w8896699** [comment]
Looks good to me
