### ISSUE TITLE
Optimize Nagios long-term-metrics-host task

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#2033]
**Describe the issue**
Nagios long-term-metrics-host task is taking 25 minutes on Silver cluster. As we want to run this metric collection more often (i.e every 10 minutes, etc) We need to optimize the way to collect metrics from each hosts in hte cluster.

**Additional context**
https://github.com/bcgov-c/platform-tools/pull/96

**Definition of done**
- [x] Figure out how it can be optimized and run within 10 minutes or less for Silver.   
- [x] Test on KLAB/CLAB
- [x] Create Changes
- [x] Run Changes

**Comment by StevenBarre** [comment]
https://stackoverflow.com/a/53268977/219116

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-tools/pull/97

**Comment by StevenBarre** [comment]
Updated Nagios rolled out
