### ISSUE TITLE
Document UI/UX improvements for the Assessment App

### ISSUE THREAD

**Issue by ShovelHand** [BCDevOps/developer-experience#2043]
Martha says:

- [x]  Add header content explaining what the report is and how it was generated. (High)

- [x] Get rid of summary table, and only have details table.  (yes, do this)

- [x] Have links to tables for people who won't scroll. (not for now.)

- [x] Do accessibility checks on icons for colourblind people. (Colours used come form design standards for BC Gov, requirements met. Double check)

DOD
Note that one item on this ticket was pushed off, so the "1,2,3" below may not make total sense. 
- [x]  1, 2, 3 are implemented in KLab and signed off on by Olena. 
- [x] Top right corner in header, "<environment>-prod Config Check" should say "<environment>-prod OpenShift Config Check"
- [x] Use user friendly name (like, KLab, or Silver) for OpenShift cluster instead of kubernetes-default-svc:443 or whatever comes from API call. 
- [x] In details tables, label the pod., like "pod: nginx-sample"

**Comment by ShovelHand** [comment]
@mitovskaol

**Comment by ShovelHand** [comment]
@mitovskaol What do you think of this, Olena?
The AppAssessment tool conducts a suite of tests on pods operating within the namespace that it is installed on, and provides feedback on configurations considered to be best practice. 
Checks are performed through API calls to OpenShift, and compared to expected values. Documentation on application health checks can be found here <link to https://docs.openshift.com/container-platform/4.9/applications/application-health.html>_

Too much? Too little? I aimed to be concise.

**Comment by mitovskaol** [comment]
The AppAssessment tool assesses configuration of pods within a specific Openshift namespace and identifies the misconfigured or missing settings based on what is considered best practices by RedHat and the Platform Services Team. 
Checks are performed through the calls to Openshift API, and compared to expected values. Documentation on application health checks can be found here <link to https://docs.openshift.com/container-platform/4.9/applications/application-health.html>. If your team is aware of additional checks that can be added to the list, please, ping us in [#devops-operations](https://chat.developer.gov.bc.ca/channel/devops-operations) channel in Rocketchat. Configuring applications pods in acccordance with best practices improves the resiliency, performance and security posture of the application.

**Note: The report produced by the AppAssessment tool provides recommendations only,  it is the responsibility of the product team to review the recommendations and implement as necessary.**  

How about this one?
