### ISSUE TITLE
Assessment App MVP 

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2044]
This Epic includes steps required to roll out the first release of the Assessment app services to the teams in the Silver cluster. 

DoD:
- the service is available for use by teams in Silver

**Comment by ShovelHand** [comment]
I discussed this at length with Cailey, who says that trying to make this available through the catalog as the git README talks about may not be feasible, and documenting steps to get tool working from Dockerhub (if I understood that part) may be better. We should definitely discuss this further as a team as I can't say what the expectation is, or what the technical abilities of the target users may be.

**Comment by StevenBarre** [comment]
Previously we'd created a Template in the `openshift` project that all teams could then access to create the AppAssessment resources. This could be handled by CCM. Downside is it wont update existing deployments when changes to the template are made.

**Comment by ShovelHand** [comment]
I believe this has reached the DoD, and I am waiting for feedback from at least one community member we have put this in the hands in to say it's working before closing the issue.

**Comment by ShovelHand** [comment]
I think this ticket is ready to be closed, but I'll wait until I demo it at the next sprint review meeting.

**Comment by ShovelHand** [comment]
All attached sprint goals are done, and I am closing this epic.
