### ISSUE TITLE
High Level Comparison of Gov.UK and Gov.US

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2047]
**Describe the issue**
We want to see what other sites are doing in terms of structure and messaging. We've heard that re-purposing and leveraging other government sites is ok, so we're going to compare developer.gov.bc.ca to these sites: 
- https://www.cloud.service.gov.uk/
- https://cloud.gov/

**Additional context**
We will look at the page structure for the non-technical documentation. We will also look at their messaging around their products, services, values. This will help us have the discussion with stakeholders around what we want the site to be in the future. The Gov.UK site has been mentioned several times as a point of reference, but we need to know what it would take to have a site like that. Does DevOps want to put in all the effort? What effort is required? What resources are required? Does DevOps want to hire those resources? (For sure a technical writer/editor would be required.)

**Definition of done**
- [x] Spreadsheet of high level comparison

**Comment by emma-csi** [comment]
Spreadsheet saved in BCDevExchange drive: https://docs.google.com/spreadsheets/d/17_Rh3NXHhfLy5zIm7k32EkHxOz9bIPkyLBem_JLQoWU/edit?usp=sharing
