### ISSUE TITLE
Group config check items by type in AppAssessment report

### ISSUE THREAD

**Issue by ShovelHand** [BCDevOps/developer-experience#2055]
CPU and Memory Requests, CPU and Memory limits, Probes, etc. 

DoD
- [ ] Group table items if applicable (resource usage, security, etc) (high)

**Comment by mitovskaol** [comment]
@ShovelHand It looks like a small task but with a great UX value. Can we please include it in the next Sprint.

**Comment by ShovelHand** [comment]
Yup, I'll put this into the next sprint.

**Comment by ShovelHand** [comment]
Reviewed  by Tyler. I merged this into main, and I am closing this ticket.
