### ISSUE TITLE
Aqua - 6.5 Upgrade

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#2059]
## Summary

Upgrade to the latest stable version of Aqua.

## Code

The code already exists as a PR in CCM

## Known Issues

Enforcers are failing and we are waiting on support from aqua.

**Comment by ShellyXueHan** [comment]
## Update:
Aqua support suggested to try the new patch version, which results in new error message. Currently waiting for updates from support.

**Comment by ShellyXueHan** [comment]
### Update:
tested the new 6.5 image in clab, all good. Waiting for ccm push to prod

**Comment by ShellyXueHan** [comment]
upgrade pushed to silver now. Aqua had some issues upgrade itself, had to manually restart component altogether to get it through.
