### ISSUE TITLE
Aqua - setup in gold cluster

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2062]
**Describe the issue**
Aqua isn't working yet in gold, scanners and jobs need to be added. I would need to look into the ccm setup to see why things aren't working like silver yet.

**Definition of done**
- [ ] enable aqua in gold from pipeline
- [ ] work on post deployment job for configuration setup, ie. SSO
- [ ] setup aqua properly in gold and test

**Comment by ShellyXueHan** [comment]
Not gonna work on this till we know if we are migrating to ACS

**Comment by StevenBarre** [comment]
We are migrating to ACS -> https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2071#issuecomment-1039697333
