### ISSUE TITLE
iStore order - cert for docs.developer.gov.bc.ca

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2068]
**Describe the issue**
iStore Order for: iStore order - cert for docs.developer.gov.bc.ca
Date Submitted: January 5, 2022
iStore Number: 1090343
Lead time (business days after EA Approves): 10 

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [x] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by juhewitt** [comment]
I definitely approved this!

**Comment by lukegonis** [comment]
completed
