### ISSUE TITLE
Search Engine Optimization for Content - External Search 

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2077]
**Describe the issue**
We want to make sure our content meets external and internal search engine optimization criteria. This issue will focus on off-site search, or external search, and investigate keywords that can be used in content. It's not so much that we are competing with other services but that we want to make sure that we are including user-centred terms in the content we write so that when they search for these terms on the internet, they find us.

**Additional context**
We'll identify these keywords and create a strategy. This won't be a hugely detailed strategy but enough to keep the writers on track. It's not going to be hugely detailed because we aren't in a highly competitive market and we aren't competing with other services (we have specific, and somewhat captive, audience). 

Emma will do this research and strategy and Theresa will review her work.

**Definition of done**
- [ ] SEO keywords identified
- [ ] SEO strategy created

**Comment by theresawuzhere** [comment]
@emma-csi Resources to review:
This source is the best: https://moz.com/beginners-guide-to-seo
More of the same: https://blog.kissmetrics.com/simple-guide-to-seo/
How SEO and IA can work together: http://www.uxmatters.com/mt/archives/2011/12/putting-seo-in-its-place-an-information-architecture-strategy.php
Yours truly: https://www.keypointe.com/use-taxonomy-and-information-architecture-to-improve-seo/
Metadata and Google: http://www.seobythesea.com/2014/02/google-uses-taxonomic-classifications-better-understand-meanings-words/
This might be useful: http://blog.hubspot.com/marketing/data-driven-strategies-writing-titles-headlines
Please list all the items we can do to optimize SEO (including crawling, keywords, content, markup/metadata)

**Comment by fabform** [comment]
Handy alternative list of [alternative search engines](https://fabform.io/a/alternative-search-engines)
