### ISSUE TITLE
NetApp OS Upgrade - GOLD cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2084]
**Describe the issue**
This issue will track the efforts towards planning and executing the required OS dates to NetApp hardware for our GOLD cluster.

**Additional context**
CHG0030691 is currently scheduled/approved for execution on January 16th 2022 between 8am and 12pm PST.

**Definition of done**
- [x] RFC created and approved.
- [x] Comms created/approved/posted in RC.
- [x] Upgrade successfully applied and tested.

**Comment by StevenBarre** [comment]
Comms PR https://github.com/BCDevOps/platform-services-status-page-notifications/pull/157

**Comment by StevenBarre** [comment]
Upgrade completed
