### ISSUE TITLE
NetApp OS Upgrade - SILVER cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2085]
**Describe the issue**
This issue will track the efforts towards planning and executing the required OS dates to NetApp hardware for our SILVER cluster.

**Additional context**
CHG0030692 is currently scheduled/approved for execution on January 23rd 2022 between 8am and 12pm PST.

**Definition of done**
- [x] RFC created and approved.
- [x] Comms created/approved/posted in RC.
- [x] Upgrade successfully applied and tested.

**Comment by StevenBarre** [comment]
Completed
