### ISSUE TITLE
Draft of Content Strategy

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2089]
**Describe the issue**
Create a draft of the content strategy that describes: 
- High level overview of challenge and opportunity
- Content strategy itself
- Guidelines and implications of the strategy
- Steps to fulfill the strategy
- Specifics on steps (site map, metadata and taxonomy, content types, content governance, content writing, testing)
- Highlights of findings from the research

**Additional context**
None

**Definition of done**
A draft of the strategy, available for review

**Comment by theresawuzhere** [comment]
https://docs.google.com/document/d/16-KlEuENSTkKY3sYpXMlAJ0wZCLotYancjg19uUzDMM/edit?usp=sharing

**Comment by juhewitt** [comment]
Looks good @theresawuzhere we'll be looking for recommendations where to place the technical documentation, whether outside of WP in a different tool that federates/links from WP much like the UK IA.

**Comment by theresawuzhere** [comment]
@juhewitt in my experience as a technical writer, and thinking about the purpose of WordPress and amount of technical documentation you could or will have, I would say using WordPress to maintain your tech docs would be sub-optimal. What does the UK IA use?

**Comment by juhewitt** [comment]
we have a ticket here that Jason worked upon before, and it was determined we should attempt Gatsby for our technical documentation: https://www.gatsbyjs.com/use-cases/technical-documentation. The UK built their own solution that pulls from GitHub, however it's single repository instance, which doesn't meet our need of multiple instances.  The devhub aggregates GitHub.com repositories (multiple), so I'm thinking we're going to want to create a ticket for our dev team to talk about what this will look like @mitovskaol for next sprint planning.
