### ISSUE TITLE
Sysdig - removing a duplicate Sysdig Team custom resource will delete the whole sysdig team

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2092]
**Describe the issue**
Sysdig team operator creates teams by the namespace/project set. if there are another CR created in the same namespace and then removed, operator will delete the sysdig team directly.

To fix, we should either add a check in operator before deleting, or prevent multiple CRs in one namespace.

**Definition of done**
- [ ] decide on the fix
- [ ] implement it

**Comment by IanKWatts** [comment]
This has been addressed in issue #4750
