### ISSUE TITLE
Platform Developer Services DNS Suffix

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#21]
It would be nice to have a non-pathfinder DNS suffix that we can use for platform developer services.  (since pathfinder.gov.bc.ca may not be the DNS we want?)
provides:
 - Consistent branding for Developer Services
 - Migration/Naming not tied to a single cluster
 - Clearer ownership of sub-domain / service names (currently it's a first-come-first-serve for names in pathfinder or dive into name conflict resolution with other development teams)

Need:
- a DNS name (iStore)
-wildcard certificate for the domain that we can share between applications.

**Comment by lukegonis** [comment]
Decision has been made regarding DNS suffix.

**Comment by jefkel** [comment]
Update: 
DNS Suffix to be used for platform services is:

**developer.gov.bc.ca**
