### ISSUE TITLE
OCP 4.8 Verify new Samples images and Templates

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2107]
**Describe the issue**
The Samples Operator manages the imagestreams and templates in the `openshift` namespace. With each new version of OCP some samples are added and removed. There is a playbook that sets exclusions to trim down which samples are available on the cluster. Determine which images/templates are new and work with Platform Services to understand which to keep or exclude. Update the playbook to exclude any new images and remove any exclusions that are no longer needed.

**Additional context**
https://docs.openshift.com/container-platform/4.8/release_notes/ocp-4-8-release-notes.html#ocp-4-8-images-removed-from-samples-imagestreams

**Definition of done**
- [ ] Confirm with stakeholders which new samples to keep if any.
- [ ] PR to update the samples playbook.

**Comment by wmhutchison** [comment]
New sample images/templates now available in OCP 4.8.

```
$ oc -n openshift get is,template -o=custom-columns=KIND:.kind,NAME:.metadata.name,AGE:.metadata.creationTimestamp | grep 2022-01
ImageStream   driver-toolkit                               2022-01-14T21:00:41Z
Template      fuse78-console                               2022-01-14T21:03:55Z
Template      rhdm710-authoring                            2022-01-14T21:03:56Z
Template      rhdm710-authoring-ha                         2022-01-14T21:03:55Z
Template      rhdm710-kieserver                            2022-01-14T21:03:56Z
Template      rhdm710-prod-immutable-kieserver             2022-01-14T21:03:56Z
Template      rhdm710-prod-immutable-kieserver-amq         2022-01-14T21:03:56Z
Template      rhdm710-trial-ephemeral                      2022-01-14T21:03:56Z
Template      rhpam710-authoring                           2022-01-14T21:03:56Z
Template      rhpam710-authoring-ha                        2022-01-14T21:03:55Z
Template      rhpam710-kieserver-externaldb                2022-01-14T21:03:55Z
Template      rhpam710-kieserver-mysql                     2022-01-14T21:03:56Z
Template      rhpam710-kieserver-postgresql                2022-01-14T21:03:55Z
Template      rhpam710-managed                             2022-01-14T21:03:56Z
Template      rhpam710-prod                                2022-01-14T21:03:55Z
Template      rhpam710-prod-immutable-kieserver            2022-01-14T21:03:55Z
Template      rhpam710-prod-immutable-kieserver-amq        2022-01-14T21:03:55Z
Template      rhpam710-prod-immutable-monitor              2022-01-14T21:03:56Z
Template      rhpam710-trial-ephemeral                     2022-01-14T21:03:56Z
Template      s2i-fuse78-spring-boot-2-camel               2022-01-14T21:03:56Z
Template      s2i-fuse78-spring-boot-2-camel-rest-3scale   2022-01-14T21:03:55Z
Template      s2i-fuse78-spring-boot-2-camel-xml           2022-01-14T21:03:56Z
```

**Comment by StevenBarre** [comment]
All those templates look like new versions of ones we've already excluded, so probably safe to just add them to the list. Unsure about the new imagestream though.

**Comment by wmhutchison** [comment]
@StevenBarre I agree - the new is appears to be something we'd use versus the end users. https://access.redhat.com/documentation/si-lk/openshift_container_platform/4.9/html/specialized_hardware_and_driver_enablement/driver-toolkit

**Comment by wmhutchison** [comment]
Add the following new templates to the YAML responsible for pulling these new Templates:

```
fuse78-console
rhdm710-authoring
rhdm710-authoring-ha
rhdm710-kieserver
rhdm710-prod-immutable-kieserver
rhdm710-prod-immutable-kieserver-amq
rhdm710-trial-ephemeral
rhpam710-authoring
rhpam710-authoring-ha
rhpam710-kieserver-externaldb
rhpam710-kieserver-mysql
rhpam710-kieserver-postgresql
rhpam710-managed
rhpam710-prod
rhpam710-prod-immutable-kieserver
rhpam710-prod-immutable-kieserver-amq
rhpam710-prod-immutable-monitor
rhpam710-trial-ephemeral
s2i-fuse78-spring-boot-2-camel
s2i-fuse78-spring-boot-2-camel-rest-3scale
s2i-fuse78-spring-boot-2-camel-xml
```

**Comment by wmhutchison** [comment]
The new imagestream may also warrant yanking since it's not something we'd want the general populace to partake of. Can run it by Matt Robson during the next TAM call.

**Comment by StevenBarre** [comment]
It may not even be managed by the Samples Operator, and thus not able to be excluded. Like the must-gather image or CLI image.

**Comment by wmhutchison** [comment]
Stuck with just cleaning out the new Templates. PR created: https://github.com/bcgov-c/platform-ops/pull/403

Playbook execution on CLAB was successful, can close off this ticket.
