### ISSUE TITLE
SecOps & DevSecOps culture engagement

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2115]
Various personas to think about: MISOs, developers, POs.  
This is research based, we’re thinking an anonymous engagement to collect information on questions like:
- how did you find out, 
- what channels, 
- who actually did something, 
- how quickly, 
- what people think/feel when they hear about this, 
- why some take it seriously, 
- why some don’t, 
- what stops you from actioning? 

We can leverage log4j vulnerability and patching as an example, how this is progressing for LoBs that were exposed, what actions they took.  

We have all of these tools that identify vulnerability’s and fixes, we have collective communication channels to action.  In some cases we know people action almost immediately, in some cases folks just don’t bother with various excuses. This is to learn together what’s going on out there culturally, and how we can combine efforts to get a litmus test for what’s up.

**Comment by lukegonis** [comment]
The service design work for this task has been complete and presentation was delivered to the platform services team. The action items that came out of this service design research will be scoped out and tracked in separate tickets.
