### ISSUE TITLE
Delete jag-csb-jes-family-protection-order project set in Silver

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2121]
This project set was created as a temporary workaround for the OCP 3 to OCP 4 migration bypassing the Project Registry. The app has since been migrated into the Registry-managed namespaces and the old namespaces have been cleaned up and ready to be deleted.

DoD:
- [x] delete the project set jag-csb-jes-family-protection-order in the Silver cluster.

**Comment by StevenBarre** [comment]
Projects deleted
