### ISSUE TITLE
Install NIFI operator in CLAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2122]
ServiceBC team would like to evaluate the NIFI operator in the CLAB cluster.

DoD:
- [ ] Install NIFI operator in CLAB
- [ ] Enable CRD in the `ae3cec` project set owned by ServiceBC Team

**Comment by mitovskaol** [comment]
@gil0109 ^^^ This work is planned for the next Sprint

**Comment by StevenBarre** [comment]
Taking a swing at this, learning more about helm, dealing with non-ocp issues

**Comment by gil0109** [comment]
Hi Team.  We can close this as I found what I believe is a redhat member building Nifi for another project.  He has a solution that should work for me that doesn't need an operator!!! Woot Woot.  Thanks to @guimou and his work on https://github.com/opendatahub-io/odh-manifests that uses Nifi ;)

**Comment by gil0109** [comment]
@StevenBarre  FYI ^^^

**Comment by guimou** [comment]
Lol, thanks for the vote of confidence!
At this moment the manifest is not merged into the Open Data Hub repo. But the code is there: https://github.com/guimou/odh-manifests/tree/nifi/nifi
And yes, I'm a data engineering architect at Red Hat, in the OpenShift Data Science group. If I may be of help regarding any OpenShift based data science platform problem or idea, don't hesitate to ping me.

**Comment by StevenBarre** [comment]
Oh good @gil0109 . It was looking to be quite a pain to install the operator in OCP with all its dependancies.
