### ISSUE TITLE
OCP 101 - add in security content

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2124]
**Describe the issue**
Certain security concepts are not included in the training right now.
Need to add slides to include details on the following:
- Layered defense of the platform and projects
- KNPs
- Vault
- Vuln scanning (pipeline focus - SAST, DAST; image focus - Aqua/XRay)
- SIEM for extended duration logs
- TLS certs - dedicated required for prod
- Security Assessments
- Engaging w/ Ministry security teams

**Definition of done**
- [x] Content created
- [ ] Publish for use

**Comment by NickCorcoran** [comment]
I think this was completed a long time ago.  Can likely close.
