### ISSUE TITLE
OCP 101 - revisit what should be kept vs done in alignment meetings and for business/project management group

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2125]
**Describe the issue**
We are running out of time during all ocp101 session recently as there are more and more important things to mention! So we'd like to revisit the slides, and figure out what would be the thigns that we can move to alignment meeting instead, since these 2 activities couple together as onboarding.

Also there is the idea of maybe splitting out the lab content into tech-focused vs general-process-focused topics.

And Nick offered to add in some security contents in 101 as well!

**Definition of done**
- [x] discuss as a team what are the things we can move around from 101 slides from/to alignment meeting. Discussion results are captured in [this Mural](https://app.mural.co/t/platformservices5977/m/platformservices5977/1646247256176/b97aeabd4db874cd7c427d8e9ded210ab8292599?sender=u1d0b96ff3161eda8f0f38743).
- [ ] update slides
- [x] decide with the team if we are moving the miro board to mural? [Mural OCP101 Board Created](https://app.mural.co/invitation/mural/platformservices5977/1646945371597?sender=uf0df5317d8dbea9ee48c7230&key=53ce5618-7a78-4548-b12c-c3495babe255)

**Comment by mitovskaol** [comment]
@ShellyXueHan Can you please add more conttext to this ticket included DoD because it is very hard for me to understand what this ticket is for. Thanks!

**Comment by mitovskaol** [comment]
@mtspn Can you please update the #3 DoD above with the link to the new OCP 101 Mural.

**Comment by mtspn** [comment]
I've added the link to OCP 101 Mural version above.
