### ISSUE TITLE
CheckPoint CloudGuard - KLAB - debug logging for Image scan failures

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2126]
**Set these to change logging to debug**
kubectl -n $checkpoint set env daemonset/${asset-mgmt}-imagescan-daemon LOG_LEVEL=debug
kubectl -n $checkpoint set env deployment/${asset-mgmt}-imagescan-engine LOG_LEVEL=debug

**Change logging level back after 24 hrs**
kubectl -n $checkpoint set env daemonset/${asset-mgmt}-imagescan-daemon LOG_LEVEL=info
kubectl -n $checkpoint set env deployment/${asset-mgmt}-imagescan-engine LOG_LEVEL=info

**Run to collect logs**
./cloudguard-container-info-collect.sh –release ${asset-mgmt} –namespace ${checkpoint} -o cloudguard.tgz

Provide results to @NickCorcoran

**Comment by NickCorcoran** [comment]
imagescan-daemon not found - question submitted to CheckPoint prior to collection

**Comment by StevenBarre** [comment]
Debug enabled Tues Jan 18th at 9am

**Comment by StevenBarre** [comment]
Debug data passed to Nick
