### ISSUE TITLE
Add iSCSI Data LIFs to NetApps

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2135]
**Describe the issue**
According to [NetApp](https://docs.netapp.com/us-en/ontap-sm-classic/iscsi-config-rhel/task_configuring_iscsi_fc_creating_lun_on_existing_svm.html) we should have 2 LIFs per node. Currently we only have one.

**Definition of done**
Configure additional data LIFs on all production NetApps

**Comment by StevenBarre** [comment]
Tested in LABs. Storage Team just needs to run two commands in the netapp CLI to add the new iscsi LIFs. Trident will pick up the new lifs after nodes have been rebooted. Will coordinate with Storage Team to have them do the commands as part of the next OCP upgrade pre-step CHG.

**Comment by wmhutchison** [comment]
Nested this ticket under the top-level OCP 4.11 upgrade EPIC since we intend to align completion of this work under that particular maintenance push.

**Comment by wmhutchison** [comment]
Closing off, all work for this is now completed.
