### ISSUE TITLE
Revisit F5 CIS v2.7 upgrade in CLAB before OCP 4.9

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2139]
**Describe the issue**
As part of the devops process, we applied a "best effort" approach to upgrading F5 CIS to the latest version available (v2.7.0) when preparing the Openshift upgrade to 4.8. We ran into segfault errors which appear to be not unique to us per other stakeholders on F5 Slack bringing up the issue for the same problem, and an internal ticket being created.

The intent is for this issue to remind us that we need to circle back and re-attempt this upgrade in CLAB, since we won't be able to upgrade to Openshift 4.9 until we have an upgrade that works of version v2.7 or later (currently at v2.6.1) due to needing Kubernetes 1.22 support.

**Additional context**
Original ticket for attempting upgrade in CLAB for OCP 4.8: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2095
**Definition of done**
- [x] Revisit with vendor on this issue and create our own ticket/case if needed.
- [x] Re-attempt another F5 CIS upgrade in CLAB once a fix is available.
- [x] Backport any required changes for the fix to work spent on OCP 4.9 upgrade.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-ops/pull/409
