### ISSUE TITLE
Install Advanced Cluster Security in KLAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2144]
Install Advanced Cluster Security (StackRox ) in KLAB to allow @NickCorcoran  continue evaluating its capabilitiers and the potential to replace AQUA for security scanning on the Platform.

**Comment by NickCorcoran** [comment]
I know we did this before and removed, but hoping re-setup isn't too difficult.  RH support have said they can help us when we do it.  Hoping we can scale down CloudGuard (rather than completely removing) for period we need to re-verify ACS capabilities.

**Comment by StevenBarre** [comment]
https://github.com/redhat-cop/gitops-catalog/tree/main/advanced-cluster-security-operator
https://github.com/gnunn-gitops/cluster-config/tree/main/components/apps/acs-operator/overlays/oauth

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/376

**Comment by StevenBarre** [comment]
CCM worked. ACS installed in both LABs.
