### ISSUE TITLE
Update monitoring page in DevHub

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2147]
DoD:

- [x] [the monitoring page](https://developer.gov.bc.ca/Openshift-4-Platform-Services-Reliability-Dashboard-with-Uptime-Robot) is updated to reflect our migration to uptime.com

**Comment by ShellyXueHan** [comment]
it's at https://developer.gov.bc.ca/OpenShift-4-Platform-Services-Reliability-Dashboard now!
