### ISSUE TITLE
Weekly CCM PROD Push for January 25-27th 2022

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#2148]
**Describe the issue**
This ticket will track efforts spent toward creating the next CCM release and promoting it against the three production Openshift 4 clusters. 

**Definition of done**
- [x] Create suitable GitHub Release before EOD Friday January 21st.
- [x] Create suitable Standard Change RFCs and notify stakeholders.
- [x] Execute RFC for SILVER cluster
- [x] Execute RFC for GOLD cluster
- [x] Execute RFC for GOLDDR cluster

**Comment by wmhutchison** [comment]
Release created, RFCs scheduled for implementation and PR created/approved for incrementing release version for CCM on PROD cluisters. Need only wait now for RFC implementation for each cluster.
