### ISSUE TITLE
Repo-mapper frontend

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#215]
Brief components:
- caddy serving with http basic auth
- webpage that displays:
  - link of generated CSV file
  - message when file not ready

**Comment by ShellyXueHan** [comment]
Updates:
- Updated bc and dc to use combined parameters 

Notice!!
- need to be able to clear Caddy cache otherwise it won't trigger service wakeup from idle

**Comment by jleach** [comment]
@jas29 Are you able to add and update comment?
