### ISSUE TITLE
Do task testing with users

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2155]
**Describe the issue**
We need to test the product owner site map with product owner users, via task testing

**Additional context**
This task testing will happen with Treejack in Optimal Workshop

**Definition of done**
- [ ] Create task testing plan
- [ ] Recruit participants
- [ ] Set up, launch, and monitor task testing

**Comment by theresawuzhere** [comment]
Here are the results from round one. We will do another round: https://docs.google.com/document/d/1KGK0r_oKV4g9_0LZao7bdRQvtW5P3uzqOJSQuJ9mPsw/edit?usp=sharing
