### ISSUE TITLE
Create content models

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2160]
**Describe the issue**
Need to layout the metadata and on-page structure for the website, so we can build the templates in a predictable way

**Additional context**
Nothing at the moment.

**Definition of done**
- [ ] spreadsheet draft created

**Comment by theresawuzhere** [comment]
@lukegonis for the definition of done, I'm pretty sure we won't do the review and finalizing the spreadsheet. I guess you want to break this across sprints?
