### ISSUE TITLE
To create CI/CD pipeline with Owasp Zap tool in KLAB

### ISSUE THREAD

**Issue by bruce-wh-li** [BCDevOps/developer-experience#2194]
- [x] Create Rocket Chat App
- [x] Create the CI/CD Pipeline using template
- [x] Config OWASP in CI/CD Pipeline
- [x] Make change to Rocket Chat App
- [x] Check Scan Result

**Comment by NickCorcoran** [comment]
Completed.  Built out both GitHub Actions and Tekton pipelines using the templates provided by Arctiq.
