### ISSUE TITLE
Artifactory workflow for Maven repositories

### ISSUE THREAD

**Issue by bolyachevets** [BCDevOps/developer-experience#2204]
**Describe the issue**
JFrog has the following instructions for setting up Maven artifactory repository: https://www.jfrog.com/confluence/display/JFROG/Maven+Repository#MavenRepository-ResolvingArtifactsThroughArtifactory

When using "Set me up" button, no repositories are showing up under Maven repository type, which precludes developers from using features detailed in the JFrog url above. 

settings.xml needs to be created manually instead.

**Additional context**

<img width="944" alt="Screen Shot 2022-01-28 at 10 00 26 AM" src="https://user-images.githubusercontent.com/22973013/151598392-00145787-b29f-4474-97fe-e4be163e72d3.png">

**Definition of done**
Should be able to see Maven repos in "Set me up" UI and follow the steps outline in JFrog guide.

**Comment by caggles** [comment]
This issue has been fixed! A meeting with JFrog support clarified the problem and provided us with instructions on configuring our Maven repos to work as expected.
