### ISSUE TITLE
Developer a quota reduction query for all tools namespaces in Silver 

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2205]
As per the details documented in [this ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1991), we want to reduce the CPU and RAM quotas in all tools namespaces in Silver. The only exception would be these 3 namespaces:

```
75e61b-tools (Education Common)
8878b4-tools (PEN)
77c02f-tools (GRAD)
0bd5ad-tools (Health Gateway)
```
EDUC team does not have Jenkins in these namespaces but instead uses them as staging environment for their app code. They will be migrating the code from `tools` into `test` over the next 1-2 months and will notify PS Team when it is done. 

Health Gateway uses Azure build agents for deployment and has tested that multiple agent instances cannot run simultaneously under the reduced quota. 

DoD:
- [ ] Develop a query that can run against all tools namespaces for the projects listed in the Project Registry that are hosted in the Silver cluster (with the exception of the 3 abovementions namespaces) and adjust the CPU and RAM quota for these projects to:
```
 requests.cpu: 2 cores
 limits.cpu: 4 cores
```

- [ ] Run the query in Silver on Feb 8, 2022 at 9am (the ticket can be closed once the query is run).

**Comment by w8896699** [comment]
quota_memory_size = 'memory-request-8-limit-16',
    quota_cpu_size = 'cpu-request-2-limit-4'

**Comment by w8896699** [comment]
@mitovskaol  75e61b|8878b4|77c02f|0bd5ad|8ad0ea has been excluded from this downgrade.
75e61b: EDUC Services
8878b4: Personal Education Number
77c02f: Graduation Records and Achievement Data
0bd5ad: Health Gateway
8ad0ea: OrgBook BC

**Comment by w8896699** [comment]
https://github.com/bcgov-platform-services/platform-gitops-kamloops-silver-namespaces/pull/350/files
