### ISSUE TITLE
Update Image Registry Usage tool email CC address list

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2208]
**Describe the issue**
Olena and Justin would prefer to have the emails CC the shared team mailbox than them personally.

**Additional context**
Use the same address as the From address in the CC

**Definition of done**
- [x] PR to update code to remove Justin/Olena as CC recipients and add the shared mailboc
- [x] Rebuild image on production clusters

**Comment by StevenBarre** [comment]
Tim can you please do this before next Tue, when the cron will run next.

**Comment by tbaker1313** [comment]
Can do!

**Comment by tbaker1313** [comment]
Updated the email addresses.

**Comment by tbaker1313** [comment]
Adjusted the email parameters. Next step will be to adjust how it deals with the 3rd warning.
