### ISSUE TITLE
Account/program ownership transfer

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#221]
As Todd will be moving out of Gov, let's start transferring some of the ownership of shared accounts and resources to Justin.

### Accounts that need to be transferred:
- [x] Apple developer program ownership (Justin will need an Apple account first)
- [x] pathfinder + bcdevexchange BC Gov email
- [x] Google Play Android Developer program

### I'll update the following reference once done:
- [x] bcdevexchange gmail
- [x] GitHub billing email

### off boarding Todd's github account related access

Anything else you can think of @caggles  ?

**Comment by jleach** [comment]
@ShellyXueHan Are you able to change the bullet points to `- [ ]` so they can be checked off as you go to show outstanding work. Thanks.
