### ISSUE TITLE
Update Image Registry Usage tool email bodies

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2210]
**Describe the issue**

**Additional context**
> The projects that do not reduce their image storage footprint after 3 weekly reminders, will get their CPU and RAM resource quotas downgraded to the smallest quota size in their dev and test namespaces. 

also include:
> Add code to the nagger tool that if a team has been notified 3 times and they are still above the limit, there will be a different email going to them saying that their dev and test namespaces will be downgraded in 7 days if the image size doesn’t get reduced

**Definition of done**
- [x] PR with changes to text and html email templates
- [ ] PR to implement the change in email after 3 notifications
- [ ] PR approved by @mitovskaol 
- [ ] Image rebuilt on prod clusters

**Comment by StevenBarre** [comment]
The scope here has changed somewhat. We'll need to add a way to track state to the code and will need a bunch more testing. Will also need to work with the Project Registry team on an API we can call with a token to trigger quota change requests. Changing the estimate to a 5 and moving to backlog.

**Comment by tbaker1313** [comment]
Have adjusted the email addresses. Next step is to investigate what needs to happen to send a different message after `3 strikes`.

**Comment by StevenBarre** [comment]
This is such a rare occurrence that its not worth automating.
