### ISSUE TITLE
OCP 4.8 Upgrade NetApp Trident in KLAB

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2214]
**Describe the issue**
Upgrade Trident based on testing in CLAB.

**Additional context**
For all of the involved playbooks, checkout and use the ocp48-upgrade branch to run them from. These branches will be merged into main if no further changes are required.
https://github.com/NetApp/trident/releases

**Definition of done**
- [x] Trident upgraded

**Comment by tbaker1313** [comment]
Completed successfully.
