### ISSUE TITLE
Platform Operations on-call and Uptime.com

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2218]
**Describe the issue**
Platform Operations on-call staff need to be notified when they receive an email from uptime.com. While this technically may be considered as over-lap of monitoring depending on the situation, it also serves as a good litmus test of availability of services outside of the BCGov/Advsol network space.

**Additional context**

**Definition of done**
- [x] Perform email tests to derive formatting of emails.
- [x] Create rules for on-call monitoring system to properly react to on-call level events.

**Comment by tmorik** [comment]
PR for a new conditions for a uptime.com alert: https://github.com/bcgov-c/advsol-docs/pull/190

**Comment by tmorik** [comment]
To monitor uptime.com alerts, Specifications are below;
1. Since we have up/down monitor from Nagios XI, we just need notifications for `Artifact` and `Vault` checks from uptime.com.
2. Set up `Hosting Services Managed Container On Call <mcsoncall@dxcas.com>` address for uptime.com checks

**Comment by tmorik** [comment]
Test have been done using buzzkill and a new buzzkill filter: 

https://github.com/bcgov-c/advsol-docs/blob/master/scripts/buzzkill/buzzkillRulesBkup.json
