### ISSUE TITLE
OCP 4.8 Upgrade Openshift in SILVER

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2224]
**Describe the issue**
Run the OCP 4.8 upgrade in SILVER.

**BLOCKED BY**
- [x] Aqua agent pods on upgraded worker nodes causes unacceptable levels of CPU/memory consumption for kubelet. Unless a more refined solution is found, we have permission to remove the involved Aqua pods to allow upgrades to complete.
- [x] User patroni clusters need to be upgraded and other remediation (PDB created) to ensure maximum stability when upgrades resume. Some solutions are now available, and a tentative resume date/time of Feb 23rd at 9am is penciled in.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] Upgrade `oc` CLI on util server
- [x] Upgrade F5 CIS to latest bugfix
- [x] SILVER upgraded to OCP 4.8
- [x] MachineConfig changes applied
- [x] CCM applied
- [x] EnCase updated
- [x] ETCD Backup updated
- [x] Nagios updated
- [x] Pruner updated
- [x] vROps updated
- [x] Logging updated
- [x] Sample Operator updated
- [x] Dell firmware applied
- [x] HPE Firmware applied

**Checklist for Firmware updates**
- [x] Gen10 - node/mcs-silver-app-01.dmz
- [x] Gen10 - node/mcs-silver-app-02.dmz
- [x] Gen10 - node/mcs-silver-app-03.dmz
- [x] Gen10 - node/mcs-silver-app-04.dmz
- [x] Gen10 - node/mcs-silver-app-05.dmz
- [x] Gen10 - node/mcs-silver-app-06.dmz
- [x] Gen10 - node/mcs-silver-app-07.dmz
- [x] Gen10 - node/mcs-silver-app-08.dmz
- [x] Gen10 - node/mcs-silver-app-09.dmz
- [x] Gen10 - node/mcs-silver-app-10.dmz
- [x] Gen10 - node/mcs-silver-app-11.dmz
- [x] Gen10 - node/mcs-silver-app-12.dmz
- [x] Gen10 - node/mcs-silver-app-13.dmz
- [x] Gen10 - node/mcs-silver-app-14.dmz
- [x] Gen10 - node/mcs-silver-app-15.dmz
- [x] Gen10 - node/mcs-silver-app-16.dmz
- [x] Gen10 - node/mcs-silver-app-17.dmz
- [x] Gen10 - node/mcs-silver-app-18.dmz
- [x] Gen10 - node/mcs-silver-app-19.dmz
- [x] Gen10 - node/mcs-silver-app-20.dmz
- [x] Gen10 - node/mcs-silver-app-21.dmz
- [x] Gen9  - node/mcs-silver-app-22.dmz
- [x] Gen9  - node/mcs-silver-app-23.dmz
- [x] Gen9  - node/mcs-silver-app-24.dmz
- [x] Gen9  - node/mcs-silver-app-25.dmz
- [x] Gen9  - node/mcs-silver-app-26.dmz
- [x] Gen9  - node/mcs-silver-app-27.dmz
- [x] Gen9  - node/mcs-silver-app-28.dmz
- [x] Gen9  - node/mcs-silver-app-29.dmz
- [x] Gen9  - node/mcs-silver-app-30.dmz
- [x] Gen9  - node/mcs-silver-app-31.dmz
- [x] Gen9  - node/mcs-silver-app-32.dmz
- [x] Gen9  - node/mcs-silver-app-33.dmz
- [x] Gen9  - node/mcs-silver-app-34.dmz
- [x] Gen9  - node/mcs-silver-app-35.dmz
- [x] Dell  - node/mcs-silver-app-36.dmz
- [x] Dell  - node/mcs-silver-app-37.dmz
- [x] Dell  - node/mcs-silver-app-38.dmz
- [x] Dell  - node/mcs-silver-app-39.dmz
- [x] Dell  - node/mcs-silver-app-40.dmz
- [x] Dell  - node/mcs-silver-app-41.dmz
- [x] Dell  - node/mcs-silver-app-42.dmz
- [x] Dell  - node/mcs-silver-app-43.dmz
- [x] Dell  - node/mcs-silver-app-44.dmz
- [x] Gen10 - node/mcs-silver-infra-01.dmz
- [x] Gen10 - node/mcs-silver-infra-02.dmz
- [x] Gen10 - node/mcs-silver-infra-03.dmz
- [x] Gen10 - node/mcs-silver-master-01.dmz
- [x] Gen10 - node/mcs-silver-master-02.dmz
- [x] Gen10 - node/mcs-silver-master-03.dmz

**Comment by wmhutchison** [comment]
Reducing estimate since while the CHG for this work has gone on longer than normal, we are not continuously working on this issue.

**Comment by wmhutchison** [comment]
Technically blocked, so moving it there.

**Comment by wmhutchison** [comment]
Removing this from Blocked since all stakeholders involved with the go/no-go decision have stated that the current RFC for March 7th can indeed resume.

**Comment by tbaker1313** [comment]
A few issues with app-31 and app-32 - still in progress.

**Comment by tbaker1313** [comment]
mcs-silver-app-32.dmz is delayed due to a hardware issue.

**Comment by wmhutchison** [comment]
All issues mentioned previously are now resolved. 100% done with SILVER OCP/firmware - closing this ticket.
