### ISSUE TITLE
Set up "cluster reader" access in Vault

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#2228]
Platform Admins (and also Nick?) should probably have a broad "cluster-wide" reader privilege in Vault. We will need to set that up using Terraform.

**Comment by j-pye** [comment]
@NickCorcoran Should any of the team actually have the ability to read the secrets of all tenants?  Or should reading secrets for all tenants be limited to the security team (i've been out of the loop long enough now that I can't remember the gov name for said team) or some subset of people? I'm just thinking about blast radius. And that the PS team being able to say that they can't read any teams secrets might be a positive?

**Comment by NickCorcoran** [comment]
Yes, we shouldn't be able to see individual product team secrets.  While it might be nice and helpful sometimes, overall it is better for us not to.
