### ISSUE TITLE
Set up team namespace in Vault

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#2230]
The platform team should have a namespace in our enterrprise Vault insttance for storing and sharing secrets like vendor account passwords, licenses, maybe SSL certs, etc etc. Let's set up a namespace for ourselves (and also the terraform-y config stuff for providing everyone with the necessary access).

DoD:
- [x] the namespace is setup in Vault and the team is provisioned with access to it
- [ ] Document access details in our [private doc repo](https://github.com/bcgov-c/platform-services-docs)

**Comment by mitovskaol** [comment]
@caggles Can you please add the reason for this tickett to be in "Blocked" in the commen please. I again forgot what was the reason for this to be blocked :(

**Comment by caggles** [comment]
@mitovskaol We're going to walk through this particular task during one of the KT sessions, but we haven't had a chance to do that yet. It's blocked by the outstanding KT meetings with Justin!
