### ISSUE TITLE
Deliver presentation on HPA and VPA to PS Team

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2235]
Horizonal Pod Autoscaler (HPA) and Vertical Pod Autoscaler (VPA) are the features available in Openshift 4 that help increase resiliency of apps and improve resource utilization efficiency. Platform Services Team needs to have a good understanding of these feature, what they do and the best practices for using them, so that we can better support product teams and advise them on the use of these features. *Development of training materials for developers will be tracked in a separate ticket.*

DoD:
-  [ ] Prepare a 10-15 min presentation about  HPA and VPA to deliver at one of the Team's Huddles.

**Comment by tmorik** [comment]
Currently testing HPA and VPA in KALB and try to figure out best practices.

**Comment by tmorik** [comment]
Slides are keeping [here](https://advsolcan.sharepoint.com/:p:/r/sites/ManagedContainerServicesMCS/Shared%20Documents/Daily%20Ops/OCP%20Talks/2022-xx-xx%20AUTOSCALING%20-%20HPA%20and%20VPA.pptx?d=w25d8dd7686724ed88379dc3b0093a65f&csf=1&web=1&e=UhKty7).  - under construction -

**Comment by tmorik** [comment]
Presentation has been scheduled on Apr 27th, Wed, 9:00- 9:30 am.  Invitation has been sent to  the entire technical part of PS Team.

**Comment by tmorik** [comment]
1st Session has been done. 
2nd Follow-up HPA - VPA Demo meeting will be hold on May 4th, Wednesday, 10-11 am. Invitations have been sent to PS team.

**Comment by tmorik** [comment]
2nd: Demo session has been done.
3rd: A brief presentation (10-15 minutes) will be given at the Platform Services Community Meetup on Tuesday, May 10.

**Comment by tmorik** [comment]
HPA/VPA presentation has been done at Platform Services Community Meetup on Tuesday, May 10.

Also The demo steps have been preparing in the GitHub so that uses can test HPA/VPA in their namespaces: 

 - https://github.com/bcgov-c/advsol-docs/pull/207

**Comment by tmorik** [comment]
For the demo video shooting, It's covered by this ticket:

 https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2584

I will close off this ticket.
