### ISSUE TITLE
Integrate Mautic with WordPress

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2236]
The [new website](https://platform-services-dev.apps.silver.devops.gov.bc.ca/) that we are building in WordPress will have the **Platform Updates** page. This page will include a **paginated** list of all updates that have been sent out to the Platform distribution list through the ]Platform Subscription Service (Mautic)](https://mautic-de0974-prod.apps.silver.devops.gov.bc.ca/s/dashboard). 

The page will contain a list of email subjects e.g. `Quota Reduction in tools namespaces in Silver Openshift cluster`,`Important Docker Lincense Change`, that are clickable links and open a new window that displays the entire email body similar to the [email preview](https://mautic-de0974-prod.apps.silver.devops.gov.bc.ca/email/preview/58)  that is available in Mautic.

DoD:
- [ ] an integration is set up between WS and Mautic that a new link is added to the top of the list on the Platform Update page in WP  when a new email is sent out through Mautic.

**Comment by mitovskaol** [comment]
@ty2k If the Platform Updates does not exist in WP yet, please connect with @theresawuzhere to create it

**Comment by theresawuzhere** [comment]
The page is here @ty2k https://platform-services-dev.apps.silver.devops.gov.bc.ca/our-services-in-private-cloud-paas/platform-updates-for-private-cloud-paas/

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
