### ISSUE TITLE
Sysdig - metrics scraping too frequent that overload kubelet service

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2257]
**Describe the issue**
Sysdig scraping kube apiserver too fast causing stress during silver cluster upgrade

To address this issue, sysdig support confirmed that the scrape rate at 10sec/request, and it's not configurable.

As suggested, we can enable sysdig to make use of node leases for cold-start, that reduces the scrape rate when server under load: https://docs.sysdig.com/en/docs/installation/sysdig-agent/agent-installation/using-node-leases/

**Definition of done**
- [x] test the changes
- [ ] push to prod and verify if that helps

**Comment by StevenBarre** [comment]
Tested node leases in lab, no improvements to API request rate.

**Comment by ShellyXueHan** [comment]
### Updates:

Sysdig suggested several things, so far non helped:
- make use of leases: we can verify the leases are created but not seeing any reduce in requests
- upgrade to 12.3.0: no improvement either
- confirmed that promscrape cannot be configured at from sysdig to a less frequent scraping interval, so if there is no way to reduce it, we'll have to disable the feature

Currently uploaded logs and manifest asked by sysdig support, waiting for next step!

**Comment by ikethecoder** [comment]
@ShellyXueHan I can see our switchover_agent metrics now in Sysdig Cloud, were you able to sort out the issues with Service Discovery?

**Comment by ShellyXueHan** [comment]
@ikethecoder I forgot to update the ticket. Service discovery has been enabled already, and we are doing pretty good with the load. Are you having any issues?

**Comment by ikethecoder** [comment]
@ShellyXueHan nope, happy it is available :) thanks!
