### ISSUE TITLE
Investigate Technical Requirements for Grafana Operator

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2259]
**Describe the issue**
Per the cluster status page in CLAB, The current version/channel of Grafana Operator is not going to be compatible with Openshift 4.9, thus the operator will need an upgrade prior to Openshift being upgraded. This likely coincides with how the Grafana Operator pod is currently using deprecated API calls that need to be fixed.

While it's quite possible and likely that Grafana Operator will receive an update via the current channel, we do want to perform an upgrade via channel switch so that we're getting a newer overall version of Grafana. There is now a `v4` channel which was attempted during earlier upgrade efforts for CLAB to 4.8, but determined to need more time to figure out completely than we were willing to allot time for at at the time.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Investigate technical requirements and dependencies to determine if native CCM update will cover this or if intervention will be required.
- [x] Test upgrades in CLAB
- [x] Confirm upgrade in KLAB
- [x] Perform upgrade in SILVER
- [x] Perform upgrade in GOLD
- [x] Perform upgrade in GOLDDR

**Comment by StevenBarre** [comment]
https://github.com/grafana-operator/grafana-operator/blob/master/documentation/upgrade.md#upgrade-from-3xx-to-4xx

Looks like we need to uninstall the old one before re-installing the new one.

```
oc -n openshift-bcgov-grafana delete Subscription grafana-operator
oc -n openshift-bcgov-grafana delete ClusterServiceVersion grafana-operator.v3.10.3
```

Still testing in CLAB, seems it needs a bit more attention

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/397

**Comment by StevenBarre** [comment]
Will go out in next CCM push

**Comment by StevenBarre** [comment]
Upgraded in Silver via CCM

**Comment by wmhutchison** [comment]
Upgraded in GOLD and GOLDDR as well, closing this ticket off as fulfilled.
