### ISSUE TITLE
Update pipeline templates

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2293]
Bruce did some work testing the pipeline templates in https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2194.  

As a result, he noted a number of areas that could be refined/updated as they are inconsistent with the way our developers generally interact in this space.
e.g. GCP account references, use of quay.io

The goal is to refine the templates to include references to artifactory, vault, etc, and provide consistent output of scanning reports.

To do:
- [x] Identify areas of concern and files in which they reside
- [x] Modify templates to reference appropriate technologies/targets
- [x] Revise Tekton Pipeline Demo Case Annotation and Add prerequisites 
- [x] Review, Revise, Test Kustomization.yaml under ./base directories
- [x] git clone -bare to create new pipeline template to https://github.com/bruce-wh-li/devsecops-tools
- [x] Review, Revise markdown, documentation in the pipeline template
- [x] Use templates to deploy a test app (using GH actions)
- [x] Use templates to deploy a test app (using Tekton)

What does success look like?
- [x] Templates updated as described
- [x] Templates successfully run
- [x] Expected outputs are consistent

**Comment by bruce-wh-li** [comment]
Hi, I would close this ticket as what defined in DOD is completed.    But, I will create another ticket to convert tekton zap scan result from log in markdown format to a new github issue
