### ISSUE TITLE
RocketChat Flatpak Login Issue with GitHub 2FA

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#23]
Client Type: Flatpak
Client Version: 2.15.3
OS Version: Fedora 30
Issue: Logging in through GitHub with 2FA enabled causes the "Houston We Have a Problem" screen when it attempts to drive the user to the verification code.

**Comment by lukegonis** [comment]
@stewartshea can you please let us know if this is still an issue?

**Comment by stewartshea** [comment]
I'm unaware of any other issues with this, but I've also stopped using the flatpak app. I'd suggest closing for now if nobody else has reported the issue.
