### ISSUE TITLE
Install ACS in Silver

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2303]
Based on assessment by @NickCorcoran, we have made a decision to go ahead with replacing AQUA with ACS in our production clusters. Based on my discussion with Nick, the steps for rolling out ACS in Silver are the following (FEEL FREE TO CHANGE AS NEEDED):

DoD:

- [x] removing Aqua components (enforcers) from Silver nodes
- [x] scaling down Aqua UI
- [x] delete AQUA namespace
- [x] Update CCM to remove Aqua elements
- [x] Acquire licenses for ACS
- [x] Ensure CCM is setup to install on Silver
- [x] Run CCM to roll out ACS in Silver **on March 22**

We also will need to fix the TLS issues we currently have in lab but for now can use the cluster wildcard though. Steven knows about this.

**Comment by StevenBarre** [comment]
@gnunn1  says we can't use the cluster wildcard and must order a separate cert.

[Docs on adding a custom cert](https://docs.openshift.com/acs/3.68/configuration/add-custom-certificates.html#custom-cert-new-install_add-custom-cert)

**Comment by StevenBarre** [comment]
Added a DoD task to ensure we've got licensing in place before the rollout.

**Comment by StevenBarre** [comment]
Custom domain and cert acquired. https://github.com/bcgov-c/platform-gitops-gen/pull/389 to add to CCM.

**Comment by StevenBarre** [comment]
ACS installed in all prod clusters
