### ISSUE TITLE
RACI Charts

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2309]
**Describe the issue**
RACI (Responsible, Accountable, Consulted, and Informed) charts will need to be created for each offering, ARO and ROSA. These charts should show what the cloud provider, BC Gov OCP platform services team, BC Gov Cloud platform team, and DXC roles are.

**Definition of done**
2 Documented RACI charts are completed and available for viewing.

**Comment by filiy** [comment]
Start with just the ROSA for now. We can use the online documentation and elaborate a bit more. Add this into the CER

**Comment by filiy** [comment]
Some links do use.
https://docs.openshift.com/rosa/rosa_policy/rosa-policy-responsibility-matrix.html
https://docs.microsoft.com/en-us/azure/openshift/responsibility-matrix

**Comment by filiy** [comment]
Maybe I just need to add 2 more columns to the chart for the internal platform and ops teams ?

Meeting with Olena this week to discuss.

**Comment by StevenBarre** [comment]
RACI in the CER
