### ISSUE TITLE
Documented support procedures

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2311]
**Describe the issue**
- [ ] When something is very broken with the OCP in the cloud who is to call who. Document this procedure.
- [ ] Document the provided SLAs for the managed OCP options.
- [x] Create support flow chart like below link.
https://app.mural.co/t/platformservices5977/m/platformservices5977/1634255277439/1b98fb52f1a179cbc324f525ca343761b26ee8cd?sender=u66de390c4d3da408f9803733

**Definition of done**
Document created and available for viewing.

**Comment by StevenBarre** [comment]
Documented in the Consulting Engagement Report
