### ISSUE TITLE
Existing tooling integrated to managed clusters

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2314]
**Describe the issue**

BC Gov is using Sysdig, Vault, Artifactory, ArgoCD & Ansible for cluster configuration, and a project registry tooling in on-prem clusters. This tooling should also work on the cloud managed OCP clusters.

**Definition of done**
Test these tools on cloud OCP and create report or documentation if tooling is working or not.

If tooling does not work or not supported that call out what cloud alternatives are available and how can they fit in with existing on-prem tooling.

**Comment by filiy** [comment]
This is called CCM - Cluster Configuration Management.

**Comment by filiy** [comment]
Sysdig/ACS per node installs

App/Product teams have ArgoCD(shared) for their tooling in cluster.  ArgoCD(ccm)  for cluster config creating namespaces etc, this powers CCM.

Talk to Steve Barr.

Vault runs in Gold cluster. Available anywhere via API. Same with Artifactory.

Will need to test network comms from ROSA.

**Comment by filiy** [comment]
This might be a task for StevenBarre to confirm. ROSA being a managed service there are probably some things that don't work or that wouldn't make sense.

**Comment by StevenBarre** [comment]
CCM was installed successfully in ROSA and most apps it managed were tested.
