### ISSUE TITLE
Cost Reporting

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2316]
**Describe the issue**

Red Hat has cost reporting available at console.redhat.com that should work of the box with managed OCP but will need to confirm. This is a nice to know but not a hard requirement.

**Definition of done**
Cost reporting is available to generate reports.

**Comment by filiy** [comment]
Also try and use the cost reporting operator to gather AWS objects outside of OpenShift. Like database services. Also map back to OpenShift project name/tag. 

Cloud pathfinder team has a tagging system for this in AWS so work with them on these details.

**Comment by caseyrobb** [comment]
Cost Management Metrics operator has been installed and is reporting metrics.  Need confirmation from the team whether they are visible in console.redhat.com.

**Comment by caseyrobb** [comment]
Cost metrics are successfully being sent from the ROSA cluster to console.redhat.com.  We have also successfully added the AWS billing report from the account 646284873784 (mv9dx3-rosa) as a billing source on the Red Hat console.  We should start seeing cost metrics within 24hrs.

**Comment by caseyrobb** [comment]
Cost models still need to be created in the Red Hat console for the ROSA clusters.  I'll ask around internall at RH to see if we have examples/templates.
