### ISSUE TITLE
Multi cluster tooling and visibility

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2317]
**Describe the issue**

If now there are 4 or 8 clusters across the cloud and in-prem what tooling to use to manage and observe multiple clusters.
Existing ArgoCD & Ansible and Sysdig tooling may work fine or another product like ACM might provide a better solution.

**Definition of done**
Documentation provided about this tooling or tooling set up with documentation.
Not a hard requirement but good to know.

**Comment by filiy** [comment]
Nick was also looking at firewall for Cloud Clusters, maybe check point? This would be something to look into also.

**Comment by filiy** [comment]
This might be a task for StevenBarre to confirm.

**Comment by StevenBarre** [comment]
Sticking with per-cluster ArgoCD for now
