### ISSUE TITLE
Cluster Authentication

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2319]
**Describe the issue**
Configure managed cloud OCP clusters to utilize existing (https://oidc.gov.bc.ca) authentication procedures to log into the cluster

**Definition of done**
Users can log onto cluster using existing methods and credentials and this is documented.

**Comment by filiy** [comment]
Started this. We created a local account to use. Testing oidc will be next.

**Comment by filiy** [comment]
In order to test OIDC we need working DNS. This is blocked until cloud team finishes this.

**Comment by filiy** [comment]
setup meeting with steven to get details for OIDC info and connections created.

**Comment by StevenBarre** [comment]
Docs https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/CCM/OAuth.md

**Comment by filiy** [comment]
Steven created a new client in SSO and we added a authentication to the ROSA cluster from console.redhat.com using these details.

We need DNS to work before we can test this.

**Comment by StevenBarre** [comment]
Is adding this via the RH Console the best way? Can we "infra as code" this somehow? Can we just create the oauth object via argocd like we do in other clusters?

**Comment by filiy** [comment]
Yup. I don't think there is any issue with doing this via code and just pushing the oauth config via ArgoCD.

**Comment by filiy** [comment]
On that note, I believe this is complete now. At least we've tested and confirmed we can use oidc.gov.bc.ca to log into the ROSA clusters.
