### ISSUE TITLE
OCP 4.8 Upgrade Openshift Prep in GOLDDR

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2333]
**Describe the issue**
Run the OCP 4.8 upgrade prepatory steps in GOLDDR. The aim here is to deal with potentially impactful components of the upgrade that are not part of the core upgrade during a Sunday change window.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] Upgrade `oc` CLI on util server.
- [x] Run Registry Hard Prune.
- [x] Upgrade F5 CIS if required.
- [x] Upgrade NetApp Trident if required.

**Comment by StevenBarre** [comment]
Completed
