### ISSUE TITLE
Critical Systems - Create test plan for DR (and BCP?)

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2335]
An important piece of a disaster recovery capability is that it is tested to identify gaps.  This task is to create a test scenario for DR.  Other tasks to run the exercise (tabletop or live), record outcomes, identify gaps and update the DR plan will follow.  Could also just be a walk-through of current process flow through documentation to get team familiar.

- [x] Create test plan for DR
- [x] Review for applicability/reasonableness

**Comment by NickCorcoran** [comment]
Suggest reaching out to security team from SDPR for an example

**Comment by AvneetKahlon** [comment]
Having meeting with John from SDPR and Tally singh.
