### ISSUE TITLE
New landing page for Developer.gov.bc.ca

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2336]
In the new web presence for the Cloud Services in BC Gov, the landing page for https://developer.gov.bc.ca will represent an index of all developer services available in BC gov for product teams working in the Private and Public clouds. This approach has been inspired by industry leaders such as https://developer.apple.com/ and https://developers.google.com/ 

The `developer.gov.bc.ca` page can look like this:

![image.png](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/d233d4e6-753a-428c-882a-b13457eda8cc)

DoD:
- [x]  working with  the Platform Service Team , create a list of all developer services to include in the index
i asked the team, but it wasn't official and i didn't get any feedback.
- [x] determine if the page can be hosted on the same WP instance that will be used to hold the "business" content for the PS Team  (hopefully, it is a yes)
**We have confirmed that in order to have its own navigation , menus and breadcrumbs, this site needs to be hosted in a separate WordPress Instance. @mitovskaol will be requesting 2 WP instances for this site: test and prod.**
- [x] Develop the page in WP: for now, this is all I could create. We need a better directory than this, one that can be sorted, have images, etc. https://platform-services-dev.apps.silver.devops.gov.bc.ca/our-products-in-the-private-cloud-paas/developer-registry/

**Comment by theresawuzhere** [comment]
From Olena in RocketChat
For the Private Cloud services, I was thinking we will have the following:
Openshift -> points to a page (does not exist yet) that lists links to the Openshift Consoles for all Platform clusters e.g. [Openshift Console for Silver Cluster’(https://console.apps.silver.devops.gov.bc.ca/dashboards), Openshift Console for Gold Cluster, etc
Artifactory -> points to https://artifacts.developer.gov.bc.ca/
Vault' -> points tohttps://vault.developer.gov.bc.ca/`
Sysdig -> points to https://app.sysdigcloud.com
RocketChat -> points to https://chat.developer.gov.bc.ca

I am also thinking that maybe next to the link to the Service UI we should also include the link to the technical doc for this service, what do you think?
e.g. Artifactory -> links to the Service UI at https://artifacts.developer.gov.bc.ca/ and to the Service docs at https://docs.developer.gov.bc.ca/artifactory (for now can point to the Artifactory Service Definition )

**Comment by theresawuzhere** [comment]
@mitovskaol for this ticket, under DoD there's this item, "determine if the page can be hosted on the same WP instance that will be used to hold the "business" content for the PS Team (hopefully, it is a yes)".  For this WP instance, are you referring to the test site or the production site?

**Comment by theresawuzhere** [comment]
The developer.gov.bc.ca can't be in the same WP instance because we need a site that can have its own URL and: 
Everything such as the navigation, the site name, and page title are site-level settings with the exception of the bread crumbs. I asked @ty2k and we tested it and this is the result. Tyler says,

>  So really it seems like this page is more suited to being the homepage of a different WordPress site with a different title and header navigation and all that.

**Comment by mitovskaol** [comment]
@theresawuzhere Yes, I understand that the developer.gov.bc.ca page needs to be hosted in a separate WP instance.

**Comment by theresawuzhere** [comment]
@mitovskaol ok, for this DoD item, did I understand the question correctly and answer it with a "no"? or were you asking something else?

> determine if the page can be hosted on the same WP instance that will be used to hold the "business" content for the PS Team (hopefully, it is a yes)

**Comment by mitovskaol** [comment]
@theresawuzhere I updated the DoD in the ticket to reflect the findings.

**Comment by theresawuzhere** [comment]
the list of resources is in progress here: 
https://docs.google.com/spreadsheets/d/1fNFRWPYWPDQW7I3xqYprlHRaKzCDybZoG4X6w772zL0/edit

**Comment by mitovskaol** [comment]
Sounds good @theresawuzhere  The new ticket with the title "Set up a WordPress instance for the new developer.gov.bc.ca"
