### ISSUE TITLE
Document the design for a Canary Test app

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2338]
The Platform Services Team needs a simple app that will be deployed in all our Openshift clusters and will serve 2 purposes: 1) in Lab clusters it will help test the impact of Openshift upgrades on apps  and 2) we can also use to monitor the availability of the Platform service by checking that the app is healthy and can perform all its functions i.e. can spin up a new pod, can create a new PVC, etc

This ticket aims to document the design of the app e.g. what components it must have to be representative of most apps on the Platform and especially include the technologies that proved to be vulnerable to Openshift upgrades in the past. e.g. use Patroni for PostgreSQL clusters. Approach to monitoring the health of the app should be documented here as well e.g. what health checks and liveliness probes should be set up to monitor the main app functions, what cron jobs should set up to force the execution of the main app functions e.g. a cron job that periodically kills a database pod in a Patroni cluster to force a new pod to spin up.

**Suggested Core and Additional Components to Test:**
- [ ] Part of Openshift upgrades tests ability to build from Github repo (platform-tools repo).
- [ ] Test core ability for Openshift to build and launch a simple web app via S2I. (Platform Ops had a script for this on OCP 3.11, bring back and update for OCP4).
- [ ] Test ability for Operator-driven Database clusters to survive an upgrade (CrunchyDB, EDB).
- [ ] Test abilty for non-Operator-driven database clusters to surviva an upgrade (Patroni). Needs to be stock/standard with respect to recommended standards offered by Platform Services
- [ ] Test Ability for Openshift Pipelines to continue functioning.
- [ ] Test ability for Artifactory to continue working.
- [ ] Test ability for Vault to continue working.
- [ ] Test ability for SSO services to continue working. Test via SSO login only, or do we need to test this inside an app as well?
- [ ] Test ability for ACS to function. Not sure what we want to check exactly here apart from ACS coming up via web console. Perhaps can web console come up if primary, and/or System Health is all green with respect to ACS if primary/secondary?
- [ ] Test ability for components of Red Hat Integration to continue functioning. Might only be possible for clusters where it is installed, and need to be tested by owning stakeholders of the service.
- [ ] Test applicatons setup for HPA and VPA, unit-test to confirm HPA and VPA continue working as expected.
- [ ] Test Sysdig is still working (SaaS backend still sees data for canary apps)

**Definition of Done:**
- [ ]  Document the app components
- [ ] Document what main app functions will be periodically executed with the purpose of testing their success
- [ ] Document how the health of the app will be monitored

**Comment by wmhutchison** [comment]
My initial list for components, looking not just at the canary app(s) but everything to ensure nothing gets forgotten. From the first list we can then pare back to what makes sense for one or more canary apps.

**Comment by wmhutchison** [comment]
1. Unit-testing across all APP nodes:
    1. Can it run pods without issue? (Platform Ops has legacy script for this)
    2. Can one build via S2I and both upload and read from internal registry?  (Platform Ops has legacy script for this)
    3. Can one successfully execute a native Openshift Pipeline?

2. Testing commonly-used apps:
     1. Does a running Patroni cluster survive the upgrade process? (likely needs a simple app that uses the DB for automated tests, more command-line checks for more thoroughness)
     2. Does a running CrunchyDB cluster survive the upgrade process? (likely needs a simple app that uses the DB for automated tests, more command-line checks for more thoroughness)
     3. Does Red Hat Integration services still work? (would need help setting something up app-wise to test this, otherwise we're looking for pods involved that might have failed)
    
3. Testing commonly-used services:
     1. Does the web console for Openshift still work?
     2. Does Kibana web interface work?
     3. For ACS, does the web console for that system come online if hosted on the cluster in question, or going to the console responsible for monitoring the cluster have any issue with the upgrade?
     4. For sysdig, are we able to login to sysdig web console and see up-to-date data fetches from any of our canary app(s)? Running pods with no crashloops also a good thing.
     5. Does vault still work? (Canary app using it, and web management console is accessible and shows no issues on login)
     6. Does artifactory still work? (Canary app using it, I guess there's a management console for it to check as well?)
     7. Does VPA still work as expected? (Inspect the resource associated with an app managed by this)
     8. For GOLD/GOLDDR maintenance, do internal services setup with GLSB DNS update properly?


4. Testing internal operations:
     1. Does AlertManager have no alerts, and we know that it is working (often tested for us by virtue of the upgrade process itself)?
     2. Are there any ongoing Nagios alerts after upgrade is finished?
     3. Check before/after graphs for API Performance within native Grafana to see if there's a significant and permanent uptick in usage. Can expect some jitter during the upgrade itself, more concerned about possible API issues due to some component post-upgrade acting differently.

**Comment by mrobson** [comment]
Adding a few initial thoughts:

1) Validate network policies within the test application
2) Testing SSO integrations
3) Validating live traffic during the upgrade (looking for sdn related issues or other disruptions / response time issues)
4) Comparing baseline graphs for cluster statistics - Things like CPU and Memory usage on the control plane and other infra level resources before and after upgrades

**Comment by wmhutchison** [comment]
For testing DB services, the focus will remain on DB services that leverage an operator we installed ourselves or othewise is provided by Red Hat, since we need to know the potential impact post-OCP-upgrade of associated operators for these.

**Comment by wmhutchison** [comment]
Moving to Backlog due to me going on vacation. If there's a desire to promote work on this in my absence, can move out of Backlog. Have added to the main description a reasonable check-list of additional things to check after each upgrade, we might end up doing that adhoc for OCP 4.9 upgrade as individual ticket items until time is spent to polish and automate via canary apps/monitoring/etc.

**Comment by wmhutchison** [comment]
Olena has expressed an interest in prioritizing Canary development for Patroni services in light of recent Health Gateway issues during OCP 4.9 SILVER upgrades.

**Comment by wmhutchison** [comment]
work on this has slide by the wayside due to operational issues that came up during SILVER OCP 4.9  work, particularly during firmware patching. Almost resolved now, so coming back to work on this more fully.

Based on feedback from Olena, priority is to be given to setting up a suitable Canary monitor for basic Patroni services. Focus will be on the official supported image standards per Platform Services since otherwise this can devolved into not-sure-how-many instances of Patroni that'd have to be maintained for specific stakeholders as some stakeholders are not running the official/latest Patroni/Postgresql images.

**Comment by wmhutchison** [comment]
I have setup a test Patroni cluster in KLAB and (insecurely)  exposed its API to allow for rapid prototyping. We'd not expose the route for actual use.

```
$ curl -s http://canary-patroni-master-api-wmhutchison-test.apps.klab.devops.gov.bc.ca/cluster | jq .
{
  "members": [
    {
      "name": "canary-patroni-0",
      "role": "leader",
      "state": "running",
      "api_url": "http://10.97.19.4:8008/patroni",
      "host": "10.97.19.4",
      "port": 5432,
      "timeline": 1
    },
    {
      "name": "canary-patroni-1",
      "role": "replica",
      "state": "running",
      "api_url": "http://10.97.13.52:8008/patroni",
      "host": "10.97.13.52",
      "port": 5432,
      "timeline": 1,
      "lag": 0
    },
    {
      "name": "canary-patroni-2",
      "role": "replica",
      "state": "running",
      "api_url": "http://10.97.16.139:8008/patroni",
      "host": "10.97.16.139",
      "port": 5432,
      "timeline": 1,
      "lag": 0
    }
  ]
}
```

**Comment by wmhutchison** [comment]
Reading up now on the API details to see what we've got available and then start abusing this new Patroni cluster while checking API to see what we get for useful/relevant data in terms of proper monitoring of the cluster.

**Comment by wmhutchison** [comment]
Created a networkpolicy to allow Nagios monitoring namespace access to reach the new API service (not the temporary route previously exposed for faster prototyping). Should have all the pieces now to start working on a Nagios monitor. For now we're going to keep it simple and Nagios is going to check the health of Patroni based on whatever the consensus is for who the master is.

**Comment by wmhutchison** [comment]
```
$ oc -n openshift-bcgov-nagios rsh nginx-857f79d8dd-b6s4f
sh-4.4$ curl -s http://canary-patroni-master-api.wmhutchison-test.svc:8008/cluster
{"members": [{"name": "canary-patroni-0", "role": "leader", "state": "running", "api_url": "http://10.97.19.4:8008/patroni", "host": "10.97.19.4", "port": 5432, "timeline": 1}, {"name": "canary-patroni-1", "role": "replica", "state": "running", "api_url": "http://10.97.13.52:8008/patroni", "host": "10.97.13.52", "port": 5432, "timeline": 1, "lag": 0}, {"name": "canary-patroni-2", "role": "replica", "state": "running", "api_url": "http://10.97.16.139:8008/patroni", "host": "10.97.16.139", "port": 5432, "timeline": 1, "lag": 0}]}sh-4.4
```

**Comment by wmhutchison** [comment]
Was stuck for a little while regarding the bcgov Patroni official image. Tried to S2I my own from Github but experienced breakage. Resolved by sourcing directly from the `bcgov/patroni-postgresql:12.4-latest` image which has an older Patroni with issues on health checks, but has been adjusted to over-come that.

**Comment by wmhutchison** [comment]
Working now on prototyping the core bare-bones of Canary app testing, which for now means a simple Python script that can do DB connections. To avoid messing around with the perfect clean Dockerfile to build a custom image for this, have instead grabbed <https://github.com/sclorg/django-ex.git> for now to run the `python-canary` pod and work out the initial workings of the testing for DB connectivity.

This same script will be viable for use against CrunchyDB as well.

**Comment by wmhutchison** [comment]
Given the unexpected complexity and curve-balls involved with Platform Ops working on developing this app (not being  active developers), am thinking that this specific ticket might need to become its own EPIC and then split off the various components of Canary testing into separate tickets for improved visibility into overall progress. Some Canary components will be easy to setup, and others will require more investigation/testing/learning. Will review this thought more closely at the start of next sprint.

**Comment by mitovskaol** [comment]
@wmhutchison This ticket is for documenting the design for the MVP of the Canary app (i.e. first iteration). Since you already included the suggested design in this ticket it can now be closed. You can track the work of implementing different app components in separate tickets each Sprint.

**Comment by wmhutchison** [comment]
@mitovskaol Thanks - will clean this ticket up, update/close and carve out new EPIC/tickets as needed. :)

**Comment by wmhutchison** [comment]
Ticket starting to suffer from scope creep. Per previous comments, closing this off, and creating a better EPIC to drive work on Canary applications as we proceed to implement them.
