### ISSUE TITLE
PaaS WordPress platform status indicator

### ISSUE THREAD

**Issue by ty2k** [BCDevOps/developer-experience#2339]
Add an indicator to the [PaaS WordPress instance](https://platform-services-dev.apps.silver.devops.gov.bc.ca/) that shows the status of the OpenShift platform, mirroring the [Platform Status page](https://status.developer.gov.bc.ca/).

**Additional context**
The Platform Status page is driven by Uptime.com. There are several options for adding an indicator using the data from Uptime.com:

1. A simple [embedded widget](https://support.uptime.com/hc/en-us/articles/360001342779-Using-the-Uptime-Widget) is provided that displays a static image showing an up-time percentage for the previous 30 days:
    <img width="564" alt="Widget code sample and image example" src="https://user-images.githubusercontent.com/25143706/157152401-dec9f7b8-f7c4-4b91-a3ff-c3e63f09277b.png">
2. [Zapier](https://zapier.com/apps/wordpress/integrations/uptime) provides integrations with Uptime.com and WordPress that might allow the creation of an auto-updating status indicator.
3. Per Uptime.com's customer support team, Uptime.com has a WordPress plugin on its roadmap but with no ETA.
4. We could call the [Uptime.com REST API](https://support.uptime.com/hc/en-us/articles/360009681280-Getting-Started-with-the-Uptime-com-REST-API) with our own custom WordPress plugin (no off-the-shelf plugin is available for this right now from the WordPress community).

Wireframe showing where the Platform Status indicator should live on the homepage:
![PaaS home page with status indicator](https://user-images.githubusercontent.com/25143706/157154224-67124e1c-fbcf-40c5-8912-cb50f5077a35.png)

**Definition of done**
- [ ] [Homepage](https://platform-services-dev.apps.silver.devops.gov.bc.ca/) is updated to include a traffic light indicator in a reusable block
- [ ] [Platform Status Page](https://platform-services-dev.apps.silver.devops.gov.bc.ca/our-services-in-private-cloud-paas/platform-status-for-private-cloud-paas/) is updated to include the indicator block
- [ ] If applicable, code is checked into a repository

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
