### ISSUE TITLE
Platform Operations - Investigate Anti-affinity rules for internal registry

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2349]
**Describe the issue**
We need to investigate if internal registry pods can be configured with proper anti-affinity so that scenarios like the below can be avoided. 

**Additional context**
```
$ oc -n openshift-image-registry get pods -o wide | grep image
cluster-image-registry-operator-64d9ff8848-wx8xs   1/1     Running   0          5h33m   10.97.0.28       mcs-silver-master-01.dmz   <none>           <none>
image-registry-5d7cc55465-c48k6                    1/1     Running   0          4h2m    10.97.6.25       mcs-silver-infra-02.dmz    <none>           <none>
image-registry-5d7cc55465-dfdq9                    1/1     Running   0          5h35m   10.97.8.22       mcs-silver-infra-01.dmz    <none>           <none>
image-registry-5d7cc55465-zf9jz                    1/1     Running   0          5h35m   10.97.8.24       mcs-silver-infra-01.dmz    <none>           <none>
```

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by StevenBarre** [comment]
I think I looked into this before, and since the number of pods matches the number of available hosts it causes rollouts to fail. But I don't remember when that was, so worth double checking again.

**Comment by wmhutchison** [comment]
Based on results of the last number of OCP upgrades last year, this is no longer an issue we're seeing. Closing ticket.
