### ISSUE TITLE
Add default policy to block known malicious IP addresses

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#235]
While reading the Aporeto docs I noticed they have an automation to automatically block a well known list of suspicious or known to be malicious IP addys.

https://docs.aporeto.com/docs/main/guides/network-policies/block-bad-ips/

We should consider if such an automation / policy would be valuable.

**Comment by j-pye** [comment]
Will not be completed. Closing. 
(Aporeto is being removed)
