### ISSUE TITLE
Investigate Access to Artifactory from Outside Openshift

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#2358]
The DataBC team has asked to access Artifactory from their applications not running on Openshift. 

Technically, there is no reason why they can't do that. However, the provisioning process assumes that the team requesting Artifactory access has an Openshift namespace. If we wish to allow those without Openshift namespaces to access Artifactory, we will need to introduce a new way to provision Artifactory access that does not have anything to do with Openshift itself.

There are policy, cost and security considerations that should be discussed as a part of this.

**UPDATE: Platform Services Team met with DataBC Team on June 13 to discuss this. It was decided that DataBC team will use the approach of accessing the Artifactory service from outside of Openshift through a project set that will be created in the Silver cluster. All new project sets provisioned on the platform have 2 service accounts for accessing Artifactory. These service accounts can be used by the external components to access the Artifactory service. This approach allows external components to leverage the existing provisioning process for accessing Artifactory without any changes required.**

**Comment by NickCorcoran** [comment]
My initial thought is that we, and our tools, are here to support our platform - not everything in gov.  Extra work to create a new access model for external things doesn't really make sense.  CITZ IMB should have an alternative for non-OCP things.  
I understand the desire for 1 place to go though.  
Will have some chats to determine best way forward.

**Comment by AubreyR** [comment]
Any updates on this Epic?
