### ISSUE TITLE
Visual Designs for Private Cloud website

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2361]
**Describe the issue**
After we launch the Private Cloud website, we'll need to review the visual design elements and change them as needed. For the launch we will use photography of BC, but post-launch we will assess the imagery and ask for graphic design assistance.

**Additional context**
If we want illustrations, can we get some time from GCPE or GPX (?). Justin can kickoff this introduction for us.

**Definition of done**
- [ ] Designs requested
- [ ] Designs created and reviewed
- [ ] Designs uploaded onto website

**Comment by lukegonis** [comment]
The design MVP has been decided on, future design improvements will be tracked in a different issue.
