### ISSUE TITLE
Redirects for WP and Tech Docs pages

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2363]
**Describe the issue**
We need to handle redirects for pages retired from DevHub and moved to WP or to the new tech docs.
We don't want people to have out of date information

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [ ] Keep track of new and old URLs in the Site Map and Content Mapping
- [ ] Launch new product owner website and tech docs
- [ ] Set up redirects from old URL to new URL.
- [ ] For pages that are retired, remove content and provide message that the content has moved, then provide the new URL.

**Comment by mitovskaol** [comment]
This work is tracked in other tickets, closing as duplicate.
