### ISSUE TITLE
Create a list of topics currently covered in OCP 101 and in Onobarding Guide

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2366]
In preparation of the discussion on March 21 where we will decide what topics should be included in Openshift 101 training vs in the onboarding guide, we need to have the list of topics included in these materials today.

DoD:
- [x] create a spreadsheet that in one column lists topics that are included in the Openshift 101 curriculum today (taken from [the Miro board](https://miro.com/app/board/o9J_kjVPaSw=/)) and in the second column include the list of topics covered in the [Onboarding onto the Platform Guide](https://docs.google.com/presentation/d/1UcT0b2YTPki_o0et9ZCLKv8vF19eYakJQitU85TAeD4/edit?usp=sharing)

Topics should be sorted so that the same topics present in both lists appear in the same row in the spreadsheet, it will be easier to find the overlap between both lists this way.
Example:  
OCP 101:                                                                       
General guidelines and practices:                                
continious support for apps,                                             
who is responsible for what on the Platform 

Onboarding Guide:
Shared Responsibility Model

**Comment by mtspn** [comment]
List in progress is here: https://docs.google.com/spreadsheets/d/1ndhw1dOs5BTWXhtJVvCHgFH85qaBrkV-KTMbU99RHKY/edit?usp=sharing
