### ISSUE TITLE
Integrate Registry with new KLAB 2 (NSXT) Openshift cluster

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2374]
The Platform Services Team in partnership with Enterprise Hosting are building 2 new Openshift on-prem clusters to add to the Private Cloud Platform. The new clusters will use a different Software Define Network (SDN) technology.   [SDN  technology](https://docs.openshift.com/container-platform/3.11/architecture/networking/sdn.html) is a network security tool used to control communication between pods within a namespace and outside of the namespace.  The Silver, Gold/Gold DR, KLAB and CLAB clusters use Openshift Built-in SDN. The new NSXT Pathfinder and KLAB 2 (NSXT-Lab) clusters will use the [NSXT SDN technology from VMWare](https://docs.vmware.com/en/VMware-NSX-T-Data-Center/index.html). NSXT technology can work on an Openshift cluster as well as on a traditional infrastructure such as VM. Openshif Built-in SDN can only work on an Openshift cluster. 

There are many teams in the BC Gov that are looking to modernize their legacy applications taking a phase approach - the source database (often Oracle) remains as is and continious to be hosted on a VM inside the government network zones but the app can be re-build using modern cloud-native technologies and hosted in Openshift. These team need a network security tool that can protect connections between their apps hosted in an Openshift cluster and the database services that run on a  VM. The new NSXT cluster will provide this functionality.

The Project Registry needs to support provisioning projects in the new NSXT Openshift clusters.

DoD:
- [ ] The NSXT-LAB cluster appears in the list of clusters on the Project Registry page and once the project provisioning form is submitted, a project set is created in the NSXT-LAB cluster 

@StevenBarre can help with access to the NSXT-LAB (KLAB2) cluster

**Comment by mitovskaol** [comment]
@okanji If you have capacity this Sprint to tackle this ticket, it would be great, but if it requires for the Re-Write to be finished, feel free to push it to the next Sprint

**Comment by StevenBarre** [comment]
@DanDeane tells me the NSXT-LAB (KLAB2) cluster will be getting stood up during the next "SDN Project" sprint. So we might want to push this task to the Apr 21st sprint after it is ready.
