### ISSUE TITLE
Write SaaS content for Private Cloud WordPres site

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2378]
The SaaS Cloud Service Team needs the following content developed:

DoD:
- [x]  content for the SaaS  Cloud Services landing page
- [x]  content for the [Our Partners page](https://docs.google.com/document/d/1-o4WNDK10v_Pu1vr7K4canL5EeomtGxnSKUsEKqT9bU/edit?usp=sharing) of the Private Cloud website

**Comment by mitovskaol** [comment]
@danielhirner I believe that this is what we have committed to help you with at this moment.

**Comment by theresawuzhere** [comment]
@danielhirner 
Would you be so kind as to add a comment the ticket with:
How many you SaaS services you potentially have?
One sample of the information (metadata) you have about each service?
The date by which you ideally want the page(s) available?
Any additional content you need on the site.

**Comment by danielhirner** [comment]
@theresawuzhere 

**How many you SaaS services you potentially have?**  
- 100 +,  the market offerings are constantly expanding so it will always be growing... 
**One sample of the information (metadata) you have about each service?** 
- I will send you an email attachment in MS Teams. 
**The date by which you ideally want the page(s) available?** 
-  April 30th for MVP would be great and would align with are expected responses from our initial data hoping to receive from a survey we put out to P-Card holders. 
**Any additional content you need on the site.**
Links to SaaS wayfinding guide (https://digital.gov.bc.ca/resources/low-touch-saas), links to Q&A, link to SaaSInfo email, links to all the compliance groups' pages and potentially email addresses (Security, Privacy, Risk Management Branch, Legal Services Branch, etc.) and links out to other groups like CSAM who can respond to requests for SaaS available under Enterprise Contracts.

**Comment by theresawuzhere** [comment]
From Olena: 
· Private Cloud: The B.C. government’s private cloud platform as a service (PaaS) is a reliable and secure hosting platform for deploying and running cloud-native applications powered by RedHat’s Openshift technology. It is available to ministries, agencies and Crown corporations working with the Government of B.C.
· Public Cloud. Pay-as-you-go Public Cloud hosting service for Ministry Teams with accelerators to quick-start with compliance, management and development. Currently offering AWS; GCP and Azure coming soon.
· SaaS. The SaaS Adoption Team proactively assists ministries in adopting SaaS solutions that best meet their requirements, within the context of procurement policy and coherent technology ecosystems
