### ISSUE TITLE
Investigate `file-integrity-operator pod restarts many times` issue

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#2381]
**Describe the issue**
`file-integrity-operator` pod restarts many times in Silver after OCP 4.8 upgrade. RH case has been opened.

**Additional context**
- [RH Case 03272459](https://access.redhat.com/support/cases/#/case/03172459)  

**Definition of done**
- [x] Investigate and find solutions
- [x] Test the fix
- [x] Apply the fix (CCM push CHG0035963 on March 29th)

**Comment by tmorik** [comment]
According to RH support, this is because lack of memory request and limit for the operator pod. We are trying to upgrader them and testing them in the K/CLAB clusters.

**Comment by tmorik** [comment]
Draft PR: https://github.com/bcgov-c/platform-gitops-gen/pull/409

**Comment by tmorik** [comment]
PR has been merged. Waiting for the next CCM push.

**Comment by wmhutchison** [comment]
Confirmed after CCM push that new limits are in place and pod is no longer crashlooping due  to OOMKill.

```
Containers:
  file-integrity-operator:
    Container ID:  cri-o://4c3ae1de5ec15cee34618980e5099468e5383313a818d813b5c75afc625bfc0c
    Image:         registry.redhat.io/compliance/openshift-file-integrity-rhel8-operator@sha256:c379d73b6efb5bc775838b17d362e14b9c8644374cfd462b7d15ee8f2a5e4435
    Image ID:      registry.redhat.io/compliance/openshift-file-integrity-rhel8-operator@sha256:a49132a4ac3b12d0daac0ff7d6bb14ad9d86eb1c200218b708c17ac3f323bf6e
    Port:          <none>
    Host Port:     <none>
    Command:
      file-integrity-operator
    Args:
      operator
    State:          Running
      Started:      Tue, 29 Mar 2022 11:41:33 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  1Gi
    Requests:
      cpu:     50m
      memory:  350Mi
```
