### ISSUE TITLE
Project Registry - Project Visibility and organization

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2382]
**Describe the issue**
Currently visibility into the Project Registry is restricted to POs, TLs and select others with direct grants.
There is desire to expand visibility of *some* information for all projects to anyone that can login w/ IDIR.

Information that should be available for anyone to see:
Project Information
- Project Name
- Project Description
- Ministry
- Cluster
Contact Information
- Product Owner
- Technical Lead(s)

Information that should only be available with project edit access:
Quota Information
- Namespace
- Quotas

I think it would also be beneficial in the main dashboard view, to separate projects managed by a logged in user (i.e. Your Projects) and another grouping of projects not managed by the logged in user (i.e. Other Projects).

**Additional context**
I can mock some things up if helpful.

**Definition of done**
- [ ] Visibility of Project Information and Contact Information for all projects for all logged in IDIR users
- [ ] Restricted visibility of Quota information to users with edit access to a project
- [ ] Separate sections in dashboard for Your Projects and Other Projects

**Comment by NickCorcoran** [comment]
I was talking w/ a few MISOs and they indicated that seeing namespace and quota details was of particular use to them.  I don't think this would be the case for the majority of people though.  
The main reason on namespace is that they can easily figure out who owns a resource when viewing content in ACS.  
Quotas also help determine risk factors to an application as part of a security assessment.  
- Unsure if this means they would need a custom role or not.  I don't mind managing that if it is a manual thing as I will have to do the same for ACS - perhaps they could draw from the same list in a YAML in a secure repo.

**Comment by mitovskaol** [comment]
This ticket will have to wait until the Re-Write is finished as the authorization will be changed quite a bit.

**Comment by Iryna-Kaplun** [comment]
This ticket has been moved to the registry repo #1058 and will be tracked there.
