### ISSUE TITLE
GOLDDR Certificate for API

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2391]
**Describe the issue**
On March 22nd 2022, internal Nagios monitoring alerted the Platform Operations team that the API certificate for the GOLDDR is going to expire in 90 days. Will need to look at getting this renewed.

**Additional context**
Look at the wildcard APP certificate as well, since it'll likely have a similar expiry date.

Also look at ongoing initiatives where there's a desire to consolidate iStore requests so that we're not peppering others with multiple iStore requests for cert renewals, so we might end up re-newing the rest of the certs for other clusters to align with GOLDDR going forward.  May or may not happen, but for now, current priority is dealing with GOLDDR.

**Definition of done**
- [x] Determine if APP cert is going to expire around the same time or not
- [x] Get the ball rolling on cert renewal
- [ ] Create a suitable EPIC if this turns into a desire to get the rest of the cluster certs renewed with new expiry dates to align with GOLDDR.

**Comment by StevenBarre** [comment]
Cert being ordered in #2433

**Comment by StevenBarre** [comment]
Certs for Gold DR updated
