### ISSUE TITLE
Porter Operator: Improve Logging

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2397]
**Describe the issue**
Update the logging of the Porter Operator to provide more information for troubleshooting.

**Additional context**
Log messages of the `portmap-api` container do not include a timestamp.

Because the Porter Operator builds are managed by CCM and are in the Silver cluster, where we cannot disable Argo CD auto-sync as we do in KLAB, an alternative BuildConfig will be created in another namespace.  This will allow us to build from a branch of the Porter Operator git repo and produce an image with an alternate tag for testing.

**Definition of done**
- [x] All log messages include the date and time
- [x] All events that could be helpful for troubleshooting produce log messages

**Comment by ksummersill2** [comment]
Porter Operator is going through testing and will be pushed for review.

**Comment by ksummersill2** [comment]
Updated the readme file and documentation on building the Porter Operator. Logging was updated with log.Println. Now to test to see if the logs show up with timestamps.

**Comment by ksummersill2** [comment]
Need to finalize testing and get with Ian.
