### ISSUE TITLE
Determine WordPress content migration best practice

### ISSUE THREAD

**Issue by ty2k** [BCDevOps/developer-experience#2406]
To support multiple WordPress instances on OpenShift, determine a best practice for migrating WordPress content between `-dev`/`-test` and `-prod` instances of a single site.

For example, once content on the [Private Cloud PaaS dev site](https://platform-services-dev.apps.silver.devops.gov.bc.ca/) is ready to be graduated to a "production" site in OpenShift, how should this be done?

**Additional context**
- Check the widely-used [All-in-One WP Migration plugin](https://wordpress.org/plugins/all-in-one-wp-migration/).
- Contact the GDX Engagement team to see if they have a recommendation.

**Definition of done**
- [x] Demonstrate content migration method to Olena and Justin
- [x] Make a recommendation for a content migration solution

**Comment by ty2k** [comment]
I tested the [All-in-One WP Migration plugin](https://wordpress.org/plugins/all-in-one-wp-migration/) on the [current dev site](https://platform-services-dev.apps.silver.devops.gov.bc.ca/) and a local WordPress instance running on my machine using PHP 7.4, MySQL, and [WordPress 5.9.3](https://wordpress.org/download/). Overall, I found success in moving over blog posts and the site theme, with some caveats.

## Entire new site database is overwritten

The All-in-One WP Migration plugin exports the original WordPress site's entire database, and *overwrites* the target site's database. There is no "merge" or "upsert" option - any existing data in the target site will be gone after the migration is completed. This means we need to perform the migration immediately upon receipt of the production site before any changes are made to it - unless we are happy to lose those changes.

In the future, this plugin would be especially good for over-writing dev/test sites with production data if we are developing new features, testing new plugins, and the like.

## Maximum file upload size

The plugin uses the WordPress file upload API to import a site archive (`.wpress`) file. This API is limited in the size of file uploads it accepts by a configuration value. The current dev site has a [`max_upload_size`](https://developer.wordpress.org/reference/functions/wp_max_upload_size/) set to 128MB. I found that when using the default plugin settings to export everything from the site, the resulting `.wpress` archive file was around 280MB. 

Locally, I was able to change this setting on my WordPress instance by using a `./php.ini` file and running the server using `php -S localhost:8000 -c .` where the `-c` flag passes the directory of the `php.ini` file as an argument. My `./php.ini` file looked like this, though lower allocations are fine as long as they are greater than the `.wpress` file size:

```ini
# php.ini
upload_max_filesize = 512M
post_max_size = 512M
memory_limit = 1024M
max_execution_time = 0
max_input_time = 300
```

There are [several ways to change a WordPress site's maximum file upload size](https://www.cloudways.com/blog/increase-media-file-maximum-upload-size-in-wordpress/#plugin). If for any reason we aren't able to modify the `maximum_upload_size` in our production instance at build time, we can potentially use a plugin like [Increase Maximum Upload File Size](https://wordpress.org/plugins/upload-max-file-size/) for this task at runtime when the site is operational.

If for some reason the `maximum_upload_size` value can't be changed, we can also look at excluding items from the All-in-One export advanced options:

![All-in-One WP Migration advanced options screenshot](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/a7d56e50-7ed9-4119-9aac-a8e80cc8f9ea)

I found that by excluding plugins, I was able to get the file export size down to 88MB. An issue with doing things this way is that the resulting WordPress site will have styles missing from plugins, and the exact scope of what's missing isn't very clear. Adding plugins back in after the fact might not "just work" as expected. It would be preferrable to copy the entire site over than to have to figure out what might be missing afterwards from looking at mangled pages.

## User access after importing a site

Once a `.wpress` file has been imported into a new WordPress site, the entire existing database is overwritten (not merged). On my local machine, I have no connection to the BC Gov SSO system to be able to log in using my IDIR account, like I have on the development site. In production, authentication might "just work" after completing the migration, but what if it doesn't and we're locked out?

To make sure we aren't locked out of the site, and to be able to work on my local development site after a migration, I added an administrator user account to the development site prior to export. Rather than using SSO, this user logs in through the WordPress login page with a password. After migrating the development site's content to my local instance, I find I am still able to use this account to log in as expected. However, the act of migrating and over-writing the database means that the user account I set up while first installing WordPress is gone.

**Comment by ty2k** [comment]
I've marked this issue as **blocked** as I've taken it as far as I can without having access to our production WordPress instance to be able to confirm the viability of the All-in-One WP plugin for our migration strategy.

**Comment by ty2k** [comment]
The GDX Engagement team has stood up an empty `test` WordPress site for us within a multi-site instance: https://platform-services-test.apps.silver.devops.gov.bc.ca

This multi-site instance limits our ability to test the [All-in-One WP Migration plugin](https://wordpress.org/plugins/all-in-one-wp-migration/), as it would require the [Multisite Extension](https://servmask.com/products/multisite-extension), which is a paid add-on. Currently, the price is USD $199/once plus either USD $29/month or USD $319/year:

![Pricing for All-in-One WP Migration multisite extension](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/20eec2d6-a40b-46f7-8bd3-a6361548a948)

To help determine if that cost is bearable, the GDX team will be standing up a new single site instance for us within OpenShift so we can use the migration plugin and confirm that everything works as expected (or what additional work may be required).

**Comment by mitovskaol** [comment]
@ty2k I think once you had a chance to test the migration with the new test WP instance, this ticket can be closed.

**Comment by ty2k** [comment]
After testing an export from [dev](https://platform-services-dev.apps.silver.devops.gov.bc.ca/) to a new single site WP instance called [test](https://platform-services-test.apps.silver.devops.gov.bc.ca/), I found that we are able to migrate the entire contents of the site from one environment to another with no loss of data.

Currently, when we include all options in our database export, the file size is around 280 MB, meaning we will need a maximum file upload size of at least this much to accomplish the import action on the target site.

![Backup files screenshot](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/b935bd0e-a52a-4b75-b0e9-656d0b1752de)

Our current `test` instance has the file upload size set to 512 MB. An import and restore action takes around half an hour to complete at this file size.

My recommendation is to proceed with the All-in-One WP Migration plugin plus the paid [multisite extension](https://servmask.com/products/multisite-extension) in our future production multisite WordPress instance. There are no foreseeable blockers to this method working.

**Comment by mitovskaol** [comment]
Thank you for the great work on this research @ty2k  and for documenting your findings in detail!
