### ISSUE TITLE
Add content to developer.gov.bc.ca

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2414]
**Describe the issue**
Once the site structure is defined and implemented in Wordpress, add the services and content to this site.

**Additional context**
None at this time.

**Definition of done**
- [ ] Add content pages to website
- [ ] Add services to website
- [ ] Ensure content meets accessibility requirements

**Comment by mitovskaol** [comment]
Closing this ticket as ownership of developer.gov.bc.ca will be transitioned to Developer Experience Team.
