### ISSUE TITLE
Create the Developer.gov.bc.ca Wordpress site 

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2416]
**Describe the issue**
Need to set up the developer.gov.bc.ca site.

**Additional context**
![DevHub.png](https://images.zenhubusercontent.com/619e7c0917f0b96bbcf6d42f/6d6b5004-bed6-4d0d-b0b5-e556ac7cdd20)

**Definition of done**
- [ ] Content page template is created
- [ ] Home page is created
- [ ] Services page is created
- [ ] Template for an individual service is created, based on metadata fields
- [ ] Services can be filtered and sorted based on metadata fields
- [ ] Site and services can be searched

**Comment by lukegonis** [comment]
This issue is no longer relevant for the Platform services team, the Developer-Experience label has been added for Karl Hardin's Reference
