### ISSUE TITLE
Content Review & Release Policy

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2431]
**Monday morning:**
 - Phil will upload a new topic, branch, and PR to the repo https://github.com/BCDevOps/devops-platform-workshops/blob/master/openshift-201/
 - Matt will identify the reviewers for this topic: Cailey or Shelly AND Billy or Steven
 
**Monday - Wednesday morning:**
 - The reviewers will review the content and leave comments / changes in the PR and can also provide feedback here in the RocketChat channel

**Wednesday afternoon:**
- The reviewers and Phil meet for the touch point and discuss/clarify the comments

**Thursday - Friday:**
- Phil makes changes to the content based on the provided comments

**End of day Friday:** 
- Final version of the topic is available for the final review in the PR
- Matt ensures that the assigned reviewers approve the PR and it it gets merged into the main branch in the repo
The cycle repeats again for every new topic starting from Monday morning.

**Comment by mitovskaol** [comment]
@filiy What is the Definition of Done for this ticket?

**Comment by filiy** [comment]
@mitovskaol I guess when all the training content is complete this issue can be closed. Though its really here as a reference. Actually it probably makes more sense if I create a markdown file in the master branch of the training content repo. 

I will close this!

**Comment by filiy** [comment]
Moved this to a markdown file.
https://github.com/BCDevOps/devops-platform-workshops/blob/master/openshift-201/CONTENT-REVIEW-POLICY.md
