### ISSUE TITLE
Enable Argo CD for JAG_RBAC

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2434]
**Describe the issue**
Devise a plan for the management of OCP RBAC in Argo CD for the entire justice ministry using the Warden Operator and the "GitOpsAlliance" resource.

**Additional context**
Because the project sets to be included have multiple ministry IDs, a new label will have to be added to each project set's tools namespace:
`alliance: JAG_RBAC`

Get a list of users that should have access to the Argo CD UI and to the GitHub repo.  Incorporate these users into the GitOpsAlliance resource manifest.

The GitOpsAlliance resource will be created in each of these clusters: KLAB, Silver, Gold, and GoldDR.

The plan will be prepared by the Platform Services team and reviewed and approved by JAG.  Initial implementation to be done by the Platform Services team, then turned over to JAG for completion.

**Definition of done**
- [x] A plan has been prepared, including repo migration strategy, repo structure, and scope
- [x] The plan has been reviewed and approved by JAG
- [x] Initial setup has been done and instructions provided to JAG for implementation next steps

**Comment by mitovskaol** [comment]
@IanKWatts This work requires a discussion with @rloisell to confirm that the GitOpsAlliance would work for his needs.

**Comment by IanKWatts** [comment]
I'll be meeting with Ryan on June 13th for this.

**Comment by IanKWatts** [comment]
Ryan and I have agreed on the plan and initial implementation has been done using two project sets each in KLAB and Silver.  I have provided Ryan instructions on next steps so that they may test the update process themselves.

To Do (outside the scope of this ticket): 
- When Ryan is ready and the GitOpsAlliance resource has been created in Gold and GoldDR, the Platform Services team will need to create the required "app of apps" for them.
