### ISSUE TITLE
In PO WP site, make the left hand navigation automated

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2442]
**Describe the issue**
In PO WP site, make the left hand navigation automated.

**Additional context**
Right now we are building the left hand side navigation in Wordpress by hand. Every time we add a page, we need to add it to the navigation. We have a reusable block for each section of the website. However, this can be error prone as we might add pages but forget to add them to the left hand side list. Or we can change a URL and it breaks the link. 

Wordpress has features for: 
- Indicating the parent page
- Indicating the order within the section.

These can be leveraged in the site.

**Definition of done**
- [ ] Create a left-hand side navigation feature that automatically displays the pages in the section, in the hierarchy specified in Wordpress

**Comment by ty2k** [comment]
I've done some research in previous tickets to try using the [Max Mega Menu plugin](https://wordpress.org/plugins/megamenu/) to meet these requirements.

One issue is that our theme imposes hover/flyout styling on menus built using the WordPress menu data model. Below is an example of the out-of-the-box functionality if we drop a WordPress menu into a content page. I have my mouse cursor positioned to reveal the third level items under the Case Studies page.

![Screen Shot 2022-04-06 at 1.47.42 PM.png](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/d68dd5fb-0f72-4c56-ac76-a24d95ba5e98)

With no control over the markup of menus within the theme, we are left with only CSS to get it looking how we want (fully expanded and displaying within a single rectangle). If we go down that path, we might be able to match the look okay, but we will be left with cruft like unusable `<button>` elements have been hidden by CSS.

**Comment by theresawuzhere** [comment]
@ty2k yes, this definitely won't work for us. the interaction is super awkward and i doubt it's accessible.

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
