### ISSUE TITLE
In WP, make the On This Page table of contents automated

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2443]
**Describe the issue**
In Wordpress make the On This Page table of contents automated.

**Additional context**
Right now we are building the On this Page section of each page by hand. This means we need to add HTML anchors by hand, then add on-page links to the On This Page section. This is prone to error as people can incorrectly create these links. Additionally, headings can be revised or removed, which will change the text in On This Page. We can remove this manual maintenance.

**Definition of done**
- [x] A feature is created where the On This Page reads all the Heading 2s on the page and puts them into the section. These would be links to further down on the page.

**Comment by ty2k** [comment]
Here is a January 2022 article from CSS Tricks on the current state of WordPress table of content blocks: https://css-tricks.com/table-of-contents-block-in-wordpress/

Since this feature is not yet baked into WordPress, an automated table of contents would need to be added with a plugin (either our own or an off-the-shelf one).

**Comment by ty2k** [comment]
@theresawuzhere I've installed a plugin called [SimpleToC](https://wordpress.org/plugins/simpletoc/) in the test site and it seems to do everything you would expect out of a table of contents plugin. You can specify the heading levels you would like to include (H2-H6), and re-generate it with a single Refresh button click if your headings change. It has a built-in "Table of contents" title that we would need to exclude if we want ours to read "On this page". One hiccup: If we use an H2 heading for "On this page" and then refresh, that heading would get included in the table of contents, unfortunately.

Could you please test this plugin out and see if it meets your needs? Just search "table" or "simple" when adding a block and you should see "SimpleTOC":

![SimpleTOC Gutenberg block icon](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/cfc2e85a-a99f-4292-951f-54a001c1e6b0)

**Comment by theresawuzhere** [comment]
@emma-csi will try this out and let us know how it works

**Comment by ty2k** [comment]
Sounds great. @emma-csi if I can help or give you a walk-through on this plugin, please give me a shout!

**Comment by emma-csi** [comment]
@ty2k Thanks, works great! I'm happy with it. @theresawuzhere it's on the Overview of our services page if you want to take a look. I'm going to start adding it to the other pages.

**Comment by ty2k** [comment]
Just following up with this one @theresawuzhere. Does the SimpleTOC plugin meet your needs? If so I will mark this done. Thanks! :)

**Comment by emma-csi** [comment]
@ty2k Theresa is away on vacation, but I think we can mark this as done.
