### ISSUE TITLE
OpenShift Pipelines Presentation

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2447]
**Describe the issue**
- Develop presentation slides for an OpenShift Pipelines introduction

**Additional context**

**Definition of done**
- [x] Slides are completed in Mural
- [x] Slides are reviewed and approved by Platform Services Team

**Comment by jayfray12** [comment]
Initial Content for tutorial are in Mural under the `OpenShift Pipelines` section
