### ISSUE TITLE
OpenShift Pipelines - Lab

### ISSUE THREAD

**Issue by jayfray12** [BCDevOps/developer-experience#2448]
**Describe the issue**
Develop lab content in markdown

**Additional context**
use template library found [here](https://github.com/bcgov/pipeline-templates)

**Definition of done**
- [x] Lab Content developed
- [x] Lab Content tested
- [x] Lab Content reviewed

**Comment by jayfray12** [comment]
PR to lab content found here:
https://github.com/BCDevOps/devops-platform-workshops/pull/119

Note:  I found some issues with the `pipeline-template` repo but do not have permission to submit a PR there

**Comment by StevenBarre** [comment]
PR and Slides reviewed
