### ISSUE TITLE
Investigate SSO for Mural.com

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2449]
Investigate KeyCloak integration with Mural.com

- [ ] Investigate what licensing model allows for SSO integration

If not available under current licensing (requires Business license - https://mural.co/pricing):
- [ ] Raise license to level required to leverage SSO

If/when available under current licensing:
- [ ] Get access to setup config to attempt setup
- [ ] Create client in KeyCloak in a realm that has IDIR available
- [ ] Test setup

**Comment by ShellyXueHan** [comment]
we don't own it. leave it for the other team to manage.
