### ISSUE TITLE
Investigate SSO for Zoom.us

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2450]
Investigate KeyCloak integration with Zoom.us

- [ ] Investigate what licensing model allows for SSO integration

If not available under current licensing (requires Business license - https://zoom.us/pricing):
- [ ] Raise license to level required to leverage SSO

If/when available under current licensing:
- [ ] Get access to setup config to attempt setup
- [ ] Create client in KeyCloak in a realm that has IDIR available
- [ ] Test setup

**Comment by ShellyXueHan** [comment]
Olena has reach out to a team that manage it for the whole gov. leave it up to them ;)
