### ISSUE TITLE
SSO usage - review the list of keycloak clients for shared services

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2455]
**Describe the issue**
 review the setup and decide if they have any custom usage.

**Definition of done**
- [x] look into each app to check if there are any custom usage
- [x] decide on if any of them would be moved to common realm
- [x] decide on if any of them would be merged into one realm

**Comment by ShellyXueHan** [comment]
### Update:
- list of shared services SSO usage are updated in the Google sheet
- I'll book a meeting with Nick and Olena to discuss on the migration plan

**Comment by NickCorcoran** [comment]
I have asked Marco what their team suggests based on client use on current realms for Platform Registry and Mautic.  He was going to provide feedback after engaging team.

**Comment by ShellyXueHan** [comment]
### Update:

currently pending discussion with RedHat support and SSO team on gold migration details!

**Comment by ShellyXueHan** [comment]
### updates:
Here are some note that comes out from the discussion:

- Out of the box Keycloak does not have the config/feature to filter GitHub user login based on Github organization membership, so we would still need the keycloak custom extensions
- We’ve decided to keep the login experience consistent between OpenShift consoles and platform shared services,  splitting out GitHub login from SSO is not an option
- OpenShift creates users by its keycloak user ID that’s local to the application realm. This would be an issue when migrating between keycloak instances or realms

 
Some action items:

- Shelly – look into platform shared services to confirm which user attribute is used to create accounts, and if possible start to merge keycloak realm usage
- Nick and team – try out Tremolo Security
- SSO team – discuss and let us know if GitHub as an IDP and keycloak custom extensions will be support coming to gold
- Once we have updates from the above, let’s have another discussion on this!

**Comment by ShellyXueHan** [comment]
### updates:
- we are still waiting for SSO team to confirm on the support plan of custom extensions
- i'll break this into individual tasks to migrate SSO usage for different apps/services
