### ISSUE TITLE
Rocket.Chat STRA Remediation - Network Security

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#247]
- [x] Investigate issue
- [x] Post requested update to forums
- [ ] Issue resolved

**Comment by jleach** [comment]
@ShellyXueHan How's this ticket going?

**Comment by NickCorcoran** [comment]
Known issue in release we are currently running.

**Comment by ShellyXueHan** [comment]
will test this out in the next RC upgrade.

**Comment by NickCorcoran** [comment]
this was related to logout not functioning properly unless cache was cleared after and browser restarted.  This is a known issue and we will have to live with it until RC decides to fix.  Risk is low and most users likely never logout anyhow.
