### ISSUE TITLE
Platform Operations - Create CronJob for checking validity of system:admin account

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2473]
**Describe the issue**
Most of of the Platform Operations API access is now handled via their own login accounts, the system:admin account does also get used for specific items as well as general fall-back for things like GitHub auth acting up, etc. Platform Ops wants a cronjob that will check once a week for the due date for the system:admin account and email if that is going to expire soon so it can be proactively fixed versus reactively fixed when we check things out ourselves.

Full automation should be fairly straight forward since we presently update the kubeconfig file via extacting and replacing the file as-is with contents we extract directly from the cluster.

**Additional context**
Red Hat Knowledge article for this specific issue: <https://access.redhat.com/solutions/6112601>

**Definition of done**
- [x] Create and test cronjob that will email Platform Ops team when account is about to expire.
- [x] Implement additional automation (optional) to perform automated kubeconfig replacement and test. Email if test fails.

**Comment by tmorik** [comment]
Drafting: https://github.com/bcgov-c/platform-ops/pull/435

**Comment by tmorik** [comment]
The above PR has been merged. This script is run on all util servers at 9am daily and if the date checked is 10 days before the expiration date of the `admin account`, it will update the kubeconfig on the util server and send an email to MCS.
