### ISSUE TITLE
Ministry-specific logic for project provisioning

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2481]
The JAG Ministries  - AG, PSSG and EMBC - would like to have custom logic implemented when a request to provision a project set is submitted for one of their Ministries in the Registry.

If Attorneey General, Public Safety and Soicitor Genersl, Municipal Affairs and Housing or Eergency Management  BC Ministry is selected in the dropdown on the project create form:

1) Automatically populate the second TL input fields with Ryan L’s info (Name, email and GitHub ID). Make the input fields disabled in this case so that these default values cannot be overriden by the user.
2) On the last step of the form wizard (before clicking the Submit button), add a second checkbox: By checking this box, I confirm that I have engaged with the AG Architecture and Security team and received an approval for this project.

![image.png](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/68454d79-6202-45e4-b069-cdd3e946f26d)

DoD:
- [ ] All of the above changes are completed.

**Comment by ShovelHand** [comment]
Note to self: let's have a "MinistrySpecificLogic.js" file in Platform Services Registry.20 where for sake of code maintainability, we have some of these conditions figured out instead of updating a bunch of different React components every time we need to account for changes like this.

**Comment by Iryna-Kaplun** [comment]
This ticket was moved to the App Dev team board #1532 and will be closed here.
