### ISSUE TITLE
Scaling the right way - Presentation 

### ISSUE THREAD

**Issue by jjocic** [BCDevOps/developer-experience#2497]
**Describe the issue**
OpenShift Training Material development - MVP 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Presentation "slides" complete on Mural board and reviewed.

**Comment by filiy** [comment]
I believe this topic is covered with the VPA/HPA and resource management labs.

Are we good to close this out?

**Comment by mtspn** [comment]
Closing, as discussed this topic is covered by the VPA/HPA and resource management sections.
