### ISSUE TITLE
Scaling the right way  - Lab 

### ISSUE THREAD

**Issue by jjocic** [BCDevOps/developer-experience#2498]
**Describe the issue**
OpenShift Training Material development - MVP 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
 Lab Content developed
 Lab Content tested
 Lab Content reviewed

**Comment by filiy** [comment]
I believe this topic is covered with the VPA/HPA and resource management labs.

Are we good to close this out?

**Comment by mtspn** [comment]
Closing, covered by other topics as above!
