### ISSUE TITLE
Evaluate the use of Airtable for building a SaaS directory 

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2499]
The SaaS Team needs to know if AirTable is the right technology to. build searchable directory of SaaS services in their WordPress site. The screenshots of how the directory may look like are available in [this deck](https://bcgov.sharepoint.com/:p:/t/04977-SaaSAdoptionTeam/EZxuCCkhbYRFvqWRBM6jxDUB4aic-T2UWz7wz5kSaCIiDQ?e=6cu4iU).

DoD:
- [ ] Research and document the findings in this ticket where Airtable is the right tool for this

**Comment by danielhirner** [comment]
Directory template with data elements available here: https://bcgov.sharepoint.com/:x:/t/04977-SaaSCloudServicesWebsite/EVoguyy5a_ZMk_M0t3NRzCkB7P_iBeifiPrbtkFGs5jhug?e=sjzmFU

**Comment by theresawuzhere** [comment]
@danielhirner @mitovskaol I didn't investigate this. Dan directed me to use it, after he had done some research.
