### ISSUE TITLE
Must Gather Operator

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2503]
**Describe the issue**
AdvSol often has to create `must-gather` reports for Red Hat as part of opening cases. It appears there is now an operator that would make collecting them easier.

**Additional context**
https://github.com/redhat-cop/must-gather-operator

**Definition of done**
- [x] Test in a lab
- [x] Create CCM PR to install
- [x] Document for ops team how to use it
- [ ] Demo at sprint review

**Comment by tmorik** [comment]
Installation issue has been opened to the community: https://github.com/redhat-cop/must-gather-operator/issues/33

**Comment by tmorik** [comment]
CLI way worked, so the test will be continued.

**Comment by tmorik** [comment]
Another issue has been opened: https://github.com/redhat-cop/must-gather-operator/issues/34

M-G operator is collecting data but uploading. cURL is complaining about the uploading URL is something wrong.

**Comment by tmorik** [comment]
Figured out above issue's cause. Upload test is now completed successfully. The RH case for this MG test is this:  https://access.redhat.com/support/cases/#/case/03233089

**Comment by tmorik** [comment]
New issue founded. I have open an issue ticket in the community:
https://github.com/redhat-cop/must-gather-operator/issues/35

-- Logging images for M-G are not working.

**Comment by tmorik** [comment]
Although not directly related to the above issue, another issue was opened to the community: https://github.com/openshift/must-gather-operator/issues/73

I was trying to test M-G operator from `openshift` community (the one we are working on is from `redhat-cop`) because this community's document is a bit cleaner and make sense, but found outdated info in the readme.

**Comment by tmorik** [comment]
It looks like it will take some time to resolve the `Logging images for M-G are not working` issue. the other images are working and useable, so I will proceed without logging image issue. for now.

Creating Operator's PR : https://github.com/bcgov-c/platform-gitops-gen/pull/471  (Draft)

**Comment by tmorik** [comment]
M-G Operator will be installed by the CCM upgrade v4.6.12 this week. 
- Silver's will be installed during Silver upgrade
-

**Comment by tmorik** [comment]
Doc PR:  https://github.com/bcgov-c/advsol-docs/pull/236

**Comment by tmorik** [comment]
CM push had been done and M-G operator is now installed on the all clusters and working as expected. I will close this ticket.
