### ISSUE TITLE
Create security dashboard and links to it from a project's details in Platform Registry

### ISSUE THREAD

**Issue by ShovelHand** [BCDevOps/developer-experience#2532]
Create initial view for projects' security details in Platform registry. It will be a table showing the security audit fro the project. See this ticket's epic for a mockup of the security dashboard, and the details to be included.

**Comment by ShovelHand** [comment]
At this point, we're considering this for Platform Services Registry 2.0 only, right?

**Comment by Iryna-Kaplun** [comment]
This issue is duplicated on the registry repo #1009. This issue can be closed and #1009 will be the main one for this work.
