### ISSUE TITLE
Prep for Upgrade CrunchyDB to v5.1

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2536]
**Describe the issue**
There's a new version of CrunchyDB out! Time to do some upgrading.

**Additional context**
https://blog.crunchydata.com/blog/introducing-pgo-the-open-source-postgres-operator-from-crunchy-data-version-5.1
https://github.com/bcgov/how-to-workshops/tree/master/crunchydb

**Blocker Removed**
CrunchyDB syncing in CCM has been turned off, allowing us to perform this update manually.

**Definition of done**
- [x] Investigate/test automation of pulling Crunchy images through Artifactory
- [x] Test the upgrade in LAB
- [x] Update how-to docs to reflect the current recommendations about images.
- [x] Create ticket for Silver upgrade tasks (plan with DXC for manual upgrade, Mautic notifications, etc)
- [x] Update CCM (despite the lack of sync) to make sure that any accidental manual syncs in the future don't have the potential to cause a version rollback.

**Comment by caggles** [comment]
The updated CRD fails when applied through Argo because the `last-applied-configuration` annotation is too long and the work-around (server-side apply) does not exist in Argo yet. This feature is being implemented as we speak - we'll want keep an eye on this PR: https://github.com/argoproj/argo-cd/pull/9711

**Comment by matthieu-foucault** [comment]
@caggles , any ETA on this, and is there any way a product team like ours can help? cc @wenzowski 
Looks this is blocking an essential feature for us, configuring our postgres cluster to back up to AWS: 
Our postgres cluster configuration, in https://github.com/bcgov/CONN-CCBC-portal/pull/565, failed to back up to our S3 buckets, with the following issue:

`command terminated with exit code 31: ERROR: [031]: option 'repo2-s3-key-type' is 'web-id' but 'AWS_ROLE_ARN' and 'AWS_WEB_IDENTITY_TOKEN_FILE' are not set`

After a bit of digging, looks like support for this was added in v5.0.1: see https://github.com/CrunchyData/postgres-operator/pull/2845 and https://github.com/CrunchyData/postgres-operator/issues/3069#issuecomment-1120075729

**Comment by wenzowski** [comment]
Without S3 support we’re going to have to request a dramatic increase in backup volume size, so the goal with requesting an ETA is to advise PO on how to be as responsible as possible with cluster pvc claims.

**Comment by conbrad** [comment]
Hi, just curious if this is still blocked and what is blocking it?

**Comment by w8896699** [comment]
Pushed required image into artifactory
Tested in clab with 4.12 with updated base image: https://github.com/bcgov/crunchy-postgres/pull/27
Tested in klab with 4.11.

**Comment by caggles** [comment]
We went up to 5.3 on Thursday of last week. Yay :D
