### ISSUE TITLE
VPA MutatingAdmissionWebhook slow or timing out | SPIKE

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2538]
**Describe the issue**
Some users are occasionally getting an error like this when creating pods
```
Error creating deployer pod: Internal error occurred: admission plugin "MutatingAdmissionWebhook" failed to complete mutation in 13s
```

Searching Kibana shows lots of 10+ second calls to the VPA admission hook
```
I0428 23:10:26.456846      20 trace.go:205] Trace[1975892683]: "Call mutating webhook" configuration:vpa-webhook-config,webhook:vpa.k8s.io,resource:/v1, Resource=pods,subresource:,operation:CREATE,UID:da7a7301-ad69-4ec5-85ab-90f8680fb159 (28-Apr-2022 23:10:13.457) (total time: 12999ms):
```

**Additional context**
https://access.redhat.com/support/cases/#/case/03208612

**Definition of done**
Pods can start without issues

**Comment by lukegonis** [comment]
blocked on a fix/response from Red Hat.

**Comment by StevenBarre** [comment]
Will be fixed in the 4.9 upgrade.

Another user hit this today with their pipeline. Asked Matt if there was a way to get pipelines to auto-retry creating pods.

**Comment by StevenBarre** [comment]
Pulled some more stats/graphs for Matt today. Looks like Vault webhook might be having the same issue, or is somehow related.

**Comment by StevenBarre** [comment]
Graphs look much better since the 4.9 upgrade. Asking user if their still having issues, waiting for a reply.

**Comment by StevenBarre** [comment]
No reply from users, closing
