### ISSUE TITLE
Review OCP 4.9 Release notes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2540]
**Describe the issue**
As Ops prepares for the next OCP upgrade we want to have the Platform Service Team review the Release Notes and identify any changes that are likely to impact product teams.

Several people are being assigned here because more eyes are better. At least two people should review the Release Notes.

**Additional context**
https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html

**Definition of done**
- Review the doc and note items of interest in the comments of this ticket
- Have a meeting with Ops to discuss the notes
- Draft of an email to be sent to the product teams announcing the upgrade and its changes.

Sending of the email will be a separate ticket in the appropriate sprint once the upgrade timing is nailed down.

**Comment by IanKWatts** [comment]
Because of the upgrade of Kubernetes to version 1.22, we will have to update references to some APIs.  For example, `rbac.authorization.k8s.io/v1beta1` will have to be replaced with `rbac.authorization.k8s.io/v1`.  I'll work on preparing a comprehensive list.

**Comment by StevenBarre** [comment]
@IanKWatts William has already started work on the API stuff under EPIC #2256 and now there's a draft of an email to send via Mautic ready for review https://github.com/BCDevOps/platform-services-status-page-notifications/pull/166/files

**Comment by StevenBarre** [comment]
No email required.
