### ISSUE TITLE
Devhub Issue: User access into Github or Openshift [short description here]

### ISSUE THREAD

**Issue by rarmitag** [BCDevOps/developer-experience#2542]
> path: (do not delete) https://github.com/BCDevOps/developer-experience/blob/master/docs/UserAccessToOrg.md
 > (do not delete) devhub page: /User-access-into-Github-or-Openshift

## Devhub Content Issue
Please provide access to openshift for github user:  schaturv18

**Comment by mitovskaol** [comment]
@rarmitag Can you please provide the justification for the user schaturv18 needing access to BC Gov's Openshift.

**Comment by rarmitag** [comment]
He’s one of our database administrators at registries, Siddharth Chaturvedi. Idir=SCHATURV

In the future I will provide more information, I wasn’t sure if this was the correct methodology.

Thanks,

Rich

**Comment by mitovskaol** [comment]
Thank you Rich, this is all I need. The invite was sent to Sid to join bcgov and BCDevOps, he needs to accept both and he will be able to access Openshift console.

**Comment by rarmitag** [comment]
Hi Olena.

Sorry to bother you with this but Sid didn’t receive any invitations. Would it be possible to send them to him again.


Thanks,

Rich

**Comment by mitovskaol** [comment]
The invite has been resent. If Sid doesn't receive it still, let me know.

**Comment by rarmitag** [comment]
He received the invites and has access now. Thank you.
