### ISSUE TITLE
Logging best practices for App teams

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2545]
**Describe the issue**
During a recent incident it became evident that app teams are not clear on what to log, or how much.  There is a desire to ensure teams meet policy requirements while also being able to recreate a scenario when an investigation occurs (who, what, when, why, how).  
Create best practices for logging for app teams and publish for consumption.  
Link to Security Considerations for Openshift.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Review policy requirements for logging
- [x] Identify what logs are useful and for what purpose
- [x] Identify opportunities for automated collection after suspected incident
- [x] Review with select app teams
- [ ] Publish

**Comment by StevenBarre** [comment]
Please also balance with the message that the logging storage is not infinite. The answer to too little logging isn't to just log everything. There's been times when teams turn on debug level logs on their production app and start using 50Gb of logs per day.

**Comment by NickCorcoran** [comment]
Currently reviewing with various app and security teams.

**Comment by mitovskaol** [comment]
@NickCorcoran Please connect with @mtspn to find the right place for this content on the Tech Doc website. Also check with him if these recommendattions should be included in the Loggin topic in Openshift 201

**Comment by NickCorcoran** [comment]
Publish to happen under another ticket
