### ISSUE TITLE
Video Demo HPA/VPA

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2584]
Record and edit a video demonstration of Horizontal and Vertical Pod Autoscaling 

Follow on from HPA/VPA demonstrations: 

**Definition of done**

- [x] Schedule meeting with Tatsuya Morikawa to record VPA/HPA Demo
- [x] Prepare question prompts for recording
- [x] Edit demonstration footage for brevity
- [x] Deliver final video, publish to youtube and include with Openshift Resources and 201 training

**Comment by tmorik** [comment]
@mtspn, FYI - The scenario for the demo steps is prepared on GitHub here: https://github.com/bcgov-c/advsol-docs/pull/207

It's still under reviewing by team mates and you are welcome to review also.

**Comment by tmorik** [comment]
The Demo steps scenario has been merged :  https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/AutoscalingDemo.md

Next step is to record a video. How do we want to proceed?

**Comment by mtspn** [comment]
Hey @tmorik, let's schedule a time to meet to record a video demonstration. I'll send you a calendar invite. I think it would be great if you can present the same material as in the recent video demonstration you made to the team, and we can record the call via Zoom. I'll prepare some questions to ask during the call at the end of your presentation, I can send you these in advance if you would like.

**Comment by tmorik** [comment]
> Hey @tmorik, let's schedule a time to meet to record a video demonstration. I'll send you a calendar invite. I think it would be great if you can present the same material as in the recent video demonstration you made to the team, and we can record the call via Zoom. I'll prepare some questions to ask during the call at the end of your presentation, I can send you these in advance if you would like.

Yes, Please send to me so that I can prepare :)

**Comment by mtspn** [comment]
Video uploaded on The Exchange youtube channel here: https://youtu.be/nZMtJRQR3jY
