### ISSUE TITLE
CCM ArgoCD - job not deleted after sync completed

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2585]
**Describe the issue**
There are several setup jobs as part of CCM roles that should be deleted on completed. Tested adding the annotations but no luck:
```
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

Reference: https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies

**Definition of done**
- [x] make it work ;P

**Comment by ShellyXueHan** [comment]
for example, acs access job: https://github.com/bcgov-c/platform-gitops-gen/blob/master/roles/rh-acs/templates/job.acs-automation-post-sync.yaml.j2

**Comment by IanKWatts** [comment]
Yes, you're missing the hook annotation.
