### ISSUE TITLE
Build an Application (new page) 

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2587]
New tech doc 'Build an Application'  

**Definition of done**

- [x] Outline Draft
- [x] Outline Review
- [x] Content First Draft
- [x] SME review
- [x] Make appropriate changes
- [x] Final Review
- [x] Approval

**Comment by mtspn** [comment]
Base on Openshift 101 instructions

**Comment by lukegonis** [comment]
@mtspn Hey Matt, @ksummersill2 is going to take a crack at this issue in consultation with you.

**Comment by mtspn** [comment]
Okay nice, @ksummersill2 there are some bullet points outlining this topic from a previous brainstorming session which can be found [here](https://github.com/bcgov/platform-developer-docs/blob/rewrite-build-deploy-and-maintain-apps/src/docs/build-deploy-and-maintain-apps/build-an-application.md)

**Comment by ksummersill2** [comment]
Not sure if I have access to push-up changes. I could pull down but not edit and push up via git.

**Comment by ksummersill2** [comment]
Pushed up outline changes to the rewrite-build-deploy-and-maintain-apps branch.

**Comment by ksummersill2** [comment]
Currently working the pages association to the outline.

**Comment by ksummersill2** [comment]
Outline completing the initial draft before submitting for Tech Doc Review.

**Comment by mtspn** [comment]
@ksummersill2 were you able to sort out your access? Can you point me to the branch you're working in so I can take a look? Or if you haven't got it somewhere else, could you please push to `rewrite-build-deploy-and-maintain-apps`

**Comment by ksummersill2** [comment]
Provided a push of content for the build app page.

**Comment by ksummersill2** [comment]
Checked in changes. Need to get information from the team for the rest of the documentation.

**Comment by mtspn** [comment]
@ksummersill2 could you please make the changes suggested in review? https://github.com/bcgov/platform-developer-docs/pull/122#pullrequestreview-1130653723

**Comment by mtspn** [comment]
Notes from team day on what should be included in this doc: 
**Build an Application** 
- Create the code for your application 
- CI/CD Pipeline (link to pipeline templates) 
- Database (link to DB Best Practices doc, mention Patroni and MongoDB images)
- Select a good base image from Artifactory 
- (link to Artifactory doc for how to pull an image through Artifactory)
- Creating your image (recommend using S2I as an easier option, if you need more control then you can make a docker file - link to external docs on how to make a dockerfile)

**Comment by Pilargit12** [comment]
**NEW branch to draft this technical document: https://github.com/bcgov/platform-developer-docs/pull/172** 


previous one:https://github.com/bcgov/platform-developer-docs/pull/122

**Comment by Pilargit12** [comment]
Published new page 
https://docs.developer.gov.bc.ca/build-an-application/
