### ISSUE TITLE
Deploy an Application (new page)

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2588]
Create new page: 
Deploy an Application 

**Definition of done**

- [x]  Outline Draft
- [x]  Outline Review
- [x]  Content First Draft
- [x]  SME review
- [x]  Make appropriate changes
- [x]  Final Review
- [x]  Approval

**Comment by mtspn** [comment]
Document outline can be found here: https://github.com/bcgov/platform-developer-docs/blob/rewrite-build-deploy-and-maintain-apps/src/docs/build-deploy-and-maintain-apps/deploy-an-application.md

**Comment by ksummersill2** [comment]
Working through the Deploy and Application documentation and will be pushing for review.

**Comment by ksummersill2** [comment]
Updating the Deploy the Application on feedback and pushing out.

**Comment by mtspn** [comment]
This page should also include information about Artifactory and Vault

**Comment by Pilargit12** [comment]
New PR 

https://github.com/bcgov/platform-developer-docs/pull/174/files

**Comment by Pilargit12** [comment]
Current review by Steven Barre and Shelly Han

**Comment by Pilargit12** [comment]
https://docs.developer.gov.bc.ca/deploy-an-application/ ✅
