### ISSUE TITLE
Four Gold Signals for App Monitoring (new page)

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2592]
Updated request on ticket: 
Billy advised this topic will be reviewed under ticket [Improve Sysdig Monitoring Documentation#4481](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4481) as creating a new document that is widely known to the community and available in multiple different sources. 

This includes updates to: 
* Set up a team in Sysdig Monitor
* Create monitoring dashboards in Sysdig Monitor
* Create alerts and notifications in Sysdig Monitor
* Set up advanced metrics in Sysdig Monitor

Initial request of Ticket: 
Create new page:
Four Gold Signals for App Monitoring
_Ping Olena to get slide decks with the content for this page_

**Definition of done**

**Comment by Pilargit12** [comment]
[Uploading... Golden Signals Demo With Sysdig Monitoring.pdf]
Obtained slidedeck, advised to contact Billy and/or Shelly for further info or questions

**Comment by Pilargit12** [comment]
Also youtube video found https://www.youtube.com/watch?v=W9xM5rd9CaQ 

Demo #11: Four Golden Signals for App Monitoring

**Comment by Pilargit12** [comment]
Ticket will be completed along with [Improve Sysdig Monitoring Documentation#4481](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4481)
