### ISSUE TITLE
STRA and PIA for Private Cloud Platform

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2598]
Create new page: 
STRA and PIA for Private Cloud Platform

**Definition of done**

- [x] First draft
- [x] SME review
- [x] Approval

**Comment by Pilargit12** [comment]
Need further context about the creation for this page or reference it?  Conversation with Nick.

**Comment by NickCorcoran** [comment]
I think this is the same as https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/2599 and could likely be closed.

**Comment by Pilargit12** [comment]
STRA and PIA Requirements for Apps needs to be updated: 

https://developer.gov.bc.ca/BC-Government-OpenShift-DevOps-Security-Considerations

**Comment by NickCorcoran** [comment]
https://github.com/bcgov/platform-developer-docs/pull/198

**Comment by Pilargit12** [comment]
Completed: https://docs.developer.gov.bc.ca/devops-security-considerations/#stra-and-pia-requirements-for-applications ✅
