### ISSUE TITLE
STRA and PIA Requirements for Apps

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2599]
Rewrite the following pages:
STRA and PIA Requirements for Apps https://developer.gov.bc.ca/BC-Government-OpenShift-DevOps-Security-Considerations
**Definition of done**

- [x] First draft
- [x] SME review
- [ ] Approval

**Comment by Pilargit12** [comment]
Need further context from SME to know exactly what to rewrite "STRA and PIA" or if a new section or page need to be written.  Talk to Nick about this

**Comment by Pilargit12** [comment]
Closing as it was determined to be the same task here: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/2598
