### ISSUE TITLE
Vulnerability Scanning with ACS (rewrite)

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2601]
Rewrite the following pages:
Vulnerability Scanning with ACS and XRay	https://developer.gov.bc.ca/Platform-Services-Security/BC-Government-Aqua-Cloud-Service-Definition

**Definition of done**

- [ ] First draft
- [ ] SME review
- [ ] Approval

**Comment by Pilargit12** [comment]
Does the current content need anything extra added, what exactly needs to be rewritten?  Please confirm and provide more context.

**Comment by Pilargit12** [comment]
Spoke with Nick C through teams today, he advised the current content is good as it is now, no need to further rewrite the content for this ticket.   Later he will create a new ticket where there will be a guide targeted for Product owners and technical leads.
