### ISSUE TITLE
Application signing for mobile development (rewrite)

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2630]
Rewrite the following pages:
Mobile development	https://docs.developer.gov.bc.ca/s/c4mifrtl1fal3c5rdpng/mobile-development/d/c4huh8a1tev0e75glulg/android-signing
Android App Signing	https://github.com/bcgov/mobile-signing-service/wiki/Android-App-Signing
Apple App Signing	https://github.com/bcgov/mobile-signing-service/wiki/Apple-App-Signing

**Definition of done**

- [ ] First draft
- [ ] SME review
- [ ] Approval

**Comment by Pilargit12** [comment]
This content's owner is Monica Granbois in DevX - is it needed in a new section for tech docs or just to link to these github repos?

**Comment by Pilargit12** [comment]
It has been re-written, contacted Monica Granbois and confirmed Oct 30, 2023 she provided this page: https://mvp.developer.gov.bc.ca/docs/default/component/mobile-developer-guide
