### ISSUE TITLE
Platform Architecture (New Page)

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#2632]
Create new page: 
Platform Architecture 

**Definition of done**

- [x] First draft
- [x] SME review
- [x] Approval

**Comment by Pilargit12** [comment]
Create new page that links to IDIR protected page: https://cloud.gov.bc.ca/private-cloud/platform-architecture-diagram/ 

Create some text that can help accessibility to read the diagram.

**Comment by Pilargit12** [comment]
https://github.com/bcgov/platform-developer-docs/pull/185

**Comment by Pilargit12** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmt1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5aab073724c533bbcf95013102fa65d45bb6359/Monosnap%20Home%20-%20Private%20Cloud%20as%20a%20Service%20Platform%20Technical%20Documentation%202023-08-23%2008-16-33.png)

⬆️ Front page update ⬆️

**Comment by Pilargit12** [comment]
@mtspn - added you to this ticket for sprint review purposes - Thank you for presenting my closed item

**Comment by mtspn** [comment]
Did anyone have the chance to review this document prior to merging? I noticed that the[Private cloud](https://https//digital.gov.bc.ca/cloud/private/) link is not working (https// is duplicated)
