### ISSUE TITLE
Decide on new audit log policy

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2640]
**Describe the issue**
As of OCP 4.9 the audit log policy can be customized to have different log levels for different groups of users. Do we want to make use of this feature?

**Additional context**
Docs [Configuring the audit log policy with custom rules](https://docs.openshift.com/container-platform/4.9/security/audit-log-policy-config.html#configuring-audit-policy-custom_audit-log-policy-config)
Epic [OCP 4.9 Testing in CLAB](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2550)

**Definition of done**
- [x] Determine if the default policy should be changed from `Default`
- [x] Determine if any groups should have custom policies
- [x] If a change is needed, create a ticket in the EPIC to implement the change during the upgrade testing

**Comment by NickCorcoran** [comment]
While I believe anything more than Default is overkill for Silver/Gold, it may be prudent for us to to test this for Emerald.  
It would be good to see the delta between
- Default
- WriteRequestBodies 
- AllRequestBodies

AllRequestBodies may be preferred for those creating/using/storing Protected C data.

**Comment by StevenBarre** [comment]
KLAB set to WriteRequestBodies now. That should capture the full yaml of CREATE, UPDATE, DELETE actions on the API, while GET, LIST, WATCH are still logged without the full payload. Give it a try and let me know if/when you want it upgraded to AllRequestBodies .

**Comment by StevenBarre** [comment]
Setting removed from KLAB and added to KLAB2

**Comment by StevenBarre** [comment]
Using AllRequestBodies for all logs seems to overwhelm the logging stack. I've got a case open with Red Hat to investigate if we can get logging stack to accept this volume of logs.

**Comment by StevenBarre** [comment]
Red Hat says

> To keep Audit logs policy other than default instead for forwarding audit logs to default Elasticeasrch, you can forward them to an external log store

> But if you want to forward logs to internal/default Elasticeasrch Audil logs policy should be default.

So it seem sthe built in EFK stack is not capable of handling the volume of logs from audit when the verbosity is turned up.
