### ISSUE TITLE
Customize the router error pages

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2641]
**Describe the issue**
The error pages returned by the router if no pods are available for a route, or if the route does not exist, can be customized as of OCP 4.9. It would be sweet if we had some BCGov themed pages instead of the generic blank ones.

Pages could also link to the platform status page.

**Additional context**
Docs [Customizing HAProxy error code response pages](https://docs.openshift.com/container-platform/4.9/networking/ingress-operator.html#nw-customize-ingress-error-pages_configuring-ingress)

**Definition of done**
- [ ] Design new HTML pages
- [ ] Create CCM PR to implement the changes

**Comment by okanji** [comment]
We can re-use this in the registry. The registry has an error page but it is not branded.
