### ISSUE TITLE
Send email to Product Teams about the upcoming API Deprecation

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2643]
**Describe the issue**
Use the Mautic service to send an email to product teams announcing the API Deprecation that will be coming in OCP 4.9 upgrade.

**Additional context**
https://github.com/BCDevOps/platform-services-status-page-notifications/blob/master/notifications/Upgrading-OCP49-API.md

**Definition of done**
Email sent out

**Comment by mitovskaol** [comment]
The email has been sent on May 11.
