### ISSUE TITLE
Run Kraken before and after OCP 4.9 upgrade

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2646]
**Describe the issue**
Run Kraken before and then after the OCP 4.9 upgrade and compare the results.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Kraken.md

**Definition of done**
- No change in cluster stability after upgrade

**Comment by tbaker1313** [comment]
Kraken run before and after upgrade - no change, so this test is successful.
