### ISSUE TITLE
Document the process for planned and unplanned failovers for RocketChat

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2650]
**Describe the issue**
Develop a plan for the management of Rocketchat failovers from Gold to GoldDR and vice versa, whether the failover is planned or unplanned.

**Additional context**
Current setup:
- GSLB is in place.  Failure on the Gold side, for whatever reason, causes requests to be automatically directed to GoldDR.
- Gold and GoldDR installations are identical.
- Mongo DB in GoldDR is not updated in real time.  A cron job in GoldDR takes the latest daily Mongo DB backup from Gold and updates the GoldDR DB, so at any point in time GoldDR is up to date within one day of Gold.
- When service is restored in Gold, traffic will automatically be redirected back to the application in that cluster without a Mongo dump/restore from GoldDR to Gold.
The daily import into DR starts at 6:30pm and takes about 10 minutes to complete.
In the current configuration, the same would happen in Gold if Rocketchat were running in DR at 6:30pm. There is a script that runs in each cluster, checks the cluster status (active or passive) and if it is the passive cluster it will restore the DB using the most recent backup from the active cluster.

**Definition of done**
- [x] A plan has been agreed upon
- [x] The plan is documented and includes a description of replication in different scenarios - Gold/active and GoldDR/passive and the other way around

**Comment by IanKWatts** [comment]
Meeting to discuss this has been pushed to May 31, so completion of follow-up details, like a diagram and doc, will likely spill over into the next sprint.

**Comment by mitovskaol** [comment]
@IanKWatts Please document the failover plan in https://github.com/bcgov-c/platform-services-docs/
