### ISSUE TITLE
Devhub Issue: User access into Github or Openshift [short description here]

### ISSUE THREAD

**Issue by rarmitag** [BCDevOps/developer-experience#2656]
> path: (do not delete) https://github.com/BCDevOps/developer-experience/blob/master/docs/UserAccessToOrg.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue

Could you please give Mihai Dinu access to openshift.  
His github id is: mdinu1961
His email is: Mihai.Dinu@gov.bc.ca

He is a BA with Registries that requires access to our databases located in openshift.

Thanks,

Rich

**Comment by ozamani9gh** [comment]
@rarmitag This has not been done yet.   Can someone contact me at omid.x.zamani@gov.bc.ca to let me know status of this request.   its been over 7 days
