### ISSUE TITLE
Devhub Issue: User access into Github or Openshift [short description here]

### ISSUE THREAD

**Issue by ozamani9gh** [BCDevOps/developer-experience#2664]
> path: (do not delete) https://github.com/BCDevOps/developer-experience/blob/master/docs/UserAccessToOrg.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue
Could you please give Sarah Elzinga access to Openshift
Her github id is:  sarahelz19
Her email is: sarah.elzinga@gov.bc.ca

She is a BA with Registries that requires access to our databases located in openshift

**Comment by ShellyXueHan** [comment]
Hello, please read through the doc and use https://just-ask.developer.gov.bc.ca/ to invite users to BCGov GtiHub organizations for OpenShift acces.
