### ISSUE TITLE
Finalize the MVP List of Kraken Use Cases

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2684]
Paltform Ops Team needs to be able to test the ability of Openshift to self-heal and recover from various issues. Kraken is a chaos engineering tool intentionally disrupts different services  within an Openshift cluster and monitors if the system can recover.

We need to have a list of use cases that test critical Openshift services. Kraken will attempt to disrupt thes services and Openshift is supposed to self-heal from these disruptions. 

DoD
- [ ] the MVP list of disruptions documented in this ticket.

Additional context:

Just a suggestion that we can start making the list by looking at the critical Openshift services that are currently monitored by Cerberus (full list of metrics can be found in [this repo](https://github.com/BCDevOps/platform-services/tree/master/monitoring/cerberus):
- monitoring on the 5 major cluster services identified in [Miro board](https://miro.com/app/board/o9J_kgyjm_k=/)
- image registry / Artifactory
- ingress service
- API service
- worker nodes
- NetApp storage (Trident backend)

**Comment by StevenBarre** [comment]
Abandoning kraken. Will discuss chaos eng with Red Hat.
