### ISSUE TITLE
Create content and tagging strategy for stackoverflow

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2686]
**Description**
We need to figure out how different types of content can be used in stackoverflow and how the tags should be used.

**More information**
There are articles, questions and answers, and collections. We need to know when to use each type.
We can put in a lot of tags, but we need to figure out which tags we want to put in.

**Definition of done**
- [x] Learn about the different types of content in OS
- [x] Learn about tagging in OS
- [x] Create a plan for the content and tagging
- [ ] Review with team (Nick, Shelly, Cailey, and Steven) - ask about their experiences in SO
- [ ] Finalize

**Comment by theresawuzhere** [comment]
@mitovskaol For a review meeting to see how the StackOverflow POV went, I'm going to invite Cailey, Shelley, and Nick. Is there anyone else I should invite?

**Comment by mitovskaol** [comment]
@theresawuzhere  + Justin H

**Comment by theresawuzhere** [comment]
strategy doc: https://docs.google.com/document/d/1qT_HdRtxqWBVXj9btXBn0ECISI-ryCn9vsHcuza__u0/edit#
tagging sheet: https://docs.google.com/spreadsheets/d/1wrsUmNThGXg3XrIwm673HJwxuRPlpXMnS61weEQqJPw/edit#gid=1904840399
