### ISSUE TITLE
Allow updates for pod limit

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2692]
**Describe the issue**
The maximum number of pods allowed in a namespace is currently not adjustable.  It is hard-coded in the ResourceQuota `compute-long-running-quota`.  The other resources in this ResourceQuota can be configured via the registry app - those are the limits for CPU and memory for the namespace.

Allow the pod limit to be set, similar to how CPU and memory limits may be set via the registry.

**Additional context**
This will require a small change to the registry database and API.

**Definition of done**
- [ ] Registry DB has been updated to accommodate this feature
- [ ] Registry API has been updated
- [ ] Registry UI has been updated
- [ ] ResourceQuota template file is updated
- [ ] Feature has been tested in KLAB
- [ ] Feature has been merged into CCM main branch for rollout

**Comment by IanKWatts** [comment]
@StevenBarre Shall I close this ticket.  We had one user that was hitting the limit and it hasn't come up again in over a year, so I'm thinking this feature is not worth the effort.

**Comment by StevenBarre** [comment]
Sounds good to me.
