### ISSUE TITLE
Document database backup strategy for WordPress sites

### ISSUE THREAD

**Issue by ty2k** [BCDevOps/developer-experience#2699]
With our Private Cloud PaaS test WordPress site having new content added to it over time, we need a strategy for backing this data up.

This site is provided to us as a service by the GDX Engagement team, who will ultimately be responsible for this.

Check with Steven Barre to look at what might already be in place for data backups on the existing site's namespace.

Check with the GDX Engagement team (Shawn Turple) to see what their strategy is for data backups in the OpenShift environment. Provide recommendations based on Steven's findings in the namespace.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [ ] Database backup plan is outlined in this ticket

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
