### ISSUE TITLE
2020 Q1 Patching

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#270]
https://trello.com/c/U2J9jFz9/156-2020-q1-patching

Unless the change is trivial (rare), we put a week between LAB and PROD upgrades for OCP and OCS.

Expected version of OCP: 3.11.?? (waiting new errata to release with version info)
Expected version of OCS: 3.11.5

- Jan 20-24 RFC189788 LAB OCP (done)
- Feb 10-14 RFC188204 LAB OS (done)

- Mar 14-20 RFC190949 PROD OS (in progress)
- Mar 18-20 RFC190793 LAB OCS (todo)

- TBA – (uncreated RFC for new LAB OCP – will create when latest errata drops)
- TBA - RFC190948 PROD OCS (todo)
- TBA - RFC190946 PROD OCP (todo)

**Comment by tbaker1313** [comment]
This has been completed. Rescheduling new OS Patching for 2020 Q2
