### ISSUE TITLE
Vault Terraform - upgrade

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2707]
**Describe the issue**
`Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512`

**Definition of done**
- [ ] upgrade in lab and test
- [ ] upgrade in prod

**Comment by ShellyXueHan** [comment]
We started to get some frequent but inconsistent failure from terraform runs that failed with:
```
0s
Run innovationnorway/setup-vault@v1
  with:
    version: ~1.6
  env:
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/035eee5e-6bee-4111-9b92-47c2923673ca
Error: unsupported media type requested, only [application/vnd+hashicorp.releases-api.v0+json application/vnd+hashicorp.releases-api.v1+json] are available
```

The package has been archived too (https://github.com/innovationnorway/setup-vault) so we should upgrade to use something else.

**Comment by IanKWatts** [comment]
@ShellyXueHan I'm not seeing these errors in recent workflows.  Do you know if this is still an issue?

**Comment by ShellyXueHan** [comment]
haven't had them for a while now. But it used to happen around once a month, the error message will only show during that time. We will need to update the model used anyway since it's been archived and pretty outdated.

**Comment by ShellyXueHan** [comment]
github workflows updated already
