### ISSUE TITLE
Storage: Object store integration

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#271]
https://trello.com/c/RWUKUabp/136-storage-object-store-integration

Plan the implementation of the BCGov hosting services object store within the platform.

**Comment by caggles** [comment]
We have the access necessary, but it happened by adding users manually instead of using the IDIR group. We may wish to open another ticket later about updating access from individual users to the IDIR group.

**Comment by jefkel** [comment]
Our URL:
https://citz-dev-exchange.objectstore.gov.bc.ca

The following details have come out from the meeting with the storage team:
Object Store Namespace Name: CITZ-Dev-Exchange
- encryption at rest disabled by default
- data available during outage (small possibility of stale data during outage)
- no default compliance or enforcement set at namespace (recommend leaving off for bucket creation as this can be a trigger for teams to move to their own object store)
- AD Group to be used as owner/admin : CITZ-Dev-Exchange-obj-admins - members: Luke, Todd (Shelly, Cailey ?)

Technical Notes:
- Internal (non-S3) administration functions are NOT available via DMZ as this API/interface is hosted in Zone B
- S3 API is available on public HTTPS access, need to confirm/verify that is enough access for automation tooling.
- ~1000 buckets per namespace (no storage size limitations). This is a recommended maximum from the vendor. Can make additional namespaces if required? or gate # of buckets we can provision per team?
