### ISSUE TITLE
Setup Vault Injector on KLAB2

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2732]
**Describe the issue**
As part of testing the NSX environment we need to install the Vault Agent into KLAB2 and confirm it works correctly.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Test pod in KLAB2 can access a vault secret.

**Comment by ShellyXueHan** [comment]
### update:

- argocd not yet working on klab2, so i manually installed the namespace and vault injector
- was able to setup vault auth from vault server from klab for klab2 injector
- also setup a test deployment, but getting error with the init container to authenticate:
```
2022-08-25T23:49:01.005Z [INFO]  auth.handler: authenticating
2022-08-25T23:50:01.008Z [ERROR] auth.handler: error authenticating: error="context deadline exceeded" backoff=35.35s
```
@StevenBarre I'm not sure if this is about the network policy or related to the network setting on klab2. I would need to double check again next week (i'm flexing this Friday).

**Comment by StevenBarre** [comment]
I'm on vacation next week. William is also on flex Monday. Not sure where your test deployment is so I can't check its netpols. But Egress netpol is now enforced too. So you may need a netpol in the test deployment allowing egress of the init container TO the injector.

Draft PR of dev docs here https://github.com/bcgov/platform-developer-docs/pull/111/files

**Comment by ShellyXueHan** [comment]
### Update:

we've installed vault injector and verified it's working with a test deployment. Waiting for klab2 rebuild and do the final install/

**Comment by ShellyXueHan** [comment]
### Update:

started installing vault injector yesterday as klab2 is up. using argocd this time, we we were having some issue setting up the ssh key for argocd to read from an enterprise repo. Ian is investigating on this.

**Comment by ShellyXueHan** [comment]
### Updates:
- created test vault project set in klab2
- Steven has added network rule to allow user project set to talk to vault server in the other cluster
- waiting for registry and argocd-shared to be ready to wrap up the testing setup
- created separate ticket to look into high dataclass use case: #3088

**Comment by ShellyXueHan** [comment]
all set, the only thing left is for Ian to add the vault testing deployment app to argocd-shared namespace in emerald!

**Comment by ShellyXueHan** [comment]
### Update:

Waiting for ArgoCD-shared to get ready in emerald cluster to sync up.
