### ISSUE TITLE
Switch docker storage to overlay2

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#274]
https://trello.com/c/krHq8ylx/173-switch-docker-storage-to-overlay2

With the expectation of running our OCP 3 cluster for at least the next 6 months, we should plan to migrate our docker storage to overlay2 (will hopefully help with other issues as well.)

**Comment by sbarre-esit** [comment]
William is on Vaca May 11-24, will resume work upon return.

**Comment by wmhutchison** [comment]
[https://app.zenhub.com/files/220104031/c777821a-b462-419d-986c-90cd928f2d52/download](https://app.zenhub.com/files/220104031/c777821a-b462-419d-986c-90cd928f2d52/download)

Initial draft of RFC methodology that will first need to be tested in LAB, and then PROD.

**Comment by sbarre-esit** [comment]
@mitovskaol I purpose we add overlay2fs to just the App nodes first, as that's where we see the most pain. We can do the rest of the nodes during OS patching to reduce the number of times we need to poke at gluster/elasticsearch.

We can do the Lab Wednesday May 13 and PROD May 19-22.

We'll include in the RFC fixing the iscsid conf issue that impacts the netapp block volumes as well.

Does this plan work for you and the users?

**Comment by mitovskaol** [comment]
Sounds good @sbarre-esit Please post the notice in the alerts channel as soon as possible. Thank you!

**Comment by sbarre-esit** [comment]
LAB app nodes changed over. RFC created for PROD.

When we do OS patching @tbaker1313 we'll need to upgrade the master/infra/storage nodes as well. I just wanted to avoid CNS/ES restarts for now as this is mostly an improvement for the app nodes.

**Comment by sbarre-esit** [comment]
PROD App nodes in progress

**Comment by sbarre-esit** [comment]
Waiting on #467 to complete the rest of the nodes.

**Comment by mitovskaol** [comment]
Scheduled for execution on Sat June 13.
