### ISSUE TITLE
Tech Docs HTML sitemap

### ISSUE THREAD

**Issue by ty2k** [BCDevOps/developer-experience#2749]
Following #2748, create an HTML sitemap that displays the full site structure in a visually hierarchical format with links to each page, especially child/leaf node pages. This will serve as a human-readable table of contents compared to the machine-readable XML sitemap, which serves as a table of contents for search crawlers.

**Additional context**
This HTML sitemap benefits both human users and search engines. The HTML Sitemap acts as a full-site table of contents for human users who want to see the entire site structure at once. It also facilitates incoming links to child pages that don't appear directly in the left-hand navigation menu. Without this, child/leaf node pages will only be linked to from their parent landing pages. Search crawlers use the number of internal links pointing to a page on a site as a metric for how important that page is in the site's information architecture. Less incoming links indicate a page is less important. See [HTML Sitemaps at SEMRush](https://www.semrush.com/blog/html-sitemap/) for additional background on the value of HTML sitemaps.

**Definition of done**
- [ ] HTML sitemap page shows a hierarchical table of contents that allows a user to visit any page in the website with a click
- [ ] HTML sitemap page is linked to in the site footer or another spot that appears on every page on the site

**Comment by lukegonis** [comment]
Closing this issue as it is no longer relevant
