### ISSUE TITLE
Update assets in theHUB with new contact details

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2756]
**Describe the issue**
Update all the Config Items in theHUB to have Olena as the owner instead of Justin.

Do any other cleanup needed while you are in there.

**Additional context**

**Definition of done**
All asset records for MCS in theHUB are accurate

**Comment by tbaker1313** [comment]
This should be mostly completed. Need to update a few more records.

**Comment by tbaker1313** [comment]
Records updated and a few other records corrected as needed - mostly the storage Netapp ones are all now the same owner and technical contacts.
