### ISSUE TITLE
INC0067026 - Degraded network connectivity with MCS-SILVER-MASTER-03.DMZ and MCS-SILVER-MASTER-02.DMZ

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2763]
**Describe the issue**
Recently during the course of the OCP upgrade of SILVER to 4.9, one of the master nodes showed unusual errors on the server console after receiving firmware upgrades. Further investigation revealed that one of the dual-port NIC cards is no longer responding, thus resulting in a loss of redundancy for network connectivity for the affected node. Steps will be taken to open a vendor case on the matter, feed them diagnostic data supporting the issue seen, and have a replacement part along with technician dispatched to the data centre so we can restore network redundancy for the affected master node (MCS-SILVER-MASTER-03.DMZ).

UPDATE: Vendor support disagrees that the that NIC in question is non-functional, but instead just needs to be downgraded regarding its firmware first. Will attempt to do so if potential risk involving the node's overally stability can ensure we only target the affected NIC.

UPDATE 2: Our (Platform Operations) team has performed a full QA to determine if there are any other servers to be concerned about. This resulted in the discovery of MCS-MASTER-02.DMZ also having NIC problems. One of the APP nodes  also has some unusual results (APP-28) but that appears to be more of a configuration issue and will be handled/treated as such (drain the APP node, fix the config issue, uncordon).

**Definition of done**
- [x] Open vendor case ticket.
- [x] Feed relevant data to the case and follow vendor instructions.
- [x] Continue working with vendor support for both cases and follow instructions as needed. Once concrete instructions are formed for proper resolution, checkboxes will be created to track them.

**Comment by wmhutchison** [comment]
Added MCS-SILVER-MASTER-02.DMZ to the list after a general node QA revealed that it also had a NIC in an unavailable state. A separate vendor case was opened and the decision quickly reached to send a replacement. This is expected to arrive and be replaced sometime tomorrow.

**Comment by wmhutchison** [comment]
The vendor case for MCS-SILVER-MASTER-03.DMZ is ongoing. Vendor support feels the NIC is not in fact non-functional but instead just needs to have its firmware downgraded. Am pushing for case escalation after not receiving further updates after almost 24 hours.

**Comment by wmhutchison** [comment]
the following two updates will combine updates placed in the INC ticket. One per each master node.

**Comment by wmhutchison** [comment]
Latest updates for MCS-SILVER-MASTER-02.DMZ:
- vendor support dispatched a technician along with replacement NIC to the data centre, and the NIC was replaced.
- instability for the entire server took place along with critical ILOM errors afterward to the point where the server hard-reset itself. No impact to the cluster because the server in question was drained of all workloads.
- MCS team was able to apply new firmware updates to the replacement NIC, which did satisfy the status of the NIC in ILOM (now listed as Good, was previously Unknown).
- ILOM still however is generating critical errors involving the NIC card in question. Due to concerns of stability, the node in question remains not in use, meaning the cluster is now in a degraded state for master nodes.
- vendor case updated and waiting for next-steps to resolve this, whether that involved additional technical steps or them shippping a new mainboard.
- NIC was replaced. Critical errrors  from ILOM regarding the NIC, and the server crashed a short period of time after reboot.
- Replacement NIC had its firmware updated. Still receivin critical errors from ILOM regarding the NIC. No crash noted, but the critical errors are of concern.
- Brought the matter to HPE Support's attention, uploaded the latest ILOM data dump, and awaiting their next instructions.
- Followed up with DCM to have them remove the new NIC so we can see if that stabilizes the ILOM alerts. It did, which is good to know since we can confidently run that server with reduced network redundancy over being potentially unstable due to the new NIC.
- Will see what HPE Support does, since the next part they may have us replace would involve the entire mainboard for the server, unless their finding is that the replacement NIC happened to be bad.

**Comment by wmhutchison** [comment]
Latest updates for MCS-SILVER-MASTER-03.DMZ:
- still pursing case escalation due to no response from HPE support in almost two days.
- priority on escalation now shifted due to new findings from work performed on MCS-SILVER-MASTER-02.DMZ. We cannot touch MCS-SILVER-MASTER-03.DMZ until MCS-SILVER-MASTER-02.DMZ is confirmed 100% to be stable again.
- received follow-up communication from HPE support. They agreed to our assessment and will no longer pursue a firmware downgrade attempt and instead ship replacement NIC card.
- due to the current state of MCS-SILVER-MASTER-02.DMZ, we requested any further action be put on hold until further notice. While having degraded network connectivity, MCS-SILVER-MASTER-03.DMZ is otherwise fully functional, where as the state of MCS-SILVER-MASTER-02.DMZ has degraded in terms of server instability when making use of the replacement NIC.

**Comment by wmhutchison** [comment]
Current state for each SILVER MASTER node.
- MCS-SILVER-MASTER-01.DMZ: Stable, no issues with hardware/firmware.
- MCS-SILVER-MASTER-02.DMZ: Stable, albiet reduced redundancy for network. Only possible due to removing replacement NIC.
- MCS-SILVER-MASTER-03.DMZ: Stable, albiet reduced redundancy for network. Remains stable with original failed NIC in place. Not touching this one at all until we're fully rsolved with MCS-SILVER-MASTER-02.DMZ.

**Comment by StevenBarre** [comment]
Changing the estimate to a much higher number as this is taking a lot of time from multiple people and will be impacting our sprint deliverables.

**Comment by tbaker1313** [comment]
Today we started with an appointment for the morning of June 17th to fix this issues with a system board and a new NIC replacement. However the service tech started a new appointment for June 16th @ 1400 - the tech did not show up. Have requested a new appointment from the HPE dispatch team for tomorrow morning.

**Comment by tbaker1313** [comment]
New appointment for June 17th (today) @1000 - still awaiting technician for system board and NIC replacement.

**Comment by tbaker1313** [comment]
Hardware replacement is underway.

**Comment by tbaker1313** [comment]
Hardware fixed in MCS-SILVER-MASTER-02.dmz This has restored the network redundancy. At this time we are going to let the node run for at least the weekend before doing any further work on it. The next node to be addressed will be MCS-SILVER-MASTER-03.dmz which also probably needs at least a new network card.

**Comment by tbaker1313** [comment]
Created CHG0038441 to implement the fix for MCS-SILVER-MASTER-03.dmz between June 20 and June 22. The process will only take a few hours but due to the HPE dispatch/scheduling system it's not easy to predict when we can get a tech to visit the data center.

**Comment by tbaker1313** [comment]
Sent in request to HPE support for a service appointment. Haven't heard back yet - have requested June 21 in the AM.

**Comment by tbaker1313** [comment]
Received confirmation from HPE tech (Doug) that he will be attending Kam DC for this repair June 22nd @ 0900.

**Comment by tbaker1313** [comment]
NIC replaced and network redundancy restored on MCS-SILVER-MASTER-03.dmz

**Comment by tbaker1313** [comment]
Closing ticket, issue has been resolved.
