### ISSUE TITLE
Document and Implement A general node QA check playbook or script

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#2766]
**Describe the issue**
Occassionaly the Platform Operations team comes across an issue on a node that probably does not need active monitoring, but instead should be checked both after a new node is first built and after any maintenance activities that impact the node (OCP upgrades, firmware updates, etc).

This task will capture all of the things we should be checking for on each Openshift node, and then both document them so we can ensure they are being done until automation is built, and then of course, automate it since SILVER is a big cluster.

**Proposed Check-list**
- [x] Check to see if systemd has any failed services similar to what is shown on login.
- [x] Check to make sure all network interfaces are properly configured and bond0/1 working if multiple NICs are configured.
- [x] Check to make sure DNS resolvers function on the host.
- [x] Check to make sure the node can reach the Internet.
~- [ ] Check ILO settings for things like email alerts and the virtual nic (should be disabled.)~
~- [ ] Ensure current ILOM credentials still work to access ILO web console and/or SSH.~

**Definition of done**
- [x] Document both here in this ticket and in advsol-docs the initial check-list.
- [x] Work on automation for implementing the involved checks so that large clusters can be quickly checked.
- [ ] Document the use of automation for checking once available and ready.

**Comment by tbaker1313** [comment]
Started making a playbook to test some of these things. Some of the ILO/iDRAC checks will require a little more effort due to them being on a different vlan and not readily accessible.

**Comment by tbaker1313** [comment]
Working on a good way to enumerate the network interfaces and check the different configurations for virtuals/physicals.

**Comment by tbaker1313** [comment]
Moving the ILO/iDRAC part to another ticket as it'll be a bit trickier.

**Comment by tbaker1313** [comment]
Still needs some work, added new PR and created a new ticket for refinements and documentation.
