### ISSUE TITLE
Artifactory Project admin cannot share repositories

### ISSUE THREAD

**Issue by bolyachevets** [BCDevOps/developer-experience#2767]
**Describe the issue**
Artifactory Project admin cannot share repository.

**Additional context**
As described here: https://www.jfrog.com/confluence/display/JFROG/Managing+Projects
Repositories can be shared by project admins:
<img width="1512" alt="Screen Shot 2022-06-14 at 2 32 29 PM" src="https://user-images.githubusercontent.com/22973013/173692915-e784b8ca-e156-4aab-84d4-fc5bf5650e49.png">

Currently, "share" option is not available:
<img width="1512" alt="Screen Shot 2022-06-14 at 2 20 17 PM" src="https://user-images.githubusercontent.com/22973013/173693034-ceeedb92-255f-441e-855c-437c4a68f2e6.png">

**Definition of done**
Project Admins should be able to share repositories outside of projects.

**Comment by caggles** [comment]
JFrog has indicated to me that this is intentional and they do not have plans to change it. We can further discuss how to proceed if this is a blocker for your team.
