### ISSUE TITLE
Change links in the header

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2768]
**Describe the issue**
During the user content testing, we found that users had a hard time understanding the links for "Silver", "Gold" and "Register your project" in the header of the Wordpress site. We would like to: 
- Change to Silver to "Log in to Silver" 
- Change Gold to "Log in to Gold"
- Remove Register option

**Additional context**
None

**Definition of done**
- [x] Changed to Silver to "Log in to Silver" 
- [x] Changed Gold to "Log in to Gold"
- [x] Removed Register option

**Comment by ty2k** [comment]
I've made the changes on the [Private Cloud PaaS dev site](https://platform-services-dev.apps.silver.devops.gov.bc.ca/):

![Screenshot of Private Cloud PaaS site](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/7784f727-4b87-4718-ada8-2d44995fb1d7)
