### ISSUE TITLE
Reformat the Alert on the Home page

### ISSUE THREAD

**Issue by theresawuzhere** [BCDevOps/developer-experience#2769]
**Describe the issue**
During the user testing, the Alert was too prominent on the site and undue panicked new users. We'd like to change the formatting.

**Additional context**
This is the way it currently looks.
![image.png](https://images.zenhubusercontent.com/619e7c0917f0b96bbcf6d42f/54196eb9-e8fc-4d22-9826-e1023a81cdb4)

We'd like to calm it down to this.
![image.png](https://images.zenhubusercontent.com/619e7c0917f0b96bbcf6d42f/7a8e103b-9b8f-479c-b270-9c61a77ff833)

**Definition of done**

- [ ] Remove exclamation mark icon. 
- [ ] Remove the light yellow background
- [ ] Make the text black and not bold (the normal paragraph style) instead of dark yellow bold.

**Comment by ty2k** [comment]
I've removed the [custom code block](https://github.com/bcgov/platform-services-wordpress/blob/main/src/alert-banner.html) that was generating the [BC Gov Design System style alert banner](https://developer.gov.bc.ca/Design-System/Alert-Banners). In its place, I've added a standard WordPress paragraph block with the same text and link:

![Screenshot of Private Cloud PaaS dev site](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/53414ab2-b7fe-4dcd-959b-f73eb89504cc)
