### ISSUE TITLE
Create 10 project sets in Silver for Openshift 201 students

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2772]
Openshift 201 students will be temporarily assigned a project set in Silver cluster where they can work on the lab.

DoD:
- [x] 10 new project sets need to be created in Silver via [the Registry](https://registry.developer.gov.bc.ca/)  with the PO: Olena Mitovska (GitHub ID mitovskaol) and Tech Lead - Matt Spencer. Leave the second TL blank , you will populate it with a student name and GitHub ID prior to each Openshift 201 training. 
Please use the following naming convention for these project sets: Openshift 201 Test Project 1, Openshift 201 Test Project 2, ... , Openshift 201 Test Project 10.
- [ ] document in this ticket an approach for cleaning up namespaces after each students so that the next student can start with a clean project set.

The following CLI commands can be used:
Training project clean up (TO BE REPEATED BEFORE EACH Openshift 201 LAB) : 
Step 1: `oc -n license-1 delete --all all,secret,configmap,pvc`
Step 2: delete previous student’s rolebinding
Step 3: create admin rolebinding for the new student
Step 4: restore to default networkpolicies

**Comment by mitovskaol** [comment]
The projects have been created.

**Comment by mtspn** [comment]
@w8896699 this ticket has the description of what is involved in cleaning up a 201 namespace
