### ISSUE TITLE
Security Tool Adoption Stats

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2773]
Platform Services Team would like to understand the level of adoption for the security tools on the Platform: Artifactory, Vault and Sysdig. This information will help us identify if more effort should be put into increeasing the adoption via advertizing, more documentation and/or training. It will also help us plan next round of license renewal for the tools where licenses are issues on a per user basis.

DoD:
- [x] Document in this ticket how many apps in Silver and Gold use -  Artifactory, Sysdig and Vault and ArgoCD services.

**Comment by NickCorcoran** [comment]
Collected in documented in Community Meetup deck and provided to Olena.
