### ISSUE TITLE
Automate responsive log curating

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#278]
https://trello.com/c/kyePef9U/141-automate-responsive-log-curating

**Problem:**
Log curation/pruning is not flexible based on storage available and requires manual intervention when an increase of logs can fill the storage, or a decrease in logs does not automatically allow an increase in # of days retained.

**Outcome: What is the level of effort for the following?**

Add additional functionality to our logging monitoring to manage the # of days retained in the log curator configuration so that:
- when %free after a prune is less than Configured_Min_Free, continue to prune to ensure enough storage is available for the days logs.
- when %free after a prune is greater than CONFIGURED_MAX_FREE, adjust next prune to keep more logs (or prune less)
- Alert for manual investigation when # days retained drops below a specific threshold

**Comment by sbarre-esit** [comment]
I'm still not convinced this is worth the effort. Would be interested to hear from @mitovskaol how much logs we should be retaining for Kibana and if we should be putting effort towards this.

**Comment by mitovskaol** [comment]
@NickCorcoran Assigning this to you to lead since you are already looking into determining the log capture and retention policies for the Platform

**Comment by lukegonis** [comment]
No longer relevant, as log curating in ocp4 is different
