### ISSUE TITLE
GitHub Enterprise repo migration - 1

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2786]
Migrate these to new enterprise (https://github.com/enterprises/bcgov-ent/):

- [x] https://github.com/bcgov-platform-services/acs-automation (Shelly)
- [x] https://github.com/bcgov-platform-services/platform-gitops-vault (Shelly)

Also some other repos:
- [x] https://github.com/BCDevOps/platform-services/tree/master/monitoring/cerberus
- [x] https://github.com/BCDevOps/platform-services/tree/master/monitoring/uptime

- [x] look into GitHub CLI for enterprise features - not worth it, just setup two git host locally instead

**Comment by ShellyXueHan** [comment]
### Update:
- Sysdig: https://github.com/bcgov/platform-services-sysdig
- Cerberus: https://github.com/bcgov/platform-services-cerberus
- uptime.com: https://github.com/bcgov/platform-services-uptime

@NickCorcoran sorry I didn't see your comment in the first line about using the enterprise Github org! so I migrated the above services to `bcgov` public repos. Is that okay? They do not contain any sensitive information.

I will move `vault` repo to the enterprise org for sure as it needs to be private.

But I also wonder if `acs-automation` needs to be in the enterprise org? It's got no sensitive info there either. Or is the purpose of the migration basically to move all our repos to the enterprise org? if so I'll move move them again...

**Comment by ShellyXueHan** [comment]
### Update:

I'm waiting for Justin P to add some manifest back to vault repo. Will not move it till that's done!

**Comment by ShellyXueHan** [comment]
### Update:
currently waiting for a new RoboWitness user created in enterprise github org.

**Comment by NickCorcoran** [comment]
I have IDIR service accounts, but waiting for ADMS to enable sync to Azure AD for them to work.

**Comment by ShellyXueHan** [comment]
### update:
account ready, back to action!

**Comment by ShellyXueHan** [comment]
done! Argocd reference updates as well!
