### ISSUE TITLE
GitHub Enterprise repo migration - 2

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2787]
Migrate these to new enterprise (https://github.com/enterprises/bcgov-ent/):

- [x] https://github.com/bcgov-platform-services/benny-operator (Ian)
- [x] https://github.com/bcgov-platform-services/warden-operator (Ian)
- [x] https://github.com/bcgov-platform-services/github-sandbox (Ian)
- [x] https://github.com/bcgov-platform-services/platform-gitops-container (Ian)
- [x] https://github.com/bcgov-platform-services/platform-gitops-calgary-clab-namespaces (Ian)
- [x] https://github.com/bcgov-platform-services/platform-gitops-kamloops-klab-namespaces (Ian)
- [x] https://github.com/bcgov-platform-services/platform-gitops-kamloops-silver-namespaces (Ian)
- [x] https://github.com/bcgov-platform-services/platform-gitops-kamloops-gold-namespaces (Ian)
- [x] https://github.com/bcgov-platform-services/platform-gitops-calgary-golddr-namespaces (Ian)

Add these repos to the GitHub backup setup.

**Comment by IanKWatts** [comment]
@NickCorcoran I have prepared a migration plan for the "namespaces" repos, but I don't seem to have access to the bcgov-ent org yet.  The first four repos in the list in the description will be easy to migrate.

**Comment by IanKWatts** [comment]
github-sandbox is not used and will not be migrated.

**Comment by IanKWatts** [comment]
Migration complete and all necessary provisioner updates made.  Just need to do a bit more testing to verify things like the registry API callback.

**Comment by IanKWatts** [comment]
Migration complete and all necessary provisioner updates made.
Project updates are working and registry API callbacks, too.
Project deletion is working.
All Argo CD instances can connect to the new repos.
