### ISSUE TITLE
Mautic Admin URL update

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2790]
**Describe the issue**

**Definition of done**
- [x] change `https://mautic-de0974-prod.apps.silver.devops.gov.bc.ca/ ` to `https://admin-subscribe.developer.gov.bc.ca`
- [x] install the wildcard tls cert
- [x] testing

**Comment by w8896699** [comment]
https://admin-subscribe.developer.gov.bc.ca/s/login is available now.
