### ISSUE TITLE
Moving RH build entitlement check script & Benny operator from Klab to Silver 

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#2798]
**Describe the issue**
Currently, RH build entitlement certificates are received by the Klab utility server and applied to the Klab cluster for application to other clusters; since Klab is a development/testing environment, it is appropriate to start with a production server/cluster such as the Silver cluster.      

**Additional context**
- https://github.com/bcgov-c/platform-ops/tree/main/tools/build-entitlement-monitor
- https://github.com/bcgov-c/platform-gitops-gen/tree/master/roles/benny-operator

**Definition of done**
- [x] Move RH entitlement certificate update from Klab util / cluster to Silver util / cluster
- [x] Set up entitlement check script and cronjob on Silver util and use openshift-bcgov-entitlements in Silver cluster
- [x] Set up Benny operator accordingly (use Silver instead of Klab )
- [x] Documenting

**Comment by tmorik** [comment]
RH Case open to get a prpper way to migrate: 

[Case #03290408](https://access.redhat.com/support/cases/#/case/03290408)

**Comment by tmorik** [comment]
RH confirmed the migration steps, they are...; 

1. Register Silver util server (mcs-silver-util.dmz).
2. Set up entitlement checker script and make sure /etc/pki/entitlement has certs from RH.
3. Set up Benny in Silver
4. Un-register entitlement for KLAB util server (mcs-klab-util.dmz).

**Comment by tmorik** [comment]
- The `mcs-silver-util.dmz` server is registered to Redhat so that it has now RH build entitlement cert in the `/etc/pki/entitlement` directory.
-  The benny operator will be updated by the CCM on August 23, Tuesday by [`Update benny source cluster #511`](https://github.com/bcgov-c/platform-gitops-gen/pull/511)
- After the CCM push for the benny operator, MCS needs to adjust cron jobs on the SILVER util server and the KLAB util server.

**Comment by tmorik** [comment]
### Cron job set up for `buildEntitlementFileChk.sh`

1 On the `mcs-klab-util.dmz` server, Stop the cron job for `/usr/local/bin/buildEntitlementFileChk.sh` as follow;

```
sudo vi /etc/cron.d/buildEntitlementChk

//comment out this job (or you can remove the job)
#55 * * * * root /usr/local/bin/buildEntitlementFileChk.sh >> /var/log/buildEntitlementFileChk.log 2>&1
```

2 On the `mcs-silver-util.dmz` server, Set up a cron job for `/usr/local/bin/buildEntitlementFileChk.sh` as follow;
```
sudo vi /etc/cron.d/buildEntitlementChk

//Execute a command once an hour at 55 minutes
55 * * * * root /usr/local/bin/buildEntitlementFileChk.sh >> /var/log/buildEntitlementFileChk.log 2>&1
```

### Ref
- [buildEntitlementChk](https://github.com/bcgov-c/platform-ops/tree/main/tools/build-entitlement-monitor)
- [Benny Operator](https://github.com/bcgov-c/platform-gitops-gen/tree/master/roles/benny-operator)

**Comment by tmorik** [comment]
### Cron job set up for `buildEntitlementFileChk.sh`

1 On the `mcs-klab-util.dmz` server, Stop the cron job for `/usr/local/bin/buildEntitlementFileChk.sh` as follow;

```
sudo vi /etc/cron.d/buildEntitlementChk

//comment out this job (or you can remove the job)
#55 * * * * root /usr/local/bin/buildEntitlementFileChk.sh >> /var/log/buildEntitlementFileChk.log 2>&1
```

2 On the `mcs-silver-util.dmz` server, Set up a cron job for `/usr/local/bin/buildEntitlementFileChk.sh` as follow;
```
sudo vi /etc/cron.d/buildEntitlementChk

//Execute a command once an hour at 55 minutes
55 * * * * root /usr/local/bin/buildEntitlementFileChk.sh >> /var/log/buildEntitlementFileChk.log 2>&1
```

### Ref
- [buildEntitlementChk](https://github.com/bcgov-c/platform-ops/tree/main/tools/build-entitlement-monitor)
- [Benny Operator](https://github.com/bcgov-c/platform-gitops-gen/tree/master/roles/benny-operator)

**Comment by tmorik** [comment]
Document PR: https://github.com/bcgov-c/advsol-docs/pull/228

**Comment by wmhutchison** [comment]
Will enable new cron and disable old cron after SILVER CCM push today.

**Comment by wmhutchison** [comment]
done. Leaving KLAB cron/script in place for now, will revisit and remove before EOD Friday if there is no need to roll back.

**Comment by wmhutchison** [comment]
Per Ian's note regarding that we're not 100% over to SILVER until all PROD CCM pushes are finished.

```
Tatsuya and I discussed this: if there is an update to the entitlement cert before all the clusters have been updated (to look to Silver), then we can manually update the Secret and the custom resource in KLAB so that those other clusters will pick up the change.

Once all clusters have been updated (Thursday?) it will all be automated happiness again.
```

**Comment by wmhutchison** [comment]
All CCM prod syncs have been completed. Performed the cron switch (disabled KLAB, enabled SILVER) and notified Ian. Will move this into Sprint Backlog for now and have Tats review when he's back from vacation so he can determine if everything is as it should be.

**Comment by tmorik** [comment]
Confirmed the RH build entitlement checker script is working in the Silver cluster as expected and replaced the secrets for the Benny Operator, and the Benny Operator distributed the new secrets for other clusters.

i.e. 
These are from GoldDR cluster:

	```
	oc -n openshift-bcgov-entitlements  describe secret etc-pki-entitlement platform-services-controlled-etc-pki-entitlement

	Name:         etc-pki-entitlement
	Namespace:    openshift-bcgov-entitlements
	Labels:       <none>
	Annotations:  <none>

	Type:  Opaque

	Data
	====
	1051192802227752551-key.pem:  3247 bytes
	1051192802227752551.pem:      99298 bytes


	Name:         platform-services-controlled-etc-pki-entitlement
	Namespace:    openshift-bcgov-entitlements
	Labels:       <none>
	Annotations:  <none>

	Type:  Opaque

	Data
	====
	1051192802227752551-key.pem:  3247 bytes
	1051192802227752551.pem:      99298 bytes
	```

Both `etc-pki-entitlement` and `platform-services-controlled-etc-pki-entitlement` have been updated by Benny Operator to the latest `1051192802227752551` one. 

... And I also tested to rebuild the nagios monitoring using this entitlement in KLAB, and it's benn built and nagios is working as expected. 

The RH build entitlement check scirpt and the Benny Operator have been moved from KLAB to Silver.

I will close this ZenHub ticket.
