### ISSUE TITLE
Aporeto master protection in lab

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#280]
https://trello.com/c/bm6HDvVX/30-aporeto-master-protection-in-lab

We will configure aporeto to protect the master nodes in the lab such that clients will need a proper JWT from SSO to hit the API. This, in turn means, that people without access to SSO will never connect to the API directly.

**Comment by tosazuwa** [comment]
Due to Aporeto removed form OCP 3.11 clusters, this work is no longer relevant
