### ISSUE TITLE
Remove homepage image

### ISSUE THREAD

**Issue by marthaedwards** [BCDevOps/developer-experience#2801]
**Describe the issue**
Ideally, we want to have custom graphics for the cloud websites (public, private and SaaS) - but this will take some work to figure out our branding and the message we want to put forward through the websites. 

For MVP, we should remove the cloud image and have a colour block instead, until graphics can be sorted out with Public Cloud design team

**Additional context**

**Definition of done**
Remove the image

**Comment by mitovskaol** [comment]
the image was removed
