### ISSUE TITLE
Missing database documentation

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#2805]
The team has outlined a list of documents that should exist. Many do, but many others do not. This ticket covers the creation of missing documents relating to databases on the platform.

Related: the following link contains the master list of documents that should exist, as well as their status.
https://docs.google.com/spreadsheets/d/1Kcp45DF63nOpkeBncsynuIh91Tj9AzSOwwp76F4GX3Q/edit#gid=804907029

**Comment by mitovskaol** [comment]
@caggles As soon as the first markdown file with the DB content is finished, please get in touch with @ty2k and he will create a menu item to link it to on the left hand side of the site.At this moment "Database and API Management" menu does not exist yet as there is no content to link it to.

**Comment by ty2k** [comment]
I've [added an empty sub-menu](https://github.com/bcgov/platform-developer-docs/pull/74) for our Database and API Management content. New docs should be added to the `./src/docs/database-and-api-management/` directory (which doesn't exist in the repository yet).
