### ISSUE TITLE
Document a monitoring standard for all platform shared services and Apps

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#2820]
As a platform services team, we need to have default monitoring standards that will be applied to all our services and apps.

Enhanced monitoring, which are more unique to the application but could include metrics along these lines:

Traffic Monitoring:
* Number of HTTP Requests
* Number of Sessions
* Number of Transactions per second

Errors:
* Rate of Failed Requests

Latency:
* Amount of time to service requests

DOD: 
- [ ] Documented monitoring metrics and monitoring tools that will describe the approach to monitoring and alerting that will be applied to all platform shared services and apps.
- [ ] Publish the standard into our documentation website

**Comment by w8896699** [comment]
Reference: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1878

**Comment by w8896699** [comment]
CPU Used vs Requested(Utilization) where it the percentage between sysdig_container_cpu_cores_used and kube_pod_sysdig_resource_requests_cpu_cores. We can learn how much resources the registry is actually using vs how much it requested
CPU Used vs Limited(Threshold) where is the percentage between sysdig_container_cpu_cores_used and kube_pod_sysdig_resource_limits_cpu_cores. We can learn how much more resources is available for the registry application
For Utilization, we would like to achieve as much high as possible. However, its not always achievable 80% or above, but we will try our best.
For Limitations, I have set up an alert so when its 80%, it will send a RC message to ab internal channel to notify us to give it more resources as it almost run out of the resources. we can then give it more resources or do Horizontal auto scale depends on the situation.

**Comment by w8896699** [comment]
**More context**
I have added:

CPU Used vs Requested(Utilization) where it the percentage between sysdig_container_cpu_cores_used and kube_pod_sysdig_resource_requests_cpu_cores. We can learn how much resources the registry is actually using vs how much it requested
CPU Used vs Limited(Threshold) where is the percentage between sysdig_container_cpu_cores_used and kube_pod_sysdig_resource_limits_cpu_cores. We can learn how much more resources is available for the registry application
For Utilization, we would like to achieve as much high as possible. However, its not always achievable 80% or above, but we will try our best.
For Limitations, I have set up an alert so when its 80%, it will send a rc message to registry internal channel to notify us to give it more resources as it almost run out of the resources. we can then give it more resources or do Horizontal auto scale depends on the situation.

**Comment by w8896699** [comment]
Network Monitoring:
Error count: The number of errors encountered by network system calls, such as connect(), send(), and recv() at specified time by using sum of `sysdig_container_net_http_error_count` .  If we see a high error number, we would be expecting that there may exist logic bug, or api/db connection error

**Comment by ShellyXueHan** [comment]
@w8896699 looking great! would you start a document of the above information? Something like "Sysdig Monitoring Best Practise for Shared Platform Services and Applications" It's better to have them in a piece of doc then comments here!

**Comment by w8896699** [comment]
@ShellyXueHan is there any advice of where I should post them? I plan to ask a question in StackOverflow and answer there.

**Comment by ShellyXueHan** [comment]
add it to where sysdig docs are: https://github.com/bcgov/platform-developer-docs/tree/main/src/docs/app-monitoring

I'm thinking this would be an example for other teams to see how they should monitor their app as well. So it would be great if you can give reasons on why choosing specific metrics, how the SLI is monitored, and how alert thresholds are set, etc. Basically using our own monitoring practise as a guideline for other teams. That's what SRS is about ;)

**Comment by w8896699** [comment]
pods are been responsive,
pods crashing or restarting many time. crashloopback.
Pods using a lot resource, using reasonable amount of request resources
50% - Ops / Toil ; 50% Innovation


how to fix the issue
template query for general application to track specific matrics and explain what those matrics do.

Application and Platform Metrics

DORA metrics https://www.leanix.net/en/wiki/vsm/dora-metrics#:~:text=stream%20management%20efforts.-,What%20are%20DORA%20metrics%3F,change%20failure%20rate%20(CFR) 

How long does it take to discover bad pod, and average time to recover from it. The feedback from this dora will help team to understand how to fix it.

**Comment by w8896699** [comment]
I am waiting for @ksummersill2 to send me some meeting notes so I can add some detail to the doc.
