### ISSUE TITLE
Add Artifactory to Shared ArgoCD instance

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#2826]
**Description of the issue**
As part of the migration to Gold, we also want to start using Argo CD to manage the Artifactory installation (the current pipeline is very manual and inconsistent with other installation processes). As such, the first step of the migration will be to create two empty instances of Artifactory, one in Gold and one in Gold DR, alongside all other necessary objects, entirely through Argo CD.

**Additional information**
Migrate the Artifactory Helm files and templates from the old repo to the new GitOps repo.  Update configuration files as appropriate for Gold and GoldDR.

**Definition of Done**
- [x] Argo CD setup is complete (i.e., GitOpsTeam created) for both Gold and GoldDR
- [x] Existing Artifactory deployment files are migrated from the old repo to the new GitOps repo

**Comment by IanKWatts** [comment]
Just waiting for the next CCM push to Gold to set a RoleBinding to allow us to continue setup.

**Comment by IanKWatts** [comment]
Gold is set up and we will look at repo federation next.  GoldDR setup will happen after the initial repo federation investigation.
