### ISSUE TITLE
Database as a Service options for ROSA

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#2828]
**Describe the issue**
Look into deploying AWS services, mainly DBaaS from OpenShift so app teams in OpenShift can leverage AWS services in the ROSA cluster

**How does this benefit the users of our platform?**
Allows easy use of cloud resources.

**Definition of done**
App users easily deploy DBaaS in AWS and connect OpenShift apps to this DB

**Comment by caseyrobb** [comment]
RDS operator requires an IAM user and specific policy prior to being installed.

**Comment by filiy** [comment]
putting this here for reference.
https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/

**Comment by StevenBarre** [comment]
Would it make sense to just have product teams get their own AWS Account from CPF and create their RDS there via Teraform? Then all the billing is straightforward. They could then connect from their OCP project to that RDS instance in the other account?

Or does the VPC and account isolation make that difficult?

**Comment by filiy** [comment]
Yeah good idea Steven. That might be a question for the CloudOps team. I feel like the VPC/networking isolation might be an issue. The database service in AWS gets a private IP on the subnets where the ROSA cluster nodes live. I'm not sure how that would work across accounts and different subnets/VPC.

**Comment by filiy** [comment]
Adding this in here for reference too.

https://console.redhat.com/application-services/databases
https://access.redhat.com/documentation/en-us/red_hat_openshift_database_access/1/html-single/quick_start_guide/index
