### ISSUE TITLE
Porter Operator: Investigate reconciler issue in Silver

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2830]
**This may be fixed by issue #2340 - verify this after that fix has been deployed to Silver**

**Describe the issue**
The Porter Operator is available in all clusters, though it was primarily written to enable TCP connectivity between the Gold and GoldDR clusters.  In the Silver cluster, TransportServerClaim resources do not have a `.status` field, which seems to be associated with a reconciler error in the `manager` container.  Investigate why this is the case and update the operator to remove the reconciler error and allow for the status field to be added to the resources.

**Additional context**
Scan the logs of the porter operator's "manager" container for reconciler errors.
Review the manifests for TransportServerClaim resources to see the status or lack thereof.

**How does this benefit the users of our platform?**
Users want to see that this service is working normally and does not have known errors that may or may not affect functionality.

**Definition of done**
- [ ] The cause of the reconciler error has been found and documented here
- [ ] If a practical fix is available, it has been incorporated into the Porter Operator code and the operator image has been rebuilt and applied to each cluster.  If not, list the reason here as "won't fix".

**Comment by ksummersill2** [comment]
Porter Operator is going through testing and will be pushed for review.

**Comment by ksummersill2** [comment]
Example Output:
```

**Comment by IanKWatts** [comment]
I suspect that this issue will be resolved by issue #2340 when that gets deployed to Silver after the wildfire emergency is over.

**Comment by IanKWatts** [comment]
Marking this as blocked until the update in #2340 can be applied after the wildfire emergency is over.  I suspect this will be resolved by that update; if not, we'll move this back to the backlog.

**Comment by IanKWatts** [comment]
This was fixed here:
https://github.com/bcgov/platform-services-porter-operator/pull/6/files
