### ISSUE TITLE
Automate Platform capacity reporting

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2832]
As a Platform Director I would like to get a report every 3 weeks that would include the following information:
-  For each cluster , developer namespaces only:
- - CPU Usage vs CPU Request (current snapshot and from 2 weeks ago)
- - CPU Usage Percentage Trend over the last 2 weeks and predicted forecast 
- - Memory Usage vs Memory Request (current snapshot and from 2 weeks ago)
- - Storage Usage vs Storage Request  (current snapshot and from 2 weeks ago)
- - HA Proxy Trend (stacked session counts per router) over the last 2 weeks
- - Openshift image registry (% used, % available) (current snapshot and from 2 weeks ago)
- - NetApp Storage (% used, % available) (current snapshot and from 2 weeks ago)
- - NetApp Storage Backup (transferreed amount in Gib) (over the last 2 weeks)

- RedHat Cases status update over the last 2 weeks
 - - how many new were opened
 - - how many were closed
 - - how many total are still open

DoD:
- [ ]  an automated report with the abovementioned stats that gets emails to PlatformServicesTeam@gov.bc.ca and Olena.Mitovska@gov.bc.ca on a bi-weekly basis

**Comment by StevenBarre** [comment]
No longer required
