### ISSUE TITLE
Bugfix: Warden Operator: Argo CD Project fails to create

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2833]
**Describe the issue**
An error is encountered when the Warden Operator attempts to create the Argo CD Project for a project set.  It may be due to the license plate containing only digits.

**Additional context**
The error has only been seen when the license plate contains only digits.
The `name` variable may need to be explicitly set as a string so that it is not interpreted by the operator as an integer.
See the `reconcileGitOpsAppProject` in `controllers/gitops_reconciler.go`

**How does this benefit the users of our platform?**
They will be able to self-serve for Argo CD as intended.

**Definition of done**
- [x] The hypothesis is tested in a separate code snippet
- [x] A fix is applied to the Warden Operator code in a bugfix branch
- [x] Create a Build Config for the Warden Operator
- [x] A new version of the operator is built and tested
- [ ] The fix is made permanent and applied to all clusters

**Comment by ksummersill2** [comment]
Create a hypothesis using a simple Go Script located at: https://github.com/ksummersill2/bc-testing/tree/main/go-license-plate-number-check

**Comment by ksummersill2** [comment]
Create pull request for issue at: https://github.com/bcgov-platform-services/warden-operator/pull/1
Want to test out the changes for using replace instead of trim to fix the issue.

**Comment by ksummersill2** [comment]
The Warden Operator is currently setup to automatically sync with main branch. Setting up a new build config associated to branch 2833 to verify that changes within KLab.

**Comment by ksummersill2** [comment]
The build config is created on KLab within ksummersill2-tool namespace however running into docker build issues to provide the image. I am currently working on that process now to resolve.

**Comment by ksummersill2** [comment]
Going to run one more test today for the warden operator and then work with Ian to push changes.
