### ISSUE TITLE
Deriving Calculations for Free Capacity on an OCS/CNS cluster

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#284]
https://trello.com/c/zkPqjbSw/61-deriving-calculations-for-free-capacity-on-an-ocs-cns-cluster

The data feed currently comes from running "heketi-cli" and massaging the results for nodes in different ways. Not multi-cluster friendly yet.

**Comment by lukegonis** [comment]
Moving to closed as this is no longer relevant.
