### ISSUE TITLE
Vault - resources tuning

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2844]
**Describe the issue**
Vault server and injector pods are still using default resource config. we should update that!

**How does this benefit the users of our platform?**
using default is not good practise.

**Definition of done**
- [x] monitor on vault pods resource usage
- [x] figure out the source of vault manifest (helm chart or something else?)
- [x] specify resource configuration
- [x] apply changes

**Comment by IanKWatts** [comment]
This has been done as part of some other tickets.
4527 - re-org of vault gitops repo
3516 - setting of resources for agent injector and vault stateful set
4017 - vault injector improvement
All changes have been applied
