### ISSUE TITLE
Private Cloud WordPress feedback form component

### ISSUE THREAD

**Issue by ty2k** [BCDevOps/developer-experience#2847]
To give our users an easy way to offer feedback on our site content, create a feedback form component at the bottom of our pages that asks users if they found the page they are on useful. For inspiration, see the [GOV.UK feedback component](https://components.publishing.service.gov.uk/component-guide/feedback).

Because we would like to make this pattern as reusable as possible across our other web properties, use the BC government's [Common Hosted Forms service (CHEFS)](https://chefs.nrs.gov.bc.ca/app/) to host the form, and have the new feedback component link to it.

**Additional context**
- Work with Olena to determine the exact wording and logical flow of the feedback block.
- Ideally, the user won't have to add the URL of the page they are on to the form. Hopefully there is an existing pattern to use the referring URL to populate the form.
- The feedback component can probably live at the WordPress theme level, since we will want it on every page. In other words, don't try to add it to the individual content pages (and the template pages they were created from) unless that is totally necessary for some unforeseen reason (like requiring a unique URL parameter in the link or something).
- See the blog post [Making the GOV.UK feedback component more accessible](https://insidegovuk.blog.gov.uk/2022/03/28/making-the-gov-uk-feedback-component-more-accessible/) for accessibility considerations.

**How does this benefit the users of our platform?**
Users will have a straightforward way to offer feedback on our content. Without this, users would have to track down our team email address, post feedback in Rocket.Chat, etc. This will lower the barrier to entry to getting feedback, helping us know where our content needs to improve.

**Definition of done**
- [ ] CHEFS form is created and sends data to PlatformServicesTeam@gov.bc.ca
- [ ] Feedback form component appears at the bottom of each WordPress page

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
