### ISSUE TITLE
add feedback component to both product owner and tech docs websites

### ISSUE THREAD

**Issue by marthaedwards** [BCDevOps/developer-experience#2848]
**Describe the issue**
Each page should have the functionality for users to 
1 - provide feedback on whether it was useful (measures user satisfaction)
2 - report a problem or a necessary content change. 

**Additional context**
There is a current pattern for #1 on BC Gov websites (see below) - however, I would like to offer #2 as well, so we can action items, This might require looking into privacy. 
UK gov pattern is something we could copy - https://insidegovuk.blog.gov.uk/2022/03/28/making-the-gov-uk-feedback-component-more-accessible/

**How does this benefit the users of our platform?**
Improves user experience by having a place to report problems, and gives us insights to fix issues

**Definition of done**
Feedback mechanism on the two websites

![Screen Shot 2022-07-08 at 2.30.39 PM.png](https://images.zenhubusercontent.com/6011b63bf939603a91327283/8f48a408-7268-47ad-8fcb-764f95805c9b)

![Screen Shot 2022-07-08 at 2.30.47 PM.png](https://images.zenhubusercontent.com/6011b63bf939603a91327283/1ff27878-c777-469b-b6f9-9dbbfc83327f)

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
