### ISSUE TITLE
Automate emailing scan reports from ACS to PO/TLs of the app

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2853]
As a product team that uses Advanced Cluster Security (ACS) scanning service in the private cloud, we want to receive the reports with vulnerability scanning results via email automatically.

Additional context:
**The implementation of this feature is contingent on integrating ACS with the Platform Registry in order to query the contact information for Product Owner and Technical Lead(s) for the app.
DoD:
- [ ] Add a feature to ACS that sends out the report with the ulnerability scanning results to the Product Owner and Tech Lead(s) email automatically at the end of each scan.

**Comment by AvneetKahlon** [comment]
ACS have vulnerability reporting feature, we have setup gov email notifier for them and they use that notifier to send vuln reports to thrmselves.
