### ISSUE TITLE
Create an architecture diagram for Private Cloud Platform

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2854]
As a Platform Services Team we need to have an architecture diagram outlining our clusters, their network zones and the cluster high level capabilities (Openshift Build In SDN vs NSX-T), shared services installed on them i.e. Sysdig and ACS, etc.

Additional Context:
The old architecture diagram can be used as an example.   
![OCP4-Final-Architecture.png](https://images.zenhubusercontent.com/5ae096c24b5806bc2bd09c0f/21985980-066d-4845-84e8-9032fc722e3d
)

Target audience:
Technical architects that want to understand the differences between the clusters. Will be public.

DoD:
- [ ] the diagrams is created and PNG version uploaded to the protected space in Private Cloud website. (The source version from diagrams.net can be stored in protected folder  in Google drive)

**Comment by StevenBarre** [comment]
https://drive.google.com/file/d/1Oc-ItASybNjpbXzBUNp25Z7B6zmfbsA-/view?usp=share_link

**Comment by StevenBarre** [comment]
> PNG version uploaded to the protected space in Private Cloud website

@mitovskaol can you let me know which page you want this on?

**Comment by mitovskaol** [comment]
I suggest creating a brand new page and a new menu item under "Platform architecture reference" menu in Tech Docs with a title "Platform Architecture diagram" and put in there. @Kolezhanchik  can help point to the place in the [docs repo ](https://github.com/bcgov/platform-developer-docs) where this new markdown file should be placed.

**Comment by StevenBarre** [comment]
Done!
https://docs.developer.gov.bc.ca/platform-architecture-diagram/
https://cloud.gov.bc.ca/private-cloud/platform-architecture-diagram/
