### ISSUE TITLE
Align LAB cns project config with PROD

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#286]
https://trello.com/c/Ss3NW81l/25-align-lab-cns-project-config-with-prod

CNS in the Lab is set to a global project. CNS in prod is isolated (with network joins where appropriate). 

- Lets isolate cns project in lab
- Join the devops-dashai-tools project to cns

**Comment by sbarre-esit** [comment]
I think Shea made this Jeff? Do we still need this?

**Comment by jefkel** [comment]
is the config for CNS in the lab the same as in Prod?  If not, then I think we could keep this ticket open (possibly for one of the new OPS team members to learn with?)

**Comment by lukegonis** [comment]
Closing this issue as it is no longer needed in OCP3.
