### ISSUE TITLE
Allow spaces and dashes in first and last name in project details page

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2860]
**Describe the issue**

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [x] spaces and dashes are allowed in all first and last name fields in the project details page
- [x] to test, enter a name with spaces and dashes in the front end, save the change and go back to project record in the registry to confirm the email appears

**Comment by lukegonis** [comment]
@w8896699 this issue is blocked/unable to merge to master, can you please help Gordon with it when you have a chance?

**Comment by qrdn** [comment]
The issue has been resolved and has no problems with merging now.
