### ISSUE TITLE
Catalog Grooming

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#287]
https://trello.com/c/fSfvSVAf/27-catalog-grooming

There are too many items in the catalog that users may not require, may cause confusion, or simply aren't endorsed. Create a codified process to manage the catalog entries and eventually prune the templates/objects that we don't want presented to end users.

**Comment by lukegonis** [comment]
Not worth the effort in OCP3, will revisit to see if this is still an issue in OCP4.
