### ISSUE TITLE
Jenkins auto-provision template

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#290]
https://trello.com/c/nVUTwemZ/92-jenkins-auto-provision-template

When using auto-provisioned Jenkins should it use the customized bcgov template?

Should we be using gluster-block instead of gluster-file?

Should the default PVC be bigger? Jenkins breaks when there is 500Mb free.

> Disk space is too low. Only 0.482GB left on /var/lib/jenkins.

**Comment by ShellyXueHan** [comment]
- [ ] investigate the current template
- [ ] decide on storage type (netapp block/file)
- [ ] decide on proper storage size
