### ISSUE TITLE
OpenShift 301

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2904]
**Describe the issue**
- This course will teach the Shared Services/Tools available to developers/teams on the platform, including: Sysdig, Artifactory, ACS, Vault 

1. decide at a high level what content should be included
2. collect content from vendor/SMEs
3. organize content into consumable form (Mural? Lab exercises? Self Paced Learning?)
4. Test run through with Platform Services team
5. Scheduling - Eventbrite, Outlook, Zoom
6. Advertising/Marketing - Community Meetup, Rocket.Chat, Teams, LinkedIn, Learning Hub, etc.

**Definition of done**
- [ ] The course is available for registration

**Comment by mtspn** [comment]
This ticket will also need a decision on how to schedule training between 101/201/301

**Comment by mtspn** [comment]
Current approach is to introduce self-paced modules to cover the topics that might have been included in a 301 course, directing participants to self-paced sysdig training. Cailey is creating Artifactory videos.
