### ISSUE TITLE
CronJob's every minute - ask teams to reduce these and possibly put them into a persistent pod.

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#291]
https://trello.com/c/Qz9BuCh0/94-cronjobs-every-minute-ask-teams-to-reduce-these-and-possibly-put-them-into-a-persistent-pod

Push Cron education out to community regarding best practices for Cron scheduling
 - Kubernetes scheduled -

**Comment by jefkel** [comment]
Possibly something that can be added to Cailey's awesome documentation and communication push?

**Comment by sbarre-esit** [comment]
@caggles could we add something to your docs about not running cronjobs too frequently?

**Comment by sbarre-esit** [comment]
@caggles could we add something to your docs about not running cronjobs too frequently?

@tmorik can you check if there are still active cronjobs that run too frequently on the platform?

```console
$ oc get cronjob --all-namespaces | grep -E '\* \* \* \* \*|\*/1 \* \* \* \*|NAMESPACE' | grep -v True | awk '{print $1"/"$2}'
```

**Comment by tmorik** [comment]
@sbarre-esit , Command output is like this: 
```
 $ oc get cronjob --all-namespaces | grep -E '\* \* \* \* \*|\*/1 \* \* \* \*|NAMESPACE' | grep -v True | awk '{print $1"/"$2}'
NAMESPACE/NAME
zcd4ou-dev/future-effective-filings-dev
```

**Comment by caggles** [comment]
I'm working on the docs right now, and I'm hoping to provide some guidance on what can/should be done when a job runs very often. First solution is "don't run the job so often" but I'm not sure where to find docs on how to put your cronjobs into a persistent pod - can anybody point me towards some if you're already aware of them? If not, I'll poke around some more on my own.

**Comment by sbarre-esit** [comment]
https://hub.docker.com/_/jobber looks cool?

**Comment by caggles** [comment]
An initial version of the doc is here: https://github.com/BCDevOps/developer-experience/pull/548

I'll open another ticket to further investigate Jobber and maybe provide more guidance on using it later, but hopefully this is a good starting place for the document.
