### ISSUE TITLE
ArgoCD - Ignore missing install plans for operator subscription

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2914]
**Describe the issue**
ArgoCD will consider a sync failed when the install plan is missing. We can update its configuration to ignore the event.

Gerald's solution:
https://github.com/gnunn-gitops/gitops-operator-install/blob/main/openshift-gitops/base/openshift-gitops-cr.yaml#L66

We might be able to add it here:
https://github.com/bcgov-c/platform-gitops-gen/blob/master/roles/argocd/templates/cm.argocd-cm.yaml.j2#L121-L134

But I'm not sure how are the configurations currently used? As I don't see the configmap being referenced other than `timeout.reconciliation`. https://github.com/bcgov-c/platform-gitops-gen/search?q=argocd-cm

**Definition of done**
- [x] look into this
- [x] implement fixes or alternatives

**Comment by IanKWatts** [comment]
This has been implemented in the Argo CD ConfigMap and merged into CCM.
https://github.com/bcgov-c/platform-gitops-gen/pull/516
