### ISSUE TITLE
ACS automation - MISO and Admin access role mapping issue

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2924]
**Describe the issue**
There are two issues:
1. ACS API endpoint has introduced better response code for conflicting auth provider (from 500 to 409):
```
TASK [Set default role for provider "OpenShift"] *******************************
11
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content_length": "265", "content_type": "application/json", "date": "Fri, 29 Jul 2022 19:34:25 GMT", "elapsed": 0, "json": {"code": 6, "details": [], "error": "error adding during mutation: a default group already exists for auth provider \"auth_provider_openshift_id\"", "message": "error adding during mutation: a default group already exists for auth provider \"auth_provider_openshift_id\""}, "msg": "S
tatus code was 409 and not [200, 500]: HTTP Error 409: Conflict", "redirected": false, "status": 409, "url": "https://acs-lab.developer.gov.bc.ca/v1/groupsbatch", "vary": "Accept-Encoding"}
```

2. `groupsbatch` behaves different now where we would create duplicate item for the same group config.

**Definition of done**
- [x] look into what caused the change for auth provider and fix
- [ ] wait for Billy to implement the new logic for groupsbatch

**Comment by ShellyXueHan** [comment]
### update:

this is related to the new changes of ACS where user can now be assigned with multiple roles, and causing some ansible tasks fail now. Will need to discuss with Gerald on how to handle that before proceeding.

**Comment by ShellyXueHan** [comment]
### Updates:
we've set the standard for role mapping on ACS in the future, Billy can continue on with the group updates for both app team access and miso access now. @w8896699 once you are done with the app team access update, please add the same change for admin and miso access here: https://github.com/BC-Gov-PaaS-Platform-Services/acs-automation/pull/4 thank you!

**Comment by w8896699** [comment]
updated that pr. It shouldn't block next time ccm after been merged.
