### ISSUE TITLE
Add 'alliance' label to NATS messages

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#2926]
**Describe the issue**
In support of the Warden Operator's "GitOps Alliance" feature, a namespace label is required.  Add the label to the NATS message that is sent to the Provisioner.  Include it at the top level of the JSON, after the 'merge_type' field.
- For any project set that is part of the JAG group, set it as:
  `"alliance":"JAG",`
- For any other project set, set it as:
  `"alliance":"none",`

**Additional context**
- The namespace template used by the Provisioner will be modified to include this field.
- This label will be added to the namespace manifest used by Argo CD
`.metadata.labels.alliance`

**How does this benefit the users of our platform?**
This ensures that a family of project sets will automatically get the correct label, used for collective management via Argo CD.  It also ensures that any removal or modification of the label will self-correct by way of Argo CD.

**Definition of done**
- [ ] The NATS messages produced by the registry include a top-level `alliance` field

**Comment by lukegonis** [comment]
@okanji would you be ok for setting this as a priority for @Kolezhanchik in the upcoming sprint?

**Comment by ShovelHand** [comment]
Done in Platfrom Services Registry 1.0. Not yet tested in 2.0

**Comment by ShovelHand** [comment]
Done and tested in both old and new Platform Services Registry apps.
