### ISSUE TITLE
Research long term metrics retention

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#293]
https://trello.com/c/LTXln6uU/24-research-long-term-metrics-retention

As a minimum, we need to track some metrics long term for growth planning. Things like cluster CPU and Memory capacity and consumption, CNS capacity and consumption, running pods, etc.

We'd like to have access to graphs with 6-12 months of data available.

Metrics I'd like long term
- [ ] load average on hosts
- [x] number of pods in each state
- [ ] number of projects
- [ ] number of PVs per storage class
- [ ] disk usage/free of CNS nodes or other storage platform)
- [ ] Cluster capacity and requests
- [ ] disk usage of infra components (registry, hawkular, prometheus)

**Comment by sbarre-esit** [comment]
Sysdig is incapable of long term aggregation that makes sense. I think we should look into doing our own aggregation and having Sysdig scrape that.

**Comment by lukegonis** [comment]
ties to issue 639 around monitoring/metrics.

**Comment by sbarre-esit** [comment]
Now that I've figured out how to store data points in Nagios, I'm going to use it for my long term graphs for OCP4. Giving up on doing this for OCP3.

**Comment by StevenBarre** [comment]
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/33c7b8dd-ee42-4213-952a-f4e88ddfbccb)
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/b9e5d5b4-a29f-4372-b4e0-6f1a7f53be9c)

**Comment by StevenBarre** [comment]
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/ae5d7570-b00a-432b-8ba6-7ee3d4798dee)

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-tools/pull/31

**Comment by StevenBarre** [comment]
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/fe078660-cd52-47cd-bc0f-bd7b15e29d27)

**Comment by jefkel** [comment]
Are you able to separate the metrics by node? (ie: separate workload running on master/infra from workload running on workers?)

**Comment by StevenBarre** [comment]
Generally, yes. The first two CPU Capacity are workers only.

For the pod stats, we could slice and dice by node or namespace if that would be useful.

What do you think would be most optimal/useful for trend graphs?

**Comment by jefkel** [comment]
I think it depends on what we're looking to trend.

Worker node usage (mem/cpu/pods/etc) are a great base as this helps trend cluster usage  (for namespace based metrics, it might be best to just use the metrics tool?)

Trending for infra nodes (as a separate graph) would be useful as indicators that the infra nodes are holding up as the cluster grows over time.  (could include masters in same graph, but as separate lines?)

After the meeting today, it came up that the over-provisioning metric is missing (ie: total quota allocated), and that could be a nice addition?

**Comment by StevenBarre** [comment]
Oooo sum of quota could be cool.

By namespace, i was more talking splitting things into those that start with openshift-* and those that don't like I did for CPU Raw.

I don't really expect the requests/limits or pod count on infra/master to change over time.

So maybe change the `MCS Pods` to be just worker nodes?

Then add an extra graph for CPU/MEM used % on master/infra nodes?

I was also planning to add some per-host graphs for things like load average, total pod count, etc as these graphs are just cluster scoped.

**Comment by StevenBarre** [comment]
Calling the "research" phase complete and closing this ticket this sprint. Created an [EPIC](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/947) to track the work going forward and expanding the metrics being captured.
