### ISSUE TITLE
Container Breakout Presentation development

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#2933]
Create a presentation re: Container breakout.  To be presented at a Community Meetup.
This will help to communicate reasons to OCP customers why we limit container permissions.

To include in PowerPoint:
- [x] Things that can lead to breakout
- [x] Harms that can come from breakout
To be recorded:
- [x] Demo of breakout happening in a lab
- [x] Damage that can be caused by breakout user

**Comment by ShellyXueHan** [comment]
please add a slide to the presentation deck: https://docs.google.com/presentation/d/1FTfopbZyG9IShpdItxz-zmCVStCHbIKTgItNuskKTCo/edit#slide=id.g13fa3ab0731_0_153! thanks!
