### ISSUE TITLE
Review OCP 4.10 Release Notes - Shelly

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2943]
**Describe the issue**
Review the [OCP 4.10 Release Notes](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
Fully read the release notes and added anything of interest as a comment here.

**Comment by ShellyXueHan** [comment]
- https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-conditional-updates
- pipelines workflow UI changes - we might need to update documents
- ProjectHelmChartRepository - something we might want to use for share?
-  Dynamic plug-in (Technology Preview) - integrate doc pages?
- debug pod UI
- workload notifications - what is it?
- `AppliedClusterResourceQuota` for app teams
- Listing pods targeted by network policies - new feature?

note: continue on with storage later.
