### ISSUE TITLE
Review OCP 4.10 Release Notes - Billy

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2944]
**Describe the issue**
Review the [OCP 4.10 Release Notes](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
Fully read the release notes and added anything of interest as a comment here.

**Comment by w8896699** [comment]
Learned:

* Debug pod's log now can be access in Web UI(we may include this in ocp101)
* Switch between YAML view and Form view UI Change
* A new Metrics Targets page in the OpenShift Container Platform web console shows targets, looks like it has search and filter by label function. Will be helpful for debugging issue.
* Anti-affinity rules and pod disruption budgets for couple monitoring pod
* Docker default config location setting has been deprecated. 
* Noticed that a couple of the RHEL7 services is being deprecated.
* non-admin user can see storage quota now
