### ISSUE TITLE
Review OCP 4.10 Release Notes - Tim

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2947]
**Describe the issue**
Review the [OCP 4.10 Release Notes](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
Fully read the release notes and added anything of interest as a comment here.

**Comment by tbaker1313** [comment]
Initial larger changes noted include:
* You can now view debug terminals in the web console
* RBAC page will display content (bugfix)
* Place nodes into maintenance mode by using the Node Maintenance Operator
* Added hard anti-affinity rules and pod disruption budgets for Alertmanager, Prometheus adapter, Prometheus & Thanos Querier
* Access to the third-party Grafana web user interface is deprecated
* Jenkins Operator removed

**Comment by tbaker1313** [comment]
Release notes reviewed and ticket updated.
