### ISSUE TITLE
Meeting to discuss OCP 4.10 Release Notes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2948]
**Describe the issue**
Once everyone has had a chance to review the [OCP 4.10 Release Notes](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team, have a meeting to discuss each persons individual findings/notes.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Steven to schedule a MS Teams meeting to have everyone discuss.

**Identify any dependencies**
See blockers

**Definition of done**
Meeting held.

**Comment by StevenBarre** [comment]
Meeting scheduled for Tues Aug 23rd at 2pm

**Comment by gnunn1** [comment]
https://developers.redhat.com/articles/2022/03/22/whats-new-developers-openshift-410-console#openshift_pipelines_enhancements

**Comment by StevenBarre** [comment]
Meeting was held and generated these tickets

- [OCP 4.10 Install Web Terminal Operator via CCM in CLAB](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2999)
- [Document how to use Egress NetPol in OCP 4.10](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/3001)
- [OCP 4.10 Test enabling HTTP Compression in CLAB](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/3002)
- [Updates to OCP101 for the 4.10 upgrade](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/3003)
- [Investigate Enhancements to API in the install-config.yaml file](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/3004)
- [Create customized error pages for HAProxy](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/3005)
- [Investigate disabling copied CSVs to support large clusters](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/3006)

Also added comments to the tickets [Send Mautic Mail about the OCP 4.10 Upgrade](https://app.zenhub.com/workspace/o/bcdevops/developer-experience/issues/2950) and [Create slide for Community Meetup about 4.10 Release Notes](https://app.zenhub.com/workspace/o/bcdevops/developer-experience/issues/2949) about what we want to cover.
