### ISSUE TITLE
Send Mautic Mail about the OCP 4.10 Upgrade

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2950]
**Describe the issue**
After the team meets to discuss the [OCP 4.10 Release Notes](https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html), draft and send an email to product teams outlining what they need to know about the coming upgrade.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Compile the notes from the meeting into an email for @mitovskaol to send via Mautic.

**Identify any dependencies**
Must have the meeting with the team first.

**Definition of done**
Mautic email sent.

**Comment by mitovskaol** [comment]
@StevenBarre  In my absence Cailey or Shelly can help with sending the content through Mautic once it is prepared

**Comment by StevenBarre** [comment]
- debug pod terminal in web console
- Egress netpol is now available
- Enable HTTP compression
- Listing pods targeted by network policies @wmhutchison 
- blog about new things https://developers.redhat.com/articles/2022/03/22/whats-new-developers-openshift-410-console

**Comment by ShellyXueHan** [comment]
did not send out the email, but considering the upgrade is completed and it would be confusing to send it out now, we are closing the ticket directly!
