### ISSUE TITLE
Determine gov email addresses validation is possible in the Registry

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2953]
**Describe the issue**
Determine if it is possible to validate gov email addresses and fetch first and last name information based on that email. 

**Rational/Why**
We want to validate if valid email address was entered into the PO email field and to automatically populate first and last name

**Additional Context** 
- Link to the code repositories
- List of technologies that may be expected to be known in order to work on the task
- Clear description of where the code change is going, e.g "add the text input to the create request form in components/request.js"
- Clearly identify which products are being updated ("Platform Services Registry")

**Dependencies**
- Internal, external, who to talk to if more information is needed

**Tests**

**Definition of done/Acceptance Criteria**
- Clear description of the intended final result
- Acceptance criteria that describes the action a User Acceptance Tester would be trying to see if the work is complete

**Comment by okanji** [comment]
This has been implemented in registry 2.0
