### ISSUE TITLE
Document the steps for adding common components to the project edit form

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#2955]
**Describe the issue**
At this moment the info about common components used in a new app is only captured in the create project form. 

**Rational/Why**
There is no ability to edit this info after the project has been provisioned. As apps evolve over time, some common components are removed from their architecture and others are added, so the teams need the ability the modify the common component information in the Registry.

DoD:
- [ ] Document in this ticket what Registry code needs to be updated to implement this change.

**Comment by okanji** [comment]
This is implemented in the registry 2.0

**Comment by Iryna-Kaplun** [comment]
This ticket is completed.
