### ISSUE TITLE
Fix cloud.gov.bc.ca errors to align with Style Guide

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#2956]
**Describe the issue**
There are a few grammatical errors and stylistic inconsistencies within the cloud.gov.bc.ca site that do not align with the GDX Style Guide.
 
**What is the Value/Impact?**
- Fixing these issues would align our site with the GDX/BC Gov standards

**What is the plan? How will this get completed?**
- Get Alex WP access
- identify and fix all grammatical errors (approximately 5-10)
- identify and fix styling inconsistencies in case study (approximately 5)
- publish

**Identify any dependencies**
- Alex's WP access

**Definition of done**
- [ ] changes are viewable in production

**Comment by alexandralloyd** [comment]
Completed
