### ISSUE TITLE
Sysdig - uninstall sysdig agent from infra and master nodes

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#2958]
**Describe the issue**
Let's discuss if we actually need sysdig agents on infra and master nodes.

**What is the Value/Impact?**
if not needed we can save up some license!

**What is the plan? How will this get completed?**
discussion and find out any use case.

**Identify any dependencies**
no

**Definition of done**
- [x] identify any use case for sysdig agent on master and infra nodes - not needed
- [x] decide on if we should keep them
- [x] plan on actions needed - CCM pr in place
- [x] remove sysdig label from master and infra nodes
- [x] CCM push to prod

**Comment by StevenBarre** [comment]
Masters and Infra labels removed in all clusters
