### ISSUE TITLE
Sysdig Dashboard: CPU/Mem Capacity

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#296]
https://trello.com/c/M5zL2PME/104-sysdig-dashboard-cpu-mem-capacity

Mirror AdvSol Grafana Compute cluster top 6 panels
- CPU and Mem - Usage, Requests, Limits (over time)

**Comment by stewartshea** [comment]
Updates required to the Sysdig dashboard that is being shown on status.developer.gov.bc.ca. 
- [ ] Adjust Supply & Demand into Commitment 
- [ ] Color code Commitment 
- [ ] Drop CPU History 
- [ ] Link off to page with deeper details (ie. when this is red, buy more hardware)
- [ ] Add filters for the pathfinder cluster (as the lab is now being seen)

**Comment by stewartshea** [comment]
Following the latest review, a few updates are required; 
- [ ] Add links to  the resiliency guidelines 
- [ ] Node description 
- [ ] # of Prod Projects
- [ ] Remove Limits
- [ ] Stable threshold at 75% < Red > 
- [ ] Look into the graphing of the number - 24 - 72 hour period. 
- [ ] Simplify time view (or remove time picker)

**Comment by stewartshea** [comment]
I'm getting some feedback from Sysdig on the longer timeframe since it tends to continue to increase for the longer time periods which doesn't make too much sense.

**Comment by stewartshea** [comment]
The other changes have been applied to the dashboard.
