### ISSUE TITLE
Sysdig Dashboard: Weather

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#297]
https://trello.com/c/TRc97EVj/105-sysdig-dashboard-weather

Dashboard to graph the following over time:
Pods per state (running, completed, crashlooping, etc)
PV's per StorageClass
 - warn when gluster-* at 80% of 1500
 - alert when gluster-* at 90% of 1500
Disk usage per storage node (not internal to PV's, but used for provisioning)

**Comment by lukegonis** [comment]
This issue is a duplicate, moving to closed
