### ISSUE TITLE
Content testing round 2: Analysis, reporting back and next steps

### ISSUE THREAD

**Issue by marthaedwards** [BCDevOps/developer-experience#2977]
**Describe the issue**
Analyze insights from the research, grouoing into themes
Pull out relevant insights to report back to execs and team
Gather consensus on next steps with design team, and record those in design decision log

**Additional context**

**How does this benefit the users of our platform?**
We use these insights to make the website better for them

**Definition of done**
Research data sorted into themes. 
Presentation made to report back
Next steps logged in design decision, and made into backlog tickets where appropriate

Folder
https://drive.google.com/drive/u/0/folders/1Y85r6cuCoWZ1hPiihfwHh42_SOHAicym

design decision log: https://docs.google.com/spreadsheets/d/1GcKZ7PgxCyPESw02ul6qbeai-xB9jSeCnvwp-2bIQXY/edit#gid=527988114

**Comment by alexandralloyd** [comment]
Created the design decision log to track the decision that came out of this research:https://docs.google.com/spreadsheets/d/1GcKZ7PgxCyPESw02ul6qbeai-xB9jSeCnvwp-2bIQXY/edit#gid=2052166830

Created #3040 to reflect the need to make these changes.
