### ISSUE TITLE
Devhub Issue: User access into Github or Openshift [Access to 26e83e-test namespace in OpenShift]

### ISSUE THREAD

**Issue by dmitri-korin-bcps** [BCDevOps/developer-experience#2979]
> path: (do not delete) https://github.com/BCDevOps/developer-experience/blob/master/docs/UserAccessToOrg.md
 > (do not delete) devhub page: /User-access-into-Github-or-Openshift

Hello,

Could you please give me Edit access to 26e83e-test namespace in OpenShift.  As a member of NRIDS - Sustainment Team I need the access to troubleshoot build/deployment issues for gwells product. 
My GitHub id is dmitri-korin-bcps.

Thanks
Dmitri Korin

**Comment by lukegonis** [comment]
Hello @dmitri-korin-bcps you can request access to OpenShift via https://just-ask.developer.gov.bc.ca/
The GWells Technical Lead should be able to grant access to that specific namespace (26e83e-test)
