### ISSUE TITLE
MCS Emerald Utility server - Determine steps to use the GOV proxy to access the internet

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#2984]
**Describe the issue**
Currently the mcs-emera-util.dmz server is in an SDN zone and can't readily access things like github. Need to determine what needs to happen to use the proxy to reach the internet. Notable urls that we can't access are github.com and smtp.advsol.tech

**How does this benefit the users of our platform?**
Necessary for administration of the EMERALD cluster.

**Definition of done**
- [x] The server mcs-emera-util.dmz can successfully connect to the internet, send mail and clone git repos.

**Comment by tbaker1313** [comment]
smtp issue was routing related and now fixed.

**Comment by StevenBarre** [comment]
Added `/etc/profile.d/proxy.sh` with needed proxy settings
