### ISSUE TITLE
ETCD Encryption

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#299]
https://trello.com/c/L9X7N0Cy/112-etcd-encryption

Todd asked if we are encrypting ETCD. Currently we are not, but there is a way to do it. https://docs.openshift.com/container-platform/3.11/admin_guide/encrypting_data.html

OCP4 link: https://docs.openshift.com/container-platform/4.4/security/encrypting-etcd.html
He asked I add a card to the backlog.

**Comment by lukegonis** [comment]
this is a feature for future investigation, requires some research to understand the implications before the decision

**Comment by mitovskaol** [comment]
The team had a discussion and confirm that this is a feature that we want to enable in the new OCP 4 Platform. I am closing this ticket and will open a new one in the OCP 4 backlog.
