### ISSUE TITLE
Ops team install  Red Hat OpenShift Service Mesh (Istio) in KLAB

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#2990]
**Describe the issue**
In tech share meeting, we discussed that we want to have a tool that monitors our platform network traffic, and Istio has been brought up. 
**Additional context**
- [Red Hat OpenShift Service Mesh](https://docs.openshift.com/container-platform/4.10/service_mesh/v2x/ossm-about.html#ossm-servicemesh-overview_ossm-about)
- [Istio](https://istio.io)

**How does this benefit the users of our platform?**
- Traffic Management - Control the flow of traffic and API calls between services, make calls more reliable, and make the network more robust in the face of adverse conditions.

- Service Identity and Security - Provide services in the mesh with a verifiable identity and provide the ability to protect service traffic as it flows over networks of varying degrees of trustworthiness.

- Policy Enforcement - Apply organizational policy to the interaction between services, ensure access policies are enforced and resources are fairly distributed among consumers. Policy changes are made by configuring the mesh, not by changing application code.

- Telemetry - Gain understanding of the dependencies between services and the nature and flow of traffic between them, providing the ability to quickly identify issues.

**Definition of done**
- [x] install Red Hat OpenShift Service Mesh (Istio) in Klab
- [x] test/evaluate

**Comment by tmorik** [comment]
Updated the ticket description

**Comment by tmorik** [comment]
RH ServiceMesh operator has been installed in KLAB and deployed the operator in `istio-system` namespace. 

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/ac33b53f-4c71-4682-ac97-190838039978)

The steps I followed is here:

- https://docs.openshift.com/container-platform/4.10/service_mesh/v2x/preparing-ossm-installation.html#preparing-ossm-installation

Also the sample app `bookinfo` has deployed in the `bookinfo` namespace. the Deployment steps is here :

- https://docs.openshift.com/container-platform/4.10/service_mesh/v2x/ossm-create-mesh.html#ossm-tutorial-bookinfo-overview_ossm-create-mesh

The Kiali web console (RH ServiceMesh console) is also up and running and catching the sample `bookinfo` app's status:

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/7c44148e-ba68-4636-bc31-c904b8903ca0)

**Comment by tmorik** [comment]
RH ServiceMesh operator has been installed in KLAB and deployed the operator in `istio-system` namespace. 

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/ac33b53f-4c71-4682-ac97-190838039978)

The steps I followed is here:

- https://docs.openshift.com/container-platform/4.10/service_mesh/v2x/preparing-ossm-installation.html#preparing-ossm-installation

Also the sample app `bookinfo` has deployed in the `bookinfo` namespace. the Deployment steps is here :

- https://docs.openshift.com/container-platform/4.10/service_mesh/v2x/ossm-create-mesh.html#ossm-tutorial-bookinfo-overview_ossm-create-mesh

The Kiali web console (RH ServiceMesh console) is also up and running and catching the sample `bookinfo` app's status:

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/7c44148e-ba68-4636-bc31-c904b8903ca0)

**Comment by tmorik** [comment]
For simple ServiceMesh test, Try to connect `bookinfo` app web page and see if your activities are shown in the ServiceMesh console.

- Bookinfo webpage :  http://istio-ingressgateway-istio-system.apps.klab.devops.gov.bc.ca/productpage

- ServiceMesh console: https://kiali-istio-system.apps.klab.devops.gov.bc.ca/

![Uploading image.png…]()

Or you can add your apps to the ServiceMesh. Please follow this instruction:

- [Adding or removing projects from the service mesh](https://docs.openshift.com/container-platform/4.10/service_mesh/v2x/ossm-create-mesh.html)

**Comment by tmorik** [comment]
The ServiceMesh installation doc will be PRed in here: https://github.com/bcgov-c/advsol-docs/pull/252

**Comment by StevenBarre** [comment]
Moved to In Review while waiting for @w8896699 to do some testing.

**Comment by w8896699** [comment]
I have tested it and it works as described. Also tried to install argocd-shared as test. Works as expected.

**Comment by tmorik** [comment]
It looks like KLAB's serviceMesh is broken since sometime in February. Since no one is using it, I will remove this operator for now, and will reinstall it upon request.
