### ISSUE TITLE
OCP 4.10 Install Web Terminal Operator via CCM in CLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#2999]
**Describe the issue**
The [Web Terminal Operator](https://docs.openshift.com/container-platform/4.10/web_console/odc-about-web-terminal.html) is now GA in 4.10. Install it via CCM in CLAB (and the rest of the clusters as they are updated)

**What is the Value/Impact?**
Provides a terminal in the web console with the `oc` CLI tool, and other tools, that is already logged in and scoped to the current project.

**What is the plan? How will this get completed?**
 - Write CCM role
- Test in CLAB after 4.10 upgrade

**Identify any dependencies**
4.10 upgrade in CLAB

**Definition of done**
CCM PR merged

**Comment by tbaker1313** [comment]
CCM files are prepared and tested in CLAB

**Comment by tbaker1313** [comment]
Tested CCM implementation in CLAB and this was successful. Leaving ticket open pending any feedback. https://github.com/bcgov-c/platform-gitops-gen/pull/522 fixed the issues and was tested successfully.

**Comment by StevenBarre** [comment]
https://access.redhat.com/support/cases/#/case/03310194 documents some needed NetPol to get this working

**Comment by tbaker1313** [comment]
This has been added to all the LAB environments. Will assess and apply to PROD if desired.
