### ISSUE TITLE
Stale Openshift Namespace Image Review and Update

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#300]
https://trello.com/c/RpOIpl1z/114-set-up-scheduled-import-of-images

Investigate allowing scheduled import of images.

[Directions for master-config.yaml changes](https://blog.openshift.com/automatically-update-red-hat-container-images-on-openshift-3-11/)

Some imagestreams are already set to auto-update and might cause some confusion for people if they actually start updating. Also people using `:latest` on some of the `openshift` images might get a surprise when their pods auto-redeploy.

ACTION: Need to come up with the update strategy for images in the `openshift` namespace and implement it.
- Acceptance criteria: specifically, apply security patches to existing tag releases at a minimum
 

Additional scope: security patches to high demand `bcgov` images (as identified by product teams in Rocketchat) e.g. caddy, ngnix, Jenkins

**Comment by lukegonis** [comment]
this is referring to add a manual review of the images in the ocp3.11 namespace and deciding which of those should be updated. should be updated to incorporate security updates for the existing version. manual updates will be performed once to cover the period until the application migration off 3.11 is complete.

**Comment by lukegonis** [comment]
we discussed not actioning this on 3.11 and instead we should make it a requirement to move to ocp4 that tams not use the latest tag.

**Comment by jefkel** [comment]
That sounds reasonable for an automated (scheduled) update, however it doesn't resolve the issue of existing outdated images in the openshift namespace (in OCP3).

After chatting with Gerald Nunn, he has identified several imageStreams with out-dated image references.  The updated versions are updated not just for new releases, but we're also missing security updates to existing image tag releases.

looking at the 155 imagestreams in the openshift namespace, the "last updated" (which could mean new versions or patches to existing versions) ranges from 4 weeks ago, to 4 years ago.

maybe we just do a manual update of all tags of a small group of images a week?  (with notifications, etc) and try to get these manually updated to something more recent?

**Comment by wmhutchison** [comment]
will look into auditing said imagestreams, prioritize the ones in actual use, and from there, we can start working on a suitable action plan.

**Comment by jefkel** [comment]
Looking for a date/resource for this ticket

**Comment by wmhutchison** [comment]
Ticket has been re-prioritized and is now in progress. ETA will be refined after some initial investigation is performed to see just how much is in actual use versus what may be configured in someone's namespace but not running.

**Comment by wmhutchison** [comment]
The vendor link to the Red Hat blog when it comes to the section involving switching on via jq tweaking of the JSON output, but it makes the assumption that 100% of the imagestreams in openshift project are 100% provided by Red Hat, where as for our current 3.11 PROD cluster there are other items now in that namespace not from Red Hat.

Thus will need to refine searching based on the following annotation parameter/value which does inform us which officially come from Red Hat and are thus supported.
```
"openshift.io/provider-display-name": "Red Hat, Inc."
```

The query should also list all imagestreams without this annotation and provide that to the rest of the stakeholders in case there are missed imagestreams needing to be captured/managed elsewhere.

**Comment by wmhutchison** [comment]
Work still in progress, working on additional jq queries to properly isolate the data we need to get from JSON exports of the target imagestreams and running pods with their image data.

May complete by the end of this week, but more likely to be finished by the start of next week.

**Comment by wmhutchison** [comment]
The jq-fu for working through each project to extract the unique Image IDs for all running pods, making sure to iterate through one project at a time with a small delay so as to not DoS the API service.

```
 oc -n <project> get pods -o json | jq ' .items[] | .status.containerStatuses[] | .image'
```

That'll give us SHA references that we can now search for inside the is objects within openshift namespace. The criteria is to return the following for an SHA match:
- the image name and matching tag
- whether or not the image is a recognized Red Hat image. Thus far as per noted above that's being done with an appropriate value set for theopenshift.io/provider-display-name.

Going to study the JSON for a single imagestream rather than the entire list in openshift namespace, so we can look more closely at the JSON structure and deferive the specific queries we need jq to do.

Another smaller todo that'll be a lot easier to setup is just to wade through all imagestream objects and note all such objects that do not appear to be managed by Red Hat. Some of these may already be reference in the Stale BCGov namespace, but I suspect there are additional imagestreams not yet being tracked that either do need to be tracked or cleaned up if no longer required.

**Comment by wmhutchison** [comment]
An extremely hackish solution to list imagestreams in openshift namespace that do not appear to have the Red Hat annotation stating its supported by them. Will review these manually and if they check out, pass along to the other stakeholders for consideration.

$ cat openshift-is.json | jq '.items[] | {name: .metadata.name, displayname: .metadata.annotations."openshift.io/provider-display-name"}' | grep -B 1 -E "displayname.*null" | grep -v displayname | grep name | awk '{ print $2 }'
"alpine",
"alpine-caddy",
"backup-pvc-apb",
"base-centos7",
"base-jdk",
"bcgov-s2i-caddy",
"bcgov-s2i-nginx",
"centos",
"dotnet",
"dotnet-runtime",
"dotnetcore-10-rhel7",
"httpd",
"jboss-decisionserver62-openshift",
"jenkins",
"jenkins-2-centos7",
"jenkins-2-rhel7",
"jenkins-slave-base-rhel7",
"jenkins-slave-bddstack",
"jenkins-slave-nodejs",
"jenkins-slave-nodejs6",
"jenkins-slave-py3nodejs",
"jenkins-slave-python-rhel7",
"jenkins-slave-python3nodejs",
"jenkins-slave-sonar",
"jenkins-slave-zap",
"jenkins2",
"mariadb",
"minio",
"mongodb",
"mysql",
"nginx",
"nginx-runtime",
"nodejs",
"oracle-client-rpms",
"patroni",
"perl",
"php",
"platform-services",
"postgis",
"postgres",
"postgresql",
"python",
"redis",
"rhel7",
"ruby",
"solr-base",
"sonarqube",
"sso74-openshift-rhel8",
"taiga-back",
"taiga-back-upstream",
"taiga-front",
"taiga-front-runtime",
"wildfly",

**Comment by wmhutchison** [comment]
Current approach I'm going to take with the openshift is json data is flatten it all into a series of arrays that have in each array the following info.

image name
tag reference
image SHA reference.

That way I can use more generic searches for matches of "is the following text in any of the arrays listed" and from there, list the image name/tag data for matches involving SHA. This might end of being refined further, but is an acceptable compromise between spending tons of time on the perfect solution versus getting the raw data refactored into a more parsable format.

**Comment by wmhutchison** [comment]
This was being starved for attention this week due to dealing with increased volume of meetings and some new operational issues that need attention (hard prune failure and associated glusterfs fun).

**Comment by wmhutchison** [comment]
Moving this back to Sprint Backlog due to a resurgence of operational issues involving NetApp block storage taking front stage again, plus going on vacation for 10 days and thus will not be in a position to put additional work into this until I return.

**Comment by wmhutchison** [comment]
The intent is to hand this over to Tatsuya and Tim for taking this off of William's plate since his workload has resulted in him making zero traction on this matter. Viably time for those individuals should start opening up as we conclude 3.11 PROD OS patching this quarter.

**Comment by tmorik** [comment]
Looking & investigating this task. Drafting a spreadsheet based on William's comments above.

**Comment by tmorik** [comment]
The spreadsheet for the namespace openshift's image stream (oc get is -n openshift) list has been created and saved under:  https://asintranet.advsol.tech/HIS/VMwareLinux/linux/Linux/Documentation/Operations%20Manual/OpenShift-pathfinder/openshift-docs/OCP3_ImageStreamCheck/openshift-is.xlsx

**Comment by sbarre-esit** [comment]
@jefkel since OCP3 is so close to decomm, I vote we close this ticket.

**Comment by jefkel** [comment]
I'd ask that @NickCorcoran weigh in re: stale/non-updated images available in a platform managed namespace as this was a security initiative to identify and potentially update any risky container images that are hosted/owned by the platform as much as it was an operational maintenance initiative.

**Comment by NickCorcoran** [comment]
@jefkel I think that trying to fix image streams on OCP3 at this point is not going to help us much.  The bigger thing to look at is if the same image streams are being used to deploy apps on OCP4.  If yes, then we have a problem, as we're porting the problem to our new platform.  I agree that we need to have something that triggers visibility or automatically updates based on security patches and major version changes to the images called those image streams are pulling down.

**Comment by sbarre-esit** [comment]
> if the same image streams are being used to deploy apps on OCP4

As part of the [Image Management Plan](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/362) we've reduced the number of sample images. The ones left are updated as part of quarterly OCP patching.

Images in the `bcgov` namespace will all be set up with CI/CD to ensure they are rebuilt regularly.
