### ISSUE TITLE
OCP 4.10 Test enabling HTTP Compression in CLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3002]
**Describe the issue**
In OCP 4.10 we can enable compression in HAProxy of select MIMETypes.

https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-ne-router-compression

> **Ingress Controller router compression**
> This enhancement adds the ability to configure global HTTP traffic compression on the HAProxy Ingress Controller for specific MIME types. This update enables gzip-compression of your ingress workloads when there are large amounts of compressible routed traffic.
> 
> For more information, see [Using router compression](https://docs.openshift.com/container-platform/4.10/networking/ingress-operator.html#nw-configuring-router-compression_configuring-ingress).

There's a list of mimetypes that should be compressed at https://letstalkaboutwebperf.com/en/gzip-brotli-server-config/ - tried using the full list but Openshift wouldn't accept some of the mimetypes. Those have been removed.

**What is the Value/Impact?**
This will improve the performance of web pages for apps that haven't configured compression themselves.

**What is the plan? How will this get completed?**
- Test in CLAB
- Discuss with Matt on if there are any risks, what he thinks of the mimetype list (Gerald was concerned about compressing json)
- Update playbooks/docs to include compression config in the rest of the clusters during their upgrades

**Identify any dependencies**
Need feedback from Matt before moving it to PROD

**Definition of done**

- [x] HTTP Compression enabled in CLAB, and upgrade steps for the rest of the clusters documented.

**Comment by tbaker1313** [comment]
Added this list of mime types and enabled compression in CLAB:
spec:
  httpCompression:
    mimeTypes:
	- "text/html"
    - "text/css"
    - "text/plain"
    - "text/xml"
    - "text/x-component"
    - "text/javascript"
    - "application/x-javascript"
    - "application/javascript"
    - "application/json"
    - "application/manifest+json"
    - "application/vnd.api+json"
    - "application/xml"
    - "application/xhtml+xml"
    - "application/rss+xml"
    - "application/atom+xml"
    - "application/vnd.ms-fontobject"
    - "application/x-font-ttf"
    - "application/x-font-opentype"
    - "application/x-font-truetype"
    - "image/svg+xml"
    - "image/x-icon"
    - "image/vnd.microsoft.icon"
    - "font/ttf"
    - "font/eot"
    - "font/otf"
    - "font/opentype"

**Comment by tbaker1313** [comment]
This is implemented, instructions have been added to the upgrade docs.

**Comment by tbaker1313** [comment]
Closing this as testing was successful in CLAB and will create new RFCs and tickets for implementing in PROD.
