### ISSUE TITLE
Updates to OCP101 for the 4.10 upgrade

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3003]
**Describe the issue**
OCP 4.10 adds some new things that should be included in the OCP 101 course.

**Additional context**
https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#ocp-4-10-web-console-developer-perspective

> With this update, creating pipelines workflow has now been enhanced:
> - You can now choose a user-defined pipeline from a drop-down list while importing your application from the Import from Git pipeline workflow.
> - Default webhooks are added for the pipelines that are created using Import from Git workflow and the URL is visible in the side panel of the selected resources in the Topology view.
> - You can now opt out of the default Tekton Hub integration by setting the parameter enable-devconsole-integration to false in the TektonConfig custom resource.
> - Pipeline builder contains the Tekton Hub tasks that are supported by the cluster, all other unsupported tasks are excluded from the list.

https://docs.openshift.com/container-platform/4.10/release_notes/ocp-4-10-release-notes.html#pod-debug-mode-web-console

> With this update, you can now view debug terminals in the web console. When a pod has a container that is in a CrashLoopBackOff state, a debug pod can be launched. A terminal interface is displayed and can be used to debug the crash looping container.

**How does this benefit the users of our platform?**
Improved training

**Definition of done**
Training material updated

**Comment by mtspn** [comment]
I've added notes into the relevant training topics to reflect these updates. 

OpenShift 101: [Deployment - CrashLoopBackOff](https://github.com/BCDevOps/devops-platform-workshops/blob/master/101-lab/content/03_deployment.md)
OpenShift 201: [Pipelines](https://github.com/BCDevOps/devops-platform-workshops/blob/master/openshift-201/pipelines.md)
