### ISSUE TITLE
Investigate Performance Tuning options for NetApp Virtual Appliances

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#303]
https://trello.com/c/5b8X20nl/137-investigate-performance-tuning-options-for-netapp-virtual-appliances

Now that we have the NetApp Virtual Appliance live in the 3.11 production cluster, we have a need to track some performance statistics

**Comment by lukegonis** [comment]
Closing this issue as it will b tracked in OCP4 buildout board
