### ISSUE TITLE
Add decision maker functionality to the web 

### ISSUE THREAD

**Issue by okanji** [BCDevOps/developer-experience#3036]
An admin should be able to reject or approve a project edit or create request made by a user. An admin should have the option to:

a) Approve a project edit or create request
b) Reject a project edit or create request

Add these buttons corresponding to the above to the request page.

DOD:

- [x] Submit button 
- [x] Reject button
- [x] The appropriate call is made to the API

**Comment by mitovskaol** [comment]
@okanji it would be helpful to have more context for this ticket as it is unclear to me what requests would be handled by an admin approver.

**Comment by okanji** [comment]
@mitovskaol, I'm sorry for the late reply. I will add that context

**Comment by okanji** [comment]
I have added the **approve** and **reject**

![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/0d74e53a-4ff7-434e-8e94-acc1ee8640a9)
