### ISSUE TITLE
Content and Design Tweaks to Product Owner's Site

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3040]
**Describe the issue**
Small content and design edits for the product owners site, based off of the [design decision log](https://docs.google.com/spreadsheets/d/1GcKZ7PgxCyPESw02ul6qbeai-xB9jSeCnvwp-2bIQXY/edit#gid=2052166830).

**Additional context**
Based off of ticket #2977's results 

**How does this benefit the users of our platform?**
Addresses needs identified in user research.

**Definition of done**
All small edits are completed and published.

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore.
