### ISSUE TITLE
Fix ocp-monitor crashes on registry disk usage check

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#305]
https://trello.com/c/8TYDmYeD/144-fix-ocp-monitor-crashes-on-registry-disk-usage-check

https://github.com/bcgov-c/platform-ops/issues/145

**Comment by wmhutchison** [comment]
Can be closed - the script was modified to only specify registry pods that are in a 1/1 Ready state. Also Nagios freshness check now exists so if the monitoring script crashes for any reason (including this), we are notified.
