### ISSUE TITLE
Analytics for the Private Cloud Technical Documentation site

### ISSUE THREAD

**Issue by ty2k** [BCDevOps/developer-experience#3054]
The Private Cloud Technical Documentation site does not currently have a way for us to view analytics for visitors using the site. Add analytics tracking using the GDX Analytics product (Looker-Snowplow) or another alternative to allow us to collect data about how our visitors are using the website.

**Additional context**
I have a meeting booked with Dan Pollock (GDX Analytics product owner) for Tuesday, September 20 to discuss requirements to use this integration. Unlike in [our WordPress site](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/3050), this will require some kind of code change on our part. I'm assuming based on previous experience with Google Analytics that this will be a simple addition of a `<script>` tag that references the Snowplow tracking script, but I will know more after this meeting.

Also, depending on cost and features, we may want to look into Matomo or similar self-serve analytics options. I am hesitant to roll our own solution when there is an enterprise service available, however. If we go this option, this ticket might just end up as a spike, with a more involved self-serve path broken into several tickets.

**How does this benefit the users of our platform?**
Collecting analytics data will allow us to see which pages users are visiting and how frequently. This data can be used to continually improve our content by showing us where people are spending more time/less time, which pages aren't getting traffic when we would hope they do, etc.

**Definition of done**
- [ ] An analytics tracker is in place on the site
- [ ] Our team (especially Service Design) has access to the data being collected by the tracker

**Comment by ty2k** [comment]
To use the GDX Analytics product in our Technical Documentation site, we will have to pay a license for the Looker dashboard portion of the integration. Assuming we are using the same user group as is being used in our Private Cloud WordPress site (#3050), the cost would be $50 for the new site's license. It would be $100 if using a different user group to account.

For billing:

> For the second site, we’ll just need an email from Olena authorizing adding the second site to your account (already signed up with the DES Team at GDX). We’ll just add it in the billing system.

We would need custom front-end code as detailed in #3070, and it sounds like the GDX Analytics team will be able to help us write this code.

**Comment by ty2k** [comment]
Example Snowplow tracker plugins that we might be able to use directly or as sample code:
- https://www.npmjs.com/package/gatsby-plugin-snowplow-tracker
- https://www.gatsbyjs.com/plugins/gatsby-plugin-snowplow-bc/

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore. Can be closed.
