### ISSUE TITLE
Create CI/CD pipeline 

### ISSUE THREAD

**Issue by okanji** [BCDevOps/developer-experience#3055]
A continuous integration and continuous deployment (CI/CD) pipeline is a series of steps that must be performed in order to deliver a new version of software.

This needs to be set up for the new project registry 

**Context**
The pipeline already exists, talk to @IanKWatts about how to duplicate this for the new registry

@w8896699 will help with this,

**Comment by w8896699** [comment]
pair programing this

**Comment by w8896699** [comment]
Successfully deploy web, https://platsrv-registry-web-platform-registry-dev.apps.silver.devops.gov.bc.ca. 
Added kustomize template and instructions of how to use it.
