### ISSUE TITLE
Usability testing for Product Registry #3057

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3061]
Describe the issue
The new product registry will be launched soon. Usability testing is needed on the DEV version of the site to ensure all functionalities from the old site are present on the new site.

Additional context
Will need to ask Oamar about timing and access for the actual testing

How does this benefit the users of our platform?
Making sure Product Owners, Technical Leads, and Admins needs are met in terms of functionality.

Definition of done

- [ ] Usability is tested completed and recorded.

- [ ] Any changes that need to be made to the registry are recorded as tickets in ZenHub

**Comment by Iryna-Kaplun** [comment]
This epic got moved to the registry repo #1015.
