### ISSUE TITLE
Ensure glusterfs pods have the hostPath for /core set

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#307]
https://trello.com/c/4UGVQENv/146-ensure-glusterfs-pods-have-the-hostpath-for-core-set

https://github.com/bcgov-c/platform-ops/issues/142

**Comment by wmhutchison** [comment]
Documenting this now so it doesn't get forgotten again. Testing and confirming as well in the 3.11 LAB.

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/advsol-docs/pull/98 created/reviewed/approved and the associated changes in LAB are being made. Closing off.
