### ISSUE TITLE
Document ROSA in AWS SEA exceptions

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#3074]
I believe some exceptions have been made in the BC Gov AWS SEA SCPs to allow for ROSA to install.

If we can call out those exceptions then Red Hat can work through or at least bring up the issues with the ROSA team to fix.

Some items are already in progress.

https://issues.redhat.com/browse/SDE-1239 - Private DNS issue
https://issues.redhat.com/browse/CORS-2282 - Un-installer error logs

**Comment by StevenBarre** [comment]
https://mobb.ninja/docs/rosa/rosa-asea-landing-zone/ has docs on updated steps for SEA.

We did an install live using the RH Console. Can we formalize and document it as a `rosa` cli call instead? Make it more reapeatable.

**Comment by filiy** [comment]
This work isn't needed anymore as the updated SEA and ROSA installer seem to work nice now. This is called out in the mobb article. 

We'll make sure we go through the install via the CLI one more time.
