### ISSUE TITLE
RITM0064531 - New tracking/monitoring for node Kubelet client certs

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#309]
https://trello.com/c/JZSM3xwU/148-new-tracking-monitoring-for-node-kubelet-client-certs

https://github.com/bcgov-c/platform-ops/issues/139

**Comment by wmhutchison** [comment]
Creating a matching theHub tracking ticket for this one to improve visbility and need to implement.

Just finished a LAB master cert refresh run today, and on a whim, checked `oc get csr` and found pending approval CSR's dating back a day meaning these were not triggered by the master cert refresh per se.

Will be re-testing the current master cert renewal playbook once more in LAB with a clean slate of approved csr's to confirm if this work is also forcing node cert renewals or if it was just that csr's are coming due in LAB.

**Comment by tbaker1313** [comment]
This has been implemented and runs once daily @ 0900. Appears to be working correctly - will monitor for a day before closing.

**Comment by tbaker1313** [comment]
This is working correctly and detecting pending CSR requests once per day.
