### ISSUE TITLE
Apply temporary fix for 'oc get all' when using pipelines and clean up

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3093]
**Describe the issue**
Some users are experiencing an issue when they issue the command `oc get all` - it gives them a permission denied error and can break some scripts. 

**Additional context**
https://access.redhat.com/solutions/6975952
Tracked under RH Case 03314411

**How does this benefit the users of our platform?**
Allows scripts to work normally until the pipeline operator is upgraded to 1.8.1

**Definition of done**
- [x] Identify which users are encountering the issue
- [x] Apply some rbac permissions to allow the users to see tekton resolution requests
- [x] When pipelines are upgraded, remove the permissions added above

**Comment by tbaker1313** [comment]
Added the following to test. New pipeline release should fix this permanently within 2 weeks:
clusterrole pipelines-as-code-cleanup-job
clusterrolebinding pipelines-as-code-cleanup-job
clusterrole tekton-info-aggregate-view

**Comment by tbaker1313** [comment]
Tested and the clusterrole tekton-info-aggregate-view appears to have fixed the problem. Will monitor and close this ticket when the actual pipeline upgrade fix happens and the additional clusterroles and rolebindings are removed.

**Comment by StevenBarre** [comment]
Can we split this ticket and close the first half? It might be a while until the operator is updated and no point adding the ticket to each sprint while we wait.

**Comment by tbaker1313** [comment]
Closing and creating a new ticket to revert the rbac changes.
