### ISSUE TITLE
Rebuild KLAB test node to SILVER APP node

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3094]
**Describe the issue**
Build 4 new nodes:
- 3 SILVER app nodes
- 1 KLAB app node for temporary testing

**Additional context**
RITM0123940 - SILVER APP 45
RITM0123941 - SILVER APP 46
RITM0123938 - SILVER APP 47
RITM0123939 - Temporary KLAB APP 05

**How does this benefit the users of our platform?**
Adding capacity.

**Definition of done**

- [x] MCS-SILVER-APP-45.dmz built
- [x] MCS-SILVER-APP-45.dmz tested
- [x] MCS-SILVER-APP-46.dmz built
- [x] MCS-SILVER-APP-46.dmz tested
- [x] MCS-SILVER-APP-47.dmz built
- [x] MCS-SILVER-APP-47.dmz tested
- [x] MCS-KLAB-APP-05.dmz built
- [x] MCS-KLAB-APP-05.dmz tested

- [ ] Eventually rebuild MCS-KLAB-APP-05 to MCS-SILVER-APP-48
- [ ] Ensure when rebuilding the klab node back to a silver app node that the records are updated.

**Comment by tbaker1313** [comment]
Servers handed over, the MCS-KLAB-APP-05 server will be rebuild to MCS-SILVER-APP-48 when some KLAB testing is completed.

**Comment by StevenBarre** [comment]
Can we close this ticket as done and open a separate one in the backlog for the node rebuild? Else this might just get dragged along for a few sprints blocked waiting on Jasons testing.

**Comment by tbaker1313** [comment]
Completed.
