### ISSUE TITLE
Test Logging Operator and AWS CloudWatch on the Government ROSA Cluster

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#3096]
~To find the best solution for log monitoring of Govt ROSA clusters, such as CloudWatch or EFK, we need to install and test the Cluster Logging Operator Add-on on a test ROSA cluster.~

Based on the [internal ROSA logging testing](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2971) and [logs will be sent to govt SEIM](https://chat.developer.gov.bc.ca/channel/aws-how-to?msg=Aty7ZvmykffsWHxL5), CloudWatch is preferable solution. We will change the goal for this ticket to install CloudWatch Logging to rosa-lab and test it. 

## Additional context

- https://mobb.ninja/docs/rosa/sts-cluster-logging-addon/
- Logging: https://www.rosaworkshop.io/ostoy/9-logging/
- RH Case: https://access.redhat.com/support/cases/#/case/03278768/discussion
- https://chat.developer.gov.bc.ca/channel/aws-how-to?msg=Aty7ZvmykffsWHxL5

## Definition of done

- [x] Install CloudWatch Logging to rosa-lab
- [x] Test manual steps
- [x] Test automated steps using Ansible
- [x] Documenting

**Comment by StevenBarre** [comment]
Lets change the goal of this to "install CloudWatch Logging to rosa-lab"

**Comment by tmorik** [comment]
RH case opened.  https://access.redhat.com/support/cases/#/case/03346248
cluster logging operator installation for ROSA STS is failing.

**Comment by tmorik** [comment]
Asking help in RC channel also: https://chat.developer.gov.bc.ca/group/devops-rosa-operations?msg=jsa9nsThkRZbCykzm

**Comment by StevenBarre** [comment]
Firewall issues in SEA fixed, old version of cluster logging addon removed from rosa-lab, and got some docs from the support case. Moving this back to in progress now that @tmorik can take another run at this.

It appears we can install the regular EFK stack and then just set up log forwarding to CloudWatch similar to how we ship logs to SIEM today.

**Comment by tmorik** [comment]
With the workaround that has been provides from RH support - [Case 03346248 - set up cluster logging operator for ROSA STS](https://access.redhat.com/support/cases/#/case/03346248) - , the logging-operator has been installed on the `rosa-lab` cluster.

```
//Logs are sent to CloudWatch

[root@localhost ~]# aws logs describe-log-groups --log-group-name-prefix rosa-lab
{
    "logGroups": [
        {
            "logGroupName": "rosa-lab.audit",
            "creationTime": 1668631025814,
            "retentionInDays": 731,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:ca-central-1:646284873784:log-group:rosa-lab.audit:*",
            "storedBytes": 0
        },
        {
            "logGroupName": "rosa-lab.costmanagement-metrics-operator",
            "creationTime": 1668631386657,
            "retentionInDays": 731,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:ca-central-1:646284873784:log-group:rosa-lab.costmanagement-metrics-operator:*",
            "storedBytes": 0
        },
        {
            "logGroupName": "rosa-lab.infrastructure",
            "creationTime": 1668631016572,
            "retentionInDays": 731,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:ca-central-1:646284873784:log-group:rosa-lab.infrastructure:*",
            "storedBytes": 0
        },
        {
            "logGroupName": "rosa-lab.sealed-secrets",
            "creationTime": 1668631529759,
            "retentionInDays": 731,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:ca-central-1:646284873784:log-group:rosa-lab.sealed-secrets:*",
            "storedBytes": 0
        },
        {
            "logGroupName": "rosa-lab.steve-test",
            "creationTime": 1668631527877,
            "retentionInDays": 731,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:ca-central-1:646284873784:log-group:rosa-lab.steve-test:*",
            "storedBytes": 0
        },
        {
            "logGroupName": "rosa-lab.tester",
            "creationTime": 1668631387606,
            "retentionInDays": 731,
            "metricFilterCount": 0,
            "arn": "arn:aws:logs:ca-central-1:646284873784:log-group:rosa-lab.tester:*",
            "storedBytes": 0
        }
    ]
}
```

On the AWS console you can query against the forwarded logs:

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/cd483a8f-821c-4a9f-96d8-f9fe1c4f32f3)

However, this workaround appears to compromise the security of the cluster, and according to a RedHat bug report (the source of this workaround), it is necessary to use an appropriate RBAC for logcollector DeamonSet. 

RH case is still opened and chasing the issue.

**Comment by tmorik** [comment]
Doc PR: https://github.dxc.com/AdvSol/mcs-operations-manual/pull/11

**Comment by tmorik** [comment]
As par discussion in the PR, `Deploy logging and ES operators using ansilbe` will be investigated and tested and documented.

**Comment by tmorik** [comment]
Install EFK operator to the rosa-lab cluster, Kibana and Elasticsearch pods are up and running with the collector that has been installed with CloudWatch integration.  

However, it looks like Kibana WebConsole is not able to see the all indices in the elasticsearch, thus user cannot create a new index pattern.

indices on the ES

```
[root@localhost efk-logging]# oc -n $NS exec -c elasticsearch $ES_POD -- es_util --query='_cat/indices/?v'
health status index                                  uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   app-000001                             EAsTM8VdQaidKS-LZvMVfQ   3   1          0            0      1.5kb           783b
green  open   audit-000001                           2rnT3tMqQXivqXu0TmMG-Q   3   1          0            0      1.5kb           783b
green  open   .security                              7HIQsWlnRCGbbpxaVjb9Jg   1   1          6            0     53.2kb         33.2kb
green  open   .kibana_1                              UqifrC4jQXa3pZmCHNsiFA   1   1          0            0       522b           261b
green  open   .kibana_-201621928_stevenbarregithub_1 O2_SBhKVQL6TnZQs8VxhEg   1   1          1            0      7.4kb          3.7kb
green  open   infra-000001                           iem2NB1FTlKBf0e2EEZa3A   3   1          0            0      1.5kb           783b
green  open   .kibana_1325707180_admindu1odc_1       -P-ZQqLASxidmYqy5t-QeA   1   1          1            0      7.4kb          3.7kb
```

But only a few of them in the kibana web console

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/a4f7f616-d1b8-4a30-ae37-977166ef035a)


I will open a RH case about this issue.

**Comment by tmorik** [comment]
Event router has been set up on ROSA and confirmed it's up and running. 

- https://github.dxc.com/AdvSol/mcs-operations-manual/blob/main/rosa/How-to-setup-Cluster-Logging.md#deploying-and-configuring-the-event-router-for-rosa-for-govt-advsol-rosa-both

Currently working on the playbook building.

**Comment by tmorik** [comment]
The playbook PR above is merged into main repo.

**Comment by tmorik** [comment]
Doc PR (MCS repo): https://github.dxc.com/AdvSol/mcs-operations-manual/pull/14
