### ISSUE TITLE
Document Rollout Strategy for replacing Github IDs for IDIR for POs and TLs in Registry

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#3099]
As we are replacing GitHub IDs with IDIR for Product Owner and Tech Leads contacts in the Registry we need to ensure that this change will not impact the existing admin access for users in Openshift that is currently assigned to their GitHub IDs.

**some of the things to consider**
Document the suggested approach to gradually replacing GitHub IDs with IDIRs when any change to a product record is initiated in the Registry (do not allow saving any changes to the record until IDIR field for PO and TLs are populated, display a message notifying the user that the admin access to the product namespaces in Openshift will assigned to the IDIR)
Analyse the impact on this change on the existing users that currently have admin access tied to their GitHub IDs
Confirm that one all new project proivsonnng requests IDIR info will be collected for POs and TLs instead of GitHub

**Dependencies**
- [x] this document/plan is required before implementing the change

 **Definition of done/Acceptance Criteria**
- [x] document the impact of this change on the users in existing OpenShift projects and new ones. This includes documenting access to all integrated systems i.e. openshift, Vault, Artifactory, etc that is tied to a GitHub ID and confirming that the access will still work once GitHub ID is replaced with IDIR
- [x] sign off on strategy by PO and Security Architect

**Comment by mitovskaol** [comment]
@ShovelHand I wrote down some suggestions for the roll out strategy that you will be working on as part of this ticket.

**Comment by ShovelHand** [comment]
Here is a link to the draft message https://docs.google.com/document/d/1UCE1EJH0bnEc5U2DR1ATQUv-4p_nsEAFfuJQAVYAm8A/edit?usp=sharing

**Comment by w8896699** [comment]
I updated ACS side of authentication to use email instead of name. 
https://github.com/BC-Gov-PaaS-Platform-Services/acs-automation/tree/test

I have push it to a test image branch so we can test it first and merge it when we make sure it's ready.

**Comment by ShovelHand** [comment]
Artifactory, ACS and Vault have all been tested and confirmed to work with this change, and the README has been updated in the repo to document these changes. 
@mitovskaol @NickCorcoran Last thing is for you to sign off on the changes.

**Comment by mitovskaol** [comment]
Thank you for the thourough work on this , Alex! I am singing off on this change. Please feel free to close the ticket.

**Comment by ShovelHand** [comment]
Thrilled to close this out. Thanks, everyone!
