### ISSUE TITLE
Automate NetApp Storage Efficiency playbook

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#310]
https://trello.com/c/uWBiBa0j/149-automate-netapp-storage-efficiency-playbook

We have a playbook than ensures all the FlexVolumes created by Trident have Deduplication and Compression enabled, but need to automate it to run once a day to catch any newly created volumes.
https://github.com/bcgov-c/platform-ops/issues/133

**Comment by lukegonis** [comment]
process will be manual for ocp3 and not required for ocp4.
