### ISSUE TITLE
SDN - Investigate automation of management of proxy include script on NSX-T based UTIL servers

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3107]
**Describe the issue**
At present we have an include file titled '/etc/profile.d/proxy.sh' that now exists on both the EMERALD and KLAB2 UTIL server. It is there to configure use of the forward proxy by the server itself and also provide suitable proxy exemptions.

This should be baked into the existing playbooks meant for setting up a UTIL server so that the values are being consistent and nothing gets missed. 

**Definition of done**
- [x] Add content for ansible config-nsx-util playbook to automate the creation and management of this proxy include file.
- [x] Test to confirm the changes reliably manage the file on both KLAB2 and EMERALD.
- [x] Merge associated PR once successfully tested.

**Comment by StevenBarre** [comment]
https://github.dxc.com/AdvSol/mcs-ansible-tower/pull/15
