### ISSUE TITLE
Monitor state of /etc/containers/registries.conf

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#311]
https://trello.com/c/nmqHc3mq/150-monitor-state-of-etc-containers-registriesconf

https://github.com/bcgov-c/platform-ops/issues/116

**Comment by wmhutchison** [comment]
This will be turned into a documentation point for our OCP upgrade versus any active monitoring check involving the existing ocp-monitor which already is too large. This file is only touched during official OCP upgrade playbook executions.

The Red Hat case for it remains open and unresolved (still in progress) as to when they will fix this.

**Comment by mitovskaol** [comment]
No impact on clients creating images, only has impact on internal ugprades. Work is still in progress.

**Comment by wmhutchison** [comment]
Closing this off. Does not impact users or regular OCP upgrades (just OCS which is being handled manually now by instruction by Red Hat). The vendor ticket has also clarified this will not likely be addressed/fixed in OCP3.
