### ISSUE TITLE
Display subnet info for project namespaces in Registry UI

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#3112]
Apps hosted in the Emerald Cluster had /24 subnet information generated for them at the time of provisioning namespaces as described in [this document](https://cloud.gov.bc.ca/private-cloud/nsx-networking/) (IDIR protected). This information resides in Openshift as part of the namespace meta information. Product teams would like to see this information displayed on the product detail page in the Registry UI.

At this moment the information is only passed from the Registry app to the provisioner to Openshift. This feature requires building the second communication line where information can be passed from Openshift to the provisioner to the Registry app.

DoD:
- [ ] /24 subnet information is displayed on the product detail page in the Registry **for Emerald namespaces**.

**Comment by Iryna-Kaplun** [comment]
This epic is duplicated on the registry repo #1013. This one will be closed and #1013 will be the main one for this work.
