### ISSUE TITLE
Document how to install ROSA in Gov SEA

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3113]
**Describe the issue**
There's some custom steps needed to install ROSA into the BC Gov SEA. Document the needed steps.

**What is the Value/Impact?**
Easy to install more clusters in the future.

**What is the plan? How will this get completed?**
Add doc to https://github.com/bcgov-c/advsol-docs

**Identify any dependencies**
Need help from RH Phil 

**Definition of done**
PR merged

**Comment by tmorik** [comment]
Doc repo : https://github.dxc.com/AdvSol/mcs-operations-manual/pull/15

**Comment by tmorik** [comment]
Doc has been merged!
