### ISSUE TITLE
SSO realm merge planning - Mautic

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3115]
**Describe the issue**
we will be merging the realm this service uses to another central realm. This ticket is to find out what's the impact and if the merge is doable for this service.

**What is the Value/Impact?**
this is to get prepared for SSO Gold migration.

**What is the plan? How will this get completed?**
Discussion with Service Lead, testing, planning

**Identify any dependencies**
yes, I need to gather a list of all SSO usages first!

**Definition of done**
 - [x] identify service's SSO usage
 - [x] discuss if realm merge is doable
 - [x] come up with testing plan

**Comment by w8896699** [comment]
Testing plan:
We have three Gold SSO realm env:
dev https://dev.loginproxy.gov.bc.ca/auth/admin/platform-services/console/
test https://test.loginproxy.gov.bc.ca/auth/admin/platform-services/console/
prod https://loginproxy.gov.bc.ca/auth/admin/platform-services/console/

For each environment, I will use localhost Mautic to test if the realm that I created works properly with different kinds of account(github, idir)

After working on localhost, I will push the config change to the corresponding environment and test with different types of accound.
