### ISSUE TITLE
Set 3Par specific settings via Ansible

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#312]
https://trello.com/c/4jH6YrIK/151-set-3par-specific-settings-via-ansible

3Par needs some specific settings in device mapper config to ensure optimal performance. They've been set by hand for now but should be managed by Ansible during quarterly patching.
https://github.com/bcgov-c/platform-ops/issues/107

**Comment by lukegonis** [comment]
complete
