### ISSUE TITLE
Investigate user-defined alerting to ensure it doesnt alert on-call team

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3120]
**Describe the issue**
This https://github.com/bcgov-c/platform-ops/blob/c7e66db40ba469829f6ede77ea7bb8df109f7435/roles/config-infra/templates/alertmanager.yaml.j2#L19-L21 was added to the AlertManager config to hide user defined alerts from the Ops team. But a recent test seems to show that it is no longer catching user defined alerts.

**What is the Value/Impact?**
Prevent product teams from creating alerts that wake up on-call

**What is the plan? How will this get completed?**
Create a user-defined alert [PrometheusRule](https://docs.openshift.com/container-platform/4.10/monitoring/managing-alerts.html#creating-alerting-rules-for-user-defined-projects_managing-alerts) that is firing. Test that it doesnt alert on-call.

**Identify any dependencies**
May need to open a case with Red Hat for advice.

**Definition of done**
Solution in place to prevent users from making alerts that go to on-call.

**Comment by tbaker1313** [comment]
Implemented the recommended adjustment and tested. Adjusted the alertmanager playbook via PR for future use.
