### ISSUE TITLE
Knowledge transfer

### ISSUE THREAD

**Issue by ShovelHand** [BCDevOps/developer-experience#3121]
Between Billy, Zhanna and Alex. 

DoD:
Billy will mock up a couple of registry bug scenario:

- [x] Project stuck in pending edit or approved
   * able to analyze possible issues and solve them accordingly.

- [x] User can not login to dashboard
- [x] Registry failed to load the dashboard
- [x] Registry need cluster wide update

**Comment by ty2k** [comment]
Besides "user can not login to dashboard", I'm also interested in the situation where a user can log in, sees their dashboard momentarily, and then gets logged out back to `/public-landing?redirect=/dashboard`.

**Comment by w8896699** [comment]
Also need to learn how to use backup container

**Comment by w8896699** [comment]
I have create this doc: https://github.com/bcgov/platform-services-registry/pull/787/files

**Comment by w8896699** [comment]
https://github.com/bcgov/platform-services-registry/blob/master/docs/Registry-debug.md

I have walked through the KT session with main supports of the Registry application and answered all questions to make sure they know as much as I do.
