### ISSUE TITLE
Add more info about services provisioned through Registry to the confirmation email

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#3125]
When app namespaces - dev, test, tools and prod - are provisioned in Openshift through Registry, the confirmation email is sent to the Product Owner and Technical Leads listed on provisioning request form, that includes details about the namespaces and a link to the Openshift Console to access them.

At the time of the provisioning of the namespaces, the following service accounts are created in the namespace that provides access to Vault and Artifactory services:
- 2 Artifactory service accounts prod and non-prod and 2 user accounts assigned to the 2TLs listed on the request form
- 2 Vault service accounts prod and non-prod
- ACS integration
Also,  PO and Tech Leads listed on the form are assigned admin access to the namespaces and can add other team members as necessary. If a PO or a TL is removed as a contract for a product in the Registry on the product details page and replaced with a new contact, the only contact loses admin access to the product namespaces and a new contract assumes admin access.

We need to update the namespace provision confirmation email to include above-mentioned details.

Link to our products documentation: https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/

**NOTE:** Talk to @IanKWatts to find our about everything that gets provisioned in addition to the namespaces.

DoD:
- [x] The confirmation email that is sent out at the end of the product namespace provisioning from the Registry is updated to include the information about everything that is created in addition to the namespaces themselves.
- [x] @mitovskaol @alexandralloyd have reviewed and provided feedback

**Comment by Kolezhanchik** [comment]
https://github.com/bcgov/platform-services-registry-api/blob/main/src/ches/templates/provisioning-request-done.html

**Comment by mitovskaol** [comment]
@Kolezhanchik Can you please post the text only for the email in a comment, it would be easier for me to read and comment on :) Thank you!

**Comment by Kolezhanchik** [comment]
@mitovskaol  it is just a link to the original template - to know where to find it

**Comment by Kolezhanchik** [comment]
the text was provided by Ian Watts, it is possible to see and to comment it here https://docs.google.com/document/d/10W3p4faTs-CFwuu_kxSPIUUI-3GozOHDj1NE7RW-w_c/edit?usp=sharing
it could look like this an email 
![image.png](https://images.zenhubusercontent.com/62c35ec2ef07f0a53a3f3d28/e8e3c817-3882-46fb-b3a8-effaa2671334)

**Comment by mitovskaol** [comment]
@Kolezhanchik Can you please re-post the email text into the body of this tickets so that I can my edits in it. Also, the provisioning confirmation email should include a link to the Openshift console for accessing the namespaces.

**Comment by Kolezhanchik** [comment]
that is the whole email text, 

Good News!

Your request for a new namespace set is done; logon to the cluster console and you'll see all four namespaces. If you have any more questions reach out to the Platform Services team in the #devops-how-to channel in RocketChat.

{{ humanActionComment }}

Product Details
Product Name:	{{ projectName }}
Product Owner:	
{{ POName }}
{{ POEmail }}
Technical Contact:	{% for technicalLead in technicalLeads %} {% endfor %}
{{ technicalLead.firstName }} {{ technicalLead.lastName }}
{{ technicalLead.email }}
To find out more detailed information regarding your product, edit product details or submit quota upgrade requests, login to the [Product Registry](https://registry.developer.gov.bc.ca/)
Namespace Details
OpenShift Cluster:	{{ setCluster }}
Dev Namespace:	{{ licensePlate }}-dev
Test Namespace:	{{ licensePlate }}-test
Prod Namespace:	{{ licensePlate }}-prod
Tools Namespace:	{{ licensePlate }}-tools
The Product Owner and the Technical Lead has been provisioned with admin access to the namespaces above and can add other users as necessary.
Your new OpenShift project set includes access to supplementary services, including the Artifactory artifact repository, the Vault secrets management system, and the Advanced Cluster Security (ACS) security platform.
 
Artifactory
Artifactory is an artifact repository system.
- A service account has been created for you with read access to Artifactory. This includes locally cached container images for faster builds and pod startup, as well as access to useful pre-built images maintained by the Platform Services Team.
Basic Artifactory usage: [more information here](https://beta-docs.developer.gov.bc.ca/image-artifact-management-with-artifactory/)
Prebuilt images: [more information here](https://beta-docs.developer.gov.bc.ca/prebuilt-images/)
General information:[ find it here](https://jfrog.com/artifactory/) 
- It is also possible to create your own project in Artifactory for storing builds and other artifacts. [more information here](https://beta-docs.developer.gov.bc.ca/setup-artifactory-project-repository/)
 
Vault
Vault is an identity-based secret and encryption management system. Use it to securely access and store your secrets.
- Access is automatically been granted to Product Owners and Technical Leads.
- A service account is created automatically for Vault access in your deployment manifests.
Vault overview: [find it here](https://beta-docs.developer.gov.bc.ca/vault-secrets-management-service/)
Vault getting started guide:[ find it here](https://beta-docs.developer.gov.bc.ca/vault-getting-started-guide/)
General information: [find it here](https://www.vaultproject.io/)
 
ACS
Red Hat Advanced Cluster Security helps you enforce DevOps and security best practices in your application.
- An access role and scope are created for your project set automatically.
- A service account is created automatically for Vault access in your deployment manifests.
ACS overview: [find it here](https://cloud.gov.bc.ca/private-cloud/our-products-in-the-private-cloud-paas/container-scanning-with-redhat-advanced-cluster-security-service/)
General information: [find it here](https://www.redhat.com/en/technologies/cloud-computing/openshift/advanced-cluster-security-kubernetes)
Do not forget to check the [OCP 4 Migration Guide](https://github.com/BCDevOps/OpenShift4-Migration) and it’s [Q&A section](https://github.com/BCDevOps/OpenShift4-Migration) and connect with other teams working on the OCP 4 Platform in RocketChat’s [#devops-ocp4-migration channel.](https://chat.developer.gov.bc.ca/channel/devops-ocp4-migration)

**Comment by alexandralloyd** [comment]
Added my comments/edits to the Google Doc

**Comment by mitovskaol** [comment]
I've added my changes as well. @Kolezhanchik Can we please make the "Llog on to the cluster console" into a hyperlink and auto generate the link to the console based on the cluster name
