### ISSUE TITLE
Fix Flyway migrations for M1 Macs in Product Registry

### ISSUE THREAD

**Issue by ty2k** [BCDevOps/developer-experience#3128]
**Describe the issue**
The Flyway migrations in the Platform Product Registry repository are used to make changes to the application's PostgreSQL database schema in a versioned manner. Using migrations allows for changing the schema and included seed data atomically as the need arises (ex: increase the length of the email address field with a migration, add a new cluster to the registry's `ref_cluster` table with new seed data).

Developers on new Government-issued MacBook Pro laptops with M1 chip architecture ("Apple silicon") have experienced issues with the Flyway container appearing to start with no log output, 100% CPU usage, and no resulting changes to the Postgres database. Jason Leach has demonstrated a method for us to spin up local databases using a dump of the production database, which allows for local development that doesn't involve the Flyway scripts. For schema changes, it's necessary to have a working Flyway container to be able to write and test the new migrations/seeds.

Update the Flyway migration container to work on M1 Macs if possible, or document a way around this issue if not.

**Rational/Why**
Without Flyway migrations working, local development involving any schema changes can't be tested until code is in the `dev` environment, which is not ideal. Being able to change, drop, and re-create the database locally improves development speed and ensures that new changes are closer to "working" before being tested in a shared environment.

**Additional Context** 
- `./db` directory in repository: https://github.com/bcgov/platform-services-registry/tree/master/db
- Technologies involved:
  - [Flyway](https://flywaydb.org/)
  - Docker
- Expected code change: update to `./db/flyway.Dockerfile`
- Product to be updated: Platform Services Registry

**Dependencies**
- Internal to Platform Services team

**Tests**
- Test if other developers with and without M1 Macs are able to use the Flyway container as expected after any change.

**Definition of done/Acceptance Criteria**
- Flyway container is updated such that it will allow a developer who is new to the project can clone the repository and seed a fresh database instance for themselves without having to use a production database dump script
- Using the Flyway container, developers are able to write new migration and seed files that can be run in our OpenShift product namespaces

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore. Can be closed.
