### ISSUE TITLE
Kibana Security Focused Queries/Dashboards/Alerts

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#3136]
Kibana provides log visualization for all OpenShift service types (system, audit, app).  
We need to develop some queries/dashboards related to security events.

- [x] Ensure access to Kibana
- [x] Ensure availability/access to data - Cluster reader should enable this + index
- [ ] Identify appropriate queries (e.g. access attempts over period, out of working hours access, other)
- [ ] Create dashboard(s)
- [ ] Demo to Nick/Olena

Definition of done:
- [ ] Dashboard(s) created
- [ ] Alert successfully sent (email or other) based on trigger

**Comment by NickCorcoran** [comment]
Setup meeting w/ NRM security analyst and security investigations analyst to discuss opportunities.

**Comment by NickCorcoran** [comment]
Discovered through investigation that building this as desired is not currently feasible, and existing tooling does not enable alerting.  To investigate options directly w/ Red Hat security team.

**Comment by AvneetKahlon** [comment]
Meeting with RedHat guys to find out how to work on this.
