### ISSUE TITLE
Improve how bond interfaces fail over

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#314]
https://trello.com/c/QubxoGHL/153-improve-how-bond-interfaces-fail-over

Red Hat suggestions we change the config of the bond NIC from using "miimon" to using ARP checks against the gateway IP. 
https://github.com/bcgov-c/platform-ops/issues/70

**Comment by wmhutchison** [comment]
Steven has implemented this method into existing Silver OCP4 physical servers. Am of the opinion to not bother messing around with existing OCP3 physicals, will discuss this with him and if agreed, close off this ticket if OCP4 physicals with the setup show no problems over the next few weeks.

**Comment by wmhutchison** [comment]
If we still aim to implement in OCP3, then we'll need to align around a suitable OS patching maintenance window.

**Comment by mitovskaol** [comment]
REcommendaiton is not to make this change in OCP 3 since there hasnt been any incident in a long time. Continue monitoring the Silver cluster over the next 3 weeks to confirm that this fix works well in OCP 4 and if confimed, close this ticket in 3 weeks.

**Comment by lukegonis** [comment]
if this issue doesn't reoccur until the next backlog grooming we will close it.
