### ISSUE TITLE
Schedule & implement Hard Prune in GOLD and GOLDDR clusters

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3145]
**Describe the issue**
Matt will let us know when it's ok to proceed with this, there's a bug that is causing some images that shouldn't be deleted to be deleted.

**How does this benefit the users of our platform?**
Removing old images helps maintain the performance and stability of the cluster.

**Definition of done**

- [x] Verify with RH that the new pruning configuration is safe to use.
- [x] Test in a LAB environment
- [x] Schedule hard pruning for GOLD
- [x] Schedule hard pruning for GOLDDR
- [x] Implement the hard prune in GOLD
- [x] Implement the hard prune in GOLDDR
- [ ]

**Comment by wmhutchison** [comment]
Mis-read this item, putting back into Backlog.

**Comment by tbaker1313** [comment]
Completed.
