### ISSUE TITLE
Gracefully handle missing photos when Idir user added to Project Request in Platform Services Registry

### ISSUE THREAD

**Issue by ShovelHand** [BCDevOps/developer-experience#3147]
Not every user has a phot associated with their IDIR account, which leads to an ugly broken image and displayed alt text in contacts steps for Platform Services Registry.
![image.png](https://images.zenhubusercontent.com/61685dc792ace60aa0bf03dd/c7bbf860-8e4f-4412-a9bb-65be29a3df56). We should have some kind of placeholder image or something in these cases, like the typical greyed out silhouette of a user, or whatever. 

**Additional Context** 
- https://github.com/bcgov/platform-services-registry

**Definition of done**
- When a user without an IDIR phot is entered, we have better looking UI than a broken image with alt text displayed.

**Comment by ty2k** [comment]
I would suggest something like this:

`AdaptedGitHubUserDisplay.tsx`
```tsx
import userAvatarPlaceHolder from '../../../../assets/images/user-avatar-200x200.png';

// ...

        <Image
          src={avatar ? avatar : userAvatarPlaceHolder}
          alt={name}
          sx={{
            borderRadius: '50%',
          }}
        />
```

`user-avatar-200x200.png` (this is just the [FontAwesome user icon](https://fontawesome.com/icons/user?s=solid&f=classic) styled with the Design System `#313132` value)
![user-avatar-200x200.png](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/2d5b88a7-cbfc-49c2-82a9-1c3964562298)

This will give you this kind of effect when someone has no avatar available from the Graph API:
![Avatar is not available](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/57b817a9-4cf0-4643-8c4a-356c570c33c9)

And if someone does have an avatar:
![Avatar is available](https://images.zenhubusercontent.com/5ec709daacce4878764898c4/0e9e480d-48de-425f-a2f8-f8f6bccd69d7)
