### ISSUE TITLE
ROSA: Identify differences in Storage Classes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3153]
**Describe the issue**
Identify gaps where the deployment into a public cloud based cluster changes the way we can supply storage to product teams.

**What is the Value/Impact?**
Product teams need storage

**What is the plan? How will this get completed?**
Review ROSA and classic cluster storage, document differences, propose solutions.

**Identify any dependencies**

**Definition of done**
A plan on how to close any gaps we can, or documentation of those we can't

**Comment by StevenBarre** [comment]
Cluster comes with several EBS based block storage classes. I believe the default in 4.11 is gp3-csi. There is an operator you can install to get AWS NFS, but there is no quota on that storage ...

https://mobb.ninja/docs/rosa/aws-efs-csi-operator-sts/

**Comment by filiy** [comment]
I'll take this issue for now to test too see if we can set up any storage quotas on EFS.

**Comment by filiy** [comment]
Looks like there are some EFS docs to follow. I'll test in a lab. But I don't think the quotas in openshift will work.

https://docs.openshift.com/rosa/storage/persistent_storage/rosa-persistent-storage-aws-efs-csi.html

https://access.redhat.com/articles/6966373

**Comment by filiy** [comment]
This guide is probably the best for set up.
https://mobb.ninja/docs/rosa/aws-efs-csi-operator-sts/

It's called out more or less the same in other docs too.
https://docs.openshift.com/container-platform/4.11/storage/container_storage_interface/persistent-storage-csi-aws-efs.html
https://docs.openshift.com/rosa/storage/persistent_storage/rosa-persistent-storage-aws-efs-csi.html
https://access.redhat.com/articles/6966373

I'll get this added to the CER.

**Comment by filiy** [comment]
although you can set OpenShift quota for an EFS storage class that isn't going to control how much data you can write to the underlying system. 

This would need to be monitored to ensure EFS usage didn't grow to TB's in size.
