### ISSUE TITLE
ROSA: Identify differences in Logging

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3157]
**Describe the issue**
Identify gaps where the deployment into a public cloud based cluster changes the way we can supply logging services.

**What is the Value/Impact?**
App logs available

**What is the plan? How will this get completed?**
Review ROSA and classic cluster logging, document differences, propose solutions.

**Identify any dependencies**

**Definition of done**
A plan on how to close any gaps we can, or documentation of those we can't

**Comment by StevenBarre** [comment]
According to https://access.redhat.com/support/cases/#/case/03278768/ (under the advsol.mcs user), we can EITHER have logs get forwarded to CloudWatch OR we can install the usual EFK stack.

According to [Julian[(https://chat.developer.gov.bc.ca/channel/aws-how-to?msg=Aty7ZvmykffsWHxL5)

> Each team can view and add to the existing logs, but they can’t remove what’s there. So each team is responsible for their own logging and has tools at the AWS Account level for managing logs.
>
>On top of that, CPF also retains the logs over in an immutable bucket in the ASEA core account areas away from where teams can see or modify them. From there we ship down to the SecOps Hadoop SIEM on-prem.

So it seems like CloudWatch would be the preferred option as it ensures proper log retention and leveraging of the SEA platform. However, as the Ops team would own the AWS Account, product teams would be unable to see the CloudWatch logs.

**Comment by tmorik** [comment]
From the OCP 4.10 of ROSA, we can deploy both CloudWatch and EFK logging stack. It's been tested on rosa-lab under the [Test Logging Operator and AWS CloudWatch on the Government ROSA Cluster#3096](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/3096), successfully.

One caveat to using both logging is that it is costly. Since logs are resource eaters by nature, using both CloudWatch and EFK will make a big & twice(because they are collecting a same logs) of running cost.

As we tested in the rosa-lab cluster, according to the AWS cost explorer, the CloudWatch is spending $60-$80 per day.

CloudWatch's Cost trend :

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/71cec56b-383d-4fed-a2a3-08220358548c)

**Comment by tmorik** [comment]
On the other hand, EFK is not impacting to the CloudWatch Cost above, but it will costing to other service charges, such as ROSA service and EC2-instance services:

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/32e0f20c-d9f1-4031-b995-f4679abdb82c)

Started EFK on Nov 25th (red arrow).

Note: this EFK deployment was very small deployment which we are not going to use in prod env. So this cost jump will be much higher than this graph.

**Comment by tmorik** [comment]
Another point that we should consider is that it's operating cost. 

The EFK deployment will be costing our (MCS) time when we need to patch/upgrade of EFK operator as we are doing it for Hybrid OCP clusters (Silver, Gold etc.), while the AWS CloudWatch won't require such operations as Amazon will do it for us.

**Comment by tmorik** [comment]
Summary of findings so far:

1. AWS CloudWatch is preferable for logging
2. AWS CloudWatch logging is pay-as-you-go, which means that as logging increases, so does the cost. 
3. However Product Teams would be unable to see the CloudWatch logs.
4. From OCP 4.10, EFK logging operator can be co-existed with ClowdWatch.
5. Using EFK logging, Product Teams will be able to see the logs.
6. However, EFK logging requires large EC2 instance for infra nodes and will costly.

Probably we should not use both loggings at the same time as it's waste of cluster resources and money. If we can resolve **3. However Product Teams would be unable to see the CloudWatch logs**, the Cloudwatch would be the best solution.

**Comment by tmorik** [comment]
Waiting for review.

**Comment by StevenBarre** [comment]
Very thorough @tmorik ! Looks good to me. We'll wait for Milo to get back from vacation and hand it over to him to review.

**Comment by StevenBarre** [comment]
Passed info to Milo, closing
