### ISSUE TITLE
Tekton Pipeline template - add docker setup option

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3175]
**Describe the issue**
The tekton script from this template: https://github.com/bcgov/pipeline-templates/tree/main/tekton

It's not working too well for windows users, even with WSL. We can consider creating a dockerfile to run the script which would make the start up process way easier!

**What is the Value/Impact?**
Make pipeline template easy to use

**Definition of done**
- [ ] create a dockerfile to run the tekton script
- [ ] test on different OS

**Comment by w8896699** [comment]
Ask Ian
