### ISSUE TITLE
Upgrade Trident

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#318]
https://trello.com/c/nrW8gHKz/169-upgrade-trident

SCTASK0124245
Upgrade to https://github.com/NetApp/trident/releases/tag/v20.01.0

Trident is the app/pod that manages the Netapp volume provisioning. Current version is 19.10 and we'll be moving to 20.04 - testing in LAB is ongoing.
Further information is available @ https://github.com/NetApp/trident/releases

**Comment by tbaker1313** [comment]
Trident is the app/pod that manages the Netapp volume provisioning. Current version is 19.10 and we'll be moving to 20.04 - testing in LAB is ongoing.
Further information is available @ https://github.com/NetApp/trident/releases

**Comment by tbaker1313** [comment]
Trident upgraded to latest version 20.04.0
