### ISSUE TITLE
Grow Capacity for Cassandra metrics in OCP 3.11 PROD

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#319]
https://trello.com/c/ETnJnQGx/172-grow-capacity-for-cassandra-metrics-in-ocp-311-prod

**Comment by wmhutchison** [comment]
No longer required - root cause for the space issue was indices not being properly cleaned out thus 3+years of legacy data no longer required. Once truncated, usage of existing PVC is down to 7%.
