### ISSUE TITLE
SSO realm merge planning - OCP login

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3197]
**Describe the issue**
we will be merging the realm that OCP console login uses to another realm in Gold. This ticket is to find out what's the impact and if the merge is doable for this service.

**What is the plan? How will this get completed?**
Discussion with Service Lead, testing, planning

**Definition of done**
 - [x] identify service's SSO usage
 - [x] discuss if realm merge is doable
 - [x] come up with testing plan

Detailed testing steps:
1. First create client in gold sso realm.
2. Then use klab/clab to test out the new client integration, and figure out:
  - if an existing user can login properly, and that openshift is able to recognize the user
  - if not, what extra steps is needed for users to be able to log back into the same app account
3. Lastly, get prepared for the actual migration with the following:
  - testing plan
  - prepare for scripts for user migration if needed
  - migration plan (time and actions)

**Comment by StevenBarre** [comment]
Updated the inventory for KLAB to use the new keycloak URL and update the client secret in the GH Actions secrets https://github.com/bcgov-c/platform-gitops-gen/pull/556

Stuck on some conflicting changes to CCM/GitOps before merging the config repo to test.

**Comment by StevenBarre** [comment]
A blast email should be sent when dates for PROD migration are set. Users should be warned of the new SSO page look, and the need to authorize a new GitHub App after they log in to GitHub.

![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/8b26fccc-d344-4339-bfbb-d6e2f1dcb0ad)

**Comment by StevenBarre** [comment]
Change should be done after hours to minimize impacts
