### ISSUE TITLE
SSO realm merge planning - Rocketchat

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3203]
**Describe the issue**
we will be merging the realm that RC uses to another realm in Gold. This ticket is to find out what's the impact and if the merge is doable for this service.

**What is the plan? How will this get completed?**
Discussion with Service Lead, testing, planning

**Definition of done**
 - [x] identify service's SSO usage
 - [x] discuss if realm merge is doable
 - [x] come up with testing plan

**Comment by ShellyXueHan** [comment]
### Updates:
There are several things we need to do for the realm migration to work for Rocketchat:
- update the current RC oauth config: switch `Key Field` from `username` to `email` (this is because on Gold we'll use AzureAD instead of original IDIR, where the username would change now!)
- create a new oauth integration on RC to point to Gold SSO (testing in https://test-chat.apps.gold.devops.gov.bc.ca, where I can login to the original account as long as email matches)
- send out community notification to let ppl know the changes, and start to login via Gold SSO instead!
- finally cut off Silver SSO from RC

**Comment by IanKWatts** [comment]
@ShellyXueHan Do you have a preference for login expiration?  1 day?  7 days?

**Comment by ShellyXueHan** [comment]
@IanKWatts i'm thinking maybe 7 days to reduce the load on SSO service. Let's discuss about this when we sync up!

**Comment by ShellyXueHan** [comment]
### updates:
As the result of discussion, we will need to investigate on the number of active users on rocketchat to prevent out of seats after auth migration. more action items tracked in #2385.
