### ISSUE TITLE
Set up cluster atuoscaling for ROSA

### ISSUE THREAD

**Issue by filiy** [BCDevOps/developer-experience#3207]
https://docs.openshift.com/rosa/rosa_cluster_admin/rosa_nodes/rosa-nodes-about-autoscaling-nodes.html#rosa-nodes-about-autoscaling-nodes

**Comment by StevenBarre** [comment]
Since we have to buy ACS and Sysdig licenses, I'm not sure we want auto-scaling?

**Comment by filiy** [comment]
We deiced to not to enable auto-scaling.
