### ISSUE TITLE
Vault Fixes

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#3208]
After doing some investigation of Vault and its failover process, and after an outage that occurred on Friday, there are a number of fixes that should be implemented in order to ensure Vault is better supported in the future. This work can be divided into two sections - failover improvements, and support improvements

**Failover Improvements**

Vault's failover process can be improved iteratively, with each step looking like this:

1. When Vault fails over to the DR site, the DR instance requires manual intervention to stand up. Once the main site recovers, the system fails back to the main site automatically. 
2. When Vault fails over to the DR site, the DR instance stands up automatically. Once the main site recovers, the system fails back to the main site automatically. Changes are not synced back.
3. When Vault fails over to the DR site, the DR instance stands up automatically. Vault continues to point to the DR site even after main site recovery, allowing for us to sync back to the main site as we are able.

We can move from one step to the next safely while still providing full service to users.

**Support Improvements**

- update support documentation for DXCAS
- expand architecture documentation to include more network and other related content
- expand operational documentation to include more maintenance and troubleshooting tasks

**Comment by IanKWatts** [comment]
All issues completed
