### ISSUE TITLE
Create issues in GitHub for change control process

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#322]
https://trello.com/c/4szHFMr9/42-create-issues-in-github-for-change-control-process

I'm thinking it would be handy to create issues or PR's in GitHub for things like OCP upgrades. This way we can add some approvers, we can add any code or steps that are going to happen for review and visibility.

**Comment by sbarre-esit** [comment]
@jefkel @mitovskaol I think this is now mostly covered by the status page notification PRs and bot?

This is a very old card from back in Todds time and we wanted to help make quarterly patching RFCs more visible to the community instead of just the emails that get sent to the PD.

**Comment by jefkel** [comment]
I think the move from Trello to github addresses this more than the status page updates.  No ongoing discussion history about the changes happens in the status page notifications, no replacement of email approval via git review/approve is done there either.  (But that might be too much to ask the RFC process to handle just yet)

**Comment by mitovskaol** [comment]
@sbarre-esit As per Nick's recommendations, RFC work  - upgrades and maintenance - will not be posted on the Status page for security reasons. These updates will continue to be posted in #devops-alerts channel and now can be tracked via GitHub issues.

**Comment by sbarre-esit** [comment]
Ah, I hadn't noticed https://status.pathfinder.gov.bc.ca/ is dead and no longer gets stuff from that bot.

I think part of the original idea was to also replace the email we send to the PD with github so approvals are handled there. But seems the new PD is much better at quickly responding to RFC emails and approving them.
