### ISSUE TITLE
Playbook to automate OS patching

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#323]
https://trello.com/c/iFMiABBi/82-playbook-to-automate-os-patching

The desired end goal is to have a single playbook which when ran, will fully automate the process of patching all nodes in a given OpenShift cluster in an intelligent fashion. Said intelligence will include:

- For PROD, handle APP nodes in specific grouping and timing so as to minimize the probability that any one node evacuation will push all pods to a recently patched node.
- Using sut/HP One View, fully automate firmware updates.
- Add sufficient service checks so as to allow master/infra nodes to be automated (ensure both general API calls are working as well as local API pod)

**Comment by mitovskaol** [comment]
Ongoing work until the decomissioning of OCP 3.11 cluster.

**Comment by lukegonis** [comment]
Closing, as we now have a playbook, enhancements/changes will be tracked in new issues.
