### ISSUE TITLE
SSO migration - ArgoCD and GitOps

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3252]
**Describe the issue**
This is to update the service's SSO integration to use Gold Keycloak. Migration plan has been defined previously.

**Definition of done**
- [x] update SSO integration in lower environments (dev/test/lab/etc.)
- [x] define testing tasks to verify migration result
- [x] define roll back plan
- [x] community announcement
- [x] run migration scripts (this is needed to pre-populate existing github users)
- [x] update production SSO integration and carry out testing tasks

**Migration progress by Argo CD instance**
- [x] CLAB CCM
- [x] CLAB shared
- [x] KLAB CCM
- [x] KLAB shared
- [x] KLAB2 CCM
- [x] KLAB2 shared
- [x] Silver CCM
- [x] Silver shared
- [x] Gold CCM
- [x] Gold shared
- [x] GoldDR CCM
- [x] GoldDR shared
- [x] Emerald CCM
- [x] Emerald shared

**Comment by IanKWatts** [comment]
Testing tasks:
- update ConfigMap 'argocd-cm' for new SSO URL
- update Secret 'argocd-secret' for oidc.sso.clientSecret
- restart argocd-server / openshift-gitops-server
- confirm admin access for users in Keycloak group 'argo_platform_admins'
- confirm read access for users in Keycloak group 'argocd_readers'

Rollback tasks:
- revert argocd-cm to old SSO URL
- update Secret 'argocd-secret' for oidc.sso.clientSecret
- restart argocd-server / openshift-gitops-server

**Comment by IanKWatts** [comment]
Warden Operator also migrated and all clusters done.
