### ISSUE TITLE
SSO migration - Mautic

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3254]
**Describe the issue**
This is to update the service's SSO integration to use Gold Keycloak. Migration plan has been defined previously.

**Definition of done**
- [x] update SSO integration in lower environments (dev/test/lab/etc.)
- [x] define testing tasks to verify migration result
- [x] define roll back plan
- [ ] community announcement
- [ ] run migration scripts if needed
- [ ] update production SSO integration and carry out testing tasks

**Comment by w8896699** [comment]
define testing tasks to verify migration result:
Use team testing account(psta) to verify that new keycloack works fine

define roll back plan:
Revert onfigmaps/mautic-config-prod sso.json back to
```
{
  "url": "https://oidc.gov.bc.ca/auth",
  "realm": "devhub",
  "clientId": "mautic-subscription-prod"
}
```

revert secrets/mautic-subscription-api-prod, KC_URL KC_REALM, KC_CLIENT_SECRET
value can be find in https://oidc.gov.bc.ca/auth/admin/devhub/console/#/realms/devhub/clients/0e07ef58-4a3d-4e3e-a8dc-883104d4803b

**Comment by w8896699** [comment]
Mautic keycloack relam has been successfully moved to gold.
