### ISSUE TITLE
SSO migration - openshift clusters

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3256]
**Describe the issue**
This is to update the service's SSO integration to use Gold Keycloak. Migration plan has been defined previously.

**Identify any dependencies**
#3197

**Definition of done**
- [x] update SSO integration in lower environments (dev/test/lab/etc.)
- [x] define testing tasks to verify migration result
- [x] define roll back plan
- [x] community announcement
- [ ] run migration scripts if needed
- [x] update production SSO integration and carry out testing tasks

**Comment by StevenBarre** [comment]
Completed
