### ISSUE TITLE
Configure Ingress Operator in KLAB cluster

### ISSUE THREAD

**Issue by AvneetKahlon** [BCDevOps/developer-experience#3258]
**Describe the issue**
Configure ingress operator that outputs the access logs to EFK stack. The goal is to observe whether EFK stack is able to handle the capacity of logs. If it's successful, we can implement it in production cluster.

**Additional context**
In meeting with SecOps regarding configuring alert dashboard, they suggested analyzing http request logs. 

**How does this benefit the users of our platform?**
If this local EFK stack works then we will have alert dashboard for our team where we can setup alerts for unusual activities.

**Definition of done**

- [x] The ingress controller sends all the access logs to stack.

**Comment by StevenBarre** [comment]
Logging enabled in KLAB

**Comment by StevenBarre** [comment]
https://docs.openshift.com/container-platform/4.10/networking/ingress-operator.html#nw-configure-ingress-access-logging_configuring-ingress
http://cbonte.github.io/haproxy-dconv/2.0/configuration.html#8.2.4

**Comment by StevenBarre** [comment]
@AvneetKahlon @NickCorcoran how's the review of this going?

`kubernetes.namespace_name:"openshift-ingress" AND kubernetes.container_name:logs`

**Comment by StevenBarre** [comment]
To find for a specific route add ` AND message:"be_edge_http:license-test:route-name"` putting in the correct namespace and route name.

**Comment by StevenBarre** [comment]
Matt (RH) says that for a cluster the size of Silver we should only use the option that sends the logs via Syslog to some other system, and not keep the logs in EFK.

**Comment by wmhutchison** [comment]
Re-opening for the time being as Avneet is asking questions about this, so will keep it open to see where this goes, and if it makes more sense, re-close this and open a new ticket.
