### ISSUE TITLE
Review iSCSI settings for NetApp

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#326]
https://trello.com/c/pbRcPfPt/165-review-iscsi-settings-for-netapp

Found some extra settings we may need to apply to our hosts for best stability of iscsi

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-A46327AC-5A5E-459F-87E0-B25B0D83F52B.html and case https://access.redhat.com/support/cases/#/case/02562725 to ask about it

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-F9935B47-A709-4CAA-945B-64C03E338E79.html

**Comment by sbarre-esit** [comment]
I think this is done? Can you confirm and close if it is?

**Comment by tbaker1313** [comment]
Iscsi settings for Netapp have been updated on servers and in relevant playbooks.
