### ISSUE TITLE
Mautic - email template missing icon

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3270]
**Describe the issue**
the email template has a broken link in the header. need to update the BCGov icon to a working one.
[GitHub repo](https://github.com/bcgov/bcgov-just-ask)
**Definition of done**
- [ ] fix email template

**Comment by Kolezhanchik** [comment]
the repo with the admin interface for Mautic    https://github.com/bcgov/Mautic-Subscription-App

**Comment by Kolezhanchik** [comment]
the GitHub repo where templates stored is https://github.com/bcgov/Mautic-Openshift, I don't have access to it. But the problem with [icon ](http://mautic-de0974-prod.apps.silver.devops.gov.bc.ca/themes/BCGov-Platform-Services/img/bcgovlogo.png)is 
![image.png](https://images.zenhubusercontent.com/62c35ec2ef07f0a53a3f3d28/2085e818-0625-4d54-b5c3-f5ab829f23fb)
all of pods are running

**Comment by ShellyXueHan** [comment]
@Kolezhanchik alright, you should have admin access to the repo now!

**Comment by Kolezhanchik** [comment]
thank you @ShellyXueHan everything is ok with logo in repo and the path to image is correct

**Comment by Kolezhanchik** [comment]
logo route provided ![image.png](https://images.zenhubusercontent.com/62c35ec2ef07f0a53a3f3d28/4d246b9d-7cdf-46e2-b504-3a638c8a8b48)
