### ISSUE TITLE
Remove router custom ciphers

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#330]
https://trello.com/c/eVS9lJmc/18-remove-router-custom-ciphers

Install the Mozilla 'modern' set of SSL Ciphers on the openshift routers.

*   An additional cipher (DHE-RSA-AES256-GCM-SHA384) was added to the set of 'modern' ciphers to temporarily support a custom WAM configuration.

**Comment by sbarre-esit** [comment]
@jefkel Do you know if there was ever any update here? Are we going to need to carry this over to OCP4?

**Comment by jefkel** [comment]
I believe it’s likely that we will need to carry the customizations over.  Let’s automate and test applying these, but revert and hold off until we are able to test/confirm with the apps (just in case it’s ok)

**Comment by sbarre-esit** [comment]
Since we won't be using the OCP router anymore, this would be something to try and tweak in the F5 BIG-IP, which doesn't sound fun ...

Do we have any way we can test this?

**Comment by lukegonis** [comment]
No longer relevant, moving to closed.
