### ISSUE TITLE
Reduce how much is kept by the pruner

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3307]
**Describe the issue**
ETCD is getting full of stuff, need to be more aggressive with pruning. 

**What is the Value/Impact?**
Change the pruners to only keep 2 instead of 5 previous things. And only keep 48 hours instead of 96 hours.

Those two things are ORd together. So if a thing is the most recent 2 OR less than 48h, it is kept.

This is for Builds, Deployments, and Images.

**What is the plan? How will this get completed?**
- https://github.com/bcgov-c/platform-ops/pull/436
- https://github.com/bcgov-c/platform-tools/pull/147

Test in LABs, create CHGs for prod, announce in Dec 6th Community update.
SILVER/EMERALD - Dec 6 - CHG0043455 
GOLD/GOLDDR - Dec 7 - CHG0043457 

Also CHG0043794 will reduce image tag retention from 3 to 1 on Dec 14th 

**Identify any dependencies**
none

**Definition of done**
All prod clusters have new lower retention.

**Comment by tbaker1313** [comment]
SILVER and GOLD are completed.

**Comment by tbaker1313** [comment]
Completed.
