### ISSUE TITLE
NFS PV implementation for backup storage targets

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#331]
https://trello.com/c/UvYv1Bdt/14-nfs-pv-implementation-for-backup-storage-targets

Deploy NFS auto-provision of storage as replacement storage for backup targets (replacing legacy Gluster volumes)

**Comment by sbarre-esit** [comment]
I think we can close this?

**Comment by jefkel** [comment]
Yeah, deployed as is for now, but won't be migrated to OCP 4.  (will leverage direct integration with NetApp for backup volumes.)
