### ISSUE TITLE
PRB0040321 Block Hosting Volumes fill up with extra files

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#332]
https://trello.com/c/SIUyIKVa/159-prb0040321-block-hosting-volumes-fill-up-with-extra-files

CNS Block volumes leak a 64M file when they are deleted. Eventually the BHV gets too full of cruft and provisioning fails.

We added a monitor for the situation with https://github.com/bcgov-c/platform-ops/pull/106

Red Hat case https://access.redhat.com/support/cases/#/case/02497550

RH advises this should be fixed in the next OCS release, currently targeted for late Jan 2020.

**Comment by jefkel** [comment]
Expected fix for this issue will be included in the next OCS patches to be deployed in Q3.  No action is required on this task.

Moving to blocked while we wait for the patching to be completed, at which time this can be closed.

**Comment by wmhutchison** [comment]
This will be able to be closed after we execute the PROD OCS upgrade currently scheduled for August 22/23rd.

**Comment by wmhutchison** [comment]
PROD OCS upgrade now complete. Closing this ticket off now.
