### ISSUE TITLE
Gluster brick process crashes on portscan

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#333]
https://trello.com/c/n3kV27dB/162-gluster-brick-process-crashes-on-portscan

This caused the outage on Dec 8th
https://access.redhat.com/support/cases/#/case/02536261
https://review.gluster.org/#/c/glusterfs/+/23861/

**Comment by sbarre-esit** [comment]
This is fixed in OCS 3.11.5, which will get installed in 2020-Q3. For now, we've excluded the servers from the nmap scan that causes this crash.

**Comment by tosazuwa** [comment]
Workaround in place. Full fix in #494
