### ISSUE TITLE
OCP 4.11 Perform Hard Prune in KLAB - TBD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3332]
**Describe the issue**
The image registry should have a hard prune run on it from time to time. So we plan a Sunday morning change window operation to run the prune each quarter before patching kicks off. KLAB can be run during daylight hours. This might not be completed due to a RH bug with hard pruning.

**Additional context**
https://docs.openshift.com/container-platform/4.11/applications/pruning-objects.html#pruning-hard-pruning-registry_pruning-objects

**Definition of done**
- [x] KLAB image registry pruned

**Comment by tmorik** [comment]
No Hard Prune for OCP 4.11 upgrade. New Manual Prune is this : https://github.com/bcgov-c/advsol-docs/blob/4.11-upgrade/OCP4/Upgrade.md#perform-a-manual-image-prune---new
