### ISSUE TITLE
Error page when clicking on a product within the dashboard

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3335]
**Describe the bug**
When you click on a product that's status is "decision pending," you are taken to an error page. 

**Environment**
Test

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a product that's status is "decision pending"
2. Log in to the Registry
3. When redirected to the main dashboard under requests tab, click on the product that is listed as "decision pending"
4. See error page

**Expected behaviour**
When you click on the product on the dashboard you should be taken to the edit/summary page of the product. 

**Screenshots**
![Screenshot 2022-11-29 at 1.46.24 PM.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/32b90443-f9d1-4a4e-a848-34adc35a63cd)
![Screenshot 2022-11-29 at 1.45.55 PM.png](https://images.zenhubusercontent.com/61e5c37effa2c8288c8c07d1/5bbbda97-f84b-417c-9025-0b152f73f582)

**Desktop (please complete the following information):**
 - OS: Ventura 13.0.1
 - Browser: Chrome
 - Version: 107.0.5304.110

**Additional context**
Unsure if this is just for products that have a decision pending or for all products

**Comment by okanji** [comment]
@alexandralloyd, can you try and re-create this issue? Can you create a new project and see if you still have this issue?
