### ISSUE TITLE
INC0029871 ociopf-p-186 /var/lib/origin full

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#334]
https://trello.com/c/95Y8mo43/158-inc0029871-ociopf-p-186-var-lib-origin-full

https://access.redhat.com/support/cases/#/case/02558786

Gluster client is not releasing its file handle, so the log file can't rotate properly and is now 22G on a 25G filesystem

**Comment by sbarre-esit** [comment]
I think this was fixed by our most recent RHEL patching?

**Comment by tbaker1313** [comment]
Recent OS patching has corrected this issue.
