### ISSUE TITLE
OCP 4.10 Upgrade NetApp Trident in EMERALD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3350]
**Describe the issue**
Upgrade Trident based on testing in LAB clusters.

**Additional context**
https://github.com/NetApp/trident/releases

**Definition of done**
- [x] Trident upgraded

**Comment by wmhutchison** [comment]
Apart from some compatiblity issues needing to be addressed due to the OS version of EMERALD's UTIL box, Steven's updated playbook worked flawlessly. Trident now upgraded.
