### ISSUE TITLE
OCP 4.10 Upgrade Openshift in EMERALD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3351]
**Describe the issue**
Run the OCP 4.10 upgrade in EMERALD.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] Upgrade `oc` CLI on util server
- [x] GOLD upgraded to OCP 4.10
- [x] Ensure all pull secrets are present per #3537
- [x] MachineConfig changes applied
- [x] CCM applied
- [ ] ~~EnCase updated~~
- [x] ETCD Backup updated
- [ ] ~~Nagios updated~~
- [x] Pruner updated
- [x] Logging updated
- [x] Sample Operator updated

**Comment by wmhutchison** [comment]
Not worrying about updating Nagios for the time being. Would fix API checks if needed, but not needed for this time around. Long-term fix will involve us moving our builds for Nagios to Artifactory.

**Comment by wmhutchison** [comment]
Global pull secrets updated. Will continue to check/monitor EMERALD, but otherwise close off the RFC Wednesday morning if nothing else is detected.

**Comment by wmhutchison** [comment]
RFC closed as complete.
