### ISSUE TITLE
OCP 4.11 Upgrade F5 CIS in EMERALD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3352]
**Describe the issue**
Upgrade F5 CIS to newer version based on testing in LAB clusters as well as SILVER. 

**Additional context**
From https://github.com/bcgov-c/platform-ops/ (latest main pull)

```
ansible-playbook -i inventory/gold playbooks/config-f5.yaml
```

**Definition of done**
- [ ] Run playbook.
- [ ] Confirm F5 CIS upgraded.

**Comment by wmhutchison** [comment]
Removing from EPIC and closing - No F5 CIS for NSX-backed clusters, as that function is provided by NSX/AVI instead.
