### ISSUE TITLE
OCP 4.10 Perform Hard Prune in EMERALD - TBD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3353]
**Describe the issue**
The image registry should have a hard prune run on it from time to time. So we plan a Sunday morning change window operation to run the prune each quarter before patching kicks off.

**Additional context**
https://docs.openshift.com/container-platform/4.10/applications/pruning-objects.html#pruning-hard-pruning-registry_pruning-objects

**Definition of done**
- [ ] EMERALD image registry pruned

**Comment by wmhutchison** [comment]
Not going to bother with this for EMERALD at this time. Will be a candidate for the next maintenance run.
