### ISSUE TITLE
OCP 4.10 Upgrade Openshift in KLAB2

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3357]
**Describe the issue**
Run the OCP 4.10 upgrade in KLAB2.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] Upgrade `oc` CLI on util server
- [x] KLAB2 upgraded to OCP 4.10
- [x] MachineConfig changes applied
- [x] CCM applied
- [x] ETCD Backup updated
- [x] Nagios updated
- [x] Pruner updated
- [x] Logging updated
- [x] Sample Operator updated

**Comment by wmhutchison** [comment]
Due to the KLAB2 Trident ticket eating up a lot more time than expected coupled with other issues to address (including KLAB etcd), actual work on this ticket will have to wait for next week.

**Comment by wmhutchison** [comment]
Have resolved everything for the base OCP upgrade. Now taking care of the rest.
