### ISSUE TITLE
Prune unused image tags in Silver/Gold/DR

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3380]
**Describe the issue**
RH has identified that the Silver cluster has over 21,000 image tags which is starting to impact ETCD performance. Upon review, many of these tags appear to be old and unused by any running pods. Many appear to be tagged per build or PR and are likely just not getting cleaned up.

The suggestion is to do a one time manual run of the image pruner with argument `--keep-tag-revisions=0` and `--keep-younger-than=336h` (2 weeks) . This will prune ALL image revisions of unused tags (older than 2 weeks)(, and thus also prune the tag. The pruner will not remove any tags or revisions in use by existing pods/deployments/statefulsets/cronjobs.

However, this is still a fairly major cleanup and could potentially remove a tag that a developer isn't expecting to have garbage collected on them. Sufficient notice and consultation should be taken.

**What is the Value/Impact?**
Improve ETCD performance

**What is the plan? How will this get completed?**
- Send a blast email via the subscription tool informing dev teams of the upcoming change and give them sufficient time to respond and object / ask questions.
- Discuss at the next Community Meetup to inform teams
- Post in the Alerts channel at least 2 weeks a head of the CHG
- Run a one time image prune in the 3 classic prod clusters

**Identify any dependencies**
- Need assistance from Platform Services to send the blast email
- Need to respond to any questions / objections from the community

**Definition of done**
- Old image tags pruned

**Comment by mrobson** [comment]
Reference to image prune conditions for what is kept when things are in use: https://docs.openshift.com/container-platform/4.10/applications/pruning-objects.html#pruning-images-conditions_pruning-objects

**Comment by mrobson** [comment]
If anyone wants to look, here is a list of all of the projects + tags counts when you prune with keeping 1 revision. You can see there are over 17000 project + tag combos with only 1 reference.

[https://app.zenhub.com/files/220104031/76bbbf1b-750b-465d-8af8-8b961fc97063/download](https://app.zenhub.com/files/220104031/76bbbf1b-750b-465d-8af8-8b961fc97063/download)

Doing a dry run prune with keeping 0 tags, here is a list of what it would delete:

[https://app.zenhub.com/files/220104031/d3e43392-98a9-4d6c-bb0a-9ff1fba51abe/download](https://app.zenhub.com/files/220104031/d3e43392-98a9-4d6c-bb0a-9ff1fba51abe/download)

`   1 0137d5-tools/phsa-adapter: prod:   sha256:6b1847565362ed5b50df601034c85e325ee9ffc08d2c3e1b4fe640d73346d981...
   1 0137d5-tools/phsa-adapter: prod-backup:    sha256:6b1847565362ed5b50df601034c85e325ee9ffc08d2c3e1b4fe640d73346d981...
   1 0137d5-tools/phsa-adapter: train:  sha256:13f4443afa2d5995cfc5bdf6653564687044c616ef79b87f3f1cdd37004a96b6...
   1 0198bb-tools/arc-dispute-api:      0.0.1-pb:       sha256:ba2ef260989ffa537236c34098b82983997f67fc17a891e6c6181b96d7307439...
   1 0198bb-tools/arc-dispute-api:      0.0.1-pb:       sha256:ba7f1e3d56bec598e7b7857f7d85e9ff405299cc759602e13e78fe6d4412aeb2...
   1 0198bb-tools/arc-dispute-api:      0.0.1-pb:       sha256:ca3e3eda9d74d5608f30e0915e2148c0149cd08ead695246af13282109946af6...
   1 0198bb-tools/arc-dispute-api:      0.0.2-pb:       sha256:063a7c5dd154bfa932f6de3c25525692966b6a2d1090e243661529d19dbb6e60...
   1 0198bb-tools/arc-dispute-api:      09f8cd3-632394ce:       sha256:9fd5e4a31dad0c3ae53adf50b55f7fc731484eb8906ee87216e660569eea5d1e...
   1 0198bb-tools/arc-dispute-api:      09f8cd3-63239517:       sha256:6cecdb18cff23cf95b12493fa6bce45a963e02ecba7803bc114b258651d44da0...
   1 0198bb-tools/arc-dispute-api:      0f71a27-6362f55a:       sha256:ed8aa06a11531ffe5bc55ca6588f88781456cbc84b9f5b8c766fb4712ba3d1df...
   1 0198bb-tools/arc-dispute-api:      1315892-633ef9ba:       sha256:e9da29e09620975c004a7a82eee6243c97c4df67326e4fd37035b7cef046bd09...
   1 0198bb-tools/arc-dispute-api:      1.44.1: sha256:cce4ccfd70ff4cbbb4216d14efe1c66d890f405c4fc65548705734994d61ead6...
   1 0198bb-tools/arc-dispute-api:      1.44.2: sha256:7bbe6908c39b69ee02363349065ed9213a497fccddce37c43461b924fb7dccc7...
   1 0198bb-tools/arc-dispute-api:      1.44.3: sha256:fa308f9349d2a39bcfcaaf70c3bbc00e98e027680631dba283120366efe0290a...
   1 0198bb-tools/arc-dispute-api:      1.44.4: sha256:a328bd8e3016749e3d2ed0097c37793419678a200f21bf087dc41137eec885d9...
   1 0198bb-tools/arc-dispute-api:      1.44.4: sha256:e049f342067a98595476ea719e5c12aa71771390605812a92f82204218c9e13a...
   1 0198bb-tools/arc-dispute-api:      1.44.4: sha256:f8ae415b3917bc34728edd40666093dd8a482efd32d1366b2df22bfee14ecd43...
   1 0198bb-tools/arc-dispute-api:      1.44.5: sha256:6cecdb18cff23cf95b12493fa6bce45a963e02ecba7803bc114b258651d44da0...
   1 0198bb-tools/arc-dispute-api:      1.44.6: sha256:68f7f06da8a28bbdc6dc936ff159c9e5fb81d6daa7557dd438919a4d0135a448...
   1 0198bb-tools/arc-dispute-api:      1.44.6: sha256:6c0b48bbf4808d601661d39d1ec79cc40376bd96ed6f2578127589368a36d1d7...
   1 0198bb-tools/arc-dispute-api:      1.45.0: sha256:00b850ddc61bdb9d89e062aa9e9a96b405c3a1f24645b581f0d80b29c269464a...
   1 0198bb-tools/arc-dispute-api:      1.45.0: sha256:c4b279697239ccb8569e985db1a5c304280729542b5357a471222779dbda9848...
   1 0198bb-tools/arc-dispute-api:      1.45.1: sha256:8027913d78b7cb23ebaaea90d587f2e2a28c3ac7da4b4641007c9967866261a8...
   1 0198bb-tools/arc-dispute-api:      1.45.1: sha256:e1a989dacd5e197da0815f358cb1b68af8569290b78292349a734a61f29bd3cb...
   1 0198bb-tools/arc-dispute-api:      1.45.2: sha256:86a3de0758e1f4945c788f87a9c244936df6fb96d42beb506ac7a917ac8165ee...
   1 0198bb-tools/arc-dispute-api:      1.45.2: sha256:a9d81c5bbd6dc78ddd9f9fcb76618938ed1f0170f8856f2a258ef865b97cfb5f...`

**Comment by tbaker1313** [comment]
Completed in SILVER

**Comment by wmhutchison** [comment]
Completed  in GOLD on February 5th 2023.

**Comment by tmorik** [comment]
Completed in GOLDDR on Feb 12th 2023
