### ISSUE TITLE
RHACS - SILVER - Central pod Not Upgrading after Operator is Upgraded

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3388]
**Describe the issue**
Earlier today it was internally reported that https://acs.developer.gov.bc.ca/ was not working. Investigation confirmed this and noted the central pod was stuck in a 0/1 Ready state. Nothing amiss stood out as the cause for this (no resource issues could be detected nor anything in the pod logs stood out). Opened a case with Red Hat once it was confirmed more support was needed.

**Blocked By**
Red Hat knows of the issue and is working on a fix. Once the fix is available and we are past the holiday Change Freeze, the fix will be applied and confirmed before unblocking/resolving this ticket. UPDATE: Operator upgrade applied, but a new bug was found. Waiting for specific instructions from Red Hat on how to work around this, as they internally pursue a bugfix.

**Additional context**
A CCM push was made earlier today in EMERALD and SILVER clusters, but nothing stands out that could have been the cause for ACS to malfunction.

URL for vendor case: https://access.redhat.com/support/cases/#/case/03392725
URL for Knowledge base article outlining issue: https://access.redhat.com/solutions/6990153

**How does this benefit the users of our platform?**

**Definition of done**
- [x] Confirm state of ACS (not accessible, bouncing pods does not help)
- [x] Open vendor case, populate with standard data sets.
- [x] Continue working vendor case, adding more data/etc as needed.
- [x] Confirm resolution of issue.

**Comment by wmhutchison** [comment]
Issue has resolved itself, but case will remain open to see if we can determine any root cause.

**Comment by wmhutchison** [comment]
We still have Keda disabled, will enable it tomorrow morning and see if that re-breaks ACS or not. If it does, then Keda will remain uninstalled.

**Comment by wmhutchison** [comment]
Moving this to Blocked state as a known and required fix is not available yet. Will unblock when fix is available and applied to SILVER.

**Comment by wmhutchison** [comment]
A fix is available and successfully applied to our LAB clusters. Will not proceed with PROD clusters until January 2023 when Change Freeze will have expired.

**Comment by wmhutchison** [comment]
The upgraded operator (3.73.1) was successfully upgraded in SILVER during this week's CCM push in SILVER, but it was discovered that the upgrade process had stalled. Apparently this did also happen in KLAB when the same operator had upgraded there as well, but due to not receiving full attention and offering no hints of having stopped, it escaped notice.

**Comment by wmhutchison** [comment]
updated the vendor case with latest findings and additional data dumps. Response from Red Hat was that this was an internal bug.

```
Most recent comment: On 2023-01-12 09:04:16, Robson, Matt commented:
"William,

Taking a look at the operator logs, we can see there is a conflict occurring with the storageClassName and size properties.

Discussing internally, those can be removed from the central CR and the upgrade should proceed and complete. We have also opened a bug to address this.
```

**Comment by wmhutchison** [comment]
The sole YAML configured in the CR for ACS is the folllowing section.

```
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
        storageClassName: netapp-block-standard
```
The default PVC size is 100GB. Waiting on Red Hat for how to exactly remove some/all of this to allow the upgrade to proceed without nuking the existing PVC which will have existing data stored. If just removing the entries from the YAML spec will allow this, then we will test in KLAB first, and if successful, will proceed with the same during the next SILVER CCM RFC push.

**Comment by wmhutchison** [comment]
Confirmed with Red Hat the sole change needed to be made is to remove this line from the `central` CR:

```
        storageClassName: netapp-block-standard
```

Tested this successfully in KLAB. Created an RFC for executing this in SILVER next Tuesday after work (CHG0044604 - MCS - SILVER - Apply vendor recommendations to allow RHACS software to complete upgrade process)

**Comment by wmhutchison** [comment]
RFC awaiting approval, as are the comms for posting in #devops-alerts.

**Comment by StevenBarre** [comment]
RFC completed and pod restarted in under 10 min

**Comment by wmhutchison** [comment]
Will close this off as issue is well-defined as is the work-around.
