### ISSUE TITLE
Registry switch - update GitHub Actions for callbacks from provisioner

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#3396]
**Describe the issue**
When the registry application is switched to the new version, update the registry callback URL and HTTP verb

**What is the Value/Impact?**
After the provisioner processes an update from the registry, it sends a message back to the registry to let it know that the request has been fulfilled.  Without this callback, a project set will continue to show "pending edit" in the registry.

**What is the plan? How will this get completed?**
Update the GitHub Actions `registry-fulfillment-prod.yaml` and `registry-fulfillment-test.yaml` in each cluster's "namespaces" repo:
* In the `REGISTRY_RESPONSE` line, change `-X PUT` to `-X POST`
* In the same curl command, change the registry URL from `${REGISTRY_URL}/api/v1/provision/namespace` to `${REGISTRY_URL}/namespace`
* IF the registry URL has changed, update the secret in each repo: `PROD_REGISTRY_URL`

**Identify any dependencies**
n/a

**Definition of done**
- [x] These updates have been made in the namespaces repo for each cluster

**Comment by w8896699** [comment]
Missing emerald and klab2. I will need admin access to those two repo

**Comment by w8896699** [comment]
Finished on silver gold golddr clab klab

**Comment by IanKWatts** [comment]
Done in emerald and klab2 and billy has access to those repos.
