### ISSUE TITLE
Enable push notification for rocketchat

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3402]
**Describe the issue**
mobile users don't get push notification from rocketchat. this is something we need to setup.

what's known so far:

Looks like we need to do the following to check on the push notifications. It requires the Rocket.Chat Cloud service, which we apparently have access to.
Administration –> Connectivity Services –> Login to Rocket.Chat Cloud

**Definition of done**
- [x] test out push notification gateway, and figure out if there are any extra cost needed
- [x] enable the feature

**Comment by caggles** [comment]
There's no extra cost needed - this is one of the reasons we signed up for Enterprise in the first place. We just need to turn on the push gateway, using the default rocketchat gateway. I won't touch this until you guys get back, just in case, but it should just be a matter of enabling the push gateway (under Admin -> Settings -> Push) and then restarting the server.

**Comment by IanKWatts** [comment]
Done and working
