### ISSUE TITLE
Certificate installed for EMERALD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3427]
Install the new certificate on the cluster.

**Definition of done**
- [x] PR created and passed QA
- [x] RFC created and scheduled (CHG0046423 on March 15th)
- [x] Certificate installed via RFC

**Comment by wmhutchison** [comment]
Backlog for now. Will move back if signed certs are not in Platform Ops' hands by late February.

**Comment by wmhutchison** [comment]
CHG0046423 successfully executed. Certs are good until 2024.
