### ISSUE TITLE
Certificate installed for GOLD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3428]
Install the new certificate on the cluster.

**Definition of done**
- [x] Certificate installed

**Comment by wmhutchison** [comment]
Backlog for now. Will move back if signed certs are not in Platform Ops' hands by late February.

**Comment by tmorik** [comment]
RFC: CHG0046449 - 16/03/2023 09:00:00 AM - 16/03/2023 04:00:00 PM

**Comment by tmorik** [comment]
Certificate has been installed.
