### ISSUE TITLE
Certificate installed for SILVER

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3430]
Install the new certificate on the cluster.

**Definition of done**
- [x] PR created and passed QA
- [x] RFC created and scheduled (CHG0046431 on March 15th)
- [x] Certificate installed via RFC

**Comment by wmhutchison** [comment]
Backlog for now. Will move back if signed certs are not in Platform Ops' hands by late February.

**Comment by tbaker1313** [comment]
PR created. Ready to complete. CHG0046431

**Comment by wmhutchison** [comment]
CHG0046431 successfully executed. Good until 2024.
