### ISSUE TITLE
Certificate installed for KLAB

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3431]
Install the new certificate on the cluster.

**Definition of done**
- [x] Certificate installed

**Comment by wmhutchison** [comment]
Backlog for now. Will move back if signed certs are not in Platform Ops' hands by early February.

**Comment by tbaker1313** [comment]
Cert has been received.

**Comment by tmorik** [comment]
Certificate has been renewed and installed in KLAB cluster; The new expiry dates are...:

api:

```
$ curl -vk https://api.klab.devops.gov.bc.ca:6443 |& grep date
*       start date: Feb 02 22:55:31 2023 GMT
*       expire date: Mar 01 22:55:30 2024 GMT
```

console(app):

```
$ curl -vk https://console.apps.klab.devops.gov.bc.ca/ |& grep date
*       start date: Feb 02 22:51:25 2023 GMT
*       expire date: Mar 01 22:51:24 2024 GMT
```
