### ISSUE TITLE
Certificates installed for KLAB2

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3432]
Install the new certificate on the cluster.

**Definition of done**
- [x] API Certificate installed
- [x] Wildcard APPs Certificate installed

**Comment by wmhutchison** [comment]
Backlog for now. Will move back if signed certs are not in Platform Ops' hands by early February.

**Comment by wmhutchison** [comment]
Certs installed and confirmed. Replied back to IMS for both confirming certs now in place so they can close off the iStore order(s).
