### ISSUE TITLE
Create new doc on backups and restores

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3434]
**Describe the issue**
During the move of docs from the old DevHub to the new docs site, https://developer.gov.bc.ca/OCP4-Backup-and-Restore never made it over. There is currently no clear directions on how to request a restore of a `netapp-file-backup` PVC.

**Additional context**
https://chat.developer.gov.bc.ca/group/CGX4pibqJhtKzz3Yy?msg=HyhYgY4SoHtrryDE2

**How does this benefit the users of our platform?**
Clear directions we can link to for requesting restores of data

**Definition of done**
New doc published to https://docs.developer.gov.bc.ca/

**Comment by StevenBarre** [comment]
Not sure who's taking this on, so just assigned a bunch of you :)

**Comment by lukegonis** [comment]
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/3518
