### ISSUE TITLE
SDN - Cerberus not fully working on KLAB2 and EMERALD

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3441]
**Describe the issue**
Cerberus is not fullly functioninig yet in both KLAB2 and EMERALD. Will need to help stakeholders investigate this to see how this can be solved.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
TBD

**Comment by StevenBarre** [comment]
@ShellyXueHan I believe the issue is that the build for Cerberus fails in the NSX clusters. Do you need some help getting that sorted out? Or perhaps it would make more sense to build the image once and put it in Artifactory and pull that?

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/629 approved/merged to go out during next CCM prod push. Once complete, this will fulfill this ticket.

**Comment by wmhutchison** [comment]
Unblocking and closing. Shelly has got this covered under https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/3662.
