### ISSUE TITLE
SDN - Investigate test suite for Vault on KLAB2 and EMERALD

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3445]
**Describe the issue**
One of the vault pods in both KLAB2 and EMERALD isn't properly starting up. Initial investigation revealed some additional and missing netpol, but also appears that perhaps the test suite wasn't correctly configured in Vault. Will investigate and ask for help from the Vault experts as needed.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [x] Perform fresh observation of failing pods and compare against VRLI 
- [x] Created new netpol to allow traffic back from OCP clusters hosting vault back to KLAB2/EMERALD.
- [x] Note new errors on the Vault pods hinting configuration issues with the Vault test suite.
- [x] Wait for Shelly or others to review the configuration of this Vault test suite and adjust as needed.
- [x] Perform final evaluation before concluding this is fixed.

**Comment by wmhutchison** [comment]
It'll need to be tightened up, but to start, both KLAB2 and EMERALD were missing additional networkpolicy rules to allow the traffic from the outbound IPs for the OCP clusters hosting both LAB and PROD Vault back to the test pods.

After that, it looks like the folks who set this test up will need to fix things up since logs on the remote Vault instances both complain about invalid namespace for both the klab2 and emerald tests. Not sure how to fix, will leave that with Shelly/etc.

**Comment by wmhutchison** [comment]
At present, looking in the hosted vault pod logs (KLAB for LAB, GOLD for PROD) and both currently come up with the following as a result of ongoing attempts by the vault test pod not starting up correctly.

```
"error":"namespace not authorized"
```

No new VRLI block issues otherwise to report, thus concluding that there's no more blockage, and this is just a configuration issue that Shelly or someone else will need to address. Reaching out to Shelly on that matter.

**Comment by wmhutchison** [comment]
At present, looking in the hosted vault pod logs (KLAB for LAB, GOLD for PROD) and both currently come up with the following as a result of ongoing attempts by the vault test pod not starting up correctly.

```
"error":"namespace not authorized"
```

No new VRLI block issues otherwise to report, thus concluding that there's no more blockage, and this is just a configuration issue that Shelly or someone else will need to address. Reaching out to Shelly on that matter.

**Comment by wmhutchison** [comment]
Shelly is tied up for a little while with bigger things on the go (SSO migration). Putting in Sprint Backlog for now.

**Comment by wmhutchison** [comment]
@ShellyXueHan Let me know if  I can re-assign this ticket to you or you'll create your own tracking ticket. Came across what I believe to be a configuration issue per the "namespace not authorized" message.

Not a top-level priority yet, but we'll need to ensure Vault is functioning in these clusters before EMERALD goes live to the community which will be sometime in early February.

**Comment by ShellyXueHan** [comment]
@wmhutchison I've restarted the vault-test pod in klab2 and it's working fine now. Not sure what happened previously tho... in emerald things are looking normal.

**Comment by StevenBarre** [comment]
Turns out we don't need the vault-test deployment in the openshift-bcgov-vault namespace. It's now been deleted in both KLAB2 and Emerald and the alerts have cleared.
