### ISSUE TITLE
OCP - Internal Review regarding whether or not there is a need for Openshift AlertManager channels in Rocket Chat

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3476]
**Describe the issue**
Once Upon a Time, someone decided it would be neat if all of the AlertManager notifications generated by each Private Openshift cluster not only gets sent via email to the Platform Operations people, but also gets injected into a unique channel for each Openshift cluster. No one on the Platform Operations side recalls exactly who asked for this, but in recent months, this integration has become buggy in that attempts to view the contents of these channels in Rocket Chat shows up with a blank web page. 

We (Platform Operations) want to know if anyone on the Platform Services side of the fence wants/needs this functionality. If the answer is no, then Platform Operations will take steps to remove the integration between AlertManager and Rocket Chat, which should reduce some data consumption (AlertManger gets quite spammy during certain events including Openshift upgrades). If otherwise the call is to keep these channels, then we will push for new tickets to be opened for a more formal investigation of resolving the issue for displaying these channels to interested parties.

**Additional context**
For a list of channels in Rocket Chat, do a channel search for any channels with the prefix of "ops-alerts-"

**How does this benefit the users of our platform?**
No business benefit to the community, AlertManager notifications mainly relate to the health of the Openshift cluster itself and associated Openshift system pods. 

**Definition of done**
- [x] Discussion among Platform Services on this request to remove or keep AlertManager channels in RocketChat
- [x] Platform Operations to create appropriate tickets/PRs/etc as needed if we are to remove these channels.
- [ ] Platform Services to create appropriate tickets assigned to the correct stakeholders for proper investigation of this matter (RocketChat issue) if we are to keep these channels.

**Comment by faisal-hamood** [comment]
@wmhutchison was this auto-assigned to me or do you need my help with something specific? :)

**Comment by wmhutchison** [comment]
The decision was made to nuke these channels. Closing off this ticket and creating a new one.
