### ISSUE TITLE
OCP - Remove Rocket Chat channel integration from AlertManager configs

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3478]
**Describe the issue**
Based on recent discussion within Platform Services and Platform Operations, it was determined that no one is making use of the channels in Rocket Chat created to receive AlertManager notifications. This, coupled with recurring issues actually viewing content in many of these channels, resulted in the decision to just remove the integration and channels entirely instead of keeping them and investing unknown amounts of time as to why the content visibility issue persists.

**Additional context**
Rocket Chat admins will need to be the ones to remove the Rocket Chat integrations/channels, since Platform Ops people seemingly cannot do this themselves without Rocket Chat going crazy.

The specific channels can be found when searching in https://chat.developer.gov.bc.ca/directory/channels for channels prefixed by `ops-alerts-`.

The RC channel for SILVER has already been removed due to excessive breakage earlier. Before this new decision was made, an older ticket existed to allow us to selectively enable/disable RC integration to prevent breakage when doing SILVER upgrades, but now that this decision was made, that ticket is now moot.

**How does this benefit the users of our platform?**
Internal benefit only to Platform Services/Operations, since removing this integration will a bit of load and a bit more of storage from Rocket Chat. AlertManager is normally reasonably quiet, but can get quite noisy on occasion, thus using up resources inside Rocket Chat.

**Definition of done**
- [x] Create a PR in platform-ops to remove the section involving RC integration from the config-infra role in the alertmanager template. Also remove the RC webhook link in the inventory files. (Tatsuya)
- [x] Same as above, but for the NSX branch (final merge pending). (William)
- [x] Test main PR by applying against CLAB and KLAB. (Tatsuya)
- [x] Perform similar clean-up in RC for KLAB2/EMERALD. (William)
- [x] Monitor Openshift upgrades, confirm alertmanager secret update. (Tatsuya)
  - [x] K/CLAB
  - [x] SILVER
  - [x] GOLD
  - [x] GOLDDR
- [ ] Rocket Chat Admins to remove (if required before removing the channel) Webhook integrations for the following channels:
  - [x] #ops-alerts-clab
  - [x] #ops-alerts-klab
  - [x] #ops-alerts-gold
  - [x] #ops-alerts-golddr
  - [x] #ops-alerts-klab2
- [ ] Rocket Chat Admins to remove the following channels:
  - [x] #ops-alerts-clab
  - [x] #ops-alerts-klab
  - [x] #ops-alerts-gold
  - [x] #ops-alerts-golddr
  - [x] #ops-alerts-klab2

**Comment by tmorik** [comment]
platform-ops PR: https://github.com/bcgov-c/platform-ops/pull/440  (merged to main)

**Comment by tmorik** [comment]
Asking how to proceed removing RC channels : https://chat.developer.gov.bc.ca/channel/rocketchat-help?msg=EknXrhnBnzTggZKQR

**Comment by tmorik** [comment]
All listed channels and their integrations have been removed!
