### ISSUE TITLE
KLAB - Degradation of etcd services

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3488]
**Describe the issue**
Last Thursday we had three changes related to KLAB in relatively short order.
- VMWare team upgraded the ESXi hosts housing all of the KLAB VMs.
- Platform Operations team after the above mentioned VMWare upgrade applied latest firmware update to the KLAB VMs.
- VMWare and Platform Operations that evening (Jan 19th) upgraded the NSX back-end.

Early Friday morning KLAB started to notify regarding etcd stability concerns. This ticket will track the journey as this issue goes through troubleshooting efforts between DXC VMWare, Platform Operations, and Red Hat to find the issue and best fix.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**
No direct benefit to the end users. Indirect benefit since we use our LAB clusters for testing new technologies and for some selected users, their applications before specific updates of concern are applied. CLAB is still fully available as another LAB cluster for such things.

**Definition of done**
- [x] Work with DXC VMWare team to determine if any of the VMWare related changes are the cause.
- [x] Create vendor case with Red Hat and submit data dump with the intent of rebuilding master nodes under the basis that one of the etcd member nodes is corrupt.
- [ ] Follow vendor directions for how to replace etcd on a master node that is crashlooping.
- [ ] Expand DoD as needed for more Action Steps.

**Comment by wmhutchison** [comment]
On January 24th a meeting with Dan Deane was convened to go over the various RFCs involving VMware and how they could have affected KLAB. The end result was that none of the RFC's themselves could have caused KLAB to act the way it has (working, but degraded etcd stability, which is not ideal and should be rectified).

This a vendor case wth Red Hat was opened that same day (https://access.redhat.com/support/cases/#/case/03420476). Today (Jan 25th) Red Hat asked for some data from KLAB to feed into the case so they can help determine what state the etcd cluster is in , since etcd on MCS-KLAB-MASTER-02 is crash-looping. If etcd as hosted by the other two masters is deemed stable, then we will hopefully resolve this issue by following vendor documentation on rebuilding MCS-KLAB-MASTER-02 to resolve this.

**Comment by wmhutchison** [comment]
Since the master node itself still functions, but just have etcd crashlooping, there are instructions we can follow that will allow us to drop the broken etcd member and replace with data from the remaining two nodes, thus avoiding a node rebuild and waiting for VMWare people to help out.

https://docs.openshift.com/container-platform/4.11/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html#restore-replace-crashlooping-etcd-member_replacing-unhealthy-etcd-member

**Comment by wmhutchison** [comment]
The results for the previous comment and work appear to be promising. Will wait until the next day before determining if more intervention is required or if this issue is now resolved.

KLAB/openshift-config ~ $ oc -n openshift-etcd get pods -l app=etcd           
NAME                          READY   STATUS    RESTARTS   AGE
etcd-mcs-klab-master-01.dmz   5/5     Running   0          12m
etcd-mcs-klab-master-02.dmz   5/5     Running   0          10m
etcd-mcs-klab-master-03.dmz   5/5     Running   0          14m

**Comment by wmhutchison** [comment]
Unfortunately the previous results were not meant to last. Today started with degradation once more, but no more crashlooping pods. 

Updated vendor case with new data dumps. Matt Robson also stated that this may very well be an issue with the newest v19 virtual hardware applied to the KLAB VMs, so am waiting first for Red Hat to audit the new data and advise which master we can safely take down and re-image, and then will do so, making sure VMware gives us a new VM entirely for ensuring we avoid the latest virtual firmware. All being well, this will be ready for us to act on first thing next week.

For now, aggressive silence rules in KLAB AlertManager  server to stop spamming the Platform Operations team with messages we cannot resolve due to the stability of the cluster.

**Comment by StevenBarre** [comment]
Tried putting all 3 masters onto the same ESX hosts, no improvement.

Tried adding CPU to the masters, no improvement.

**Comment by StevenBarre** [comment]
Downgraded the vm hardware of the masters, no improvement

**Comment by wmhutchison** [comment]
Upgraded Estimate due to ongoing time involvement to continue investigating and troubleshooting this.

**Comment by StevenBarre** [comment]
Moved masters to a new ESX cluster, no improvement.

Matt has suggested installing `sar` on the master nodes, but the provided directions didn't work.

KLAB has Istio installed, which is different than CLAB, going to try removing it.

May also try turning off the non-master nodes and see if that reduces load on the api and provides any stability.

**Comment by StevenBarre** [comment]
Istio removed, no change.

Turning off nodes just causes more api churn due to the scheduler trying to place pods with no where for them to go.

**Comment by StevenBarre** [comment]
Doubled the RAM of the masters to 48GB. Was able to observe that both ETCD and kube-apiserver are using lots of memory. The increase seems to have allowed ETCD to stay up longer between crashes.

Defragmented ETCD, but the DB is still large. There are over 2.2 million events in ETCD. But most seem to be related to etcd/api issues.

**Comment by StevenBarre** [comment]
Removed the pipeline operator yesterday and that reduced the memory usage and stabilized things. Reinstalled it today and things have remained stable.
Migrated the VMs back to the NSX cluster as that's where we have room for them long term.

**Comment by StevenBarre** [comment]
Back in Dec CLAB started getting HighOverallControlPlaneMemory alerts and we opened https://access.redhat.com/support/cases/#/case/03393728

KLAB is now also showing this alert and we are following up with RH about it.

Otherwise, KLAB has remained stable so far.
