### ISSUE TITLE
Investigate IBM MQ Operator

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3493]
**Describe the issue**
IBM MQ operator is requested by the AG team for use in modernizing an old application. Review its requirements and install it in a Lab cluster to determine if/how it could be supported in Production.

**What is the Value/Impact?**
@anmcgill has an app that will end of life Jan 2024 they would like to transition to OpenShift

**What is the plan? How will this get completed?**
Review IBM MQ docs and then install to a lab cluster. Test the operator works well for @anmcgill and is multitenant safe. Document the support system for the operator.

**Identify any dependencies**
@anmcgill 

**Definition of done**
- IBM MQ operator installed in a lab
- Decision on if we can move forward with installing in PROD

**Comment by StevenBarre** [comment]
IBM MQ only supports EUS versions of OpenShift going forward, ie the even numbered releases. We're unlikely to change our cluster patching to only upgrade to EUS versions and skip the ones in between.

https://www.ibm.com/docs/en/ibm-mq/9.3?topic=operator-version-support-mq

**Comment by StevenBarre** [comment]
Requesting `*.icr.io` added to the Forward Proxy allow list for NSX clusters. That's where the operator catalog and images come from.

**Comment by StevenBarre** [comment]
IBM MQ and IBM Licensing are now installed in KLAB2. @anmcgill can you please request a test namespace in KLAB2 and give it a test drive?

**Comment by StevenBarre** [comment]
Andrew is out of office this week.

**Comment by StevenBarre** [comment]
The team that will be using this operator is new to OpenShift and will need some time to get sufficiently up to speed to start testing. Will close this ticket for now and open a new one once we are ready to port it over to Emerald via CCM

**Comment by wmhutchison** [comment]
Recent blocker until now was that the stakeholders involved did not yet receive a KLAB2 namespace to evaluate this. That's now been changed, so moving this out of Blocked to reflect this.
