### ISSUE TITLE
Create a policy to prevent CronJobs from running too often

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3496]
**Describe the issue**
CronJobs that run more often than every 5 minutes impacts the performance of the k8s API and the cluster.

**What is the Value/Impact?**
Improved cluster performance and stability

**What is the plan? How will this get completed?**
- Roll out policy into production

**Identify any dependencies**
Previous ticket to do all the planning

**Definition of done**
Kyverno policy deployed to PROD

**Comment by jleach** [comment]
I've created the policy as per [PR 605](https://github.com/bcgov-c/platform-gitops-gen/pull/605). Its set to run in the lab clusters for lengthy beta testing. You can use [this](https://gist.github.com/jleach/77bf54c86cc8bcc792a4fef3022d1462) fast running CronJob for testing.

**Comment by StevenBarre** [comment]
Split the ticket into two. Moved all the planning to #3689

This ticket now just for the implementation in PROD

**Comment by StevenBarre** [comment]
This will get rolled out to Prod the week of May 29th via CCM

**Comment by StevenBarre** [comment]
Rolled out
