### ISSUE TITLE
RunWhen - evaluation summary

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3499]
**Describe the issue**
This is to summarize what we've found out about RunWhen product.

**Definition of done**
- [ ] learn about RunWhen and discuss use cases
- [ ] sum up the following:
  - use cases and value-add
  - multi-tenant model
  - platform services team effort to onboard, implement and maintain
  - platform services team effort to support this as a shared service
  - additional information

**Comment by w8896699** [comment]
Evaluation plan: 
1. I will work closely with their team closely to fully implement runwhen on one of the applications to get full user experience(DevOps side point of view)
 - Evaluation key metrics are: ease of use, scalability, and integration with other tools such(Sysdig and uptime.com)
 - How it can make our life easier: determine what feature and capabilities we need from runwhen, what automation we actually need to apply to our application
 - Test plan that includes specific tasks to be performed with RunWhen such as scheduling a script to run? or creating a task to run at a certain condition, (tbd discuss with runwhen team)
 - Document those testing activities and analyzed the results to against the key metrics that I specified. 


2. Try to let an stable application team(Ask Shelly for recommendation) to try with runwhen on they application(Developer side point of view)
 - A demo of how it should work to give them a idea about runwhen
 - Collect feedback from runwhen team on how they feel support the application team
 - Collect feedback from the application team about

3.  How to contribute/develop the code bundle, can we have a workshop to minimize the learning curve?

**Comment by w8896699** [comment]
https://gist.github.com/w8896699/24598d7311b190e26c7c80f95902e4ae
