### ISSUE TITLE
Some finds during setting up vault 

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#3516]
1. Seems like vault doesn't have resources quota for its pod.
2. Namespace doesn't have long-run quota
3. silver vault namespace can be cleaned up
4. c-lab namespace `pye-vault` can be cleaned up
4. vault-test deployment doesn't have resrouces limite

**Comment by IanKWatts** [comment]
1. Resource limits have been set for the 'vault' StatefulSets
2. Both the agent injector and vault now have resources limits, so did not add 'compute-long-running-quota'
3. Silver vault namespace openshift-bcgov-vault has only what we need - don't see another namespace with Vault resources in it
4. CLAB namespace 'pye-vault' was empty and has been removed
5. The vault test app has been revised and now includes resource limits in its app deployment and patroni stateful set
