### ISSUE TITLE
KLAB2 - Use Kyverno to ensure Trident network annotation remains in place

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3517]
**Describe the issue**
During the OCP 4.10 upgrade of KLAB2, the Trident operator refreshed the deployment configuration for the Trident CSI pods, which resulted in major breakage of all pods using any NetApp storage, and in a few cases, resulted in block storage corruption.

Before we can consider moving forward with the OCP 4.10 upgrade of EMERALD (required before that cluster will be promoted for active use by the entire community), we need to solve this issue in KLAB2, and the Kyverno tool seems to be a good fit to do this.

**Additional context**

**How does this benefit the users of our platform?**
Ensuring Openshift cluster maintenance does not result in breakage or corruption of persistent storage from NetApp volumes.

**Definition of done**
- [x] Research or investigate how to configure Kyverno to keep network metadata persistent inside Trident csi deployment
- [x] Test in KLAB2 to confirm the change works.

**Comment by StevenBarre** [comment]
After some testing, found that Kyverno is ignoring `openshift-*` namespaces so its not accepting the Policy I created. Working with Jason to find a workaround.

**Comment by StevenBarre** [comment]
Doesn't look like there will be a good workaround here. Will need to solve the trident issue some other way.

**Comment by wmhutchison** [comment]
Dunno if it''ll work or not, but we might need to ditch the operator when it comes to how we manage Trident on KLAB2/EMERALD and move to using tridentctl for installing/upgrading. The following link allows generation of full YAML files that we can then customize for our needs, which would then include adding the specific stuff we need, knowing no pesky operator's going to yoink it.

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy-tridentctl.html

FYI here's all that can be tweaked for our current method, which would allow us to address the general desire to source our images from Artifactory, but offers no hooks for the stability issues at present.

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy.html

**Comment by StevenBarre** [comment]
Started updating the playbooks to uninstall the operator and switch to using `tridentctl install` instead as it gives more control and ensures no surprise updates to deployments.

Found that the registry.k8s.io registry uses several backends and redirects to them via 301 Redirects. So it's going to be impossible to keep all the possible URLs in the forward proxy.

Opened a ticket with Cailey to have it added as a pull-through cache in Artifactory. Also added code to cache all the images locally in the clusters image registry.

Still facing some struggles but making progress.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-ops/pull/445

Needs a bit more work, but the bulk is done and tested.

**Comment by StevenBarre** [comment]
Figured out how to pre-pull images to nodes to improve speed of daemonset rollout

**Comment by StevenBarre** [comment]
Pushed some more commits adding pre-pull in parallel and removing the old Operator deployment.

**Comment by wmhutchison** [comment]
successfully tested in KLAB2, using another OCP upgrade (to v4.10.52) as the testing mechanism.
