### ISSUE TITLE
Service Transition - accounts and orgs

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3521]
**Describe the issue**
This is to transition some of the low maintenance service ownership to DevEx team.

 - github orgs (bcgov, bcgov-c, enterprise org, BCDevOps)
 - dockerhub orgs
 - NPM org

**Definition of done**
- [x] Knowledge Transfer
- [x] account ownership transitioned

**Comment by ShellyXueHan** [comment]
@MonicaG could you confirm that you have admin access to the above orgs? There should be several invites sent out already but I'm not sure if you've received all of them.

**Comment by MonicaG** [comment]
@ShellyXueHan - yes, I see admin functions on npm now. I will contact Nick about the Enterprise GitHub org admin.

**Comment by NickCorcoran** [comment]
GitHub Enterprise org admin granted.
