### ISSUE TITLE
Prep for usability testing with users for Registry 2.0

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3530]
**Describe the issue**
Complete all preparations for the usability/task testing with users. 

**How does this benefit the users of our platform?**
Making sure the website is easy to use and navigate. 
**Definition of done**

- [x] Finish script

- [ ] Book meetings

- [x] Create notetaker's guide

**Comment by Iryna-Kaplun** [comment]
This ticket got moved to the registry repo #1017
