### ISSUE TITLE
Conducting usability testing with users

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#3531]
**Describe the issue**
Actually running 5 to 7 usability sessions with both POs and TLs.

**Additional context**
May have to do this after go live.

**How does this benefit the users of our platform?**
Making sure the platform is easy to use and navigate. 

**Definition of done**

- [ ] All sessions are completed

- [ ] Interviews are transcribed accurately

**Comment by Iryna-Kaplun** [comment]
This ticket got moved to the registry repo #1016
