### ISSUE TITLE
Weekly CCM PROD Push for Feb 14 to Feb 16

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#3532]
**Describe the issue**
This ticket will track efforts spent toward creating the next CCM release and promoting it against the three production Openshift clusters.

**Definition of done**
- [x] Create suitable GitHub Release before EOD Friday
- [x] Create suitable Standard Change RFCs and assign to team members as appropriate
- [x] Create and Receive approval for PR incrementing CCM version for PROD clusters
- [x] Ensure version increment PR is merged before executing any RFCs
- [x] Execute RFC for SILVER & EMERALD cluster
- [x] Execute RFC for GOLD cluster
- [x] Execute RFC for GOLDDR cluster

**Comment by tmorik** [comment]
## v4.14.0 for OCP 4.11

### What's Changed
* Collect Kyverno metrics in Prometheus by @StevenBarre https://github.com/bcgov-c/platform-gitops-gen/pull/607
* Remove gitops-shared from cluster-apps by @IanKWatts https://github.com/bcgov-c/platform-gitops-gen/pull/606

https://github.com/bcgov-c/platform-gitops-gen/pull/608

**Comment by wmhutchison** [comment]
CCM push for EMERALD/SILVER now complete.

**Comment by tmorik** [comment]
CCM push for GOLD completed. 

One note:
- CCM shows `Synced` for rhacs operator but it's still processing state because InstallPlan for RHACS is pending state. 

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/92fed0bc-fe59-4fa6-8190-06f19202d4a8)

![image.png](https://images.zenhubusercontent.com/5ea9f983189dd56ef6dde075/297b3cba-4ac6-416e-90d3-750745849dbc)

This pending installplan will be approved in next CCM push.

**Comment by tmorik** [comment]
GOLDDR's CCM push completed successfully.
