### ISSUE TITLE
Add Artifactory pull through for registry.k8s.io 

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3536]
**Describe the issue**
Trident depends on images from registry.k8s.io . The NSX clusters have difficulty reaching that repo as the URL redirects to several different backends, some on AWS S3, making it difficult to add everything to the forward proxy.

**What is the Value/Impact?**
Improved reliability for fetched images for Trident.

**What is the plan? How will this get completed?**
Too be filled out by Cailey

**Identify any dependencies**
None

**Definition of done**
Pull through cache set up and documented

**Comment by caggles** [comment]
artifacts.developer.gov.bc.ca/k8s-docker-remote all ready to go!
