### ISSUE TITLE
Ensure all clusters have all pull secrets

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3537]
**Describe the issue**
All clusters should have all needed pull secrets installed

The ansible inventory vaults should be updated to also have all the pull secrets

**What is the Value/Impact?**
Lack of artifactory or docker pull secrets can lead to issues pulling images from those repos

**What is the plan? How will this get completed?**
- Confirm full list of repos
- Update ansible vaults for all clusters
- Update secret on the cluster if its missing anything

**Identify any dependencies**
None

**Definition of done**
Note which clusters need fixing, to be done during next quarter patching

Secret value check:
- [x] Silver 
  - repo value and installed value match
  - podman test for `artifact`, `quey.io` and `registry.redhat.io` were OK.
- [x] Gold 
  - repo value and installed value match
  - podman test for `artifact`, `quey.io` and `registry.redhat.io` were OK.
- [x] GoldDR 
  - repo value and installed value match
  - podman test for `artifact`, `quey.io` and `registry.redhat.io` were OK.
- [x] Klab
  - repo value and installed value match
  - podman test for `artifact`, `quey.io` and `registry.redhat.io` were OK.
- [x] Clab 
  -  repo values  DO NOT match with installed values
  - `docker.io` is missing in the installed secret
  - podman test for `artifact` (klab's secret is installed), `quey.io` and `registry.redhat.io` were OK. 
- [x] Emerald 
  - repo values  DO NOT match with installed values
  - `docker.io` is missing in the repo value, but it's in the installed secret.
  - `podman pull registry.redhat.io/redhat/redhat-operator-index:v4.12` test was successful. 
  - podman test for `artifact` was FAILED.
  - podman test for `quey.io` was successful. 
- [x] Klab2 
  - repo values DO NOT match with installed values
  - creds are hard-corded in the cluster. 
  - podman test for artifact (klab's secret is installed) and registry.redhat.io were OK. . 
  - podman test for `quey.io` was successful.

**Comment by StevenBarre** [comment]
Need to ensure quay.io is included in all clusters before May 1st

**Comment by tmorik** [comment]
Ref: 
- https://docs.openshift.com/container-platform/4.12/installing/install_config/configuring-firewall.html#configuring-firewall_configuring-firewall
- https://access.redhat.com/articles/6999582

**Comment by tmorik** [comment]
How to check:

```
// From util servers, run podman.
KLAB/openshift-operators ~ $ sudo -i
[sudo] password for tmorik_a:
[root@mcs-klab-util ~]# podman login registry.redhat.io
Username:  <keepass - Red Hat Image Registry cred>
Password:
Login Succeeded!
[root@mcs-klab-util ~]# podman pull registry.redhat.io/redhat/redhat-operator-index:v4.12
Trying to pull registry.redhat.io/redhat/redhat-operator-index:v4.12...
Getting image source signatures
Copying blob f0b07b5fac1e done
Copying blob 98b5d479a07e done
Copying blob 766eb4e6e310 done
Copying blob 93809c7db2a0 done
Copying blob efb7b6a40e86 done
Copying blob 697b6ee4d96c done
Copying config 12433d07f7 done
Writing manifest to image destination
Storing signatures
12433d07f7f048e0c02bf6dd9bcb8d7c81fc0524c143ad870fa7583ff78885ae
// Check if return value is `0` 
[root@mcs-klab-util ~]# echo $?
0
```

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/rhcos-ignition-builder/blob/master/inventory/group_vars/klab_util/vars.yaml#L23 the values in the vaults for all clusters should be compared.

And the actually installed secret in each cluster should be checked that it matches the vault value
https://console.apps.klab.devops.gov.bc.ca/k8s/ns/openshift-config/secrets/pull-secret

**Comment by tmorik** [comment]
How to check vaults:

1. Get Ansible vault value

```
git pull rhcos-ignition-builder
cd rhcos-ignition-builder
ansible-vault decrypt inventory/group_vars/klab_util/vault.yaml --output=/home/<your dir>/decrypted_vault
```

2.  Get `pull-secret` secret from `openshift-config` Namespace

```
oc -n openshift-config get secret pull-secret -o json | jq '.data[]' | sed s/\"//g | base64 -d > /home/<your dir>/decrepted-pull-secret
```

3. Compare both are match using `diff` etc.
4. Test `podman` command in the comment above.
5. Delete `/home/<your dir>/decrepted-pull-secret` and `/home/<your dir>/decrypted_vault`.

**Comment by tmorik** [comment]
Checked all clusters as check list in the DoD.  The pull-secret in the CLAB, KLAB2 and EMERALD need to be updated.

**Comment by wmhutchison** [comment]
Make sure all clusters have an Artifactory pull secret. It's needed for fulfilling the Trident upgrades for OCP 4.12, which for PROD will fall on a Sunday. Check the OCP 4.12 top-level EPIC for some preliminary RFC date ranges (will be solidified once we've actually finished upgrading CLAB and addressing all potential issues)

**Comment by wmhutchison** [comment]
One liner to show the contents of the global pull secret in a nice format on any cluster.

```
oc -n openshift-config get secret pull-secret -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d | jq
```

**Comment by tmorik** [comment]
Checked `artifacts.developer.gov.bc.ca` secret in all clusters. Emerald was not able to login using installed secret.

```
    "artifacts.developer.gov.bc.ca": {
      "username": "<user>",
      "password": "<pass>",
      "auth": "<auth string>",
      "email": ""

// podman login - failed	  
EMERALD/openshift-config ~ $ sudo -i
[sudo] password for tmorik_a:
[root@mcs-emera-util ~]# podman login artifacts.developer.gov.bc.ca
Username: emerald-cluster
Password:
Error: authenticating creds for "artifacts.developer.gov.bc.ca": pinging container registry artifacts.developer.gov.bc.ca: Get "https://artifacts.developer.gov.bc.ca/v2/": read tcp 10.99.1.4:58006->142.34.229.249:8080: read: connection reset by peer
[root@mcs-emera-util ~]#
```

The other clusters are OK like below

```
[root@mcs-silver-util ~]# podman login artifacts.developer.gov.bc.ca
Username: <user>
Password: <pass>
Login Succeeded!
[root@mcs-silver-util ~]# podman image list
REPOSITORY                                                  TAG      IMAGE ID       CREATED         SIZE
registry.redhat.io/redhat/redhat-operator-index             v4.12    25dcc33e5c9c   11 hours ago    1.39 GB
<none>                                                      <none>   12433d07f7f0   12 days ago     1.36 GB
registry.opensource.zalan.do/acid/spilo-14                  2.1-p5   bf119bc65a55   11 months ago   801 MB
ghcr.io/bcgov-platform-services/platform-gitops-container   latest   92864ac86514   12 months ago   1.23 GB
```

Remark: KLAB2 and CLAB are using KLAB's cred.

**Comment by tmorik** [comment]
Confirmed `quey.io` secret is in the installed pull-secret and login test was successful for all clusters.

**Comment by tmorik** [comment]
CLAB, Emerald and KLAB2 needs to be synced.

**Comment by tmorik** [comment]
To update global pull secret (pull-secret), I will follow the steps in this doc : 

 - [How to change the global pull secret in OCP 4](https://access.redhat.com/solutions/4902871)

**Comment by tmorik** [comment]
## pull secret updating steps

1. Get Ansible vault value

```
git pull rhcos-ignition-builder
cd rhcos-ignition-builder
ansible-vault decrypt inventory/group_vars/klab_util/vault.yaml --output=/home/<your dir>/decrypted_vault
```

2. Updating an existing secret

```

oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=/home/<your dir>/decrypted_vault

```

3. Check result

```
// Check secret
oc get secret pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode}}' | jq

// Check node status
oc get nodes && oc get mcp

// podman login and pull test
sudo podman login artifacts.developer.gov.bc.ca
sudo podman pull registry.redhat.io/redhat/redhat-operator-index:v4.12

```

Ref:

- https://access.redhat.com/solutions/4902871
- https://docs.openshift.com/container-platform/4.11/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets


#KLAB2

```

NSX KLAB2/openshift-operators ~ $ oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=klab2-repo-decrypted_vault
secret/pull-secret data updated

NSX KLAB2/openshift-operators ~ $ oc get secret pull-secret -n openshift-config --template='{{index .data ".dockerconfigjson" | base64decode}}' | jq
{
  "auths": {
    "artifacts.developer.gov.bc.ca": {
      "auth": "<secret string>"
    },
    "cloud.openshift.com": {
      "auth": "<secret string>"
      "email": "<email>"
    },
    "quay.io": {
      "auth":  "<secret string>"
      "email": "<email>"
    },
    "registry.connect.redhat.com": {
      "auth":  "<secret string>",
      "email": "<email>"
    },
    "registry.redhat.io": {
      "auth":  "<secret string>",
      "email": "<email>"
    }
  }
}

// Check if  nodes are restarting -- no reboot
NSX KLAB2/openshift-operators ~ $ oc get mcp
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADED
infra    rendered-infra-5f0e4f19d592617481ba413f3749abfa    True      False      False      3              3                   3                     0
master   rendered-master-d605eb9b9f66a9675956d0be81a78077   True      False      False      3              3                   3                     0
worker   rendered-worker-5f0e4f19d592617481ba413f3749abfa   True      False      False      4              4                   4                     0
NSX KLAB2/openshift-operators ~ $ oc get node
NAME                      STATUS   ROLES    AGE    VERSION
mcs-klab2-app-01.dmz      Ready    worker   215d   v1.23.12+8a6bfe4
mcs-klab2-app-02.dmz      Ready    worker   215d   v1.23.12+8a6bfe4
mcs-klab2-app-03.dmz      Ready    worker   215d   v1.23.12+8a6bfe4
mcs-klab2-app-04.dmz      Ready    worker   213d   v1.23.12+8a6bfe4
mcs-klab2-infra-01.dmz    Ready    infra    216d   v1.23.12+8a6bfe4
mcs-klab2-infra-02.dmz    Ready    infra    216d   v1.23.12+8a6bfe4
mcs-klab2-infra-03.dmz    Ready    infra    216d   v1.23.12+8a6bfe4
mcs-klab2-master-01.dmz   Ready    master   216d   v1.23.12+8a6bfe4
mcs-klab2-master-02.dmz   Ready    master   216d   v1.23.12+8a6bfe4
mcs-klab2-master-03.dmz   Ready    master   216d   v1.23.12+8a6bfe4

// podman login & pull test
NSX KLAB2/openshift-operators ~ $ sudo podman login artifacts.developer.gov.bc.ca
[sudo] password for tmorik_a:
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to artifacts.developer.gov.bc.ca

NSX KLAB2/openshift-operators ~ $ sudo podman image list
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE

NSX KLAB2/openshift-operators ~ $ sudo podman pull registry.redhat.io/redhat/redhat-operator-index:v4.12
Trying to pull registry.redhat.io/redhat/redhat-operator-index:v4.12...
Getting image source signatures
Copying blob 93809c7db2a0 done
Copying blob dbe90aa35940 done
Copying blob 0bc6f9525df0 done
Copying blob 113f1ccf7cb9 done
Copying blob 766eb4e6e310 done
Copying blob e6923aa206c9 done
Copying config 4d25b47b61 done
Writing manifest to image destination
Storing signatures
4d25b47b61cd4556a113cd10b957548ce34658987938528e3c006eba116ce712

```

**Comment by tmorik** [comment]
The Change CHG0047538 completed successfully.

**Comment by tmorik** [comment]
The Change CHG0047538 completed successfully.
