### ISSUE TITLE
Provisioner should delete files from namespaces repos

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#3559]
**Describe the issue**
If a file exists in a project's directory in a namespaces repo, and the provisioner does not create that file, it should be removed from the repo.  For example, a 'services' quota file was created for a project set in Emerald, which should not have a services quota.  Re-running the provisioner correctly did not create that file, but also did not remove it.

**What is the Value/Impact?**
The namespaces repos need to be properly maintained by the provisioner.

**What is the plan? How will this get completed?**
Look into how the provisioner updates the repos.  Add the ability to delete files that are no longer used.

**Identify any dependencies**
For this to work as expected, "pruning" should be enabled on all namespace Applications in Argo CD.  Update the provisioner template for Applications so that this is the case. 

**Definition of done**
- [x] Issue has been addressed in the tenant role
- [x] Provisioner Application template is set to prune resources
- [x] New app-provisioner image has been built and deployed

**Comment by StevenBarre** [comment]
CCM handles it like this https://github.com/bcgov-c/platform-gitops-gen/blob/master/.github/workflows/push-emerald-config-generation.yaml#L56-L62

**Comment by IanKWatts** [comment]
Noted, thanks Steven!

**Comment by IanKWatts** [comment]
https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/149
