### ISSUE TITLE
SDN - Fix and add static KLAB2 STOR dhcpd include to GitHub repo

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3564]
**Describe the issue**
During the course of an emergency RFC involving DNS issues needing us to update dhcpd.conf on all our Openshift clusters, it was discovered that the unique situation of KLAB2 STOR network is not persistent, and thus when a refresh of KLAB's dhcpd.conf configuration  takes place from regular IDIR home folder versus a specific folder as root, then KLAB2's STOR entries are not included in KLAB's dhcpd.conf, thus resulting in missing entries, which over a longer period of time, would have resulted in KLAB2 losing all of its IP addresses used to access NetApp Storage.

This ticket will address reviewing and cleaning this up so that re-running KLAB's playbook for refreshing dhcpd.conf will not lose these KLAB2 IP addresses later on when the dhcp lease expires on the assigned IP addresses.

**Additional context**
KLAB2 has a NetApp instance that is carved off of the KLAB NetApp instance. Because KLAB's NetApp instance is a virtual instead of physical appliance, the KLAB2 NetApp instance must be on the same network VLAN as KLAB's NetApp instance. KLAB-UTIL is currently the provider of DHCP services to the KLAB/KLAB2 NetApp network VLAN, thus we can't let KLAB2-UTIL also attempt DHCP services for this same network range. Thus what happens is that running the playbook on KLAB2-UTIL creates a stub file that we then copy over to KLAB-UTIL to be read in and thus inject the additional network definitions for KLAB2 NetApp access from the KLAB-UTIL server. This ticket will serve to ensure that stub file generated is now sourced from GitHub repo instead of being manually copied over between servers.

This is not an issue with EMERALD. EMERALD NetApp, like KLAB2 NetApp, is an instance off of another NetApp (SILVER in this case), but since SILVER NetApp is a physical instead of virtual appliance, we are able/allowed to assign EMERALD NetAPP its unique and separate network VLAN, thus avoiding this split-dhcpd configuration as experienced by KLAB/KLAB2.

**How does this benefit the users of our platform?**
Fixes of this nature improve the stability of our Openshift platforms.

**Definition of done**
- [x] Review and refresh how current roles are handling the dhcpd.conf.
- [x] Investigate how best we can include the KLAB2 dhcpd snippet into the GitHub repo but ensure other clusters are not reading in the KLAB2 content as well.
- [x] Implement and test any required changes.

**Comment by wmhutchison** [comment]
1. We need to be able to add a structure to the cluster's inventory file like this:

```
dhcp-includes:
  prod:
  - prod-from-klab2.yaml
  - others-if-desired.yaml
```

2. We then need to modify NSX dhcp so that the stub files generated are placed in roles/dhcpd/files or roles/dhcpd/includes. File names generated mention the network type and cluster name.

3. We then modify the dhcpd.conf.j2 so it'll detect and include all matching include files that it sees.

**Comment by wmhutchison** [comment]
These general changes also start to align this repo's code to better align for the future if/when we migrate these playbooks into DXC's internal Ansible Tower instance. Once that's done, the inventory structure would then be used to specify additional content, and then the playbook execution could both generate the original cluster's dhcpd.conf content, and then also dynamically generate/include additional dhcpd.conf content to include. Thus able to generate KLAB dhcpd.conf and include KLAB2 STOR dhcpd.conf content without the need to have this pre-generated and injected as a static include from Github.

**Comment by StevenBarre** [comment]
Just spit-balling here, but Ansible will load everything in `inventory/`. So maybe we could just reference the other cluster inventory from the playbook when needed?

In the template we are using `hostvars[groups[groupname][0]]['group_network_conf']`, where `groupname` is just an auto var for the current hosts group I think? Can just also reference the klab2 group if our current group is klab or something?

**Comment by wmhutchison** [comment]
If we're 100% certain the KLAB/KLAB2 situation will be the only one, I'm fine with hacking it in that way, will certainly save some time here. :)

**Comment by wmhutchison** [comment]
hmmm, for this to work I guess we'd have to tell jinja2 to use another inventory outside of the one mentioned? And if so, how to do that?

 Running "ansible-inventory -i inventory/klab --list" lists only KLAB assets, KLAB2 not to be found.

My attempt to add a "if KLAB then re-run the above snippet but with groupname replaced with "klab2_nodes" failed with not knowing anything about "klab2_nodes" which does make sense given how the inventory is currently ingested.

Putting a pin in this approach for now, happy to circle back to it if we know how to deal with multiple inventory files, or how to tweak the template to correctly reference both KLAB and KLAB2 inventory content.

**Comment by wmhutchison** [comment]
Updated PR to reflect the hack for this. Hacked specifically for just KLAB/KLAB2. Tested temporarily in KLAB, but not going to walk away for the weekend + flex for such a change, even if it's just KLAB.

Will re-test next Tuesday, and based on results, promote PR formally for review/approval. https://github.com/bcgov-c/rhcos-ignition-builder/pull/104

**Comment by wmhutchison** [comment]
PR reviewed and approved after fulfilling an additional documentation request. Ticket can now be closed.
