### ISSUE TITLE
Renew Shared Services Certs

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#3582]
**Describe the issue**
MySC Order for: 
Date Submitted:
MySC Number:
Lead time (business days after EA Approves):

Luke and Dana submit MySC orders
Billy ensure Certbot installs certs

**Definition of done**
- [ ] Business area creates/submits order
- [ ] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [ ] EA Approves 
- [ ] Order is sent to DXC for fulfillment 
- [ ] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by w8896699** [comment]
Completed and recorded at : https://docs.google.com/spreadsheets/d/1pvaxCdYts1MeRv7bHP10a1yt_MGk6KpK/edit#gid=755033945
