### ISSUE TITLE
Add netpol to nsx-system-operator namespace

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#3593]
**Describe the issue**
The Compliance Operator has identified that some namespaces don't have any NetworkPolicies and is encouraging us to add them.

**Additional context**
https://github.com/bcgov/how-to-workshops/tree/master/labs/netpol-quickstart

**Definition of done**
Add KNP to `nsx-system-operator` namespace in EMERALD (and KLAB2)

**Comment by StevenBarre** [comment]
Tested in KLAB2, doesn't explode the cluster. Will use CCM to implement in PROD

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/623

**Comment by StevenBarre** [comment]
Blocked waiting for CCM rollout next week to Emerald
