### ISSUE TITLE
Compliance scan result check for EMERALD and KLAB2 clusters

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#3594]
**Describe the issue**
Compliance Operator's scan result for EMERALD and KLAB2 Clusters shows `FAIL` status for some rules. We need to make sure these rules are necessary for EMERALD and KLAB2. And create a tailored profile for the clusters on NSX if they can be ignored.  

**Additional context**
- [Check result spreadsheet](https://advsolcan.sharepoint.com/:x:/r/sites/ManagedContainerServicesMCS/Shared%20Documents/Daily%20Ops/Cluster%20Compliance%20Check/ComplianceCheckResults_2023_Mar.xlsx?d=w9093e1d851094496a6057ead9483bd31&csf=1&web=1&e=M4hVFi)

To check the current status of each rules, Read **INSTRUCTIONS** and **DESCRIPTIONS** fields in this spreadsheet.

**Definition of done**
- [x] Check each rules
- [x] Create tailored profile for them as needed
- [x] Deploy tailored profile using CCM

**Comment by StevenBarre** [comment]
`oc delete secrets kubeadmin -n kube-system` in KLAB2 and Emerald should solve `ocp4-cis-mcs-kubeadmin-removed`

**Comment by StevenBarre** [comment]
Opened https://access.redhat.com/support/cases/#/case/03454381 for all the OVS alerts. The NSX clusters are using the NCP network plugin instead of OVS these are false alerts. Confirming with RH if there's a way to trick the compliance operator or if we should just exclude those tests on these clusters.

**Comment by StevenBarre** [comment]
Enabled debug mode and uploaded fresh logs to RH case

**Comment by StevenBarre** [comment]
Red Hat has created a bug to track this

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/653
