### ISSUE TITLE
Proper monitoring for internal ACS certificates

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3613]
**Describe the issue**
There are a number of internal ACS certificates used both within an ACS instance on a cluster as well as integrating a controlling ACS instance with other managed ACS instances. Those internal certificates do expire and need to be refrshed, but at present the only way to check on this is to remember to login to the controlling ACS web console and see if the certs are about to expire.

This ticket will explore automation  of monitoring these certificates and export to the existing custom Nagios checks performed already in the `openshift-bcgov-nagios` namespace. That way we will not be beholden to manual processes for keeping on top of these internal certificates.

**Additional context**
Inspection of the download YAML file tells us the following secrets are what get refreshed for the internal certificates involved. To be found in the `stackrox` namespace.

```
sensor-tls
admission-control-tls
collector-tls
```

**How does this benefit the users of our platform?**
- [ ] Develop new Nagios monitoring check - content/code changes to reside in a new branch/PR.
- [ ] Test new check in a LAB environment.
- [ ] Obtain review/approval of the PR before merging.
- [ ] Create RFCs for updating the PROD clusters with the new Nagios check.

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by StevenBarre** [comment]
Is it the web facing URL? or some internal cert? If its external, Nagios Active should be able to hit it and alert us when we are 90 days out, same as the default apps cert.

**Comment by wmhutchison** [comment]
Going to close this ticket off as un-necessary. Due to our ongoing need to manage ACS upgrades ourselves, we're forced to see/review the status of certs during each ACS upgrade, thus can plan the internal cert replacement accordingly. Might revisit this if/when ACS operator resumes being a fully automated upgrade.
