### ISSUE TITLE
Renew certificates for PROD and LAB RHACS websites before April 1st 2023

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3614]
**Describe the issue**
Need new web console certs for the two ACS implementations before April 1st, 2023:
https://acs-lab.developer.gov.bc.ca
https://acs.developer.gov.bc.ca

**How does this benefit the users of our platform?**
Maintain the https capability of the ACS consoles which provides additional security.

**Definition of done**

- [ ] Certificate for LAB ACS updated
- [ ] Certificate for PROD ACS updated

**Comment by tbaker1313** [comment]
Adding Luke as he will probably need to order the certs.

**Comment by w8896699** [comment]
We ended up create a CSR and send it to Justin Thomason, and use the Cert from him to update in CCM repo's GIthub Action's secrets.
