### ISSUE TITLE
Move platform-developer-docs from bdec76-dev to bdec76-prod

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#3616]
**Describe the issue**
Move the platform-developer-docs app from the bdec76-dev environment to the bdec76-prod environment. The production version of the app should always stay in the prod environment.
Invite Billy to discuss this ticket and clarify details.

**Additional context**
- [ ] Update the route for the platform-developer-docs app to point to the bdec76-prod environment
- [ ] Update the certbot configuration to include the bdec76-prod environment
- [ ] Create a new deploymentconfig for the platform-developer-docs app in the bdec76-prod environment
- [ ] Copy over any necessary secrets to the bdec76-prod environment
- [ ] Verify that the app is running correctly in the prod environment

**How does this benefit the users of our platform?**

**Definition of done**
- [ ] The platform-developer-docs app is successfully running in the bdec76-prod environment
- [ ] The route, certbot, deploymentconfig, and secrets have been updated to reflect the move to the prod environment
- [ ] All necessary configurations and settings have been updated to ensure proper functionality of the app in the prod environment.

Next step, probally add CI/CD to this app

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/BCDevOps/developer-experience/3616?planning-poker) with Zenhub @Kolezhanchik @okanji @funtigr

**Comment by Iryna-Kaplun** [comment]
This issue is duplicated on the registry repo #1006. This one will be closed as #1006 will be the main ticket for this work.
