### ISSUE TITLE
SDN - New Web Forward Proxy Request dated for March 10th 2023

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3622]
**Describe the issue**
Additional URL requests are being received via Rocket Chat (https://chat.developer.gov.bc.ca/channel/nsx-early-adopters?msg=y9kqTbE3wN86nRGMZ).

**Additional context**
New URLs requested to date:
- api.nuget.org
- *.nuget.org (added in case the above does not cover off all required access)

Links:
- [original request in Rocket Chat:](https://chat.developer.gov.bc.ca/channel/nsx-early-adopters?msg=y9kqTbE3wN86nRGMZ)
- [link to ZenHub ticket:](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/3625)

**How does this benefit the users of our platform?**
Adding requested URLs to the NSX Forward Web Proxy configuration will allow developers to proceed as needed with their work on the EMERALD Openshift cluster.

**Definition of done**
- [x] clearly communicate to the involved users when the cut-off for receiving the current batch of new URLs will be (ASAP or a date in the near future)
- [x] Copy the Word docuement and save with a file name reflecting the date for the new submission.
- [x] Create in ZenHub an iStore template ticket with the details of this request. Assign to Luke Gonis, place ticket in Operations Pipeline.
- [x] Email Luke Gonis and PO with an attachment for the new request and ask it to be input into iStore. Reference the created ZenDesk ticket.
- [x] Confirm receipt of emails for DXC and OCIO stakeholders as they approve the work.
- [x] Confirm when implementation date is received and update this ZenHub ticket ass well as the ZenHub ticket created for iStore order. (March 21st per NETSRM 296351 RITM0141229)
- [x] Confirm after implementation date that the new URL works correctly (can be tested from UTIL servers as well as a test pod in either KLAB2 or EMERALD).

**Comment by wmhutchison** [comment]
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/3625 created for Luke to track the iStore side of things.

**Comment by wmhutchison** [comment]
Blocked pending scheduled date of DXC Network change to implement this URL addition.

**Comment by StevenBarre** [comment]
Scheduled for March 21st per NETSRM 296351 RITM0141229

**Comment by wmhutchison** [comment]
Successfully completed, Tested from UTIL servers to confirm. Notified on #nsx-early-adopter channel.
