### ISSUE TITLE
QA 20 new Silver worker nodes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3623]
**Describe the issue**
Need a separate set of eyes to double check the new nodes are built correctly and ready to join the cluster.

**What is the Value/Impact?**
Better odds of a successful CHG to add the nodes to the cluster

**What is the plan? How will this get completed?**
QA the nodes

**Identify any dependencies**
None

**Definition of done**
QA tasks closed in theHUB

**Comment by tbaker1313** [comment]
Completed.
