### ISSUE TITLE
Change project to product (universal changes)

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3633]
**Describe the issue**
There are both "project" and "product" names used in the registry and we need to replace "project" with "product" to avoid confusion and be consistent. 

**Definition of done**
There is no "project" terminology in the registry and only "product" is used across the website.

**Comment by alexandralloyd** [comment]
[Uploading... Screenshot 2023-03-16 at 9.11.56 AM.png]

Circles are where a space is added and underlines are where we can change project to product.

**Comment by alexandralloyd** [comment]
[Uploading... Screenshot 2023-03-16 at 9.11.56 AM.png]

**Comment by funtigr** [comment]
Also on the second screenshot there are two unmarked places with word "project". Near the Minitstries Dropdown.
"this **project** belongs to" and "request for a new **project**."

**Comment by alexandralloyd** [comment]
https://drive.google.com/drive/folders/1xe2-u3h-VpOeW6HFdbdL9zHP6aB4vK4M

Circle is where the quotation marks should be removed

**Comment by alexandralloyd** [comment]
https://drive.google.com/drive/folders/1xe2-u3h-VpOeW6HFdbdL9zHP6aB4vK4M

Circle is where the quotation marks should be removed

**Comment by alexandralloyd** [comment]
https://drive.google.com/drive/folders/1xe2-u3h-VpOeW6HFdbdL9zHP6aB4vK4M

https://drive.google.com/drive/folders/1xe2-u3h-VpOeW6HFdbdL9zHP6aB4vK4M

**Comment by funtigr** [comment]
Most of them are quick-fixed now but still a couple left:
This screenshot is made on Requests Tab but the same thing is in the same place on Product Tab:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/0b0d8c5b-60b2-4595-95f7-d8e8f3ea1c52)
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/d596037a-8cac-4fbf-85b7-92faf7bda52a)
