### ISSUE TITLE
Update the Ministry name/acronym for the Ministry that split into 2 (Ministry of Forests and Ministry of WLRS) for creating new product/namespace

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3635]
**Describe the issue**
As a user creating a new product/namespace, I want to be able select my new ministry so that my info is accurate. Split off from the issue #3634

**Rational/Why**
Clients should be able to choose the proper Ministry name in the dropdown Ministry list when creating a new product/namespace and the old Ministry name should be hidden in the list. 

**Additional Context** 
Oamar will create a script for data base migration for further changes in Ministry names

**Dependencies**
provisioner and ACS. Without provisioner and ACS it can't go live. 

**Tests**

**Definition of done/Acceptance Criteria**
There are no old Ministry names (Natural Resources; Municipal Affairs; Housing) in the dropdown list and new updated Ministry names are available for clients to select from.

**Comment by okanji** [comment]
As discussed with Nick. A change to the ministries has implications for both the provisioner and ACS. We have determined that this is therefore a 'large effort small reward' ticket. If there is a big push to change the Ministries, it will require Nick and Ian to get involved in addition to the dev team.

**Comment by Iryna-Kaplun** [comment]
Based on Oamar's comment above, this ticket is a 'large effort small reward' ticket. The team has decided to close this ticket.

**Comment by Iryna-Kaplun** [comment]
Based on Oamar's comment above, this ticket is a 'large effort small reward' ticket. The team has decided to close this ticket.
