### ISSUE TITLE
Update dashboard functionality

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3636]
**Describe the issue**
Dashboard functionality - not able to select and de-select viewable columns, not able to sort rows by select columns. 

**Rational/Why**

**Additional Context** 

**Dependencies**
- Backend work #3735
- Usability testing results will help us assign value of hide/view columns 

**Tests**

**Definition of done/Acceptance Criteria**

**Comment by faisal-hamood** [comment]
Hide/view columns is low value for general users. Usability testing to verify that hypothesis. Bumped to lower priority for now.

**Comment by Iryna-Kaplun** [comment]
Not relevant anymore. Can be closed.
