### ISSUE TITLE
Open links that leave the website (ie console links) should open in new tab

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3639]
**Describe the issue**
Open links that leave the website (ie console links) should open in new tab

**Rational/Why**
As a PO/TL, I want a new tab open when I click a link in the registry, so that I can continue to work in the registry without losing my page/position.   

**Additional Context** 
_Link to the code repositories
- List of technologies that may be expected to be known in order to work on the task
- Clear description of where the code change is going, e.g "add the text input to the create request form in components/request.js"
- Clearly identify which products are being updated ("Platform Services Registry")_

**Dependencies**

**Tests**

**Definition of done/Acceptance Criteria**
- When I click on links that leave the main page (e.g. external links: PO website, OCP, etc...), then I want that page to open in a new tab.

**Comment by lukegonis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/BCDevOps/developer-experience/3639?planning-poker) with Zenhub @okanji @alexandralloyd @funtigr @faisal-hamood
