### ISSUE TITLE
Request doesn't move to product section after approval for PO users

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3640]
**Describe the issue**
From PO perspective: After approval, requests stay in Request section and not product section. You need to refresh the page in order to see your request move to the Product section

**Rational/Why**
Why should this work be done? 'As a, I want, So I can' can be helpful.

**Additional Context** 
_- Link to the code repositories
- List of technologies that may be expected to be known in order to work on the task
- Clear description of where the code change is going, e.g "add the text input to the create request form in components/request.js"
- Clearly identify which products are being updated ("Platform Services Registry")_

**Dependencies**
- Internal, external, who to talk to if more information is needed

**Tests**

**Definition of done/Acceptance Criteria**
When my project is provisioned, I want it to show up in the Products tab and not in the Requests tab.

**Comment by lukegonis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/BCDevOps/developer-experience/3640?planning-poker) with Zenhub @alexandralloyd @funtigr @okanji @Kolezhanchik

**Comment by faisal-hamood** [comment]
Not an issue. Verified by Artem during refinement. 
@Iryna-Kaplun please delete this issue.
