### ISSUE TITLE
In Successful Quota Change email the Quota information has the previous parameters instead of new ones

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3642]
**Describe the issue**
In Successful Quota Change email the Quota information has the previous parameters instead of new ones

**Rational/Why**
Why should this work be done? 'As a, I want, So I can' can be helpful.

**Additional Context** 
- Link to the code repositories
- List of technologies that may be expected to be known in order to work on the task
- Clear description of where the code change is going, e.g "add the text input to the create request form in components/request.js"
- Clearly identify which products are being updated ("Platform Services Registry")

**Dependencies**
- Internal, external, who to talk to if more information is needed

**Tests**

**Definition of done/Acceptance Criteria**
- Clear description of the intended final result
- Acceptance criteria that describes the action a User Acceptance Tester would be trying to see if the work is complete

**Comment by funtigr** [comment]
The new quotas are shown in Quota Change Successful email now:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/ea53dd16-208b-43b6-a38f-45157eda4dbf)
