### ISSUE TITLE
Get Sal setup on console.redhat.com

### ISSUE THREAD

**Issue by faisal-hamood** [BCDevOps/developer-experience#3671]
**Describe the issue**
As a Product Owner for the private cloud services, I want access to usage and cost of the current customers/users of the platform, so that I can report to stakeholders, customers, and the team the value and budget needed. 

Justin Hewit was mentioning "cost management" in console.redhat.com to view usage and cost of our private cloud. This is a project he started but did not complete. Sal is taking it on, and needs access and a quick tour of the tool and the existing calculations. Please do some research, set up access, and book a meeting to discuss/take a tour of the tool. 

**Definition of done**
1. Sal has access to console.redhat.com and is able to view all clusters and projects/namespaces.
2. Sal has an understanding of the existing cost structure in "cost management" 
3. Emerald, Gold, Silver, and Public tiers are in the system and are measuring "cost"/usage

**Comment by StevenBarre** [comment]
Sent Sal an account invite.

**Comment by StevenBarre** [comment]
Meeting booked for Mar 31 with Justin and Olena to discuss

**Comment by StevenBarre** [comment]
Meeting moved to Apr 13th

**Comment by StevenBarre** [comment]
Done
