### ISSUE TITLE
Revert Openshift DNS resolver configurations on all managed clusters

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3672]
**Describe the issue**
Earlier this year Platform Operations ran across an issue with Operating System upgrades where IPV6 DNS queries did not return an expected response, thus causing increased overhead with cluster-based DNS queries, or for some users using images based on specific resolver libraries, actual breakage due to the changes.

To work around this as this initial changes affected primary name servers only, Platform Operations pushed out a number of emergency and high priority changes to make all managed Openshift clusters use solely the un-upgraded DNS servers which were solely secondary  and not primary. 

A recent new upgrade was performed to also upgrade the DNS servers we moved to for our resolving services, and due to the RFC having both down at the same time, this disrupted our Openshift clusters' ability to resolve DNS for a short period.

Now that the original issue with the OS upgrade is now addressed and all involved DNS servers also upgraded, we need to roll back the DNS resolver configuration to their original configuration which will make proper use of the primary and secondary DNS servers in each data centre.

**Additional context**
Incident ticket reference: MySC: INC0569392 / AS: INC0077513

**How does this benefit the users of our platform?**
Updating the configuration improves resiliency regarding each clusters' ability to resolve DNS entries when needed.

**Definition of done**
- [x] Re-test in all LAB environments.
- [x] Create documentation using RFC Methodology as the basis.
- [x] Create all required RFCs and top-level comms for alerts channel. Promote all for review/approval.
- [x] Execute RFC for SILVER (proposed for March 27th)
- [x] Execute RFC for GOLD (proposed for March 28th)
- [x] Execute RFC for GOLDDR (proposed for March 29th)
- [x] Execute RFC for EMERALD (proposed for March 30th)

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/advsol-docs/pull/264 opened for review. Once reviewed/approved, will merge and thus fulfill the documentation aspect of this ticket.

**Comment by StevenBarre** [comment]
CHG0046919 completed for Silver

**Comment by wmhutchison** [comment]
CHG0046922 completed for GOLD cluster.

**Comment by wmhutchison** [comment]
RFCs for GOLDDR and EMERALD now executed as well. Unblocking and closing this ticket.
