### ISSUE TITLE
Plan for preventing CronJobs from running too often

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3689]
**Describe the issue**
CronJobs that run more often than every 5 minutes impacts the performance of the k8s API and the cluster.

**What is the Value/Impact?**
Improved cluster performance and stability

**What is the plan? How will this get completed?**
- Discuss with stakeholders - this will be a big change and impact a lot of teams that are currently doing this
- Decide if we will proceed
- Test Kyverno policy in a LAB
- Announce via a Community Meetup and email blast

**Identify any dependencies**
Need input form Product Owner, maybe some of the most impacted teams, and @jleach 

**Definition of done**
- Planned implementation date selected
- Announcements made

**Comment by StevenBarre** [comment]
Get license plates with fast crons
```
oc get cj -A | grep -P '  \*(\/[1-4])?\s' | cut -f 1 -d' ' | cut -f1 -d'-' | sort -u
```

Drafted email and sent to Sal/Olena for review

**Comment by StevenBarre** [comment]
Email sent to 15 teams requesting feedback

**Comment by StevenBarre** [comment]
Gold / DR abb712 no reply, sent a follow up
Gold DR c8d6f2 no reply, sent a follow up
Silver f2b77c no reply, sent a follow up
950003 responded they would work on it ASAP
0fad32 09269b 9212c9 c53ff1 end of May

Other namespaces no longer have cronjobs that would be impacted.

**Comment by StevenBarre** [comment]
Gold / DR abb712 replied they would look into it
Gold DR c8d6f2 no reply, sent a follow up
Silver f2b77c replied they will need some time, but no definitive dates

**Comment by jleach** [comment]
@StevenBarre What about using the Kyverno policy I wrote? Can we bring up rolling it out with the team?

**Comment by StevenBarre** [comment]
Sending notices that we plan to do this May 29th or 30th

Silver
0fad32 09269b 9212c9 c53ff1 notified
f2b77c notified
950003 notified

Gold - none detected

Gold DR
c8d6f2 notified

**Comment by StevenBarre** [comment]
`oc get cj -A | grep -P 'TZ=' | cut -f 1 -d' ' | cut -f1 -d'-' | sort -u` to find cronjob using TZ. Sent them an email about the upcoming change and that 4.12 will support `spec.timeZone` instead.
