### ISSUE TITLE
Investige vROPs as a long term metric store

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3694]
**Describe the issue**
Investigate the feasibility of using vROPs as a long term metric store instead of Nagios. This will help us make graphs showing cluster capacity over long time frames like a year and produce better reports.

**What is the Value/Impact?**
Improved capacity planning and longer term storage of performance metrics.  Will also be able to provide dashboards to the team for viewing, where this is something that cannot be achieved with the existing solution.

**What is the plan? How will this get completed?**

- [x] - Install vROPS management pack for kubernetes **- _complete.  Installed most up to date version for the down rev'd version of vROPS that we are running.  Will upgrade to latest when we upgrade vROPS to latest._**
- [x] - Request any new firewall rules to KLAB2 _**- complete**_
- [ ] - Review required permissions and role based access or service account access and implement in KLAB2 _**- need to schedule meeting with Steven once firewall rules are in..scheduled for tomorrow night - May 4th (be with you.).**_
- [ ] - Review OOTB dashboards and investigate options for sending custom metrics

**Identify any dependencies**

- Hosting instance of vROPS.
- Lab OpenShift cluster ( KLAB2)

**Definition of done**
Team review of solution and decision on value, data being presented and forward looking capabilities for long term storage of metrics and properties from the clusters.
If we agree that this is the place, extend solution to include all other lab and production openshift clusters.

**Comment by DanDeane** [comment]
looking to park this until we get vROPs upgraded and or reviewed to see if it will be a proper long term metric store as we are considering different options due to our inability to upgrade vROPs due to the ep-ops dependency.
