### ISSUE TITLE
For Gold projects, it should receive two callbacks from both Gold and GoldDR then mark as provisioned

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#3732]
**Describe the issue**
As a user, I want a status for both Gold and GoldDR, so that I can troubleshoot or follow-up if one of my namespaces fails. 

**Rational/Why**

**Additional Context** 

**Dependencies**

**Tests**

**Definition of done/Acceptance Criteria**
When a user provision a project with Gold, I want Gold and GoldDR's provisions to be presented in the UI. Both Gold and GoldDR should have the same license plate. GoldDR projects should not be editable. Add a label that they can only be edited with Gold.

**Comment by Iryna-Kaplun** [comment]
This ticket is duplicated on the registry repo #1008. This ticket will be closed and #1008 will be the main ticket for this work.
