### ISSUE TITLE
Natural Sort Order By Name Sorting/Ability to Sort by Name

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#3735]
**Describe the issue**
Natural Sort Order By Name Sorting. Ability to be able to sort by name, and particular if it could be a natural sorting to see 'OpenShift 201 Test Project 2' appear after 'OpenShift 201 Test Project 1' rather than.. 'OpenShift 201 Test Project 1' followed by 'OpenShift 201 Test Project 10'

**Rational/Why**

**Additional Context** 
 
**Dependencies**

**Tests**

**Definition of done/Acceptance Criteria**
When I sort a column, I want a natural sort by text to be ascending/descending alphabetically and numerically. 
Desirable order: Ministry/ Cluster/ Product Title
The sort order should be case in insensitive (capital and small letters are sorted alphabetically regardless of the letter case).

**Comment by funtigr** [comment]
The same names with 10 and 100 are still before the same names with 2 (on TEST env):
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/3c869c92-873f-4ad9-8457-730de461513a)

**Comment by funtigr** [comment]
For now sorting works only for the Name column so sorting is not impacted by any other columns.

I made a new ticket out of above comment: [#3893 ](url)
