### ISSUE TITLE
Ability to adjust the number of results per page

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#3736]
**Describe the issue**

**Rational/Why**

**Additional Context** 

**Dependencies**

**Tests**

**Definition of done/Acceptance Criteria**
When I open the products and requests page, I want an option to display 10, 25, 50, and 100 results on the page.

**Comment by funtigr** [comment]
Changing number of items shown on the page works on both **_Products_** and **_Requests_** tab for usual **_Users_** and on **_Products_** and **_Active Requests_** tab for **_Admin_**.

The items are not duplicated between pages. 
The items are not getting lost. 

Checked on three browsers: **_Chrome_**, **_Firefox_**, **_Safari_**. 

**Concern**: When any **_Filter_** or **_Search_** gets in action the set of number drops back to default 10.

**_Requests_** and **_Active Requests_** tabs show items by last edited and on **_Products_** tab in alphabetic order.

**Comment by funtigr** [comment]
Concern is fixed.
Now when any Filter or Search or any of them together get in action the set of number remains the same.
