### ISSUE TITLE
Forward Proxy request

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3773]
**Describe the issue**
Per https://chat.developer.gov.bc.ca/channel/devops-operations?msg=Kw4nM6kYcLtnbxAsc

Add the Canada Post API endpoint to the allow list

**What is the Value/Impact?**
Allow app to do address validation

**What is the plan? How will this get completed?**
Have Luke submit an iStore order

**Identify any dependencies**
Luke

**Definition of done**
- FP access list updated
- Respond to user in above chat thread

**Comment by StevenBarre** [comment]
Form filled out and sent to Luke

**Comment by wmhutchison** [comment]
Per Luke's morning status posting in RC today, sounds like Luke now has to place such orders through MySC instead of iStore. Very doubtful actual implementation of this will take place this week when Steven's away. We'll see.

**Comment by wmhutchison** [comment]
This request has made it past the new MySC submission process. Earlier this morning an internal email has been sent to proceed to the next phase of this request, which involves getting an approval request from the OCIO NWSecurity team to review/approve the URL request, and another ticket for DXC Network to start work on the actual addition of the new URL. 

Will update here when approval has been submitted and a formal RFC change confirmed with a date for actual changes.

**Comment by StevenBarre** [comment]
Scheduled for the morning of Thur Apr 20th

**Comment by StevenBarre** [comment]
User notified
