### ISSUE TITLE
Update provisoner Secret

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#3784]
**Describe the issue**
https://console.apps.silver.devops.gov.bc.ca/k8s/ns/platform-provisioner-tools/secrets/registry-sso-prod

This information need tobe updated, as we already start using new keycloack instance. I noticed that SYNC and SYNC-pending is still using this info.

@okanji and @IanKWatts  I know that you guys are recently work on this, please feel free to update any info that I am not aware about this issue.
**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by IanKWatts** [comment]
- The SSO client has been created in the new SSO realm
- Team vault account updated with new info
- registry-sso-prod Secret updated

**Comment by IanKWatts** [comment]
registry-sso-test and registry-sso-dev also updated accordingly
