### ISSUE TITLE
SDN - Documentation - Improve documentation regarding netpol for shared resources on regular Openshift

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3789]
**Describe the issue**
Existing documentation needs to be clarified further regarding common resources (SSO, Artifactory) in terms of how to properly set up their networkpolicy regarding both Ingress and Egress rules. It may be relatively clear to allow access from EMERALD to the incoming VIP for a service like Artifactory, but it's not equally clear to allow back traffic on the outbound SNAT IP addresses belonging to the cluster(s) involved. 

**Additional context**
[Link to document needing updating.](https://cloud.gov.bc.ca/private-cloud/guide-for-emerald-teams/)

**How does this benefit the users of our platform?**
Improved documentation improves ability for new users on EMERALD to better make use of shared services.

**Definition of done**
- [ ] Draft out in Notepad proposed changes to document.
- [ ] Apply updates in Wordpress.

**Comment by StevenBarre** [comment]
Can you explain this a bit more to me when you are back? I'm not sure how/when the SNAT addresses would be needed in a netpol?

**Comment by wmhutchison** [comment]
My brain was mostly defaulting to being thorough/complete due to the nature of NSX of "default deny, specify everything else". Based on our your response, we're then allowing all outbound traffic from the various clusters to NSX clusters without netpol? If so, then indeed we can waive the need to allow outbound SNAT IPs from the likes of SILVER./GOLD/GOLDDR back to EMERALD/KLAB2.

The main gist of this ticket though is to ensure folks who need access to shared services like SSO/Artifactory and so on hosted on non-NSX clusters have an easy way of noting the required netpol since regular folks shouldn't otherwise need to be fully aware of the deeper technical aspects of what's involved in a shared service like SSO or Artifactory. 

Or perhaps we should just bake-in netpol involving shared services into the default-deny netpol in similar fashion to what we do with the likes of DNS or internal registry?

Happy to discuss further. :)

**Comment by StevenBarre** [comment]
No longer required
