### ISSUE TITLE
SDN - New Forward Proxy Request involving fastly.net

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3791]
**Describe the issue**
Fulfill Abin Antony's request to have *.fastly.net added to the forward proxy. It is the CDN for the Debian packages thus any container builds involving Debian will need this opened up.

**Additional context**
[Link to Rocket Chat thread involving request.](https://chat.developer.gov.bc.ca/channel/nsx-early-adopters?msg=y9kqTbE3wN86nRGMZ)

**How does this benefit the users of our platform?**
Ongoing addition of required URLs satisfies both the needs of the user in question as well as future users who may need to source Debian packages in similar fashion.

**Definition of done**
- [x] Create new copy of Forward Request form with additions to the document.
- [x] Submit copy of document via email to Luke.
- [x] Wait for follow-up from Network stakeholders regarding fulfillment of request. Test via curl to confirm.
- [x] Notify user regarding completion of addition.

**Comment by lukegonis** [comment]
The request has been submitted and will be fulfilled via iStore, the  iStore # is 1134527

**Comment by StevenBarre** [comment]
Scheduled for the morning of Thur Apr 20th

**Comment by StevenBarre** [comment]
Users notified
