### ISSUE TITLE
PUT - finalize status page on uptime.com

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3814]
**Describe the issue**
To show the PUT status on a page via uptime.com. This is a first-try ticket for Artem and Billy to pick up uptime.com service as service lead!

**Definition of done**
- [x] create check components
- [x] improve status page: create groups and add all PUT components. Better naming for the page.

**Comment by w8896699** [comment]
Hi @ShellyXueHan, can you specify what exactly the improvement you want to be done for status page

**Comment by w8896699** [comment]
Created couple checks (for mongo, registry and cruncy) for practicing and testing.

All n8n test is now under PUT tag: https://uptime.com/devices/services?tags=PUT

Updated list of services checks in here: https://uptime.com/statuspage/platform-service-sli-page
