### ISSUE TITLE
Repo-mountie KT

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3824]
**Describe the issue**
This is for Helen and Monica to learn about repo-mountie.

**Definition of done**
- [x] KT meeting from Jason
- [x] planning for upcoming tasks to work on for repo-mountie

Tasks to be done later on:
- Update dependencies
- Fix bug with event trigger
- improve build process

**Comment by ShellyXueHan** [comment]
@MonicaG @blueQcloud this one has been here for a long while. I wonder if the knowledge transfer is completed yet? I've moved some action items to be tasks for the future and keep it simple for this one to be pure KT. So if things are all good, please close this ticket. If not, please comment with what needs to be done and I can help to arrange. Thank you!

**Comment by MonicaG** [comment]
Yes, the knowledge transfer is done. The action items to update/improve it should be in other tickets. I've created tickets in our jira backlog.

**Comment by ShellyXueHan** [comment]
thank you Monica!
