### ISSUE TITLE
Registry Retro

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#3847]
**What Happened**
-
- Preparing for a Digital Demos presentation, Oamar wanted to clean up a bunch of the test projects and deleted a bunch of them. By mistake, he deleted the registry's project. The four registry namespaces were deleted as a result. This happened around 9:50.
- Ian found the workflow action that had deleted them, changed the "delete" action to the "create" action and manually submitted the task to NATS, which recreated all the namespaces with the same license-plate.
- The gitops repo was still present, because deleting a project set doesn't delete that. So recreating the ArgoCD project meant that they could reconnect to the gitops repo, which contained a lot of the infrastructure configuration.
- The gitops repo did not contain anything in the tools namespace, and it was missing a couple of other things likes secrets and stuff. So that stuff had to be recreated manually.
- Next, Billy had to rebuild missing images from the tools namespace. Rebuilding was easy but took a long time to build all of them.
- A bunch of secrets were still in the old registry namespace, allowing the team to recover some of them. Oamar had some tokens locally and was able to use those to recover others. The main missing one was the database secret. The DB secret wasn't recovered and new passwords were generated. 
- The name of the backup PV wasn't saved, so the team was not able to recover the backup files.
- Both of these prevented the team from being able to recover the database from a backup.
- Instead, the team scraped the data from the cluster, since all the namespaces have annotations and labels that contain all the information within the registry.
- With that info, Oamar was able to generate an SQL statement to refill all the data the registry was supposed to have on the current state of all projects. Outstanding quota change requests were unable to be recovered. Oamar was also able to recreate all the registry users through a combination of the contact info annotations on projects, and from an old copy of the registry database. This was completed around 5:30.
- The user list is supposed to have the first and last name of each user. Not all of them were imported during the original user recreation task. The app threw an error if first or last name was null. Oamar changed it so this wouldn't throw an error, and then also manually fixed the issue by adding the missing first and last names.
- Around the same time, the team was trying to push fixes into production, but this involves promoting from test, and a test build didn't actually exist, causing some errors. So the team also had to manually tag some images.
- At this point, the registry was fixed and available, but the vanity URL was inaccessible due to a missing cert.
- Billy then recreated the certbot to send another cert request. Because this happened after EOD, they didn't approve it until morning.
- Once the approval was in place early the next morning, certbot picked up and everything was fixed.

**What Could Have Prevented This Outage In the First Place?**
-
- The old registry had a pre-deletion check where, if a namespace had any pods or PVs in it, the registry refused to deleted it. This should be added to the new registry - it was already in progress, but Oamar hadn't finished it yet. 
   - Oamar has turned off project deletion entirely until this functionality has been re-added
   - Re-implementing this functionality is a high priority.
   - When deleting your namespace in the registry, you have to type in the namespace name to make sure the user is deleting the right namespace.
- The name of the registry project set was actually "Registry Test" so, while deleting various test projects, Oamar thought this was a test project set when it was actually the real, live production registry.
    - Let's go through our project sets in the registry to make sure that they are labeled correctly to prevent this sort of mistake in the future.
    - Test against a namespace that uses a HPA because Billy said it caused him issues.
- We could add a label or other marker to project sets that have the potential to broadly impact the functionality of many applications (aka the various services that we run), like SYS or something.
    - Maybe let's also have a label to clearly mark projects that we're using for test purposes as well? Because we need to do some testing in the production registry in order to test integration with the provisioner, so it would be good to clearly mark those that are only there for testing purposes. The word "test" in the name isn't sufficient to ensure that it's actually a throw-away test project.

**How Could We Have Made It Easier to Recover?**
- 
- Let's push images to Artifactory so it's not necessary to rebuild them in the event of them getting deleted. While it's possible to rebuild pretty easily, it takes too long! Part of the reason why it takes so long is that the build pod needs like 2G of RAM which is crazy so what's up with that?
- Add missing objects to the gitops repo. 
- Record and backup the name of the PV (not the PVC), all secrets including the TLS cert. Secrets should probably be backed up to Vault. 
   - find out from steven why he couldn't recover the PV. Is this a problem that we should be worried about in general?
- Create a doc that covers all the steps for recovery and put it in the gitops repo
- A bunch of objects were in a bunch of different places and Billy had to go find them so let's try to put everything in the same place (gitops repo)
- Since we didn't actually test the DB backup recovery yesterday, we should run through that whole process in test before we need it again.
    - Let's also consider moving from nfs-file-backup to S3 for backups.
- Switch from S2I to Dockerfile for guaranteed consistency in rebuilt images.

**Other Notes**
-
- Ian has a list of the objects that are required in the namespace but that aren't saved as IAC in the gitops repo.

**Take Aways and Next Steps**
- 
Make a ticket for:
- all of our services to backup all secrets for those services to make sure recovery is possible.
- to check all our namespaces in the registry to make sure they have clear names
- sys and test labels in the registry (Oamar)
- add the missing objects and all the tools stuff to the gitops repo (Ian/Artem)
- push images to artifactory (Billy)
- investigate the PV recovery issue with Steven (Cailey)
- test the full DB recovery process (Oamar)
- investigate copy from nfs-file-backup to S3 for DB backups (Oamar/Ian)
- switch from S2I to Dockerfile (Zhanna/Billy)

**Comment by caggles** [comment]
@mitovskaol @faisal-hamood  here are our notes and takeaways from the registry outage!

**Comment by mitovskaol** [comment]
Thank you very much for the detailed analysis of the outage @caggles , it was very helpful ! @Iryna-Kaplun can you please work with the team to create the tickets that are mentioned above and we will prioritize them for the next Sprint. I need Oamar to unblock the public cloud team with their provisioner integration, but maybe Zhanna and Artem can work on these "operational" tickets?

**Comment by caggles** [comment]
I'd already made about half of the tickets, just FYI, so @Iryna-Kaplun you might wanna check in and make sure some people didn't end up with duplicates!
