### ISSUE TITLE
Make sure all our important secrets are backed up

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#3848]
**Describe the issue**
Check all the Openshift secrets for all our services, and make sure the secrets are backed up somewhere. Vault is a good spot, unless the service in question IS Vault, in which case maybe Azure. But really, just as long as they're SOMEWHERE (and preferably that somewhere isn't your laptop, please).

**How does this benefit the users of our platform?**
Improved resiliency!

**Definition of done**
The primary or secondary resource for each service should check it off once they have either saved all the important secrets for the service (including TLS certs, licenses and/or any shared external accounts like Zoom accounts!!) somewhere safe and accessible to the team. 
- [X] Artifactory
- [x] Vault
- [x] Sysdig
- [x] ACS
- [x] Uptime.com
- [x] ArgoCD shared instances
- [x] CCM
- [X] CrunchyDB and EnterpriseDB Operators
- [x] Benny, Porter and Warden Operators
- [x] Tekton Operator
- [x] Certbot
- [x] Private Cloud Website
- [x] Technical Doc Website
- [x] Openshift 101 and 201
- [x] Registry
- [x] Provisioner, Policybot and Bulldozer
- [x] Mautic
- [x] Repomountie
- [x] Rocketchat and Hubot
- [x] Just Ask
- [X] DockerHub shared accounts
- [x] RedHat shared accounts
- [x] Zoom shared accounts
- [x] Google Team shared accounts

https://docs.google.com/spreadsheets/d/1pvaxCdYts1MeRv7bHP10a1yt_MGk6KpK/edit#gid=755033945

**Comment by w8896699** [comment]
Just ask: https://vault.developer.gov.bc.ca/ui/vault/secrets/platteam-prod/show/just-ask-prod?namespace=platform-services

**Comment by mtspn** [comment]
Meeting scheduled with Tyler & Zhanna for Friday May 26th to discuss any secrets or related information for the Tech Docs site.

**Comment by mtspn** [comment]
I don't think we're quite ready to close this one, I'm going to meet with Tyler and Cailey Friday to discuss any secrets needed for the Tech Docs site.

**Comment by caggles** [comment]
Based on the conversation with Tyler, I have saved the outstanding secrets from the tech docs site. Closing!
