### ISSUE TITLE
Test and document how to restore objects from ETCD backup

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3851]
**Describe the issue**
From time to time we may need to get some info from a K8S object that has been deleted. We back up ETCD daily and can in theory recover or at least read individual objects from that.

**What is the Value/Impact?**
Be able to get back lost secrets, or find the PV for a backup PVC that has been deleted.

**What is the plan? How will this get completed?**
Get the basics from our RH TAM and develop a local procedure to restore the ETCD backup and then extract objects from it. Document the process.

**Identify any dependencies**
RH TAM

**Definition of done**
Document in https://github.com/bcgov-c/advsol-docs

**Comment by tmorik** [comment]
RH Case opened: Case #03510951

**Comment by tmorik** [comment]
Evaluating the steps and making a document.

**Comment by tmorik** [comment]
Steps summary:

ECTD is backed up by a backup cron job in the `openshift-bcgov-etcd-backup` namespace. To retrieve the backed up data from it, you have to run three steps;

1. Spin up a temporary pod with the backup PVC, and download it to a local drive (util server).
2. Create a CENTOS container, download ETCD to it, and restore ETCD snapshot.
3. Start etcd in CENTOS container and Explore keys in the restored ETCD using `etcdctl`.

**Comment by tmorik** [comment]
Documenting PR has been tested and merged.
