### ISSUE TITLE
Create the public cloud API

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3857]
**Describe the issue**
The public cloud team has built a public cloud provisioner, and the registry API will need to be able to handle the provisioning of public cloud projects

**Additional Context** 
A public cloud project will follow a similar lifecycle to a private cloud project. With the exception that:
- There is no delete feature
- All edit requests are automatically approved

**Definition of done/Acceptance Criteria**
- Create API endpoints that will enable the Creation, approval, and edit of a private cloud project

**Comment by okanji** [comment]
I have met with @crochcunill from the public cloud team to walk him through the API, show him the documentation, and hand over the public cloud API for testing. The public cloud API has been deployed to our dev branch and is in review with a pull request for Zhanna. I was to meet with Zhanna to go over all the changes I made so can review the work but was not able to find time this sprint. I will find time to meet with her soon.

## Documentation: https://github.com/bcgov/platform-services-registry-api

I have created supporting documentation for each public cloud endpoint where I describe the flow of the entire API (from create to approve to provision to edit..). I define the inputs for each endpoint and give a javacript example on how to invoke the endpoint. Here is an example: ![image.png](https://images.zenhubusercontent.com/5ea9ab5d1ac2ef7f9a589259/21f0a97d-74b5-4a00-bf72-68c98200a6da)
