### ISSUE TITLE
Decom and upgrade 4 GOLDDR APP nodes

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3882]
**Describe the issue**
Update GOLDDR APP nodes with new servers and make the new nodes live.

**Additional context**
Decom tickets
RITM0144992 mcs-golddr-app-02
RITM0144993 mcs-golddr-app-03
RITM0144994 mcs-golddr-app-04
RITM0144995 mcs-golddr-app-05

Build tickets:
RITM0145679 line #1 - replacing MCS-GOLDDR-APP-03.DMZ - SCTASK0301864 - MCS-GOLDDR-APP-11.DMZ replacement for existing server MCS-GOLDDR-APP-03.DMZ 
RITM0145680 line #2 - replacing MCS-GOLDDR-APP-04.DMZ - SCTASK0301866 - MCS-GOLDDR-APP-12.DMZ Replacement for existing server MCS-GOLDDR-APP-04.DMZ 
RITM0145681 line #3 - replacing MCS-GOLDDR-APP-04.DMZ - SCTASK0301825 - MCS-GOLDDR-APP-13.DMZ Replacement for existing server MCS-GOLDDR-APP-04.DMZ
RITM0145682 line #4 - replacing MCS-GOLDDR-APP-03.DMZ - SCTASK0301863 - MCS-GOLDDR-APP-10.DMZ Replacement for existing server MCS-GOLDDR-APP-03.DMZ 
RITM0145683 line #5 - replacing MCS-GOLDDR-APP-05.DMZ - SCTASK0301867 - MCS-GOLDDR-APP-14.DMZ Replacement for existing server MCS-GOLDDR-APP-05.DMZ 
RITM0145684 line #6 - replacing MCS-GOLDDR-APP-02.DMZ - SCTASK0301854 - MCS-GOLDDR-APP-08.DMZ Replacement for existing server MCS-GOLDDR-APP-02.DMZ 
RITM0145685 line #7 - replacing MCS-GOLDDR-APP-05.DMZ - SCTASK0301868 - MCS-GOLDDR-APP-15.DMZ Replacement for existing server MCS-GOLDDR-APP-05.DMZ 
RITM0145686 line #8 - replacing MCS-GOLDDR-APP-02.DMZ - SCTASK0301862 - MCS-GOLDDR-APP-09.DMZ Replacement for existing server MCS-GOLDDR-APP-02.DMZ 

**How does this benefit the users of our platform?**
Replacing old hardware with virtualized hardware will improve reliability and reduce the likelihood of hardware failure.

**Definition of done**

- [x] Servers decommissioned
- [x] Servers built
- [x] Servers tested
- [x] Servers active in the GOLDDR cluster

**Comment by tbaker1313** [comment]
rhcos-ignition-builder inventory updated with IP info and MAC addresses. Should be ready to proceed.

**Comment by tbaker1313** [comment]
Tested dhcp network connectivity and verified inventory is correct.

**Comment by tbaker1313** [comment]
Created CHG0048740 to implement this.

**Comment by StevenBarre** [comment]
Completed and all tickets closed
