### ISSUE TITLE
Entering Non-Valid Email or Email with Exceeding Space in the Registry User Field

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#3899]
**Describe the issue**

**Rational/Why**

**Additional Context** 

**Dependencies**

**Tests**

**Definition of done/Acceptance Criteria**
If non-valid email or an email with exceeding space is entered in the user's field, there should be an error message notifying why this is incorrect.

**Comment by Iryna-Kaplun** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Experience-5bb7c5ab4b5806bc2beb9d15/issues/BCDevOps/developer-experience/3899?planning-poker) with Zenhub @alexandralloyd @funtigr @Kolezhanchik @okanji

**Comment by funtigr** [comment]
If I paste an e-mail instead of manual input it is not being looked up in the IDIR emails.
Video demo:
https://drive.google.com/file/d/1iiF4oI0CqdoeInT1o89ZSqPNmB2rrs7L/view?usp=sharing

**Comment by funtigr** [comment]
Testing was made on Test env.
Now pasting e-mail address without spaces gives a tooltip with an e-mail. If you click it name, last name and ministry is populated. 
If I paste an e-mail address with a trailing space or several spaces it gets removed automatically and tooltip is shown.
If I paste an existing e-mail address with random uppercase letters the address is recognized and tooltip is shown.
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/dba21586-9344-48bc-be58-0c38bb3c2538)
If I use non-linked to IDIR but valid e-mail (artem@gmail.com) a message about non-linked to IDIR is shown:
![image.png](https://images.zenhubusercontent.com/63fe8ab5f6435681bfb7de0a/c5d936dc-6629-4605-b807-1ffbf88fb021)
