### ISSUE TITLE
DRP review with Platform Admin team and DXC

### ISSUE THREAD

**Issue by AvneetKahlon** [BCDevOps/developer-experience#3909]
**Describe the issue**
Disaster Recovery Plan (DRP) has been drafted. Need to be reviewed by the technical team to make sure the document covers all the aspects of disaster recovery if there is unexpected disruption. 

**Additional context**
Add any other context, attachments or screenshots
A disaster recovery (DR) plan is a formal document created by an organization that contains detailed instructions on how to respond to unplanned incidents such as natural disasters, power outages, cyber attacks and any other disruptive events.

**Definition of done**

- [x] Review drafted DRP with Platform Admin team (Cailey and Shelly)
- [x] Review DRP with DXC team (Steven)
- [x] Make sure to add all the information required by the team to recover in event of incident.

**Comment by NickCorcoran** [comment]
Has been reviewed with Cailey.  Just Shelly left to review with.
