### ISSUE TITLE
Test Server-Side Apply in CLAB's ArgoCD instance

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#3921]
**Describe the issue**
We have had to remove Crunchy from CCM because the CRDs couldn't be updated because they're too large - we need to be able to apply it with the server-side apply option. The Argo operator didn't offer that option until recently. Now that it's installed in CLAB, we should test to see if it works again!

**How does this benefit the users of our platform?**
Updates to Crunchy will take much less time again! Yay!

**Definition of done**
- [x] Try updating Crunchy via CCM
- [x] If it works, create a plan for turning Crunchy back on in CCM.

**Comment by caggles** [comment]
This will proceed as soon as there's an updated version of CrunchyDB operator to test - our last upgrade took us to the most recent version, so we need them to release a new update to test in CCM.

**Comment by StevenBarre** [comment]
Couldn't we just re-enable the argocd app to sync with the current CRD?

**Comment by caggles** [comment]
All done! Tested in both KLAB and CLAB, everything looks good to proceed and I'm opening a PR to turn Crunchy syncing back on in CCM as we speak :)
