### ISSUE TITLE
Develop a new on call incident checklist

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3922]
**Describe the issue**
When called out for an INC after hours (or during hours) there's several things that should be done. Make a checklist to help the ops person ensure steps aren't missed

**What is the Value/Impact?**
Improved INC response

**What is the plan? How will this get completed?**
Write a doc and get it reviewed by PR

**Identify any dependencies**
None

**Definition of done**
Merged doc

**Comment by StevenBarre** [comment]
- Post updates in RC
- Update status page

**Comment by StevenBarre** [comment]
Create a ZenHub issue template checklist https://github.com/BCDevOps/developer-experience/pull/3933
Docs on how to update the status page https://github.com/bcgov-c/advsol-docs/pull/273

**Comment by wmhutchison** [comment]
@StevenBarre This PR might need to be revisited, what caused the format change to labels? CCM template no longer shows up, copy/pasted from an older ticket to create my CCM ticket for this coming week.

**Comment by StevenBarre** [comment]
@wmhutchison fixed!
