### ISSUE TITLE
Refine Mautic Documentation and Improve Database Cleanup Process

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#3924]
**Describe the issue**
Currently, the debug script used for cleaning up the Mautic database is causing unintended consequences. When executed, it deletes entries from the leads table, resulting in the cancellation of contact lists in Mautic and preventing the recipients from receiving emails. We need to find a better approach to clean up the database without disrupting the functionality of contact lists and email delivery.

**Additional context**

1.  Review Existing Debug Script

- Analyze the current debug script responsible for cleaning up the Mautic database.
- Identify the specific code segment causing the deletion of entries from the leads table.

2 

- Explore alternative methods for cleaning up the Mautic database without disrupting contact lists.
- Investigate best practices and recommended approaches for database maintenance in Mautic.
- Develop a new script or refine the existing one to ensure safe and effective cleanup.

3 Testing and Validation

- Create a test environment to validate the new cleanup script.
- Perform thorough testing to ensure that contact lists remain intact and emails can be successfully delivered.
- Seek feedback from stakeholders and gather user acceptance.

4. Documentation Enhancement

- Update the Mautic documentation to provide clear instructions for database maintenance.
- Include information about the improved cleanup process and any necessary precautions.
- Document the steps to prevent disruptions to contact lists and email functionality.

**How does this benefit the users of our platform?**

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by ShellyXueHan** [comment]
documentation has been added, but not the database clean up script. @w8896699 please feel free to start a new ticket!
