### ISSUE TITLE
Vault - use S3 for DB backup

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#3941]
**Describe the issue**
better DB backup storage option.

**Definition of done**
- [x] investigate how to
- [x] update backup strategy
- [x] update DB backup and restore docs

**Comment by IanKWatts** [comment]
Updated docs are:
https://github.com/BC-Gov-PaaS-Platform-Services/platform-gitops-vault/blob/main/docs/VaultRaftSnapshot.md
https://github.com/BC-Gov-PaaS-Platform-Services/platform-gitops-vault/blob/main/docs/VaultRaftRestore.md
