### ISSUE TITLE
How to install the 'oc' command line tool (new page)

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#3943]
Create a new tech doc page focused on how to install oc and add it to PATH. Topics could include

**Install oc on a mac**
- Install homebrew
- Add homebrew to path
- Install openshift-cli (oc) 
- Consider video demo in the future here

**Install oc on windows**
- Install homebrew
- Add homebrew to path
- Install openshift-cli (oc) 
- Consider video demo in the future here

****

**Definition of done**

- [x] First draft
- [x] SME review
- [ ] Approval

**Comment by Pilargit12** [comment]
Pull request: https://github.com/bcgov/platform-developer-docs/pull/171

**Comment by Pilargit12** [comment]
Page now live at https://docs.developer.gov.bc.ca/install-the-oc-command-line-tool/ !
