### ISSUE TITLE
Namespace access for Ministry Ops teams

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#3945]
**Describe the issue**
Some ministries are now wanting their IT ops teams to help support their containerized apps.  This means initially having visibility to the Openshift console and Kibana, and later the ability to restart pods that have failed.

**How does this benefit the users of our platform?**
More eyes on Ministry focused apps.
Less issues for platform admins to take action on or search for team member to resolve.

**Definition of done**
- [x] Work with CITZ IMB as pilot group
- [x] Identify options for granting access to ALL Ministry apps for a group of users
- [x] Consider how new namespaces are given rolebindings for these users ^
- [x] Identify method to segregate platform admin namespaces from Ministry namespaces (specifically for CITZ)
- [x] Create script for initial user grants

**Comment by NickCorcoran** [comment]
Options:
- manual grants to users in individual namespaces (time consuming)
- script based grants for subset of Ministry (CITZ) namespaces (remove platform services/test ones)
- Argo CD user sync (would require setting up each project in Argo Shared space)
- Tremolo user group (future - likely ideal) - Avneet investigating

**Comment by NickCorcoran** [comment]
Options:
- manual grants to users in individual namespaces (time consuming)
- script based grants for subset of Ministry (CITZ) namespaces (remove platform services/test ones)
- Argo CD user sync (would require setting up each project in Argo Shared space)
- Tremolo user group (future - likely ideal) - Avneet investigating

**Comment by NickCorcoran** [comment]
ITOps team granted access to registry to view all CITZ assets.

**Comment by NickCorcoran** [comment]
ITOps team granted access to registry to view all CITZ assets.

**Comment by juhewitt** [comment]
thank you for taking this on!  happy to chat more about it with all parties for the thinking of SRE concepts between DevOps, ITOps, SecOps and more...

**Comment by NickCorcoran** [comment]
For new namespaces... script would need to be manually updated.

**Comment by NickCorcoran** [comment]
Split CITZ/Platform Services/testing
- Change Ministry Label?
- Add PS flag? (probably best solution)
- Manually based on PS PO/TL (probably initial solution)

**Comment by NickCorcoran** [comment]
Admin to run script.
Nick to look into Argo or Tremolo as longer term options for global citz access.
