### ISSUE TITLE
Investigate EDB operator upgrades

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#3955]
**Describe the issue**
Need to figure out why EDB operator doesn't upgrade in the expected way.

**Additional context**
RH Case #03521405

**How does this benefit the users of our platform?**
Need to upgrade to at least 1.18

**Definition of done**

- [x] EDB operator upgrade is successful

**Comment by caggles** [comment]
EDB's team made a mistake when submitting their recent updates to the various upgrade channels. They are submitting fixes, but we need to wait until those are made available through OLM before we can actually finish upgrading EDB to 1.18 and beyond.

**Comment by caggles** [comment]
This has been completed!
