### ISSUE TITLE
Edit request for Public Cloud webpage

### ISSUE THREAD

**Issue by Pilargit12** [BCDevOps/developer-experience#3957]
**Describe the issue**
Remove URLS not consistent with [Public Cloud webpage. ](https://cloud.gov.bc.ca/ ). 

Simplifying information provided in the site, by removing extra URL's and indicating a simpler way to reach the Public Cloud website services.

**Additional context**
![Screenshot 2023-05-25 at 12.45.12 PM.png](https://images.zenhubusercontent.com/64417a91d7b68b6a95ec4b1a/0037a1f2-e77d-45c3-b79b-424ce97094de)

The request came originally from Allieren Ward (Senior Content Design Lead) 

- Remove Cloud onboarding journey URL
- Remove our list of available AWS services URL 
- About the secure public cloud URL
- Adding a new link directing the visitors to: https://digital.gov.bc.ca/cloud/public/ 

**How does this benefit the users of our platform?**

The visitor will not be confused which link to click on to find more about the Public Cloud. It will direct them to the correct and updated URL. 

**Definition of done**
- [x] Correction of the above, edit will be done through the WordPress website and changes will be reflected when published. 
- [x] Inform Allieren Ward of published work for review.  
- [x] Inform Failsal Hammod of completed task

**Comment by mtspn** [comment]
Pilar does not have the necessary access to edit this page, requested same on platform services team channel.

**Comment by Pilargit12** [comment]
[x ] Correction of the above, edit will be done through the WordPress website and changes will be reflected when published.
[x ] Inform Allieren Ward of published work for review.
[x ] Inform Failsal Hammod of completed task
