### ISSUE TITLE
NSX - Set NCP to run in HA mode

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#3965]
**Describe the issue**
NCP supports running in HA mode, so that there are 2+ pods running to ensure if one node goes down changes to the network are still pushed to NSX.

Let's give it a test in KLAB2 and see if there's any issues

**What is the Value/Impact?**
Improved resiliency of NSX clusters

**What is the plan? How will this get completed?**
https://docs.vmware.com/en/VMware-NSX-Container-Plugin/4.0/ncp-kubernetes/GUID-2122160A-7B39-4F73-9ED3-6E1C2346E265.html

https://github.com/vmware/nsx-container-plugin-operator/blob/main/manifest/openshift4/coreos/ncp-openshift4.yaml#L494-L496

https://github.com/bcgov-c/rhcos-ignition-builder/pull/111/files

As part of the upgrade CHG, apply the change to set NCP to run 2 replicas

**Identify any dependencies**
None

**Definition of done**
Emerald NCP set to run with 2 replicas

**Comment by wmhutchison** [comment]
The required changes were successfully applied in EMERALD earlier this morning, monitored for a bit to ensure it's stable, and then kicked off EMERALD's OCP upgrade. First business day next week should be ample time to let this change to bake-in, given the amount of churn involved with OCP's node upgrades coupled with additional node drains for ESXi patching this week.
