### ISSUE TITLE
Custom Auto-scaling Operator KEDA not upgrading automatically anymore

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3976]
**Describe the issue**
A recent upgrade to the KEDA operator has transitioned this operator from Technical Preview to Generally Available. This change however broke the automated upgrade process, by virtue that the manifest content in CCM needed to change, and the old operator needed to be uninstalled first.

**Additional context**
This is only an issue for KEDA versions in OCP 4.11 and 4.12. It is not an issue with KEDA as installed in OCP 4.10 (KLAB2, EMERALD).

**How does this benefit the users of our platform?**
Ensure stable upgrades for operators providing shared services. The old operator still works/runs.

**Definition of done**
- [x] Troubleshoot with vendor support as needed (case opened).
- [x] Initial testing in KLAB by removing KEDA and re-applying CCM as-is.
- [x] More testing in KLAB by removing KEDA and manually installing to check its manifest and compare against CCM.
- [x] Test a PR against CCM KLAB repo for proposed fix.
- [x] Create a PR against main CCM repo for proposed fix against all clusters.
- [x] Test against CLAB and use as a means of documenting the precise uninstall steps to be used when handling this in next CCM release.
- [x] Confirm this issue has been addressed in all PROD clusters.

**Comment by StevenBarre** [comment]
Does deleting the CRDs require deleting any CRs in use? Will dev teams need to re-create any custom metric scalers they have set up?

**Comment by wmhutchison** [comment]
Removing the CRDs doesn't destroy any CR's, it'll be just that any attempts to "do something" with the CR's during that shortish period won't work since the API won't know how to handle it. The sole CR we delete is the first step (kedacontroller).

**Comment by wmhutchison** [comment]
also to that end, doesn't appear KEDA's being actively used in any of our clusters, production or otherwise.

**Comment by wmhutchison** [comment]
also to that end, doesn't appear KEDA's being actively used in any of our clusters, production or otherwise.

**Comment by StevenBarre** [comment]
> also to that end, doesn't appear KEDA's being actively used in any of our clusters, production or otherwise.

shockedpikachu.jpg

**Comment by wmhutchison** [comment]
QA complete, closing as completed.
