### ISSUE TITLE
Tremolo install in KLAB

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#3981]
**Describe the issue**
Tremolo uses OpenUnison to perform Kubernetes API calls and provides a variety of capabilities.  We wish to explore the use of the UI for authorization management for OpenShift users.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**
This may make it easier to manage user access for POs/TLs that manage more than 1 namespace.

**Definition of done**
- [x] Components to install identified
- [x] Operator/components installed (work w/ DXC team on this)
- [x] Verified as operational
- Another ticket will be created to configure/setup for performing authorizations

**Comment by AvneetKahlon** [comment]
Tremolo installed and operating.
