### ISSUE TITLE
DevOps Learning

### ISSUE THREAD

**Issue by calbertan** [BCDevOps/developer-experience#3986]
Learn DevOps concepts to prepare for working with Tekton

**Definition of Done**

- [x] learn CI/CD and the CI/CD pipeline

- [x] look into infrastructure as code and gitops/devops concepts

- [x] get familiar with Tekton

- [x] take on some Tekton issues

**How does this benefit our platform**
Christopher will be assigned Tekton related tasks

**Identify any dependencies**
Billy will act as the mentor/supervisor

**Comment by mtspn** [comment]
Just a reminder that the first OpenShift 201 exercises may help with your familiarization on this: https://github.com/BCDevOps/devops-platform-workshops/blob/master/openshift-201/pipelines.md
