### ISSUE TITLE
SDN - refresh AKO pod from v1.8 to v1.10

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#3991]
**Describe the issue**
Investigation reveals that the operator which integrates an NSX-based Openshift cluster with AVI (responsible for handling access to services/routes) has a newer version available. Apart from some general bugfixes, the new version affords us the ability to run the AKO pod in HA mode which is desired for a production environment. This ticket will track the effort spent testing, evaluating and implementing this change first in KLAB2 and then EMERALD.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**
Receiving latest bugfixes as well as addtional functionaly for HA support, which we greatly desire in a production environment.

**Definition of done**
- [x] Test implementation in KLAB2 by rendering out the manifests required for v1.10.
- [x] QA results in KLAB2 giving it some bake-in time (one week).
- [x] Implement change in EMERALD via suitable RFC. (CHG0050939 on August 6th)
- [x] QA results in EMERALD giving it some bake-in time (one week).

**Comment by wmhutchison** [comment]
Took a peek, AKO is now at 1.10.1 circa June 2023. 

https://avinetworks.com/docs/ako/1.10/ako-release-notes/

Also based on vendor notes, the helm repo URL changes after v1.9, and it's not yet in the Forward Proxy. Not a blocker since we can use a regular UTIL server to build out the new YAML, but will need to check over everything in the end and add a new request for Network with all applicable URLs.

**Comment by wmhutchison** [comment]
Took a peek, AKO is now at 1.10.1 circa June 2023. 

https://avinetworks.com/docs/ako/1.10/ako-release-notes/

Also based on vendor notes, the helm repo URL changes after v1.9, and it's not yet in the Forward Proxy. Not a blocker since we can use a regular UTIL server to build out the new YAML, but will need to check over everything in the end and add a new request for Network with all applicable URLs.

**Comment by wmhutchison** [comment]
PR created now: https://github.com/bcgov-c/platform-ops/pull/459

KLAB2 updated via ansible playbook. Giving it a full week at the very least for bake-in, and then push for an EMERALD RFC on a Sunday morning to make the same change.

**Comment by wmhutchison** [comment]
proceeding to create a suitable RFC and comms for implementing this in EMERALD during the Sunday morning change window on August 6th when Steven Barre is on-call. If issues in KLAB2 are detected between now and August 4th, the RFC might be deferred/cancelled.

**Comment by StevenBarre** [comment]
CHG0050939 completed

**Comment by wmhutchison** [comment]
Will close off this ticket next Tuesday (August 15th) - that will be a bit over one week since EMERALD had its AKO upgraded.

**Comment by wmhutchison** [comment]
Following up on EMERALD, no issues noted or detected involving the AKO upgrade. Closing this ticket as it's been now a bit over a week since the EMERALD upgrade.
