### ISSUE TITLE
PIA for Service Design (Including Optimal Sort)

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#3997]
**Describe the issue**
PIA required for Optimal Sort tool - has been rolled-up into a PIA for Service Design Generally.

A PIA for Service Design must include approaches to Service Design, advice for reasonable securirty, guidance for what is necessary and what is not, and a process for replicating analysis. A review of Optimal Sort will apply to this larger PIA, and the larger PIA will also apply to all future Service Design tools.

**Additional context**
See Ticket "Privacy Assessment Process Update - Cloud SaaS Adoption#4176" for more details.

**How does this benefit the users of our platform?**

The wider PIA will be useful not only to our program, but users from multiple ministries as it applies to broader Service Design initiatives. The PIA will also enable compliance with new privacy regulations.

**Definition of done**
- [x] Use identified and documented (please talk w/ Alex)
- [x] Identify any PI use
- [x] Identify authorities/risks
- [x]  Final PIA Submit signed-off [currently in progress on this step]

**Comment by bspeers-bcdevexchange** [comment]
PIA in secondary review.

**Comment by bspeers-bcdevexchange** [comment]
Currently sent for final sign-off.

**Comment by bspeersbcgov** [comment]
Signed off and closed.
