### ISSUE TITLE
Mautic Subscription Page UI Update

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#4014]
**Describe the issue**
The[ subscription page](https://subscribe.developer.gov.bc.ca/subscription) for our email communications needs to be updated to reflect our new email workflow. 

We need to add a greyed outbox to this page that says something along the lines of "critical private cloud platform emails (cluster updates, etc)." We will also need to provide users with direction to unsubscribe from critical emails you need to be removed from the registry.

This ticket is for the creation of the UI design of the page.

**Additional context**
Another ticket should be made to for the implementation of this design change.

**How does this benefit the users of our platform?**
Allows for users to easily unsubscribe to all non-critical emails. Ensures all users get critical updates

**Definition of done**

- [ ] Get approval from Pilar for language
- [ ] Create UI in Figma

- [ ]

**Comment by Iryna-Kaplun** [comment]
No relevant anymore. Can be deleted
