### ISSUE TITLE
Create presentation for OpenShift 101 

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#4016]
**Describe the issue**
Create a 15-20min presentation for the Digital Demos presentation for August 2nd. 

**Additional context**

> Hi Matt, would you be interested to do a presentation about technical training at one of the future Digital Demos? I was thinking an overview of the history, how the content is developed and delivered today and our plans for using an online platform like Instruqt, what training we offer now and what we plan to add in the future and explain why you think it was so successful and benefits it provides to the team? 15-20 mins

**How does this benefit the users of our platform?**
- Education about training offerings, and future improvements

**Definition of done**

- [x] Reach out to people who can help with 101 history
- [x] Develop slide deck
- [x] Present

**Comment by lukegonis** [comment]
Some people you could talk to are:
- Shelly
- Patrick Simonian
- Shea Stewart
- Jeff Kelly

**Comment by mtspn** [comment]
Decided to focus more on the future of OpenShift 101 and Instruqt, rather than needing to meet with past facilitators just giving a brief course history.

**Comment by mtspn** [comment]
Working on slide deck here: https://docs.google.com/presentation/d/1QstWbx7kn0XBmM3IS7ApsOolZ8i_ALf8Q3AmaG7AuFQ/edit?usp=sharing
