### ISSUE TITLE
Vault injector improvement

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4017]
**Describe the issue**
Vault injector is not HA at the moment, so is the proxy in nsx-t. Should add more replicas and confirm if that works with the current setup.

**Definition of done**
- [x] test out the changes
- [x] push to prod

**Comment by bashbang** [comment]
Upvote this please...for the next system upgrade.  It's impacted us on the GDX team on the more recent upgrade of both Gold and GoldDR

**Comment by IanKWatts** [comment]
We have opened a ticket with HashiCorp for this, because we haven't been able to get the agent-injector leader election to work yet, based on the available documentation.

**Comment by IanKWatts** [comment]
Talked to Hashicorp support today.  This will require a review of our gitops setup for Vault.  We should be using Helm directly, instead of generating manifests offline and adding them to the repo.  That's not a very sustainable approach.

**Comment by IanKWatts** [comment]
Now blocked by #4527, Vault GitOps repo reconfiguration

**Comment by IanKWatts** [comment]
GitOps repo updates are ready and are implemented for the lab clusters.  We will do the same in the prod clusters soon.

**Comment by IanKWatts** [comment]
The agent injector Deployment is now HA - prod clusters have 5 pods, labs have 3.  The proxy Deployment in the NSX clusters is updated for 3 pods.
