### ISSUE TITLE
Add monitoring for Kyverno

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4027]
**Describe the issue**
I discovered the Kyverno pods in Silver were crashlooping, but had not been notified of such.

**What is the Value/Impact?**
Awareness of when this critical service is not healthy.

**What is the plan? How will this get completed?**
Can we move this to `openshift-bcgov-kyverno` and get the free alertmanager rules? Should we set up some other kind of monitoring?

**Identify any dependencies**
Collab between Jason and AdvSol Ops

**Definition of done**
Kyverno is properly monitored in all clusters its deployed in

**Comment by w8896699** [comment]
pr on cerberus: https://github.com/bcgov/platform-services-sre/pull/21
ccm pr: https://github.com/bcgov-c/platform-gitops-gen/pull/717
sysdig dashboard: can be found [here](https://app.sysdigcloud.com/#/dashboards/403901?last=3600&scope=kubernetes.cluster.name%20as%20%22cluster%22%20in%20%3F%28%22silver%22%29%20and%20kubernetes.namespace.name%20as%20%22namespace%22%20in%20%3F%28%22kyverno%22%29%20and%20kubernetes.workload.type%20as%20%22type%22%20in%20%3F%20and%20kubernetes.workload.name%20as%20%22workload%22%20in%20%3F%20and%20container.label.io.kubernetes.pod.name%20as%20%22pod%22%20in%20%3F%20and%20kubernetes.pod.container.name%20as%20%22container%22%20in%20%3F)

CPU and memory alerts will send notification to rc: https://app.sysdigcloud.com/#/alerts/rules?filter=kyverno&direction=desc&sortBy=modifiedOn
