### ISSUE TITLE
Sysdig - Initial planning for workshops by the vendors / Virtual DevSecOps Days 

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#4043]
We are looking at running this event in September

Definition of done
- [x] Dates for Sysdig workshop are selected and confirmed with vendors
- [x] figure out event registration method
- [x] send out community notice

**Comment by w8896699** [comment]
Sysdig needs to know:
How long do they get to the presentation?
How many audiences?
3rd week of Sept is perfect but can be early.
Demo will be on morden web app and db monitoring.

**Comment by faisal-hamood** [comment]
How long do they get to the presentation?
- Workshop, not presentation ;)  Workshops include a hands-on component for training (similar to AWS code whisperer session)
How many audiences?
- Let's say 20-25 people 

Yes, we might need to postpone this by a month or so. Let's discuss during sprint planning.
