### ISSUE TITLE
PIA for Instruqt for OCP traininig

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#4044]
**Describe the issue**
PIA required for Instruqt for OCP training

**Additional context**
https://instruqt.com/

**How does this benefit the users of our platform?**

**Definition of done**
 Use identified and documented (please talk w/ Matt)
- [x] Identify any PI use
- [x] Identify authorities/risks
- [x] Submit for sign-off

**Comment by bspeers-bcdevexchange** [comment]
Working on scope with program and OCIO privacy, may be able to simplify scope and broaden impact simultaneously.

**Comment by bspeers-bcdevexchange** [comment]
Instruct has been set aside, however, PIA has been submitted for review and will focus on training and Instruct may be taken out of scope - any new tool will be added.
