### ISSUE TITLE
Add COMS link to Platform Storage Page

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#4072]
**Describe the issue**
On the platform storage page, add a link to [COMS](https://docs.developer.gov.bc.ca/reusable-services-list/#common-object-management-service) on the [platform storage page](https://docs.developer.gov.bc.ca/platform-storage/#s3-compatible-object-storage-dell-emc-elastic-cloud-storage)
**Additional context**
Email request: 
Hi Ari,
You may not be the right person to ask but perhaps you can steer me in the right direction!
 
There is already a link to our COMS service under the Reusable Services list on docs.developer.gov.bc.ca  (and Common Components sections on digital.gov) but I would like to see a mention of it on https://docs.developer.gov.bc.ca/platform-storage/#s3-compatible-object-storage-dell-emc-elastic-cloud-storage in the Details paragraph if possible.  Perhaps just another sentence at the end saying “There is also a microservice available (Common Object Management Service) that extends the S3 API with additional features that should be considered.”
 
Thank you!
 
Sharolyn Hurley
**How does this benefit the users of our platform?**
Links to shared service. 

**Definition of done**
- [x] Link is added to page
- [x] New build is triggered to the link is visible

**Comment by Pilargit12** [comment]
- Link added in details as per suggestion 
- Added link to related links section as well. 
- Edited on main due to small change (discussed with Matt Spencer) 
- New build to update change on live website
