### ISSUE TITLE
Test Kyverno policy to force TLS routes in NSX clusters

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4120]
**Describe the issue**
The NSX clusters are designed to only support routes using port 443 (with firewall rules). But this is not well exposed to users. Let's add a policy to reject routes without a TLS setting to help make this clearer.

**What is the Value/Impact?**
Improved security

**What is the plan? How will this get completed?**
Put this into CCM https://kyverno.io/policies/openshift/check-routes/check-routes/

**Identify any dependencies**
None

**Definition of done**
- Tested in LAB
- Create ticket to roll out in PROD

**Comment by StevenBarre** [comment]
@jleach after some more review, it looks like port 80 routes do work, just not for my browser that can reach internal URLs (low/medium dataclass). So this may not be needed.

@NickCorcoran any thoughts from you on if we should allow port 80 routes? Currently its being used by Cerberus/uptime.com to check the clusters health without needing to get a vanity TLS cert. Do we want people to choose using TLS as documented, or put in place policy to force TLS?

**Comment by NickCorcoran** [comment]
I think most people should be using TLS routes for their consumable content, but I get your point re: health checks on port 80.  It is a waste to expect all to be 443 for that type of traffic.  Perhaps we can have them include "healthcheck" as part of the route name, and all others must be 443.  could that work?

**Comment by StevenBarre** [comment]
Discussed further with Nick and we agreed to not do this now.
