### ISSUE TITLE
Test RH Integration upgrade in CLAB and KLAB2

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4138]
**Describe the issue**
Work with AG to upgrade the RH Integration operators in CLAB and validate their app supports the new version

**What is the Value/Impact?**
Ensure a smooth upgrade in PROD

**What is the plan? How will this get completed?**
Find the latest version and release notes from https://access.redhat.com/documentation/en-us/red_hat_integration/ and https://access.redhat.com/documentation/en-us/red_hat_amq_streams and review with AG.
Update the operators in CLAB
Verify with AG (Jennifer D and Ryan L) that the upgrade is safe for PROD

**Identify any dependencies**
AG

**Definition of done**
- [x] RH Integration upgraded in CLAB
- [ ] RH Integration upgraded in KLAB2
- [x] Testing completed in CLAB
- [ ] Testing completed in KLAB2
- [x] Upgrade docs updated with any extra steps
- [ ] Plans made for PROD upgrades

**Comment by StevenBarre** [comment]
Reviewed https://access.redhat.com/documentation/en-us/red_hat_integration/2023.q2/html-single/release_notes_for_red_hat_integration_2023.q2/index . Camel K supported configs link does not show 4.13, but Matt confirmed the page is out of date and 4.13 is supported. Looks like only minor version updates and nothing major.

**Comment by tbaker1313** [comment]
Upgraded again in CLAB - have send an email to request further testing which will occur next week.

**Comment by tbaker1313** [comment]
Tested again after upgrading AMQ Streams to 2.5 - tested successfully.

**Comment by tbaker1313** [comment]
Reopening to document that we need to do this for KLAB2 once the upgrade to 4.12 is completed.

**Comment by tbaker1313** [comment]
Closing to make a new one for KLAB2
