### ISSUE TITLE
Fix ACS Access Provider for IDIR

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#4141]
**Describe the issue**
ACS has 2 different Access Provider (or IDP) integrations.  
1 uses OpenShift Auth, which seamlessly updated through the migration to Gold SSO
2 used a client in the root AzureIDIR realm on Silver, that is no longer

We attempted to update the identity issuer information, but this information is not editable in ACS.  It requires us to make a new Access Provider.  While this was done easily (created within our Gold platform-services realm), the rules associated with the old Access Provider are not easily migrated to the new one.  

This task will export all rules (authorizations) from the old access provider and apply them to the new access provider.

**Additional context**
We should have an idea on how to export/create from the work Billy has done in the past.

**How does this benefit the users of our platform?**
Currently users without OpenShift user accounts cannot access ACS (includes Ministry security teams, and others)

**Definition of done**
- [x] Create new client in platform-services KeyCloak Realm for ACS-lab
- [x] Create new access provider in lab environment and test it works
- [x] Export all rules (authorizations) from old Access provider
- [x] Import/create new rules (authorizations) on new Access provider
- [x] Validate working

Once this is complete, we can start planning for prod environment.

**Comment by AvneetKahlon** [comment]
Case created with RedHat #03572655 to help on editing the issuer in auth provider.
