### ISSUE TITLE
Remove GitHub IDP option for Emerald/KLAB2 login

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#4142]
**Describe the issue**
As part of locking the Emerald/KLAB2 clusters down to IDIR only, we require the removal of the GitHub IDP.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [x] Apply changes to KLAB2 KeyCloak client to restrict to Azure based IDIR only
- [x] Test KLAB2 to ensure Azure based IDIR only
- [x] Apply changes to Emerald KeyCloak client to restrict to Azure based IDIR only
- [x] Test Emerald to ensure Azure based IDIR only

**Comment by agahchen** [comment]
:fire: :fire:

**Comment by ShellyXueHan** [comment]
@Kolezhanchik @NickCorcoran here are the steps to disable Github for OCP cluster login:
1. login to SSO:
  - for klab2 client, it's in dev SSO (https://dev.loginproxy.gov.bc.ca/auth/admin/platform-services/console/#/realms/platform-services/clients/3b9e8e45-175f-45f9-9fe9-29a0164b9cf5)
  - for emerald client, it's in prod SSO (https://loginproxy.gov.bc.ca/auth/admin/platform-services/console/#/realms/platform-services/clients/25758866-c4c8-4a8a-94b4-00a350b85502)
1. click open the client, scroll all the way down to `Authentication Flow Overrides`
1. expend that section, and find `Browser Flow`
2. from the drop down, pick the flow called `browser - idir - only`
3. click on save
4. now if you clear cache from your browser and login to emerald/klab2, it should be IDIR only for the login!

**Comment by NickCorcoran** [comment]
Thank you Shelly!  I also sent out an email to users with accounts on Emerald and posted in the nsx-early-adopters channel on RocketChat.
