### ISSUE TITLE
Vault injector resource tuning

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4147]
**Describe the issue**
Here is the current level of resources given to vault agent for both init and sidecar containers:

```
            - name: AGENT_INJECT_CPU_REQUEST
              value: "250m"
            - name: AGENT_INJECT_CPU_LIMIT
              value: "500m"
            - name: AGENT_INJECT_MEM_REQUEST
              value: "64Mi"
            - name: AGENT_INJECT_MEM_LIMIT
              value: "128Mi"
```

While the actual usage is really low:
![Screen Shot 2023-07-27 at 3.51.06 PM.png](https://images.zenhubusercontent.com/5c1acc79305b926f81e2c3d4/54aab183-22b4-4e1c-8240-b0511485e514)

We could definitly lower the config quite a bit, but will also need to look up how much the init containers need since the config impacts both.

**Definition of done**
- [x] look into average resource usage for Vault sidecar and init containers (Jason suggested 30/100m CPU)
- [x] update resources config from injector deployment

**Comment by IanKWatts** [comment]
This StackOverflow answer lists updated resource settings, as used by one team.  Should be a starting point for testing default resource settings for the injector: https://stackoverflow.developer.gov.bc.ca/questions/1133
```
vault.hashicorp.com/agent-requests-cpu: '10m'
vault.hashicorp.com/agent-limits-cpu: '50m'
vault.hashicorp.com/agent-requests-mem: '25Mi'
vault.hashicorp.com/agent-limits-mem: '100Mi'
```

**Comment by IanKWatts** [comment]
We can update the values in BC-Gov-PaaS-Platform-Services/platform-gitops-vault/base/vault-agent-injector/injector-deployment.yaml

**Comment by IanKWatts** [comment]
https://github.com/BC-Gov-PaaS-Platform-Services/platform-gitops-vault/pull/30
