### ISSUE TITLE
Weekly CCM PROD Push for 2023, August 15th to August 17th

### ISSUE THREAD

**Issue by tmorik** [BCDevOps/developer-experience#4157]
**Describe the issue**
This ticket will track efforts spent toward creating the next CCM release and promoting it against the three production Openshift clusters.

**Definition of done**
- [x] Create suitable GitHub Release before EOD Friday
- [x] Create suitable Standard Change RFCs and assign to team members as appropriate
- [x] Create and Receive approval for PR incrementing CCM version for PROD clusters
- [x] Ensure version increment PR is merged before executing any RFCs
- [x] Execute RFC for SILVER & EMERALD cluster
- [x] Execute RFC for GOLD cluster
- [x] Execute RFC for GOLDDR cluster

**Comment by tmorik** [comment]
# v4.16.9 for OCP 4.12

## What's Changed

* Ministry viewer role by @IanKWatts https://github.com/bcgov-c/platform-gitops-gen/pull/704
* update acs-config by @w8896699 https://github.com/bcgov-c/platform-gitops-gen/pull/698
* fix: memory allocated to wrong deployment by @jleach https://github.com/bcgov-c/platform-gitops-gen/pull/703
* fix: update loop vars by @jleach https://github.com/bcgov-c/platform-gitops-gen/pull/702
* feat: update user ID for access by @jleach https://github.com/bcgov-c/platform-gitops-gen/pull/699
* fix: policy syntax fix depending on kyverno version by @jleach https://github.com/bcgov-c/platform-gitops-gen/pull/701
* Fix for empty sync_policy by @IanKWatts https://github.com/bcgov-c/platform-gitops-gen/pull/700
* feat: add support for kyverno v1.9.x upgrade by @jleach https://github.com/bcgov-c/platform-gitops-gen/pull/694


## Additional context:

- https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4157

**Comment by tmorik** [comment]
- CHG0051245 SILVER
- CHG0051246 EMERALD
- CHG0051247 GOLD
- CHG0051248 GOLD DR

**Comment by wmhutchison** [comment]
An issue came up during the implementation of the latest CCM merge in SILVER. It looks like the CCM merge increased the amount of RAM for the kyverno pods, but as we found out today, that's not nearly enough. During an emergency session we increased this amount of RAM to 4GB which wasn't enough, and again to 8GB which was enough. 

Following up to this statement will be additional steps we'll need to follow to ensure this doesn't happen in GOLD or GOLDDR.

**Comment by wmhutchison** [comment]
recommended steps for dealing with GOLD/GOLDDR.

* pause CCM cluster-apps + kyverno
* merge official GOLD (and GOLDDR) PR.
* create new PR for additional memory against GOLD repo, also merge.
* Unpause CCM cluster-apps + kyverno

**Comment by tmorik** [comment]
Just checked Gold and Gold DR's current memory trend for kyverno:

## GOLD

It is about half the size of the pre-CCM silver. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjBJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f712fede09a38e105791a2fbf4b7a01b4b24f8b2/image.png)

## GOLD DR

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjRJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--353df8ee8ebc39a843c7f588dd5bd913bffbaeab/image.png)

**Comment by tmorik** [comment]
Memory adjustment PR for each clusters (Draft) :

- Gold : https://github.com/bcgov-c/platform-gitops-kamloops-gold/pull/95
- Gold DR: https://github.com/bcgov-c/platform-gitops-calgary-golddr/pull/79

Currently it's set to 6Gi (current 1.5Gi x4 ). Apply these after the official PR gets merged.

**Comment by wmhutchison** [comment]
We have successfully updated GOLD manually to match SILVER memory allotment (8GB). That value will be used for all PROD clusters, and codified during the next CCM release (I will get the ball rolling on that future PR shortly).

**Comment by wmhutchison** [comment]
GOLDDR sync completed today. Closing ticket.
