### ISSUE TITLE
Update all iLO passwords

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4188]
**Describe the issue**
As Tats is moving onto another team, we need to clean up his access, group assignments, and rotate passwords.

**What is the Value/Impact?**
Ensure security of the MCS team

**What is the plan? How will this get completed?**
Run our playbook to rotate the iLO passwords

**Identify any dependencies**
None

**Definition of done**
iLO passwords updated

**Comment by StevenBarre** [comment]
Putting this off until the 4.13 upgrades

**Comment by tbaker1313** [comment]
Updated ILO/iDRAC passwords in the SILVER cluster successfully.

**Comment by tbaker1313** [comment]
Updated iDRAC passwords in the GOLD Cluster successfully.

**Comment by tbaker1313** [comment]
Updated GOLDDR iDRAC passwords. Completed.
