### ISSUE TITLE
Update util server root passwords

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4189]
**Describe the issue**
As Tats is moving onto another team, we need to clean up his access, group assignments, and rotate passwords.

**What is the Value/Impact?**
Ensure security of the MCS team

**What is the plan? How will this get completed?**
Update root pw on all MCS managed servers

**Identify any dependencies**
None

**Definition of done**
Passwords rotated

**Comment by tbaker1313** [comment]
Updated all the LAB util server root passwords in CHG0054005

**Comment by tbaker1313** [comment]
Updated all the PROD util server root passwords in CHG0054007
