### ISSUE TITLE
Remove Tats from Red Hat accounts

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4196]
**Describe the issue**
As Tats is moving onto another team, we need to clean up his access, group assignments, and rotate passwords.

**What is the Value/Impact?**
Ensure security of the MCS team

**What is the plan? How will this get completed?**
Log in to the primary RH account and go to user management and mark the account as inactive

**Identify any dependencies**
None

**Definition of done**
- [x] Red Hat access removed for the BC Gov account
~~- [ ] Red Hat access removed for the AdvSol account~~

**Comment by wmhutchison** [comment]
Removed Tats' account privileges for the BCGov account, and then disabled his account.

**Comment by wmhutchison** [comment]
Checked the advsol Red Hat account. No entries for Tatsuya exist there, thus nothing needing to be done. Closing ticket as complete.
