### ISSUE TITLE
Remove Tats from BCGov Google Drive

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4197]
**Describe the issue**
As Tats is moving onto another team, we need to clean up his access, group assignments, and rotate passwords.

**What is the Value/Impact?**
Ensure security of the MCS team

**What is the plan? How will this get completed?**

**Identify any dependencies**

**Definition of done**
- Remove bcdevexchange.org Google account
- Remove dxcas.com account from Google drive / calendar access

**Comment by ShellyXueHan** [comment]
@Iryna-Kaplun could you help with this? I don't seem to be able to remove ppl from google..
