### ISSUE TITLE
Remove Tats from Azure AD Sync

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4198]
**Describe the issue**
As Tats is moving onto another team, we need to clean up his access, group assignments, and rotate passwords.

**What is the Value/Impact?**
Ensure security of the MCS team

**What is the plan? How will this get completed?**

**Identify any dependencies**
Azure AD team

**Definition of done**
Tats restored to a "regular" IDIR account

**Comment by NickCorcoran** [comment]
I have removed from all AAD groups for our team.  Will work with Shelly/Cailey re: Vault secrets.

**Comment by NickCorcoran** [comment]
Shelly taking action on secret rotation.
