### ISSUE TITLE
Remove Tats from Vault

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4199]
**Describe the issue**
As Tats is moving onto another team, we need to clean up his access, group assignments, and rotate passwords.

**What is the Value/Impact?**
Ensure security of the MCS team

**What is the plan? How will this get completed?**

**Identify any dependencies**
None

**Definition of done**
Tats no longer has any admin access to Vault

**Comment by ShellyXueHan** [comment]
turns out there is no access setup for Tats, all good then!
