### ISSUE TITLE
Review and update the maintenance alert template

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4201]
Rewrite the following pages: https://github.com/BCDevOps/platform-services-status-page-notifications/blob/master/maintenance_template.md

Does the template still match with our standards for communication? Are the listed approvers for PRs still the best people for that? https://github.com/BCDevOps/platform-services-status-page-notifications/blob/master/.github/CODEOWNERS

**Definition of done**

- [ ] First draft
- [ ] SME review
- [ ] Approval

**Comment by Pilargit12** [comment]
Hi @StevenBarre can you provide more context?  I do not oversea the BCDevOps pages.  Can you find out subject matter experts that can verify this please?

**Comment by StevenBarre** [comment]
That's the template we use to post in the #devops-alerts channel in RocketChat about upcoming maintenance. We wanted to verify that the language used is up to date and the grammar is good. The template was written by Olena in Apr 2020 and has only had a few minor updates since.

**Comment by Pilargit12** [comment]
Updated 🚀
