### ISSUE TITLE
Notification for Cal network change

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4210]
**Describe the issue**
[TIB](https://ociomysc.service-now.com/sp?id=kb_article&table=u_kb_template_technical_information_bulletin&sys_id=a9cbd49cdbc1fd10fa861938139619bf&view=ess) will be on Sept 24th and will take out the Calgary datacenter for up to an hour.

**What is the Value/Impact?**
MCS Gold DR will be down

**What is the plan? How will this get completed?**
Post about it in the alerts channel
Draft and get approved an email to all Gold DR PO/TL telling them about the outage.

**Identify any dependencies**
Will need approval from Olena of message contents, and help from Shelly/Cailey to send from the PS mailbox

**Definition of done**
- [x] Craft PR for posting in alerts channel.
- [x] Post in alerts channel once PR is approved/merged.
- [x] email sent to PO/TL

**Comment by wmhutchison** [comment]
PR created for RC comms, awaiting approval: https://github.com/BCDevOps/platform-services-status-page-notifications/pull/220

**Comment by wmhutchison** [comment]
Will push for escalation on this if not approved by next week (Monday/Tuesday).

**Comment by StevenBarre** [comment]
Prodded Sal and the email got sent
