### ISSUE TITLE
SDN - OCP 4.12 - Obtain new ncp image

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4213]
**Describe the issue**
A new ncp image is now available from VMWare which will support our upgrade to OCP 4.12. for KLAB2/EMERALD.

**Additional context**
At present the Platform Operations team should be able to download the new ncp software on our own, but still need Dan's help to upload it to the correct external location.

Long term solution for uploading the image is to place it in Artifactory, but the collective team decision is to hold off on that until we have Artifactory in HA mode (in progress).

**How does this benefit the users of our platform?**

**Definition of done**
- [x] work with team and Artifactory experts to download ncp and upload to Artifactory.
- ~~[ ] if Artifactory option does not work then work with Dan Deane regarding the download of ncp and upload to our Dockerhub account.~~

**Comment by wmhutchison** [comment]
WIthout needing Dan's intervention, I have been able to download the zip file provided by VMWare from their support web site, it is currently sitting on KLAB2-UTIL in the /data directory (nsx-container-4.1.1.0.22071564.zip) to be investigated/etc.

The remaining todo is to either find a viable replacement for the Dockerhub account Dan opened for supporting KLAB2/EMERALD, or not viable in a timely fashion, ask Dan to upload the newest download to that location.

**Comment by StevenBarre** [comment]
We should be able to put this into Artifactory.

**Comment by wmhutchison** [comment]
discussed further with Steven. ncp image's pull policy is IfNotPresent, so should not be a blocker for us to migrate to Artifactory. 

After a new NSX-backed Openshift cluster is first built, we can add to our existing playbooks to add similar structure for image pulls similar to what we're currently doing for Trident.

**Comment by wmhutchison** [comment]
discussed further with Steven. ncp image's pull policy is IfNotPresent, so should not be a blocker for us to migrate to Artifactory. 

After a new NSX-backed Openshift cluster is first built, we can add to our existing playbooks to add similar structure for image pulls similar to what we're currently doing for Trident.

**Comment by wmhutchison** [comment]
will proceed to now setup the downloaded ncp image into Artifactory, asking Cailey for help and possibly a new service account if needed. Once done, then we will proceed with updating KLAB2's ncp image reference and version, working out bugs/issues if they arise.

**Comment by wmhutchison** [comment]
ncp image now resides in Artifactory, no need to bug Dan Deane about this.
