### ISSUE TITLE
Automate regular reindexing of Rocketchat DB (and possibly others)

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#4216]
Regular re-indexing is part of good database hygiene, but it's something we don't actively do very often. Reindexing helps queries to run efficiently. If you don't reindex your DB, queries will usually gets slower over time, as the index grows lobsided.

Rocketchat is the most important candidate for reindexing, because even a small improvement to query time would probably have a noticeable impact on the performance of the database.

We should also look into the benefits of introducing automated reindexing of our other app databases, and maybe some documentation on reindexing as a best practice for teams.

**Definition of Done**
- [ ] Investigate the options for reindexing the RC database
- [ ] Test the reindexing plan
- [ ] Automate reindexing on a regular schedule based on the cost/benefit results of the test
- [ ] Create a ticket that uses the information we learned reindexing the RC database to inform a plan for possibly reindexing other app DB and/or writing docs about reindexing as best practice.

**Comment by IanKWatts** [comment]
The following is not related to indexes, but since I took a look, figured I'd share it here.

https://www.mongodb.com/docs/v6.0/administration/analyzing-mongodb-performance/

**The global lock total time should be close to the uptime**
```
rs0 [direct: primary] test> db.serverStatus().uptime
188435
rs0 [direct: primary] test> db.serverStatus().globalLock
{
  totalTime: Long("188436351000"),
  currentQueue: { total: 0, readers: 0, writers: 0 },
  activeClients: { total: 0, readers: 0, writers: 0 }
}
```
Here, the total time in microseconds is the same as the uptime in seconds.

**Lock wait times**
Dividing locks.<type>.timeAcquiringMicros by locks.<type>.acquireWaitCount can give an approximate average wait time for a particular lock mode.
```
rs0 [direct: primary] test> db.serverStatus().locks
{
  ParallelBatchWriterMode: {
    acquireCount: { r: Long("8285760"), W: Long("86") },
    acquireWaitCount: { r: Long("1"), W: Long("1") },
    timeAcquiringMicros: { r: Long("229736"), W: Long("625") }
  },
  FeatureCompatibilityVersion: { acquireCount: { r: Long("45959024"), w: Long("3500227") } },
  ReplicationStateTransition: {
    acquireCount: { w: Long("18033054"), W: Long("4") },
    acquireWaitCount: { w: Long("2"), W: Long("1") },
    timeAcquiringMicros: { w: Long("997"), W: Long("3") }
  },
  Global: {
    acquireCount: { r: Long("50685042"), w: Long("9563260"), W: Long("6") }
  },
  Database: {
    acquireCount: { r: Long("66496"), w: Long("9544190"), W: Long("4") }
  },
  Collection: {
    acquireCount: { r: Long("66500"), w: Long("9544167"), W: Long("6") }
  },
  Mutex: { acquireCount: { r: Long("29101157") } },
  oplog: { acquireCount: { w: Long("1") } }
}
```
Here, ParallelBatchWriterMode wait time ~0.2s for reads and ~0.0006s for writes, if I read that right.

**Connections are well within the limit**
```
rs0 [direct: primary] test> db.serverStatus().connections
{
  current: 216,
  available: 838644,
  totalCreated: 5474,
  active: 12,
  threaded: 216,
  exhaustIsMaster: 4,
  exhaustHello: 3,
  awaitingTopologyChanges: 7
}
```

**Comment by caggles** [comment]
Closing as "won't do."

I did some more reading on Mongo indexes and it seems like regular reindexing isn't as necessary as it had been previously - especially as RocketChat reindexes with each upgrade. Regular reindexing wouldn't help the issue as much as I have previously believed, seems like my DBA knowledge is getting a touch outdated, lol.
