### ISSUE TITLE
SILVER - Refresh old physical APP nodes into replacement VM nodes

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4222]
**Describe the issue**
As part of the lifecycle process for hardware, we are coming up to needing a refresh against four physical APP nodes, to be replaced with eight VMs (each VM is half the size of CPU/RAM compared to the physicals). This ticket will track this work starting from initial paperwork to final decommissioning of the old hardware.

**Blocked By**
Change freezes for SILVER (Wildfire state of emergency, possibly HIBC RSP as well) prevent us from proceeding with this work.

**How does this benefit the users of our platform?**

**Definition of done**
- [x] Handle initial DXC tickets involved with the creation of new VM app nodes.
- [x] Handle initial DXC tickets involved with the decommissioning of the old hardware nodes.
- [x] Prepare a suitable PR involving the inventory changes involved with this change.
- [x] Create and execute an approved RFC to handle the removal of the old nodes and replacing them with the new nodes.
- [x] If not done within the scope of the previous RFC, create and execute an RFC specifically meant to decommission the old nodes.

**Comment by wmhutchison** [comment]
During pre-check portion where we create NNR DNS entries for the production hostnames, it was discovered that none of these have propagated out to DNS.

Not a major issue right now since we're not not yet in a position to start building out the replacement VMs, but will need to be investigated and resolved at some point. Will update more about that effort here once underway.

**Comment by wmhutchison** [comment]
Updated this ticket to reflect current state of things. Also moving into Blocked since we cannot proceed further with implementing the refresh until SILVER is free of change freezes.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/rhcos-ignition-builder/pull/120

**Comment by StevenBarre** [comment]
Scheduled for Oct 4-6th

**Comment by StevenBarre** [comment]
Completed
