### ISSUE TITLE
GOLDDR - Refresh old physical APP nodes into replacement VM nodes

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4223]
**Describe the issue**
As part of the lifecycle process for hardware, we are coming up to needing a refresh against three physical APP nodes, to be replaced with six VMs (each VM is half the size of CPU/RAM compared to the physicals). This ticket will track this work starting from initial paperwork to final decommissioning of the old hardware.

**Blocked By**
Waiting on build tickets to drop in the DXCAS ticketing system, whose presence will be due to the actual VMs being provisioned and ready for us to move forward on a rebuild RFC.

**How does this benefit the users of our platform?**

**Definition of done**
- [x] Handle initial DXC tickets involved with the creation of new VM app nodes.
- [x] Handle initial DXC tickets involved with the decommissioning of the old hardware nodes.
- [x] Prepare a suitable PR involving the inventory changes involved with this change.
- [x] Create and execute an approved RFC to handle the removal of the old nodes and replacing them with the new nodes.
- [ ] If not done within the scope of the previous RFC, create and execute an RFC specifically meant to decommission the old nodes.

**Comment by wmhutchison** [comment]
During pre-check portion where we create NNR DNS entries for the production hostnames, it was discovered that none of these have propagated out to DNS.

Not a major issue right now since we're not not yet in a position to start building out the replacement VMs, but will need to be investigated and resolved at some point. Will update more about that effort here once underway.

**Comment by wmhutchison** [comment]
Moving into Blocked, as final build tickets have not yet dropped for this clusters.

**Comment by StevenBarre** [comment]
Build tickets have dropped

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/rhcos-ignition-builder/pull/119

**Comment by StevenBarre** [comment]
CHG0052434 scheduled for Sept 25-27

**Comment by StevenBarre** [comment]
Completed
