### ISSUE TITLE
Investigate Cert manager to replace certbot

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#4224]
## Description
Evaluate Cert Manager's capabilities in Klab to confirm its suitability for automatic SSL/TLS certificate renewal, potentially replacing Certbot.

**Primary Assignee:** Ian

## Additional Context
- Add any relevant attachments, logs, or screenshots here.

## User Benefits
This investigation will ensure our platform maintains uninterrupted SSL/TLS certificate management, enhancing security and reliability for all users.

## Definition of Done
- Set up ClusterIssuers or Issuer in the Klab environment.
- Configure Cert Manager to handle certificate issuance and auto-renewal.
- Verify that Cert Manager reliably automates the renewal process without issues.
- Document the setup and verification process.
- Provide a summary of the findings to the team, confirming if Cert Manager meets our needs for certificate management.

**Comment by w8896699** [comment]
https://cert-manager.io/docs/getting-started/

**Comment by w8896699** [comment]
https://console.apps.klab.devops.gov.bc.ca/k8s/ns/shellyxuehan-dev/secrets/ssl-secret
https://console.apps.klab.devops.gov.bc.ca/k8s/ns/shellyxuehan-dev/secrets/eab-secret

**Comment by IanKWatts** [comment]
Apparently the ACME v2 API does not allow for an admin approval step, so the cert-manager automation "just works".  The OCIO team will discuss this and decide if they're okay with that; they want to be able to verify that there is an iStore order that has been approved and paid.  In the meantime, cert-manager seems to work just fine.

**Comment by IanKWatts** [comment]
Testing certificate renewal will have to wait, because both the Entrust certificate and the Let's Encrypt certificate have 90 day durations.  They will not be eligible for renewal until September 30 and September 10, respectively.

**Comment by IanKWatts** [comment]
@w8896699 and @NickCorcoran I think we can close this ticket.  We have investigated; cert-manager works for OCIO Entrust and Let's Encrypt; we just need to wait and see what happens with Entrust and OCIO.  I'll leave the test certs in place so that in time we can verify that the renewal also works.
