### ISSUE TITLE
 integrate Cerberus check with DXC check script

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#4225]
**Describe the issue**
Cerberus now have a check for kyverno. Olena suggest that DXC team's check should involve this check so it can notifying when kyverno is down.
(Need to add more detail with DXC's help.)
**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by StevenBarre** [comment]
Add a PrometheusRule to the kyverno namespace to alert on-call if the pods are down
