### ISSUE TITLE
OpenShift Architecture - OpenShift 101 Workshop Video Recording

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#4231]
**Describe the issue**
Create a video of this workshop section based on new content 

**How does this benefit the users of our platform?**
Updated learning materials

**Definition of done**

- [x] New content is delivered, tested, refined as needed
- [x] Video is recorded, edited, uploaded
- [x] Add to playlist for 101 workshop content

**Comment by mtspn** [comment]
Video draft here: https://youtu.be/_XauFvYaGJI?si=C7dJr6CgBZHEO78u

**Comment by mtspn** [comment]
Hi Cailey, another video here for your review. Please share any feedback or suggestions in the comments of this ticket. Thanks!

**Comment by caggles** [comment]
Sounds pretty good! The only thing I might suggest is to add something during the discussion of containers vs pods to clarify that a pod usually has one primary container, and the other containers in the pod should be sidecars (aka they should run processes that exist only to support the primary process - things like logging containers or the vault sidecar or whatever). That would probably help to clarify why you might run multiple containers in a pod.

**Comment by mtspn** [comment]
Thanks Cailey, I may look at using a more recent recording and check whether the description of a service is correct.
