### ISSUE TITLE
Sysdig with Emerald

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#4239]
**Describe the issue**
The NSX clusters cannot connect directly to the internet. The Sysdig agents currently cannot connect to the collector. We want to adjust its settings to use the Forward Proxy to connect to the collector so it can report data.

**Additional context**
- https://docs.sysdig.com/en/docs/installation/configuration/sysdig-agent/tune-agent/enable-http-proxy-for-agents/
- https://docs.sysdig.com/en/docs/administration/saas-regions-and-ip-ranges/

**How does this benefit the users of our platform?**
Allow Emerald users to use Sysdig

**Definition of done**
Sysdig data being collected for Emerald cluster

**Comment by ShellyXueHan** [comment]
### updates and todos:
- sysdig agent daemonset has been installed in nsx-t clusters
- enable sysdig http proxy: https://docs.sysdig.com/en/docs/installation/configuration/sysdig-agent/tune-agent/enable-http-proxy-for-agents/
- setup netpol

**Comment by StevenBarre** [comment]
Proxy details https://digital.gov.bc.ca/cloud/services/private/internal-resources/emerald/

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/blob/master/roles/sysdig_agent/templates/cm-sysdig-agent.yaml.j2

**Comment by StevenBarre** [comment]
Sent forward proxy form to Luke to get the two URLs added to the allow list. Blocked until that is completed.

**Comment by StevenBarre** [comment]
Scheduled update of the forward proxy Jan 29th

**Comment by w8896699** [comment]
send pr for review https://github.com/bcgov-c/platform-gitops-gen/pull/787

**Comment by w8896699** [comment]
Sysdig gets emerald and KLAB2 data, ticket close
