### ISSUE TITLE
Patroni/Crunchy Documentation Updates

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#4240]
**Describe the issue**
There's a bunch of best practices and help with Patroni and CrunchyDB that still just kinda lives in my head and that I communicate with teams mostly through helping them with troubleshooting. Documenting this for teams to self-serve this information would be great.

**How does this benefit the users of our platform?**
Provides knowledge transfer on managing DBs from me to teams.

**Definition of done**
- [x] Patroni architecture overview and troubleshooting
- [x] Installing Patroni (helm, recommended config, recommended image sources)
- [x] Upgrading Patroni (upgrading patroni version vs upgrading postgres version)
- [x] Resource usage and requests/limits
- [ ] Crunchy architecture overview and troubleshooting
- [ ] Installing Crunchy (helm, recommended config, recommended image sources)
- [ ] Limitations of Crunchy community edition (esp image sources)
- [ ] Upgrading Crunchy (upgrading crunchy version vs upgrading postgres version)

**Comment by mitovskaol** [comment]
@caggles Can you please include the link to the documentation in the ticket
