### ISSUE TITLE
ACS Clean up

### ISSUE THREAD

**Issue by AvneetKahlon** [BCDevOps/developer-experience#4242]
**Describe the issue**
ACS rules need to be cleaned to have a uniform naming of roles. The PO and 2 technical leads are provisioned access through registry with naming app-team-XXXX and additional access is assigned manually through scripts. these additional accesses need to have a uniform naming like manual-app-team-XXXX.
**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**

- update the roles in both auth providers
- delete the unnecessary roles

**Comment by NickCorcoran** [comment]
majority of work done here, but will be an ongoing task.
