### ISSUE TITLE
Hashicorp (Vault) - Initial planning for workshops by the vendors / Virtual DevSecOps Days

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#4250]
We are looking at running this event in September

Definition of done
- [x] Dates for Hashicorp (Vault) workshop are selected and confirmed with vendors

**Comment by ShellyXueHan** [comment]
### update:
Date is settled at November 8th, 9-12 in person. Waiting for detailed agenda

**Comment by lukegonis** [comment]
This is no longer something we are pursuing
