### ISSUE TITLE
 JFrog (Artifactory) - Initial planning for workshops by the vendors / Virtual DevSecOps Days 

### ISSUE THREAD

**Issue by Iryna-Kaplun** [BCDevOps/developer-experience#4251]
We are looking at running this event in September

Definition of done
- [ ] Dates for JFrog (Artifactory) workshop are selected and confirmed with vendors

**Comment by caggles** [comment]
JFrog misunderstood the original request and sent me a bunch of (honestly pretty cool) self-directed training, so I've spoken to them again about doing a guided session and they're going to get back to me.
