### ISSUE TITLE
SDN - Document in EMERALD docs how to use native Tekton

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4252]
**Describe the issue**
Due to this likely being a popular use case going forward on EMERALD, expand on the existing documentation to ensure all components involved for using Tekton on EMERALD in lieu of Github Actions is fully documented.

**Additional context**
Vendor link: <https://tekton.dev/docs/pipelines/labels/>

Document in more detail the following:
- how to properly label a Pipeline resource to add pod DataClass labels.
- how to add NetworkPolicy to allow triggering of a pipeline within the SPAN network so that the user namespace can reach what it needs to in the openshift-pipelines namespace.

**How does this benefit the users of our platform?**
Offering viable solutions to users of the EMERALD cluster matching what they could use on other non-NSX Openshift clusters.

**Definition of done**
- [ ] Create rough draft of proposed documentation update.
- [ ] Submit proposed documentation update via standard processes. Submit revisions to content if needed.
- [ ] Confirm when documentation update is complete,

**Comment by StevenBarre** [comment]
No longer needed
