### ISSUE TITLE
Provisioner: Update and deploy new app-provisioner image

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#4277]
**Describe the issue**
The Application Developers need to know how to apply changes to the app-provisioner image, test the changes in a lab cluster, and then apply the change to all clusters.

**Rational/Why**
The Application Developers will soon take over the maintenance of the provisioner.

**Additional Context** 
- https://github.com/bcgov-c/devops-fulfillment-pipeline
- https://github.com/bcgov-c/tenant-gitops-eb6118
- https://provisioner.apps.silver.devops.gov.bc.ca 

**Dependencies**
- app-provisioner image
- Argo Events
- Argo Workflows

**Tests**
These steps are described in general terms.  We can go through the process together - that is, with Ian.
* Clone the app-provisioner repo: https://github.com/bcgov-c/devops-fulfillment-pipeline
* Create a new branch, such as "practice_ian"
* Make a small change to the Ansible playbook, such as the addition of a debug message
* Commit the branch and change back to the repo
* Update the app-provisioner BuildConfig to build from your branch
* Test the new image in Dev or Test by updating the appropriate lab sensor and submitting a registry request in that environment
* Inspect the container logs and verify that your test message is present
* Tag the image, using the next logical patch number
* Update the sensors for each cluster to use the new version

**Definition of done/Acceptance Criteria**
- [ ] New image has been built
- [ ] Image has been tested in lab
- [ ] Update has been deployed to all clusters
- [ ] Test branches have been merged and deleted

**Comment by Iryna-Kaplun** [comment]
This issue has been copied to the registry repo #1061 and will be tracked there.
