### ISSUE TITLE
Upgrade RH integration in KLAB2 and test

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4283]
**Describe the issue**
Work with AG to upgrade the RH Integration operators in CLAB and validate their app supports the new version

**What is the Value/Impact?**
Ensure a smooth upgrade in PROD

**What is the plan? How will this get completed?**
Find the latest version and release notes from https://access.redhat.com/documentation/en-us/red_hat_integration/ and https://access.redhat.com/documentation/en-us/red_hat_amq_streams and review with AG.
Update the operators in KLAB2
Verify with AG (Jennifer D and Ryan L) that the upgrade is safe for PROD

**Identify any dependencies**
AG

**Definition of done**

- [x] RH Integration upgraded in KLAB2
- [x] Testing completed in KLAB2
- [x] Upgrade docs updated with any extra steps
- [x] Plans made for PROD upgrades

**Comment by wmhutchison** [comment]
Based on version numbers I'm now seeing for Integration-related operators, KLAB2 is now running the same version as CLAB, with the Camel K operator now being very slightly newer than the version in CLAB. Barring any new refreshes in KLAB2 afterward, we're probably able to move forward with a request-to-test once KLAB2 node upgrades finishes off today.

**Comment by StevenBarre** [comment]
Emailed Jennifer and team.
