### ISSUE TITLE
Vault - knowledge sharing with Ian

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4288]
**Describe the issue**
knowledge sharing with Ian to become tech support for Vault service

**Definition of done**
- [x] KT meetings
- [x] complete documents if missing

**Comment by IanKWatts** [comment]
Shelly and I have had several KT sessions.  I have read the maintenance docs and user guides.  We have a list of possible tasks that I could potentially get involved with.

**Comment by IanKWatts** [comment]
At this point, we don't more document work to do.
