### ISSUE TITLE
Document/plan 'how to get s3 bucket for teams'

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#4301]
**Describe the issue**

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [ ] plan/document created
- [ ] reviewed by Pilar

**Comment by caggles** [comment]
I have the contact information required to gather the necessary info for this doc. I'm just drafting their emails and then I need to wait for them to get back to me.
