### ISSUE TITLE
INC0085444  MCS SILVER nodes were deleted

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4326]
**Describe the issue**
During a routine disk resizing change, all SILVER nodes were accidentally deleted.

**Checklist**
- [x] Create an incident in theHUB
- [x] Contact the SPOC to elevate the INC to a P2
- [x] Post in [#devops-alerts](https://chat.developer.gov.bc.ca/channel/devops-alerts)
- [x] [Update](https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Status-Page.md) the [Status Page](https://status.developer.gov.bc.ca/)
- [x] --> Solve the issue <--
- [x] Post in [#devops-alerts](https://chat.developer.gov.bc.ca/channel/devops-alerts)
- [x] [Update](https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Status-Page.md) the [Status Page](https://status.developer.gov.bc.ca/)
- [x] Work with SPOC to complete the Outage Report

**Comment by StevenBarre** [comment]
OR completed
