### ISSUE TITLE
Improve cluster uptime monitoring

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4327]
**Describe the issue**
We had a cluster incidence on Silver where there cluster became unavailable and apps went down. However, this is not reflected in the readyz API endpoint, only cerberus captured that. Currently we are displaying the readyz monitor on status page, this is an issue as it doesn't accurately reflect the cluster status. While cerberus is a bit too sensitive with daily node drain activities, we could modify its check to fit better for uptime status purpose, and add it on the page.

**Definition of done**
- [x] Knowledge share on current setup with Ian
- [x] explore better options for cluster uptime monitoring
- [x] OR consider tuning cerberus to fit better
- [x] implement the solution
- [x] observe the new cerberus instance for a while (till next ccm push is completed)
- [x] add to public uptime.com status page
- [x] fix uptime.com Rocketchat webhook issue
- [x] resolve kyverno check racing issue

**Comment by IanKWatts** [comment]
* The kyverno check is updated to check for running pods.  We'll keep the existing ConfigMap check in there, too, for now.
* ArgoCD checks now exist for all instances and report pod failures to Rocketchat.
* The PV check is being re-tested.

**Comment by w8896699** [comment]
Cerberus will do pod status check instead of configmap check.

**Comment by w8896699** [comment]
Status page start using cerberus check again
