### ISSUE TITLE
Explore automatic email notification options from Uptime.com

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4328]
**Describe the issue**
There is a subscription feature for status pages on Uptime.com, ppl who subscribed will get notified when there are service downtime recorded on the page. However, the feature is disabled at the moment because we use Mautic as main communication method.

**Definition of done**
- [ ] consider the above options and make a decision
- [ ] explore email templating for different scenarios

**Comment by ShellyXueHan** [comment]
### Updates:
1. enable subscription feature:
Pros:
- user can self-register for the alerts based on the status page
- no additional work required
Cons:
- user can NOT select which events to send out email, they'll get notified on all activities from the status page
- we can NOT set an email template

2. webhook trigger from uptime.com to Mautic
Pros:
- we can use the same email distribution list as the critical update ones for each cluster
- we can set email templates
Cons:
- need to setup an automation service that does the triggering and compositing of the email

**Comment by StevenBarre** [comment]
Another Mautic con would be that it may be hosted on the impacted cluster and not working.

**Comment by ShellyXueHan** [comment]
agree! side note, we also need to migrate mautic to Gold and setup dr there!

**Comment by ShellyXueHan** [comment]
### Updates:
I've confirmed with uptime.com support on the status page subscription feature:
- there is no notification when a check fails on the status page, it'll only send out when we manually create an incidence or a maintenance window. -> *I'd suggest we not use it since it's a duplication effort of what our subscription service does.*
- the rest might not matter, but I'll just put it down here for reference.
  - we can customize the notification template
  - we cannot limit on the method of notification, that means once enabled, users can pick from email/text/RSS which we have no control on
  - once an incidence or maintenance window message has been created, it sends out the notification. but later updates on the same event will not trigger notification anymore.
