### ISSUE TITLE
Build a tool / github action to double check new node IPs aren't duplicates

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4336]
**Describe the issue**
When adding new nodes with dhcp stuff, we need to double check that we aren't adding duplicate IPs.
https://github.com/bcgov-c/rhcos-ignition-builder/pull/120

**What is the Value/Impact?**
Prevent duplicate IPs in DHCP config

**What is the plan? How will this get completed?**
Can we create a github action to lint PRs and alert if there are duplicate IPs in the inventory files

**Identify any dependencies**
None

**Definition of done**

- [x] Some way to detect duplicate IPs in inventory files before they go live.
- [x] Create documentation 
- [x] Deliver a techtalk on github actions

**Comment by StevenBarre** [comment]
Not sure how we'll be able to detect duplicates with IPs not listed in the INV files?

**Comment by vivekratan88** [comment]
https://blog.ktz.me/check-for-duplicate-items-in-a-list-with-ansible-using-a-custom-filter/

**Comment by tbaker1313** [comment]
In the inventory files, the ip addresses are in the line containing 'ip:' so we can extract that data and feed it to awk something like this:

```
grep -R "ip:" inventory/host_vars/* | awk -F ':' '{if($3 in x){if(x[$3]) print x[$3]; print;x[$3]=""} else x[$3]=$0}'
```

**Comment by tbaker1313** [comment]
Had to try another approach to this as the last effort didn't yield a working result on the first test. Added a new workflow to test and am attempting to determine why the second task isn't running the way I think it should.

**Comment by tbaker1313** [comment]
Created a new repo for testing https://github.com/tbaker1313/test-actions

**Comment by tbaker1313** [comment]
Closing and will open another ticket to refine the process and setup a possible block if this test doesn't complete successfully.
