### ISSUE TITLE
Double check all DHCP configs for duplicate IPs

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4337]
**Describe the issue**
We had an issue where a node had a duplicate IP as another node. Need to do a re-check of all nodes and IPs to ensure no duplicates.

**What is the Value/Impact?**
Cluster stability

**What is the plan? How will this get completed?**
Hack up some bash to check things

**Identify any dependencies**
None

**Definition of done**
- Confirm no duplicates in configs currently
- Confirm InfoBlox data matches reality

**Checklist**

- [x] CLAB PROD
- [x] CLAB MGT
- [x] CLAB storage
- [x] CLAB ONTAP

- [x] KLAB PROD
- [x] KLAB MGT
- [x] KLAB storage
- [x] KLAB ONTAP

~- [ ] KLAB2 PROD~
- [x] KLAB2 MGT
- [x] KLAB2 storage
- [x] KLAB2 ONTAP

- [x] SILVER PROD
- [x] SILVER MGT
- [x] SILVER storage
- [x] SILVER ONTAP

- [x] GOLD PROD
- [x] GOLD MGT
- [x] GOLD storage
- [x] GOLD ONTAP

- [x] GOLDDR PROD
- [x] GOLDDR MGT
- [x] GOLDDR storage
- [x] GOLDDR ONTAP

~- [ ] EMERALD PROD~
- [x] EMERALD MGT
- [x] EMERALD storage
- [x] EMERALD ONTAP

**Comment by tbaker1313** [comment]
CLAB Storage is a mess, lots of incorrect ip/names
CLAB ONTAP network space appears incorrect should be /24 in inventory

KLAB2 ONTAP may need reservations for it's reserved ip space

SILVER PROD nodes aren't always named correctly

GOLD storage is missing infoblox assignments

EMERALD may need reservations for it's reserved ip space

EMERALD AND KLAB2 bootstrap MGT is the same - EMERALD should probably be changed.

**Comment by tbaker1313** [comment]
Reserved all the IPs for EMERALD netapp.

**Comment by tbaker1313** [comment]
GOLD Storage has been updated and all ips are now reserved and using the desired names.

**Comment by tbaker1313** [comment]
KLAB2 storage has been updated with the desired reservations.

**Comment by tbaker1313** [comment]
Cleaned up the CLAB listings.
