### ISSUE TITLE
Rebuild DHCP health check for Openshift clusters to run cron inside single pod

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4348]
**Describe the issue**
Due to its need, we initially created a new health check to let us know if DHCP leases are close to expiry on any node in an Openshift cluster so we have proactive notice of an issue before it disrupts services in the cluster. This check worked, but came with its own management problems due to how it was implemented (a large number of concurrent cron pods ran each time the health check operates). By re-designing this check so that a single pod persists and handles the checks running cron services inside the pod should allow this health check to stand as well as improve reliability and stability of the check itself.

**Additional context**
Ticket related to the removal of the original DHCP check: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4347

**How does this benefit the users of our platform?**
Having reliable health checks that do not introduce technical or management issues on their own is most desired when looking after our Openshift clusters.

**Definition of done**
- [x] Work out the new solution in a new Github PR/branch.
- [x] Test the new solution in a LAB cluster (both NSX and regular Openshift).
- [x] Once ready, deploy across all Openshift clusters.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-tools/pull/180

**Comment by StevenBarre** [comment]
Deployed to all PROD clusters
