### ISSUE TITLE
Vault - market research on alternatives

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4358]
**Describe the issue**
Run a market research on secret management services to compare feature, service level and price.

**Definition of done**
- [x] market research
- [x] discuss with team

**Comment by IanKWatts** [comment]
Had a meeting with Akeyless this morning, which seems like a possible replacement.  Their solution is not entirely on-prem, so would need to get approval from a security standpoint.  We will look into Akeyless further.

**Comment by IanKWatts** [comment]
The on-prem thing is a barrier to adopting an alternative.  Summary of findings documented here:
https://github.com/bcgov-c/platform-services-docs/blob/main/vault/vault_alternatives.md
