### ISSUE TITLE
Investigate in how to self-fix Documize issue

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#438]
Background:
Documzie has a bug when user try to see protected content without login session.
However, no much attention/effort were given to take care of this issue so far from the Documize team.

Plan:
we will take a look into the code and see if it's feasible to fix it and have a custom build for now.

**Comment by mitovskaol** [comment]
@ShellyXueHan I wonder if upgrading Documize to the latest version would fix it?

**Comment by ShellyXueHan** [comment]
@mitovskaol shall we still invest time into documize since we are looking for alternative now?

**Comment by mitovskaol** [comment]
Lets close it for how, i really don't want to invest any more time in Documize as we will be retire it in the next 2-3 months
