### ISSUE TITLE
Add MISO requirement to the onboarding doc

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4384]
**Describe the issue**
Teams should talk to their MISO before reaching out to us for onboarding to the platform. We don't have a way to enforce this, but we can make it specific in the onboarding doc: https://digital.gov.bc.ca/cloud/services/private/onboard/

**Definition of done**
- [ ] Shelly work on the content
- [ ] Pilar review it and add to doc website

**Comment by Pilargit12** [comment]
https://docs.google.com/document/d/16QnsbATdmj_cmnhr1WCqvfHuTHVC7A8z_Gs_w5pvzbM/edit#heading=h.j7plbv2a0v4e
