### ISSUE TITLE
Weekly CCM PROD Push for November 7-9

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4388]
**Describe the issue**
This ticket will track efforts spent toward creating the next CCM release and promoting it against the three production Openshift clusters.

**Definition of done**
- [x] Create suitable GitHub Release before EOD Friday
- [x] Create suitable Standard Change RFCs and assign to team members as appropriate
- [x] Create and Receive approval for PR incrementing CCM version for PROD clusters
- [x] Ensure version increment PR is merged before executing any RFCs
- [x] Execute RFC for SILVER & EMERALD cluster
- [x] Execute RFC for GOLD cluster
- [x] Execute RFC for GOLDDR cluster

**Comment by wmhutchison** [comment]
Adding a note for EMERALD. Cluster-apps and Integration apps are paused on CCM, so make sure GitOps sees the new PR version after merging, and once done, unpause cluster-apps so that the updates to integration remain consistent and don't attempt a roll-back of Camel K.

**Comment by wmhutchison** [comment]
RHACS app in all PROD clusters this week will also be manually paused for allowing the PROD ACS RFC to complete. If all goes to plan, an older draft PR will be applied in CCM to formalize that during next week's CCM merge.

**Comment by StevenBarre** [comment]
Silver and Emerald applied

**Comment by tbaker1313** [comment]
Completed.
