### ISSUE TITLE
Vault Terraform migration

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4395]
**Describe the issue**
this is to implement the migration based on the explore ticket #4215, option 1 (migrating to public cloud and use s3 storage for the states) is the most preferred.

**Definition of done**
- [x] implement new state storage
- [x] test
- [x] push to prod

**Comment by ShellyXueHan** [comment]
#4215

**Comment by IanKWatts** [comment]
Labs and Prod migrated and tested
