### ISSUE TITLE
Critical Systems Doc review

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#4399]
**Describe the issue**
All critical systems docs need to be reviewed w/ the CITZ IMB security team.  A few docs will need to be updated due to changes since last security review.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [x] Update SoAR items in STRA system that have been completed
- [x] Update Defensible security spreadsheet based on current state
- [x] Update critical systems checklist spreadsheet based on current state
- [x] Upload docs to sharepoint site
- [x] Meet w/ CITZ IMB security team to discuss

**Comment by AvneetKahlon** [comment]
Reviewed with CITZ IMB. Updated BIA.
