### ISSUE TITLE
Apple account updates

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#44]
- Enable Push Notification with FCM
- Explore pricing model
- Discuss on process for similar requests

**Comment by jleach** [comment]
@ShellyXueHan This issue cleared up - do we still need it?

**Comment by ShellyXueHan** [comment]
Still need to discuss with Shea and Todd about the account management. Will close once that's done.

**Comment by ShellyXueHan** [comment]
@jleach please touch base with Shea on the account updates.

**Comment by ShellyXueHan** [comment]
@popkanjanakantorn we will need to reenter the payment method again, it didn't get pass.

**Comment by ShellyXueHan** [comment]
done. details tracked in documize.
