### ISSUE TITLE
LAB TLS cert expiring

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#441]
The TLS cert for `*.lab.pathfinder.gov.bc.ca` will expire on 2020-07-27. Will need an iStore to order a renewal.

**Comment by tosazuwa** [comment]
@sbarre-esit , can you send Pop an email with the details of what you need? He doesn't use ZenHub. Cc me also so I can follow up

**Comment by sbarre-esit** [comment]
iStore #1030281

**Comment by sbarre-esit** [comment]
iStore #1030695

**Comment by wmhutchison** [comment]
Per email from IMS on May 21st.

```
Good afternoon, IMS has received the iStore order for the SSL Certificate for the above URL.

You are listed as the technical contact.

Please submit CSR(s) to IMS@gov.bc.ca, we will then generate the Certificate for you.

Thanks
Tonja
```

**Comment by wmhutchison** [comment]
An RFC change ticket is currently penciled in for June 4th to perform the replacement.
