### ISSUE TITLE
Enable Pod security admission syncing for workloads in Openshift prefixed namespaces

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4419]
**Describe the issue**
From Openshift version 4.11 and onwards, AlertManager generates notices involving PodSecurityViolation  where a workload is starting up in a security context that it shouldn't. At present this is still allowing pods to start up regardless, but in the future, that will be changed.

Per discussed on the vendor link below, Openshift will disable pod security context syncing for any openshift-prefixed namespaces with the assumption that all of these belong to Openshift. This however is not the case for some of our namespaces as prefixed by `openshift-bcgov` which do need to have security context syncing enabled.

**Additional context**
Vendor link: <https://docs.openshift.com/container-platform/4.12/authentication/understanding-and-managing-pod-security-admission.html>

**Namespace checklist**
Check each namespace off as either CCM or a playbook is updated to reflect the additional annotation.
- [x] openshift-bcgov-avi
- [x] openshift-bcgov-cerberus
- [x] openshift-bcgov-crunchy
- [x] openshift-bcgov-encase
- [x] openshift-bcgov-entitlements
- [x] openshift-bcgov-etcd-backup
- [x] openshift-bcgov-f5cis
- [x] openshift-bcgov-gitops-shared
- [x] openshift-bcgov-grafana
- [x] openshift-bcgov-grafana-test
- [x] openshift-bcgov-image-registry-notifier
- [x] openshift-bcgov-integration
- [x] openshift-bcgov-lldpad
- [x] openshift-bcgov-nagios
- [x] openshift-bcgov-perfmon
- [x] openshift-bcgov-porter-operator
- [x] openshift-bcgov-pruner
- [x] openshift-bcgov-sysdig-agent
- [x] openshift-bcgov-trident
- [x] openshift-bcgov-vault
- [x] openshift-bcgov-vrops
- [x] openshift-bcgov-warden-operator

**Definition of done**
- [x] Manually work out all of the required changes to be done to namespaces.
- [x] Create PR's to ensure changes are applied to namespaces when created on new clusters and updated on existing clusters.
- [x] Confirm the AlertManager alert no longer is being produced.

**Comment by wmhutchison** [comment]
The following was ran against all namespaces prefixed with `openshift-bcgov` in both GOLD and GOLDDR where AlertManager was informing us about Pod security violation issues, done about two weeks ago.

```
oc label namespace <namespace> security.openshift.io/scc.podSecurityLabelSync=true
```

Will start enumerating all known `openshift-bcgov` namespaces in a checklist for this ticket, and start work on various PR's to get the above annotation added.

**Comment by wmhutchison** [comment]
Added a checklist to reflect all of the namespaces on all clusters involving openshift-bcgov.

**Comment by StevenBarre** [comment]
openshift-bcgov-nagios previously covered by https://github.com/bcgov-c/platform-tools/pull/149

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-ops/pull/472 covers

- openshift-bcgov-avi
- openshift-bcgov-f5cis
- openshift-bcgov-trident

**Comment by StevenBarre** [comment]
Emailed Cailey and Shelly about the vault namespace.

Merged the PRs. The CCM one will be applied in the new year.

All other namespaces labeled on all clusters. Moving to blocked until CCM and Vault are handled.

**Comment by StevenBarre** [comment]
Checked all clusters for the PodSecurityViolation alert and removed any silences.
