### ISSUE TITLE
OCP 4.13 Review Release Notes Epic

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4427]
**Describe the issue**
Have the team review the Release Notes for OCP 4.13 for any impacting or exciting changes that need to be communicated to the community.
https://docs.openshift.com/container-platform/4.13/release_notes/ocp-4-13-release-notes.html

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes they need to be aware of.

**What is the plan? How will this get completed?**
Have each team member review the Release Notes, then meet to discuss what they found and what needs to be communicated. Help Cailey create a slide for the community meetup, and an email via Mautic.

Notable changes from the release notes and CLAB test upgrade are the following:

**Changes that impact Developers:**

**Identify any dependencies**
Everyone needs to read the notes before the meeting can happen.

**Definition of done**
- [x] Community informed of upcoming changes to the clusters.

**Comment by tbaker1313** [comment]
Completed.
