### ISSUE TITLE
PRB0040369 - OpenShift NetApp Block volumes fail to format and mount sometimes

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#444]
PRB0040369 -> internal DXC problem ticket reference.

Working with both Red Hat and NetApp stakeholders to dig into issues involving NetApp block volumes either not mounting due to requiring a reformat, or otherwise just not mounting for other reasons.

**Comment by sbarre-esit** [comment]
Worked with Matt to do some more testing and reproduce. Looks like we've managed to narrow this down.

- When the last block PVC is removed from a host, it will logout of all NetApp LUNS
- When a new PVC lands on the host, it will login to the netapp and pull down the full list of luns ~200 currently
- When a PVC is deleted, the LUN is removed from the host where the pod was, but not other hosts that have pulled down the full list
- When a new PVC is created, it may reuse a LUN number
- If a PVC with a reused LUN lands on a host that already has that LUN from previously, funky things may happen such as the size being wrong or fsck issues

**Comment by sbarre-esit** [comment]
Updating PROD App nodes this week to have the iscsid fix that will prevent this.

**Comment by sbarre-esit** [comment]
Waiting on #467 to complete the rest of the nodes.

**Comment by mitovskaol** [comment]
Scheduled for execution on Sat June 13 (master + storage)
