### ISSUE TITLE
OCP 4.13 Test RH Integration upgrade in CLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4451]
**Describe the issue**
Work with AG to upgrade the RH Integration operators in CLAB and validate their app supports the new version

**What is the Value/Impact?**
Ensure a smooth upgrade in PROD

**What is the plan? How will this get completed?**
Find the latest version and release notes from https://access.redhat.com/documentation/en-us/red_hat_integration/ and review with AG.
Update the operators in CLAB
Verify with AG that the upgrade is safe for PROD

**Identify any dependencies**
AG

**Definition of done**
- [x] RH Integration upgraded in CLAB
- [x] Upgrade docs updated with any extra steps
- [x] Plans made for PROD upgrades

**Comment by tbaker1313** [comment]
Tested and no impact noted. Confirmed on Dec 12th.
