### ISSUE TITLE
Silver project cleanup

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4494]
**Describe the issue**
identify abandoned test projects, contact PO/TL to see if they still need the project. Maybe we can build automation that will look for abandoned projects (no traffic in the last 24 months) and check with the owner if the project is still relevant. 

**Note:** this will happen after resource reclaiming automation is done

**Definition of done**
- [x] script to identify projects (projects with one PO/TL, nothing deployed to prod)
- [x] communication to internal project contacts
- [x] communication to product team contacts

**Comment by lukegonis** [comment]
Waiting until the DXC team runs the clean up automation (Late Jan)

**Comment by ShellyXueHan** [comment]
### Update:
- scripts ready
- internal project clean up in progress: notification sent out, clean up will happen on March 11th
- community notification to be sent after internal project clean up complete in March

**Comment by ShellyXueHan** [comment]
- notification sent for silver
- internal namespaces cleaned up
