### ISSUE TITLE
SSO - turn off direct access grant for all Registry clients

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4495]
**Describe the issue**
SSO team has reached out asking to turn off `direct access grant` for Registry clients in the realm.

**Definition of done**
- [ ] discuss changes, update SSO team on timeline
- [ ] test out in lower environment
- [ ] push in changes

**Comment by okanji** [comment]
Re created this in the App dev board so am closing here.

**Comment by okanji** [comment]
Re created this in the App dev board so am closing here.
