### ISSUE TITLE
Update DXC Github network docs regarding Infoblox

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4507]
**Describe the issue**
Infoblox is an internal DXC tool used to track IP addresses. It is used very rarely by the Platform Operations team to the point that we often forget which login credentials it requires/etc. This ticket will track internal docs meant to remind us how to access Infoblox (URLs and credentials).

**Definition of done**
- [x] Create internal GitHub PR for the new documentation in DXC Github.
- [x]  Merge after PR is reviewed/approved.

**Comment by StevenBarre** [comment]
Add a note about CLAB storage vlan not being in Infoblox

**Comment by wmhutchison** [comment]
Moving onto this ticket now that Artifactory docs are in a state awaiting peer review/tweaks/etc.

**Comment by wmhutchison** [comment]
Moving onto this ticket now that Artifactory docs are in a state awaiting peer review/tweaks/etc.

**Comment by wmhutchison** [comment]
https://github.dxc.com/AdvSol/mcs-operations-manual/pull/23 created. While advertised as new documentation for Infoblox, the scope remains tied to this specific ticket thus the new markdown is not a tutorial on how to use Infoblox. That can be readily added later with further updates.

**Comment by wmhutchison** [comment]
After some minor changes, the team has signed off on the PR. Now merged.
