### ISSUE TITLE
Reduce Silver app node disk size

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4509]
**Describe the issue**
In an effort to save money, reducing the disks on 18 VM workers from 800G to 500G.

**What is the Value/Impact?**
Reduced costs

**What is the plan? How will this get completed?**
Create CHG and send notifications
Work with VMware team to rebuild the nodes with smaller disks

**Identify any dependencies**
- istore orders
- VMware team

**Definition of done**
- [x] RFC created and submitted for approval.
- [x] comms PR created for alerts channel.
- [x] confirm RFC and comms approval before posting comms in alerts.
- [x] execute approved RFC as scheduled.

**Comment by StevenBarre** [comment]
CHG0054814

**Comment by wmhutchison** [comment]
CHG0054814 created by Steven Barre, audited to confirm that all VM disk reductions now have associated REQ requests and said requests are on hold pending actual execution of the work. Sent approval request and updated CHG ticket state to match.

**Comment by wmhutchison** [comment]
https://github.com/BCDevOps/platform-services-status-page-notifications/pull/240 are the comms for posting in alerts channel once RFC approval is confirmed.

**Comment by wmhutchison** [comment]
Comms and RFC are approved, posted comms in alerts channel.

**Comment by wmhutchison** [comment]
First day of RFC, have completed 12 VMs in terms of node rebuild. Hoping to finish the rest off tomorrow.

**Comment by wmhutchison** [comment]
Work completed. Will close off RFC and this ticket tomorrow morning if no issues arise from this work.

**Comment by wmhutchison** [comment]
No issues detected from work, closing off RFC and this ticket, updated comms on alerts channel.
