### ISSUE TITLE
Increase Emerald node disk size

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4510]
**Describe the issue**
In an effort to align EMERALD disk size with other PROD systems, increase the worker VM sizes from 150GB to 500GB. Keep the existing 150GB node sizes for master/infra as-is.

**What is the plan? How will this get completed?**
Work with VMware team to resize the nodes. Note if it's not possible to resize the disk to make this happen, might need to research further and re-attempt under a separate RFC. Note that while VMWare do have disk resizing tickets for all the EMERALD nodes, only the worker nodes will require VMWare to "do something", as the tickets for masters/infras are already accurate on the system, it's just a billing adjustment that needs to happen.

**Identify any dependencies**
- istore orders
- VMware team

**Definition of done**
- [x] Confirm nodes are resized with VMWare assistance during EMERALD OCP upgrade RFC.

**Comment by wmhutchison** [comment]
Found the following article which should prove useful for re-sizing the EMERALD app nodes, will test it on one of the nodes before committing to the rest.

https://access.redhat.com/discussions/6230831

**Comment by wmhutchison** [comment]
Completed this today with the help of VMWare. Unfortunately just increasing the disk size itself wasn't enough to kick off an OS-level resize, even after VM reboot. Followed the recommendation in the above-mentioned discussion thread to complete the work without issue.

```
sudo su
growpart /dev/sda 4
sudo su -
unshare --mount
mount -o remount,rw /sysroot
xfs_growfs /sysroot
```
