### ISSUE TITLE
Reduce Gold DR app node disk size

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4511]
**Describe the issue**
In an effort to save money, reducing the disks on 8 VM workers from 800G to 500G.

**What is the Value/Impact?**
Reduced costs

**What is the plan? How will this get completed?**
Create CHG and send notifications
Work with VMware team to rebuild the nodes with smaller disks

**Identify any dependencies**
- istore orders
- VMware team

**Definition of done**
- [x] RFC created and submitted for approval.
- [x] comms PR created for alerts channel.
- [x] confirm RFC and comms approval before posting comms in alerts.
- [x] execute approved RFC as scheduled.

**Comment by StevenBarre** [comment]
CHG0054815

**Comment by wmhutchison** [comment]
Work on this started today, and barring anything else interfering, will be also likely completed by EOD today too.

**Comment by wmhutchison** [comment]
RFC completed and closed. Matching internal DXC tickets also received/updated/closed.
