### ISSUE TITLE
Build 6 new Gold app VMs

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4512]
**Describe the issue**
As more workload moves to Gold it is getting full. New OCP licenses are being ordered for Jan 1st. Add 6 new nodes to Gold to increase its capacity.

**What is the Value/Impact?**
Increased cluster capacity

**What is the plan? How will this get completed?**
https://github.com/bcgov-c/rhcos-ignition-builder#add-more-nodes-later

**Identify any dependencies**
- iStore needed
- VMware team to build the VMs

**Definition of done**
- [x] Create new PR for new GOLD nodes.
- [x] Review/QA/approve PR.
- [x] Build and QA new GOLD nodes off the PR.
- [x] Merge PR if no issues arose during build.
- [x] Create hand-over RFC once new GOLD nodes are live.

**Comment by wmhutchison** [comment]
DXCAS internal tickets for assigning IP addresses have dropped and been processed. Forwarding all of the VRA emails to the Platform Ops team.

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/rhcos-ignition-builder/pull/129 created and in draft for now while creation and QA of PR is in progress.

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/rhcos-ignition-builder/pull/129 created and in draft for now while creation and QA of PR is in progress.

**Comment by wmhutchison** [comment]
PR reviewed/approved/merged. Have generated updated dhcp and tftp content on GOLD-UTIL, will be able to jump right into bootstrapping up all the VMs first thing Thursday morning, and have all built/QA/handed over via RFC before EOD Thursday.

**Comment by wmhutchison** [comment]
Ran into some initial issues doing a build, but that was due to repo having committed to OCP 4.13 values while GOLD is not yet on 4.13, thus resulting in a node build that couldn't join the cluster because of this mis-match. Fixed this up locally versus official commit since it's extremely doubtful any new node builds will be required for GOLD before GOLD gets its OCP 4.13 face-lift. Node builds/QA now in progress.

**Comment by wmhutchison** [comment]
Another issue came up during hand-over, where F5 Network detected an IP conflict that was not being tracked correctly in the system responsible for assigning new IPs. Have addressed and fixed this up for GOLD and created a new ticket in Sprint Backlog to audit the remaining Openshift clusters to ensure that any new nodes created will not show a similar problem.

Nodes now in operation, hand-over RFC created. Closing ticket.
