### ISSUE TITLE
SDN - Create Custom monitor for AKO pod status

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4518]
**Describe the issue**
In response to a recent issue where AVI (the VMWare service responsible for managing router/service entries between Openshift and NSX) was overloaded and had to restart, we had scaled down the KLAB2 AKO pods over-night while the AKO pods in EMERALD were restarted at the time.

The take-away from this event was that nothing that was alert-worthy for on-call was generated at all, when this should be the case if this were to happen in EMERALD. This ticket thus will track the creation of a custom monitor for the AKO pods and for a PROD cluster like EMERALD, notify on-call so that possible issues can be proactively brought to our attention versus finding out solely by being notified by users of the platforms in question.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**
Proactive monitoring is best to ensure smooth operations. Users would only notice an issue for this scenario during the modification of state for a route or service resource.

**Definition of done**
- [x] Investigate the best solution for this custom check (Nagios or AlertManager/Prometheus evaluation)
- [x] Implement the solution, test in KLAB2.
- [ ] Implement the solution in EMERALD once tested and finalized.

**Comment by wmhutchison** [comment]
If there's a need to check out any custom prometheus queries to see if they'll do the desired job, here's how to manually scale down AKO entirely on KLAB2:

```
oc -n openshift-bcgov-avi scale sts/ako --replicas=0
```

And to put it back:

```
oc -n openshift-bcgov-avi scale sts/ako --replicas=2
```
Only do the scale-down for testing when you're ready to do so. For a short period of time, scaling AKO down doesn't break anything, but that changes as pod churn takes place on the cluster, since AKO isn't updating AVI with the new details.

**Comment by wmhutchison** [comment]
If there's a need to check out any custom prometheus queries to see if they'll do the desired job, here's how to manually scale down AKO entirely on KLAB2:

```
oc -n openshift-bcgov-avi scale sts/ako --replicas=0
```

And to put it back:

```
oc -n openshift-bcgov-avi scale sts/ako --replicas=2
```
Only do the scale-down for testing when you're ready to do so. For a short period of time, scaling AKO down doesn't break anything, but that changes as pod churn takes place on the cluster, since AKO isn't updating AVI with the new details.

**Comment by tbaker1313** [comment]
AKO pod status check
https://docs.openshift.com/container-platform/4.13/observability/monitoring/managing-alerts.html#creating-alerting-rules-for-user-defined-projects_managing-alerts

https://github.com/bcgov-c/platform-gitops-gen/blob/master/roles/kyverno/files/prometheusrule.advsol-alert-rules.yaml

Create prometheus rule to detect the number of AKO pods

**Comment by tbaker1313** [comment]
Added a PR https://github.com/bcgov-c/platform-ops/pull/493

**Comment by tbaker1313** [comment]
Completed.
