### ISSUE TITLE
An announcement about changes in UI Registry

### ISSUE THREAD

**Issue by funtigr** [BCDevOps/developer-experience#4528]
**Description**:
Our team (App Development) is working on a new UI for the Registry App. We are planning to go live in mid January. It will be just a switch to the new UI, probably without demoing it.
So we were thinking of making an announcement. All the functionality will be the same, only visual elements will change, according to ones created for us by a Service Designer. All the data - products, users and request history will be left in place as we use the same database.
We see it as an Email and a Rocket Chat channel announcement.

1. The objective is to warn people about upcoming changes in the interface. Regular users may become baffled if they are not expecting for positions of some interactive elements to change. 
2. Actionable Items: Not the obligatory or crucial ones, but we would like to ask them to give us feedback. Either in the Rocket Channels or in the letters to our email: platformservicesteam@gov.bc.ca  
3. No particular highlights. Maybe more modern interface, minimalistic look.
4. We are planning to go live after the holidays, most probably in January.

**Comment by Pilargit12** [comment]
**E-mail format**

**Subject: Exciting News: Platform Product Registry - Update coming soon!**

Dear Cloud services community, 

I hope this email finds you well. We're happy to share some exciting news with you—there's an upcoming update to the [Platform Product Registry ](https://digital.gov.bc.ca/cloud/services/private/products-tools/registry/)user interface!

**What to expect:**
Starting mid-January 2024, you'll notice a fresh new look for the Platform Product Registry. The update focuses on enhancing visual elements while keeping the functionality of the program (products, user profiles, request history) unchanged. Rest assured, your data will remain intact.

**Why the change:**
We believe in staying ahead of the curve, and our goal with this update is to provide you with a more modern and minimalistic interface. We're confident that the refreshed design will improve your overall user experience.

**Your input matters:**
We value your opinion, and we're eager to hear what you think about the updated UI. If you have any feedback, suggestions, or thoughts, please feel free to reach out to us at platformservicesteam@gov.bc.ca and Rocket.Chat channels. Your insights are essential in helping us refine and enhance the  Platform Product Registry further.

**Preparing for the transition:**
We understand that change can be surprising. To ease the transition, we wanted to give you a heads up so you can navigate the updated interface with confidence.

Thank you for being a valued member of the Cloud services community. We appreciate your continued support, and we're committed to delivering an app with useful improvements for you!

Best regards,

**Comment by Pilargit12** [comment]
**Rocket.Chat format**

Subject: Exciting News: Platform Product Registry gets a makeover! 🚀

Hi Cloud services community! 👋

Guess what? Brace yourselves for an exciting update for the Platform Product Registry mid-January 2024! 🌈

**What's changing**
We're upgrading some of the visuals, but the good stuff—products, profiles, request history—stays the same, the update focuses on a visual refinement. Just a fresh look for a fresh year! 

**The purpose**
We aim to enhance the overall aesthetics of the app. The upcoming changes bring a modern and minimalist design to ensure a seamless and visually appealing user experience. 🌟

**We want your thoughts**
Send us a message at PlatformServicesTeam@gov.bc.ca with your feedback or through Rocket.chat channel **[add link to appropriate Rocke.Chat channel please]** . Your thoughts shape our game, and we're all ears!

**Ready for the change**
Change is good, right? Prepare for a more modern and minimalistic interface. Same app, just looking sharper! 

Thanks for being part of the Cloud services community! ⭐️

Cheers,

Platform services team 🎉

**Comment by Pilargit12** [comment]
Hi @funtigr ! 

Please let me know what you think, you can see both formats above and also I added a comment for you to add the appropriate link to the rocket.chat channel where you wish to direct the feedback from community members. 

Happy to help! 

Pilar

**Comment by funtigr** [comment]
Thanks a lot!
We will look at the announcements with the team but looks good to me!
