### ISSUE TITLE
Sysdig - reduce unused metrics

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4530]
**Describe the issue**
We are way over the `custom metrics` limit on sysdig. Recently they built a panel called `Dashboard Manager` which we can use to check the number of time series per metrics. There are some we identified already that are good to be disabled (no used / alternatives available). But we are still over the limit.

**Definition of done**
- [ ] go through all metrics above 5K, list the ones that are not needed

**Comment by w8896699** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e708012742b26f17249531756b238f345590bf70/Screen%20Shot%202024-03-13%20at%208.58.24%20AM.png" alt="Screen Shot 2024-03-13 at 8.58.24 AM.png" />
