### ISSUE TITLE
Assess automating updating the contacts in the user alertmanager settings

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4532]
**Describe the issue**
Currently, in our PROD clusters there's an AlertmanagerConfig object, this was discovered to be user configurable in SILVER but not in  GOLDDR. We should look into automating this so it updates the contacts on a regular schedule.

**How does this benefit the users of our platform?**
Alerts end up going to the correct people instead of the ones that were configured when the playbook was first run.

**Definition of done**

- [x] Contacts automatically update in the AlertmanagerConfig

**Comment by IanKWatts** [comment]
This is basically done.  Just need to know for which clusters to create the AlertManagerConfig resources.  Currently just set for Gold.

**Comment by IanKWatts** [comment]
Although they have the same version of the GitOps Operator installed, Gold and GoldDR do not have the same Role that is used by ArgoCD.  Among other things, the Role `openshift-gitops-argocd-application-controller` in GoldDR does not have permissions to manage AlertManagerConfigs.  This will prevent ArgoCD from managing those resources, so I won't update the provisioner for GoldDR just yet.
Any idea why that Role would be different?  It's supposed to be managed by the operator.

**Comment by IanKWatts** [comment]
Looks like 4 of 7 clusters have references to AlertManagerConfigs in that role: CLAB, KLAB, Silver, and Gold
The clusters that do not have it are GoldDR, Emerald, and KLAB2
Sounds like a configuration option in the alert manager?

**Comment by IanKWatts** [comment]
@StevenBarre could you have a look at the comments above and let me know what you think?

**Comment by StevenBarre** [comment]
I've opened https://access.redhat.com/support/cases/#/case/03701553 to figure out why some clusters have rbac for namespace admins and some don't.

**Comment by StevenBarre** [comment]
```console
$ oc --as=system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller auth can-i --list --namespace=openshift-gitops | grep monitoring
*.monitoring.coreos.com                                                []                                    []                                                                       [*]
```

On Gold DR it should have access to the `alertmanagerconfigs.monitoring.coreos.com` objects. It looks like the other clusters may have some cluster roles, that are then aggregated to namespace admin/edit/view roles that grant more access than should exist due to them being older installs. This will likely need to be cleaned up, taking away permissions from teams without it being explicitly granted to them.

**Comment by StevenBarre** [comment]
This will be handled by https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4583

https://github.com/bcgov-c/platform-gitops-gen/pull/796 will grant the correct permissions to teams, then the old clusterroles can be removed in Silver
