### ISSUE TITLE
AlertManagerConfig automated updates

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#4533]
**Describe the issue**
Cluster alerts are sent to teams based on the contact info in AlertManagerConfigs.  These were initially generated using contact info from namespace annotations, but are not being automatically updated when contact info is changed for a project.  Implement a system for the automated management of these resources.

**What is the Value/Impact?**
Keep contact information up to date so project teams receive their alerts.

**What is the plan? How will this get completed?**
Incorporate this into the provisioner and add a YAML manifest for the AlertManagerConfig in the namespaces repo.

**Identify any dependencies**
n/a

**Definition of done**
- [x] app-provisioner image has been updated to create the manifest and add it to the namespaces repo
- [x] successfully tested in a lab cluster
- [x] implemented for all clusters

**Comment by StevenBarre** [comment]
The one-off playbook that was used is here, if you want to steal any code/yaml from it https://github.com/bcgov-c/platform-tools/pull/164/files

**Comment by IanKWatts** [comment]
Closing this issue as it was completed a while ago.
