### ISSUE TITLE
Due Feb 29th - TLS cert renewal for LAB clusters

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4542]
**Describe the issue**
Need to renew the TLS certs for the lab clusters before they expire.

- [x] `api.clab.devops.gov.bc.ca`
- [x] `*.apps.clab.devops.gov.bc.ca`
- [x] `api.klab.devops.gov.bc.ca`
- [x] `*.apps.klab.devops.gov.bc.ca`
- [x] `api.klab2.devops.gov.bc.ca`
- [x] `*.apps.klab2.devops.gov.bc.ca`

iStore Order for: 
Date Submitted:
iStore Number:
Lead time (business days after EA Approves):

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [x] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by Iryna-Kaplun** [comment]
Catherine Liu submitted MySC orders for these 6 certs on Feb 5, 2024.

**Comment by wmhutchison** [comment]
All ordered replacement certificates have been successfully installed in the LAB clusters (KLAB, CLAB, KLAB2).
