### ISSUE TITLE
Update TLS certs in CLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4544]
**Describe the issue**
Update the API and Apps wildcard cert before the current ones expire.

**What is the Value/Impact?**
Cluster needs non-expired certs to keep functioning.

**What is the plan? How will this get completed?**
https://github.com/bcgov-c/platform-ops/blob/main/roles/config-api/README.md

**Identify any dependencies**
iStore for new cert

**Definition of done**
New certs installed

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/platform-ops/pull/480 in Draft. Will test applying this branch in CLAB next week, and if successful, allow PR to be reviewed/approved/merged.

**Comment by wmhutchison** [comment]
PR approved/merged, closing ticket.
