### ISSUE TITLE
Update TLS certs in KLAB2

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4546]
**Describe the issue**
Update the API and Apps wildcard cert before the current ones expire.

**What is the Value/Impact?**
Cluster needs non-expired certs to keep functioning.

**What is the plan? How will this get completed?**
https://github.com/bcgov-c/platform-ops/blob/main/roles/config-api/README.md

**Identify any dependencies**
iStore for new cert

**Definition of done**
New certs installed

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/platform-ops/pull/478 in Draft. Will test applying this branch in KLAB2 next week, and if successful, allow PR to be reviewed/approved/merged.

**Comment by wmhutchison** [comment]
Performed QA of PR created last week. Applied relevant playbooks against PR and confirmed certificates were installed. Promoted PR from Draft for approval.

**Comment by wmhutchison** [comment]
PR approved/merged, closing ticket.
