### ISSUE TITLE
Update TLS certs in SILVER

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4547]
**Describe the issue**
Update the API and Apps wildcard cert before the current ones expire.

**What is the Value/Impact?**
Cluster needs non-expired certs to keep functioning.

**What is the plan? How will this get completed?**
https://github.com/bcgov-c/platform-ops/blob/main/roles/config-api/README.md

**Identify any dependencies**
iStore for new cert

**Definition of done**
New certs installed

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/platform-ops/pull/483 has the new certs.

**Comment by wmhutchison** [comment]
CHG0057394 created/scheduled for 6am on March 12th. Comms for all PROD cluster cert updates will be posted once all three RFCs are approved.

**Comment by StevenBarre** [comment]
New TLS certs installed
