### ISSUE TITLE
Update TLS certs in EMERALD

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4550]
**Describe the issue**
Update the API and Apps wildcard cert before the current ones expire.

**What is the Value/Impact?**
Cluster needs non-expired certs to keep functioning.

**What is the plan? How will this get completed?**
https://github.com/bcgov-c/platform-ops/blob/main/roles/config-api/README.md

**Identify any dependencies**
iStore for new cert

**Definition of done**
New certs installed

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/platform-ops/pull/484 has the new certs. Internal QA has passed, and plan on installing these the morning of March 5th while EMERALD OCP upgrade RFC is in play. Once installed successfully, will update notes on the PR and promote for review/approval.

**Comment by wmhutchison** [comment]
https://github.com/bcgov-c/platform-ops/pull/484 has the new certs. Internal QA has passed, and plan on installing these the morning of March 5th while EMERALD OCP upgrade RFC is in play. Once installed successfully, will update notes on the PR and promote for review/approval.

**Comment by wmhutchison** [comment]
Certificates were successfully installed during the existing EMERALD Openshift upgrade RFC (CHG0056994). Reply-all'd to the emails from ISB so they know the certificates are installed and thus can close their tickets for this.
