### ISSUE TITLE
Calculate the total number of default-size projects that can fit on production clusters

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#4552]
As part of the cost recovery model development, we need to know how many XS-sized (default sized) projects can fit into all production clusters - Silver, Gold and Emerald.

Suggested approach: sum up the total CPU powers of all 3 production clusters and divide by the CPU cores included in the default quota for new projects.

**Comment by StevenBarre** [comment]
Had a meeting and discussed the spreadsheet I'd created. Will need to make some more changes.

**Comment by StevenBarre** [comment]
Updated spreadsheet provided to Olena.
