### ISSUE TITLE
Review and update content related to security and privacy (Digital and Tech docs sites) 

### ISSUE THREAD

**Issue by Pilargit12** [BCDevOps/developer-experience#4554]
**Describe the issue**
Update and review content related to security and privacy 

**Additional context**
Maintenance of important changes of information related to those subjects is needed

**How does this benefit the users of our platform?**
Trustworthiness and having up to date information is necessary for our users security and safety of their applications

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

- [x] Meeting with Nick and Blake to identify what content needs to be updated
- [x] Obtain new content material and identify home for the content
- [x] Draft changes and review them 
- [ ] Publish updated materials

**Comment by NickCorcoran** [comment]
Had a discussion with Blake and Avneet re: content.
Planning the following:
- Draft a separate section/page for Privacy
- Draw out STRAs are part of a security assessment (same for PIAs in privacy section)
- Draft a separate section/page for Information Classification as it can apply to either (or both) security and privacy
         - Privacy section - change heading to Info Classification - talk about classifications, personal and confidential. Break out

- Add Linkages from sections to IMIT standards for sections that have a direct linkage

**Comment by NickCorcoran** [comment]
Created new page in new branch for Privacy Compliance and Guidance content:
https://github.com/bcgov/platform-developer-docs/blob/Security-Privacy-updates-JanFeb2024/src/docs/security-and-privacy-compliance/privacy-compliance-and-guidance.md

**Comment by NickCorcoran** [comment]
Considering breaking out content in Security Considerations page into the following separate pages:
- Platform security compliance
- Platform security tools
- Platform application security best practices

**Comment by NickCorcoran** [comment]
Just need to do secondary review myself and get someone else to look at as well.  Should complete this week.

**Comment by NickCorcoran** [comment]
I have reviewed content and asked Avneet to take a final look before merge.
