### ISSUE TITLE
SSO changes - turn off ACS offline sessions

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4555]
**Describe the issue**
SSO team has asked us to turn off ACS offline sessions.

**Definition of done**
- [x] discuss the change
- [x] test in lab
- [x] push changed in prod

**Comment by NickCorcoran** [comment]
This seems to have gotten lost due to no security tag.  Will look into this next sprint.

**Comment by NickCorcoran** [comment]
<img width="666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjFEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b41d2a0a29f2c3ed29e2dbe37bcdaf8fb20b00f/image.png" alt="image.png" />
Set to On in Lab.

**Comment by NickCorcoran** [comment]
To test out today and if all good to enable on prod ACS client tomorrow.

**Comment by NickCorcoran** [comment]
Change made to Prod on 29 Aug.
