### ISSUE TITLE
Broken link: OpenShift project resource quotas

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#4559]
Broken link on the page : https://docs.developer.gov.bc.ca/openshift-project-resource-quotas/

The link to 'Request a quota increase for an OpenShift project set' in 'related links' at the bottom of the page is circular and returns to the same page. 

The link for 'Request a quota increase for an OpenShift project set' should direct to the page found at https://docs.developer.gov.bc.ca/request-quota-increase-for-openshift-project-set/

**Comment by Pilargit12** [comment]
https://github.com/bcgov/platform-developer-docs/pull/216 - for revision of dead links and general updates
