### ISSUE TITLE
Update information on Hosting tiers on digital.gov.bc.ca 

### ISSUE THREAD

**Issue by Pilargit12** [BCDevOps/developer-experience#4574]
**Describe the issue**
Provide clear content regarding our hosting tiers please see suggestions under additional content 

**Additional context**
We received feedback in the Meetup Community chat that it would be helpful to have the following info added/made easier to understand on the page: https://digital.gov.bc.ca/cloud/services/private/products-tools/hosting-tiers/ 

* Include summary table that clearly differentiates why/where/what is different about each OCP edition; possible attributes including:

- [x] target uptime (availability)
- [x] maximum payload/data Security Classification the platform certified to host
integrated HA, DR options
- [x] underlying release plan, i.e. receives RedHat regular or EUS releases
- [x] slate of supported operators
- [x] upper limit of scalability: compute, storage, network
- [x] options for secure interoperability with other hosting services: STMS-Classic, VM-SDN (on-prem ESX VMs using NSX SDN), AWS, Azure, GCP, OCI

**How does this benefit the users of our platform?**
It provides more information to our clients, we also wish to include information based on their direct feedback and continue to build that relationship and trust 

**Definition of done**
Published information online and make the update available in our community channels

**Comment by Pilargit12** [comment]
Google doc: https://docs.google.com/document/d/12Z38eo7e_NmS-oc7zFdt_eEldIUPQu4GekJJgfk7Mxk/edit

**Comment by StevenBarre** [comment]
Had a call with @Pilargit12 to discuss. Filled out as much of the table as I know, and asked Olena for clarification on the scalability bit.

**Comment by Pilargit12** [comment]
The website https://digital.gov.bc.ca/cloud/services/private/products-tools/hosting-tiers/ includes a link to the new private technical docs page: https://docs.developer.gov.bc.ca/hosting-tiers-table/ where a table comparison among all hosting tiers is ready to be reviewed by those looking for further information on each.
