### ISSUE TITLE
Update Artifactory documentation

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#4591]
Alongside the Artifactory migration in Gold, some of the documentation in Artifactory needs to be updated in order to reflect some of the minor changes in functionality and process that comes with disaster recovery. I also would like to take this opportunity to reorganize the docs a little, to better reflect the actual workflow that users follow so that they have an easier time navigating the docs in a useful order.

**Comment by Pilargit12** [comment]
PR https://github.com/bcgov/platform-developer-docs/pull/218
