### ISSUE TITLE
Add docs for resource reclaimer

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4595]
**Describe the issue**
Document the new cronjob that scales down old or broken deployments.

**What is the Value/Impact?**
Better access to knowledge for app teams

**What is the plan? How will this get completed?**
Get advice from Matt on where best to put it. Write draft. Get it reviewed and published.

**Identify any dependencies**
Matt

**Definition of done**
Published doc

**Comment by mtspn** [comment]
Adding Pilar for visibility, we'll be in touch when there is draft for your review.

**Comment by StevenBarre** [comment]
Let's add a new page under `Platform architecture reference` to cover automation that's run on the platform. We'll start with a section on this resource tool, and later add sections for the AlertManager configs that sends alerts and the image registry storage emails.

**Comment by mtspn** [comment]
Draft PR here: https://github.com/bcgov/platform-developer-docs/pull/219

**Comment by StevenBarre** [comment]
https://docs.developer.gov.bc.ca/platform-automation/
