### ISSUE TITLE
Emerald wordpress page update 

### ISSUE THREAD

**Issue by Pilargit12** [BCDevOps/developer-experience#4605]
**Describe the issue**
Received an email from the content design team about a potential update in content due to received feedback from Glenn Mahoney: 

"The following content describes some key elements of the network topology of OpenShift Silver and Gold, required to enable interoperability with the rest of Government’s systems&infrastructure:
https://digital.gov.bc.ca/cloud/services/private/internal-resources/topology/
Missing from that is a description of Emerald"

**Additional context**
Contacted Steven Barre, he will be able to help edit the current content as a Subject Matter Expert (SME) also Glenn provided this link that adds more additional context to this need:

https://chat.developer.gov.bc.ca/channel/nsx-early-adopters/thread/QjYxcvCAYnfjWgPsZ

**How does this benefit the users of our platform?**
Provide a more accurate description of Emerald for our client's use

**Definition of done**
The web content will be updated, reviewed by Pilar and approved by the DO.ContentDesign@gov.bc.ca team and will be published once that is all done and finally advising Glenn of the update too.

**Comment by StevenBarre** [comment]
Content emailed to Pilar
