### ISSUE TITLE
SDN - Update all nodes with passwords for core user

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4606]
SDN - Update all nodes with passwords for core user

**Describe the issue**
~~Add a password to all nodes for the core user and record the new password in Keepass. This ticket is specific to nodes belonging to NSX-backed Openshift clusters such as KLAB2 and EMERALD which will have different instructions than what is used for KLAB/CLAB/SILVER/GOLD/GOLDDR due to the differing versions of Openshift.~~
Now that KLAB2 and EMERALD are moving to OCP 4.14, the machineconfig role for regular Openshift will work there as well.

**Additional context**
More information at <https://access.redhat.com/solutions/7010657>

**Definition of done**
- [x] Update KLAB2. Confirm there are no issues.
- [x] Update EMERALD.

**Comment by StevenBarre** [comment]
Much less easy to do this in 4.12. May just wait until NSX clusters are upgraded to 4.14.

**Comment by StevenBarre** [comment]
Tested in KLAB2

**Comment by StevenBarre** [comment]
Tested in Emerald
