### ISSUE TITLE
Vault - operation token

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4612]
**Describe the issue**
an operation token is needed for vault DR failover. The token has to be generated from the primary cluster. We need to have the token ready in the case of the cluster failover to Golddr (clab). Due to the 32 days max TTL config from vault, we cannot generate a token longer than that. Thus we need to create a cronjob to periodically refresh the token and save it somewhere we can access.

requirements for the cronjob:
- a token that can generate operation token (at the moment, the root token is used)
- access to run Vault commands
- secure place to save the operation token, also accessible by platteam
  - save in Azure key vault, which will require an Azure client that can read+write secret
  - save in S3 object storage (need to check with Nick on details)

**Definition of done**
- [x] discussion
- [x] implementation

Note: KT with the DXC team has been put in #4718

**Comment by IanKWatts** [comment]
I think operation tokens can be renewed.  Might be able to do it like this:
https://developer.hashicorp.com/vault/docs/commands/token/renew

**Comment by IanKWatts** [comment]
CronJobs have been created in each primary instance (Gold and KLAB).  Operation tokens are created and stored in an OpenShift Secret in both the primary and secondary clusters.
