### ISSUE TITLE
Pen test monitoring and issue resolution

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#4625]
**Describe the issue**
As pen test takes place there are sometimes technical or access issues that come up.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [x] Monitor progress
- [x] Check in meetings
- [x] Close out activities (access revocation)

**Comment by AvneetKahlon** [comment]
Got pentest report.
