### ISSUE TITLE
Review OpenShift master and node journal logs for errors

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#463]
Red Hat recommends we review the logs for `error` and ensure we understand all the logs and make cases if we see anything off to investigate.

**Comment by wmhutchison** [comment]
Taking a look at nodes, first item that a Red Hat case will be opened about:

```
atomic-openshift-node kubelet_volumes.go:140] Orphaned pod <redacted> found, but volume paths are still present on disk : There were a total of 3 errors similar to this. Turn up verbosity to see them.
```

This is appearing on one of our newest app nodes, so is not an old artifact dating back some time.

**Comment by mitovskaol** [comment]
Right now log monitoring is done manually on a regular basis, tickets are open with RedHat when erorrs are found. Long term we are looking to create an automated monitoring solution, this work will be tracked in a separate ticket.
