### ISSUE TITLE
Privacy/Data info for using Zenhub

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#4639]
**Describe the issue**

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [x] summary/one pager
- [x] wording for banner

**Comment by bspeersbcgov** [comment]
Drafts of each have been completed, though it wasn't possible to shorten to just one page (the current draft is 1.5 pages). I will take on any recommended edits.

I'm attaching the draft to this ticket and have also sent it via email.

I will check off the two "definition of done" entries once a final version of each is complete (with any recommended edits of these drafts).

Thanks!

-Blake[Zenhub - Privacy Guidance doc.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnFiQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a825844ec2bb128a91eee38af4c9b7e5686c22b/Zenhub%20-%20Privacy%20Guidance%20doc.docx)

**Comment by bspeersbcgov** [comment]
Closed as complete.
