### ISSUE TITLE
Decomission the old KLAB util server

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4653]
**Describe the issue**
The new RHEL 9 KLAB util server is in place. Decomm the old one.

**What is the Value/Impact?**
Keeping util servers current

**What is the plan? How will this get completed?**
Get an istore order to decomm and work with Linux team to complete a "scream test" and finally remove the server.

**Identify any dependencies**
Linux team, and istore submitter

**Definition of done**
Old server decommed

**Comment by tbaker1313** [comment]
old records removed and server deleted.
