### ISSUE TITLE
2020 Q2 Patching schedule

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#467]
MCS LAB OS patching - RFC 194028 - CITZ - Standard Change #33 MCS LAB - MCS OS Patching to LAB - May 25-29 2020 - COMPLETE
MCS PROD OS patching -  RFC 194163 - CITZ - Standard Change #33 MCS PROD - MCS OS Patching to PROD - June 13-19 2020 - pending

**Comment by wmhutchison** [comment]
The last maintenance activity for this quarter (PROD OS patching) is in line to be executed without being blocked, starting Saturday June 13th.

If the current RFC is not sufficient to complete all of the node patching, then a new standard-change RFC will be created to complete the work before the end of this month (which also is the end of Q2).

**Comment by wmhutchison** [comment]
PROD OS patching is ongoing, and there's a reasonable chance this will need to continue the following week. Almost finished OS patching, but firmware patching for specifically the Gen10 hardware has been particularly problematic this week. A case with HPE Support is open on the matter, and a "Plan B" in the form of downloading the SPP ISO is underway too.

**Comment by wmhutchison** [comment]
currently creating additional RFCs to cover off some of the various ministry VMs means to act as proxy between Aporeto and Openshift. While that solution is on hold for now, we (DXC AS) are mandated to continue applying quarterly patches until the servers in question are officially decommissioned.

**Comment by wmhutchison** [comment]
PROD OS patching is almost 100% complete as well - OS patching was finished Friday last week (June 26th) - we're finishing off the associated firmware patching this week.

**Comment by wmhutchison** [comment]
This is 100% complete - firmware has been upgraded as well. Closing ticket.
