### ISSUE TITLE
Test Sysdig Teams operator in Emerald

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4670]
**Describe the issue**
Ensure the Sysdig Teams operator is working in the NSX clusters

**What is the Value/Impact?**
Allow product teams to use the Sysdig Teams operator to set up dashboards in Sysdig

**What is the plan? How will this get completed?**
- Ensure operator is installed in clusters
- Ensure needed proxy config is working
- Test and confirm its working
- Let tenants know its working

**Identify any dependencies**
- Need an iStore to adjust the forward proxy

**Definition of done**
Working Sysdig Teams operator

**Comment by StevenBarre** [comment]
Target implementation date Mar 25th

**Comment by StevenBarre** [comment]
Forward proxy updated. Operator is still failing however. Asked Billy to investigate.

**Comment by w8896699** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/838 will fix the issue. Tested with project e595b8

**Comment by w8896699** [comment]
Tested in emerlad, Close ticket
