### ISSUE TITLE
Add implementation date to doc for Alertmanager in Silver/Emerald

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4711]
**Describe the issue**
Update https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-automation/alertmanager/

> Silver and Emerald cluster timeline
> Beginning March 20, 2024 these alerts are sent out to Product Owners and Technical Leads.

**What is the Value/Impact?**
Update with the date that Silver and Emerald were implemented

**What is the plan? How will this get completed?**
What are the key components of this task?

**Identify any dependencies**
Internal, external, who to contact in case of absence, person to refer to for further help.

**Definition of done**
Doc updated and published

**Comment by Pilargit12** [comment]
Working through this update included in https://github.com/bcgov/platform-developer-docs/pull/232
