### ISSUE TITLE
Jenkins Optimization

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#472]
Based on dashboard results, we can get some headroom by reducing jenkins cpu requests;

- [x] Create dashboard of Jenkins usage
- [x] Test Jenkins startup time with various configurations
- [x] Write up report on utilization
- [x] Write up recommendations in devhub for Jenkins resource configurations
- [x] Send note to teams around results

This is all about reducing load on OCP3; source ticket here: https://github.com/BCDevOps/OpenShift4-RollOut/issues/201

**Comment by stewartshea** [comment]
Added this PR for the test playbook that has been used to gather startup statistics. 
https://github.com/BCDevOps/platform-services/pull/690

**Comment by stewartshea** [comment]
Initial guesstimate is that we can reduce by over 100 cores on the request side of things. I'm starting to write up the report details and recommendations.

**Comment by stewartshea** [comment]
https://github.com/BCDevOps/developer-experience/pull/496 is related to the devhub content

**Comment by lukegonis** [comment]
@stewartshea can you please provide an update on this?

**Comment by stewartshea** [comment]
Everything from my side has been completed on this task @lukegonis 

I would suggest that possible we discuss the last item with @mitovskaol about sending a note to teams about reducing their Jenkins configurations per the docs and guidelines we've created

**Comment by mitovskaol** [comment]
@lukegonis I have posted an ask in the #devops-operations channels asking the teams to reduce their Jenkins resource allocations and will keep bringing this topic up and pointing to the doc in all my future interactions with the Platform teams. The ticket can be closed now.
