### ISSUE TITLE
Sysdig - add Kyverno policy to limit one CR per project set

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4750]
**Describe the issue**
this will prevent teams accidentally removing the sysdig team when they delete a duplicated CR in the namespace

**Definition of done**
- [x] check for list of teams that have multiple CR, work with them to remove it (wait until policy in place - Shelly)
- [x] add policy and test in lab
- [x] implement in prod

**Comment by IanKWatts** [comment]
I've prepared a ClusterPolicy for this and tested it in KLAB.

**Comment by IanKWatts** [comment]
Here are my notes on the namespaces listed above:
```
4a9599-tools
    delete the one that has a typo in it: 4a9599-sysdig-team
        name: 4a9599-sysdig-team
    4a9599-sysdigteam is good
        name: 4a9599-sysdigteam
950003-tools
    both are good; ask them to remove one
        950003-prod-sysdigteam
            name: 950003-prod-sysdigteam
        950003-sysdigteam
            name: 950003-sysdigteam
    warren.christian@telus.com
9c33a9-tools
    two resources with same user list but different roles
        9c33a9-sysdig-team
            name: 9c33a9-sysdig-team
        9c33a9-sysdigteam
            name: 9c33a9-sysdigteam
e0cee6-tools
    two identical roles; delete one
        e0cee6sysdigteam
            name: e0cee6sysdigteam
        sysdigteam
            name: sysdigteam
    young-jin.chung@gov.bc.ca
e52f12-tools
    Looks like one was meant for another namespace
    e52f12-sysdigteam is correct
    0ab226-sysdigteam also exists in 0ab226-tools and should be deleted here
        0ab226-sysdigteam
            name: 0ab226-sysdigteam
        e52f12-sysdigteam
            name: e52f12-sysdigteam
    Kuan.Fan@gov.bc.ca
    Richard.Tan@gov.bc.ca
d8f105-dev
    deleted, this is a 101 lab namespace
```

**Comment by ShellyXueHan** [comment]
### Update:
Completed!

So turns out this could be done quite easy! For each duplicated project set:
- change the sysdig team name from sysdig console. It's of the format `<licenseplate-team>`, add `-tmp` at the end of the team.
- delete the extra sysdig team CR from the namespace, wait for the operator to finish the run. It will sysdig team not found, assume it's deleted. As the playbook look for sysdig team by name, it won't delete the actual team that has been renamed.
- make sure there is no automation that created the sysdig team CR from the namespace.
- once this is all good, rename the sysdig team from console back to normal.
