### ISSUE TITLE
Pruner - add doc links to email

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4753]
**Describe the issue**
Adding the document with how-tos to the email that gets sent to teams when their workload is scaled.

- https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-automation/automated-scaling/

**Definition of done**
- [ ] link added to the scripts

**Comment by vivekratan88** [comment]
Added links to the body of the message for emails, committed changes.

**Comment by StevenBarre** [comment]
Rolled out the updates to Silver
