### ISSUE TITLE
Sysdig workshop

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4765]
**Describe the issue**
We have been seeing increased adoption rate of sysdig after the workshop. It'd be great to have a long term plan for this to continue.

Data of teams onboarded to sysdig:
number of new team | time
   4 2023-01
   7 2023-02
   6 2023-03
   4 2023-04
   4 2023-05
   4 2023-06
   9 2023-07
   2 2023-08
   2 2023-09
   3 2023-10
  18 2023-11
  11 2024-01
   4 2024-02
  11 2024-03
   2 2024-04

**Definition of done**
- [ ] discuss with Matt and Dustin on potential solution

**Comment by mtspn** [comment]
Consider promoting the existing sysdig training that is available, such as https://training.sysdig.com/monitor-hands-on-labs

We could : 
- create an additional tech document in the app monitoring section that links to this on-demand training
- create a rocketchat channel to support people working through this training at their own pace? 
- promote this training during community meetups

**Comment by mtspn** [comment]
Dustin suggested the idea of him running quarterly live training sessions on various Sysdig Monitor topics, provided we could get a minimum number of attendees to run a course. We could poll in the community meetup to select topics of interest.
