### ISSUE TITLE
Repo Cleanup for Platform Ops team in Artifactory

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4770]
**Primary Assignee**
@caggles 

**Describe the issue**
Between internal changes as well as the federation of Artifactory when it became HA earlier this calendar year, there is a need to review and clean-up unused repos (just one known to date) and ensure official repos used by the Ops team are visible inside the Artifactory web console.

**Additional context**
After internal auditing to confirm that `plat-cluster-docker-local` is not used anywhere on KLAB2 or EMERALD, Artifactory administrators are going to remove that repo from Artifactory since it has been deprecated in favor of the federated `cluster-docker-local` repo instead. Platform Ops to provide feedback if post-change web console visibility is still not present for the new repo.

**How does this benefit the users of our platform?**
Ensuring a stable location for the Platform Ops team to upload proprietary and custom-built images ensures maintenance for Openshift clusters proceeds smoothly and quickly.

**Definition of done**
- [x] Ops team to audit to confirm KLAB2 and EMERALD are not using `plat-cluster-docker-local`
- [ ] Artifactory admins (Cailey) to remove that same repo from Artifactory. If additional steps needed to promote/allow `cluster-docker-local` visibility in web console, do so as well.
- [ ] Ops team to QA the end results (bounce NSX pods in KLAB2 to confirm nothing's broken. Make sure official repo is still visible in Artifactory web console)

**Comment by wmhutchison** [comment]
Audit results when checking EMERALD for the nsx operator deployment, which manages both the operator and the agent ncp images.

```
              value: artifacts.developer.gov.bc.ca/cluster-docker-local/nsx-ncp-ubi:4.1.2.0
          image: artifacts.developer.gov.bc.ca/cluster-docker-local/nsx-container-plugin-operator:4.1.2.0
```

EMERALD is thus clear from using `plat-cluster-docker-local` repo.

**Comment by wmhutchison** [comment]
Same audit except for KLAB2. Newer ncp version here due to attempting a rush upgrade of KLAB2 to OCP 4.14.

```
              value: artifacts.developer.gov.bc.ca/cluster-docker-local/nsx-ncp-ubi:4.1.2.1
          image: artifacts.developer.gov.bc.ca/cluster-docker-local/nsx-container-plugin-operator:4.1.2.1
```

Also clean from use of `plat-cluster-docker-local` thus it'll be safe for Cailey to remove this old repo.

**Comment by wmhutchison** [comment]
Added Steven Barre to this ticket. It's not an urgent one, just one that needs a Platform Ops team member to QA things in KLAB2/EMERALD once Cailey's done her part to make sure all still works. Can be done while I'm away on vacation, or can wait until I'm back. This blocks nothing, just some house-keeping to reduce confusion when we login to Artifactory's web console and wonder what the difference between `plat-cluster-docker-local` and `cluster-docker-local` is.

**Comment by wmhutchison** [comment]
Coordinting with Cailey on first removing perms to the old repo first, and then nuke if scream-testing doesn't turn up anything. Not expecting much since only ncp-related images are in actual use, so will bounce KLAB2/EMERALD operator pods as a means of enforcing this scream-test.

**Comment by caggles** [comment]
Removed the old permissions, so now is a good time to test and see if things break :)

**Comment by wmhutchison** [comment]
@caggles Testing complete. Am able to still pull desired images without breakage. Proceed with full removal.
