### ISSUE TITLE
Artifactory - Two new read/write tokens for the cluster-docker-local repo

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4784]
**Describe the issue**
Documentation for the Platform Operations team is being finalized regarding how they can best make use of Artifactory for storing custom-built images instead of building these on each Openshift cluster.

At present write access to the `cluster-docker-local` repo is performed by using a token generated by any member of the Platform Operations team who receive said token after logging into the Artifactory web console. This however does not lend well towards further automation of our build processes, so we want two Artifactory service accounts created for this purpose, the new accounts having read/write access to the Artifactory `cluster-docker-local` repo, and one account to be used for each class of Openshift clusters (so one for regular Openshift, and one for NSX-backed Openshift).

**Additional context**
There seems to be an `ArtifactoryServiceAccount` custom resource that might allow self-serve ability to create the credentials needed, but not sure if it requires a traditional license plate based namespace structure to work or not. 

**How does this benefit the users of our platform?**
This allows further automation of internal build processes for images, improving the speed by which Openshift maintenance is performed and reducing the possibility of human error to slow down progress.

**Definition of done**
- [x] Create the two new Artifactory Service Accounts with read/write access to `cluster-docker-local` and save the credentials in an Openshift secret accessible by the Platform Ops team
- [x] Platform Ops team will QA the generated credentials by using `podman` to manually upload image updates to Artifactory.

**Comment by caggles** [comment]
Done! A secret has been created in the devops-artifactory namespace on gold, called cluster-docker-local-secrets with the usernames and passwords.

**Comment by StevenBarre** [comment]
Tested and working
