### ISSUE TITLE
Install helm onto RHEL9 UTIL servers

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4786]
**Describe the issue**
We currently use `helm` to manage the manifests for ako, and may switch to using `helm` for doing the same for things like the F5 CIS manifests since those can be also generated using `helm`. This was installed on our RHEL7/8 UTIL servers, but has not yet been included in RHEL9. This ticket will track the inclusion of `helm` into the RHEL9 build standard so that we continue having all of the required tools to maintain software like ako.

**Additional context**
At present all LAB servers are now RHEL9 but not so for the PROD servers, thus for any immediate need to use or run helm, do so from one of the existing PROD UTIL servers. 

**How does this benefit the users of our platform?**
Ensuring the Platform Operations teams have all the tools required to provide fast turn-around when maintenance is involved.

**Definition of done**
- [x] Add changes to allow helm be installed on the RHEL9 UTIL servers.

**Comment by vivekratan88** [comment]
PR link : https://github.com/bcgov-c/rhcos-ignition-builder/pull/135
