### ISSUE TITLE
OCP 3.11 PROD master certs due to expire July 2020

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#479]
Per daily cronjob that monitors key certificates, the master certificates are due to expire on July 11th 2020. 

- https://access.redhat.com/support/cases/#/case/02630156 (vendor case link)
- https://docs.openshift.com/container-platform/3.11/install_config/redeploying_certificates.html#redeploying-master-certificates (vendor link for specific playbook to run)

Work will need to be scheduled both for non-business hours since while rolling restart of services on masters will take place, there will still be a minor hiccup to API calls during the playbook's execution. 

Sufficient lead time will need to be planned both for the sake of proactive communication to all stakeholders as well as allowing all change management parties have enough time to review/approve the RFC.

**Comment by wmhutchison** [comment]
Will be doing this work in LAB first even if the LAB certs aren't yet expiring. Will setup a suitable cadence going forward and also identify possible glitches/etc to be wary of when scheduling this work for PROD.

**Comment by wmhutchison** [comment]
RFC for testing this in LAB is scheduled/approved for execution June 5th 2020.

After this is completed and risk/impact assessment completed for PROD, the tentative date for performing this in PROD will be likely right after PROD OS patching is finished (June 20th 2020). 

Again, the PROD certs expire on July 11th 2020.

**Comment by mitovskaol** [comment]
Scheduled for execution on Fri June 5.

**Comment by wmhutchison** [comment]
LAB testing was successful - additional playbook dependencies were identified in the form of a custom playbook that we will generate involving calling a number of roles meant to perform similar cert renewals for other components of the cluster.

Apart from fixing some components that break after the master cert is renewed, this is also meant to reset the cadence for these additional certificates so that going forward they will all be renewed in smaller groups.

**Comment by wmhutchison** [comment]
Met with Shelly and Clecio today to discuss implications of this change with respect to PROD SSO services. They want to pursue the creation/install of their own SSL certificate since right now the service is making use of the internal service serving secret to perform its re-encrypt style connectivity to the outside world. 

For this reason the proposed RFC date of June 21st will be moved forward one week to June 28th, and have advised that we won't be moving this RFC further ahead any more without very good reason.

The go/no-go regarding whether or not SSO stakeholders can find a suitable work-around will be the following Monday (June 22nd). If a work-around is achieved and tested, then this will affect the communications we send out to the general users since with a work-around, we no longer have to advise that SSO may be unavailable for a period of time.

If no work-around can be achieved, then a communication regarding the work and advising of a small impact to SSO will be sent out.

**Comment by wmhutchison** [comment]
Openshift documentation does allow us to specify in advance the duration period of the involved certificates, as shown here for Openshift 3.11:

https://docs.openshift.com/container-platform/3.11/install/configuring_inventory_file.html#advanced-install-config-certificate-validity

New certs are good for two years (others like etcd are good for three). Not really an issue for 3.11 PROD since due to project requirements and resource constraints, we need to be completely off 3.11 PROD well before these certs expire again.

Will need to check though if these variables exist for OCP4, and if they do, we may want to pick larger values for expiry for these specific certs.

**Comment by mitovskaol** [comment]
@ShellyXueHan has sent out communications to impacted product teams.
Scheduled for implementation in PROD on Sunday June 28.

**Comment by wmhutchison** [comment]
RFC for performing this work in PROD was successfully completed on June 28th. The 9am daily certificate report confirmed resolution by no longer warning us of pending expiring certs. Closing this ticket.
