### ISSUE TITLE
Add list of currently allowed URLs to Emerald docs

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4790]
**Describe the issue**
Add the current list of URLs allowed via the forward proxy to the docs page https://digital.gov.bc.ca/cloud/services/private/internal-resources/emerald/

**How does this benefit the users of our platform?**
Easier access to the known list of already approved URLs, and making it easier to know which URLs need requesting.

**Definition of done**
Page updated

**Comment by Pilargit12** [comment]
Hi @StevenBarre currently on draft now - can you please check the draft version, will message you URL
