### ISSUE TITLE
OCP NSX 4.14 Review Release Notes - Tim

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4797]
**Describe the issue**
Review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

4.14 Release notes
- Minor changes/improvements to the Administrator console view - better searching, more control over operator upgrade versions - https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#ocp-4-14-web-console
- Login to cluster via web browser - https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#oc-logging-in-browser
- Minor enhancements to oc new-build and oc new-app - you can set the --import-mode flag to Legacy or PreserverOriginal, and then create new applications by using a single sub-manifest or all manifests - https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#oc-new-build-enhancement 
- Minor changes to alerting rules - main one that impacts us - MultipleContainersOOMKilled - https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#ocp-4-14-monitoring-changes-to-alerting-rules

**Identify any dependencies**
None

**Definition of done**
- [ ] Fully read the release notes and added anything of interest as a comment here

**Comment by tbaker1313** [comment]
Completed.
