### ISSUE TITLE
OCP NSX 4.14 Review Release Notes - Vivek

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4798]
**Describe the issue**
Review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [ ] Fully read the release notes and added anything of interest as a comment here

**Comment by vivekratan88** [comment]
**Whats new in Openshift 4.14**

**-Security and Compliance: SCC Preemption Prevention & Secrets Store CSI Driver Operator**
SCC Preemption Prevention : 

Issue - Sometimes SCC is of higher priority and is preempted by another workload 
Resolved by :Pinning the workload to specific SCC to prevent preemption of SCC with annotations


Secrets Store CSI Driver Operator
-Helps auto mount secrets from external secret storage solutions like Azure Key Vault/AWS secret manager. This mounted to ephemeral vol so when pod is deleted the secret is also deleted.
-It auto rotates secret every 2 minutes and automatically rotates if the secret is changed.
-Sensitive data like passwords, bearer tokens, and certificates can be stored and managed in a centralized secret storage that is external to the cluster.
-Operator can sync secrets and create kubernetes secrets if its required for workflow.


**-Control Plane and Infrastructure: Hosted Control Planes & ARM Arch support**

Hosted Control Planes : One single control plane cluster will act as control plane cluster for pods in another cluster. Generally we have stand alone control plane which is hosted by group nodes which are VMs.
In HCP you create control planes as pods on a hosting cluster without the need for dedicated virtual or physical machines for each control plane. This helps decouple the control plane(includes an API endpoint, a storage endpoint, a workload scheduler, and an actuator that ensures state) and data plane (data plane includes compute, storage, and networking where workloads and applications run.)

New changes for HCP
-HCP can be hosted on Baremetal with Agent provider
-Allows HCP to be deployed in nested openshift virtualization VMs
-Enhancements for AWS.

ARM Arch support

Increased ARM support for different cloud providers such GCP, IBM Power or IBM Z, see link given below for more details
https://docs.openshift.com/container-platform/4.14/installing/installing-preparing.html#supported-installation-methods-for-different-platforms


**Data Management and Storage: OpenShift Data Foundation Enhancements**
-New features include regional disaster recovery, IPv6 auto-detection, log-based bucket replication, and autoscaling for Multicloud Object Gateway endpoints. These improvements enhance the resilience and scalability of storage solutions​

**Developer Productivity:Red Hat build of Quarkus 3.2 & OpenShift Pipelines Enhancements**

Quarkus is a Java framework tailored for deployment on Kubernetes
-New Dev UI with improved navigation, metrics tracking and endpoint management.
- IntelliJ Quarkus plugin.
-Redis as Quarkus cache extension.
-Simplified Azure functions support.
-MTA v1.2 support for Java 17 also more metrics to do assessment for applications to see if it can be refactored.

OpenShift Pipelines Enhancements 1.12 (Tekton 0.50)

-Tekton Results, which helps users logically group CI/CD workload history and separate longterm result storage away from the Pipeline controller, is in Technology Preview. You can bring in your own external Postgres database for storing records and external storage like Google Storage Buck or Amazon S3 for storing logs and events.
-With Pipelines as code, you can expand a custom parameter within your PipelineRun resource by using the params field, extend the scope of the GitHub token at the following levels: repository-level and global-level, and set policies that allow certain actions only to members of a team and reject the actions when other users request them.
-With the OpenShift Pipelines operator, you can configure the default SCC for pods that OpenShift Pipelines creates for pipeline runs and task runs. You can also set the SCC separately for different namespaces and configure the maximum (least restrictive) SCC that can be set for any namespace. We also support “options” field to enable additional configs for Tekton that are not currently added or supported by Red Hat.

**Openshift Monitoring:**
-Expire silences in Bulk
-LokiStack Console Plugin allows searching for patterns across all namespaces
-Insights advisor for openshift : Free service it asses cluster conditions and gives recommendations to improve it. New features for storage performance added for CephFS & VMware
-Free Insights cost management to monitor per-resource(namespace,cluster,node,tag) usage and spending on vCPU count, RAM and Storage capacity



**Networking: OVN Enhancements**
-Open Virtual Network improvements include localized network flow data on every node, which reduces operational latency and scales more effectively with the addition of new nodes, enhancing overall network performance and stability​

 
**AI workload**
-NVIDIA L40S GPU Accelerator for video based AI scanning. NVIDIA GPU support for AWS,Azure,GCP and OCI,=.
-This GPU can be used for LLM training and inference;Generative AI and chatbots

**Comment by vivekratan88** [comment]
expire alerts in bulk expand, also classify tech previews.

**Comment by vivekratan88** [comment]
also had links for the written info, add the part for deployment config which is going away.

**Comment by vivekratan88** [comment]
updated tech preview also removed features we don't use and added the ones we do use.
