### ISSUE TITLE
OCP NSX 4.14 Review compatability - CrunchyDB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4809]
**Describe the issue**
Ensure that either the current instlaled version of the operator is compatibale with the new OCP version, or an upgrade is completed.

<https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms>

- Current installed version: 
- Does that version support OCP 4.14?: 
- If no, what version do we need to update to?: 

**Definition of done**
- [ ] Current version is compatable, OR
- [ ] Operator upgraded in all clusters

**Comment by caggles** [comment]
We'll need to upgrade Crunchy to 5.4 or 5.5 for this, as crunchy 5.3 is not listed as compatible with any openshift version above 4.13.

**Comment by wmhutchison** [comment]
the CCM merged PR to accomplish this is on course to be implemented on June 4th for EMERALD.
