### ISSUE TITLE
Document change management process

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#481]
In Linux Land we have a document describing what isn't considered a "change" and thus doesn't need an RFC. We need to develop a guideline doc for MCS that outlines similar details and is agreed to by all.

These are the high level guidelines AdvSol Change Management outline. How each team interprets specific activities we leave up to them. 

Following activities require an RFC :
- Any activity that is non-routine and/or has the potential of high risk.
- All updates to infrastructure 
- Any activity done during a change window
- Any activity that may be disruptive to the service 
- Significant server configuration changes, including changes to job schedules.
- All configuration changes to core or sensitive infrastructure components.
- Migration of application code changes, including reports and scripts.
- Substantial data manipulation exercises that are not part of regular operations, such as running a data load or conversion program.
- Unscheduled outages, such as an emergency recycle.
- Unscheduled backup and restore activities.

RFC not required for:
- Daily operational configuration or data changes where the change is routine in nature, and tracked through an accepted request and approval process. Examples include user administration and catalog changes, single client submitted requests.

**Comment by mitovskaol** [comment]
Have a meeting scheduled on June 30 to go over the first draft of the document
