### ISSUE TITLE
OCP NSX 4.14 API Compatibility Audit and Updates for KLAB2

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4818]
**Describe the issue**
An audit of relevant AlertManager notifications needs to take place on KLAB2 with the intent of determining what needs to be handled by testing developers who make use of KLAB2, and what needs to be updated by either cluster admins or owners of various CCM-managed apps. Results from this will help feed work put into doing the same for other clusters.

**Additional context**
By virtue of how the API checks work, we will never have a 100% clean report since the checks themselves will trigger a false positive, but Red Hat does document what to expect for these so they can be readily ignored.

**AUDIT RESULTS**

**Definition of Done**
- [ ] Review and audit all notifications from AlertManager regarding API upgrades.
- [ ] Identify updates and changes that will be covered by CCM updates or other cluster-admin updates.
- [ ] Identify updates and changes that will be covered off by regular developers making use of KLAB2.
- [ ] Confirm all updates have completed and reporting is normal.

**Comment by vivekratan88** [comment]
There is only one Kubernetes API that is being removed in this upgrade storage.k8s.io/v1beta1 - checked the EMERALD cluster and we're not using that version, all workloads are using the newer version storage.k8s.io/v1 - which is fine.

Zero requests for beta, hence it is not used.
Output:

NSX KLAB2/openshift-config ~ $ oc get apirequestcounts | grep csistoragecapacities
csistoragecapacities.v1.storage.k8s.io                                                            57                      1463
**csistoragecapacities.v1beta1.storage.k8s.io                                                       0                       0**
NSX KLAB2/openshift-config ~ $

**Comment by vivekratan88** [comment]
NSX KLAB2/openshift-config ~ $ oc get apirequestcounts | grep csistoragecapacities
csistoragecapacities.v1.storage.k8s.io                                                            57                      1463
csistoragecapacities.v1beta1.storage.k8s.io                                                       0                       0
NSX KLAB2/openshift-config ~ $

**Comment by tbaker1313** [comment]
We also need to check horizontal pod autoscalers for autoscaling/v2beta2
This is the result (none found):
$ oc get apirequestcounts | grep -i horizontal | grep v2beta
horizontalpodautoscalers.v2beta1.autoscaling                                   1.25               0                       0
horizontalpodautoscalers.v2beta2.autoscaling                                   1.26               0                       0
