### ISSUE TITLE
OCP NSX 4.14 API Compatibility Audit and Updates for EMERALD

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4819]
**Describe the issue**
An audit of relevant AlertManager notifications needs to take place on EMERALD with the intent of determining what needs to be handled by testing developers who make use of EMERALD, and what needs to be updated by either cluster admins or owners of various CCM-managed apps. Results from this will help feed work put into doing the same for other clusters.

**Additional context**
By virtue of how the API checks work, we will never have a 100% clean report since the checks themselves will trigger a false positive, but Red Hat does document what to expect for these so they can be readily ignored.

**AUDIT RESULTS**

**Definition of Done**
- [x] Review and audit all notifications from AlertManager regarding API upgrades.
- [x] Identify updates and changes that will be covered by CCM updates or other cluster-admin updates.
- [x] Identify updates and changes that will be covered off by regular developers making use of EMERALD.
- [x] Confirm all updates have completed and reporting is normal.

**Comment by tbaker1313** [comment]
There is only one Kubernetes API that is being removed in this upgrade storage.k8s.io/v1beta1 - checked the EMERALD cluster and we're not using that version, all workloads are using the newer version storage.k8s.io/v1 - which is fine.

**Comment by tbaker1313** [comment]
$ oc get apirequestcounts | grep csistoragecapacities
csistoragecapacities.v1.storage.k8s.io                                                            52                      1458
csistoragecapacities.v1beta1.storage.k8s.io                                                       0                       0

**Comment by tbaker1313** [comment]
Also checked the old horizontal pod autoscaler for v2beta2 . This is the result - no problem apis found:
$ oc get apirequestcounts | grep -i horizontal | grep v2beta
horizontalpodautoscalers.v2beta1.autoscaling                                   1.25               0                       0
horizontalpodautoscalers.v2beta2.autoscaling                                   1.26               0                       0
