### ISSUE TITLE
OCP NSX 4.14 Test Ignition playbooks in KLAB2

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4836]
**Describe the issue**
Verify the rhcos playbooks work with the new version by draining/deleting and re-building one APP node. Check that the ignition files have the new ignition version metadata and any changes needed.

**Definition of done**
- [ ] ~~RHCOS playbooks used for building clusters tested~~

**Comment by wmhutchison** [comment]
NSX doesn't rely on tftpboot and similar tech like regular Openshift, but does rely on ingesting the ignition file for a new/rebuilt node manually inserted by us, so would tie into the node rebuild ticket to test.

**Comment by wmhutchison** [comment]
Closing due to not being required for OCP 4.14 upgrade. Playbooks involved play a role more for regular Openshift where changes in tftpboot/etc might affect things, but such are not used in NSX-backed clusters.
