### ISSUE TITLE
Create Kyverno policy for PrometheusRules

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4846]
**Describe the issue**
When product teams create custom PrometheusRules objects, they may not set an `interval` on a group. This can lead to prometheus trying to evaluate those rules/alerts every 30s instead of doing it less often. This can cause undue load on the cluster Prometheus.

**What is the Value/Impact?**
Protect against bad config from teams impacting cluster performance.

**What is the plan? How will this get completed?**
Test a Kyverno policy to set an `interval` if none is provided. Allow a team to override the default of `5m` if they want.

**Identify any dependencies**
None

**Definition of done**
PR in CCM for the new policy

**Comment by IanKWatts** [comment]
CCM PR: https://github.com/bcgov-c/platform-gitops-gen/pull/881
