### ISSUE TITLE
Complete Risk Register

### ISSUE THREAD

**Issue by AvneetKahlon** [BCDevOps/developer-experience#4847]
**Describe the issue**
Initial risk register list is setup. Need to update risk register according to digital STRA.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**

- [x] Make sure to get access to Digital STRA 
- [x] Complete risk register
- [x] Create visualization of risk register

**Comment by NickCorcoran** [comment]
Can also review STRA folders on SharePoint site for SoARs for entry in as some may not be in the Digital STRA system.
