### ISSUE TITLE
Investigate N8N Post Upgrade Testing

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#4857]
**Describe the issue**
N8N is logging out some token, and crunchy test in clab keep failing even though the crunchy is working fine. 

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
- [ ] fix the test so it can reflect the real situation for crunchy
- [ ] fix log so it won't show token

**Comment by w8896699** [comment]
Keep this ticket in review so that if error pop up again
