### ISSUE TITLE
Update auto-scaledown script to exclude CrunchyDB deployments

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#4861]
**Describe the issue**
Because the operator owns everything about CrunchyDB deployments, users don't have much direct control over when and how their images and deployments are updated. When the images are updated in Artifactory, this doesn't trigger an update of the deployments so the automation script considers the deployment to be un-updated, and will target them for shutdown.

The automation scripts should be updated to exclude deployments and stateful sets with postgres-operator.crunchydata.com in the label key. This will prevent the automation scripts from shutting down crunchy deployments.

**How does this benefit the users of our platform?**

Crunchy deployments in dev and test namespaces will not be wrongly scaled down because Openshift thinks the images haven't been updated lately.

**Definition of done**

- [x] Automation scripts now exclude deployments and statefulsets with postgres-operator.crunchydata.com in the label key.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-tools/pull/193

**Comment by StevenBarre** [comment]
Ended up just excluding all objects with a parent, to future proof for other operators. Deployed to all clusters.
