### ISSUE TITLE
Nagios - Create notification for silenced alerts

### ISSUE THREAD

**Issue by vivekratan88** [BCDevOps/developer-experience#4862]
**Describe the issue**
Check to see if there is way to create notification for alerts which are disabled manually and have not been turned ON

**What is the Value/Impact?**
Will ensure we don't miss on any alerts that are silenced.

**What is the plan? How will this get completed?**
Key components here is to check APIs used by Nagios to see if we can get this done

**Identify any dependencies**
Incase of absence please contact Steven B,Will H or Tim B regarding the ticket.

**Definition of done**
Complete should be email sent when notification is turned OFF for specific amount of time and host exists in Nagios. 
Need scheduled downtime of host and services 

should appear in this order 
Hosts in downtime:

- host1
- host2

Hosts notification disabled

- host3
- host4

Services in downtime

- Host1/ServiceA

Services notification disabled

- Host2/ServiceB

**Comment by vivekratan88** [comment]
what is been silenced needs to be reported in Nagios also what is silenced also should be reported - david elash

**Comment by vivekratan88** [comment]
Having a look at API docs to see if I can list all hosts whose notifications_enabled: can be set to zero, that will help in this case.

**Comment by vivekratan88** [comment]
Got play written with RO API key, doing testing now on AAP some errors seen trying to fix it with Rowan and Steven's guidance.

**Comment by vivekratan88** [comment]
More testing today, had to change API url from http to https and ran it the output seems to have been blank so working on adding FQDN to all modules and also provide debug output for host status response and re-run it again.

**Comment by vivekratan88** [comment]
Got it working the notifications needs to be disabled manually not put in maintenance window, thats way the output shows up.

OUTPUT:

https://ansible.advsol.tech/#/jobs/playbook/500284/output

**Comment by vivekratan88** [comment]
Got it working for maintenance window

OUTPUT:

https://ansible.advsol.tech/#/jobs/playbook/501123/output

**Comment by vivekratan88** [comment]
requirements changed to include services not only hosts

**Comment by vivekratan88** [comment]
updated new requirements
Hosts in downtime:
host1
host2
Hosts notification disabled
host3
host4
Services in downtime
Host1/ServiceA
Services notification disabled
Host2/ServiceB

**Comment by vivekratan88** [comment]
https://ansible.advsol.tech/#/jobs/playbook/510766/output

everywhere where selectattr is used the values are not printed hence it only show's hosts and services in downtime.

**Comment by vivekratan88** [comment]
output:
https://ansible.advsol.tech/#/jobs/playbook/520346/output
Went on call with Steven and will to resolve this.

Its fixed was missing quotes around integers for selectattr which was causing issues.

**Next steps:**
Check in cross platforms team for email format and configure email for play.

**Comment by vivekratan88** [comment]
Resolved code issue needed to have integer value in quotes.

https://ansible.advsol.tech/#/jobs/playbook/524530/output

Got a Python module issue for mail, the code seems to be correct will have to check on platform end. 
```The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1722290040.3199878-116-211402440689922/AnsiballZ_mail.py", line 107, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1722290040.3199878-116-211402440689922/AnsiballZ_mail.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1722290040.3199878-116-211402440689922/AnsiballZ_mail.py", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code```

**Comment by vivekratan88** [comment]
Output for email works 



-----Original Message-----
From: Hosting Services Managed Container Services <hsmcs@dxcas.com> 
Sent: Tuesday, July 30, 2024 2:01 PM
To: Ratan, Vivek <Vivek.Ratan@dxcas.com>
Subject: Test Email

Hello Team,

Here are the silenced notifcations:

  "Here is the information for scheduled downtime host status   :[]"
  "Here is the information for disabled notifcation host status  :['mcs_dummy_host']"
  "Here is the information for service status scheduled downtime :"
  "Here is the information for service status disabled service :['klab.mcs', 'clab.mcs']"

**Comment by vivekratan88** [comment]
Scheduled notification for every Thu at 8 AM Pacific Time in AAP.

**Comment by vivekratan88** [comment]
Tweaked to show hostname and service status, completed.

-----Original Message-----
From: Hosting Services Managed Container Services <XXXXXXXXXXXXXXXX> 
Sent: Tuesday, August 6, 2024, 11:06 AM
To: Ratan, Vivek <XXXXXXXXXXXXXXXX>
Subject: Nagios silenced alerts Email

Hello Team,

Here are the silenced notifications:

  -Here is the information for scheduled downtime host status   : []
  -Here is the information for disabled notification host status  : ['mcs_dummy_host']
  -Here is the information for service status scheduled downtime : []"
  -Here is the information for service status disabled service hostname : ['klab.mcs', 'clab.mcs']
  -Here is the information for service status disabled service name : ['MCS_CPU_Capacity_Percentage', 'MCS_AlertManager_Volume']

**Comment by vivekratan88** [comment]
made jinja based templates and had for loop created to see if that works.

https://ansible.advsol.tech/#/jobs/playbook/533081/output

output was skipped and seems to be blank

**Comment by vivekratan88** [comment]
fixed it!!

https://ansible.advsol.tech/#/jobs/playbook/543312/output

**Comment by vivekratan88** [comment]
completed, tested and incorporated all feedback from Steven and also scheduled in Ansible tower.

https://github.dxc.com/AdvSol/mcs-ansible-tower/pull/21/

**Comment by StevenBarre** [comment]
PR is still in Draft, not sure this is done ...
