### ISSUE TITLE
Chatbot - feature to connect chatbot account to GenAI service

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4867]
**Describe the issue**

**What is the Value/Impact?**

**What is the plan? How will this get completed?**
What are the key components of this task?

**Identify any dependencies**
Internal, external, who to contact in case of absence, person to refer to for further help.

**Definition of done**
Describe what 'complete' will look like.

**Comment by w8896699** [comment]
https://github.com/bcgov/rockychat/pull/7/files
Connect API of google workflow
