### ISSUE TITLE
Broken image link: Log in to OpenShift web console

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#4877]
https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/openshift-projects-and-access/login-to-openshift/

**Comment by Pilargit12** [comment]
https://github.com/bcgov/platform-developer-docs/pull/257

**Comment by Pilargit12** [comment]
- [x] Adding images to images folder instead of links works better and prevents images from not displaying correctly 
- [x] Relative link to images should be `![Alt-text- description of image for accessibility](../../images/filename.png) `
