### ISSUE TITLE
Automate the process for checking broken links / images

### ISSUE THREAD

**Issue by mtspn** [BCDevOps/developer-experience#4878]
**Describe the issue**
Improve the automation of checking for broken links and images in our documentation. 

**Definition of done**
- [ ] Review and understand the process for link checking in our documentation during the builds of our documentation
- [ ] If image links are not already checked and identified, discuss with DexEx team devs (Monica/Shea) about how this could be included 
- [ ] Check all current pages for broken links and images

**Comment by Pilargit12** [comment]
Process for reviewing broken links: 

1. Access https://github.com/bcgov/platform-developer-docs 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6ffbc284f1fe07f2c8741c499f92e4482b3856e/ACTIONS%20-%20%20bcgov-platform-developer-docs-%20This%20is%20a%20single%20location%20for%20all%20technical-developer%20documentation%20for%20product%20teams%20working%20on%E2%80%A6%202024-06-17%2009-08-40.png" alt="ACTIONS -  bcgov-platform-developer-docs- This is a single location for all technical-developer documentation for product teams working on… 2024-06-17 09-08-40.png" />

2. Select the latest workflow run <br> 

3.  Select "Usage" from the left side menu 

<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVpzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eda863d1069d78d187a44ec4924e753167dfc9dc/USAGE%20-%20Merge%20pull%20request%20%23257%20from%20bcgov-broken-image-openshift-console-doc%20%C2%B7%20bcgov-platform-developer-docs%40cb3d9d4%202024-06-17%2009-10-54.png" alt="USAGE - Merge pull request #257 from bcgov-broken-image-openshift-console-doc · bcgov-platform-developer-docs@cb3d9d4 2024-06-17 09-10-54.png" /><br>

4. Under Run Time screen, select the job 
<img width="1561" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWxzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd6c3075f0733b9e784835cf2d8ed1557cd49fd3/RUN%20-%20JOB%20Merge%20pull%20request%20%23257%20from%20bcgov-broken-image-openshift-console-doc%20%C2%B7%20bcgov-platform-developer-docs%40cb3d9d4%202024-06-17%2009-13-11.png" alt="RUN - JOB Merge pull request #257 from bcgov-broken-image-openshift-console-doc · bcgov-platform-developer-docs@cb3d9d4 2024-06-17 09-13-11.png" /><br>

5. Select "Build Techdocs" 
<img width="1717" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXRzQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb9a3c116dc1b60fea295dfddadcc9a8c8a11570/BUILD%20TECHDOCS%20-Merge%20pull%20request%20%23257%20from%20bcgov-broken-image-openshift-console-doc%20%C2%B7%20bcgov-platform-developer-docs%40cb3d9d4%202024-06-17%2009-14-34.png" alt="BUILD TECHDOCS -Merge pull request #257 from bcgov-broken-image-openshift-console-doc · bcgov-platform-developer-docs@cb3d9d4 2024-06-17 09-14-34.png" />


 6. Once selected the build techs will run, it's a long document and it is best to scroll all the way down to review the all of the 4xx errors.  4xx client error means that  the request contains bad syntax or cannot be fulfilled, but some of them are common errors where a login is needed and it is reported as not found, so as this exercise is done every so often, one will be able to distinguish from these errors and ignore them, but others will likely to be corrected. For a list of what they mean, this is a useful URL https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by mtspn** [comment]
Do the images show up for you in this issue @Pilargit12 ? 
<img width="461" alt="Screenshot 2024-06-17 at 9 50 27 AM" src="https://github.com/BCDevOps/developer-experience/assets/99685508/52fb2747-8827-4526-b744-fb4d51b07700">

**Comment by Pilargit12** [comment]
No, they show up like this: 

![image](https://github.com/BCDevOps/developer-experience/assets/131301244/872b5c30-0dd6-4817-acbc-eed7681dbaeb)

**Comment by mtspn** [comment]
Okay no worries, like they're broken in github but I can view them normally from within Zenhub.

**Comment by Pilargit12** [comment]
Thank you Matt, I wonder if I should go to github and attempt to also upload the images there?

**Comment by mtspn** [comment]
I think it's okay, as this conversation will now prompt anyone looking in github in the future to look at [Zenhub ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/4878)
