### ISSUE TITLE
Upgrade logging in PROD to 5.9

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4881]
**Describe the issue**
Upgrade the Logging stack in Silver/Gold/Gold DR to 5.9

This will enable the Splunk `indexKey` feature for log forwarding.

**What is the Value/Impact?**
Enable us to set up Splunk forwarding for AG.

**What is the plan? How will this get completed?**
Follow the documented steps to upgrade

**Identify any dependencies**
None

**Definition of done**
Logging upgraded in prod clusters

**Comment by StevenBarre** [comment]
CHG0060233 - CITZ MCS SILVER - Upgrade EFK Logging to 5.9
CHG0060234 - CITZ MCS GOLD - Upgrade EFK Logging to 5.9
CHG0060235 - CITZ MCS GOLD DR - Upgrade EFK Logging to 5.9

Scheduled for June 11-13. CHGs approved and notification posted to #devops-alerts

**Comment by StevenBarre** [comment]
Silver upgraded

**Comment by StevenBarre** [comment]
Gold upgraded

**Comment by wmhutchison** [comment]
GOLDDR upgraded.
