### ISSUE TITLE
Spike: Investigate OpenShift Plus

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#4887]
**Describe the issue**
Research spike into Openshift Plus
Steven to be primary assignee

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
 Determine:
- [x] Key features
- [x] if it is a good fit for our use case
- [ ] cost
- [x] benefits we aren't getting from our current platform

**Comment by StevenBarre** [comment]
#4773 is related

**Comment by StevenBarre** [comment]
Platform Plus is a bundle of the following software:
- Container Platform (OCP)
- Advanced Cluster Management (ACM)
- Advanced Cluster Security (ACS)
- Data Foundation (ODF)
- Quay

**Comment by StevenBarre** [comment]
Other parts of the bundle are discussed elsewhere. I'll just focus on Quay here. Quay maps onto Artifactory.

Artifactory can support other artifact types beyond container images, Quay cannot.
Quay can run Docker builds itself, while Artifactory cannot. But our teams are already either using OpenShift for builds or GitHub Actions.
Both Quay and Artifactory support image scanning, quota management, and HA setup.

If we were starting from scratch Quay may be a good choice, but I don't see a compelling reason to migrate from Artifactory.

I'll leave the cost question up to others.

**Comment by StevenBarre** [comment]
Presented at the Touchpoint call
