### ISSUE TITLE
Install Cert Manager operator in KLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4891]
**Describe the issue**
https://docs.openshift.com/container-platform/4.13/security/cert_manager_operator/index.html

Install in KLAB for security team to test out next sprint

**What is the Value/Impact?**
Could allow teams to automate cert renewals

**What is the plan? How will this get completed?**
Test the install process
PR in CCM to install in lab clusters

**Identify any dependencies**
None

**Definition of done**
Cert Manager installed in KLAB
Optional: CCM code to manage the install

**Comment by StevenBarre** [comment]
Installed in KLAB
CCM PR https://github.com/bcgov-c/platform-gitops-gen/pull/887

**Comment by StevenBarre** [comment]
@NickCorcoran can you test this?

**Comment by NickCorcoran** [comment]
I am waiting on ADMS to give me the ACME v2 endpoint for their Entrust service.  I will reach out this week to see where we're at with that.  Once I have I will be having Wade help out with some testing.
