### ISSUE TITLE
Feature request for emailed pod lists sent to the PO and TL

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#4894]
**Describe the issue**
When we need to drain a node for some reason, users would like an emailed list of impacted pods sent to the TL and PO. We usually post a list in the alerts channel but some people would like more information.

**How does this benefit the users of our platform?**
Allows users to be aware if their pods will be drained and take action before the drain if necessary. 

**Definition of done**

- [ ] Have a playbook or other technique to automatically generate and send the emails for pods on an affected node.

**Comment by StevenBarre** [comment]
@tbaker1313 do you remember where this idea came from?

**Comment by tbaker1313** [comment]
> @tbaker1313 do you remember where this idea came from?

It came from a user, I think Conor Brady?

**Comment by tbaker1313** [comment]
Request is from https://chat.developer.gov.bc.ca/channel/devops-operations?msg=RCRE3CpNi6Mi4q52C

**Comment by StevenBarre** [comment]
We expect apps to be monitored and emailing PO/TL might just cause more confusion. We'll just post in the alerts the node name and let teams check their apps and monitoring.
