### ISSUE TITLE
Exclude specific Imagestreams and Templates 

### ISSUE THREAD

**Issue by vivekratan88** [BCDevOps/developer-experience#4901]
Describe the issue
During every upgrade cycle we need to exclude specific Imagestreams and Templates 

What is the Value/Impact?
unnecessary templates/imagestreams use up disk space and will have to be removed also keeps everything tidier 

What is the plan? How will this get completed?
-Attend session
-Take down notes and screenshots.
-Work on PR as per feedback

Identify any dependencies
-Vivek Ratan
-Tim Baker

Definition of done
Done will be documentation that is reviewed, and all feedback is completed in PR reviews.

**Comment by StevenBarre** [comment]
I think this is already covered by #4835 ? Docs should be covered already in the Upgrade doc and https://github.com/bcgov-c/advsol-docs/pull/309

**Comment by vivekratan88** [comment]
This seems like duplicate issue hence closing this ticket
