### ISSUE TITLE
Add MS Login URL to Forward Proxy

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4906]
**Describe the issue**
iStore Order for: 
Date Submitted: June 12, 2024
iStore Number: 1169979
Lead time (business days after EA Approves):

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [ ] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by StevenBarre** [comment]
This change will be scheduled for Wednesday June 19th

**Comment by MarisaBC** [comment]
Order completed.
