### ISSUE TITLE
Sysdig configuration tuning to fix agent crashes

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#491]
Related to a support issue, the agents are crashing and collecting too many metrics with the load of containers. The first step here is to reduce the amount of prom metrics collected and see if this resolves the crashing agents.

**Comment by tosazuwa** [comment]
@stewartshea , can you update status of this ticket. There is another ticket #327 tracking similar

**Comment by stewartshea** [comment]
We should likely close this in favour of #327
