### ISSUE TITLE
Decommission prod util servers

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4925]
**Describe the issue**
iStore Order for: 
Date Submitted: June 20, 2024
iStore Number: 1170141
Lead time (business days after EA Approves):

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [ ] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by tbaker1313** [comment]
Submitted RFCs for action on July 9th and final decom on July 16th.

**Comment by tbaker1313** [comment]
Look for any unnecessary firewall rules that can be deleted.

**Comment by tbaker1313** [comment]
The servers have been shutdown and will be fully decommissioned on July 16th.

**Comment by MarisaBC** [comment]
According to DXC, "the servers have been shutdown and will be fully decommissioned on July 16th".

**Comment by tbaker1313** [comment]
These servers are shutdown and were removed on July 16th.
