### ISSUE TITLE
Porter Operator should grant more permissions in non-primary side

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4926]
**Describe the issue**
User in Gold DR would like to be able to get TransportServer objects that are created by the operator.

**What is the Value/Impact?**

**What is the plan? How will this get completed?**
https://github.com/bcgov-c/platform-gitops-gen/blob/master/roles/porter_operator/templates/aggregate-roles.yaml.j2#L50 currently only gets created on the primary side. The TSC permissions only need to be there, but the TS permissions should be moved to a separate ClusterRole and created on both primary and secondary sides via https://github.com/bcgov-c/platform-gitops-gen/blob/master/roles/porter_operator/templates/common-roles.yaml.j2

**Identify any dependencies**
None

**Definition of done**
CCM PR approved

**Comment by StevenBarre** [comment]
Thread https://chat.developer.gov.bc.ca/channel/devops-operations?msg=JXR4FpAHMcecDEzSe

**Comment by IanKWatts** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/897
