### ISSUE TITLE
Risk Register Completion and cleanup

### ISSUE THREAD

**Issue by AvneetKahlon** [BCDevOps/developer-experience#4928]
**Describe the issue**
A risk register is created to document, track, and manage risks of platform services and applications. 

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**

- [x] Ensure all the risks identified are documented
- [x] ensure all the columns are updated
- [x] ensure risk status is updated

**Comment by NickCorcoran** [comment]
Avneet did a considerable amount of review and updates here.  Closing now.  Into more of a maintenance mode now.
