### ISSUE TITLE
peak redhat optimization

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#4934]
**Describe the issue**
find documentation and see if those recommandation can be showed on openshift console.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by w8896699** [comment]
https://docs.redhat.com/en/documentation/cost_management_service/1-latest

**Comment by w8896699** [comment]
https://docs.redhat.com/en/documentation/cost_management_service/1-latest/html-single/using_cost_models/index?extIdCarryOver=true&sc_cid=701f2000001Css5AAC#cost-model-workflow_using-cost-models

**Comment by w8896699** [comment]
Looks like admin can change the rate: https://docs.redhat.com/en/documentation/cost_management_service/1-latest/html-single/using_cost_models/index?extIdCarryOver=true&sc_cid=701f2000001Css5AAC#what-is-a-cost-model_using-cost-models

**Comment by StevenBarre** [comment]
Yes, Justin Hewitt set up the current cost models in our account. They can be changed if it would help.

**Comment by w8896699** [comment]
Closing ticket:
These are some links that explain in depth how Cost Management is being used and how it integrates with your current on prem or cloud hosted clusters.


https://docs.redhat.com/en/documentation/cost_management_service/1-latest/html-single/getting_started_with_cost_management/index#idm140029433803056


This doc introduces the new features added 
https://docs.redhat.com/en/documentation/cost_management_service/1-latest/html-single/whats_new_in_cost_management/index#default_to_aws_savings_plan

These will detail how you integrate your cluster with Cost management operator and collect the usage data through a created integration/source.

https://www.redhat.com/en/blog/how-get-started-cost-management-red-hat-insights

https://www.redhat.com/en/blog/improve-your-cloud-cost-visibility-red-hat-insight

Currently Cost Management seems to be only available in the console.redhat.com and requires users to have the correct roles and permissions to access this. 

https://docs.redhat.com/en/documentation/cost_management_service/1-latest/html-single/limiting_access_to_cost_management_resources/index#default-user-roles_limiting-access

RFE has been created
