### ISSUE TITLE
2020 Q3 Patching schedule

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#494]
* (COMPLETE) July 10th -> OS patching for ministry Aporeto/haproxy VMs
* (COMPLETE) July 13th-17th -> LAB OCP upgrade to 3.11.232
* (COMPLETE) July 21st-24th -> LAB OCS upgrade to 3.11.5
* (COMPLETE) July 25th-August 7th -> ITIMS RFC196206 - PROD OCP upgrade to 3.11.232
* (COMPLETE) August 12th 2020 -> CHG0016745 - OS Patches against OCP4 UTIL servers
* (COMPLETE) August 17th-21st -> CHG0017127 - 3.11 LAB OS patching
* (COMPLETE)  August 22nd-23rd  -> CHG0017046 - PROD OCS upgrade to 3.11.5 server side only (clients updated during PROD OS patching)
* (COMPLETE)  September  8th - 25th -> CHG0017053 - 3.11 PROD OS patching

**Comment by wmhutchison** [comment]
After this week's Red Hat TAM meeting, the existing version 3.11.232 was decided to be acceptable versus waiting a week or more for the very latest OCP version to drop. Scheduling for everything is going to be tight in Q3, and that includes additional time for some cross-training.

**Comment by wmhutchison** [comment]
All of the Aporeto/HAProxy VMs were OS-patched for this quarter on July 10th.

The 3.11 LAB cluster was successfully upgraded from OCP 3.11.161 to 3.11.232 (latest available at that time) during the week of July 13th. While we still wait for a week before kicking off a similar upgrade in PROD, we're officially kicking off the RFC creation and comms for the PROD OCP upgrade to the same version, to start on July 25th.

**Comment by wmhutchison** [comment]
OCS (Containerized gluster) was successfully upgraded this week in LAB to latest available version (3.11.5). Both Tim and Tatsuya received cross-training since they have not previously performed this type of upgrade yet.

**Comment by wmhutchison** [comment]
Formal change tickets now in place for the OCP4 UTIL servers and 3.11 LAB cluster. Taking one last look at known disruptive Network RFCs coming up before laying down RFC tickets for PROD OCS upgrade and OS patching.

**Comment by wmhutchison** [comment]
RFC tickets now in place with ServiceNow for remaining work. Will confirm with stakeholders first regarding proposed timing before formally pushing out comms for remaining PROD work.

**Comment by wmhutchison** [comment]
PROD OS patching completed ahead of schedule. Closing off now.
