### ISSUE TITLE
chatbot - connect to aws bedrock

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#4941]
**Describe the issue**
this is to extend the current chatbot to also use AWS bedrock in addition to gcp.

**Definition of done**
- [ ] implement feature

Feature description:
- chatbot is able to connect to AWS bedrock model via API
- each conversation will be randomly directed to either AWS or GCP
- user will see which cloud they are talking to

**Comment by lukegonis** [comment]
No longer proceeding with this work
