### ISSUE TITLE
Automate metadata collection for NetApp Backups

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4943]
**Describe the issue**
Currently, the backups are stored under the PV name, which is a UID and not the PVC friendly name. In the event a PVC is deleted, it can be hard to discover the PV name to correctly request the restore.

https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/automation-and-resiliency/netapp-backup-restore/

**What is the Value/Impact?**
Simpler restore process

**What is the plan? How will this get completed?**
Develop a CronJob to collect the PV name of all netapp-file-backup PVCs and store it somewhere, possibly a ConfigMap in a non-tenant namespace.

**Identify any dependencies**
None

**Definition of done**
- [x] CronJob deployed to all clusters
- [x] Docs updated
- [ ] Announcement at a community meetup

**Comment by caggles** [comment]
maybe we can store it in s3, since then it's easy to recover if the whole cluster blows up, lol.

**Comment by StevenBarre** [comment]
Got an S3 bucket / user from Cailey. Started testing some python code.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-tools/pull/215

Still trying to figure out bucket lifecycle policy RBAC

**Comment by StevenBarre** [comment]
Lifecyle figured out. PR merged. Deployed to all clusters.

**Comment by StevenBarre** [comment]
https://github.com/bcgov/platform-developer-docs/pull/292

**Comment by StevenBarre** [comment]
Docs updated. It will be a while to the next community meetup, so closing this now
