### ISSUE TITLE
Provide Project Resource Stats in Product Owner distribution list

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#495]
- [x] @wmhutchison to update [Resource Tuning Recommendations](https://github.com/BCDevOps/developer-experience/blob/master/docs/resource-tuning-recommendations.md) with some easy one-liner cli commands teams can run to understand their own current usage
- [x] @sbarre-esit to adjust the permissions of `system:serviceaccount:devhub-tools:cluster-view-sa` to be able to read from Prometheus
- [x] @ShellyXueHan to extend the Product Owner distribution list to include project CPU Usage and CPU Requests based on the existing [Project Stats](https://github.com/bcgov-c/platform-ops/blob/master/tools/stats/projstats.sh) bash script

**Comment by mitovskaol** [comment]
@stewartshea  Can you please get in touch with Tats to discuss your idea about using Sysdig for this.

**Comment by wmhutchison** [comment]
Additional push to get something for this out there, even if it's a self-serve oc command.

At present the following appears to be viable for anyone who has access to `oc`.

```
oc get quota compute-long-running-quota -o=custom-columns="CPU Requests":.status.used."requests\.cpu","CPU Limit":.status.hard."limits\.cpu"
CPU Requests   CPU Limit
1450m          16
```

**Comment by wmhutchison** [comment]
Actual CPU usage is derived from running `oc adm top pod` and manually adding up the second column of numbers

```
$ oc adm top pod
NAME                              CPU(cores)   MEMORY(bytes)
<redacted>        3m           285Mi
<redacted>        3m           299Mi
<redacted>        3m           285Mi
<redacted>             0m           13Mi
<redacted>   9m           61Mi
<redacted>   4m           98Mi
<redacted>    0m           28Mi
<redacted>    0m           26Mi
```

The "m" means the number in front is to be divided by 1000, so 9m = 0.009.

For amount of CPU requests for the project, the following one-liner will present that value.

```
$ oc get quota compute-long-running-quota -o=custom-columns=Requests:.status.used."requests\.cpu"
Requests
1450m
```

**Comment by wmhutchison** [comment]
Apply an update to the docs via a suitable PR for the following:

https://github.com/BCDevOps/developer-experience/blob/master/docs/resource-tuning-recommendations.md

**Comment by mitovskaol** [comment]
@ShellyXueHan It would be great to have an API endpoint built for this report similar to what was built to generate the Product Owner distribution list. Can you please look into the amount of effort required for that and connect with @sbarre-esit  and @wmhutchison to learn where the report script resides.

**Comment by ShellyXueHan** [comment]
sure, maybe we could merge the two reports to the same backend if using ansible playbook. @sbarre-esit can you point me to the scripts?

**Comment by sbarre-esit** [comment]
`system:serviceaccount:devhub-tools:cluster-view-sa` already has the needed permissions (can view the openshift-monitoring namespace). Tested with

```
NS=9wbi3f-prod; curl -sk -H "Authorization: Bearer $(oc -n devhub-tools sa get-token cluster-view-sa)" "https://prometheus-k8s-openshift-monitoring.pathfinder.gov.bc.ca/api/v1/query?query=sum(kube_pod_container_resource_limits_cpu_cores%7Bnamespace%3D%22${NS}%22%7D%20*%20ON(node)%20group_left()%20count(kube_node_labels%7Blabel_region%3D%22app%22%7D)%20by%20(node)%20*%20ON(namespace%2Cpod%2Ccontainer)%20kube_pod_container_status_running%20%3E%200)%20by%20(namespace)" | jq -r '.data.result[0].value[1]'
10.7
```

Over to you @ShellyXueHan

**Comment by ShellyXueHan** [comment]
@sbarre-esit hey Steven, I can confirm the sa is working as expected. Another question for you about the filters you applied to list top 20 namespaces based on CPU request and percentage. (Olena showed me a previous Excel file you sent) I don't see it as part of the script, did you add it manually?

**Comment by sbarre-esit** [comment]
The [README](https://github.com/bcgov-c/platform-ops/blob/master/tools/stats/README.md) covers how to turn the CSV into an Excel file with some calculations and filtering. But we can make up new filters that make sense for Olena to include more or less projects.

**Comment by ShellyXueHan** [comment]
I see, thanks Steven! Formatting/filtering is only applicable in Excel files not csv. @mitovskaol Olena are you okay with just receiving the full list and apply the filters afterwards for now? As Steven mentioned, [here](README) is how the list is formatted.

**Comment by mitovskaol** [comment]
Yes @ShellyXueHan  that works for me! thank you!

**Comment by wmhutchison** [comment]
Per assigned check-box https://github.com/BCDevOps/developer-experience/pull/526 now exists for review/approval regarding oc one-liners.
