### ISSUE TITLE
Update "Request quota increase" page 

### ISSUE THREAD

**Issue by alexandralloyd** [BCDevOps/developer-experience#4961]
**Describe the issue**
After the last round of user testing, there are some minor edits that need to be made to this page: https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/automation-and-resiliency/request-quota-increase-for-openshift-project-set/

All changes are proposed outlined here: https://docs.google.com/spreadsheets/d/1oHx73meWTEe6sfwAGv3S71JsbQJGk7lhz-5TnT02M2o/edit?gid=1627999487#gid=1627999487

**Additional context**
Significant improvement from the first round of testing, but still there are some minor changes that could be made to improve usability. We want to ensure these changes coincide with changes to the Registry, so everything is aligned.

**How does this benefit the users of our platform?**
Improves page with evidence-based changes that came from user testing. 

**Definition of done**
- [ ] Changes are live on the website

**Comment by alexandralloyd** [comment]
Additional information:

These mandatory fields appear when trying to submit a quota increase request. I've attached the fields here. After pressing submit, you will now be taken to a generic comment box instead of one asking for justifications of your request. 
 
I think step 5 on this page will have to change a bit. The current wording is "A pop-up will appear to allow space to include all the information you have collected and gathered, this place only allows for text information if you need to submit photos or files please do so in the next step as it is necessary and part of the request process" - perhaps this could be removed. We can then put a new bullet above the current first bullet that says to fill in the new fields then press submit.

**Comment by Pilargit12** [comment]
Updated:

- [x] Adding information on ## Steps to request quota increase that advises readers that requests for quota decreases are automatically approved 
- [x] Removed the area in Step 5 that described: "... if you need to submit photos or files please do so in the next step as it is necessary and part of the request process..."
- [x] Confirmed with Artem that Step 6 is still valid
