### ISSUE TITLE
Create the DevHub page for the Crunchy Workshop

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#4967]
Create a page in DevHub for the Crunchy Workshop videos according to what Pilar and I discussed during our meeting on July 17:

- a separate page linked with the existing Crunchy best practices docs
- embedded videos with a short intro to each
- include additional links to other docs such as installing helm

**Comment by Pilargit12** [comment]
https://github.com/bcgov/platform-developer-docs/pull/265/files
