### ISSUE TITLE
Remove IPs from hostsubnets

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#497]
We're taking back some IPs for the 6 VMs and need to remove them from the HostSubnets of the Infra hosts which were planning to use them for Egress IPs.

**Comment by wmhutchison** [comment]
Based on what is intended for IPs for the new VMs, the following IPs will need to be removed from the list of `egressCIDRs` on the PROD INFRA nodes:

```
142.34.143.148
142.34.143.149
142.34.143.152
```

That will leave the remaining `egressCIDRs` still configured, which can be included in the removal if not truly used or intended for use.

```
142.34.143.160
142.34.143.189
142.34.143.190
```

**Comment by wmhutchison** [comment]
RFC now created pending approval for execution after 5pm PDT on June 2nd.

**Comment by wmhutchison** [comment]
RFC approved by Olena. Working now on a suitable communication for Rocket Chat.

**Comment by wmhutchison** [comment]
Communication went out on #devops-alerts on June 1st. We are in line to execute the work at 5:00pm PDT June 2nd.
