### ISSUE TITLE
Weekly CCM PROD Push for July 30 - Aug 1

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#4988]
**Describe the issue**
This ticket will track efforts spent toward creating the next CCM release and promoting it against the three production Openshift clusters.

**Definition of done**
- [x] Create suitable GitHub Release before EOD Friday
- [x] Create suitable Standard Change RFCs and assign to team members as appropriate
- [x] Create and Receive approval for PR incrementing CCM version for PROD clusters
- [x] Ensure version increment PR is merged before executing any RFCs
- [x] Execute RFC for SILVER & EMERALD cluster
- [x] Execute RFC for GOLD cluster
- [x] Execute RFC for GOLDDR cluster

**Comment by StevenBarre** [comment]
CHG0061670 Silver
CHG0061671 Emerald
CHG0061672 Gold
CHG0061673 Gold DR

**Comment by wmhutchison** [comment]
RFCs now completed for SILVER and EMERALD (CHG0061670, CHG0061671).

**Comment by wmhutchison** [comment]
RFC now complete for GOLD (CHG0061672).

**Comment by wmhutchison** [comment]
RFC now complete for GOLD (CHG0061673).
