### ISSUE TITLE
OCP 4.14 Update upgrade docs and create CHG for other clusters

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#4995]
**Describe the issue**
Ensure the Upgrade docs are up to date and have any new steps required. Create CHG records for each of the other clusters, even if they only have tentative dates.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] Documentation updated (https://github.com/bcgov-c/advsol-docs/pull/318)
- [x] Final review of GitHub PRs
- [x] CHG records created for SILVER (CHG0062504 on Sept 15th, CHG0062505 starting Sept. 16th)
- [x] CHG records created for GOLD (CHG0062514 on Sept 29th, CHG0062518 starting Oct 1st)
- [x] CHG records created for GOLDDR (CHG0062520 on Oct. 6th, CHG0062521 starting Oct 7th)

**Comment by StevenBarre** [comment]
We should run the full `config-util.yaml` instead of the `update-cli.yaml` playbook to ensure the kdump cron and folder gets set up correctly on all the util nodes.

**Comment by vivekratan88** [comment]
Logging in to the CLI using a web browser
https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#oc-logging-in-browser

Setting or deleting HTTP request and response headers in a route

https://docs.openshift.com/container-platform/4.14/networking/routes/route-configuration.html#nw-route-set-or-delete-http-headers_route-configuration

Headers can now be set in the Route object. Should be advertised to the community as a new feature.

Specifying the eviction policy for unhealthy pods

https://docs.openshift.com/container-platform/4.14/nodes/pods/nodes-pods-configuring.html#pod-disruption-eviction-policy_nodes-pods-configuring

Should be advertised to the community as a new feature.

Workloads deprecated and removed features
https://access.redhat.com/articles/7041372

Change in SSH key location

If you customized the default OpenSSH /etc/ssh/sshd_config server configuration file, you must update it according to this Red Hat Knowledgebase article.(https://access.redhat.com/solutions/7030537)


Operator lifecycle and development deprecated and removed features
operators.openshift.io/infrastructure-features annotations

**Comment by wmhutchison** [comment]
All RFCs now created and over to Luke for approval. Working next on the PR update for comms we'd post into Rocket Chat devops-alerts channel. If we're to fulfill the minimum two week notification span between posting the notice and when SILVER starts, then all of the RFCs and comms need to be approved before EOD this Friday, and comms posted by EOD Friday.

For some of the RFC contents we've gotten used to copy/pasting the previous RFC contents, which is okay, but not fully accurate to what is being done Reset this by grabbing content from latest PR of our upgrade docs.

Some chatter in CCM channel regarding CrunchyDB which needs to be upgraded in SILVER before SILVER upgrades can proceed. Confirmed this isn't a blocker with the mentioned date before emailing for RFC approval.

**Comment by wmhutchison** [comment]
RFCs approved by Luke on August 29th. Comms for RC #devops-alerts created/approved/posted today as well. Ticket updated to reflect RFC numbers and starting dates.

**Comment by wmhutchison** [comment]
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5034 was previously closed, but a recent glitch was discovered for the nagios dhcp check where the local manifests was still referencing a branch instead of main.

Checking official upgrade docs, it seems we're not pushing manual build tests for the dhcp check, which will need to be included so that such issues are then correctly detected during the appropriate ticket. Will push that update.

**Comment by wmhutchison** [comment]
Added documentation PR link to top of ticket. It should be what's used when tackling KLAB upgrade QA.

**Comment by wmhutchison** [comment]
No pending PRs for `platform-tools` or `rhcos-ignition-builder` repos to review/merge.
Two PR's exist for `platform-ops` both related to kdump. Tim closed one of them as being problematic, the other PR remains solely as a worst-case roll-back plan if kdump machineconfig issues arise which cannot be resolved.

Asked for a final review of the one documentation PR (https://github.com/bcgov-c/advsol-docs/pull/318) and will merge once approved.
