### ISSUE TITLE
OCP 4.14 Review Release Notes - Vivek

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5001]
**Describe the issue**
Review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [ ] Fully read the release notes and added anything of interest as a comment here

**Comment by vivekratan88** [comment]
Going thru points and updating them today

**Comment by vivekratan88** [comment]
Logging in to the CLI using a web browser
https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html#oc-logging-in-browser

Setting or deleting HTTP request and response headers in a route

https://docs.openshift.com/container-platform/4.14/networking/routes/route-configuration.html#nw-route-set-or-delete-http-headers_route-configuration

Headers can now be set in the Route object. Should be advertised to the community as a new feature.

Specifying the eviction policy for unhealthy pods

https://docs.openshift.com/container-platform/4.14/nodes/pods/nodes-pods-configuring.html#pod-disruption-eviction-policy_nodes-pods-configuring

Should be advertised to the community as a new feature.

Workloads deprecated and removed features
https://access.redhat.com/articles/7041372

Change in SSH key location

If you customized the default OpenSSH /etc/ssh/sshd_config server configuration file, you must update it according to this Red Hat Knowledgebase article.(https://access.redhat.com/solutions/7030537)


Operator lifecycle and development deprecated and removed features
operators.openshift.io/infrastructure-features annotations
