### ISSUE TITLE
OCP 4.14 Review Release Notes - Billy

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5002]
**Describe the issue**
Review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [ ] Fully read the release notes and added anything of interest as a comment here

**Comment by w8896699** [comment]
Interested update:
Updates in 4.14 include enhancements to resource requests and limits, as well as improvements in CPU and memory management.

Monitoring and Logging Updates:
OpenShift 4.14 brings enhancements to monitoring and logging capabilities, including better integration with external monitoring tools.

DeploymentConfig been depercated.
