### ISSUE TITLE
OCP 4.14 Meeting to discuss Release Notes

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5006]
**Describe the issue**
Once everyone has had a chance to review the [OCP 4.14 Release Notes](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html) for any changes that will impact the product teams, ops team, or platform services team, have a meeting to discuss each persons individual findings/notes.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
AdvSol to schedule a MS Teams meeting to have everyone discuss.

**Identify any dependencies**
See blockers

**Definition of done**
- [x] Meeting held

**Comment by StevenBarre** [comment]
Meeting scheduled for Aug 26th

**Comment by StevenBarre** [comment]
Meeting held. Slides updated. Backlog tickets created for docs/training updates.
