### ISSUE TITLE
OCP 4.14 Review compatibility - RH Integration

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5009]
**Describe the issue**
Ensure that either the current instlaled version of the operator is compatibale with the new OCP version, or an upgrade is completed.

<https://docs.redhat.com/en/documentation/red_hat_integration/>

- Current installed version: 
  - AMQ Streams: 2.6.0-2
  - Camel K 1.10.6
  - Service Registry 2.3.4
- Does that version support OCP 4.14?: Yes
- If no, what version do we need to update to?: 

**Definition of done**
- [x] Current version is compatible, OR
- [ ] Operator upgraded in all clusters

**Comment by StevenBarre** [comment]
Service Registry Operator 2.3.4 = Service Registry 2.5.11
https://access.redhat.com/articles/7040557

Service Registry 2.5 is supported on OCP 4.12 -> 4.15
https://access.redhat.com/articles/5208571

**Comment by StevenBarre** [comment]
Camel K 1.10 supports OCP 4.11 -> 4.16
Camel K 1.10 supports AMQ Streams 2.x and is tested with 2.6
https://access.redhat.com/articles/6241991

**Comment by StevenBarre** [comment]
AMQ Streams 2.6 supports OCP 4.11 -> 4.14
https://docs.redhat.com/en/documentation/red_hat_streams_for_apache_kafka/2.6/html-single/release_notes_for_amq_streams_2.6_on_openshift/index#openshift_container_platform_support

**Comment by StevenBarre** [comment]
There is an AMQ Streams 2.7 available, will create a separate ticket to handle that upgrade later.
