### ISSUE TITLE
OCP 4.14 Review compatibility - JBoss

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5010]
**Describe the issue**
Ensure that either the current instlaled version of the operator is compatibale with the new OCP version, or an upgrade is completed.

<https://docs.redhat.com/en/documentation/red_hat_jboss_enterprise_application_platform/>

- Current installed version: 
  * **EAP v3.0.0** (KLAB)
  * **EAP v2.4.3** (CLAB, SILVER, GOLD, GOLDDR)
- Does that version support OCP 4.14?: **Yes but should true up versions if possible.**
- If no, what version do we need to update to?:  **v3.1.0**

**Definition of done**
- [ ] Current version is compatible, OR
- [x] Operator upgraded in all clusters

**Comment by wmhutchison** [comment]
An OLM-managed operator, the sole (stable) channel wants to upgrade operator up to v3.1.0 whether it be on OCP 4.13 or 4.14, so not going to see a forced upgrade due to OCP 4.14. Just need to see if there are any version blockers for JBoss (need to be on version X if we want to upgrade to OCP 4.14).

If no current blockers for existing version, then we will proceed with comms/etc asking if we can align a Jboss upgrade to very latest with Openshift upgrade or not.

**Comment by wmhutchison** [comment]
OLM operator has significant over-lap between OCP v4.13 and v4.14, with only v4.14 having a slightly newer branch available (v3.1.0, OCP 4.13 only goes up to v3.0.0). Thus an Openshift upgrade without upgrading JBoss to latest will likely not break anything, but best to move to v3.1.0 if the stakeholders involved allow it.

At present only two Openshift clusters have a `wildflyservers` resource defined: KLAB, SILVER

**Comment by StevenBarre** [comment]
There was an email thread before with CSB Courts Digital Display System (prod) 288e51-prod to have them test the upgrade. I've followed up with them.

**Comment by StevenBarre** [comment]
Action plan order of operations:
Stuart -> update dev/test/prod in klab to 7.4
Steve -> update klab operator to 3.1
Stuart -> update dev/test/prod in Silver to 7.4
Steve -> update Silver operator to 3.1

**Comment by StevenBarre** [comment]
Updating in KLAB ran into some issues. Need to create a temporary clusterrole and binding to allow the upgrade to complete.

```bash
oc create -f - <<EOT
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temporary-node-reader
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
EOT
oc adm policy add-cluster-role-to-user temporary-node-reader -n openshift-bcgov-jboss -z eap-operator
```

Then, as you do the upgrades you may need to scale down the older replicasets to 0 to force the new pod to be able to take the Leader lease.

Once upgraded to 3.1.1, delete the temp CR/CRB

```bash  
oc delete clusterrolebinding/temporary-node-reader clusterrole/temporary-node-reader
```

**Comment by StevenBarre** [comment]
Followed up with Stuart to see if he is ready for PROD to be upgraded

**Comment by StevenBarre** [comment]
Upgraded in Silver, will be upgraded in other clusters soon
