### ISSUE TITLE
OCP 4.14 Review compatibility - CrunchyDB

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5011]
**Describe the issue**
Ensure that either the current installed version of the operator is compatible with the new OCP version, or an upgrade is completed.

<https://access.crunchydata.com/documentation/postgres-operator/latest/overview/supported-platforms>

- Current installed version: **v5.3.1**
- Does that version support OCP 4.14?: **no (supports up to OCP 4.13)**
- If no, what version do we need to update to?: **v5.5**

**Definition of done**
- [x] Current version is compatible, OR
- [x] Operator upgraded in all clusters

**Comment by wmhutchison** [comment]
Current version is not compatible with OCP 4.13, but a proposed PR by Cailey (https://github.com/bcgov-c/platform-gitops-gen/pull/914) will address this.

**Comment by wmhutchison** [comment]
@caggles Based on current knowledge of CrunchyDB, the currently installed version is not yet compatible with Openshift 4.14, but a CCM PR will fix this. If this PR is fully expected to be applied in the new week or so, then we're good. If not, then we'll need to know when since CrunchyDB support will be a blocker for Openshift 4.14 work. The PR in question is https://github.com/bcgov-c/platform-gitops-gen/pull/914

**Comment by wmhutchison** [comment]
@caggles My understanding from our meeting this week for CrunchyDB was that you would waive testing/etc in CLAB and move it to KLAB since KLAB doesn't get upgraded until a week prior to SILVER, none of which will happen until you're ready with your upgrade plans/etc.

To that end let me know when you'll have the cycles to upgrade CLAB to the required PGO version so that I can then start work on upgrading Openshift there for general testing/etc. If that's possible for the week of August 26th let me know. :)

**Comment by StevenBarre** [comment]
Or if we can just power ahead and not worry about CrunchyDB in its current version breaking on CLAB

**Comment by wmhutchison** [comment]
roger that, will move forward on my portion of remaining prep (F5 CIS upgrade) as time permits and then kick off CLAB upgrade officially.

**Comment by caggles** [comment]
We have a working option for Crunchy now. It's upgraded in KLAB. CLAB to follow with a proper PR in CCM.

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/923

**Comment by caggles** [comment]
CCM release is cut, will mark as completed when release is fully out in all clusters.
