### ISSUE TITLE
OCP 4.14 Review compatibility - EnterpriseDB

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5012]
**Describe the issue**
Ensure that either the current instlaled version of the operator is compatibale with the new OCP version, or an upgrade is completed.

<https://www.enterprisedb.com/resources/platform-compatibility>

- Current installed version: 
- Does that version support OCP 4.14?: 
- If no, what version do we need to update to?: 

**Definition of done**
- [ ] Current version is compatible, OR
- [ ] Operator upgraded in all clusters

**Comment by wmhutchison** [comment]
@caggles Adding you to this ticket since it's not immediately clear to me if there are any blockers for individuals who have EDB instances that will not work on Openshift 4.14 (or Kubernetes v1.27).

If such blockers exist, let's get that documented here so we can factor that later on once development/testing in CLAB/KLAB is done first.

**Comment by caggles** [comment]
No, no blockers for EDB!
