### ISSUE TITLE
OCP 4.14 Review compatibility - ACS

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5017]
**Describe the issue**
Ensure that either the current installed version of the operator is compatible with the new OCP version, or an upgrade is completed.

<https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_security_for_kubernetes/>

- Current installed version: 4.4.1
- Does that version support OCP 4.14?: Yes
- If no, what version do we need to update to?: 

**Definition of done**
- [x] Current version is compatible, OR
- [ ] Operator upgraded in all clusters

**Comment by StevenBarre** [comment]
https://access.redhat.com/articles/7045053

ACS 4.4 supports OCP 4.12 -> 4.16
