### ISSUE TITLE
OCP 4.14 Review compatibility - OpenShift AI

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5018]
**Describe the issue**
Ensure that either the current instlaled version of the operator is compatibale with the new OCP version, or an upgrade is completed.

<https://docs.redhat.com/en/documentation/red_hat_openshift_ai/>

- Current installed version:  2.11.0
- Does that version support OCP 4.14?: Yes
- If no, what version do we need to update to?: 

**Definition of done**
- [x] Current version is compatible, OR
- [ ] Operator upgraded in all clusters

**Comment by StevenBarre** [comment]
https://access.redhat.com/articles/rhoai-supported-configs

2.11.0 is supported on OCP 4.12 -> 4.16
