### ISSUE TITLE
OCP 4.14 Perform Pre-Upgrade steps in KLAB

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5042]
**Describe the issue**
There are several pre-upgrade steps to be performed before the OCP upgrade.

**Additional context**
Specific upgrade PR to follow for this ticket. <https://github.com/bcgov-c/advsol-docs/pull/318>

**Definition of done**
~~- [ ] Open a proactive case with RH on Friday for SILVER https://access.redhat.com/solutions/3521621~~
- [x] `oc --version` returns v4.14
- [x] Image registry pruned
~~- [ ] Trident upgraded~~
- [x] F5 CIS upgraded

**Comment by wmhutchison** [comment]
Crossed out items which either do not really belong in this ticket (SILVER proactive case, should be moved to SILVER prep ticket) or are already done (Trident upgrade).

**Comment by tbaker1313** [comment]
Pruning file is at /data/registry_hard_prune_mcs-klab-9.dmz-2024-09-10_12:16:14.txt

**Comment by vivekratan88** [comment]
completed.
