### ISSUE TITLE
OCP 4.14 Upgrade Openshift in KLAB

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5043]
**Describe the issue**
Run the OCP 4.14 upgrade in KLAB. Document if/where it gets stuck and any steps to work around it. Try and determine how disruptive the changes are to the API, Router, and hosted apps.

**Additional context**
CCM changes were merged, KLAB needs only to have its PR merged for OCP 4.14 changes to be applied there.
Specific upgrade PR to follow for this ticket. <https://github.com/bcgov-c/advsol-docs/pull/318>

**Definition of done**
- [x] KLAB upgraded to OCP 4.14
- [x] MachineConfig changes applied
- [x] CCM applied
- [x] EnCase updated
- [x] ETCD Backup updated
- [x] Nagios updated
- [x] Pruner updated
- [x] vROps updated
- [x] Logging updated
- [x] Sample Operator updated

**Comment by vivekratan88** [comment]
completed
