### ISSUE TITLE
OCP 4.14 Upgrade Openshift in SILVER

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5046]
**Describe the issue**
Run the OCP 4.14 upgrade in SILVER.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] SILVER upgraded to OCP 4.14
- [x] MachineConfig changes applied
- [x] CCM applied
- [x] EnCase updated
- [x] ETCD Backup updated
- [x] Nagios updated
- [x] Pruner updated
- [x] vROps updated
- [x] Logging updated
- [x] Sample Operator updated
- [x] Upgrade to OCP 4.14.37 when tested in KLAB/CLAB

**Comment by wmhutchison** [comment]
Day 1 (Monday) saw the core/backplane of Openshift upgraded, as well as the node upgrades for all master and infra nodes, and almost 1/2 of the app nodes.

Day 2 (Tuesday) saw some slow-down on the app nodes due to PDB issues and follow-up emails. Finished the day with  14 APP nodes remaining to upgrade. Hoping we'll finish these off on Day 3.

**Comment by wmhutchison** [comment]
Almost finished node upgrades. Working in tandem now on other more trivial upgrade checklist components to move things along. Saving logging stack upgrade to post-node upgrade.

**Comment by wmhutchison** [comment]
no new CCM release in SILVER this week to push, so QA'd CCM by making sure the gitops stack was still stable and console for ArgoCD still worked and showing sane results.

**Comment by StevenBarre** [comment]
4.14.37 core upgrade completed. 40 of 62 worker nodes updated.

**Comment by wmhutchison** [comment]
Upgrade of SILVER to 4.14.37 now complete. Moving ticket state to In-Review while final QA is performed, after which time RocketChat alerts will receive final confirmation that we've finished work formally on SILVER and update/close its RFC.

**Comment by wmhutchison** [comment]
Closing ticket, SILVER is formally upgraded along with recommended security errata.
