### ISSUE TITLE
OCP 4.14 Upgrade Firmware on affected SILVER nodes

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5047]
**Describe the issue**
Since we cannot apply HPE Firmware in the same fashion as Dell (Dell will auto-apply on the node's next reboot), this task will track effort spent after SILVER upgrade is completed to drain HPE nodes in SILVER to first relieve them of their workloads and then boot the node off the HPE SPP ISO. After that's done and rebooted again, we can put the node back into service.

**Old ISO(s) Applied:**

**ISO(s) Applied:**
P73557_001_gen10spp-2024.04.00.00-SPP2024040000.2024_0416.18.iso

**Checklist for Firmware updates**
- [x] Gen10 - mcs-silver-app-1.dmz
- [x] Gen10 - mcs-silver-app-2.dmz
- [x] Gen10 - mcs-silver-app-3.dmz
- [x] Gen10 - mcs-silver-app-4.dmz
- [x] Gen10 - mcs-silver-app-5.dmz
- [x] Gen10 - mcs-silver-app-6.dmz
- [x] Gen10 - mcs-silver-app-7.dmz
- [x] Gen10 - mcs-silver-app-8.dmz
- [x] Gen10 - mcs-silver-app-9.dmz
- [x] Gen10 - mcs-silver-app-10.dmz
- [x] Gen10 - mcs-silver-app-11.dmz
- [x] Gen10 - mcs-silver-app-12.dmz
- [x] Gen10 - mcs-silver-app-13.dmz
- [x] Gen10 - mcs-silver-app-14.dmz
- [x] Gen10 - mcs-silver-app-15.dmz
- [x] Gen10 - mcs-silver-app-16.dmz
- [x] Gen10 - mcs-silver-app-17.dmz
- [x] Gen10 - mcs-silver-app-18.dmz
- [x] Gen10 - mcs-silver-app-19.dmz
- [x] Gen10 - mcs-silver-app-20.dmz
- [x] Gen10 - mcs-silver-app-21.dmz
- [x] Dell  - mcs-silver-app-36.dmz
- [x] Dell  - mcs-silver-app-37.dmz
- [x] Dell  - mcs-silver-app-38.dmz
- [x] Dell  - mcs-silver-app-39.dmz
- [x] Dell  - mcs-silver-app-40.dmz
- [x] Dell  - mcs-silver-app-41.dmz
- [x] Dell  - mcs-silver-app-42.dmz
- [x] Dell  - mcs-silver-app-43.dmz
- [x] Dell  - mcs-silver-app-44.dmz
- [x] Gen10 - mcs-silver-master-01.dmz
- [x] Gen10 - mcs-silver-master-02.dmz
- [x] Gen10 - mcs-silver-master-03.dmz
- [x] Gen10 - mcs-silver-infra-01.dmz
- [x] Gen10 - mcs-silver-infra-02.dmz
- [x] Gen10 - mcs-silver-infra-03.dmz

Only nodes listed above are required.

**Definition of done**
- [x] Drain all nodes in sequence of their workloads and apply firmware SPP ISO

**Comment by wmhutchison** [comment]
SPP ISO downloaded to local laptop, md5sum check passed. Will copy early next week to working network share so that by week two of the SILVER RFC it'll be available to all who may participate on helping with the HPE firmware updates.

**Comment by tbaker1313** [comment]
Dell servers have all updated to the new firmware 2.22.1

**Comment by wmhutchison** [comment]
APP-17 ran into a PDB issue that I will follow up later since it'll require an email. Finishing first node drains on the last batch for the day and then will circle back.

**Comment by wmhutchison** [comment]
All nodes now firmware patched except these:
- MCS-SILVER-APP-17.DMZ. Stuck on one pod/PDB. Emailed but no response yet. Asked in internal email thread if we'll enforce the nuking of the blocking pod or not (non-PROD database).
- MCS-SILVER-APP-21.DMZ. ILOM license no longer present, so cannot use client to mount and boot off of ISO image. Vendor case opened to fix.

Worst case if these cannot be addressed today (Friday Sept 20th) we can revisit them next week after getting through the errata upgrades of Openshift in SILVER.

**Comment by tbaker1313** [comment]
Firmware on app-21 is updated - needed HPE case and new license issued due to a reset a few months ago.

**Comment by wmhutchison** [comment]
Moving to Blocked for now, we'll re-visit APP-17 when we're done with SILVER OCP take-2 next week.

**Comment by StevenBarre** [comment]
Was able to drain app-17 this morning and complete its firmware before starting the next upgrade round.

**Comment by wmhutchison** [comment]
Confirmed all nodes have been upgraded. Closing ticket.
