### ISSUE TITLE
OCP 4.14 Perform Pre-Upgrade steps in GOLDDR

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5053]
**Describe the issue**
There are several pre-upgrade steps to be performed during a Sunday Morning change window before the OCP upgrade.

**Additional context**
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Upgrade.md

**Definition of done**
- [x] Open a proactive case with RH on Friday https://access.redhat.com/solutions/3521621
- [x] `oc --version` returns v4.14
- [x] Image registry pruned
~- [ ] Trident upgraded~
- [x] F5 CIS upgraded
- [x] Stage Dell Firmware updates

**Comment by tbaker1313** [comment]
Pruning log is at /data/registry_hard_prune_mcs-golddr-9.dmz-2024-10-06_06:56:33.txt
