### ISSUE TITLE
pseudo code for registry quota auto approve process

### ISSUE THREAD

**Issue by w8896699** [BCDevOps/developer-experience#5082]
add more description

**Comment by w8896699** [comment]
```
function processQuotaRequest(request):
    namespace = request.namespace
    request_type = request.type  // "increase" or "decrease"
    resource_type = request.resource_type  // "CPU", "memory", "storage"
    requested_tier = request.requested_tier
    current_tier = getCurrentQuotaTier(namespace, resource_type)
    
    if request_type == "decrease":
        approveRequest(request)
        return "Approved - Decrease Request"

    if request_type == "increase":
        if resource_type == "CPU" or resource_type == "memory":
            total_limit = getNamespaceTotalLimit(namespace, resource_type)
            current_usage = getNamespaceUsage(namespace, resource_type)
            utilization_rate = getNamespaceUtilizationRate(namespace, resource_type)
            usage_to_limit_ratio = current_usage / total_limit

            if current_usage > 0.85 * total_limit and utilization_rate > 0.34 and usage_to_limit_ratio > 0.1:
                if requested_tier == current_tier + 1:
                    approveRequest(request)
                    return "Approved - CPU/Memory Increase Request"

        if resource_type == "storage":
            pvc_limit = getNamespacePVCLimit(namespace)
            pvc_usage = getNamespacePVCUsage(namespace)
            
            if pvc_usage > 0.8 * pvc_limit:
                if requested_tier == current_tier + 1:
                    approveRequest(request)
                    return "Approved - Storage Increase Request"

    return "Pending - Does not meet auto-approval criteria"

function getCurrentQuotaTier(namespace, resource_type):
    // Logic to retrieve the current quota tier for the namespace and resource type
    // Example: return 1 for small tier, 2 for medium tier, etc.

function getNamespaceTotalLimit(namespace, resource_type):
    // Logic to retrieve the total limit for the specified resource type in the namespace

function getNamespaceUsage(namespace, resource_type):
    // Logic to retrieve the current usage for the specified resource type in the namespace

function getNamespaceUtilizationRate(namespace, resource_type):
    // Logic to retrieve the utilization rate for the specified resource type in the namespace

function getNamespacePVCLimit(namespace):
    // Logic to retrieve the PVC limit for the namespace

function getNamespacePVCUsage(namespace):
    // Logic to retrieve the PVC usage for the namespace

function approveRequest(request):
    // Logic to approve the quota request
```
Decrease Request: Automatically approved regardless of the conditions.
Increase Request (CPU/Memory): Approved if the namespace meets the following:
Current usage exceeds 85% of the total limit.
Utilization rate is at least 35%.
Usage-to-limit ratio is greater than 10%.(may be, lets not implement it for now)
The request is only for the next quota tier.
Increase Request (Storage): Approved if the namespace has used more than 80% of its PVC limit and the request is for the next tier.

**Comment by w8896699** [comment]
## 1. Current Usage in Percentage
- **Definition**: Represents the proportion of the currently used resources compared to the total allocated quota limit in the namespace.
- Current Usage in Percentage=( Total Quota Limit/Current Usage)×100
- **Context**: This metric shows the resources already being consumed by the namespace relative to its current quota. For example, if a namespace is allocated 1000 CPU units and is currently using 850 units, the Current Usage in Percentage would be 85%.

## 2. Utilization Rate
- **Definition**: Refers to the efficiency of resource usage in the namespace. It compares the actual resource usage against the requested resource allocation.
- Utilization Rate=( Requested Resources Actual Usage )×100
- **Context**: This metric assesses how well the namespace is utilizing the resources it has requested. For example, if the namespace has requested 1000 CPU units but is only using 340 units, the Utilization Rate would be 34%. This helps determine whether the resources are being efficiently used or are underutilized.

## 3. Usage to Limit Ratio
- **Definition**: Compares the current resource usage to the total limit allocated for that resource in the namespace.
- Usage to Limit Ratio= Total Quota Limit/Current Usage
- **Context**: This ratio is a straightforward comparison of the amount of resources used versus the quota allocated. If a namespace is allocated 1000 CPU units and is using 100 units, the Usage to Limit Ratio would be 0.1 (or 10%). This metric provides a clear view of how much of the allocated quota is being consumed.


## Summary of Differences
- **Current Usage in Percentage** and **Usage to Limit Ratio** are closely related but expressed differently. Both measure the proportion of the current resource usage to the total quota, but one is expressed as a percentage and the other as a ratio.

- **Utilization Rate** is different in that it measures how efficiently the requested resources are being used, rather than how much of the allocated quota is being consumed. This rate gives insight into whether the resources requested are actually needed and used effectively.

## How They Relate to Quota Requests
- **Current Usage in Percentage**: Important for determining if a namespace is near its allocated limit and might need an increase.
- **Utilization Rate**: Useful for assessing whether the resources requested are being used effectively, which could justify an increase if the namespace is efficiently using its resources.
- **Usage to Limit Ratio**: Helps to understand the balance between usage and the allocated quota, indicating whether the current resources are being fully utilized.

**Comment by w8896699** [comment]
This is code I use to get Promql data:
```
export METRICS_TOKEN=$(oc whoami -t)
#export METRICS_URL=$(oc get route prometheus-k8s -o jsonpath='https://{.spec.host}' -n openshift-monitoring)
export METRICS_URL="https://prometheus-k8s-openshift-monitoring.apps.${CLUSTER}.devops.gov.bc.ca"

QUERY='max_over_time({__name__=~"namespace:container_cpu_usage:sum", namespace=~".*-(dev|test|prod|tools)"}[1w])'
export JSON_HIGHEST_CPU=$(curl -s -H "Authorization: Bearer ${METRICS_TOKEN}" -H "Content-Type: application/x-www-form-urlencoded" "${METRICS_URL}/api/v1/query?" --data-urlencode "query=${QUERY}")
debug "JSON_HIGHEST_CPU: $JSON_HIGHEST_CPU"

# Get total CPU requested in each namespace at this time
# ------------------------------------------------------
QUERY='sum by (namespace) ({__name__=~"namespace_cpu:kube_pod_container_resource_requests:sum", namespace=~".*-(dev|test|prod|tools)"})'
export JSON_REQUESTED_CPU=$(curl -s -H "Authorization: Bearer ${METRICS_TOKEN}" -H "Content-Type: application/x-www-form-urlencoded" "${METRICS_URL}/api/v1/query?" --data-urlencode "query=${QUERY}")
debug "JSON_REQUESTED_CPU: $JSON_REQUESTED_CPU"
```

**Comment by w8896699** [comment]
some query draft:
    a. namespace already use 85% of total limit(i.e: kube_pod_container_resource_limits/namespace-total-limit)(CPU or memory, or storage)
    b. namespace has at least 35% of CPU utilization rate(namespace:container_cpu_usage/namespace_cpu:kube_pod_container_resource_requests:sum > 35%, same idea for memory)

**Comment by w8896699** [comment]
PromQL doc: https://prometheus.io/docs/prometheus/latest/querying/basics/

useful cheat-sheet: https://promlabs.com/promql-cheat-sheet/

**Comment by junminahn** [comment]
https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time
