### ISSUE TITLE
Artifactory 7.84.20 upgrade

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#5087]
**Describe the issue**
Artifactory currently has a vulnerability. Upgrading to 7.84.20 will fix this.

**How does this benefit the users of our platform?**
Artifactory will remain secure.

**Definition of done**
- [x] upgrade artifactory in KLAB and CLAB
- [ ] upgrade artifactory in Gold and Gold DR

**Comment by IanKWatts** [comment]
We use the image from the RedHat image registry, but they do not have 84.20 yet.  Their latest version is still 84.14.  Cailey will contact them about when to expect to the new version.

**Comment by IanKWatts** [comment]
https://catalog.redhat.com/software/containers/jfrog/artifactory-pro/5d23783a69aea3638b1861bc?gs&q=jfrog
