### ISSUE TITLE
Provisioner update for cost management label

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#5098]
**Describe the issue**
In order to use the Cost Management tool in OpenShift, a namespace must have a certain label.  Update the provisioner's namespace template to include this label.

**What is the Value/Impact?**
Enable use of the Cost Management tool for all users

**What is the plan? How will this get completed?**
- Update `roles/tenant/templates/namespace.yaml.j2`, adding label: `insights_cost_management_optimizations: "true"`
- Commit the change
- Build a new version of the app-provisioner image, incrementing the minor version number by one
- Update the private cloud sensors in the provisioner's gitops repo for each environment (dev, test, prod)
- Verify the change by reprovisioning a test project that you control

**Identify any dependencies**
n/a

**Definition of done**
- [x] Implementation complete

**Comment by funtigr** [comment]
The label is added, the sensors are updated with the new versions and tested.
<img width="1474" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVcxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02f5ccf860d04e69a350087fd6f5c3f0bfb077ac/image.png" alt="image.png" />

@IanKWatts 
When changing the version of the Provisioner app, I updated the minor version (as instructed in the task description), but now I'm not sure if the change is big enough to increment the `minor` version. Maybe it would have been `patch` version? 
Now the version is `v4.3.0` but previously it was `v4.2.22`. 
I can change it to `v4.2.23` if needed.

**Comment by IanKWatts** [comment]
That's fine, just leave it as you have set it.
