### ISSUE TITLE
Update Benny Operator to use new Build secret

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5100]
**Describe the issue**
As of OCP 4.14, the build entitlement secret is now auto-created in an OpenShift namespace.
https://docs.openshift.com/container-platform/4.14/cicd/builds/running-entitled-builds.html#builds-source-secrets-entitlements_running-entitled-builds

We no longer need a cronjob to pick it up from a VM and push it into a namespace.

**What is the Value/Impact?**
Simpler automation

**What is the plan? How will this get completed?**
Remove the cronjob that picks up the secret from VMs and puts it into a secret.
Adjust the Benny operator to copy the new auto-created secret instead.

**Identify any dependencies**
OCP 4.14 upgrade in all clusters.
Needs work from both Ian and AdvSol

**Definition of done**
Can run a RHEL build in prod clusters without the old entitlement certs

**Comment by IanKWatts** [comment]
It seems that the Secrets exist in OCP 4.13 already, so no need to wait for the OCP upgrade to roll out the benny updates.

**Comment by IanKWatts** [comment]
We will keep the Benny Operator CronJob, because it uses this to check for changes, but it no longer logs in to Silver to check the cert, it just checks the local Secret.  By keeping this, the operator only updates everybody's secrets when there is a change.
