### ISSUE TITLE
Remove MCS_SDN_HighMem check from Nagios monitor image

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5107]
**Describe the issue**
In a significantly older version of Openshift, there were issues arising where inefficiently configured NetworkPolicy could cause issues with SDN containers where memory consumption would escalate as a symptom and result in inconsistent OVS changes affecting pod to pod access. The mentioned check was created to note this specific case and allow some measure of proactive  monitoring so we could check and identify the affected networkpolicy.

This is mitigated now with built-in checks for networkpolicy which will not allow a policy to be applied if the pod permutations would be excessive, thus ensuring this scenario will not happen again, thus no further need to check for it.

**Additional context**
[Documentation on the check involved.](https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Monitoring.md#mcs_sdn_highmem)

**How does this benefit the users of our platform?**
Having only required checks to be in place ensures appropriate resource and time management so that more time can be spent on other checks by the monitoring pod.

**Definition of done**
- [ ] PR changes to remove the check., test in LAB.
- [ ] Merge PR once approved, rebuild monitor image on all clusters.
- [ ] Remove check in Nagios once image is updated.

**Comment by vivekratan88** [comment]
removed lines of code with the metric and made PR for this https://github.com/bcgov-c/platform-tools/pull/206

**Comment by vivekratan88** [comment]
completed and tested it on CLAB.
