### ISSUE TITLE
Enable PromQL

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#511]
PromQL is a new feature that Sysdig is bringing to the platform which will enable certain types of math operations on collected metric data. This should enable us to build even more effective reporting dashboards.

**Comment by stewartshea** [comment]
I've reached out to Sysdig to determine when we can enable this feature .

**Comment by stewartshea** [comment]
It looks like this has been enabled now. I will continue to explore how this can help us going forward.

**Comment by stewartshea** [comment]
The new dashboard format has been enabled, but it looks like PromQL is still in the queue. I'll follow up. 

![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/fae35e41-03c7-4df8-9a9d-13d68ac8a4b3)

**Comment by stewartshea** [comment]
Waiting on a timeline from Sysdig TAM

**Comment by lukegonis** [comment]
@stewartshea can you please update this issue?

**Comment by stewartshea** [comment]
PromQL was finally enabled again. I am working on configuration for the agents to utilize this feature specifically with things like PV monitoring.
