### ISSUE TITLE
Create new inventory files for new SILVER physical nodes mcs-silver-app-77 through 88

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#5110]
**Describe the issue**
Added new inventory files for all the required new physical nodes. Add new inventory files to rhcos-ignition-builder repo in the branch new-physical-inv-silver . MAC Addresses are not known yet, so we'll fill those in later as possible. This is just to create the files and include the server name and the IP information we get from VRA.

**How does this benefit the users of our platform?**
We're replacing old servers with new ones to maintain the quality of service expected from the Openshift environment.

**Definition of done**
Inventory files created for:

- [x] mcs-silver-app-77.dmz
- [x] mcs-silver-app-78.dmz
- [x] mcs-silver-app-79.dmz
- [x] mcs-silver-app-80.dmz
- [x] mcs-silver-app-81.dmz
- [x] mcs-silver-app-82.dmz
- [x] mcs-silver-app-83.dmz
- [x] mcs-silver-app-84.dmz
- [x] mcs-silver-app-85.dmz
- [x] mcs-silver-app-86.dmz
- [x] mcs-silver-app-87.dmz
- [x] mcs-silver-app-88.dmz
- [x] SILVER main inventory file

**Comment by vivekratan88** [comment]
added mcs-silver-app-83.dmz till mcs-silver-app-88.dmz

https://github.com/bcgov-c/rhcos-ignition-builder/commit/a70c101c7c0b1da0b7c4acc2cb72f5a4452237d5

**Comment by StevenBarre** [comment]
Shouldn't there be a pull request for this?

**Comment by StevenBarre** [comment]
Makes sense. This ticket should probably go into Blocked then, and not be closed.

**Comment by tbaker1313** [comment]
This is currently blocked until we get the hardware to start merging these templated inventory files into the main branch. Need to update the MAC addresses when possible.

**Comment by tbaker1313** [comment]
Reserved the service console addresses so the servers can be installed.

**Comment by tbaker1313** [comment]
Created a new oneview template profile, one of the new 6 servers doesn't appear to be online, so will wait to add them until all are ready, then test one with the newly created GEN10 Plus MCS profile.

**Comment by tbaker1313** [comment]
Still blocked for the latest 6 nodes that we haven't had installed yet.

**Comment by tbaker1313** [comment]
This is completed, we will create a new ticket for the new MAC Addresses when possible.
