### ISSUE TITLE
INC0099773 - Briefly lost external network connectivity for Kamloops hosted Openshift clusters

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#5114]
**Describe the issue**
Clusters appeared to briefly lose come network connectivity, causing alerts from Uptime.com but did not trigger internal alerts, so it appears to be limited to external access to Openshift clusters that was impacted for about 2 minutes starting at 9:05 AM on August 23rd, 2024 - Opening an INC to investigate with the network team.

**Checklist**
- [x] Create an incident in theHUB
- [x] Contact the SPOC to elevate the INC to a P2
- [x] Post in [#devops-alerts](https://chat.developer.gov.bc.ca/channel/devops-alerts)
- [x] [Update](https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Status-Page.md) the [Status Page](https://status.developer.gov.bc.ca/)
~- [ ] Open a MS Teams call. Invite SPOC and someone from Platform Services to the call~
- [x] --> Solve the issue <--
- [x] Post in [#devops-alerts](https://chat.developer.gov.bc.ca/channel/devops-alerts)
- [x] [Update](https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/Status-Page.md) the [Status Page](https://status.developer.gov.bc.ca/)
~~- [ ] Work with SPOC to complete the Outage Report~~

**Comment by wmhutchison** [comment]
Moved to Block for now while we wait to see if SitMan needs an OR for this or not.

**Comment by wmhutchison** [comment]
No OR requested by Situation Management on this. Closing as complete.
