### ISSUE TITLE
Hardware Refresh for SILVER APP Nodes

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5115]
**Describe the issue**
Some hardware currently in use on the Openshift SILVER cluster is nearing its End of Life. Due to a vendor deal with the Province, instead of being replaced with Virtual Machines, the replacements for these nodes will be new hardware. This Epic will track all of the supporting tickets involved with completing this migration.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
All tickets assigned to this Epic are in a Closed state.

**Comment by tbaker1313** [comment]
First 6 SILVER nodes have been built.
