### ISSUE TITLE
Update docs on logging in with the oc CLI

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5116]
**Describe the issue**
OCP 4.14 (server and cli tool) add a new feature to allow logging in to the CLI via a browser tab by adding `--web` to the end of the command. Update the docs to show how to do this.

https://docs.openshift.com/container-platform/4.14/cli_reference/openshift_cli/getting-started-cli.html#cli-logging-in-web_cli-developer-commands
https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/openshift-projects-and-access/install-the-oc-command-line-tool/#test-oc-login

**What is the Value/Impact?**
Easier CLI logins

**What is the plan? How will this get completed?**
Open a PR against the docs and get it reviewed

**Identify any dependencies**
None

**Definition of done**
Docs updated

**Comment by ShellyXueHan** [comment]
doc updated
