### ISSUE TITLE
Modify the default % report on the Sysdig dashboard to show % or requests instead of limits

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#512]
The current Sysdig Teams dashboard template shows the % of limits, but it would be preferable to show % or requests. This will require the PromQL feature in order to perform math inside of the dashboards.

**Comment by stewartshea** [comment]
Additional updates;

- [ ] total pods
- [ ] total namespaces
- [ ] limits capacity
- [ ] look into removing non long-running pods from resource quota ?

**Comment by lukegonis** [comment]
@stewartshea can you please confirm if this is completed?

**Comment by stewartshea** [comment]
I feel this dashboard was completed and no further work is taking place.
