### ISSUE TITLE
Update docs to remove DeploymentConfig

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5120]
**Describe the issue**
As of OCP 4.14 DeploymentConfig is now deprecated. Update the docs anywhere it has sample DCs for users. There's a few locations that speak about processes that act on DCs (like pruning) that should stay.

Also create a doc detailing how to migrate DeploymentConfigs to Deployments.

https://access.redhat.com/articles/7041372 covers details on how to transition to Deployments.

**What is the Value/Impact?**
Prepare for when DCs are removed in a future version (not yet announced)

**What is the plan? How will this get completed?**
PR for any relevant docs

**Identify any dependencies**

**Definition of done**
Docs updated

**Comment by ShellyXueHan** [comment]
doc updated
