### ISSUE TITLE
Send email about DeploymentConfig deprecation

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5121]
**Describe the issue**
Send an email to all product owners and tech leads to inform them that DeploymentConfigs are now deprecated. While the date of when they will be removed is not yet known, it is better to start transitioning now.

So far it is known to not be removed in 4.16, so there is lots of time to transition.

**What is the Value/Impact?**
Prepare for a future deprecation of DeploymentConfigs

**What is the plan? How will this get completed?**
Draft email content and have it reviewed
Send an email to all PO/TL from the Registry

**Identify any dependencies**

**Definition of done**
Email sent

**Comment by ShellyXueHan** [comment]
email sent!
