### ISSUE TITLE
Isolate DB access without Aporeto

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#517]
Short term workaround to restrict ingress and egress traffic to a database through an API service.  This would be put in place until migration to OCP4 is complete.

allow ingress and egress access to a DB (ONLY):
- via an API deployment
- via Database Backup deployment
- via OCP health checks/etc.

**Comment by tosazuwa** [comment]
Testing of workaround in progress with @stewartshea and @WadeBarnes

**Comment by stewartshea** [comment]
One approach has been documented. A second approach, with sidecar configurations, is also being developed.

**Comment by jefkel** [comment]
Sidecar option is with Wade to test/validate.

**Comment by stewartshea** [comment]
That's not true. I'm documenting the second sidecar approach and then
sending it to him. The process works, but we need a clearer set of example
documentation
--
Shea Stewart (He/Him), Partner
Arctiq: Intelligent Architecture
shea.stewart@arctiq.ca
+1-647-972-5191
http://www.arctiq.ca
Book at meeting here: https://x.ai/calendar/sheastewart

Why I Put Pronouns on my Email Signature
<https://medium.com/gender-inclusivit/why-i-put-pronouns-on-my-email-signature-and-linkedin-profile-and-you-should-too-d3dc942c8743>

**Comment by lukegonis** [comment]
Sidecar option is with Wade to test/validate, Olena to follow up with Wade.

**Comment by lukegonis** [comment]
Waiting for feedback from @WadeBarnes
