### ISSUE TITLE
OCP NSX 4.14 Test OCP Upgrade in KLAB2

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5186]
**Describe the issue**
Run the OCP 4.14 upgrade in KLAB2. Document if/where it gets stuck and any steps to work around it. Try and determine how disruptive the changes are to the API, Router, and hosted apps.

**Additional context**
Make sure we are upgrading to the stable-4.14 channel

**Definition of done**
- [x] KLAB2 upgraded to OCP 4.14

**Comment by StevenBarre** [comment]
https://issues.redhat.com/browse/OCPBUGS-16089 was in 4.14.0 and switched the canary route to specify `spec.subdomain`. https://issues.redhat.com/browse/OCPBUGS-36467 was included in 4.14.34 and actually allowed the operator to update the route.

However, AKO appears to be unable to handle a route with just a subdomain specified. It can't correctly calculate the full hostname and so the Route never gets accepted by AKO.

Have opened a support case with Broadcom.

**Comment by StevenBarre** [comment]
Via https://access.redhat.com/support/cases/#/case/03936215 we were able to work around the AKO bug and complete the upgrade. The Ingress Operator remains degraded, but at least the other steps were completed.
