### ISSUE TITLE
INC0037756 MCS - Missing application logs

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#520]
Fluentd is throwing some errors and logs don't appear to be getting indexed properly.

**Comment by wmhutchison** [comment]
Issue was resolved by Steven Barre via identification and fixing of some missing RBAC rules which went away during a recent cluster role reconciliation. Red Hat via Matt Robson will be looking into this regarding determining why a standard reconciliation nuked standard RBAC access.

Confirmed via various users.
