### ISSUE TITLE
Switch Nagios alerting to the secondary servers for CLAB

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5218]
**Describe the issue**
The main Nagios server is used by all the OS teams and is a little overloaded. From time to time this generates false Stale alerts for us. The Nagios team has asked us to move our alerts over to the secondary servers that are less loaded.

**What is the Value/Impact?**
Less false alerts

**What is the plan? How will this get completed?**
- Update the playbooks to point at the new servers
- Run the register job to set up all the alerts on the new servers
- Remove the hosts/services from the old Nagios server

Do this for each cluster, one at a time, starting in LAB

**Identify any dependencies**
None

**Definition of done**
- [ ] CLAB switched over to secondary Nagios.
- [ ] Present top-level summary of instructions to follow for QA on remaining LAB clusters.

**Comment by vivekratan88** [comment]
worked on testing there seems to be some errors and its not picking up the changes will have to see what I can do further about this.

**Comment by vivekratan88** [comment]
more testing done it seems have errors with API Key looking into it

**Comment by vivekratan88** [comment]
Got new API key and the API key errors seem to be gone, the Nagios job work and so does monitoring working on the remaining jobs

**Comment by vivekratan88** [comment]
The key was expired hence API key error, so we had to send ticket to Rowan to make settings from his end and the key works now. Found the steps and solved one monitor job with Steven and group then later did the remaining 4 jobs now doing DHCP check metric which seems to have shell script which is running in different namespace and working on troubleshooting that the build works with logs been positive and no issues but not able to get rid of the dhcp stale check. I am comparing how it is configured in SILVER now and see if it's any different.

**Comment by vivekratan88** [comment]
Fixed the DHCP and proxy issues and it works in CLAB

**Comment by vivekratan88** [comment]
Making RFC for this and sending for approval.

**Comment by vivekratan88** [comment]
provided RFC steps for approval, document under review

**Comment by wmhutchison** [comment]
Creating an Epic to put this ticket under, and then will change the scope of this ticket for reflecting work done for CLAB. Future tickets under the same Epic will then include work on KLAB, and then work on remaining PROD clusters.

**Comment by vivekratan88** [comment]
RFC doc review done




From: Hutchison, William <William.Hutchison@dxcas.com> 
Sent: Wednesday, October 30, 2024 3:01 PM
To: Ratan, Vivek <Vivek.Ratan@dxcas.com>; Hosting Services Managed Container Services <hsmcs@dxcas.com>
Subject: RE: Nagios Passive to Active steps

Thanks for the input. Will circle back to this once I finish clearing a few other things and then get a final list of things including SAM and get all parties to sign off before I take a look at doing the change to KLAB. 😊

Cheers,

William Hutchison
Intermediate Container Operations Analyst, Infrastructure Services 
M 250.410.2369
william.hutchison@dxcas.com

Advanced Solutions, a DXC Technology Company
Suite 1101 – 4464 Markham Street
Victoria, BC  V8Z 7X8
 

From: Ratan, Vivek <Vivek.Ratan@dxcas.com> 
Sent: Wednesday, October 30, 2024 2:24 PM
To: Hutchison, William <William.Hutchison@dxcas.com>; Hosting Services Managed Container Services <hsmcs@dxcas.com>
Cc: Ratan, Vivek <Vivek.Ratan@dxcas.com>
Subject: RE: Nagios Passive to Active steps

Hi Will,

Good afternoon!

Thanks for providing feedback. I have adjusted it as per your comments.
Also added Step 8 which is necessary step to delete the passive entries so they get automatically populated in active namespace it might take around 10 to 15 mins for it to do that work.

Thanks for your time and help!

Vivek Ratan
Technical Analyst – VMware

Desk: 250.405.4500x4702
Vivek.Ratan@dxcas.com

Advanced Solutions, a DXC Technology Company
Suite 1101 - 4464 Markham Street 
Victoria, BC V8Z 7X8
http://www.dxcas.com

The information transmitted herein is intended only for the named recipient(s) above, and may contain information that is privileged, confidential, or exempt from disclosure under applicable law. If you have received this message in error, or are not the named recipient(s), please immediately notify the sender by replying to this email and delete this message from all computers. Thank you



From: Hutchison, William <William.Hutchison@dxcas.com> 
Sent: Wednesday, October 30, 2024 3:01 PM
To: Ratan, Vivek <Vivek.Ratan@dxcas.com>; Hosting Services Managed Container Services <hsmcs@dxcas.com>
Subject: RE: Nagios Passive to Active steps

Thanks for the input. Will circle back to this once I finish clearing a few other things and then get a final list of things including SAM and get all parties to sign off before I take a look at doing the change to KLAB. 😊

Cheers,

William Hutchison
Intermediate Container Operations Analyst, Infrastructure Services 
M 250.410.2369
william.hutchison@dxcas.com

Advanced Solutions, a DXC Technology Company
Suite 1101 – 4464 Markham Street
Victoria, BC  V8Z 7X8
 

From: Ratan, Vivek <Vivek.Ratan@dxcas.com> 
Sent: Wednesday, October 30, 2024 2:24 PM
To: Hutchison, William <William.Hutchison@dxcas.com>; Hosting Services Managed Container Services <hsmcs@dxcas.com>
Cc: Ratan, Vivek <Vivek.Ratan@dxcas.com>
Subject: RE: Nagios Passive to Active steps

Hi Will,

Good afternoon!

Thanks for providing feedback. I have adjusted it as per your comments.
Also added Step 8 which is necessary step to delete the passive entries so they get automatically populated in active namespace it might take around 10 to 15 mins for it to do that work.

Thanks for your time and help!

Vivek Ratan
Technical Analyst – VMware

Desk: 250.405.4500x4702
Vivek.Ratan@dxcas.com

Advanced Solutions, a DXC Technology Company
Suite 1101 - 4464 Markham Street 
Victoria, BC V8Z 7X8
http://www.dxcas.com

The information transmitted herein is intended only for the named recipient(s) above, and may contain information that is privileged, confidential, or exempt from disclosure under applicable law. If you have received this message in error, or are not the named recipient(s), please immediately notify the sender by replying to this email and delete this message from all computers. Thank you
