### ISSUE TITLE
Platform Business Continuity Planning

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#522]
As me and @caggles will be away during July 2-3, it's a good timing now to start some templates for BCP.

### Who and When:
- Shelly and Cailey
- July 2-3

### Potential Impacts:
- service downtime or interruption of platform services, such as SSO and RocketChat
- postponed application team on-boarding

### Platform Services Coverage Plan:
- [x] **RocketChat:**
- Coverage Details: RC service downtime
- Contact: Phil (RC @phil.arctiq) and Patrick (RC @patrick.simonian)

- [x] **KeyCloak:** 
- Coverage Details: issues and downtime of dev/test/prod SSO Services; urgent community support and troubleshoot
- Contact: Wade Barnes (RC account @wade.barnes)

- [x] **DevOps requests:**
- Coverage Details: pause on handling new DevOps requests ticket during the two days
- Contact: Setup a notification for temporary leave and service resume from next week

@caggles anything else I'm missing here?

**Comment by juhewitt** [comment]
looks good Shelly.  let me know when you find Rocket.Chat support.

**Comment by ShellyXueHan** [comment]
@patricksimonian @filiy Please let us know if there are still any further access you would need for taking care of rocketchat? And @WadeBarnes for SSO, if you need anything?

Thank you!

**Comment by ShellyXueHan** [comment]
Update: all prep works (requestron message setup, RC and SSO knowledge transfer) have been completed. Will keep this ticket open until me and @caggles are back.
