### ISSUE TITLE
Migrate RocketChat to chat.developer.gov.bc.ca

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#523]
We need to migrate RocketChat off the chat.pathfinder.gov.bc.ca DNS to chat.developer.gov.bc.ca in preparation to migrating it to OCP 4 Platform.

- [ ] create DNS for *.chat.developer.gov.bc.ca
- [ ] test certs for *.chat.developer.gov.bc.ca
- [ ] migrate RC urls
- [ ] update RC maintenance note with new URL and disclaims/clarification on usage

**Comment by ShellyXueHan** [comment]
@mitovskaol do we have tickets for all other platform services migration? Shall we create an epic/label to group them?

**Comment by mitovskaol** [comment]
@ShellyXueHan Yes, we need to create an epic in OCP 4 ZenHub for the Platform Services app migration and track this work there.

**Comment by ShellyXueHan** [comment]
@jleach I see you are working on this ticket, do you have an Epic/tickets created separately? If so please close this one. Thanks!

**Comment by jleach** [comment]
Closing this one. I've have separate tickets for Dev, Test and Prod that include the tests mentioned above.
