### ISSUE TITLE
Upgrade Grafana Operator to v5 on all clusters

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5231]
**Describe the issue**
Manual investigation of this Operator revealed that while the current installation still functions (v4), it is no longer a version maintained actively and thus should be migrated to the newer and supported v5 branch. This ticket will track effort spent towards the research and development of this upgrade in a LAB cluster, and implement as needed on all PROD clusters. Additional documentation will be created in the form of new tickets using the ZenHub OCP upgrade ticket generator so that this operator will not be forgotten in future upgrades.

**Additional context**
[Github page for Grafana Operator](https://github.com/grafana/grafana-operator)

**How does this benefit the users of our platform?**
This benefits internal users (Platform Services and Platform Operations) by having software which is directly still maintained with bugfixes and new features.

**Definition of done**
- [x] Upgrade Grafana in a LAB cluster and work out all of the issues.
- [x] Test the upgrade in remaining LAB clusters.
- [x] Submit suitable CCM PR to promote into PROD clusters.
- [x] Submit PR for adding a ticket to track this operator in future Openshift upgrades.

**Comment by wmhutchison** [comment]
Operator repo provides the following link for migrating from v4 to v5. Will inspect our  manifests to see if we'll need to modify our Custom Resource content or not. https://grafana.github.io/grafana-operator/blog/2023/05/27/v4-to-v5-migration/

**Comment by wmhutchison** [comment]
Throwing back into Backlog for now. Will promote forward at a later date, or someone else will pick this up instead.

**Comment by StevenBarre** [comment]
Steps to run after the sync to let it have a clean start

```bash
oc delete clusterrole/grafana-proxy clusterrolebinding/grafana-proxy clusterrolebinding/grafana-view
oc -n openshift-bcgov-grafana delete sub,csv,installplans --all
```

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/966

**Comment by StevenBarre** [comment]
https://github.com/bcgov-c/platform-tools/pull/216

**Comment by StevenBarre** [comment]
Updated in all prod clusters
