### ISSUE TITLE
Plan for Platform Services DR sites on cloud

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#524]
Initiate discussion with internal team and the community on desired DR site/strategy for:
- RocketChat
- KeyCloak

First draft of DR plan for rocketchat:
https://github.com/BCDevOps/developer-experience/blob/master/docs/DRSites/Plan.md

## Updates:
1. RocketChat full DR on cloud is not available for now:
  - we do not have SSO DR site yet. As there's no way to guard the DR site, better not provide the chat content
  - current cluster only allows for http traffic, which does not provide options to auto sync up databases across data centers (explore how that could be done until OCP4 is setup)
  - there is no access to the backup data when cluster is down
  - if cluster is still up and running, no need to switch over to cloud for DR. Can do it within/between the namespace
2. feasible DR plans for
  - RC: vanilla instance (no history, no SSO)
  - KC: not able to do that. It will need a DB backup outside of the cluster for restoring (need more discussion)
3. Something to consider now:
  - migrate *.pathfinder apps to their own DNS!
  - and request for individual DNS entry for different instances (from sandbox to prod). So that when any instance go down, we/DXC/whoever can switch it from the load balancer to point to DR site on another cluster! (details also depend on what's implemented on OCP4)

Further discussion is required.

**Comment by juhewitt** [comment]
As per my brief banter in Rocket.Chat, Option 2 for me.  Full on DR.

**Comment by mitovskaol** [comment]
Looping @NickCorcoran on this discussion to understand the implications of hosting KeyCloack SSO data outside of Kamloops data center. The ARO cluster in the Canada region , somewhere in Quebec I believe, so we would still be on the Canadian soil but not on the BC infrastructure.

**Comment by ShellyXueHan** [comment]
## Updates:
Here are the main steps to start as planned:
(@caggles and I will create zenhub tickets to track)

### For RC:
- spin up RC maintenance instance in cloud
- update RC maintenance note with new URL and disclaims/clarification on usage

### For KC:
- continue on oidc migration
- after that's done, migrate to ocp4 cluster

### What else:
- identify other platform apps
- create individual DNS entry for those services
- migrate services to new url
- migrate to an OCP4 cluster

**Comment by caggles** [comment]
### For Artifactory:

- separate the artifactory DNS entry from the rest of *.developer.gov.bc.ca so the two entries can be changed without affecting each other.

**Comment by ShellyXueHan** [comment]
@caggles Epic created here: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/541

**Comment by ShellyXueHan** [comment]
Update: tickets and epics created. Closing now.
