### ISSUE TITLE
Decommission 12 Silver nodes that have reached end of life

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5242]
**Describe the issue**
iStore Order for: 
Date Submitted: Sep 24, 2024
iStore Number: 1171488
Lead time (business days after EA Approves):

**Definition of done**
- [x] Business area creates/submits order
- [x] CITZ Service Desk reviews order, creates iStore Number, sends to EA for Approval
- [x] EA Approves 
- [x] Order is sent to DXC for fulfillment 
- [ ] Once order is fulfilled/shipped by DXC, CITZ Service Desk sends 'Completed Order' notification to business area

![iStore Order Lifecycle.png](https://images.zenhubusercontent.com/5c115ac27387c610cbb1fa12/5f6e0294-409d-47ee-b166-d14111c9fa88)

**Comment by StevenBarre** [comment]
Nodes 10 to 21 are being refreshed with new hardware as they have reached the end of their 5 year lifecycle

**Comment by MarisaBC** [comment]
September 27, 2024: Service Request Item [RITM0871404](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fociomysc.service-now.com%2Fsp%3Fid%3Dform%26table%3Dsc_req_item%26sys_id%3D455cf9d347709a9878253e62846d4386%26view%3Dess&data=05%7C02%7CMarisa.Wu%40gov.bc.ca%7Ca8961eb914c943bdc5f908dcdf254024%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638630598279811780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=yaPUcNI2SwHGn5gZAisMdFAsKjaF5obTlZ0GfhQCrkg%3D&reserved=0) has been opened: Servers not showing up in iStore: mcs-silver-app-10.dmz and more

**Comment by StevenBarre** [comment]
Will be decommissioning the first 6 nodes on Thur Oct 31. At the same time, 6 of the new nodes will be handed over.
Then the decommed nodes can be un-racked and the other 6 new nodes put in the rack.

**Comment by StevenBarre** [comment]
Second batch decommed
