### ISSUE TITLE
Add PDB responsibility to MOU table

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#5244]
**Describe the issue**
work with Pilar on this change

**Definition of done**
- [x] PDB added to MOU
- [x] add a link reference to the MOU table to the onboarding doc page

**Comment by Pilargit12** [comment]
- [x] Update done - PR also updated and corrected
- [x] Sent to Content design and communications team - Kaitlyn Rosenburg to upload new updated **Shared responsibilities model for the private cloud OpenShift platform.pdf** file
- [ ] Upload and republishing completed

**Comment by lukegonis** [comment]
Currently waiting for the Content Design Team to decide on their file hosting solution
