### ISSUE TITLE
Switch Internal Nagios monitoring for KLAB and KLAB2 to use Nagios XI-ACTIVE

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5274]
**Describe the issue**
The main Nagios server is used by all the OS teams and is a little overloaded. From time to time this generates false Stale alerts for us. The Nagios team has asked us to move our alerts over to the secondary servers that are less loaded.

**Additional context**
The DXC Monitoring team will need to be actively involved from this point forward to ensure that during these migrations, that historical data is being preserved.

**How does this benefit the users of our platform?**
Less false alerts for Platform Operations to deal with, leaving more time for them to work on other things.

**Definition of done**
- [x] Coordinate with DXC Monitoring with proposed workflow to refine a final workflow.
- [x] Test the new Workflow on KLAB.
- [x] Adjust workflow details if required from lessons-learned on KLAB.
- [x] Test final workflow on KLAB2.

**Comment by wmhutchison** [comment]
Will add some priority to this to get something out there for KLAB to review before the end of the week.

**Comment by StevenBarre** [comment]
Registered KLAB on Nagios TEST. Put in ticket to get data ported over.
TEST is still missing a few firewall/snat rules to allow the active checks to succeed.

**Comment by StevenBarre** [comment]
All labs now moved to TEST
