### ISSUE TITLE
Update Provisioner to work around project names in AlertManagerConfigs

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#5281]
**Describe the issue**
Now that AlertManagerConfigs have been updated to include the project name in the email that gets sent out, a project name with quotation marks in it creates a broken template.  Update the provisioner to work around this issue.

**What is the Value/Impact?**
ArgoCD cannot sync a project set when a manifest is not parsable.

**What is the plan? How will this get completed?**
Update the AlertManagerConfig template and rebuild the app-provisioner image.
Update the Argo Workflow sensors to use the new image.

**Identify any dependencies**
n/a

**Definition of done**
- [x] app-provisioner is updated
- [x] Provisioner is updated

**Comment by StevenBarre** [comment]
I wonder if we can do some better escaping in the Jinja to be able to accept quotes and other problematic characters? It would be nice if the email could have the name as entered in the Registry instead of striping out chars.

But if its going to be a huge pain, I'm onboard with doing whatever is easiest.

**Comment by IanKWatts** [comment]
Double quotes are not a problem.  For single quotes, adding a backslash does not help.  Not sure what it would take, but I'm open to suggestions.  Otherwise I'll go with the simple fix for now.

**Comment by IanKWatts** [comment]
Fixed using Steven's suggestion to move the problematic bits to a new line so that the enveloping single quotes are no longer required.
