### ISSUE TITLE
Create Nagios implementation to create tickets in theHUB automatically

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#5311]
**Describe the issue**
Will flesh this out - Nagios should create a HUB ticket and possibly tie into AAP.

**Additional context**
Add any other context, attachments or screenshots

**How does this benefit the users of our platform?**

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by vivekratan88** [comment]
https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/eventhandlers.html the event handler smaple we can use 


`define command{    command_name    create_servicenow_ticket    command_line    /usr/bin/path/to/your/script/<ansibleplay/script or whatever you want> "$HOSTNAME$" "$SERVICENAME$" "$SERVICESTATE$" "$SERVICEOUTPUT$"} `  need to make a script that also evokes service now
