### ISSUE TITLE
OCP 4.16 Review Release Notes - William

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5361]
**Describe the issue**
Review the [OCP 4.16 Release Notes](https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/release_notes/ocp-4-16-release-notes) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

## OCP 4.15 Release Notes

1. Node uptime information.
- Link: https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#node-uptime-information
- Scope: internal
- Notes: Nice to know this will exist starting in OCP 4.15, saves some SSH checks which is good since access via SSH is frowned upon in general.

2. Quality of Life for Administrator view
- Link: https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-administrator-perspective
- Scope: internal
- Notes: Enable and disable tailing to pod log viewer to minimize load time. Might be not really that useful in terms of performance in exchange for usefulness. I don't look at pod logs via web console much at all, but that doesn't mean my colleagues don't.

3. Pipelines Enhancements
- Link: https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-software-supply-chain-enhancements
- Scope: public
- Notes: Good for folks making good use of Pipelines in a more complex fashion in their namespaces.

4. Configuring the Whereabouts IP reconciler schedule
- Link: https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-configuring-whereabouts-IP-reconciler-schedule
- Scope: internal
- Notes: Not sure if we'd use this right away, but good to know it exists, since I think I recall once this being an issue in NSX-side for the limited pool of MGMT IPs for things like Nagios pods.

5. Detach CSI volumes after non-graceful node shutdown is generally available
- Link: https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-storage-non-graceful-node-shutdown
- Scope: internal
- Notes: This might prove to be useful (perhaps) for cases where a node crashed and is holding some PVCs hostage but isn't yet in a position for reboot. Will need more examination to see if this holds true or not.

6. The /dev/fuse device enables faster builds on unprivileged pods
- Link: https://docs.openshift.com/container-platform/4.15/release_notes/ocp-4-15-release-notes.html#ocp-4-15-nodes-dev-fuse
- Scope: public
- Notes: faster builds for the community certainly sounds nice.

7. Avoid caching etcdctl on cluster-backup.sh
- Link: https://issues.redhat.com/browse/OCPBUGS-19052
- Scope: internal
- Notes: This will need to be checked into as it pertaints to vendor-supplied backup scripts. Our own changes/methods might need to factor this in, or might be moot.

8. Internal Registry - Intermittent 504 Gateway Time-out
- Link: https://issues.redhat.com/browse/OCPBUGS-18999
- Scope: internal
- Notes: While not often, I do believe this issue has happened on occasion affecting users. Good to know about the issue and its root cause/resolution.

9. Improved consistency regarding duplicate route definitions.
- Link: https://issues.redhat.com/browse/OCPBUGS-16707
- Scope: internal
- Notes: While not likely something needing to be spread to the community, it's good for us to know that route duplication will now be handled in a consistent fashion. May or may not qualify for including in future OCP 101/201 training.

## OCP 4.16 Release Notes

1. A pod’s last termination state is now available to view on the Container list and Container details pages.
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-administrator-perspective_release-notes
- Scope: internal
- Notes: Nice to see this is available elsewhere than inspecting JSON/YAML of a pod resource which can get quite spammy to wade through depending on the complexity of the pod.

2. Handling CSR requests for nodes in web console.
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-node-csr-handling
- Scope: Internal
- Notes: Sounds convenient for us when we (re)build nodes, but will wait to see how it works and if it truly is an improvement or not.

3. oc - Warning for duplicate resource short names
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-duplicate-short-name-warning_release-notes
- Scope: Internal
- Notes: good to know about, but otherwise probably not important enough to inform the community about.

4. AdminNetworkPolicy is generally available
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-anp
- Scope: Internal
- Notes: Given the scope involved regarding NetworkPolicy, this might bear a quick peek at regarding what it does and if NSX supports it. It might grant us the ability to disable en-mass certain specific things using this new resource, but needs more investigation as to how it actually works and if it's something that will be supported by NSX or if it's a local OVN thing.

5. Garbage collection of unused rendered machine configs
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-machine-config-operator-gc_release-notes
- Scope: Internal
- Notes: Glad this is a thing, since an "oc get mc" on our various clusters can get quite spammy.

6. Additional information collected by must-gather
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-must-gather-directory_release-notes
- Scope: Internal
- Notes: including logs for the must-gather process is helpful for up-front documentation to support for cases when we're trying to run a must-gather on a cluster where problems exist which may affect the gathering process itself.

7. ClusterMonitoringOperatorDeprecatedConfig
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-monitoring-changes-to-alerting-rules
- Scope: internal
- Notes: this will be helpful in the future to ensure we're aware of deprecated metrics fields, in case our custom Grafana dashboard needs adjustments.

8. Metrics Server component to access the Metrics API general availability (GA)
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-monitoring-metrics-server-to-access-metrics-api-ga
- Scope: internal
- Notes: This will bear investigation since it mentions existing Prometheus adapter pods going away and being replaced. Will see if the replacement is useful to us or not.

9. Change in how Prometheus handles duplicate samples
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-monitoring-change-in-how-prometheus-handles-duplicate-samples
- Scope: internal
- Notes: We might see more PrometheusDuplicateTimestamps alerts in the future because of this, which is probably good since identifying/resolving these issues helps reduce overall Prometheus load.

10. Cluster Samples Operator deprecated
- Link: https://docs.openshift.com/container-platform/4.16/release_notes/ocp-4-16-release-notes.html#ocp-4-16-deprecation-samples-operator_release-notes
- Scope: internal
- Notes: Will eventually result in the removal of a step for our upgrade process which is to review new images and ask others if we're to exclude any of them or just stick to excluding newer versions of existing excluded images.
- 
**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [ ] Fully read the release notes and added anything of interest as a comment here

**Comment by wmhutchison** [comment]
Adding an internal reminder to complete this before I go on vacation.

**Comment by wmhutchison** [comment]
dumped on OCP 4.15 release notes observations at the top of the ticket. Now onto OCP 4.16.

**Comment by wmhutchison** [comment]
dumped OCP 4.16 release notes observations at the top of the ticket as well. closing ticket.
