### ISSUE TITLE
OCP 4.16 Review Release Notes - Ian

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5367]
**Describe the issue**
We're doing a double upgrade this round.

Review the [OCP 4.15 Release Notes](https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/release_notes/ocp-4-15-release-notes) and [OCP 4.16 Release Notes](https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/release_notes/ocp-4-16-release-notes) for any changes that will impact the product teams, ops team, or platform services team. Also look for any exciting new features that community should know about.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Read the release notes. Add any bits you find interesting and needing of discussion as comments here.

**Identify any dependencies**
None

**Definition of done**
- [x] Fully read the release notes and added anything of interest as a comment here

**Comment by IanKWatts** [comment]
**4.16**
* Kubernetes, 1.28 -> 1.29 (required Kyverno upgrade, which is done)
* Web console admin view: A pod’s last termination state is now available to view on the Container list and Container details pages.
* Web console developer view: When searching, a new section was added to the list of Resources on the Search page to display the recently searched items in the order they were searched.
* Vault secrets can be mounted by creating a 'SecretProviderClass' in the namespace, part of the Secrets Store CSI Driver Operator (tech preview) - would this be available to users?  https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html-single/nodes/index#secrets-store-vault_nodes-pods-secrets-store
* Legacy service account API token secrets are no longer generated for each service account, which is for the internal image registry.

**4.15**
Didn't see anything particularly interesting.
