### ISSUE TITLE
Install EDB on OCP 4

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#537]
We now have access to the EDB Operator to test an installation of EDB on openshift 4. I would like to install EDB on OCP at least once to see how it goes and to provide an instance I can explore to learn about EDB.

I need to know about getting access to the enterprise license so I can install the right version of postgres with the operator.
There is a limited amount of documentation available from EDB at the moment, so I will also be providing some feedback on what docs they have.

This task is timeboxed, so there is no definition of done - this task will be considered complete after I spend a couple of days experimenting with the operator just to see how it works, regardless of how far I actually get with that. I will provide feedback to EDB based on how far I get.

**Comment by caggles** [comment]
EDB OCP4 images are not yet available.

**Comment by mitovskaol** [comment]
@caggles Any update on the images yet?

**Comment by caggles** [comment]
Update: EDB has purchased another company and they're currently working on combining their operators into one big operator. This is expected to be finished in January. We have discussed working with them to test a beta version of their operator before then, but we will not be able to really consider moving to EDB until Jan.

**Comment by caggles** [comment]
closing because it's too big a ticket - it needs to be split up into pieces.
