### ISSUE TITLE
OCP 4.16 Send Mail about the Upgrade

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5371]
**Describe the issue**
After the team meets to discuss the [OCP 4.16 Release Notes](https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/release_notes/ocp-4-16-release-notes), draft and send an email to product teams outlining what they need to know about the coming upgrade.

**What is the Value/Impact?**
Ensure the product teams are kept informed about changes.

**What is the plan? How will this get completed?**
Compile the notes from the meeting into an email for Platform Admins to send.

**Identify any dependencies**
Must have the meeting with the team first.

**Definition of done**
- [x] Email sent

**Comment by ShellyXueHan** [comment]
hi Steven! where can i find the draft message?
