### ISSUE TITLE
PRB0041013 CITZ - MCS - Problem ticket to track HPE unexpected reboots

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#5389]
**Describe the issue**
This ticket will track effort spent investigating some recent reboot issues in SILVER involving HPE gear and no discernable hardware events causing the reboot.

**Additional context**
Vendor cases:
- <https://access.redhat.com/support/cases/#/case/03990081> (ACTIVE)
- <https://access.redhat.com/support/cases/#/case/03990059> (CLOSED)

Related incidents:
- [MCS-SILVER-APP-77.DMZ](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5312)
- [MCS-SILVER-INFRA-02.DMZ](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5313)
- [MCS-SILVER-INFRA-03.DMZ](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5388)
- [MCS-SILVER-APP-79.DMZ](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5461)
- [MCS-SILVER-APP-03.DMZ](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/gh/bcdevops/developer-experience/5464)

Hardware servers but no hardware support tickets since this is not a hardware issue.

**How does this benefit the users of our platform?**
Ensuring we have stable nodes to offer a consistent experience for our users.

**Definition of done**
- [x] Open vendor case(s) for this
- [ ] Obtain resolution or equivalent feedback from vendor
- [ ] Implement fix when able.

**Comment by wmhutchison** [comment]
https://access.redhat.com/support/cases/#/case/03990081 is the active case right now. Based on support feedback, the root cause is the kernel.

The RHEL9 kernel fix: <https://access.redhat.com/errata/RHSA-2024:9497>
Link for showing OCP releases and specific kernel version: <https://access.redhat.com/solutions/7077108>

We are waiting for Red Hat to put out an OCP version with the required kernel. Since OCP 4.14.41 dropped on November 20th without the new kernel, we'd be waiting for OCP 4.14.42 to drop with this.

At present we'll likely be continuing on coarse with fixing this in the official OCP 4.16 upgrade, but if this issue worsens, we might need to re-think this and apply an OCP 4.14-latest in SILVER as soon as possible.

**Comment by wmhutchison** [comment]
Priority RFCs are also created and will be implemented to upgrade OCP 4.14 to a version with a kernel fix for this issue.

CHG0064967 CITZ - MCS SILVER - Starting December 2nd at 9 AM and running until December 6th at 5 PM
CHG0064977 CITZ - MCS EMERALD - Starting December 2nd at 9 AM and running until December 6th at 5 PM
CHG0064978 CITZ - MCS GOLD - Starting December 9th at 9 AM and running until December 13th at 5 PM
CHG0064980 CITZ - MCS GOLDDR - Starting December 16th at 9 AM and running until December 20th at 5 PM

**Comment by tbaker1313** [comment]
No further problems found.
