### ISSUE TITLE
New Artifactory Operator Documentation

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#539]
With the new artifactory operator,  I would like to rewrite the documentation that exists for the way the operator works and how teams can use it. 

This has two benefits: it updates the documentation for teams to use properly, and it explaining how it works requires that I develop a deep understanding of the operator myself.

DOD: completed documentation on devhub that outlines the basic function of the operator and detailed explanations of how the teams can use it, checked by @jefkel to ensure that it is accurate.

**Comment by lukegonis** [comment]
This is a duplicate, will be tracked in the OCP4 board
