### ISSUE TITLE
OCP NSX 4.14 Test OpenShift Upgrade in KLAB2

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5451]
**Describe the issue**
Run the OCP 4.14 upgrade in KLAB2. Document if/where it gets stuck and any steps to work around it. Try and determine how disruptive the changes are to the API, Router, and hosted apps.

**Additional context**
Make sure we are upgrading to the stable-4.14 channel

**Definition of done**
- [x] KLAB2 upgraded to OCP 4.14

**Comment by tbaker1313** [comment]
Completed.
