### ISSUE TITLE
Investigate Operator SDK CLI tool deprecation

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#5472]
**Describe the issue**
4.16 deprecates the Operator SDK CLI tool . Does this impact our custom operators like Porter, Warden, etc ?

https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html/release_notes/ocp-4-16-release-notes#ocp-4-16-deprecation-operator-sdk_release-notes

**What is the Value/Impact?**
Ensure future compatibility

**What is the plan? How will this get completed?**
Review docs and determine if any action is needed

**Identify any dependencies**
None

**Definition of done**
- Changes do not impact us, or
- Ticket created to make necessary changes

**Comment by IanKWatts** [comment]
It looks like RedHat is going to stop providing a supported version of the operator-sdk CLI tool, but that the tool itself and its open-source upstream project can continue to be used.  Operators created with this tool should not be affected.  FWIW, I am already using the open-source version:
https://sdk.operatorframework.io/docs/installation/
