### ISSUE TITLE
Add "subscribers" to AlertManager notifications

### ISSUE THREAD

**Issue by IanKWatts** [BCDevOps/developer-experience#5477]
**Describe the issue**
The Registry now supports additional project contacts, which can have any of three roles.  The Registry team will add this information to the NATS message sent to the Provisioner.  Update the the AlertManagerConfig to include additional contacts that have the 'subscriber' role so that they will receive email alerts.

**What is the Value/Impact?**
Better communication and monitoring of applications on the platform.

**What is the plan? How will this get completed?**
Update the app-provisioner image to parse this information and include in the AlertManagerConfig template.

**Identify any dependencies**
There is a corresponding ticket on the App Dev board.

**Definition of done**
- [ ] Provisioner has been updated

**Comment by StevenBarre** [comment]
Will these additional contacts be added to the contacts annotation in the namespace as well? AdvSol parses that when emailing teams to fix something in their app.

**Comment by IanKWatts** [comment]
The contacts list includes a `role` field, which is currently either "owner" or "lead".  How about if we add subscribers to this same list with role "subscriber"?

**Comment by StevenBarre** [comment]
Perfect!

**Comment by IanKWatts** [comment]
All contacts will be added to the namespace's `.metadata.annotations.contacts`.  The new contacts will be added with a `role` value of "editor", "viewer", or "subscriber".
The AlertManagerConfig template has been updated such that subscribers are added to both the "Everyone" EmailConfig and the "TechLeads" EmailConfig.
