### ISSUE TITLE
GitHub Awesomer

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#56]
As platform services team, we want to automatically inspect and maintain the GitHub resources.

we will know this is done when we can auto the process to
- remove inactive users (assign expiry date for each user)
- notify teams when repo not meeting standard
- use security/quality notification apps
- github code stewardship
- github repo labeling/tagging
- github teams feature explored (permission/discussion)

deliverables:
- scripts to run inspection tasks
- docs on github management

**Comment by ShellyXueHan** [comment]
update:
temporary private repo: label the expiry time as a custom topic `expiry-<month>-<year>`. Example [here](https://github.com/bcgov-c/cas-ggircs-private)

**Comment by lukegonis** [comment]
@ShellyXueHan can you please provide an update on the inactive user notification feature - has it been Implemented?

**Comment by ShellyXueHan** [comment]
@lukegonis that feature is completed. But there are more features we need to implement for private repos. I'll close this ticket and turn into an epic and tickets in backlog
