### ISSUE TITLE
Change passwords for platform related accounts

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#564]
Due to recent events, we have been directed to change all passwords.  We could also use this as an opportunity to document our findings to make this process more efficient in the future.

This issue is not sprint milestone related.

**Additional context**
List of accounts generated
Categorize based on complexity to change
Prioritize based on accessibility and target value

**Definition of done**
All passwords are changed and applications/services that reference them are working

**Comment by mitovskaol** [comment]
@NickCorcoran Can you please lead the work to document all services accounts used by the team for operating Openshift and the shared tools in [this repo](https://github.com/bcgov-c/platform-services-docs). Including the password reset approach used. 

Similar to what was documented for Uptime Robot and AQUA in this repo.

**Comment by NickCorcoran** [comment]
Nick to revive this in Q4.  Will be key for understanding what needs to be backed up in the event a secret manager service is unavailable.

**Comment by lukegonis** [comment]
Nick will check w/ Cailey/Shelly to see if this is still needed. He will also need to check in w/ OCIO ISB on relevance of changing given NIST recommendations. He’ll update this issue based on that.
