### ISSUE TITLE
Create devops-alert notification for load balancer TIB

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#570]
**Describe the issue**
Create a notification in https://github.com/BCDevOps/platform-services-status-page-notifications for TIB https://ssbc-client.gov.bc.ca/tibs/ViewTib.asp?Tib=D-2020-067&Rev=0

**Definition of done**
Notification approved by Bev and Olena and published into RocketChat

**Comment by mitovskaol** [comment]
Comms have been released.
