### ISSUE TITLE
Adjust ocp-monitor emails to use new team DLs

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#571]
**Describe the issue**
The MCS team now has its own distribution lists in Exchange. Update all the bits of our code that email us to use the new DLs.

**Definition of done**
 - [x] ocp-monitor using new email lists
- [x] other places?

**Comment by tbaker1313** [comment]
Team DL hsmcs@dxcas.com
On-call DL mcsoncall@dxcas.com

**Comment by tbaker1313** [comment]
Team DL hsmcs@dxcas.com
On-call DL mcsoncall@dxcas.com

**Comment by tbaker1313** [comment]
This is completed.
