### ISSUE TITLE
Preparation for dockerhub changes

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#578]
#### Describe the issue
Docker is changing their Terms of service and doing some cleanup of their free/unlimited access.  Developer/community communication is needed to highlight these possible impacts to our teams.

##### 1. Rate Limits for docker pull requests
Has the potential to impact both builds and deployments where dockerhub images are directly referenced and are rate limited.
https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/

##### 2) Inactive image prune
Has the potential to remove a base image that has been marked inactive, but is still referenced in a local image that hasn't been re-built in a while.
https://www.docker.com/pricing/resource-consumption-updates

#### Which Sprint Priority is this issue related to?
Dockerhub changes are scheduled to start in Nov, 2020.

#### Definition of done
Stimulate community conversation to ensure development teams have time to address any dependencies
Identify / correlate / publish good practices

**Comment by mitovskaol** [comment]
Prepare an announcement about this change at the next Sprint Review

**Comment by mitovskaol** [comment]
Decision: Each team will create their own Docker account and use it for their images
Prepare a comms for the teams to advise them that the recommendaiton is to pull an image into their tools namespace and use it for builds from there
