### ISSUE TITLE
Stale BCGOV namespace Image Review and Update

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#579]
security patches to high demand bcgov images (as identified by product teams in Rocketchat) e.g. caddy, ngnix, Jenkins

Sync this work with the OCP 4 Image Pipeline development work
https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/290

**Comment by lukegonis** [comment]
@patricksimonian do you have capacity to do this in the current sprint?

**Comment by lukegonis** [comment]
Blocked by https://app.zenhub.com/workspaces/openshift-4-build-out-5db73142897668000144f22b/issues/bcdevops/openshift4-rollout/290

**Comment by mitovskaol** [comment]
@jleach is this still relevant?

**Comment by jleach** [comment]
I don’t think so. We only offer one image now and it’s up to date.

Regards,

Jason Leach
