### ISSUE TITLE
Migrate private (DXC) repo to bcgov-c

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#582]
sync/update of the private (DXC) repo for the initial cluster deployment pre-requisites to a bcgov-c location (to allow the platform services team to access and review steven's awesome setup)

**Comment by tbaker1313** [comment]
Request for repo has been requested. Will push contents when it has been created.

**Comment by tbaker1313** [comment]
Repo has been migrated to new bcgov-c private repo.
