### ISSUE TITLE
Document Operations Monitoring Tools and their Usage

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#583]
Documentt the list of tools/scripts used by the Platform Operations Team (e.g. Nagios, ElasticSearch, Prometheus, etc as well as manual scripts) and the metrics that they monitor (node availability, node capacity, Openshift API availability, etc ).

Include information if any of the monitoring tools is integrated with notifying a support person. How do we know if there is an outage on the Platform after hours? Who gets called and by whom?

**Comment by mitovskaol** [comment]
Will reach out to @DanDeane to collect the info and will document

**Comment by lukegonis** [comment]
- Next step is to receive the escalation flow diagram from @DanDeane 
- Will then add BC Gov responsibilities/roles

**Comment by sbarre-esit** [comment]
https://github.com/bcgov-c/advsol-docs/blob/master/OCP-On-Call.md covers some of this

**Comment by mitovskaol** [comment]
The requested information has been received.
