### ISSUE TITLE
Document Platform troubleshooting procedure

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#584]
Outline commons steps a support person takes to troubleshoot an issue including any automation playbooks that are used i.e. to drain the affected node and migrate workloads to another load while investigation continues.

Objective: Understand out Time-To-Recover metric (the time between when the support person is notified and when the issue is resolved) and how to reduce it.

**Comment by mitovskaol** [comment]
Will reach out to @DanDeane to collect the info and will document

**Comment by lukegonis** [comment]
Met with DXC on Sept 9 to discuss this, next step is to receive the escalation flow diagram from @DanDeane
we will then add BC Gov responsibilities/roles

**Comment by mitovskaol** [comment]
The requested information has been provided.
