### ISSUE TITLE
Verify OCS 3.11.5 no longer crashes on PCM scan

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#589]
**Describe the issue**
Previous versions of OCS would crash when hit by the quarterly security port scanner. v3.11.5 supposedly fixes this and has now been applied to LAB and PROD.

**Additional Context**
Tracked in theHUB as SCTASK0156181

**Definition of done**
- [x] Run a scan on the LAB OCS nodes and verify they do not crash
- [ ] Update the PROD OCS nodes in theHUB to enable security scanning again

**Comment by tbaker1313** [comment]
Have run the scan and it did not cause gluster issues in LAB.

**Comment by tbaker1313** [comment]
Team determined this specific scan is not necessary. The ticket will be closed as no further action required.
