### ISSUE TITLE
2020 Q4 Patching schedule

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#592]
Problem encountered with these changes due to an issue with some repos:
October 13th - 16th -> CHG0018407 - LAB OCP upgrade to 3.11.286 - now proceeding under CHG0019061 - COMPLETED
October 13th - 16th -> CHG0018408 - LAB OCS upgrade to 3.11.5-14 - now proceeding under CHG0019062 - COMPLETED

These have been replaced with the following changes:
October 19th - 23rd -> CHG0019061 - LAB OCP upgrade to 3.11.286 - COMPLETED
October 19th - 23rd -> CHG0019062 - LAB OCS upgrade to 3.11.5-14 - COMPLETED

November 2nd - 6th -> CHG0018653 - 3.11 LAB OS patching - CANCELLED due a specific package not yet available
November 12th - 13th -> CHG0019688 - 3.11 LAB OS patching - START DELAYED DUE TO PACKAGE AVAILABILITY in RHBA-2020:5007 - COMPLETED

October 24th - November 6th -> CHG0018824 - PROD OCP upgrade to 3.11.286 - CANCELLED - replaced by CHG0019119 
October 31st - November 13th -> CHG0019119 - PROD OCP upgrade to 3.11.286 - COMPLETED
November 14th -> CHG0018825 - PROD OCS upgrade to 3.11.5-14 server side only (clients updated during PROD OS patching) - COMPLETED
November 21st - December 4th -> CHG0018826 - 3.11 PROD OS patching - COMPLETED

October 26th -> OS patching for ministry Aporeto VMs
REFINE, FILTER, DREDGE, SKIM - > CHG0018716  - COMPLETED
JAG-APORETO-T1 - > CHG0018712 - COMPLETED
RANDALL.EDUC.GOV.BC.CA - > CHG0018722 - COMPLETED

December 10th -> CHG0020829 - OS Patching UTIL Servers - MCS-SILVER-UTIL.DMZ, MCS-CLAB-UTIL.DMZ & MCS-KLAB-UTIL.DMZ - COMPLETED

Versions of specific components for OCS are the following:
registry.redhat.io/rhgs3/rhgs-server-rhel7:3.11.5-14
registry.redhat.io/rhgs3/rhgs-volmanager-rhel7:3.11.5-7
registry.redhat.io/rhgs3/rhgs-gluster-block-prov-rhel7:3.11.5-6

**Comment by tmorik** [comment]
The patching, CHG0020829 ( OS Patching UTIL Servers - MCS-SILVER-UTIL.DMZ, MCS-CLAB-UTIL.DMZ & MCS-KLAB-UTIL.DMZ) will be run on Dec 10, 1 pm, today.
