### ISSUE TITLE
ARO Pathfinder - Identifiable cluster IP for on-prem firewall rules?

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#593]
**Describe the issue**
From Ryan Loisell - Hey folks, question for you Platform Services folks, do you know if there is any static IP addressing within the ARO cluster?
We are trying to figure out how to connect our internal Splunk to the ChatOps notification service that will be living in the ARO cluster.

**Comment by stewartshea** [comment]
There is an outbound IP assigned for each ARO cluster; the object is created in the cluster resource group and called "[cluster-name]-[cluster-id]-outbound-pip-v4". 

This can also be determined from within the cluster by deploying a simple curl image (ie. `byrnedo/alpine-curl`) and adding the following command to the deployment manifest: 
```
      command:
        - /bin/sh
        - '-c'
        - while true; do curl ifconfig.me && sleep 10; done
```
