### ISSUE TITLE
bcgov-c GitHub Organization clean up

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#601]
## Background:
Repos in `bcgov-c` GtiHub org are meant to be temporary and teams should work on turning to public asap. Thus, new private repos are assigned an expiry date, and should be re-evaluated again once the date has come.

## Tasks:
- check in with teams when repos are about to expire
- update repos that do not have an expiry date
- when teams are ready to move to public, remove membership
- monitor GitHub apps and GitHub Action usages

**Comment by ShellyXueHan** [comment]
This still needs to be done at some time.

**Comment by NickCorcoran** [comment]
This is now Dev Experience team responsibility.
