### ISSUE TITLE
Update Artifactory Operator to allow SVC Acct password management

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#621]
#### User Story
**Manage Artifactory Credentials**
As an Application Developer, I would like to be able to reset/recover an Artifactory Service Account access token/secret.

**Additional Context:**
The current operator does not manage child objects created as part of the Custom Resource provisioning flow.  This blocks the operator from being able to re-create a child object (in this case, the provisioned Artifactory service account secret)  In order to meet the above requirment, the operator needs 2 pieces to be in place:

1. Operator needs to watch for changes to child object (secret)
2. Operator needs to be able to manage create/delete of the secret
 - Creation of a secret requires Generating a complext password/access token, setting the associated artifactory service account password, creating a secret in the CR's namespace to match the generated password.
 - Deletion of an existing secret needs to trigger the creation of a new secret (as above)
3. Assumption is that if a secret is modified, the operator ignores the change (does nothing).  *(if functionality is broken due to an external change, then the appropriate step would be to manually delete the secret and have the operator re-create it with the above creation criteria)*

Note that the number of secrets affected might vary - two when the service account definition includes a list of docker repos, where the second is a pull secret. In this case, deleting either secret will result in the password being reset and both secrets being recreated.

**Definition of done:**
**KLab**
- [x] Test: A secret associated with an artifactorySA CR is deleted: verify that a new access token is set for that Artifactory Account, and a new secret is created for the ArtifactorySA CR.
- [x] Test: An ArtifactorySA CR is created: verify that the Artifactory Account is created, an access token set for that account, and a secret created in the CR's namespace.
- [x] Test: An ArtifactorySA CR is deleted: verify that the artifactory account is deleted (with all group membership references removed), the associated secret is deleted.
- [x] Test: ArtifactorySA created before the update works correctly for the above as well as net new ArtifactorySA objects.

**Comment by caggles** [comment]
https://github.com/BCDevOps/developer-experience/tree/docs/user-stories/apps/artifactory/docs

**Comment by jefkel** [comment]
Artifactory redeploy to KLAB is in progress, this should be moving forward again.

**Comment by mitovskaol** [comment]
Still active

**Comment by lukegonis** [comment]
Still relevant, Cailey will work on it once the Gold migration is complete.
