### ISSUE TITLE
Conduct research and recommend an email distribution list management tool

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#623]
The Platform Services PO needs a tool to manage an email distribution list for Platfom communications. The tool would provide an interface (KeyCloak SSO protected with IDIR and GitHub IdPs) where stakeholders can sign up to be included in the distribution list and unsubscribe from it.

The tool ideally would be open source. Can we hosted on-prem or available as a SaaS.

@patricksimonian  I am thinking this might be something that Andrew can help us with,

**Comment by AndrewJun97** [comment]
> The Platform Services PO needs a tool to manage an email distribution list for Platfom communications. The tool would provide an interface (KeyCloak SSO protected with IDIR and GitHub IdPs) where stakeholders can sign up to be included in the distribution list and unsubscribe from it.
> 
> The tool ideally would be open source. Can we hosted on-prem or available as a SaaS.
> 
> @patricksimonian I am thinking this might be something that Andrew can help us with,

Hi Olena! This is for sure something I can look into :)

**Comment by AndrewJun97** [comment]
This issue is currently blocked - waiting for infrastructure code from a community member who has deployed Mautic on OCP.
