### ISSUE TITLE
Remove/delete namespaces created for Registry testing purposes

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#627]

**Comment by mitovskaol** [comment]
@j-pye  can we please do the cleanup and remove the test namespaces in Openshift that have been provisioned when Project Registry has been tested

**Comment by mitovskaol** [comment]
Will wait until the project deletion feature is available in the Registry.

**Comment by lukegonis** [comment]
closing, this test project will be used for platform services testing and experimental work so we are not going to delete it at this moment. a new ticket will be created to track project deletion in the registry
