### ISSUE TITLE
Create SysDig Dashboard for the Silver Cluster

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#631]
DOD: Create a report with the cluster stats such as current capacity RAM/CPU,  project and pod count. 

Make the report flexible so that is can include multiple clusters for when we have Gold/Gold DR availabile in the future.

**Comment by sbarre-esit** [comment]
Doesn't the Sysdig Dashboard cover all those metrics now?

ps: I can't seem to find the link for the Sysdig Dashboard, can you remind me where it is?

**Comment by mitovskaol** [comment]
https://app.sysdigcloud.com/#/dashboards/158547?last=3600
@sbarre-esit  let me know if the direct link works for you, otherwise, you can find the dashboard in the public namespaces, Dashboards -> Pathfinder Capacity and Utilization - Prod

**Comment by sbarre-esit** [comment]
Woot, that works! Thanks.

**Comment by ShellyXueHan** [comment]
@mitovskaol Hi Olena, is the board ` Pathfinder Capacity and Utilization - Prod` you mentioned above for silver or ocp3 cluster? It does not exist anymore, do we need to create one for each cluster again? Is this a custom board or one of the default sysdig templates? (too many questions :P)

**Comment by mitovskaol** [comment]
@ShellyXueHan The Pathfinder Capacity and Utilization board is still available at
https://resource-dashboards.pathfinder.gov.bc.ca/d/SQGD3rVWz/advsol-noc?refresh=5m&orgId=1
I believe it was built using Prometheus and Grafana and therefore still works even though Sysdig was removed from OCP 3.11. I am also attaching a screenshot if the link doesn;t work for you.  

I would like to have something similar built for the Silver cluster (with Sysdig) so that I can keep an eye on its capacity level. 
<img width="1792" alt="Screen Shot 2021-03-17 at 9 54 58 AM" src="https://user-images.githubusercontent.com/28309901/111506484-e7983e80-8706-11eb-9bf4-be3e013e7693.png">

**Comment by ShellyXueHan** [comment]
There are two dashboards created for each cluster:
- CPU and Memory Resources
- Persistent Volume Storage

@mitovskaol Currently they are enabled on silver, gold and klab clusters. The dashboards can be found under `Dashboards` -> `Shared by my team`

**Comment by ShellyXueHan** [comment]
### Update:
There are several things we need to double check for metrics accuracy:
- https://github.com/BCDevOps/platform-services/issues/169
- https://github.com/BCDevOps/platform-services/issues/170

also explore getting @StevenBarre 's metrics via StatsD:
- support case for StatsD issue: 00009583
- https://docs.ansible.com/ansible/latest/collections/community/general/statsd_module.html#examples

Will create separate ticket for this next sprint.

**Comment by mitovskaol** [comment]
@lukegonis Can you please add the comment before closing this to indicate whether it was built and if yes, include the link to the dashboard. As per our ZenHub etiquette, team should not be closing any tickets without the last comment indicating the outcome of this work or whether it is not relevant anymore.
