### ISSUE TITLE
SG - OCP 4- Improve Cluster Operational Automation

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#635]
This themed sprint goal relates to the constant improvement for operating the platform.  This sprint will focus on 2 feature additions:

- The etcd service is like the memory center for a cluster, this sprint will look at disaster recovery features for this service
- Cluster worker nodes can be evacuated for numerous reasons and informing the application teams of affected pods/instances can be helpful for teams.  This sprint will look at bringing forward some of the custom alerting/notification automation for node evacuations.

**Comment by sbarre-esit** [comment]
Moved the ETCD task to next sprint. Closing.
