### ISSUE TITLE
Setup NetApp in OCP 3.11 Lab Cluster

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#637]
Platform Operations Team needs to have a virtual NetApp appliance installed in the LAB cluster to test NetApp and Trident upgrades there before applying them in the OCP 3.11 PROD Cluster.

A prerequisite for this work is to obtain  NetApp licenses for the LAB cluster.

Need:
- [x] SDSF forms to order VM x2
- [x] 2 VMs configured with netapp image
- [x] Configure for NETAPP for LAB access

Will be considered done when NETAPP storage is available in LAB and is working as expected.

**Comment by mitovskaol** [comment]
@DanDeane  Assigning this to you for now as we are waiting for a confirmation from NetApp re: licenses for the LAB cluster.  Can you please also fill in the details for the scope of work + definition of done + estimate to have the NetApp installed in the LAB. Thanks!

**Comment by sbarre-esit** [comment]
Tim has sent filled out SDSF forms to @lukegonis to submit to iStore.

Blocked waiting on iStore now.

**Comment by wmhutchison** [comment]
Ball's currently in the court of DXC Storage team to complete the install/configuration of the VM appliances before MCS team can take over and run  playbooks to complete setting up NetApp/Trident. Will revisit next week.

**Comment by tbaker1313** [comment]
The latest update is that the storage team ran into an issue configuring these virtuals and need to try it again. They will be looking into this on Tuesday December 1st. Assuming this goes well, it should be possible to roll these servers out to 3.11 LAB by the end of the week.

**Comment by sbarre-esit** [comment]
Nodes handed over via CHG0021002
