### ISSUE TITLE
Build  Sysdig dashboard for monitoring API endpoint health

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#639]
Build cluster API endpoint monitoring using Sysdig (for both OCP 3.11 and OCP 4) - decide what metrics are appropriate and develop a dashboard that includes those metrics.

**Comment by lukegonis** [comment]
Monitoring in OCP4 will be tracked separately in two work streams, the low level monitoring strategy will be monitored by the platform ops team (DXC), the higher level reliability monitoring for the platform will be developed by the platform services team.
