### ISSUE TITLE
Renew registry certificates in 3.11 LAB & PROD

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#644]
Will need to update the registry certificates in LAB and prod - expiry is Jan 20th, 2021

Will be considered completed when:
- [x] Confirm with Red Hat the proper methodology for renewing the registry certificate.
- [x] Renew registry certificate in 3.11 LAB cluster to test the process and re-sync expiry of LAB cert with PROD.
- [x] Renew registry certificate in 3.11 PROD cluster. Confirm expiry report no longer reports registry cert. 

At this time the PROD cert update will be completed during scheduled OS patching November 21st - December 4th under CHG0018826

**Comment by wmhutchison** [comment]
Based on review of when this particular cert was last renewed, we are expecting the upcoming PROD 3.11 OCP upgrade to deal with this certificate (said cert is good for 2 years). Will review next week if the expiry warning persists after we pass the backplane upgrade of OCP 3.11 PROD.

**Comment by tbaker1313** [comment]
This will be completed the week of Nov 24-27 in both LAB and PROD.

**Comment by tbaker1313** [comment]
Completed in PROD Dec 3rd.
