### ISSUE TITLE
Upgrade Trident on 3.11 clusters to v20.10

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#647]
** Problem Statement **
Per recent comment from NetApp involving our fsck issues (and likely affects our multipath issue as well if previous experience holds up).

Hello William,

We have just received confirmation from Engineering that the issue will be completely fixed in 20.10.  There is additional coding in v20.10 that should handle the FSCK issue more completely than the current work-around config.  The manual scanning that is in your iscsi.conf file will remain set to manual.  Version 20.10 should be out the end of the month but that can change or be delayed if anything is found during testing.  Does this answer your question or is there anything in addition you would like to know?

Thank You,
John Leahy
Technical Support Engineer
Technical Support Center 

** Definition of Done **
- [x] Confirm availablity of new version of Trident
- [x] Test upgrade of Trident in 3.11 LAB
- [x] Upgrade Trident in 3.11 PROD - roll back if issues arise

**Comment by wmhutchison** [comment]
We first need a proper NetApp environment installed in our 3.11 LAB cluster so that a proper upgrade of Trident can first be tested in 3.11 LAB before attempting the same in 3.11 PROD.

Also we need to receive confirmation from NetApp that Trident v20.10 is in fact generally available. Current estimate is end of October 2020, but testing is still underway and delays may occur due to said testing.

**Comment by wmhutchison** [comment]
Still blocked since NetApp in 3.11 LAB isn't ready yet.

**Comment by tbaker1313** [comment]
Netapp is ready in LAB and this will be tested the week of December 15-18

**Comment by tbaker1313** [comment]
https://github.com/NetApp/trident/releases/tag/v20.10.0

**Comment by tbaker1313** [comment]
This has been updated and installed in 3.11 LAB. Will be monitored and 3.11 PROD will be updated if this is successful.

**Comment by tbaker1313** [comment]
This has been scheduled for Thursday Jan 21st @ 1800
CHG0021787 - MCS 3.11 PROD - Upgrade Trident to version 20.10.0

**Comment by tbaker1313** [comment]
This is scheduled for Thursday Jan 21in CHG0021787

**Comment by tbaker1313** [comment]
This has been rescheduled due to important rollout in 3.11 PROD for Jan 22nd. Old change CHG0021787 has been cancelled and replaced by CHG0022144 - Scheduled for January 28th at 1730.

**Comment by tbaker1313** [comment]
Updated in PROD.
