### ISSUE TITLE
Standardize repos used in this ZH board

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#652]
**Describe the issue**
There are differences in the tags, templates, and Estimate point scales between developer-experience and OpenShift4-RollOut.

**Which Sprint Priority is this issue related to?**

**Additional context**

**Definition of done**
- [x] Have the same labels, with the same colors, in both repos
- [x] Have the same issue Template in each repo
- [x] Have the same Estimate point scales in both repos

**Comment by sbarre-esit** [comment]
My fav labels are the `env/*`, `site/*`, `team/*`, and `tech/*` ones in the OCP4 repo.

**Comment by mitovskaol** [comment]
@lukegonis  Is this work still in progress?

**Comment by lukegonis** [comment]
use same labels as developer experience
