### ISSUE TITLE
RocketChat Emails notifications header image too big

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#654]
**Describe the issue**
When I get notification emails from RocketChat the header image is very large and takes up most of the viewport in my Outlook. So I have to scroll to see the actual message.

**Which Sprint Priority is this issue related to?**
SG - Sprint 20 Platform Hot Fixes

**Additional context**
![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/7bb00a48-bc89-4030-8dac-50947a13af73)

**Definition of done**
- [ ] Reduce the size of the header image in the email template

**Comment by jefkel** [comment]
Is this in the correct SP Epic? (not a platform operational task?)

**Comment by sbarre-esit** [comment]
Previously we were trying to limit the number of SG, so this was added to the HotFix one. Now that we've split planned work to the ops SG and Hotfix is only for unplanned fixes, I moved it here.

Open to suggestions on where else to put it.

**Comment by jefkel** [comment]
@ShellyXueHan @caggles where are you tracking operational hotfixes for RocketChat?

**Comment by ShellyXueHan** [comment]
we've got a PS hot fix sprint goal, better fit for that one then operations.

Anyway, here's the logo from header `<img src="[Site_Url_Slash]assets/logo.png" alt="Rocket.chat" width="150px" />` which looks okay to me...

Also just double check on the email I received and the size is not as big. I wonder if it's rendered differently. @sbarre-esit are you able to get the html from the RC email you got? Or is there an options to hide image by default (as a quick fix :P)

**Comment by sbarre-esit** [comment]
https://stackoverflow.com/a/20990036/219116 says that the trick is to not use `px` in the width. That's not valid HTML and Outlook just ignores it.

**Comment by ShellyXueHan** [comment]
Updated! But I don't see a difference from my end... @sbarre-esit let us know how it look next time you get an email!

**Comment by ShellyXueHan** [comment]
Updated with Steven's suggestion and confirmed working. Closing now.
