### ISSUE TITLE
Add new Facebook Cares emoji to RocketChat

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#655]
**Describe the issue**
Facebook has added a new [cares](https://www.theverge.com/2020/4/17/21224805/facebook-care-reaction-like-button-messenger-app)  emoji / reaction. Could we get it added to the custom emoji in RocketChat?

**Which Sprint Priority is this issue related to?**
TBD

**Additional context**

**Definition of done**
- [ ] Cares emoji available in RocketChat

**Comment by mitovskaol** [comment]
I really love to use this emoji so am pushing it up the priority list :)

**Comment by jleach** [comment]
Added as `:care-1:` from here as it appears to be royalty free:

https://iconscout.com/icons/facebook-care-reaction
