### ISSUE TITLE
Build new RBAC for community helpers

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#659]
**Describe the issue**
There is a desire to provide some ministry users view access to all tenant namespaces so they can be excellent community members and lend their expertise and advice.

Currently this is achieved with the very broad Cluster scoped `cluster-reader` role. The Platform team would like to restrict this access to just tenant namespaces.

**Which Sprint Priority is this issue related to?**
TBD

**Additional context**
There's a few ways to do this. The first would be to create a service account similar to `bcdevops-admin` and allow some users to impersonate it. Then give this service account `view` role in all the namespaces via the Project Registry. The advantage here is that the users with this access don't have their normal view of the cluster cluttered up with all the tenant namespaces unless they specifically ask for it.

Another option would be to construct a user group with all the users as members, then grant that group `view` role in the namespaces. 

We could instead directly give all the users `view` role in the tenant namespaces, again by the Project Registry automation. This would require the Project Registry to know all the users, instead of the CCM tool/repos.

**Definition of done**
- [ ] Decide on which option to use
- [ ] Update the Project Registry to create the needed role in each namespace
- [ ] Update the platform gitops playbooks to add the users to the group/rolebinding

**Comment by StevenBarre** [comment]
@NickCorcoran do you have any preference for which option we go with? I'm personally a fan of (1)

**Comment by j-pye** [comment]
I also like option 1, it also forces the community helper to be familiar enough with OpenShift that they can function without the UI. 

Option 1.5
To extend on that, we could use a group for the service account impersonation as well so the RoleBinding doesn't need to be updated. Just the list of users in the group. It also gives us the ability to move to Option 2 if needed without much effort. The only difference is whether we specify the service account or the group in the namespaced `view` rolebinding.

> We could instead directly give all the users view role in the tenant namespaces, again by the Project Registry automation. This would require the Project Registry to know all the users, instead of the CCM tool/repos.

Not a fan. I'd rather use a group in either case unless there's a desire to turn the Registry into more of Teams API where community access can be controlled for each project by the PO/TC. 

(Thinking out loud) If we did have a Teams API there would be a way for @NickCorcoran to have his User that can ONLY grant namespace RBAC without having any other permissions within the namespace. (Future)

**Comment by NickCorcoran** [comment]
I like the group idea, as we cannot allow anyone, even within a given Ministry, to impersonate a view role across all their Ministry projects (especially for those that use private repos).  
As it is view only, impersonation isn't a big issue from Dev/Test environments, but could be for Prod if it allows for visibility into production data.

**Comment by j-pye** [comment]
>I like the group idea, as we cannot allow anyone, even within a given Ministry, to impersonate a view role across all their Ministry projects (especially for those that use private repos).

@NickCorcoran I believe we're only talking about view access to OpenShift resources and not the actual data within a repo or within a database. The most a `view` role should be able to do is see where everything is and see the logs for pods. (No Secrets) So they could see the repository an image is built from but if that was a private repo they would need to have their github id granted access to the repo by that team. 

Some teams are using the same SSL certs for dev, test, and prod. (Cert with alternative names like dev.app-domain, test.app-domain ) So would you want to block users from viewing routes as well?

view role ref:
https://console.apps.silver.devops.gov.bc.ca/k8s/cluster/clusterroles/view

**Comment by NickCorcoran** [comment]
@j-pye that is good information, however, I still think some teams would not want their OCP resource info and/or logs shared.  Perhaps it could be allowed if the PO 'opts in' for this ability, but I'm still not sure that sharing should cross Ministry lines of responsibility, or even outside those specific people a PO wants (and explicitly approves) looking at their resources.  
Perhaps a good topic to bring up at Sprint review for input (pros/cons) and I'll reach out to the security community on their thoughts.
I understand the desire to be able to help others here.

**Comment by StevenBarre** [comment]
@j-pye 

> To extend on that, we could use a group for the service account impersonation as well so the RoleBinding doesn't need to be updated.

I think we DO want to have to modify the rolebinding in CCM so we have an audit trail of who was added, when, and who approved it. If we did it with a group, then the group would be tracked in CCM.

@NickCorcoran 

> I like the group idea, as we cannot allow anyone, even within a given Ministry, to impersonate a view role across all their Ministry projects

You are aware at least one user already has cluster-reader which is view in ALL namespaces? This is looking to address taking away the openshift namespaces from them so they can only see tenant namespaces. https://github.com/BCDevOps/devops-requests/issues/592

> but could be for Prod if it allows for visibility into production data.

`view` access only lets you see the objects, no access to data in a PVC or secrets.

**Comment by NickCorcoran** [comment]
@StevenBarre I understand the desire, but I think perhaps the framing as community helpers is wrong for the intent to be acceptable.  Perhaps what this is more for is the specific people in each Ministry/Sector that are responsible for monitoring or assisting teams within their set Ministry/Sector scope.  This would allow for Ministry DevOps leads or architects, as well as MISOs, to access these spaces.  I think the mechanism is viable.  We just have to be careful on who gets put into those groups.

**Comment by NickCorcoran** [comment]
@StevenBarre I prefer the option **to construct a user group with all the users as members, then grant that group view role in the namespaces.**  That way we don't lose the traceability for users accessing resources (as I believe we would using impersonation).

I would also like to see the other role created that is specific to the Ministry/Sector oversight context, but perhaps that princess is in another castle (ticket).

**Comment by StevenBarre** [comment]
Audit log captures impersonations

```bash
# oc -as wmhutchison@github get nodes
```

Leaves this in the audit logs
```
user.username:stevenbarre@github impersonatedUser.username:wmhutchison@github
```

**Comment by NickCorcoran** [comment]
ah, ok.  service acct w/ impersonate is fine, but restricted to a group specified in our -c location

**Comment by jefkel** [comment]
What is the business reasoning behind revoking/restricting view access to only tenant namespaces?  Is there a specific security or business case driving this?  I believe that the community helpers were quite happy to be able to view cluster settings as well as other tenants project sets, and may not have their needs met with this change.

Re: specific view access to "opt-in" projects feels like this is out of scope of this ticket.  Developing multiple management approaches feels like overly complicated for this specific ticket, and may be better served by an access controls design session before implementation is discussed.  Starting to feel like overlap with the conversations with RL re: access controls within specific groups of projects, and might be better served by combining those discussions.

**Comment by NickCorcoran** [comment]
@jefkel While some people may have had this cluster-wide ability in the past, it is not something that we should do from a least privilege or need-to-know perspective.  Access to logs, for example, can potentially expose more information than intended.  And while we don't expect our employees/contractors to take excessive  or malicious advantage of their visibility, accounts do get compromised (even w/ MFA) and people do get disgruntled/persuaded and do things outside the norm.  This is why we need to be prudent in ensuring our access needs while balancing the idea of community (i.e. making it easy to grant access to the right people at the right time).

Agreed that more discussion needs to occur re: RBAC in general.  I have been having discussions with RL and MR and will organize a group discussion soon.

**Comment by jefkel** [comment]
might be a good time to revoke the CommunityHelper access completely then?  Feels like that visibility/access does need to be with the PS team (that's supporting the platform directly) - and community support can be added/managed by the teams wanting it (can create a group called "Community Helpers", and just show a rolebinding sample that grants that team View access to your project - you can add it if you want, or keep private if you want.)

As for RBAC for teams - I think care needs to be taken here - feels like there is an opportunity for Ministry groups to step in and create their own management tools, but they're struggling because they don't have resources (staff?) that are knowledgeable enough to build/maintain their own standard RBAC?  Happy to jump in and help define an approach for the groups/ministries/teams, however the current model also needs to have a team/person/group to hand the developed roles/rolebindings/management/maintenance back to.  (otherwise it's not self-serve, and it's an additional full-service security solution being delivered by the platform team)

**Comment by NickCorcoran** [comment]
@StevenBarre I'm happy with proceeding on this role type as it is desired by the PO and makes sense for limited time frames for select users.  I have no preference on mechanism as all options leave an audit log.  

Will likely revisit this and other roles as part of a larger RBAC discussion.

**Comment by StevenBarre** [comment]
@j-pye so thoughts on me creating a service account called bcdevops-viewer and you granting it view permission in all projects via the Project registry?

**Comment by j-pye** [comment]
@StevenBarre thoughts:  
https://gist.github.com/j-pye/23aaabf87234998453401955cbea6323

That one is group based but could be done the same way as bcdevops-admin. Or they could both be turned to groups if desired.

**Comment by StevenBarre** [comment]
- https://github.com/bcgov-c/platform-gitops-gen/pull/120
- https://github.com/bcgov-c/devops-fulfillment-pipeline/pull/19

**Comment by j-pye** [comment]
@NickCorcoran The pull requests above have been merged and rolled out to all existing namespaces on Silver. Community helpers should now have view access in all tenant namespaces.
