### ISSUE TITLE
Add labels to DevOps Request issues for which cluster they belong to

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#662]
**Describe the issue**
https://github.com/BCDevOps/devops-requests/issues gets quota and access requests for multiple clusters now. Can we get some new labels to add to the issues for `OCPv3` and `SILVER` and `GOLD`?

**Which Sprint Priority is this issue related to?**
Hotfix

**Additional context**
I don't know if there's any way to auto-apply the labels or if we just need to do it manually based on reading the tickets.

**Definition of done**
- [ ] Sweet labels exist

**Comment by caggles** [comment]
we don't have a way to auto-apply the labels, so this'll have to be manual! but the labels exist now :D
