### ISSUE TITLE
SG - OCP 4 Platform Essential Service Monitoring - Workshop 1

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#666]
**Describe the issue**
As a Platform Services Team member I need to develop reliability metrics for the Openshift Platform and the Shared Services on it . These metrics will track availability and performance of essential Platform and Shared Service. 
It is anticipated that 3 workshops will be required to identify the essential service, ther realiability metrics for them and the technoogy stack to monitor the metrics and capture the historic data in a dashboard.

**Additional context**
A service are considered essential **from the application operations perspective** if **any disruption to the operations of the service results in a disruption to the operations of an application production workload** running on the Platform.

**Definition of done**
 - [x] Prepare for the Workshop #1 where the Platform Services Team will use the KeyCloak SSO app as a sample app to understand what services the app production operations depends on on the Platform. The outcome would be a skeleton diagram outlining the essential services that the KeyCloak app relies upon i.e. Openshift routing service, Openshift API service, Docker service, Trident Storage Service, etc. It is recommended to create the diagram in a Miro board. 
- [x] Run the Workshop #1 with the Platform Service Team to fill in the gaps and add more detail to the essential .

**Comment by ShellyXueHan** [comment]
### Update:
- workshop outcome here is miro board: https://miro.com/app/board/o9J_kgyjm_k=/

**Comment by mitovskaol** [comment]
The workshop took place on Nov 19. THe outcomes documented in the Miro board. The next workshop to continue the discussion is scheduled for Dec 9.
