### ISSUE TITLE
Plumb in an additional RC route for migration

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#675]
Please create an additional route (keep the existing) for RocketChat using `chat.developer.gov.bc.ca`. You'll need to include the SSL certificate from `devhub` which can be copied from the `developer.gov.bc.ca` route. Please FWD HTTP to HTTPS for additional security.

**Comment by ShellyXueHan** [comment]
@jleach route created in prod namespace:  https://console.pathfinder.gov.bc.ca:8443/console/project/e5imao-prod/browse/routes/rocketchat-developer

Currently pointing to a fake service (just in case multiple hosts will cause interruption). You are namespace admin now, feel free to update the route and test on it.

**Comment by jleach** [comment]
I'll update it and give it an after hours test. Thanks!
