### ISSUE TITLE
Artifactory needs SSL redirect

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#677]
**Describe the bug**
Navigating to artifacts.developer.gov.bc.ca (without https) doesn't automatically redirect to https site. 
**To Reproduce**
1. Go to 'http://artifacts.developer.gov.bc.ca'
2. See app error

**Expected behavior**
Redirect to SSL site 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5882267651aa2c3057728119/1e20c78d-fe01-467b-9c05-aa39ad1e5113)

**Comment by mitovskaol** [comment]
Seems like an easy fix with a big positive UX impact, so I am bumping it up the priority list.

**Comment by caggles** [comment]
done.
