### ISSUE TITLE
Suggestion for more precise naming of Artifactory secret

### ISSUE THREAD

**Issue by garywong-bc** [BCDevOps/developer-experience#678]
A default secret is automatically create in the `*-tools` namespaces, following a name convention that starts with `default-*`.

```bash
# oc get secret -n e69aae-tools default-e69aae-rqmrfq
NAME                    TYPE                       DATA   AGE
default-e69aae-rqmrfq   kubernetes.io/basic-auth   2      26d
```

Perhaps `jfrog-default-<namespace-id>-<random-string` ?  

-- 

Note that:
"there is actually an object in openshift called ArtifactoryServiceAccount (or ArtSvcAcct) that you can oc get in order to check on the name of the secret " - that might be sufficient

**Comment by mitovskaol** [comment]
@caggles Can you please have a look and close if no longer relevant. Thanks!

**Comment by caggles** [comment]
this has been completed!
