### ISSUE TITLE
Artifactory Service Account Secret Name Update

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#680]
Right now, the secret for the default artifactory service account is `default-namespace-abcde` and that is not very clear. We should add something to the name of the secret to make it clear what it is.

DoD

- [x] The secret created by the operator now adds the word "artifactory" to the beginning of the secret name
- [x] The operator adds a label to the secret that makes it clear that it is an artifactory service account
- [x] Add a license plate like the way openshift service accounts work (this is for helping with the coming password change feature)

**Comment by jefkel** [comment]
Secret name idea: artifact-<serviceAccount Name>-<plate>
