### ISSUE TITLE
Migrate Devhub API to oidc.gov.bc.ca

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#691]
## Summary

Migrating this application to utilize oidc.gov.bc.ca as its sso endpoint for auth flows as sso.pathfinder.gov.bc.ca is now deprecated

## Definition of done

App utilizes oidc.gov.bc.ca for auth flows

**Comment by AndrewJun97** [comment]
Closed. PR tracked in https://github.com/bcgov/devhub-app-web/pull/1520
