### ISSUE TITLE
Migrate Reggie Web to oidc.gov.bc.ca

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#692]
## Summary

Migrating this application to utilize oidc.gov.bc.ca as its sso endpoint for auth flows as sso.pathfinder.gov.bc.ca is now deprecated

## Definition of done

App utilizes oidc.gov.bc.ca for auth flows

**Comment by ShellyXueHan** [comment]
### Tasks:
- update reggie URL
- update reggie SSO config
- update reggie web SSO client config redirect url
- update Rcoketchat reference wording and url on page

**Comment by ShellyXueHan** [comment]
complete. details tracked in PR https://github.com/bcgov/reggie/pull/52
