### ISSUE TITLE
Update playbook for Aporeto enforcer proxy creation for OCP 4

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#702]
As part of Aporeto pilots to test out cross-zone connectivity, the playbook for proxy setup needs to be updated and tested for use with OCP 4.

- [ ] Update playbook
- [ ] Test

**Comment by j-pye** [comment]
@NickCorcoran I think this is safe to close due to the recent OpenShiftSDN / Aporeto decision?

**Comment by NickCorcoran** [comment]
Abandoned due to switch in SDN focus.
