### ISSUE TITLE
Aporeto Proxies in DMZ - preparation

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#703]
In order to setup the new Aporeto proxies, we will need to prep the place they will live in/on.  

- [ ] Identify/create DMZ subnet for new Aporeto Proxies
- [ ] Submit iStore for 2 RHEL8 VMs in that subnet
- [ ] Submit iStore to open subnet firewall to OCP 4 and Zone B subnet
- [ ] Test comms

**Comment by Krocodial** [comment]
New subnets have been ordered, istore 1050058. Request was for 2 /29 DMZ subnets, one in Calgary and one in Kamloops

**Comment by NickCorcoran** [comment]
Abandoned due to switch in SDN focus.
