### ISSUE TITLE
Enable tcp_mtu_probing = 1 on all OCP3 servers

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#716]
**Describe the issue**
https://access.redhat.com/solutions/61720

Some parts of our network are poorly configured and create MTU blackholes.

**Which Sprint Goal is this issue related to?**
Hotfixes

**Additional context**
https://blog.cloudflare.com/path-mtu-discovery-in-practice/

**Definition of done Checklist (where applicable)**
- [x] Figure out which hosts are missing it (at least the 6 VMs seem to be)
- [x] Create CHG for v3 PROD
- [x] Apply to v3 PROD

**Comment by tbaker1313** [comment]
Will be implemented in CHG0020259 during the PROD OS patching window to minimize disruptions.
CHG0018826 - 3.11 PROD OS during the APP update process on Nov 24th through Dec 1st.

**Comment by tbaker1313** [comment]
This has been completed.
