### ISSUE TITLE
Investigate mTLS options for OCP4 Clusters

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#722]
**(ON HOLD UNTIL OCP 4.9 upgrade is both available and tested for deployment)**
In OCP3.11 the haproxy routers did not support mTLS. We would like to be able to use mTLS to secure our applications.
 
Link: <https://docs.openshift.com/container-platform/4.9/release_notes/ocp-4-9-release-notes.html#ocp-4-9-nw-mutual-TLS-authentication>

- [x] Investigate mTLS support in existing shared haproxy ingress routers
- [ ]  investigate mTLS options with F5 LoadBalancer IP service types
- [x] Document findings and review with user teams

**Comment by sbarre-esit** [comment]
https://access.redhat.com/solutions/5009651 is tracking an RFE for enabling MTLS in OCP4. We've got a case open to ensure we are kept in the loop.

**Comment by mitovskaol** [comment]
@wmhutchison Do you think this ticket is still relevant?

**Comment by wmhutchison** [comment]
Will review this ticket once things calm down a bit since there's some catch-up reading involved both for the mentioned case ticket as well as the general technologies involved.

**Comment by StevenBarre** [comment]
@mitovskaol Matt says:
>This feature is in progress for OCP 4.9.

Will keep in the backlog for now.

**Comment by StevenBarre** [comment]
Ivan Polchenko is interested in this feature.

**Comment by StevenBarre** [comment]
The feature provided by OCP 4.9 is a global one. The Ingress controller (aka the Router) is given a clientCA to verify incoming connections. While you can set verification to Required or Optional, it will only use that one clientCA for all connections. This doesn't scale well in a multi-tenant cluster where different teams will need different clientCA certs.

Closing as there's noting for us to implement here. It's unlikely this will be added in a multi-tenant way in the future. Teams can use Passthrough routes and configure mTLS checking in their app pods if they really want this.
