### ISSUE TITLE
Document a manual process for CCM and project namespace hot fix changes during ArgoCD outage

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#723]
**Describe the issue**
The Platform Service Team uses GitOps approach to build and manage OCP 4 Platform Cluster and project namespaces powered by ArgoCD tool. The risk mitigation requires us to have a manual process as a backup for applying hot fix/making emergency changes to the cluster/project namespaces in the case (howeve unlikely) when ArgoCD is down.   

**Additional context**
It should be made very clear in the docs that the manual process is **not a recommended approach** and should only be followed **in emergency situations.** Another thing to note that ability to apply any changes through the automation process **will stopped** after a manual change is implemented and until these changes are re-created by the automation process.

**Definition of done**
Documentation of the manual process for making changes to cluster configuration and project namespaces resource quotas. **Include a link to the document in the GitHub before closing this ticket.**

**Comment by juhewitt** [comment]
Thank you. :)

**Comment by mitovskaol** [comment]
Still relevant

**Comment by IanKWatts** [comment]
A new doc has been created in Documize:
https://docs.developer.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/c7gtmu56gr5oi9p8ku90/how-to-update-cluster-apps-and-project-sets-during-argo-cd-outage

**Comment by StevenBarre** [comment]
Should this be in the docs repo instead of Documize? https://github.com/bcgov-c/advsol-docs/tree/master/OCP4/CCM

**Comment by IanKWatts** [comment]
> Should this be in the docs repo instead of Documize? https://github.com/bcgov-c/advsol-docs/tree/master/OCP4/CCM

Maybe.  Would you rather see it in that repo?

**Comment by IanKWatts** [comment]
Moved the doc to here: 
https://github.com/bcgov-c/advsol-docs/blob/master/OCP4/CCM/manual_updates.md
