### ISSUE TITLE
AG/PSSG Aporeto Enforcer configuration (OCP 4 <> Zone B)

### ISSUE THREAD

**Issue by NickCorcoran** [BCDevOps/developer-experience#724]
**Describe the issue**
Setup Aproeto enforcer proxies for AG/PSSG OCP 4 <> Zone B connectivity

**Which Sprint Priority is this issue related to?**
Early adopters

**Additional info
Documize - Aporeto enforcer setup guide
https://docs.pathfinder.gov.bc.ca/s/bn6v0ac6f9gue7hhirbg/protected-platform-services/d/bonkqskhpp5rkld1o310/aporeto-enforcer-in-network-zone-setup-guide

**Definition of done**
- [ ] AG/PSSG - Open up firewall b/w OCP 4 and existing Aporeto enforcer proxies in AG/PSSG DMZ
- [ ] Lab - ensure correct access to create/edit proxy rules
- [ ] AG/PSSG - test access to Aporeto console to create/modify rules for proxy host

**Comment by NickCorcoran** [comment]
Target to complete setup by Dec 4th for Test Environment.

**Comment by agahchen** [comment]
Hi @NickCorcoran wonder if you updates on this ticket.  

Thanks,
David

**Comment by NickCorcoran** [comment]
@agahchen i sent you a note in RocketChat

**Comment by NickCorcoran** [comment]
Closing due to shifting away from Aporeto use.
