### ISSUE TITLE
Renew wildcard certificates in 3.11 PROD cluster

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#730]
Business stakeholders will need to purchase a new wildcard SSL certificate for *.pathfinder.gov.bc.ca since the current certificate expires January 31st 2021 and it is extremely unlucky the existing 3.11 PROD cluster will be 100% decommissioned by then.

The 3.11 LAB wildcard certificate is not likely to be renewed since that certificate expires July 27 2021, but it can be revisited if still online within 90 days of that renewal and we start receiving similar alerts for pending expiry as we did for PROD.

Methodology docs for the creation/replacement of this certificate: <https://github.com/bcgov-c/advsol-docs/blob/master/Maintenance.md#replace-tls-certs-for-consoleweb-ui>

**Definition of Done**
- [x] Request Luke Gonis or equivalent stakeholder to submit iStore order.
- [x] DXC to provide new CSR for signing upon request.
- [x] DXC to install replacement certificate during an appropriate RFC.

**Comment by tbaker1313** [comment]
Submitted CSR request for istore process.

**Comment by lukegonis** [comment]
@tbaker1313 update from CITZ Service Desk received on December 10: 

Hi Luke,

iStore #1050116 is Booked (EA-approved) and awaiting_shipping. That means it should be 'in process'. It was approved back on Dec. 1. For more detail than that you'd have to talk to 77000 Opt 3. We can only see the status of orders, we can't see where they are in their process.


Thank you,

**Comment by tbaker1313** [comment]
This is scheduled for Thursday Jan 21st in CHG0021780

**Comment by tbaker1313** [comment]
Certificate has been successfully replaced.
