### ISSUE TITLE
Sysdig docker pull improvements

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#735]
**Describe the issue**
Docker has implemented rate limiting of anonymous pulls. Sysdig is currently configured to always pull its image. When doing rolling reboots of nodes it will likely fail to pull its image.

**Additional context**
~~https://chat.pathfinder.gov.bc.ca/group/internal-platform-services?msg=mP6MYboCDwubpyE3R~~
https://chat.developer.gov.bc.ca/group/internal-platform-services?msg=mP6MYboCDwubpyE3R

Repo where 3.11 Sysdig code resides:
<https://github.com/BCDevOps/platform-services/tree/master/monitoring/sysdig>

**Definition of done**
- [x] Create a secret for the `bcdevops_cluster` user so the image can be pulled
- [x] Codify the secret and link to service account

**Comment by sbarre-esit** [comment]
Secret added to v3 PROD.

**Comment by sbarre-esit** [comment]
Blocked waiting on a strategy for managing the docker secrets.

**Comment by sbarre-esit** [comment]
https://github.com/bcgov-c/platform-services-docs/blob/main/DockerHub.md

Todo, codify the secret and document in https://github.com/BCDevOps/platform-services/tree/master/monitoring/sysdig

**Comment by tmorik** [comment]
Agent deployment commands have been updated in [the agent deployment document.](https://github.com/BCDevOps/platform-services/blob/master/monitoring/sysdig/docs/deployment.md) to avoid running into an issue with [docker rate limits](https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/).
