### ISSUE TITLE
OCP3 - occasional Kibana connectivity issues with ES after 3.11.286 upgrade

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#736]
**Problem Description**

It was noted not long after a recent Openshift Container Platform (OCP) upgrade to the 3.11 PROD cluster that our internal monitoring noted the following recurring message as taken from the kibana pod logs:

```
message":"No living connections"
```

This was coupled with an occasional user noticing timeouts when attempting to load Kibana's web interface.

This ticket will track efforts spent towards investigating and resolving this issue.

**Definition of Done**
- [x] troublleshoot and investigate the root cause of this issue, using vendor support as needed
- [x] Apply any solution to the 3.11 LAB cluster first
- [x] Apply the same solution to the 3.11 PROD cluster
- [x] Confirm with Red Hat with new log dumps if we have sufficiently resolved the issue
- [x] Confirm with stakeholders who heavily use Kibana regarding performance and stability

**Comment by tmorik** [comment]
This is supported by the [RedHat's case 02804895](https://access.redhat.com/support/cases/#/case/02804895/discussion?commentId=a0a2K00000V2VeoQAF).  

As suggested in the case 02804895, ES components 3.11.286 should be updated by the in LAB OCP 3.11 has been patched from 3.11.286 to 3.11.318 on Nov 23, Monday.

The steps I took for the LAB ES components were in this doc :   https://github.com/bcgov-c/advsol-docs/blob/master/OCP-Upgrade.md#fifth-step---upgrade-efk-logging-stack  (with Pre-flight check and Final checks)

**Comment by tmorik** [comment]
CHG0020388 - CITZ - PROD OCP 3.11 ES components upgrade from 3.11.286 to 3.11.318- has been scheduled to Nov 26, 0900-1600. 

https://github.com/BCDevOps/platform-services-status-page-notifications/blob/master/notifications/11-26-20-0900.md

**Comment by tmorik** [comment]
CHG0020388 - CITZ - PROD OCP 3.11 ES components upgrade from 3.11.286 to 3.11.318- has been completed. Looks like the result of this patching is promising. That "No living connection" message caused by "XXX was leaked" error on ES was drastically reduced already:

```console
$ oc logs  -c elasticsearch logging-es-data-master-3n01e7r7-17-f5mkp | grep "was leaked" | wc -l
0
$ oc logs  -c elasticsearch logging-es-data-master-5165jhq6-18-pgj8v | grep "was leaked" | wc -l
0
 $ oc logs  -c elasticsearch logging-es-data-master-a48fs3s5-16-978jq | grep "was leaked" | wc -l
0
PROD/logging ~/platform-ops (master *$%) $ oc logs  -c kibana logging-kibana-17-bpwpm | grep "No living" | wc -l
7
``` 

Only 7 messages for "No living" messages which were generated by the patching. And "xxx was leaked" errors are down to "0", which were "6000 ~ 60000"  before. 

ES cluster status is still yellow status and slowly healing. I will check that status tomorrow.

**Comment by wmhutchison** [comment]
Our monitoring for the Kibana log error message has gone away, but we're still seeing some issues involving the Elasticsearch pods and occasional failure on readiness checks.. Have updated the Red Hat case and today will be taking a new log dump of the entire EFK stack for Red Hat to analyze further.

**Comment by wmhutchison** [comment]
Had not seen or heard of any issues involving this for a while now. Closing off this issue.
