### ISSUE TITLE
Platform Docker Pull decisions and support

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#737]
## Description

As of November 4th Docker Hub has implemented rate limits on anonymous ( and to a lesser extent on non-anonymous)  free accounts’ ability to pull images within a 6 hrs window (only 200 pulls are allowed within this window). As a result, this put the Platform Services team  at risk for not being able to pull many critical images such as Aqua, Aporeto, and Sisdig that are required for keeping the Platform up-to-date and also in the case of a Platform restore, as the Docker free account is shared with the entire Platform Community (190 apps)

With the changes to docker's registry access, teams are now required to leverage their own docker ID, or leverage Artifactory's pull through docker ID.  Clear documentation and cluster configuration are required to ease the developer experience.

Options to be tested:
#### Option A) Update the Cluster Default pull secret
If we would like to support teams pulling without rate limits, can we update the cluster's global pull secret with appropriate docker.io credentials?
https://docs.openshift.com/container-platform/4.6/openshift_images/managing_images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets
- Success would be teams would not need to add any secret to their namespaces, and images with no registry reference (that leverage the cluster registry search path) are able to pull from docker.io, using the cluster's account, without rate limits.

#### Option B) Update the cluster registry search path
If we would like to disable anonymous docker.io pulls on the cluster, removing docker.io from the default registry search path will improve clarity for image pull error messages.  This would force teams to put the `docker.io` registry name into their image references, which is a requirement when using a namespace'd pull secret.

#### Option C) Create/update cluster default pull secret for Artifactory pull-through repositories.
As an alternative to provisioning separate namespace accounts for artifactory caching repositories - create a single cluster account for a cluster, add creds as per *Option A*, add URL's for all artifactory image caching repo's (or a single entrypoint with a virtual repository?)

**Definition of done**
Option A or B chosen, implemented and documented for developers.
Option C tested with any recommendations on Artifactory implementation for caching.

**UPDATE:  The Platform Services Team  has purchased an organization membership for $35 USD/month (that comes with the unlimited rate) so that we can ensure the Platform operates as expected and so that we can, through the use of Artifactory, provide unrestricted access for the wider OpenShift Container Platform community.  The username is `bcgovdevops` (ask Olena or Jason for password). The account includes an organization https://hub.docker.com/orgs/bcgovdevopsps and comes with 5 service accounts:  DOCUMENT HERE HOW THE SERVICE ACCOUNTS ARE USED:**

1. bcdevopsartifactory
2. bcdevopscluster
3. bcgovdevops 
4. TBD
5. TBD

**Comment by lukegonis** [comment]
the service accounts links to the paid dockerhub account, there use and the platform apps that use the service account are documented in the private platform services docs repo.

https://github.com/bcgov-c/platform-services-docs/blob/main/DockerHub.md
