### ISSUE TITLE
Investigate new IAM options in ECS

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#741]
It would be super cool if we could offer an object storage service to teams via ECS for whatever their purposes.  In order for us to be able to effectively offer an object storage service, we need to be able to create a bucket with a specific quota and give out access to that bucket. This was not possible before because ECS did not allow granular control over certain types of access, meaning all users were able to create new buckets with whatever quota they want, which obviously interferes with our ability to control quota.

A recent update to ECS has added IAM privilege control, which looks like it should give us the ability to prevent users from creating other buckets. The first step in offering this sort of object storage service will be to confirm that there is an IAM privilege definition which suits our requirements.

**Definition of Done**

- [ ] Create a test user (preferably programmatically) with suitable privileges (ie: write access to a bucket without the ability to create new buckets)

**Comment by mitovskaol** [comment]
@caggles What is ECS and is it related to the S3 Object Storage Services offered by Enterprise Hosting?
