### ISSUE TITLE
Documize BD backup issue

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#742]
**Describe the issue**
We are getting `PQgetCopyData()` from backup-container again. This is the same error message from previously which might be caused by some large attachment taking too long to copy.

**Additional context**
(can't find the previous ticket..)

**Definition of done**
-  investigate into what the actual cause is
- see if it's needed to extend the timeout more
- or switch backup time to overnight to avoid high network traffic

**Comment by ShellyXueHan** [comment]
### Update:
- daily and weekly backup are calling the sam backup function
- if weekly backup does not have the issue, suspect it's the network traffic difference where weekday takes longer which excess timeout

**Comment by caggles** [comment]
This issue appears to have fixed itself again - i would like to keep this ticket open in order to figure out what is actually happening to cause this.

**Comment by ShellyXueHan** [comment]
seeing backup issue again:
```
Backing up documize-patroni-master-prod:5432/documize ...
pg_dump: Dumping the contents of table "dmz_doc_attachment" failed: PQgetCopyData() failed.
pg_dump: Error message from server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
pg_dump: The command was: COPY public.dmz_doc_attachment (id, c_refid, c_orgid, c_docid, c_job, c_fileid, c_filename, c_data, c_extension, c_created, c_revised, c_sectionid) TO stdout;
removed '/backups/daily/2021-01-04/documize-patroni-master-prod-documize_2021-01-04_09-00-00.sql.gz.in_progress'
[!!ERROR!!] - Failed to backup documize-patroni-master-prod:5432/documize.
```

**Comment by ShellyXueHan** [comment]
documize has been migrated to ocp4. issue not applicable now. closing ticket
