### ISSUE TITLE
Install Cost Management Operators in SILVER

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#744]
**Describe the issue**
Platform Services Team would like to have crost management operators installed in Silver cluster

https://www.redhat.com/en/blog/introducing-openshift-cost-management-human-readable-view-cloud-native-application-costs

**Additional context**
Cost Management service for Openshift will allow us to get more insight into application cost.

**Definition of done**
Install and enable the cost management parts on the Silver cluster a per instruction here 
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.5/html/getting_started_with_cost_management/assembly_adding_sources_cost#installing_cost_mgmt-operator

**Comment by sbarre-esit** [comment]
Created #765 to track installing this in KLAB and the initial devel work. Moving to silver should be fairly simple once that is complete.

**Comment by StevenBarre** [comment]
PR https://github.com/bcgov-c/platform-gitops-gen/pull/75 created to move to SILVER.

**Comment by StevenBarre** [comment]
Pushed live and confirmed the Source was created in cloud console. Data should be flowing now.
