### ISSUE TITLE
Migration to the paid Docker account for Platform services

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#745]
**Describe the issue**
As of November 4th Docker Hub has implemented rate limits on anonymous ( and to a lesser extent on non-anonymous)  free accounts’ ability to pull images within a 6 hrs window (only 200 pulls are allowed within this window). As a result, this put the Platform Services team  at risk for not being able to pull many critical images such as Aqua, Aporeto, and Sisdig that are required for keeping the Platform up-to-date and also in the case of a Platform restore, as the Docker free account is shared with the entire Platform Community (190 apps).
 
To mitigate the risk, the Team  has purchased an organization membership for $35 USD/month (that comes with the unlimited rate) so that we can ensure the Platform operates as expected and so that we can, through the use of Artifactory, provide unrestricted access for the wider OpenShift Container Platform community.

**Additional context**
- [x] Investigation on what Platform Services namespaces (across ALL clusters) require access to the credentials -> document the list here

@j-pye to generate a list of applications in CCM that use Docker Hub. All these application use the same set of credentials and have been updated with the paid Docker account.
**The Platform Services Team will update the Docker account for the PS applications as they get migrated to OCP 4 as currently there is no easy way  to verify that all PS namespaces in OCP 3.11 use the paid account (it would require a significant time and effort to do this manually).**

- [x] Documentation (for PS Team) on how credentials are to be used, where to access, and any other tracking info needed (tracking is important for things like "what happens if we have to change a password?")

All Platform Services secrets including the paid Docker credential and Artifactory licenses will be stored in Vault. To be determined who owns the Vault service account (Olena to check with Nick and Justin). The Platform Services Team members will have access to the Vault Services account on the need to know basis. All Platform Services apps are supposed to be using the paid Docker account, however, the paid Docker account **should not be used to store images**, all images should be stored in Artifactory or in the internal Openshift cluster registry.

The Platform Services team owns the **bcgovdevopsps** organization in Docker. The bcgovdevopsps organization includes 5 service accounts, their use is documented [here](https://github.com/bcgov-c/platform-services-docs).

- [x] Investigation re: any additional policy/paperwork requirements around providing access to docker via a gated use? (are there new requirements for SLA if something to do with pulling from dockerhub fails now that we are using a platform account?)

Nick to provide more details.

-  [x] tickets created for all PS namespaces identified that require a credential configured.
The list of all PS namespaces is documented [here](https://github.com/bcgov-c/platform-services-docs/blob/main/platform-services-apps.csv). The ticket will be created to update all PS namespaces in OCP 3.11 with the paid docker account.

**Definition of done**
All the above is discussed, and the decisions are documented in this ticket.

**Comment by sbarre-esit** [comment]
OCPv3
- devops-sysdig
- trident

OCPv4
- trident
- f5-cis
- devops-security-aporeto-enforcers

The PodInjectorSelectors provided by CCM in every project should point to the internal registry instead of to the dockerhub image for the Aporeto init container.
