### ISSUE TITLE
Document Payment Design Pattern from PayBC in DevHub

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#746]
**Describe the issue**
Document the recommended design pattern for payment processing for Openshift apps from PayBC and make it available to the developer community through DevHub.

**Additional context**
PayBC has develop a design pattern for Openshift applications that require payment processing that allows them to move all payment processing components outside of the Openshift Platform as the Platform is not PCI compliant at the moment. The design pattern includes an integration with the PayBC payment server.

**Definition of done**
- [ ] Create a documentaton in the openshift-wiki repo that documents the design pattern and can be used as a how-to guide for the teams that need to implement payment processing in their apps. Re-use the content from the docs that the PayBC has emailed us , as much as possible.
- [ ] The article should be searchable in DevHub by the keywords: "payment", "paybc", "pci dss"

**Comment by NickCorcoran** [comment]
Drafted in .md and shared for comment.

**Comment by juhewitt** [comment]
Looks like @NickCorcoran  something for your review @SPIRANIGOVBC & @satsingh263.  If you are around this or next week, let me know how we're doing here.

**Comment by NickCorcoran** [comment]
Review complete and updated with recommendations.  Sent to MISO for review before posting.

**Comment by NickCorcoran** [comment]
Changes made.  DevHub needs re-deploy to show up, but work is done.

**Comment by NickCorcoran** [comment]
.md lives here: https://github.com/BCDevOps/developer-experience/blob/master/docs/PCIDSSPatternforOCP.md
- future PRs against that location and DevHub will reference.
