### ISSUE TITLE
Run simulation test for "OCP 4 Upgrade process unable to upgrade a node" in KLAB

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#749]
**Describe the issue**
As a member of Platform Operations Team I need to better understand the behaviour of an upgrade process in Openshift 4 when it gets stuck on a certain node and  cannot complete the node upgrade successfully.  I suspect that the manual intervention will be required to resume the upgrade process because the cluster will always try work towards the desired state which is the upgrade.

**Additional context**
Related ticket: [https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/262](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/262)

Test Setup (as per TAM's recommendation)
- [ ] Create a pod on one of the nodes in KLAB with a disruption budget of 0 so it can't be drained without manual intervention
- [ ] Run an upgrade using max unavailable of 2 

**Definition of done**
Document the outcome of the test in this ticket.

**Comment by sbarre-esit** [comment]
I think I already did most of this in https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/663 ?

**Comment by mitovskaol** [comment]
arghh, my search did not find that one so I created a new ticket. closing as a duplicate. The outcomes of the test documented in advsol-docs repo.
