### ISSUE TITLE
Deploy Operator using pipeline

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#754]
**Describe the issue**
When the operator should be deployed in the Artifactory pipeline, in the step following the artifactory updates (if there are any)

**Definition of done**

- [ ] Decision on how to handle cluster-admin level steps for installing the operator.
- [ ] Operator is installed from build created in earlier pipeline step.
- [ ] Updating the Operator does not result in an installation change to Artifactory itself.

**Comment by jefkel** [comment]
What do you think of separating the Service Provisioning operator from the Artifactory Service completely?  (I also think the Operator needs a name other than "the operator"?)

**Background:**
- Artifactory Service will be deployed as a stand alone service (dev/test/prod, eventually a DR sync capability)
- SVC Account and Repo provisioning operator will need to be deployed to every cluster that needs self-serve Artifactory access for namespaces.

**Proposal**
Provisioning Operator fits nicely within the CCM framework (including the privileged parts of the process) and this would satisfy the deployment pipeline piece for the operator.

The KLAB operator would link to a -dev deployment of Artifactory, and the other clusters would link to the production Artifactory service.

Add additional metadata to the provisioned artifactory objects (service accounts, repositories, etc) to indicate the provisioning cluster (audit and back-tracing requirements) - this would either be labels, groups, cluster reference encoded into username, etc.

**Comment by caggles** [comment]
Closing as we are going to use CCM to install Archeobot, so we don't need to integrate it into the pipeline.
