### ISSUE TITLE
Document node draining settings

### ISSUE THREAD

**Issue by sbarre-esit** [BCDevOps/developer-experience#755]
**Describe the issue**
Some developers are setting the pod termination grace period to crazy high values. When draining a node, the Ops team caps that to 10 min. Document this procedure so devs know what the limits are.

https://chat.pathfinder.gov.bc.ca/channel/patroni?msg=GYePCjfF826AtbYDQ

**Additional context**
https://github.com/BCDevOps/developer-experience/blob/master/docs/resiliency-checklist.md

**Definition of done**
https://developer.gov.bc.ca/Resiliency-Guidelines updated with info about the `oc adm drain` arguments used by Ops team.

**Comment by sbarre-esit** [comment]
https://github.com/BCDevOps/developer-experience/pull/766

**Comment by sbarre-esit** [comment]
PR merged. @jefkel I think Dev Hub picks up new content once a night? Can you confirm the new info made it and then close this task next week?

**Comment by jefkel** [comment]
@patricksimonian can you comment on expected devhub update timing? (just confirmed that updated markdown is not present in devhub yet)

**Comment by sbarre-esit** [comment]
Devhub has been rebuilt
