### ISSUE TITLE
SG - Artifactory Service - Pipeline Development v.1

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#762]
This sprint goal represents this sprint's work on getting Argo installed (and the installation process documented) and getting a few steps finished.

The outcome for this sprint will be full documentation on how to install Argo on a local namespace, templates for doing so, and documentation on using Argo that teams may be able to use in the future.

**Comment by caggles** [comment]
This ticket should be rolled over to next sprint. Current ticket status:

- #752 is almost finished. 
- I have spoken to Afan about the status of #791 and we should get some content for that fairly soon. 
- I did not have an opportunity to work on #751, but that was a stretch goal anyway. 
- Some work has been done on #772 but this task should be de-prioritized as it focuses on a very specific bug that is probably not worth the work it's currently requiring. It is important that it be completed eventually, but it does not need to be worked on right now.

For next sprint, I plan to shift a bit of focus towards some of the user requests for Artifactory. I definitely want to implement the secret-deletion feature for the service accounts in sprint 22. I think maybe that will be my top priority for the coming sprint, and the rest of the points for the sprint can be filled out with further work on this ticket, though I would also like to discuss the possibility of working on the design document for private local repos.
