### ISSUE TITLE
Make OCP 4 Migration content searchable in DevHub

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#767]
The collection of pro tips, FAQs and guidelines documented in OCP 4 migration repo need to be searchable in DevHub.

DoD: Searching for any of the keywords that appear in https://github.com/BCDevOps/OpenShift4-Migration/issues or https://github.com/BCDevOps/OpenShift4-Migration folders should bring up this content in DevHub.

**Comment by AndrewJun97** [comment]
The Devhub can currently search for github issues, although the user needs to be logged in for this. I see that I can search for issues on the OpenShift4-Migration repo on the Devhub. Is this what you mean?
