### ISSUE TITLE
Create SSO interface for users to subscribe/unsubscribe to the mailing list

### ISSUE THREAD

**Issue by AndrewJun97** [BCDevOps/developer-experience#769]
## Summary
Users should be able to subscribe/unsubscribe to mailing lists without the need to go through the PO. At the same time, only the user should be able to remove themselves from the mailing list.

## Definition of Done
An SSO interface for IDIR and Github authentication is set up for users to subscribe/unsubscribe to mailing lists

This would include:
- wireframing a simple design
- infrastructure code

**Comment by patricksimonian** [comment]
I like it. Should be a pretty simple web app.
