### ISSUE TITLE
Ansible script update

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#772]
**Describe the issue**
Right now, the Ansible script for Artifactory covers all required installation steps and almost all required update steps. It was recently discovered that some objects defined in the deployment config are not updated in the pods when the deployment config is reapplied. Therefore, updates are required make it so the ansible script actually updates artifactory properly.

Also, changes need to be made in order to update Artifactory without bringing down the service.

**Definition of done**

- [ ] Confirm which objects are and are not updated via the deployment config
- [ ] Update Ansible script to ensure these objects are updated appropriately
- [ ] Update Ansible script to ensure that the primary and member pods are updated at different times, ensuring there is no downtime.

**Comment by afanrasool** [comment]
This needs to be prioritized. This is only a blocker for upgrades. Can be deemed an improvement task but other tasks take precedence over this.

**Comment by lukegonis** [comment]
Closing, no longer relevant
