### ISSUE TITLE
Add cross-cluster sync to pipeline

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#774]
**Describe the issue**
Once Gold cluster is available, we will want to add cross-cluster sync to the pipeline.

**Additional context**
We'll need to figure out how to do cross-cluster sync first.

**Comment by mitovskaol** [comment]
@IanKWatts This one seems to be relevant to your work on the Artifactory pipeline so adding you to the ticket.

**Comment by caggles** [comment]
I did some investigation into how the cross-cluster stuff works - you don't really "add cross-cluster sync" as a pipeline step the way I thought. I'll open a different ticket that's more appropriate.
