### ISSUE TITLE
Aporeto OCP4 Namespace Migration

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#778]
**Describe the issue**
As a PS Admin or Cluster Admin, I'd like to have monitoring and alerts for Aporeto related resources within OpenShift 4. To accomplish this we need to move Aporeto DaemonSets and Operators into namespaces with an `openshift-` prefix. 

**Definition of done**
- [x] Aporeto Ansible Playbooks Updated to Support Namespace Migration
- [ ] Tested in KLAB
- [ ] Approved by DXC
- [ ] Migration performed in Silver

**Comment by sbarre-esit** [comment]
Justin is doing work on this branch https://github.com/BCDevOps/platform-services/tree/ocp4-aporeto/security/aporeto/build/ansible

Had a call with William and myself and reviewed the progress.

Decided to push the change in SILVER out to next week to give us time for testing and for ample notification to tenants as the change requires a rolling drain of all the nodes.

**Comment by wmhutchison** [comment]
@sbarre-esit Opened a Red Hat case as well (https://access.redhat.com/support/cases/#/case/02824287) to confirm whether or not Red Hat is comfortable with us leveraging existing AlertManager rules for monitoring assets not part of the Red Hat Openshift solution or forseeing possible issues with our reliance on this technology to perform monitoring for us.

**Comment by sbarre-esit** [comment]
Confirmed with Red Hat that as long as we don't have a name collision, this should be fine. Decided to go with `openshift-bcgov-*` prefixes on our custom namespaces.

**Comment by j-pye** [comment]
Testing will continue in KLAB tomorrow to ensure the Aporeto Operator can recover properly when started within the new namespace. Enforcer DaemonSet migration has been implemented within the playbook and is working as expected. However, the operator writes to the enforcer namespace so we must have that working as well in order to perform the migration.

Namespaces:
- openshift-bcgov-aporeto-enforcers
- openshift-bcgov-aporeto-operators

@sbarre-esit do you think the NSP operator should also continue to live in the same namespace as the Aporeto Operator or would another namespace with or without the `openshift-bcgov-` prefix be prefered ?

**Comment by sbarre-esit** [comment]
I think its fine to leave in the same namespace. If moved it should also be in a `openshift-bcgov-` prefix though.

**Comment by j-pye** [comment]
This ticket will not be completed at this time. The aporeto enforcers will continue to live in `devops-security-aporeto-enforcer` and the aporeto operator will continue to live in `devops-security-aporeto-operators`. There is no easy or straight forward way to move the resources created by the Aporeto Operator. This includes aporeto Namespace and NamespaceMapping Objects which sync with the Aporeto Console to create Aporeto namespaces. Removing these namespace objects will remove them from the Aporeto console causing disruptions for our platform tenants.

"Thinking out loud"
We could disable the operator, delete the resources, move the aporeto enforcers and operators, and allow the operator to regenerate all of the resources when we turn it back on. Extensive testing would be required to ensure the network stays online and operational for tenants. The worry is that the newly created objects will delete and recreate the aporeto namespaces due to changes in their UID which would result in temporary downtime for tenants until their policies re-sync. 

Happy to go down this rabbit hole or wait to do the move during the Prisma Cloud Migration. Not going down the rabbit hole will require additional monitoring / alerting work by the DXC team.  (No I can not estimate how long it will take to test, too many scenarios to easily put a number on)

Closing for now. If you'd like this work to proceed please let me know. /cc @mitovskaol
