### ISSUE TITLE
Implement Zero Trust networkSecurityPolicy for sysdig namespace

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#781]
**Describe the issue**
NetworkPolicy zero trust policy is required for the SysDig namespace.

**Additional context**
sysdig-agent deployment is managed through CCM workflow in the `sysdig-agent` role.

**Definition of done**
- [ ] zero-trust networkPolicy implemented in aro.pathfinder
- [ ] networkPolicies validated in KLAB
- [ ] zero trust networkPolicy updated in CCM generator.
- [ ] zero-trust networkPolicy implemented in CLAB
- [ ] zero-trust networkPolicies implemented in Silver
- [ ] zero-trust networkPolicy implemented in GOLD(Kam)

**Comment by j-pye** [comment]
Aporeto has been completely removed from all clusters as of March 24th, 2021.
