### ISSUE TITLE
Sysdig-Agent deployment to Silver

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#782]
**Describe the issue**
DXC team to deploy the Sysdig Agent to the silver cluster using CCM.

**Additional context**
Sysdig-agent CCM configuration has been developed and deployed successfully to KLAB.  This is the followup handoff to DXC for a production deployment.

**Definition of done**
- [x] Sysdig-Agent running successfully in Silver cluster (deployed by DXC)

**Comment by sbarre-esit** [comment]
https://github.com/bcgov-c/platform-gitops-gen/pull/35

**Comment by sbarre-esit** [comment]
CHG0021024 - MCS SILVER - Install Sysdig Agent
scheduled for Dec 11th at 9am

**Comment by sbarre-esit** [comment]
Sysdig installed.
