### ISSUE TITLE
Migrate Documize to oidc.gov.bc.ca

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#783]
**Describe the issue**
Migrating this application to utilize oidc.gov.bc.ca as its sso endpoint for auth flows as sso.pathfinder.gov.bc.ca is now deprecated

**Definition of done**
App utilizes oidc.gov.bc.ca for auth flows

**Comment by ShellyXueHan** [comment]
### Update for @AndrewJun97 :
- I've got the test documize setup here: https://docs-test.pathfinder.gov.bc.ca/ login with your IDIR and you'll have admin role (I've pre-set that already)
- and now you can test out changing the SSO url (that should be the only thing) in settings->authentication in the test instance. try creating some private content and test on permission after the change.
- work with @patricksimonian to take a DB backup in production before actioning there (namespace: `hmg6pw-prod`)

**Comment by AndrewJun97** [comment]
Complete, db has been backed up and pushed to prod.
