### ISSUE TITLE
Add grouping label to all Platform Services app namespaces in OCP 3.11

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#785]
The list of Platform Services owned apps is documented in [here](https://github.com/bcgov-c/platform-services-docs/blob/main/platform-services-apps.csv)

- the grouping label we are using is `product_group`
- to get a list of PS namespaces: `oc get projects -l "product_group=platform_services"`

**Comment by ShellyXueHan** [comment]
outdated ticket. closing!
This will be done in ocp4 with registry app.
