### ISSUE TITLE
Reduce Sysdig Rolebinding scope

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#786]
**Describe the issue**
In OCP3 there was a [custom role](https://github.com/BCDevOps/platform-services/blob/0bc1b59be6f4adbbbf763b72abfb6d7e6b7c96ae/monitoring/sysdig/operator/sysdig-monitor/deploy/role.yaml) used for the service account with just enough access. In OCP4 it is currently just using [cluster-reader](https://github.com/bcgov-c/platform-gitops-gen/blob/f3215397d3571b2492f8d4ad2246aee172bbb738/roles/sysdig_agent/templates/crb-sysdig-agent-reader.yaml.j2).

ArgoCD should be updated to use the reduced role from OCP3 or as minimal a role as we can.

**Additional context**

**Definition of done**
- [ ] PR to update code tested in KLAB
- [ ] PR to apply to Silver

**Comment by jefkel** [comment]
There are 2 distinct Sysdig applications deployed on the clusters:
`Sysdig-Agent` - metrics collection daemonset
`Sysdig-Teams` - Custom operator that configures the app.sysdigcloud.com cloud teams for SaaS access.

Could you clarify whether this task is referring to `Sysdig-Agent` or `Sysdig-Teams` service account?

Checking on pathfinder lab, it looks like the `sysdig-agent` service account runs with cluster-reader.  The custom cluster-role you've referenced looks like it relates to the `sysdig-teams` custom operator.

**Comment by StevenBarre** [comment]
Ah I thought both were for the agent. If the Agent can't be run with any less privilege then we can close this.
