### ISSUE TITLE
Update Platform Service apps to utilize docker hub service account for image pulls

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#788]
## Summary

There are many platform service apps that still do not utilize a docker pull secret to pull images from docker hub. 

## To Do
Investigate the build and deploy infrastructure code for the following apps to see if they pull from dockerhub and if they do, create a pull secret using our service account for dockerhub.  
- obtain the access token for one of those service accounts
- create a docker registry secret (`oc create secret docker-registry`) in the needed namespaces to use as the `PullSecret` value
- [x] devhub web - i do not think this utilizes dockerhub
- [x] devhub api - i do not think this utilizes docker hub
- [x] rocketchat - this probably does
- [x] documize - this probably does
- [x] reggie web -  i do not think this utilizes docker hub
- [x] reggie api -  i do not think this utilizes docker hub
- [x] realm o matic web -  i do not think this utilizes docker hub
- [x] realm o matic api -  i do not think this utilizes docker hub
- [x] realm o matic ansible - this might
- [x] ocp-sso
## Definition of Done

All apps that require pull secrets have them :)

**Comment by AndrewJun97** [comment]
The following apps do not pull from docker:
- devhub web
- devhub api
- reggie web
- reggie api

The following apps pull images from docker and have been added image pull secrets
- rocketchat
- documize
