### ISSUE TITLE
Artifactory multi-cluster naming

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#79]
Artifactory will be deployed to multiple clusters and will synchronize content between self contained deployments.  Developer access to the artifactory repositories will need a consistent naming convention.

Document a multi-cluster naming and synchronization model for an artifactory service deployed across multiple clusters/sites.

**Comment by caggles** [comment]
This ticket is no longer applicable - the Artifactory service is not being installed across multiple clusters, it's only being installed on one, accessible via the operator on multiple clusters.
