### ISSUE TITLE
Implement Kraken in KLAB/CLAB

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#795]
**Describe the issue**
- Roadmap Item for fiscal year 2021/2022

**Additional context**
https://www.openshift.com/blog/introduction-to-kraken-a-chaos-tool-for-openshift/kubernetes
https://github.com/openshift-scale/kraken

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by StevenBarre** [comment]
Kraken should be run from the util host, or a local VM. (Tested in local VM)

Install podman-compose
```bash
sudo pip3 install podman-compose
```

Edit the `docker-compose.yaml` file to be compatible with podman networking. Also adjust the path to the kube config file.
```yaml
ELASTICSEARCH_HOSTS: "http://host.containers.internal:9200"
```

If your VM only has once vCPU adjust `config/cerberus.yaml` to have `cores_usage_percentage=1.0` 

Fire up the helper pods.
```bash
podman-compose up
```

Will take a few minutes to come up and stablize. Happier if your VM has more memory, ES is a hungry boi.

Once its all up, and you can `curl -v http://0.0.0.0:8080` and get back a `True` from Cerberus, you can run Kraken.

```bash
podman run --rm --name=kraken --net=host \
  -v ~/.kube/config:/root/.kube/config:Z \
  -v ./config/config_performance.yaml:/root/kraken/config/config.yaml:Z \
  -v ./config/kube_burner.yaml:/root/kraken/config/kube_burner.yaml:Z \
  -v ./scenarios/:/root/kraken/scenarios:Z \
  quay.io/openshift-scale/kraken:latest
```

**Comment by StevenBarre** [comment]
Most of the Node scenarios, and all of the Cloud scenarios require the cluster be running in a cloud where API calls can be used to shut down nodes.

The two Node scenarios that work in a `generic` cloud, require manual intervention to resolve before the test times out.

Time scenarios also don't auto-recover. Maybe they do in a cloud?
