### ISSUE TITLE
Test ring buffer adjustment 

### ISSUE THREAD

**Issue by tbaker1313** [BCDevOps/developer-experience#799]
RH Case 02821135

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/monitoring-and-tuning-the-rx-ring-buffer_configuring-and-managing-networking

**Comment by StevenBarre** [comment]
`sum(rate(node_network_receive_errs_total[2m])) by (instance)` on https://prometheus-k8s-openshift-monitoring.pathfinder.gov.bc.ca/graph shows the errors we are trying to solve in v3.

You can also see the errors in `ifconfig` output.

```console
[root@ociopf-p-170 ~]# ifconfig eno49
eno49: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether e0:07:1b:ef:65:58  txqueuelen 1000  (Ethernet)
        RX packets 61608530273  bytes 70850603559127 (64.4 TiB)
        RX errors 338090  dropped 0  overruns 337616  frame 474
        TX packets 70063450239  bytes 81753642434153 (74.3 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16  memory 0x96000000-967fffff  

[root@ociopf-p-170 ~]# ethtool -g eno49
Ring parameters for eno49:
Pre-set maximums:
RX:             4078
RX Mini:        0
RX Jumbo:       0
TX:             4078
Current hardware settings:
RX:             453
RX Mini:        0
RX Jumbo:       0
TX:             4078

[root@ociopf-p-170 ~]# ifconfig eno50  
eno50: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether e0:07:1b:ef:65:5c  txqueuelen 1000  (Ethernet)
        RX packets 5262265680  bytes 5784643994537 (5.2 TiB)
        RX errors 2053  dropped 0  overruns 0  frame 2053
        TX packets 12661938185  bytes 17887022188000 (16.2 TiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 17  memory 0x97000000-977fffff  

[root@ociopf-p-170 ~]# ethtool -g eno50
Ring parameters for eno50:
Pre-set maximums:
RX:             4078
RX Mini:        0
RX Jumbo:       0
TX:             4078
Current hardware settings:
RX:             453
RX Mini:        0
RX Jumbo:       0
TX:             4078
```

So in theory we can test changing the settings with `ethtool -G eno50 rx 4078`

Questions to answer:

- Do all the HPE 10G nics have the same maximums?
- Does setting the RX buffer to the maximum reduce / remove the errors?
- Does setting the value via ifcfg file survive reboot?

These tests need to be done on nodes that are drained, in case there are negative outcomes.
-

**Comment by tbaker1313** [comment]
Initial implementation of this will be tested on February 20th during PROD 3.11 OS patching.

**Comment by tbaker1313** [comment]
This has been tested in 3.11 PROD. Required a network manager script and an adjustment to the relevant ifcfg-<interface> files. A new playbook has been created and merged into the tools part of platform-ops repo to record the steps required to implement this.

**Comment by tbaker1313** [comment]
This has been completed in 3.11 PROD. Closing.
