### ISSUE TITLE
reggie is broken

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#81]
When attempting to use Reggie to invite someone to Rocketchat, reggie produces an error for any user who tries to use the service, regardless of whether they log in with github or idir.

**Comment by ShellyXueHan** [comment]
Updates:
reggie service account is having the same issue as realm-o-matic where the auth token grows too long. Moved to the same temporary client at the moment.

Further Plan:
A: depends on the auth token issue https://issues.redhat.com/browse/KEYCLOAK-1268
B: setup a separate service account in devhub realm
