### ISSUE TITLE
Migrate DXC Nagios Monitoring to alert MCS on-call instead of Linux on-call

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#816]
**Description**
Changing DXC Nagios monitoring oncall email destination from Linux team to MCS team. 

**Additional context**
-DXC internal ticket # : SCTASK0174124

**Definition of done**
 - [x] Create new nagios monitoring templates
 - [x] Test templates in LAB OCP
 - [x] Deploy the new templates to all LAB nodes using ansible
 - [x] Deploy the new templates to all Prod nodes using ansible

**Comment by tmorik** [comment]
Nagios service monitoring templates below have been created and being tested using `ociopf-t-301.dmz`. 

Testing templates:
MCS_CPU_Usage
MCS_Cron_Heartbeat
MCS_Disk_Free_Space_/
MCS_Disk_Free_Space_/home
MCS_Disk_Free_Space_/opt
MCS_Disk_Free_Space_/tmp
MCS_Disk_Free_Space_/usr
MCS_Disk_Free_Space_/var
MCS_Disk_Free_Space_/var/log/audit
MCS_Disk_Usage_/
MCS_Disk_Usage_/home
MCS_Disk_Usage_/opt
MCS_Disk_Usage_/tmp
MCS_Disk_Usage_/usr
MCS_Disk_Usage_/var
MCS_Disk_Usage_/var/log/audit
MCS_Memory_Usage
MCS_NCPA_Listener
MCS_NCPA_Passive
MCS_NetIF_Bytes_Received_PROD
MCS_NetIF_Bytes_Sent_PROD
MCS_Swap_Usage
MCS_System_Uptime

**Comment by tbaker1313** [comment]
Have updated this in 3.11 LAB. Testing is undergoing.

**Comment by tbaker1313** [comment]
This should be completed. Leaving open for one more QA tomorrow January 15th. Last step is to check the notification groups for the mcs v4 entries.

**Comment by tbaker1313** [comment]
Verified this is completed. Closing.
