### ISSUE TITLE
Create Container Image for Pipelines

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#820]
**Describe the issue**
We're building the container images for the registry provisioning pipeline and ccm for every code change. 

Problems:
- This is slow, greater than 4 minutes per CCM pipeline run
- Dependencies are not locked in the default github actions images causing pipeline breakage if a dependency is updated with a change that isn't backwards compatible
- We're maintaining multiple nearly identical images which takes additional time from our sprint capacity

**Definition of done**
- [x] Container Image created in public github container registry (free) -- No PI or Code
- [x] CCM Dependencies met
- [x] Registry Dependencies met
- [x] Nightly or Weekly builds for Security Patches
- [x] Document adding the image to a github actions pipeline

**Comment by jefkel** [comment]
Could you add documenting the dependent operational flows?  Specifically calling out that as a critical pipeline image, updates need to be coordinated with 2 specific (and separate) pipelines

**Comment by mitovskaol** [comment]
@j-pye Is this still ongoing?

**Comment by j-pye** [comment]
Hasn't been worked on in a while but still needs to be completed.
