### ISSUE TITLE
Build an image for Sysdig Teams operator and publish to Artifactory

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#822]
**Describe the issue**
Build an image for Sysdig teams operator and publish to Artifactory

**Definition of done**
Sysdig Teams Operator has a Build Pipeline and centralised repository for all clusters to pull lab and prod images from.

**Comment by stewartshea** [comment]
The build pipeline has been modified to the ARO pathfinder cluster for now. We currently do not have a designated Artifactory repository for centralized storage.

**Comment by stewartshea** [comment]
Temporarily we are pushing to dockhub until artifactory is configured.

**Comment by mitovskaol** [comment]
Now that the Artifactory is available, this work can begin.

**Comment by ShellyXueHan** [comment]
@mitovskaol this is waiting for the artifactory remote repo which is not yet ready. Also Cailey mentioned that we'll need some team discussion on how we'd like to manage our images.

This ticket is still relevant but blocked!

**Comment by lukegonis** [comment]
This issue is still relevant and the Artifactory remote repo is ready/no longer blocking this issue
