### ISSUE TITLE
Track Aporeto Developer Early Access

### ISSUE THREAD

**Issue by j-pye** [BCDevOps/developer-experience#831]
This ticket is just meant to track teams with early access.

Please state the following in a comment:

- Teams Name
- Ministry
- Namespace License Plate (If you're not comfortable with this being in a public issue DM me)
- RC Username you can be reached at

**Comment by jujaga** [comment]
- Teams Name: **Common Services Showcase**
- Ministry: **Forests, Lands, Natural Resource Operations**
- Namespace License Plate: **a7f51d, a12c97, e9bfa5**
- RC Username you can be reached at: **jujaga**

**Comment by a-ell** [comment]
- Teams Name: **GDX CMF**
- Ministry: **CITZ**
- Namespace License Plate: **48aa05**
- RC Username you can be reached at: **adam.ell**

**Comment by jleach** [comment]
No longer relèvent as Aporeto no longer runs on the platform(s). Closing.
