### ISSUE TITLE
Create vanity urls for the Mautic app and Mautic Subscription app

### ISSUE THREAD

**Issue by AndrewJun97** [BCDevOps/developer-experience#832]
Vanity urls should be created for the Mautic App as well as the Mautic Subscription App

**Comment by AndrewJun97** [comment]
Vanity urls should be created for the Mautic App as well as the Mautic Subscription App

**Comment by mitovskaol** [comment]
Vanity URL has been created for Mautic Subscripttion app https://subscribe.developer.gov.bc.ca

There is no need to create a vanity URL for the Mautic app, so I am closing this ticket.
