### ISSUE TITLE
documize update

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#84]
There is a new version of documize out!

Step 1: time box a bit of time to figure out what the process looks like.
Step 2: finish implementing the backup container first
Step 3: update documize!

**Comment by ShellyXueHan** [comment]
Update:
Tasks included in https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/206
