### ISSUE TITLE
Deploy Sysdig Teams Operator in Silver

### ISSUE THREAD

**Issue by stewartshea** [BCDevOps/developer-experience#861]
Roll out the Sysdig Teams Operator in the Silver cluster after testing in KLAB and ARO. 
This task should only involve approving the PR  that contains the appropriate CCM ansible and k8s manifests, along with validating that the manifests apply properly through ArgoCD and the operator runs in the sysdig namespace. 

Definition of Done: 
- [x] The operator runs successfully in the same namespace as the sysdig agents
- [x] A team can deploy a SysdigTeam CR inside of their tools namespace and will receive access inside of the Sysdig application

**Comment by sbarre-esit** [comment]
CHG0022070 scheduled for Jan 20 13:00

**Comment by sbarre-esit** [comment]
I did some basic testing after installing and it seemed to work. But I'll let @stewartshea double check and then check off the DoD and close this.

**Comment by stewartshea** [comment]
I actually don't have access to any projects in Silver that would follow the tools/dev/test/prod naming pattern, so I think I need to take your word for it @sbarre-esit or I'll need to be added to a project set.

**Comment by stewartshea** [comment]
Tested in Olena's test project set; all looks good!
