### ISSUE TITLE
How to separate Artifactory Operator and Artifactory Service when docker routes must be created

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#862]
Require a design discussion about how to separate out the artifactory operator from the artifactory service when we still currently have designed the operator to create a route for new docker repos. We could potentially separate repo management and repo creation into two different things, where repo management is performed with the operator and the creation step has something different in it (maybe an API built into the artifactory namespace). We will need to discuss this further and document our design decisions.

https://miro.com/app/board/o9J_lYa3fTk=/

**Comment by jefkel** [comment]
I'm not sure why this was closed?

Still pending some q&a:
1. Do we require the subdomain DNS at all?
2. What does a separation look like (with documentation delivered into the repository?)

What comes next too? (defining next steps or is that captured elsewhere?)

**Comment by mitovskaol** [comment]
@jefkel @caggles Who is conducting this investigation ? Is this ticket blocking the entire Artifactory stream?

**Comment by caggles** [comment]
This ticket is a duplicate.
