### ISSUE TITLE
Reduce logging for Aporeto Operators

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#869]
**Describe the issue**
The pods in devops-security-aporeto-operators are generating a large amount of logs to be stored in EFK. 32 million logs per day on Jan 21st.

**Additional context**
There may not be much we can do to reduce this. It's not a major issue, more just something I noticed while looking into why the logging was running out of disk.

**Definition of done**
Less logs from operators

**Comment by jleach** [comment]
No longer relèvent as Aporeto no longer runs on the platform(s). Closing.
