### ISSUE TITLE
Developer Experience: Improve managed object documentation and naming conventions

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#876]
## Summary
With the new objects within a namespace that are managed through the Project Registry workflow, there have been reports of Developer teams struggling with trying to modify the managed objects, and not having the changes stay applied.  There is no clear indicator that a development team should not be modifying these objects directly, or where they need to go to modify the values in these objects.

## Motivation (Problem User Story)

A specific example:
- Project PO requests a project via the project registry and does not have all of the pre-requisite information available (eg: Person who fills the *Technical Lead* role) and enter a placeholder (like **TBD**) as the value.
- Project PO then logs into openshift and edits the `admin` rolebinding to add the new team member.
> *Project Sync resets admin rolebinding object in the background*
- Project Technical lead attempts to log into the cluster and does not have access to the namespace.
- Project PO checks the `admin` rolebinding, and does not see the manual changes.

## Proposal
A full solution would include both a technical change to the managed objects, as well as specific Developer Documentation created to walk teams through the new managed object usage.

### Technical Change
K8S objects created/managed by the Project Registry (or any other automated workflow) to be created with a *non-default* naming convention, and also have additional labels indicating what workflow manages their state.

Currently the project registry creates a single "admin" rolebinding object with the name "admin".
**Change to:** create 2 rolebinding objects:
**`Rolebinding Name`**: details
`project-provisioner-svcAcct`: Binds bcdevops-admin to a project admin role.
`project-provisioner-owners`: Binds appropriate PO and Tech lead users to the admin role.

Other Rolebinding name ideas:
`auto-provisioned-svcAcct`
`auto-provisioned-owners`

add an `app=xxx` label to the manifests to show which auto-provisioner app is managing the objects.

### Documentation addition
Documentation walking developer teams through the idea of managed manifests in their namespaces:
- What they are
- Why we have them
- How to recognize them
- Where to change them

## Definition of done
- [ ] Identify managed objects that require changes
- [ ] Technical change implemented in production for each managed object identified
- [ ] Developer Documentation created and published.

**Comment by mitovskaol** [comment]
Adding a note to discuss the naming convention for role bindings provided through the bot vs those added manually.

**Comment by mitovskaol** [comment]
@j-pye I this the DoD can be a post in the OCP 4 Migration repo in the Q&A format explaning what the `platform-services-controlled-admin` label is and what it is fod.
