### ISSUE TITLE
Governance Meeting: Evaluation and Direction

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#885]
**Describe the issue**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
-evaluate value/purpose of governance meeting

**Comment by lukegonis** [comment]
Waiting for final meeting where we will communicate decision to discontinue series.

**Comment by bevmcphee** [comment]
Met with Governance Team in Feb & decided to discontinue in current form.

**Comment by bevmcphee** [comment]
Going forward, we will bring Exec SMEs/Influencers together for adhoc "**Exec Advisory Counsel Sessions**" - topic specific, on an as-needed basis.
