### ISSUE TITLE
Create Platform Services team landing page

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#900]
As a Platform Services Team we need to have an online presence where everyone can learn about our work, team organization and short bios that includes areas of expertise.

DoD:
 - content developed and published in the [Team's Wordpress instance](https://platform-services-dev.apps.silver.devops.gov.bc.ca/)

**Comment by mitovskaol** [comment]
The Platform Services Team page will be created as part of the WordPress website development.
