### ISSUE TITLE
EDB Operator License Clarification

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#910]
**Describe the issue**
There are a few outstanding questions about the EDB licenses and how they related to our use of the operator

**Outstanding questions**
- Can we install in a namespace other than `openshift-operators`?
   - If not, are there plans to include this functionality in a future release?
- What privileges do the RDBA support teams require in order to support the operator?
   - Our providing these privileges depends on our ability to install the operator in its own namespace.
- Licenses are per-core, not per-instance. Do we have enough licenses to cover our needs? We currently have 12 prod licenses.

**Definition of done**
- [ ] All of the above questions answered
- [ ] Details included in the EDB Service Definition.

**Comment by caggles** [comment]
Waiting on answers from EDB people.

**Comment by mitovskaol** [comment]
@caggles Can you please document the vendor responses here so that we all have access to this information. Thanks!

**Comment by caggles** [comment]
> Can we install in a namespace other than openshift-operators?
> If not, are there plans to include this functionality in a future release?

No we can't, and no there are no plans to add this functionality. This is because the `openshift-operators` namespace requirement is something enforced by RedHat in order to allow the operator to be posted on OperatorHub. Therefore we can either consider installing it on `openshift-operators` or we can allow teams to install individual instances of the operator on their own namespaces.

> What privileges do the RDBA support teams require in order to support the operator?
> Our providing these privileges depends on our ability to install the operator in its own namespace.

The support teams don't generally expect to need access to the operator in order to perform their regular tasks. However, assuming there will _never_ be a problem with the operator seems extremely questionable, so we should consider providing _some_ privileges for troubleshooting purposes.

> Licenses are per-core, not per-instance. Do we have enough licenses to cover our needs? We currently have 12 prod licenses.

As far as we are able to tell, yes, we have enough licenses. Our current purchases cover the current number of cores being used by the existent Patroni instances (where applicable) and those projects which do not have a Patroni instance for reference have made well-educated estimates on their needs based on the most similar current projects that use Patroni. That's all covered, plus quite a significant amount of wiggle room in case we learn that EDB requires more cores.
