### ISSUE TITLE
Develop the protocol for teams to request egress rules

### ISSUE THREAD

**Issue by jleach** [BCDevOps/developer-experience#913]
## Story

As a security focused team, we need the pods in our namespace to exists in total isolation such that both ingress and egress can be controlled.

## Description 

Some teams (JAG/AG/OrgBook) are dependent on egress rules at the moment. They use them implement "total isolation" in such a way that if any pod in a given namespace was compromised it could not be used as a jump-point to gain access to additional systems. This level of functionality, if not available, will likely be an issue to these projects.

## Done When

- While egress rules are not self-serve we need a process in place where teams can request admins to implement such policy on their behalf;
- We need a longer term plan in place to get to the point were teams can serve serve egress rules.

**Comment by mitovskaol** [comment]
Since we have not had  any such asks since the OCP 4 Platform was built in fall 2020, i am going to close the ticket for now.
