### ISSUE TITLE
INC0049036 - OCP4 SILVER - Prometheus rules failing evaluation for over 5 minutes

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#929]
**Describe the issue**
SILVER cluster recently started generating AlertManager notifications stating Prometheus could no longer process up to 10 rules. 

**Additional context**
Red Hat case  ticket - https://access.redhat.com/support/cases/#/case/02865597

**Definition of done**
- [x] Derive root cause with vendor support's assistance.
- [x] Implement solution/work-around to resolve the issue.

**Comment by StevenBarre** [comment]
Friday Feb 12th
CHG0022893 - MCS SILVER - Drain and reboot MCS-SILVER-APP-04.dmz

Per RH, rebooted the server to see if errors would clear. They did temporarily, but returned on the 14th.

Tested deleting the `node-exporter` pod on an affected host and letting it re-create to see if that would fix the error. It did not.

The alert is now silenced while we await further direction from RH.

**Comment by wmhutchison** [comment]
Moving this to Blocked per previous comment. Ball's in the court of Red Hat to tell us how to proceed, will un-block when we have something more.

**Comment by wmhutchison** [comment]
No new information to report from this week's TAM meeting with Red Hat on this matter.

**Comment by wmhutchison** [comment]
Issue has not resurfaced - closing this ticket.
