### ISSUE TITLE
INC0049143 - OCP3 PROD - APP node ociopf-p-204.dmz has stopped responding

### ISSUE THREAD

**Issue by wmhutchison** [BCDevOps/developer-experience#930]
**Describe the issue**
Early morning on February 11th 2021 MCS on-call people were notified that one of the APP nodes in the Openshift 3.11 production cluster stopped responding entirely. An onsite technician was dispatched to hard reset the server since even ILOM was locked out. The hard reset worked and the node was brought back online but not yet back into service for workloads.

Continued work with vendor support on this matter to determine if root cause is possible to obtain, and if so, take appropriate steps to resolve.

**Additional context**

**Definition of done**
- [x] Bring server back into service.
- [x] Identify root cause with hardware vendor if possible.

**Comment by StevenBarre** [comment]
Friday Feb 19th
CHG0023060 - CITZ - 3.11 PROD - Vendor request to perform Hardware Validation on OCIOPF-P-204.DMZ

HPE asked us to boot the server into a testing mode and perform a hardware check. Check passed. Server booted again after the check fine.

Given that we have no indication of issues with the hardware and HPE support appears to be out of checks for us, we're leaving the node cordoned over the weekend and will return to service as part of OS patching next week.

**Comment by wmhutchison** [comment]
Per previous comment, the server was allowed to receive user work-loads once again after completing OS patching on February 23rd. No root cause determined for the original hardware lock-up, vendor has asked we keep an eye on it in case it happens again.

Closing this issue.
