### ISSUE TITLE
Upgrade Sysdig Agent

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#932]
**Describe the issue**
Update of Sysdig-Agent to current release.

**Definition of done**
- [x] ARO-PATHFINDER - Sysdig-Agent updated to current release
- [x] KLAB - Sysdig-Agent updated to current release
- [x] CLAB - Sysdig-Agent updated to current release
- [x] SILVER - Sysdig-Agent updated to current release
- [x] GOLD (Kamloops) - Sysdig-Agent updated to current release

**Comment by jefkel** [comment]
Included in this ticket will be an updated Configuration fix to ensure Prometheus scraping of the kube proxy is working.

**Comment by ShellyXueHan** [comment]
Here's the ticket tracking the issue, update details included. https://github.com/BCDevOps/developer-experience/issues/1015

**Comment by jefkel** [comment]
Agent release 11.1.2 validated and deployed to CLAB and KLAB.

Pending Production deployment PR's are ready for DXC in prod CCM repos.

**Comment by StevenBarre** [comment]
Completed
