### ISSUE TITLE
Deploy Migration Toolkit for Containers in KLAB and Silver

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#933]
As a Platform Services team member I want to evaluate the benefits that using the Migration Toolkit for app migration from OCP 3->OCP 4 can provide. 

As per [these instructions](https://docs.openshift.com/container-platform/4.5/migration/migrating_3_4/deploying-cam-3-4.html), deploy the toolkit in KLAB and Silver clusters.

**Comment by jefkel** [comment]
would recommend leveraging a migrationToolkit objectStore account/bucket (provision-able by @caggles ) once the installation is done, and it's time to configure.

**Comment by StevenBarre** [comment]
I believe this also needs to get deployed to the v3 cluster?

Also we should read https://redhat-cop.github.io/openshift-migration-best-practices/ for tips/tricks.

First one that jumps out at me is

> **When to use MTC**
>
> Ideally, you could migrate an application from one cluster to another by redeploying the application from a pipeline and perhaps copying the persistent volume data.
> 
> However, this might not be possible in the real world. A running application on the cluster might experience unforeseen changes and, over a period of time, drift away from the initial deploy. MTC can handle scenarios where you are not certain what your namespace contains and you want to migrate all its contents to a new cluster.
> 
> If you can redeploy your application from pipeline, that is the best option. If not, you should use MTC.

This is definitely a last ditch effort tool.

**Comment by mitovskaol** [comment]
@StevenBarre We found an abandoned project that could be used a test out with the tool.  So @jleach is ready to go once you install the tool in KLAB and in Silver. We will test the migration from OCP 3 to KLAB first and then from OCP 3 to Silver.

**Comment by StevenBarre** [comment]
Operator installed in OCP3 PROD and KLAB. Due to my VPN/Proxy setup, I can't access the web console however and have an INC open with our network ninjas. Other cluster admins can see if they can login though.

https://migration-openshift-migration.apps.klab.devops.gov.bc.ca/

TODO: Configure the tool to connect to the v3 cluster and add a OCS object store.

**Comment by StevenBarre** [comment]
Configured with access to the S3 bucket and Pathfinder cluster https://migration-openshift-migration.apps.klab.devops.gov.bc.ca/

**Comment by StevenBarre** [comment]
Over to @jleach to test in KLAB and evaluate before we install in Silver.

Note for everyone else, only Cluster Admins can use the tool, so you'll need to get DXC people to run this in Silver should it be needed.

**Comment by StevenBarre** [comment]
Deployed to Silver https://migration-openshift-migration.apps.silver.devops.gov.bc.ca/
/cc @mitovskaol
