### ISSUE TITLE
LTM: Add Quota totals

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#939]
**Describe the issue**
Expand the [metrics PR](https://github.com/bcgov-c/platform-tools/pull/31) to include a sum of the CPU/Memory Requests and Limits of the `compute-long-running-quota` in all projects.

**Definition of done**
- [ ] Tested in LAB
- [ ] Commits added to PR

**Comment by StevenBarre** [comment]
@jefkel does the description capture what we want for quotas? or are there other quotas we want measured too?

**Comment by jefkel** [comment]
it does (for the cluster capacity metrics)  I don't think we are tracking the build/cron metrics just yet (not sure it'll provide specific value yet)

**Comment by mitovskaol** [comment]
Looks like the work has been done and the ticket can be closed.
