### ISSUE TITLE
LTM: Graph CPU/MEM used % on master/infra nodes

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#941]
**Describe the issue**
Expand the [metrics PR](https://github.com/bcgov-c/platform-tools/pull/31) to include have a graph showing Master and Infra CPU and Memory Used %.

**Definition of done**
- [x] Tested in LAB
- [x] Commits added to PR
- [x] Create a change
- [x] Apply the change

**Comment by tmorik** [comment]
Checking Prometheus metrics that can be used for this task. Possibly it would be picked up from node-exporter rule metrics. :  https://prometheus-k8s-openshift-monitoring.apps.klab.devops.gov.bc.ca/rules#node-exporter.rules

**Comment by tmorik** [comment]
Tests on K/Clab have been done successfully.
 
PR has been created: https://github.com/bcgov-c/platform-tools/pull/90

**Comment by tmorik** [comment]
PR reviewed and merged to ocp4-base branch.

**Comment by tmorik** [comment]
Changes for each clusters:
```
CHG0032725 - Silver - 10/12/2021 10:00:00 AM
CHG0032731 - Gold - 10/12/2021 11:00:00 AM
CHG0032732 - Gold DR - 10/12/2021 12:00:00 PM
```

**Comment by tmorik** [comment]
New metrics have been added to Nagios.
