### ISSUE TITLE
Investigate necessity of DNS wildcard for Artifactory docker repos

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#949]
**Describe the issue**
We are looking to make it so the Artifactory operator can be installed on any cluster - including one where artifactory isn't installed (so the operator would point to an installation on a different cluster). As it stands right now, the operator needs access to the artifactory namespace so that it can create routes for docker repositories. The easiest way to eliminate this is to switch away from using docker repo subdomains. This ticket is to investigate the possibility of creating docker repos in artifactory without needing associated routes.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- [x] Installation of Artifactory in one of the lab clusters configured to allow the creation of docker repos without associated routes.
or
- [ ] Confirmation that the routes are necessary, along with documentation for why that is the case.

**Comment by jefkel** [comment]
Suggest that performance tests be done with removing the sub-domain route and verify performance of path-based routes for artifactory docker repositories.

**Cons**
- Path based is only supports docker v2
- Path based may have performance impacts with SSL based route (needs to be tested) 

**Pros**
- easier to create repositories from remote clusters (using current operator)
- Developer experience is consistent with other repositories (ie: similar experience to `docker.io/reponame/image:tag` naming)
- secret management is more straightforward (only 1 artifactory secret required, with a single repo URL)

**Comment by jefkel** [comment]
I believe the investigation has been completed with no operational service impacts.

Next steps captured in ticket #1137
