### ISSUE TITLE
BCbot is responding incorrectly to certain specific messages with an error.

### ISSUE THREAD

**Issue by caggles** [BCDevOps/developer-experience#956]
**Describe the issue**
BCbot responded to a message that it wasn't supposed to respond to. The response was:
```
Oops, and that’s an error: Cannot convert object to primitive value
```
I'm not sure exactly what triggers this because it is EXTREMELY rare for BCbot to respond to messages that it's not supposed to respond to. So the question is - what messages trigger this response and why?

**Additional context**
Heres is the message that originally triggered the error response: https://chat.developer.gov.bc.ca/channel/devops-ocp4-migration?msg=tMTdL38dgDPeg2mRk

**Definition of done**
-[ ] We are able to reproduce the error with some consistent understanding of what does and doesn't cause the response.
-[ ] BCbot no longer responds incorrectly to this type of message.

**Comment by mitovskaol** [comment]
@caggles Does this issue still occur?
