### ISSUE TITLE
Missing script for OpenShift SSO integration setup and configuration

### ISSUE THREAD

**Issue by ShellyXueHan** [BCDevOps/developer-experience#958]
**Describe the issue**
We had an incident from Prod OCP4 login via SSO and should consider completing the playbook for configuring SSO clients for ocp4.

Here's the full flow: https://github.com/BCDevOps/keycloak-admin/blob/master/keycloak_realm_builder/scripts/custom_usage/doc/ocp4-cluster-kc.md

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done
- [ ] update flow to the latest settings
- [ ] complete the playbook to include the setup
- [ ] testing

**Comment by mitovskaol** [comment]
@ShellyXueHan Is this still relevant?

**Comment by ShellyXueHan** [comment]
Nope, we should close this one. Also it'll be quite different by the time when we have settled on the SSO solution for our clusters.
