### ISSUE TITLE
Wildcard Certificate needed for artifactory docker repos

### ISSUE THREAD

**Issue by jefkel** [BCDevOps/developer-experience#96]
**Problem:**
Artifactory docker repositories are accessed using URL sub-domains that do not have a valid certificate.
*{reponame}*.artifacts.developer.gov.bc.ca

**Desired Outcome:**
Apply a wildcard certificate for *.artifacts.developer.gov.bc.ca to all of the existing docker repository route objects, and update the repo operator to ensure all new docker repositories get the same certificate.

**Comment by caggles** [comment]
Clecio said:

cailey.jones, we could setup https://github.com/bcdevops/certbot to automatically create/renew certs for all those docker routes

I'm gonna look into that as an option!

**Comment by lukegonis** [comment]
Update:

- iStore # 1010279 
- In progress
- I followed up with CITZIMBSD@gov.bc.ca asking if it is blocked on February 7, 2020 at 9:40 AM

**Comment by jefkel** [comment]
Update:
- Order still not being processed March 17, 2020 due to lost/missing second document.
- Luke following up

**Comment by tosazuwa** [comment]
Tolu to follow up with @jefkel regarding certificates status

**Comment by jleach** [comment]
@jefkel @caggles  This one seems like its going stale. Anything we can do to move it along?

**Comment by NickCorcoran** [comment]
OCIO Exemption was approved.  Email approval should be submitted with iStore request for cert.

**Comment by tosazuwa** [comment]
@caggles @jefkel , do we engage Pop now to help with the iStore order? Nick has recieved an approval

**Comment by jefkel** [comment]
@popkanjanakantorn do you need anything else? (Above?)

**Comment by caggles** [comment]
still blocked, going to talk to @lukegonis about this one asap.

**Comment by jefkel** [comment]
@caggles @lukegonis @mitovskaol Is this still being procured? Do we have an expected delivery date for the certificate yet?

**Comment by patricksimonian** [comment]
the iStore order was inadvertently cancelled and a new one was re-opened (being actions right meow)

**Comment by lukegonis** [comment]
SSL cert has been received, pending implementation
