### ISSUE TITLE
Migrate round 3 nodes from OCP3 to SILVER

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#982]
**Describe the issue**
Nodes 201, 202, 203, and 204 need to be drained and decommissioned. Then moved by DCM to the SILVER cluster racks, and connected to network and fiberchannel.

Since these nodes don't have 800G SSDs they will instead need to boot off a volume on the SAN.

**Definition of done**
- [x] CHG to drain the nodes of workload
- [x] CHG to remove the nodes from the cluster and decomission them
- [x] Work with network team to ensure new network switchports are configured and ready
- [ ] ~Work with Storage team to ensure SAN ports are ready and volume is created~
- [x] Work with DCM to unrack and rerack the hardware in new location
- [ ] ~Test and document process to get the nodes to boot from the SAN volume and bootstrap into OCP~
- [x] Validate nodes
- [ ] ~ Remove cordon and quarantine from nodes and add to the worker pool~
- [x] CHG to officially hand over nodes

**Comment by tbaker1313** [comment]
CHG0023296 - MCS PROD - Drained nodes 201-204 (February 25th)
CHG0023298 – decommission 4 3.11 PROD nodes (201-204) (February 26th)

**Comment by tbaker1313** [comment]
Process has started. DCM and Network teams are aware of their roles in this activity.

**Comment by tbaker1313** [comment]
Tickets for DCM and network are in progress.

**Comment by StevenBarre** [comment]
Network will configure switchports Tue Mar 9th

**Comment by StevenBarre** [comment]
After discussions with Matt, booting from SAN is not going to work. We therefore MUST use the existing 300G HDD in the servers. This will be a bit slower than the other servers with SSD, and will run out of image cache room much sooner. But should hold us over alright until Gluster is decommed and we can steal those SSDs.

Ran into some issues with iLO IPs and DNS which have now been resolved.

Appears the 10G network ports are still not connecting properly. Having DCM/Network investigate if we need new SFPs or cables or something.

**Comment by tbaker1313** [comment]
Working to get the network configured correctly. At this time we're experiencing network ports going up and down a bit. Have communicated with DCM and Network team so hopefully this can be resolved shortly. The first port of the first 2 port card and the MGT port on the built in 4 port are generally active, but missing 3 of the others.

**Comment by tbaker1313** [comment]
Network is now working correctly. Testing of routes and network is ongoing. Once that is completed will start to build and roll out the new silver nodes. Expected this can be completed by March 17th, some delays due to network and issues getting the dhcp working as intended.
