### ISSUE TITLE
Complete business model canvas

### ISSUE THREAD

**Issue by lukegonis** [BCDevOps/developer-experience#984]
**Describe the issue**
We don't know what our business model is, this activity will help us identify

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Business model canvas board

**Comment by marthaedwards** [comment]
Organize a workshop to create a Business Model Canvas with both platform services and the private cloud team. This includes:
-Setting up the session
-Research into the methods
-Building a custom board
-Facilitation planning

Outputs: 
Cleaned up version of the board
As a stretch goal - executive summary for Gen.
