### ISSUE TITLE
AQUA - familiarize with aqua deployment operator

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/developer-experience#987]
## Summary

I have no clue how aqua gets installed. Time to take a look!

## Definition of Done

- understand the installation process for aqua using the operator
- perhaps even installing it in Klab Manually?

**Comment by stewartshea** [comment]
There are no operators involved in Aqua rollout at this time. It's all deployed via CCM and straight k8s manifests.

**Comment by lukegonis** [comment]
Not a thing
