### ISSUE TITLE
Aporeto Enforcer blocking traffic from hostNetwork pods to k8s API | SPIKE

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#989]
**Describe the issue**
The new version of Aporeto is blocking traffic from pods with `hostNetwork: true` to the k8s API.

At first we thought this was intermittent, since it seems to only effect the router pods after hours/days of running. But further testing has shown that the issue is present at all times, and its just that the router software eventually dies and starts throwing errors.

**Additional context**
- https://supportcases.paloaltonetworks.com/apex/Communities_CaseDetail?id=5004u00002OULynAAH

**Definition of done**
- [ ] Stable router pods

**Comment by StevenBarre** [comment]
This appears to affect Sysdig Agents as well.

**Comment by StevenBarre** [comment]
Update from Aporeto

>Thank you again for providing all logs and helping us debug the problem.
Our developers established that the problem you are encountering is due to the enforcer experiencing an issue with DNAT rules. Work is underway to address this problem, but meanwhile they have come up with a workaround that should get you back to operational state, and you would not lose any functionality:
Can you modify your target network to exclude the API server IPs? 10.98.0.1/32 in KLAB and 10.96.0.1/32 in CLAB? You can do that with the Not operator ( !10.98.0.1/32). The exclusion of the API servers from the target network will instruct the enforcer protecting the API server to not examine the SYN,SYN/ACK handshake. You would still have protection for the API server thanks to the IP ACL rules in place (allowing PU to 10.98.0.1).

Justin Pye tested this out in KLAB/CLAB and confirmed it worked.

Change was then promoted to Silver. Tests show router can now reliably connect to the API. Sysdig agents in Silver also appear to have recovered.

**Comment by j-pye** [comment]
Are we stable now @StevenBarre and if so, can this be closed?
