### ISSUE TITLE
Deploy Sysdig Operator to Gold cluster through CCM

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#993]
Sysdig monitoring service will be available to the Ministry apps hosted in the Gold cluster. The implementation of the Sysdig operation will follow the same path as was implemented in Silver and described [here](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/861)

This task should only involve approving the PR  that contains the appropriate CCM ansible and k8s manifests, along with validating that the manifests apply properly through ArgoCD and the operator runs in the sysdig namespace. 

Definition of Done: 
- [x] The operator runs successfully in the same namespace as the sysdig agents in GOLD
- [x] A team can deploy a SysdigTeam CR inside of their tools namespace and will receive access inside of the Sysdig application

**Comment by StevenBarre** [comment]
Deployed via CCM. Just need someone to test.

**Comment by ShellyXueHan** [comment]
@StevenBarre I'll test it out in a bit after meetings! So for deploying the operator, are you following the steps [here](https://github.com/BCDevOps/platform-services/tree/master/monitoring/sysdig/operator)?

**Comment by StevenBarre** [comment]
Yup, the operator is already installed in GOLD, just needs testing that its working.

**Comment by ShellyXueHan** [comment]
Created sysdig team via CR and can confirm that i got the correct access level setup on sysdig.

**Comment by ShellyXueHan** [comment]
@StevenBarre can you also verify that you have `edit` access in sysdig team `shelly-team`?

**Comment by StevenBarre** [comment]
Confirmed.
