### ISSUE TITLE
Enable teams provision projects in GOLD

### ISSUE THREAD

**Issue by mitovskaol** [BCDevOps/developer-experience#996]
As a product teams with a mission critical app, I need to be able to request a project set provisioned in the Gold cluster of the Openshift 4 Platform through the OCP 4 Project Registry.

DoD:
- [ ] When a user logs into the Registry  and click Create, they should be able to select Gold Service (Gold/GoldDR). 

Additional Context:
The project entry form should include a message saying "Please contact Olena Mitovska to get approval for creating a project in the GOLD cluster as this cluster is reserved for critical applications, or those business applications that require maximum up time beyond highly available (99.95 vs 99.9), and all applications **must have a fully funded Product Team with dedicated DevOps resources to manage the app**. No provisioning requests will be processed without the alignment session with OIena first".

The confirmation emails should include the name of the cluster that the provisioning request was for.

**Comment by mitovskaol** [comment]
@yhfreeman @sbathgate  Please feel to covert this issue into EPIC if needed and create individual tickets to cover changes to different parts of the Registry (api, database and the provisioner bot).

**Comment by sbathgate** [comment]
Promoted to PROD Aug 23, first project provisioned in Gold / GoldDR Aug 25
