### ISSUE TITLE
OCP 4 Ops Monitoring MVP

### ISSUE THREAD

**Issue by StevenBarre** [BCDevOps/developer-experience#997]
**Describe the issue**
We need an basic monitor of the API set up. Similar to what we have for v3.

Create a service account, and set up an Active Nagios monitor to curl the API and fetch the list of nodes. Send uptime stats in a monthly report.

Code should support future expansion to other curl commands.

**Definition of done**
API GET Nodes monitor for
- [x] KLAB
- [x] CLAB
- [x] SILVER
- [x] GOLD

**Comment by StevenBarre** [comment]
Started on this but ran into a roadblock that I can't get to the Nagios Active cluster the same as the Passive cluster. I've entered a ticket for the tools team / network to look into, but may not be resolved this week. Moving to blocked.

**Comment by StevenBarre** [comment]
Wooo! Firewalls and DNS updated. Moving back to in progress.

**Comment by wmhutchison** [comment]
Steven not present, going to push this to Backlog for now until I can revisit it or Steven returns.

**Comment by StevenBarre** [comment]
Restarting work on this.

**Comment by StevenBarre** [comment]
Progress in https://github.com/bcgov-c/platform-tools/pull/48

Currently the traffic path is going through our corp proxy and then back in via SiS. This seems to be slow and unreliable (most likely the proxy). Waiting on some networking changes to allow going direct from Nagios to the F5 and bypass the proxy.

**Comment by StevenBarre** [comment]
Waiting on some SNAT changes scheduled for Tues the 24th to rollout to other clusters, but working in KLAB.

![image.png](https://images.zenhubusercontent.com/5d544a7a5faedc627998cd85/2f423b37-046a-4c1b-9046-2ef5d5cc831f)

**Comment by StevenBarre** [comment]
This is now implemented for all clusters.
